iron-fish/ironfish

- ironfish-cli/src/commands/accounts/pay.ts
Looks like the same relative path issue we had with the `accounts:balance` command.
> Fix relative import in pay command

- .github/workflows/deploy-brew.yml
The Deploy Brew workflow fails with "Set AWS_ACCESS_KEY_ID before running deploy-brew.sh". Looks like we need to pass those env vars in via the deploy-brew.yml file.
> Add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to brew workflow

- .github/workflows/deploy-node-github.yml
We were using docker.pkg.github.com, but that doesn't support public anonymous image reading, so this updates the Github Action deployment yaml file to point to ghcr.io instead.
> Point Github Docker deployment to ghcr.io

- .github/workflows/deploy-node-github.yml
There's an extra `/ironfish` on the Docker registry URL -- This removes it.
> Remove extra path from Docker registry url

- ironfish-cli/README.md
Adding some clarity to the ironfish-cli README, then will replace the onboarding docs 'build from source' instructions with links to the Github READMEs.
> Add explanation of start and start:once to ironfish-cli README

- ironfish/src/captain/anchorChain/blockchain/fixtures/Blockchain_should_notes_to_trees_1
- ironfish/src/captain/anchorChain/blockchain/fixtures/Blockchain_should_notes_to_trees_2
- ironfish/src/captain/anchorChain/blockchain/fixtures/Blockchain_should_notes_to_trees_3
- ironfish/src/captain/anchorChain/blockchain/fixtures/Blockchain_should_notes_to_trees_4
- ironfish/src/captain/anchorChain/blockchain/fixtures/Blockchain_should_notes_to_trees_5
- ironfish/src/captain/anchorChain/blockchain/index.test.ts
We had a bug where when a re-org happened, the note / nullifier trees
were trimmed too far back. The forking points notes / nullifiers were
also removed. This adds a test to make sure that the trees are
updated on a linear add, but also properly pruned and re-added during a
re-org.
This replaces the test that was in the file previously. Fixtures have
been updated.
> Add test for trees being updated

- ironfish/src/fileStores/config.ts
- ironfish/src/network/peers/peerConnectionManager.ts
This is causing the node to freeze. As soon as you get the
bootstrap node's peer list, you try to issue 60+ outbound connection attempts
which is too many and causes node to deadlock.
> Limit connection attempts per network eventloop

- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peerManager.ts
The message wasn't encoded when disconnecting users when you are at your max connections. This causes a crash because you can't send an object over WebSocket, you need to encode it to a string, or a buffer.
We'll look at cleaning up the code in another PR so that our wrapper connection only ever gets emitted from WebSocketServer, so this type of issue cannot happen again in the future.
Fixes IRO-635
> Encode message when disconnecting user

- ironfish-cli/package.json
- yarn.lock
This is being used by the new backup command
```
docker exec -i current_ironfish-node_1 /usr/src/app/bin/run ....
Error: Cannot find module 'uuid'
Require stack:
- /usr/src/app/build/commands/backup.js
- /usr/src/app/node_modules/@oclif/config/lib/plugin.js
- /usr/src/app/node_modules/@oclif/config/lib/config.js
- /usr/src/app/node_modules/@oclif/config/lib/index.js
- /usr/src/app/node_modules/@oclif/command/lib/command.js
- /usr/src/app/node_modules/@oclif/command/lib/index.js
- /usr/src/app/bin/run
Code: MODULE_NOT_FOUND
```
> Install missing package UUID in CLI

- ironfish/src/captain/anchorChain/blockchain/index.ts
- ironfish/src/captain/anchorChain/strategies/index.ts
- ironfish/src/captain/index.ts
- ironfish/src/captain/testUtilities/strategy/testVerifier.ts
- ironfish/src/consensus/index.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/strategy/index.ts
- ironfish/src/testUtilities/verifier.ts
Part of the great repo cleanup, strategy will be here too eventually. They'll both be deleted to form new modules that make up the protocol / consensus.
> Move verifier from captain to consensus

- ironfish-http-api/README.md
- ironfish-rosetta-api/README.md
- Fixed typos on tcp port in READMEs 
- Amended the psql step to include db name 
- My editor/formatter added the new lines (which didn't change the appearance of the rendered README)
> Fixing typos on READMEs for tcp port

- ironfish/src/memPool/memPool.ts
Updates the logger tag to `mempool`, since we renamed the class from `transactionPool` to `memPool`.
> Rename transactionpool logger tag to mempool

- ironfish/src/memPool/memPool.ts
This is the main log that shows up during normal operation of a node with the default log levels set, I think it's okay to move it to debug since it's not as user-readable.
> Change transaction log level to debug

- ironfish/src/network/peers/connections/connection.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/peer.test.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/testUtilities/helpers.ts
The webRtcConnection would occasionally be in state `CONNECTED`, but then throw an exception when sending a message. This doesn't seem like a logic error in our code, since the connection must receive an Identity message from the opposite party before setting the connection to 'CONNECTED'.
This PR wraps the `send` in a try/catch and sets the connection to `DISCONNECTED` if it throws an error. I added some tests for it, and it falls back to WebSockets if available.
One issue here is it doesn't propagate the failure to send if the latency simulator is enabled, but that's only used for latency-related testing, so I'm less concerned about it.
Fixes #16
> Disconnect WebRTC connection if send throws an error

- ironfish-cli/src/commands/config/set.ts
- ironfish/src/rpc/routes/config/setConfig.test.ts
- ironfish/src/rpc/routes/config/uploadConfig.ts
Allows for updating the bootstrapNodes config with config:set, like so:
```
ironfish config:set bootstrapNodes "test.bn1.ironfish.network,examplenode.com"
```
Added an example for it to `ironfish config:set --help`.
Fixes #40﻿
> Allow setConfig to parse string arrays

- ironfish/src/blockchain/blockchain.ts
If you failed to add, it would not tell you why. This is very
frustrating from an API perspective. Return the reason now.
> Return add fail reason in chain.addBlock

- ironfish-cli/src/commands/start.ts
Changed the text of the `--bootstrap` help to indicate that it accepts a list of comma-separated nodes.
Additionally, there was an error that referenced the old config value of `bootstrapNode`, so I updated it to be applicable to both the config and the flag values.﻿
> Clarify that bootstrap flag supports multiple nodes

- ironfish/src/captain/captain.ts
- ironfish/src/mining/director.test.slow.ts
- ironfish/src/mining/director.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/node.ts
- ironfish/src/testUtilities/mocks.ts
This removes captain usage from mining director, and moves the mining
event it had on it, into the director itself.
> Remove captain from mining director

- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/blockSyncer.test.ts
- ironfish/src/blockSyncer.ts
- ironfish/src/blockchain/block.test.ts
- ironfish/src/blockchain/blockchain.test.perf.ts
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/captain/captain.ts
- ironfish/src/captain/testUtilities/helpers/anchorChain.ts
- ironfish/src/captain/testUtilities/matchers/blockchain.ts
- ironfish/src/captain/testUtilities/strategy/TestStrategy.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/network/messageRouters/fireAndForget.test.ts
- ironfish/src/network/messageRouters/gossip.test.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/node.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
- ironfish/src/rpc/routes/chain/getBlock.ts
- ironfish/src/strategy/index.ts
- ironfish/src/strategy/strategy.ts
- ironfish/src/testUtilities/fixtures.ts
- ironfish/src/testUtilities/mocks.ts
There shouldn't be so many references to a serializer that should be once. This will be deleted when we move over to binaryh based serialization using bufio in the future, anyway.
* Add strategy.blockSerde
* Remove all instantiation of BlockSerde except for one in strategy
* Remove captain from passing into PeerNetwork, and now pass in Strategy and Chain to get blockSerde
* Remove lots of now invalid useds of Captain across the codebase
> Remove captain.blockSerde

- ironfish-cli/src/commands/start.ts
Changes the loading text when running `start` on a node for the first time from "Creating the genesis block" to "Loading the genesis block". I'm open to a different word, but I saw a question about "creating" specifically in Discord.﻿
> Clarify wording of genesis block loading phase

- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/strategy/index.ts
- ironfish/src/strategy/strategy.test.slow.ts
Incoming transactions with negative fees indicate miner rewards. They'll still pass proof verification, but they should only ever appear on blocks by the miners who created them, not gossiped via the NewTransaction message.
Fixes IRO-650﻿
> Reject incoming transactions with negative fees

- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
Fixes a bug where passing `-b ''` to the start command fails to filter out the empty string from the command flag and crashes when starting the PeerNetwork.﻿
> Fix passing empty string bootstrap node to start command

- ironfish/src/assert.ts
- ironfish/src/blockSyncer.ts
- ironfish/src/blockchain/__snapshots__/nullifiers.test.ts.snap
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/blockchain/blockheader.ts
- ironfish/src/blockchain/nullifiers.ts
- ironfish/src/blockchain/target.ts
- ironfish/src/serde/index.ts
- ironfish/src/serde/serdeInstances.ts
- ironfish/src/strategy/index.ts
- ironfish/src/workerPool/worker.ts
The main fix here is to cap the size of blocksForProcessing, since it can grow unbounded. Also made a change to avoid allocating a new Serde class when functions are called, most notably the transactionSerde and the Serdes in BlockHeader.
- Limit new Serde instance allocations
- Limit the number of entries in blocksForProcessing
> Improve memory usage of block syncer

- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/workerPool/messages.ts
- ironfish/src/workerPool/pool.test.slow.ts
- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/worker.ts
When Buffer instances get passed across the worker thread boundary using postMessage, they're copied using the structured clone algorithm and come out on the other side as Uint8Array. This resulted in putting Uint8Arrays into a type that we thought was a Buffer, so in the end the serialization didn't match up. This didn't reproduce in tests originally because they mostly run with the worker pool turned off, so none of the requests/responses were passed across postMessage boundaries.
> Fix worker pool typing transactions as Buffer instead of Uint8Array

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
- ironfish/src/rpc/routes/chain/getBlock.ts
- ironfish/src/rpc/routes/chain/getChainInfo.test.ts
- ironfish/src/rpc/routes/chain/getChainInfo.ts
- ironfish/src/rpc/routes/chain/utils.ts
- ironfish/src/strategy.ts
- ironfish/src/testUtilities/fake/matchers/blockchain.ts
- ironfish/src/testUtilities/fake/strategy.ts
This removes all the serdes from various components. Ultimately we will delete all these "serdes" which are just serializers by a different name.
> Remove serdes from blockchain, verifier

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/merkletree/merkletree.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/node.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
- ironfish/src/rpc/routes/chain/getBlock.ts
- ironfish/src/rpc/routes/chain/getChainInfo.test.ts
- ironfish/src/rpc/routes/chain/getChainInfo.ts
- ironfish/src/rpc/routes/chain/utils.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/strategy.ts
- ironfish/src/testUtilities/fake/helpers/blockchain.ts
- ironfish/src/testUtilities/fake/helpers/merkleTree.ts
- ironfish/src/testUtilities/fake/matchers/blockchain.ts
- ironfish/src/testUtilities/fake/strategy.ts
This PR moves merkle tree construction into blockchain. The constructor now constructs the trees, as it should because the blockchain is dependent on them and the only one who uses them.
To do this, it also removes MerkleTree.new() and Blockchain.new() static functions
> Move merkle tree construction into Blockchain

- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/peer.ts
NewBlock gossip messages should be optional, though they may not be right now. If NewBlock messages are missed, our block syncer should be able to proactively detect when it's missing blocks and seek them out from peers.
Accomplishes two things:
* Decreasing memory consumption during high volume of NewBlock messages. The outgoing buffers for the WS and WebRtc connections were backing up with messages to forward.
* Improving network congestion -- this should indirectly prioritize sending other messages over NewBlock messages, which should at least prevent the case where a node is trying to respond to an RPC call, but the socket's buffer is backed up with NewBlock messages.
Fixes IRO-655
> Drop NewBlock gossip messages if connections have buffered messages

- ironfish-cli/src/commands/status.ts
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/consensus.ts
- ironfish/src/node.ts
- ironfish/src/rpc/routes/node/getStatus.ts
https://linear.app/ironfish/issue/IRO-658
The blockchain now has an approximation of weather it's synced or not based on if the heaviest head it has is within 60 seconds. This adds 3 new concepts to Blockchain
* Blockchain.synced: boolean
* Blockchain.onSynced: Event
* Blockchain.head: BlockHeader
> Add synced detection to blockchain

- ironfish-cli/src/commands/start.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/consensus.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/director.test.slow.ts
- ironfish/src/mining/director.ts
- ironfish/src/node.ts
- ironfish/src/rpc/routes/node/getStatus.ts
https://linear.app/ironfish/issue/IRO-657
This stops the miner from mining when we aren't synced, but allows a
user to force mining to occur using --forceMining in `ironfish start`
> Only mine when we are synced unless forced

- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/workerPool/pool.test.slow.ts
- ironfish/src/workerPool/pool.ts
Adds a message queue to the worker pool class. The queue message limit is only optionally enforced right now, since our code probably will break in unexpected ways if we reject the worker pool Promises.
The NewBlock handler will drop incoming blocks if the message queue is full. This should help with memory growth as well.
Fixes IRO-656
> Add messageQueue to workerPool

- README.md
- ironfish-cli/Dockerfile
- ironfish-http-api/Dockerfile
- ironfish-rosetta-api/Dockerfile
- ironfish-wasm/build.js
This speeds up builds significantly, since using `cargo install` compiles wasm-pack locally. It also might simplify the dependency installation process on Windows (not certain on that though).
> Install wasm-pack from wasm-pack website

- .github/workflows/rust_ci.yml
Codecov recently had a security issue with their bash script used to upload coverage -- The Github action used the bash script, and added checksum verification in a recent version: https://github.com/codecov/codecov-action/releases
> Update codecov action to 1.4.1

- ironfish/src/blockSyncer.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/rpc/routes/node/getStatus.ts
- ironfish/src/utils/bench.ts
- ironfish/src/utils/index.ts
Previously the block syncer was measuring add speed, but now its being
measured by the block chain so all adds are bench marked.
> Move block syncer add speed to blockchain

- ironfish-cli/src/commands/peers/list.ts
Adds a `sort` flag to the `peers:list` command that's set to sort the peers list by connection state by default. We'll probably want to do a more complex sort later -- I'm guessing this sorts lexicographically.
> Sort the peers list by connection state by default

- ironfish/src/fileStores/config.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/node.ts
Adds a config value to enable the block syncer, defaulted to true. When set to false, the node performs no action when receiving NewBlock and NewTransaction messages, and never sends block request messages to other nodes.
Further additions here would be to add a field to the IDENTIFY message to indicate whether the node syncs blocks, although with upcoming syncer changes, peers shouldn't be sending block requests to nodes without knowledge of which blocks they have.
This config value is only used for testing and may be removed in the future.
> Add enableSyncer config setting

- ironfish-rust/src/errors.rs
- ironfish-wasm/Cargo.lock
- ironfish-wasm/Cargo.toml
- ironfish-wasm/src/lib.rs
- ironfish-wasm/src/panic_hook/mod.rs
- ironfish-wasm/src/wasm_structs/errors.rs
- ironfish-wasm/src/wasm_structs/mod.rs
- ironfish-wasm/src/wasm_structs/note.rs
- ironfish-wasm/src/wasm_structs/note_encrypted.rs
- ironfish-wasm/src/wasm_structs/spend_proof.rs
- ironfish-wasm/src/wasm_structs/transaction.rs
- ironfish-wasm/src/wasm_structs/witness.rs
Changes most Wasm functions to return `Result`s, which allows us to intercept Rust errors and return a JS error from Wasm. 
Also replaces console_error_panic_hook with a panic_hook that throws a more descriptive error directly in the case that something somewhere does `panic` or `unwrap` an Error. The previous error had the generic text `RuntimeError: unreachable executed`, but the message logged from console_error_panic_hook was more useful. In practice, this shouldn't be used often since it's common in Rust to return Result rather than panic or unwrap Results.
> Return Result from Wasm functions

- ironfish-cli/bin/run
By default, the segfault stacktrace filename will have date/time info, so if running a node that auto-restarts on crash, it has the potential to fill up disk space.
This makes the crashfile name constant so it'll overwrite the previous file if it exists.
> Log to explicit file if node segfaults

- ironfish-cli/Dockerfile
- ironfish-cli/scripts/entrypoint.sh
The WebRTC package is currently segfaulting from time to time, and if your container is set to automatically restart, it can fill up space in the container's root volume with core dumps.
We're planning to address the segfaults coming from the WebRTC package, but this script should disable core dumps to reduce disk consumption for now.
> Disable core dumps in Docker image

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/blockchain/index.ts
- ironfish/src/index.ts
- ironfish/src/syncer.ts
This fixes a bug where you get stuck trying to sync an orphan block
island. It's because some how orphan block islands are being added to
the database, even though were syncing left to right now. The issue is
once this happens, you will find an ancestor on the island, and try to
sync from there. This is slower, but will now not consider island blocks
a cache hit.
Note that this can all be deleted once we remove graphs, remove adding
islands from blockchain.
> Fix ancestor search considering islands cache hit

- ironfish-cli/bin/run
segfault-handler seems to cause crashes on Windows, or at least spams the logs with segfaults that don't always crash the process. After disabling it on Windows, the node appears to run stably.
> Disable segfault-handler on Windows

- ironfish-cli/src/commands/peers/list.ts
Changed sort to 'o' since I think its less common to change this. A new option for sequence will be `s` coming soon.
> Change sort letter from 's' to 'o'

- ironfish/src/network/messageRouters/gossip.test.ts
- ironfish/src/network/messageRouters/gossip.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/syncer.ts
Before there was no way to abort the gossip, now we can abort the gossip
by returning true or false from a gossip handler.
> Abort gossip by having handlers return boolean

- config/eslint-config-ironfish-react/package.json
- config/eslint-config-ironfish/package.json
- ironfish-cli/package.json
- ironfish-http-api/package.json
- ironfish-rosetta-api/package.json
- ironfish/package.json
- package.json
- yarn.lock
Updates the openapi-generator-cli package to attempt to fix an axios dependabot warning (this is just a dev CLI tool, so not a vulnerability, but should clean up the git logging when pushing branches).
Also removes node-forge from the package resolutions, since yarn seems to resolve it to the updated version now.
> Fix dependabot suggestions

- ironfish-cli/src/commands/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/node.ts
Adds a --workers flag to the `start` command, as well as a `nodeWorkers` config value. This sets the number of workers in the worker pool to create -- since each worker requires a few hundred MB of memory, this can be useful for reducing memory use on systems with many CPU cores.
> Add --workers and nodeWorkers config

- ironfish-cli/src/commands/miners/start.ts
- ironfish/src/mining/miner.test.ts
- ironfish/src/mining/miner.ts
Add a `--threads` option to the `miners:start` command to allow for mining on multiple cores without running separate instances of `miners:start`. The thread pool was already in place, just not configurable.
> Add --threads to miners:start command

- ironfish-cli/src/command.ts
When running through `yarn start:js`, the signal event handlers are firing twice. We intended to unbind them after the first time they fire, but since we used `.bind` to add them, the unbind wasn't working. This switches to using `process.once` (and updates types as necessary), and also checks the `closing` flag so if multiple signals fire, we don't try to close again.
> Fix signals firing twice when running through yarn

- ironfish/src/network/peers/connections/webSocketConnection.ts
I noticed that sometimes inbound messages will continue to fire event handlers even after we've called `close` on WebSocketConnection. I unbound all the event handlers on close, and this exposed another issue where close throws an error if the connection is still establishing, so I wrapped that in a try/catch.
I haven't noticed the same thing with WebRtcConnection, so I left that as-is.
> Unbind WebSocket event handlers when closing the connection

- ironfish/src/account/accounts.ts
`aborted` wasn't getting set to true on ScanState, so scans weren't aborting as expected. Also includes a few refactors:
- Remove `running` from ScanState -- it doesn't seem to be used
- Return runningPromise directly from wait()
> Fix abort() not setting aborted in ScanState

- ironfish/package.json
- yarn.lock
The version is pinned at this commit: https://github.com/iron-fish/simple-peer/commit/c69822cabbfbf2a110726c168056e43ac4f4be9d
It's based off of v9.11.0, and has two commits to address the following issues:
* Avoid segfault when calling RTCPeerConnection.localDescription
* Change "Ignoring unsupported ICE candidate" from console.warn to a debug log 
Fixes #146
Fixes #145
> Switch simple-peer to iron-fish fork

- ironfish-rosetta-api/src/services/Network.ts
- ironfish-rosetta-api/src/syncer/Syncer.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/routes/chain/getChainInfo.test.ts
- ironfish/src/rpc/routes/chain/getChainInfo.ts
This makes it so you don't need to pass an empty object in, you can just
pass nothing. This RPC api takes no arguments.
> Dont require passing args into getChainInfo

- ironfish/src/syncer.ts
The first commit just cleans up some code now that the block chain has been refactored.
The second code stops syncer peers from being disconnected if they send a block we already have, which they shouldn't, but wasn't possible until the block chain refactor.
> Dont kick peers from sending duplicate blocks

- tools/docker-compose.yml
Adding this option can help with segmentation fault errors and memory allocation problems on machines with low-RAM
#147
> Add restart option to docker-compose file

- ironfish/src/syncer.ts
it was stopping syncing when we hit a duplicate, instead we should keep syncing as long as the blocks are valid, and in sequence.
> Fix stop syncing when we hit a duplicate

- ironfish-cli/src/commands/status.ts
- ironfish/src/rpc/routes/node/getStatus.ts
```
Node:                 STARTED
P2P Network:          CONNECTED In: 0 B/s, Out: 0 B/s, peers 22
Blocks syncing:       SYNCING @ 0.48 blocks per seconds | avg time to add block 47.67 ms
Blockchain:           SYNCED, HEAD 000001b726e59c33dcbc74eca13809292e311aae90b38cb247e9dab027b88a12 (74049)
```
> Add peers count to ironfish status

- ironfish/src/platform.ts
We were slicing the last 8 instead of the first 8, which makes nothing appear in the agent.
> Fix agent not specifying git hash

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/syncer.ts
This adds the peer banning system by identity. Right now the ban list is
not persisted, and no top of that if a peer restarts they get a new
identity.
Also all verification errors have instant ban score, I'll discriminate
on those later and make them worth different values.
> Add peer banning system

- ironfish/src/syncer.ts
We were saying the blocks were added so they werent getting logged as
skipped. Then when it logged those blocks, it would never print
because orphan and duplicate blocks were being considered added.
>     Fix counting skipped blocks in syncer

- ironfish-cli/src/commands/peers/list.ts
Before, disconnected and connecting peers would show up. Now by default,
only connected peers show up. You can use --all to now show all
peers.
> Filter only connected peers from peers:list

- ironfish/src/network/version.ts
Were doing this because people on the old GIT version were not behaving
properly, and we need to exclude them from the network. They are sending
back random hashes at a requested sequence, rather than at their
heaviest chain.
> Bump protocol version to 3

- ironfish-cli/src/commands/accounts/import.ts
Provide an interactive experience to the end user if no importPath is specified when account:import is called on the command line. 
Provides potential fix for https://github.com/iron-fish/ironfish/issues/20
> Support interactive import in accounts:import 

- ironfish/src/blockchain/blockchain.ts
This function doesn't seem to be used anywhere, so seems safe to remove it.
> Remove unused getHeadersFromInput fn from blockchain

- ironfish-cli/src/commands/chain/export.ts
- ironfish-cli/src/commands/chain/readdblock.ts
- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.old.test.ts
- ironfish/src/blockchain/blockchain.test.perf.ts
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/consensus.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/mining/director.test.slow.ts
- ironfish/src/mining/director.ts
- ironfish/src/node.ts
- ironfish/src/primitives/block.test.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
- ironfish/src/rpc/routes/chain/getChainInfo.test.ts
- ironfish/src/rpc/routes/chain/utils.ts
- ironfish/src/rpc/routes/faucet/giveMe.test.ts
- ironfish/src/rpc/routes/node/getStatus.ts
- ironfish/src/sdk.ts
- ironfish/src/syncer.test.ts
- ironfish/src/testUtilities/fake/helpers/blockchain.ts
- ironfish/src/testUtilities/helpers/blockchain.ts
- ironfish/src/testUtilities/nodeTest.ts
- ironfish/src/testUtilities/routeTest.ts
- package.json
* Removes node.seed() and moves the contents into chain.open(). Added an `autoSeed` option to help the outdated jest tests pass.
* Changes chain.head, chain.latest, and chain.genesis into properties that throw if their backing field is null. These should typically only ever be null if the chain hasn't been initialized with the genesis block, then should be set after that.
> Move seed into blockchain and make head non-null

- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
Print a warning and don't let the user start the node if its corrupt
> Prevent node from starting up if the DB is corrupt

- ironfish/src/syncer.test.ts
- ironfish/src/syncer.ts
Bans peers if they send an empty response to GetBlocks. Since we only make the request with block hashes we already asked them about, and GetBlocks includes the block you requested, this should indicate a bug if it happens.
> Ban peers that send empty responses to GetBlocks

- ironfish/src/network/messageRouters/rpc.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.ts
Also fixes a few additional issues I ran into when testing the banning:
- Throw an error when banning the peer
- Drop RPC responses if peer is no longer connected
- Fix typing of neverRetryConnecting
> Increase peer banscores when sending invalid limits in block/hash requests

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/transaction.ts
- ironfish/src/storage/levelup/transaction.ts
We had one transaction / lock around blockchain.addBlock(), that if
rolled back, would leave dirty in memory state. To solve that
temporarily, we added a new IDatabaseTransaction.update() function which
updates the database but does not release the lock. This allows us to
commit state to the DB without releasing locks.
Alternatively, we can look at other solutions in the future where
transactions can be moved downwards to the things that need to be
atomic.
> Commit addBlock state after each DB operation

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/mining/__fixtures__/director.test.slow.ts.fixture
- ironfish/src/mining/director.test.slow.ts
The trees were never being verified here, so now we verify and abort the
block add if it isn't valid.
> Verify block matches trees in addBlock()

- ironfish/src/network/peerNetwork.ts
- ironfish/src/syncer.ts
We should only gossip blocks when we added them, because if we gossip a
block, it signals to others that we also have that block on our chain.
It's useful because if someone gets our gossip block, and its an orphan,
they will want to download the chain from us to that oprhan. So if we
gossip without adding, then that won't work.
Many coins distinguish this as announce vs broadcast, where announce
tells people we have it, and broadcast gossips it without indicating we
have it or not. Announce sends entire hash, broadcast sends entire
block.
If you look at the code, there is one situation here where we have the
block but we don't gossip it, and that's when it's a duplicate and we
already have it. At that point we don't regossip it out. We can
determine if we should be gossiping it out later …
> Dont gossip blocks when we don't add the block

- ironfish/src/network/peers/peer.ts
We don't have time to look into and fix these right now, and they're
disturbing users.
> Change log for sending to not connected peers

- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
The brokering peer may no longer be connected when we're attempting to send a signal message through it. We should look up a brokering peer as needed when a new signal message needs to be sent out. This should fix the "Attempting to send a signal message to peer in state CONNECTING/DISCONNECTED" logs.﻿
> Look up brokering peer before sending signal

- ironfish/src/syncer.ts
I think this is preventing syncing from handling gossips while were in
the middle of syncing orphan chains from others.
> Dont drop gossip messages if you are syncing

- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peerManager.ts
The time needed `Date.now` to be added. I pulled the logic into a central place to make it easier to change as well.﻿
> Fix disconnectUntil time in signal and signal request responses

- ironfish-cli/src/commands/config/get.ts
- ironfish-cli/src/commands/config/set.ts
Allow node connections over TCP RPC
> feat(ironfish-cli): Support TCP RPC for `config:get` and `config:set`

- ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/testUtilities/matchers/blockchain.ts
This modifies it to not curry the exceptions up through the addBlock
call, but instead throw verifyError() to properly abort the exception
and not worry if if the exception is aborted, or committed. It's always
aborted because of the exception.
> Use exceptions for aborting addBlock

- ironfish/src/assert.ts
- ironfish/src/blockchain/__snapshots__/blockchain.old.test.ts.snap
- ironfish/src/blockchain/blockchain.old.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/testUtilities/helpers/blockchain.ts
* Update `makeBlockAfter` to check the `reason` instead of `valid` flag
* Remove `looseNotes` and `looseNullifiers` from the `Blockchain` class
* Removed tests that were referencing `looseNotes` and `looseNullifiers`
* This is temporary, but skipping tests that use `hasValidSpends` in `blockchain.old.test.ts`. These tests will be moved over to the verifier and create block fixtures instead of fake blocks
> refactor(ironfish): Remove usage of `looseNotes` and `looseNullifiers`

- ironfish/src/blockchain/blockchain.ts
This should be the hash of the connected block rather than the previous block.
> Fix reconnect updating the chain head to the wrong hash

- ironfish/src/merkletree/merkletree.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/database.ts
- ironfish/src/storage/database/transaction.ts
The database code runs transaction handlers immediately and doesn't block them until they reach a database call, so logic in the transaction handlers that's dependent on external state could be incorrect. We were seeing issues that seemed to stem from this because we forgot to pass in the transactions in all cases, but it seems safer for now to lock around the entire transaction handler and reduce the amount of work being done inside of transaction handlers if possible.
> Lock database before executing transaction handlers

- README.md
There was a question about this in Discord -- I feel like it's slightly more clear / easier to search for tutorials to say `PATH environment variable` rather than just `path`.
> Clarify PATH in README

- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.ts
So these errors are used to catch chain corruption, but now that we
fixed chain corruption bugs they are triggering in valid instances. Our
account head updates, but doesn't lock so the chain can be modified
while were iterating due to a reorg. This will cause accounts to
crash because these validation check that we should be able to validate
the entire expected range.
So in accounts it's fine if we have to abort due to a reorg. Honestly
long term we can consider removing these errors once this is polished
and we can be sure there are no more chain corruption issues for sure.
> Make iterate errors optional

- ironfish-cli/src/commands/reset.ts
We don't want to auto seed here so we dont crash when we are just trying
to pull accounts out of an old version.
> Reset crash fix by not autoseeding 

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/blockchain/schema.ts
https://linear.app/ironfish/issue/IRO-706/warn-users-to-delete-db-from-betanet-upgrades
DONT MERGE THIS until we are ready to release to testnet.
This adds a hack that forces users to delete their database with a good
understandable error that will reduce questions in discord.
> Force users to wipe DB from old version

- ironfish-cli/src/commands/reset.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/node.ts
There are instances where we want to open the DB without running any
upgrades. This introduces a new upgrade argument to accounts and
blockchain open() methods. It only checks for mandatory upgrade when
true is passed.
Later we'll remove this in favor of a better system when we have time
and have added DB checks.
> Fix ironfish reset by not checking upgrade

- ironfish-http-api/scripts/build.sh
The issue here is that its copying the node_modules from MAC which is
not compatible on windows. This will cause it to run the GYP which
builds on the actual linux docker container.
> Remove node modules to build locally on linux

- ironfish-http-api/Dockerfile
- ironfish-http-api/scripts/build.sh
- ironfish-rosetta-api/Dockerfile
- ironfish-rosetta-api/scripts/build.sh
Both http api, and rosetta api build scripts were using
--ignore-scripts which prevent native modules from being built. We
copied the solution from ironfish-cli which removes the pre and post
scripts which is the intended result of using --ignore-scripts to begin
with but still allows the native module building scripts to be built.
> Remove ignore-scripts from api builds

- ironfish/src/merkletree/merkletree.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/store.ts
- ironfish/src/storage/database/types.ts
- ironfish/src/storage/levelup/store.ts
Cleaning up some logic for constructing a key path for the store
> refactor(ironfish): Remove `keyPath` from store and `KnownKeys` type

- ironfish-cli/src/commands/chain/repair.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/merkletree/merkletree.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/database.ts
- ironfish/src/storage/levelup/database.ts
- ironfish/src/storage/levelup/transaction.ts
This just removes the two arguments to `IDatabase.transaction()` and `IDatabase.withTransaction` called `scope` and `type.`. You may see some other changes because it reduces 1 level of indent, so now the code. lines all shift.
These were never used. They were going to be used for the web when we
introduce IndexDB, but it's not necessary because we can just use the
code the way it is now, there.
> Remove transaction scope and type

- ironfish/src/account/accounts.ts
https://linear.app/ironfish/issue/IRO-728/dont-rebroadcast-transactions-if-synced-is-false-on-the-blockchain
We don't wanna rebroadcast while were downloading blocks
> Dont rebroadcast transactions if not synced

- ironfish/src/account/accountsdb.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/merkletree/merkletree.test.ts
- ironfish/src/merkletree/merkletree.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/database.ts
- ironfish/src/storage/database/store.ts
- ironfish/src/storage/database/types.ts
- ironfish/src/storage/levelup/database.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/testUtilities/fake/helpers/blockchain.ts
- ironfish/src/testUtilities/fake/helpers/merkleTree.ts
https://linear.app/ironfish/issue/IRO-699/db-versions-and-migration-error
This adds a new mechanism so we can throw errors when database schemas
change. It will now enforced the DB version and a reset in a less hacky
way. A simple global database version is stored in the DB, and specified
to `db.upgrade(version)`.
If the version mismatches, then an error is thrown. If you are writing a
migration, you can avoid calling this method to run your migration logic
on old code.
> Add database version and migration errors

- ironfish-http-api/scripts/build-docker.sh
- ironfish-http-api/src/index.ts
The command just logs and creates a new server, which would have
caught the last error we had in the build.
> Add verify command to HTTP api to verify build

- ironfish-rosetta-api/scripts/build-docker.sh
- ironfish-rosetta-api/src/index.ts
https://linear.app/ironfish/issue/IRO-724/add-command-to-http-api-and-rosetta-api-to-verify-docker-build
Adds a step to make sure the image at least runs at a basic level
> Verify rosetta docker build

- ironfish/src/blockchain/blockchain.old.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/mining/director.test.slow.ts
- ironfish/src/mining/director.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
The issue here is that Blockchain.onHeadChange was never being fired. It
also duplicated onConnectBlock, so I just deleted onHeadChange and just
use onConnectBlock.
I also had to change a few places to be able to
listen to onConnectBlock since the old event used to only take the hash.
> Fix director not mining on change head

- ironfish/src/network/peers/peerConnectionManager.ts
- ironfish/src/utils/array.ts
Since we only attempt to connect to five peers per event loop, we're biasing our connection attempts to the front of the peers list. I'm not sure this has been an issue in practice, but hopefully should help spread connections between newer and older peers.
Also changes the algorithm for array shuffling to fix biasing the shuffle.
> Shuffle peers list before attempting connections

- ironfish-http-api-v2/src/common/constants.ts
- ironfish-http-api-v2/src/common/interfaces/pagination-options.ts
- ironfish-http-api-v2/src/events/events.service.test.ts
- ironfish-http-api-v2/src/events/events.service.ts
- ironfish-http-api-v2/src/events/interfaces/list-events-options.ts
Introduces a method which can be used to fetch a chunk of events for an account with cursor-based pagination.
> feat(api): Add method to fetch paginated event records

- ironfish-cli/src/commands/peers/show.ts
- ironfish-cli/src/commands/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/node.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/routes/peers/getPeer.ts
- ironfish/src/rpc/routes/peers/getPeerMessages.ts
- ironfish/src/rpc/routes/peers/getPeers.ts
- ironfish/src/rpc/routes/peers/index.ts
Adds a `--logPeerMessages` flag and a `peers:show` command to allow for viewing per-peer network messages. This should make it easier to debug differences in WebRTC signaling behavior.
Some special-casing is required to handle brokered messages and signal message encryption, which makes the logic more complex than it should be.
> Add flag for logging per-peer network traffic

- README.md
- ironfish-cli/package.json
- ironfish/jest.setup.env.js
- ironfish/package.json
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/connections/connection.ts
- ironfish/src/network/peers/connections/errors.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/localPeer.ts
- ironfish/src/network/peers/peer.test.ts
- ironfish/src/network/peers/peerConnectionManager.test.ts
- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/network/testUtilities/helpers.ts
- ironfish/src/network/testUtilities/mockLocalPeer.ts
- ironfish/src/network/types.ts
- ironfish/src/node.ts
- ironfish/src/sdk.ts
- yarn.lock
We've seen some issues with node-webrtc including segfaults and difficulty building for less-common platforms like ARM Macs. This PR tests out node-datachannel as a replacement, since we really only need the datachannel part of WebRTC.
This will require some work in the future to support browsers -- at that point we should either add support for node-datachannel to simple-peer (unfortunately it won't be a drop-in replacement), or implement an equivalent to simple-peer in WebRTCConnection.
Fixes IRO-684
> Use node-datachannel instead of simple-peer

- ironfish-cli/Dockerfile
Looks like there are some missing build dependencies when building a Docker image with node-datachannel -- will be testing out different build scripts in this PR.
> Try node-datachannel Docker build

- ironfish-cli/scripts/build.sh
Brew audit is failing with error "Binaries built for a non-native architecture were installed into ironfishbeta's prefix".
To be correct, our brew formulas should be building from source, but hopefully we can hack around it in the build script.
> Try fixing a brew audit error

- ironfish-cli/Dockerfile
Fixes issues with node-datachannel failing to build and run as part of the Docker build.
> Add cmake and updated gcc/libc to fix node-datachannel builds

- ironfish-cli/Dockerfile
Added this at the request of the community, so if you run docker you can
just type "ironfish" to execute ironfish bin an don't have to figure out
where it is.
Original request from https://discord.com/channels/771503434028941353/828808958662934558/865886555234893834
> Add ironfish bin to path

- ironfish-cli/src/commands/accounts/balance.ts
- ironfish-cli/src/commands/accounts/create.test.ts
- ironfish-cli/src/commands/accounts/create.ts
- ironfish-cli/src/commands/accounts/export.test.ts
- ironfish-cli/src/commands/accounts/export.ts
- ironfish-cli/src/commands/accounts/import.ts
- ironfish-cli/src/commands/accounts/list.test.ts
- ironfish-cli/src/commands/accounts/list.ts
- ironfish-cli/src/commands/accounts/pay.test.ts
- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/accounts/publickey.ts
- ironfish-cli/src/commands/accounts/remove.test.ts
- ironfish-cli/src/commands/accounts/remove.ts
- ironfish-cli/src/commands/accounts/rescan.test.ts
- ironfish-cli/src/commands/accounts/rescan.ts
- ironfish-cli/src/commands/accounts/use.test.ts
- ironfish-cli/src/commands/accounts/use.ts
- ironfish-cli/src/commands/accounts/which.test.ts
- ironfish-cli/src/commands/accounts/which.ts
- ironfish-cli/src/commands/config/edit.ts
- ironfish-cli/src/commands/config/get.ts
- ironfish-cli/src/commands/config/set.ts
- ironfish-cli/src/commands/config/show.ts
- ironfish/src/sdk.test.ts
- ironfish/src/sdk.ts
- ironfish/src/strategy.ts
Added a new connectRpc SDK command that helps connect users to their
node when there is no node running by either connecting to, or starting
a node.
https://linear.app/ironfish/issue/IRO-784/make-commands-be-able-to-run-with-no-node-running
> Add support for running commands offline

- ironfish-cli/src/commands/status.ts
- ironfish/src/mining/director.ts
- ironfish/src/node.ts
- ironfish/src/rpc/routes/mining/newBlocksStream.ts
- ironfish/src/rpc/routes/node/getStatus.test.ts
- ironfish/src/rpc/routes/node/getStatus.ts
This PR adds mining director info to the status command, and makes it so it can be used offline. You can see the new output below.
```bash
> ironfish status
Node:                 STOPPED
P2P Network:          WAITING In: 0 B/s, Out: 0 B/s, peers 0
Mining:               STOPPED, 0 miners, 0 mined
Blocks syncing:       STOPPED @ 0 blocks per seconds
Blockchain:           NOT SYNCED, HEAD 0000274568976dd9f4e7e7900296d6066600ebff313121edb565c23999df4dad (1730)
```
https://linear.app/ironfish/issue/IRO-801/add-mining-director-info-to-status-command
https://linear.app/ironfish/issue/IRO-802/make-status-command-work-offline
> Add miner information to status command

- ironfish-cli/src/commands/chain/export.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/routes/chain/exportChain.ts
- ironfish/src/rpc/routes/chain/index.ts
- ironfish/src/utils/async.ts
Because this was just in the command, you couldnt export a chain segment
from a running node. Now that it's an RPC route you can do it on a
running node.
https://linear.app/ironfish/issue/IRO-803/move-chain-export-logic-from-command-to-rpc-route
> Move export chain logic to RPC route

- ironfish-cli/src/commands/status.ts
- ironfish-cli/src/hooks/version.ts
- ironfish/src/package.ts
- ironfish/src/rpc/routes/node/getStatus.ts
This sends the git hash back in status so we can see what version people
are using when they post their status in discord.
```
Node:                 STOPPED @ 0bda2ef
P2P Network:          WAITING - In: 0 B/s, Out: 0 B/s, peers 0
Mining:               STOPPED - 0 miners, 0 mined
Blocks syncing:       STOPPED @ 0 blocks per seconds
Blockchain:           NOT SYNCED @ HEAD 000004531420c9a368a809253ebdcfeeb264acea5b917fcbf10211c5ecbe0c78 (793
```
> Add version to status command

- ironfish-cli/src/commands/reset.ts
- ironfish/src/utils/node.ts
Before it would just crash, now it'll wait for the existing node to
close.
> Make ironfish reset wait for node to close

- ironfish-cli/src/commands/accounts/balance.ts
So now its easier to see:
```
The account balance is:    $IRON 2,185.00000000 ($ORE 218,500,000,000)
Amount available to spend: $IRON 2,075.00000000 ($ORE 207,500,000,000)
```
> Line up balance in balance command

- ironfish-cli/src/commands/accounts/balance.ts
- ironfish-cli/src/commands/accounts/rescan.ts
- ironfish-cli/src/commands/chain/export.ts
- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/routes/accounts/rescanAccount.ts
- ironfish/src/rpc/routes/chain/exportChain.ts
- ironfish/src/rpc/routes/chain/index.ts
- ironfish/src/utils/async.ts
Rescan was broken for a few reasons.  It didn't attach to an existing
rescan properly, it also didn't indicate well that it was retaching when
I fixed that. The rescan code itself was iterating the wrong way which
resulted in a crash when it couldn't find the next block. The fixes
are..
* Added startedAt to rescan so existing attachments can see how long
the existing rescan has been running
* Fixed iteration direction, it was going left from the genesis block
instead of right causing it to immediately abort
* Attaching to rescan was broken because it didn't await the actual RPC
command causing it to exit instanstly
> Fix account rescan

- ironfish-cli/Dockerfile
- ironfish-http-api/Dockerfile
- ironfish-rosetta-api/Dockerfile
These builds were failing because they didn't have cmake, so I took the
cmake install from the CLI docker. Later if we publish ironfish to
NPM these other dockers won't have to build it.
> Add cmake to http-api and rosetta API builds

- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/chain/repair.ts
- ironfish-cli/src/commands/miners/mined.ts
- ironfish-cli/src/types.ts
- ironfish-cli/src/utils/index.ts
- ironfish-cli/src/utils/terminal.ts
- ironfish/src/primitives/block.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/routes/mining/exportMined.ts
- ironfish/src/rpc/routes/mining/index.ts
- ironfish/src/utils/blockchain.ts
This new command will scan all your blocks and print out which blocks
you mined. This is helpful for debugging to see which blocks made it on
the main chain, and which did not.
```bash
> ironfish miners:mined 206952 207325
Exporting mined block from 206952 -> 207325
00000001fb7056ab90496e542c50664d84492a79206319c66c0d50d253a5a7c3 jason 5 MAIN 206952: view in web
00000007e826e3e826ffad744f4aed56f2190460933172b1186329f8bd3c8ee6 jason 5 FORK 207028: view in web
000000046dfd1348351bff5aadb146543e4b0a371d23030910eceaf6e8fff3b4 jason 5 MAIN 207037: view in web
Exporting blocks: [==========------------------------------] 98/374 26% | ETA: 39s
```
https://imgur.com/a/faUwqmi
https://linear.app/ironfish/issue/IRO-845/create-minersmined-command
> Add miners:mined command

- ironfish-cli/src/commands/miners/start.ts
The mining message made people think they mined a block which was
submitted, but this message is just for if they mined an attempt that
might get discarded.
> Change mining message in miner

- ironfish-cli/package.json
- ironfish-cli/src/api.ts
- ironfish-cli/src/commands/chain/export.ts
- ironfish-cli/src/commands/chain/sync.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/routes/chain/exportChain.ts
- ironfish/src/rpc/routes/chain/followChain.ts
- ironfish/src/rpc/routes/chain/index.ts
- yarn.lock
This adds a new RPC command that follows the chain starting at an
arbitrary head, if any. Once it connects, and blocks are added, the
follow RPC command will stream back the blocks and the block event based
on the chain operations that occur. It only streams back blocks on the
main chain. This will be changed later.
The new command now will accept and API endpoint and token for an Ironfish
API and POST those blocks to the endpoint. That API can be found here,
https://github.com/iron-fish/ironfish-api
It will also pull the API host and endpoint from these environment variables
* IRONFISH_API_HOST
* IRONFISH_API_TOKEN 
```bash
> ironfish chain:sync
Connecting to node and fetching head...
connected: 00000004b7b8ecc6e945096bc809dde30ac5996e4c09ee1eada83439e6200210 - 44966 - 31h 35m 31s …
```
> Add API block syncer

- ironfish-cli/src/commands/accounts/pay.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/index.ts
- ironfish/src/account/validator.test.ts
- ironfish/src/account/validator.ts
Adding library to validate Account keys.
Adding basic validation on account import, this to reduce the risk of adding an account with invalid keys.
> Adding basic validation on account import

- ironfish-cli/src/commands/miners/mined.ts
- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/rpc/clients/ipcClient.ts
- ironfish/src/rpc/clients/memoryClient.ts
- ironfish/src/rpc/routes/mining/exportMined.ts
The mined command was good, but very slow, this makes a few
improvements
- Processes and scans 100 blocks at a time now
- Show time estimate using time estimater
- Make iterateTransaction method more robust
- Add option to also scan and include forks
> Improve mined command usability

- ironfish-cli/src/commands/accounts/rescan.ts
- ironfish-cli/src/commands/restore.ts
This new command will download a backup and restore it to your datadir
from an AWS S3 bucket.
It's an undocumented hidden command because most user's won't know how to or can use this.
```
> ironfish restore *** node.laptop1.3071f
Downloading
from: https://***.s3.us-east-1.amazonaws.com/node.laptop1.3071f.tar.gz
to:   /var/folders/8r/rhb_vnln4v7598b61_9wxykr0000gn/T/ironfish.backup/***
Downloading backup: [========================================] 100% | ETA: 0s
Unzipping
SRC /var/folders/8r/rhb_vnln4v7598b61_9wxykr0000gn/T/ironfish.backup/***/node.laptop1.3071f.tar.gz
DST /var/folders/8r/rhb_vnln4v7598b61_9wxykr0000gn/T/ironfish.backup/***/node.laptop1.3071f
Unzipping node.laptop1.3071f.tar.gz... done
Gettting backup name... .ironfish
Moving
SRC …
```
> Add restore command

- ironfish-cli/src/api.ts
- ironfish-cli/src/commands/chain/sync.ts
- ironfish/src/rpc/routes/chain/followChain.ts
Changelog
---
- Add transactions array to response object
- Tweak process for converting commitments and nullifiers to hex strings
- Add `main`, `transactions`, and `transactions_count` to block level sync payload
- Add `fee` to transaction level sync payload
- Small grammar correction
> IRO-1123: Send Transactions as a Part of Block Sync Payload

- ironfish/src/fileStores/config.ts
Reverts iron-fish/ironfish#353
These changes are good, but we need to hold them up until we can improve the connection issues.
The explanation is that since we are reducing the connections down to 8, we are reducing the changes to find a good connection. Right now, every 50 people you attempt to connect to results in maybe 1 connection. It also takes 30 seconds to time out a connection before you can try a new one.  So with 50, that's 50 concurrent attempts, and with 8 people that's many less attempts.
When connecting generally results in a connection this won't be such a big deal.
> Revert "IRO-1130: Update default max and target peers values as 8 by default"

- ironfish/src/strategy.test.slow.ts
- ironfish/src/workerPool/job.test.slow.ts
I had auto-merge enabled on my [previous pull request](https://github.com/iron-fish/ironfish/pull/355), which merged without slow tests passing. This code change fixes the broken slow tests.
> test(ironfish): Fix `strategy.test.slow.ts` to use new transaction verification

- ironfish/src/workerPool/job.ts
- ironfish/src/workerPool/pool.ts
This is a new feature that is causing large errors to be printed when
jobs don't handle the JobAbortedException. In the past when you were
shutting down these jobs would just hang and cause problems. Aborting is
a good behavioural change, but we haven't yet gone through and
upgraded all job call sites.
This adds a new bool to each job that you can turn on depending on the
job if you want to handle the job aborted error.
> Manually enable JobAbortedError per job

- ironfish-cli/src/api.ts
- ironfish-cli/src/commands/chain/sync.ts
The documentation link should be on the IronfishAPI class now in the
place that uses it. It was only this way before because it used to do
straight CURL requests inside the code here.
> Update syncer API doc strings

- ironfish/src/blockchain/blockchain.ts
I'm changing this because this property is deceptive. I don't like to
have properties that do big non fast calculations underneath. My general
guideline is that if it's not a fast accessor, or a fast calculation, it
should be a method. On a side note, I wrote this originally.
> Change blockchain.progress -> blockchain.getProgress()

- ironfish-cli/src/commands/faucet.ts
This lets you pass in your email via a flag instead of requiring STDIN
https://linear.app/ironfish/issue/IRO-1172/add-email-flag-for-faucet-command
> IRO-1172: Add faucet email flag

- ironfish-cli/src/commands/faucet.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/routes/faucet/giveMe.test.ts
- ironfish/src/rpc/routes/faucet/giveMe.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.ts
This turns the faucet back on and points it at the new production
API that we've been working on.
https://linear.app/ironfish/issue/IRO-1173/point-faucet-at-new-api
> IRO-1173: Enable faucet and point to new production API

- ironfish-cli/src/commands/service/faucet.ts
- ironfish/src/webApi.ts
When ever the faucet now completes a FaucetTransaction, it will send the
hash up along during the complete event for storage.
https://linear.app/ironfish/issue/IRO-1226/send-tx-hash-to-api-faucet-complete
> Send tx hash to API faucet complete

- ironfish-cli/src/commands/accounts/balance.test.ts
- ironfish-cli/src/commands/accounts/balance.ts
- ironfish-cli/src/commands/accounts/pay.test.ts
- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/service/faucet.ts
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/rpc/routes/accounts/getBalance.ts
- ironfish/src/rpc/routes/accounts/removeAccount.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.ts
Just removing this because it feels redundent. The result of this is the
balance, so you can write...
> const balance = accounts.getBalance()
then address the balances by `balance.confirmed` or
`balance.unconfirmed` which seems simpler than `balance.confirmedBalance`
> Remove "Balance" suffix from result of getBalance()

- ironfish/src/network/peers/peerManager.ts
We were mistakenly sending out peer lists to disconnected and connecting peers as well as connected peers.
> Send peer list to connected peers instead of identified peers

- ironfish/src/consensus/consensus.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/strategy.test.ts
- ironfish/src/strategy.ts
- ironfish/src/utils/math.ts
Please see this doc: 
https://docs.google.com/spreadsheets/d/1b2ZKY3vpEyk5GPB3TCjWFK4v_dfaokVsxydc8-NigAM/edit#gid=0
TL;DR 
We used to have 15 second block times and with our emissions curve (and a tiny bit of tweaking) the first year past launch had 5 coins per block as the block reward. 
We then changed our block time to 60 seconds and using the same equation our block rewards would be 19.9771 coins per block. 
Since we're using a decay function to lower inflation and decrease block reward per year, our equation makes it hard to have round numbers per block, especially if we'll be changing block time. 
In this PR the proposal is to **round** the block reward to the nearest 0.125 of a coin to make the block rewards easier to read and not be prone to rounding errors. 
Due to the decision …
> Updating IRON_FISH_YEAR_IN_BLOCKS due to block time change

- .gitignore
There are a few build artifacts missing from the gitignore -- This PR adds them in.
> Add missing files to ironfish-rust-nodejs gitignore

- ironfish/package.json
- yarn.lock
Upgrades node-datachannel to 0.1.12 to attempt to fix some crashes with the following error message:
```
libc++abi: terminating
```
> Upgrade node-datachannel to 0.1.12

- .github/workflows/ci.yml
- .github/workflows/deploy-brew.yml
- README.md
- ironfish-cli/Dockerfile
- ironfish-cli/package.json
Upgrades Node.js to the latest LTS, version 16.
I tested this on an M1 Mac Mini and it seems to build and run fine. However, our Homebrew workflow needs to be updated, probably to use bottles, because the current version assumes x86 when uploading the build artifacts. So we can't yet remove the platform check script forbidding Apple Silicon from running.
> Upgrade Node.js version to 16

- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/network/messages.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/localPeer.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/node.ts
The isWorker/broadcastWorker code isn't used anymore now that our API node architecture has been changed, so we can remove the code to simplify our networking a bit.
This is a breaking change for anyone starting their node with the worker flag, but we're okay with breaking compatibility during the testnet phase.
> Remove isWorker/broadcastWorker code

- package.json
- tools/node-platform-check.js
Apple Silicon should now work properly when building from source, so we can remove the preinstall check that prevented `yarn install` from working.
> Remove platform check during preinstall phase

- ironfish-cli/scripts/build.sh
The rust now depends on npm install for the rust build scripts.
> Fix brew build

- ironfish-rust-nodejs/package.json
- yarn.lock
Don't like self upgrading libraries. You can get exploited that way.
> Pin cargo-cp-artifact at 0.1.5

- ironfish/src/account/__fixtures__/accounts.test.ts.fixture
- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/memPool/memPool.ts
This prevents a very specific problem where we create a transaction on a
fork that is no longer valid on the main chain. The issue is that we'll
permanently rebroadcast this transaction but no one will think it's
valid. This causes the transaction DDOS mechanism that is taking down
the network. We don't delete these transactions because they may become
valid if we re-org back to our original chain.
This is NOT the permanent solution because it will check the
transaction forever, and never unmark the notes as spent that were spent
on this fork.
The correct solution is...
1. Transaction expiration to eventually remove this transaction
2. Properly unmark notes as spent by deleting the transaction that was
created on a fork when the block reorg occurs.
These fixes are coming in later patches.
> Don't rebroadcast invalid transactions

- ironfish/src/chainProcessor.ts
This is a temporary fix for the double block bug in our API sync
code. Yes, it's only two lines changed. Here's a brief explanation:
In chainProcessor.ts, the API head and the local chain head are
used to find a fork point and whether traversal to said point is
linear in nature. After the fork point is found, the chain processor
generates an iterator using the fork point and the local chain head,
the latter of which was used to find the fork point just a few lines
before. However, it is possible for the local chain head to be updated
in between findFork() and iterateTo() such that the newly generated
iterator has block hashes that were never seen/processed by findFork().
This manifests as an errant 'connected' event leading to several blocks
at the same height instead of a 'disconnected' …
> Temporary fix for double block bug in sync

- ironfish/src/chainProcessor.ts
After looking at the code, I think the proposed changes are the real fix
and not a temporary fix. We can't really lock the entire chain to update
because it would freeze syncing. Also accounts doesn't need to lock the
chain either. All that's required is that we freeze the head at the
beginning and always reference that as the target, similar to the
accounts.
> Remove TODO items from chainProcessor

- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/consensus/verifier.ts
Once transactions have expired, we want to remove them from accounts so that the notes that were spent in the expired transaction become spendable again.
> Remove transactions from accounts when they expire

- ironfish-cli/src/commands/reset.ts
```
DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
at emitRecursiveRmdirWarning (node:internal/fs/utils:816:13)
at Object.rmdir (node:internal/fs/promises:542:5)
at Reset.start (/Users/jspafford/projects/fish/ironfish-cli/build/commands/reset.js:48:32)
at async Reset.run (/Users/jspafford/projects/fish/ironfish-cli/build/command.js:22:13)
at async Reset._run (/Users/jspafford/projects/fish/node_modules/@oclif/command/lib/command.js:43:20)
at async Config.runCommand (/Users/jspafford/projects/fish/node_modules/@oclif/config/lib/config.js:173:24)
at async Main.run (/Users/jspafford/projects/fish/node_modules/@oclif/command/lib/main.js:27:9)
at async Main._run …
```
> Fix deprecated use of rmDir

- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/node.ts
- ironfish/src/utils/node.ts
When we are not upgrading the data version, it means we are doing a
migration which means data should not be loaded.
> Only load data in open when upgrading the DB

- ironfish-cli/jest.setup.js
- ironfish/jest.setup.js
There's a deprecation warning for rmdirSync on Node 16, so we can swap over to using rmSync now.
> Update rmdirSync to rmSync

- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
When blocks are disconnected, miner's fee transactions were getting added to the mempool, which then caused a block verification error when creating a block in the mining director.
> Fix miner's fee transactions re-entering the mempool

- ironfish-cli/src/commands/chain/forks.ts
Fork finder used to evict blocks after 45 seconds, which is good when
our block times were 15 seconds. Now with 60 second block times, they
are evicted before the next block ever comes in.
> Fix fork finder evicting non stale blocks

- ironfish/src/rpc/routes/chain/getBlockInfo.ts
I found it useful when debugging to check whether the node viewed a block as part of the main chain or a fork, so this adds the info to the chain:block command.
> Add field to chain:block to show if the block is on the main chain

- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/node.ts
If the accounts head does not exist in the chain, the accounts will currently fail to update the head or rescan transactions.
This updates the reset command to also clear the accounts head, and also throws errors when a header could not be found for a given block. Also, on startup, it checks whether the accounts head exists on chain and resets if not.
> Reset accounts when accounts head does not exist in the chain

- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/routes/faucet/getFunds.test.ts
- ironfish/src/rpc/routes/faucet/getFunds.ts
Original issue was reported [here](https://github.com/iron-fish/ironfish/issues/551). This code change cases on the `code` returned from the API and renders different messages appropriately for validation vs limits.
> feat(ironfish): Check for max faucet requests in `getFunds`

- ironfish-cli/src/commands/miners/mined.ts
Clear up potential confusion around `miners:mined` as we are not exporting blocks when running this command.
> Adjust text on miners:mined

- ironfish/src/mining/director.ts
Fixes #649. The blocks mined but invalid due to the 'invalidSpend' are still added to the stats (see below: X), causing confusion. This will fix the output of the status command: 
./ironfish status: 
Version              0.1.9 @ src
Node                 STARTED
Mining               STARTED - 1 miners, X mined
...
> Do not include invalidSpend blocks to mined stats

- ironfish/src/mining/mineHeader.ts
- ironfish/src/workerPool/tasks/mineHeader.ts
According to [Buffer API](https://nodejs.org/api/buffer.html#static-method-bufferfromarray), Buffer.from() copies the passed buffer data onto a new Buffer instance if the argument is Uint8Array. When we send headerBytes to the worker, it is casted to Uint8Array and then we call Buffer.from(). It seems unnecessary and we can keep it in Buffer.
> Redundant allocation when sending headerBytes to workers

- ironfish-cli/src/commands/miners/mined.ts
hyperlink does not work when the hash is capitalized
> stop setting block hash to upper case in link

- ironfish/src/consensus/consensus.ts
This was originally meant to be 4x block time, but since we changed the
block time, this is out of sync. It's causing people to no longer be in
sync much more frequently with our slower block times.
> Change max synced age ms to use block time

- .github/workflows/ci.yml
- .github/workflows/rust_ci.yml
Attempt to fix codecov upload failing on PRs from forks.
The codecov action doesn't require a token for public repositories, so that's why I deleted the token from Rust CI. We should try out the github action for codecov upload for the JS CI when we have some time.
```
[ ] Yes
```
> Fix codecov token upload

- ironfish-cli/src/commands/workers/status.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/miner.ts
- ironfish/src/node.ts
- ironfish/src/workerPool/pool.test.ts
- ironfish/src/workerPool/pool.ts
We're making this change because many users with very high core
machines are running out of memory because our node is spawning too many
workers. This is causing their machine to run out of memory more than
they expect.
Based on our optimizations I don't think anyone needs to use more than 6
workers. They are mostly idle all the time now. In the case that the
user needs more they can set "nodeWorkersMax" to -1 to disable the cap
completely.
This only is used when auto scaling is used, because we always respect the
end users desired worker configuration if they set it manually.
Ran the code, and checked how many workers were created. I also set it to -1 to ensure it still auto scaled up. …
> Set maximum node workers to 6 using new option "nodeWorkersMax"

- yarn.lock
#698 replaced blake3-wasm with blake3, but we needed to update the `yarn.lock` with this change as well.
```
[ ] Yes
[x] No
```
> Update yarn.lock with blake3 change

- ironfish/src/consensus/consensus.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/webSocketServer.ts
This past weekend a lot of people reported not being able to sync (see https://github.com/iron-fish/ironfish/issues/725 for instance). The problem is that some blocks are starting to get beefy, and when you sync in batches of 20 blocks that message size exceeds the default webrtc max message size. 
This PR sets the max message size for both our webrtc and websocket connections to 256MB to alleviate the problem for now. The real fix is to make sure our batch size doesn't exceed a certain size, which will come later. 
Tested locally for both webrtc and websocket connections 
No
> Changing max message size for both websocket and

- ironfish/src/consensus/verifier.ts
- ironfish/src/mining/__fixtures__/director.test.slow.ts.fixture
- ironfish/src/mining/director.test.slow.ts
- ironfish/src/mining/director.ts
Fixes an issue where mined blocks would get rejected when calling `addBlock`, with the reason given `Failed to add mined block to chain with reason Invalid spend`. See https://github.com/iron-fish/ironfish/issues/619 for an example. 
Factors out the spend verification from `verifyTransactionAdd` and calls it when we're fetching transactions out of the mempool. The mempool calls `transaction.verify` internally, but doesn't know about the chain, so that verification has to be done by the director now.
There may be more bugs causing this issue, but will need to mine for a bit to check it out, and this fixes at least the most obvious and testable one.
Added a unit test that fails on the current `staging`.
what …
> Check transactions for invalid spends before adding to block

- ironfish/src/syncer.ts
This issue was introduced in
https://github.com/iron-fish/ironfish/pull/647 which moved our sync
time definition back 10 hours. This solved another issue, but now when
people become synced they are suddenly stuck because the syncer won't
run anymore.
This is an experimental change, but it allows the syncer to run at any
time when someone has more work than us. Remember, that gossip also
still kicks off a sync as well.
Ran locally for awhile to test, but I am only syncing one block at a time because of the syncing bug outlined in the current issues. So I haven't been able to see what happens when you are fully synced.
[ ] Yes
[x] No
> Allow syncer to sync with peers even when synced

- ironfish/src/mining/director.ts
- ironfish/src/utils/async.ts
Just a simple fix that allows you to not half to return a promise in the
predicate.
Run lint
> Don't require async predicate in AsyncUtils.find

- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/testUtilities/mocks.ts
This code was only being used in tests, also the tests were still passing even though the tested function was not called anymore. So I altered the tests so they would fail in this case.
Ran tests
> Remove verifier.verifyNewBlock

- ironfish-cli/src/commands/accounts/pay.test.ts
- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/service/faucet.ts
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.ts
- ironfish/src/primitives/transaction.test.slow.ts
- ironfish/src/rpc/routes/transactions/__fixtures__/sendTransaction.test.ts.fixture
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.ts
- ironfish/src/testUtilities/fixtures.ts
This PR continues from prior work in allowing for multiple outputs in transactions. It was not necessary to adjust transactions at the native code level and the worker pool already had multiple recipients. This is also the first step in allowing for bulk faucet transactions, which should speed up faucet processing considerably.
Tests have been adjusted to use the `receives` object (originally present in `createTransaction.ts` in the worker pool module) in the transaction request object; all tests pass locally.
```
[ ] Yes
[x] No
```
> Allow for Multiple Receipts in Transactions

- ironfish/src/consensus/consensus.ts
Maybe 12 hours was too much. If we fix syncing issues it should be a bit
better, but let's try to tune this lower now with the invalid spend fix.
Ran the syncer for a bit
```
[ ] Yes
[x] No
```
> Reduce MAX_SYNCED_AGE_MS to 5 hours

- ironfish/src/network/version.ts
Bump network version to 12 and make the required version 12 too. We want to test if the latest protocol fixes change syncing, so we should require people to upgrade to know.
---
```
[x] Yes
[ ] No
```
> Bump network version to 12

- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/testUtilities/fixtures.ts
There is a bug in that we verify a transaction expiration based on the
current chain head, rather than on the block the transaction was added
to. This means if you sync an old fork from someone you are nearly
guaranteed to ban them.
Consider this chain
```
G -> A1 -> A2
-> B1
```
If you have a transaction on B1 that expires at height 2 (expiration is
inclusive, meaning you have to include the transaction BEFORE that
expiration), then sync that chain from another node, you'll ban them.
From your perspective, B1 has an expired transaction because you
have block A2 as your head.
The fix is to validate transactions based on their block, and not your
current head.
Wrote a test, and ran my syncer for awhile and didn't see any banning.
Is this a breaking change? If yes, add notes below on why …
> Fix banning peers for expired transactions

- .github/pull_request_template.md
This reverts commit 5321de01e6635b621e28db8af597bb053432a34e.
Github interprets these check boxes as tasks, so we'll revert this change.
N/A
```
[ ] Yes
[x] No
```
> Revert "Make breaking change into check boxes (#756)"

- ironfish/src/syncer.ts
redundant line breaks in the log of invalid blocks
This issue was introduced in #776 
There are redundant line breaks in the log of invalid blocks, affecting readability
This solved the issue.
> redundant line breaks in the log of invalid blocks

- ironfish/src/rpc/routes/chain/exportChain.ts
Some people would find it useful if exported chain will contain timestamps in it.
In this PR timestamp was added in the response schema, yup validation and populated to results.
One disadvantage of this PR is that chain:export will require offline node, because some variables and methods aren't accessible while node is running.
I ran chain:export and got this results
[ ] Yes
[x] No
> Add timestamps in exportChain.ts

- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
The start command docs indicate you can pass comma-separated bootstrap nodes, but trying to do so does not work. Fixed by parsing comma-separated values out of the bootstrap flag.
Fixes #771
Added unit tests for the start command.
```
[ ] Yes
[x] No
```
> Fix passing comma-separated bootstrap nodes to start

- ironfish-cli/scripts/run-network-macos.sh
- ironfish-cli/src/commands/service/faucet.ts
- ironfish/src/webApi.ts
These changes allow the faucet service command to get multiple requests from the API so that faucet transactions can be done in bulk.
1. Adjust your configuration with the following values:
-- `getFundsApi`: `'http://localhost:8003/faucet_transactions'`
-- `miningForce`:  true
2. Mock your own chain by doing the following:
-- Adjust `ironfish-cli/scripts/run-network-macos.sh` to include a miner, using `~/.ironfish1` as its data folder
-- Start one node using itself as a bootstrap node:
--- `yarn start:once start -b 127.0.0.1:9033 --datadir=~/batch_faucet_test`
-- Run `run-network-macos.sh` and allow for blocks to be mined on the chain.
3. Set the following environment variables:
-- `IRONFISH_API_HOST="http://localhost:8003"`
-- `IRONFISH_API_TOKEN="test"`
4. Start the Iron Fish API …
> Allow for Bulk Faucet Transactions

- ironfish-cli/src/commands/service/faucet.ts
- ironfish/src/webApi.ts
The faucet was incorrectly configured to do the max amount of faucet requests possible in a transaction. Practically, we want to have an upper bound to this number. This PR also removes workarounds that were present for the API.
Manual testing through each case.
> Fix Faucet API Request

- ironfish/src/consensus/verifier.ts
We were using the notes tree size to verifier the spend, which is not
correct but shouldn't generally cause an issue because the note
tree is bigger than the nullifier tree.
Run node for awhile
```
[] Yes
[X] No
```
> Use nullifier tree size to verify spend

- ironfish/src/consensus/verifier.ts
- ironfish/src/merkletree/merkletree.ts
This is causing add blocks to fail. It's verifying double spends inside of `hasValidSpends` which is called in `verifyConnectedBlock`. We should only verify the spend root after we connect the block, so it's split out here to do that.
The bug is detailed here:
1. Add block
2. Add nullifiers to chain from spends
3. Verify added block
4. Verify nullifiers don't exist in the chain
> Only verify spend root in hasValidSpends

- ironfish-cli/src/commands/miners/mined.ts
This fix was suggested by Stack Overflow: https://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions#comment80319576_34570694
Fixes #599
Manually run miners:mined and check that output is the same.
```
[ ] Yes
[x] No
```
> Fix use of clearLine in miners:mined

- ironfish-cli/src/commands/start.ts
Add graffiti log on start
I run it doggy
```
[ ] Yes
[x ] No
```
> chore: add graffiti logging on start

- ironfish/src/blockchain/blockchain.test.perf.ts
- ironfish/src/merkletree/merkletree.test.ts
- ironfish/src/merkletree/merkletree.ts
We didn't prune the leaves index when truncating the tree, causing the index to be stale and have data that never cleans up. This is a slow but existing "data" leak on the users hard drive. It could also create a bug because if you use `MerkleTree.contained()` with an index greater than the current tree size, it will say the element is in the tree.
Ran tests
```
[] Yes
[x] No
```
> Truncate index during MerkleTree truncate

- ironfish/package.json
- ironfish/src/mining/mineHeader.ts
- ironfish/src/primitives/blockheader.ts
- ironfish/src/primitives/nullifier.ts
- yarn.lock
The blake3 package doesn't seem to ship a native addon that works properly in node 16, so let's try blake-hash instead.
Manually tested by mining on a chain, and existing tests should pass.
```
[ ] Yes
[x] No
```
> Switch blake3 to native addon

- ironfish/src/blockchain/blockchain.test.perf.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/merkletree/merkletree.test.ts
- ironfish/src/merkletree/merkletree.ts
- ironfish/src/merkletree/schema.ts
In the merkle tree file, we have a `contained` method. Currently, there's a linear scan that goes through _**all**_ of the existing nullifiers when determining if a transaction is valid (e.g. not a double spend). As we get more transactions, this linear scan becomes more and more inefficient (e.g. beefy later blocks would take several seconds). 
This change adds another db store that lets you check in O(1) if an element exists in a merkle tree. 
Tested it locally and avg block time is about 20ms per transaction per block 
This requires a db upgrade.
> Optimize MerkleTree.contains from O(n) to O(1)

- tools/reset-network-genesis.sh
Generates the genesis block using a pre-existing account rather than creating a new account and exporting it at the end. Has the benefit of making it optional to create a new account when generating a new genesis block.
None needed
```
[ ] Yes
[x] No
```
> Update the genesis script to use a pre-existing genesis account

- ironfish-cli/src/commands/faucet.ts
If you try to use the faucet when the node is running, it will fail
silently but say it succeeded. This is because connect offline, then try
to connect using IPC and the error is not handled properly.
Request from faucet offline and online
```
[ ] Yes
[x] No
```
> Fix facuet using wrong client

- ironfish-cli/src/commands/service/faucet.ts
We should incentivize the inclusion of faucet transactions in a block by increasing the fee awarded per output.
Manual testing and calculation.
> Incentivize faucet transaction per number of outputs

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/mining/director.test.slow.ts
- ironfish/src/mining/director.ts
There is too much confusion about whether we (as testnet users) have mined a block successfully or not. The reason is mostly about the logs. Ironfish logs the following message for the failed blocks as well. 
> _Successfully mined block 00000000076ef9860eba6ba1009946f9d6f3573e3f5ad2d0fdeb06177a6ade01 (15879) has 2 transactions_
miners:mined is also accurate, but it is very slow and occasionally hangs. That's why it is really important for users to easily understand whether they mine or not. 
This PR fixes this issue. When we log the 'Successfully mined block' message, it is now always accurate. 'status' command will also give the accurate stats for the current run.
Addressing #702.
```
[ ] Yes
```
> Fix mined stats and logs for forks

- ironfish/src/fileStores/config.ts
- ironfish/src/node.ts
Add `blocksPerMessage` as configuration option. 
Temporary fix for https://github.com/iron-fish/ironfish/issues/725
```
[ ] Yes
[x] No
```
> Add `blocksPerMessage` as configuration option.

- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
These are two separate changes that should produce very minor performance improvements to the accounts store. I discovered them while testing nulling out incoming block header hashes.
Right now, we call `chain.getHeader` with the accounts head hash, then check the result of that against the chain head hash to see if we need to scan new transactions. But since we already have the account hash, we can check it directly against the chain head hash and early-exit before calling `chain.getHeader`.
We're storing headHash as a string in the accounts DB and caching it as a string on `this.headHash`, but on each event loop, we're converting it from a string to a Buffer in order to pass it to `blockchain.ts`. If we change the type of `this.headHash` to Buffer, we only need to convert it when …
> Small performance improvements to accounts store

- ironfish/src/workerPool/worker.ts
Fixes the `ironfish` tests on Windows. I think the `ironfish-cli` tests are broken, but they seem a bit more complicated to fix. We should probably run these tests on Windows in CI as well.
Tests should pass as normal.
```
[ ] Yes
[x] No
```
> Fix ironfish tests on Windows

- ironfish-cli/src/commands/accounts/import.ts
- ironfish-cli/src/commands/accounts/list.ts
- ironfish-cli/src/commands/accounts/which.ts
- ironfish/src/account/account.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/account/index.ts
- ironfish/src/account/validator.ts
- ironfish/src/mining/director.ts
- ironfish/src/rpc/routes/accounts/exportAccount.ts
- ironfish/src/rpc/routes/accounts/getAccounts.ts
- Create Account class and add displayName field
Adds a displayName field that includes a hash of the account's private+view keys along with the account name. The `displayName` field doesn't necessarily need to be serialized, but only needs to be generated once, so I created a class for Account that loads in a SerializedAccount object.
- Log account when generating mining reward transaction
Adds a log to the mining director when a mining reward transaction is generated, in order to make it clearer which account is generating the transaction.
Tested mining on a fresh chain manually.
```
[ ] Yes
[x] No
```
> Add displayName to Account and log when creating mining transaction

- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/primitives/blockheader.ts
Nulls out the hash field on headers of incoming blocks. There's no known bug as a result of this, but we should remove this field in the future because nodes should be calculating it themselves vs. assuming that other nodes have provided a correct hash.
Synced a chain from scratch on this PR with an account with transactions
```
[ ] Yes
[x] No
```
> Clear out header hash on incoming blocks

- ironfish/src/rpc/routes/chain/getBlockInfo.ts
You can now pass negative sequences in chain:block to start from the
head. So if you pass -1 you'll now get the head block.
Tested commands locally
```
[ ] Yes
[x] No
```
> Add neg sequence in chain:block to show from head

- ironfish/src/rpc/routes/chain/exportChain.ts
- ironfish/src/rpc/routes/chain/getBlockInfo.ts
- ironfish/src/rpc/routes/events/types.ts
Difficulty wasn't sent back in chain:block or export but now it is. This
was requested by jq for ironfishnetwork.com
Used the commands
```
[ ] Yes
[x] No
```
> Export difficulty in chain:export + chain:block

- ironfish-cli/src/commands/blocks/show.ts
This is more consistent with our other tooling
Run 
```js
yarn start:once blocks:show 1
```
```
[x] Yes
[ ] No
```
> Move chain:block to blocks:show

- ironfish-cli/src/commands/service/faucet.ts
Changed fee multiplier to use the length of the faucet transaction payload instead of the count used to query the API to get multiple faucet requests. Prior to this change, it resulted in faucet transactions paying out 50 $ORE (as 50 is our current internal limit) instead of X $ORE where X is the amount of faucet requests being fulfilled.
Tested manually.
> Fix overly large faucet fee

- ironfish/src/chainProcessor.ts
- ironfish/src/rpc/routes/chain/followChain.ts
- Sleep between chainProcessor.update calls
chainProcessor.update was running in a tight loop, but it wasn't locking up the node because it was hitting the DB in each loop iteration. Still, it was using a fair bit more CPU than necessary, so this adds a 1 second sleep between calls.
- Check if head hashes are equal before accessing DB
We can compare the chain head and the chainProcessor head without a DB call, so we can do those checks first to reduce contention and save some CPU as well.
Tested running service:sync when already synced, and when starting from scratch.
```
[ ] Yes
[x] No
```
> Throttle followChain RPC route

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/rpc/routes/node/getStatus.test.ts
- ironfish/src/rpc/routes/node/getStatus.ts
Log out node heap usage and rss with status command.
This PR is opened against #888 until that code change is merged.
Added unit test.
```
[ ] Yes
[x] No
```
> feat(cli,ironfish): Add memory usage to status command

- ironfish-cli/package.json
- ironfish/package.json
- package.json
- yarn.lock
Upgrade axios to fix CVE-2021-3749
After upgrade, `yarn audit` shows no high severity vulnerabilities
```
[ ] Yes
[x] No
```
No breaking changes in this upgrade according to the axios release notes: https://github.com/axios/axios/releases
`oldhill0x12345`
> security: upgrade axios to fix CVE-2021-3749

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/metrics/gauge.ts
- ironfish/src/metrics/meter.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/mining/director.ts
- ironfish/src/network/peers/peerConnectionManager.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/rpc/routes/node/getStatus.test.ts
- ironfish/src/rpc/routes/node/getStatus.ts
- ironfish/src/utils/types.ts
Add a `Gauge` metric, and collect RSS / Heap Used metrics every second in the metric monitor.
Manually tested.
```
[ ] Yes
[x] No
```
> feat(ironfish): Add heap and rss gauges to `metricsMonitor`

- ironfish/src/primitives/block.ts
- ironfish/src/primitives/transaction.ts
- ironfish/src/rpc/routes/chain/followChain.ts
- ironfish/src/strategy.test.slow.ts
Added a `transaction.withReference` around the transaction use in `followChain` to avoid some duplicate deserialization calls.
I also noticed that `transaction.withReference` wasn't working correctly for async callbacks -- The callback would execute, then call the `finally` to drop the reference before the callback was finished. Fixed this without making `transaction.withReference` async by creating a separate `Promise.resolve()` to wrap the result and calling `finally` on that one.
Synced a fresh database locally and also ran a node that was already synced up. Ran followChain with these changes to make sure it still works
```
[ ] Yes
[x] No
```
> Fix transaction withReference and use in followChain

- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/worker.ts
This doesn't fix any bugs, just makes the worker file path use consistent OS-relative path separators, which looks a bit nicer in the logs.
Also updates the text of the log when the worker pool starts to look a bit nicer.
Node should start up as expected on Windows and non-Windows.
```
[ ] Yes
[x] No
```
> Use path.join for worker file path

- ironfish-cli/src/commands/config/show.ts
- ironfish/src/sdk.ts
This removes RPC routes in the accounts and config namespace from being
mounted in the TCP adapter. This is to prevent a an attack where
users can have their graffiti changed. This is a short term fix because
the real fix is to add RPC token authentication.
Accessing one of these routes via TCP will now display the following error
```
No route found config/getConfig in namespace config for method getConfig
```
Tested lcoally
```
[ ] Yes
[ ] No
```
> Remove account and config RPC calls from TCP

- ironfish-cli/src/commands/service/sync.ts
The `service:sync` command fetches the head from the API, but discards it if `args.head` is set. This PR only fetches the API head if it's going to be used, and adjusts the logs accordingly.
This shouldn't change functionality because the code existing code still prioritizes `args.head` if it's set.
Ran `service:sync` on an existing node with `args.head` passed and without `args.head` passed.
```
[ ] Yes
[x] No
```
> service:sync: Only fetch head from API when no head arg

- ironfish-cli/src/commands/miners/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/miner.test.ts
- ironfish/src/mining/miner.ts
Playing with batchSize can impact the hash rate. A faster processor can benefit from a higher batchSize. Making it configurable can give more flexibility to miners. 
Manually tested via 
```
./ironfish config:set minerBatchSize <newBatchSize> 
./ironfish config:show
```
When I set a very low batch size, I noticed that the hash rate significantly slows down. 
```
[ ] Yes
[ X] No
```
> Make batch size configurable for miner

- ironfish-cli/src/commands/service/faucet.ts
The client balance command is particularly slow and uses a fair bit of CPU. Rather than checking the balance first every 5 seconds, we can check the API first to see if there are any new faucet transactions.
Tested that faucet command fetches transactions from the API still. I didn't test with more than 50 transactions.
```
[ ] Yes
[x] No
```
> Check the API for faucet transactions before fetching balance

- ironfish-cli/src/command.ts
- ironfish-cli/src/commands/start.ts
- ironfish-cli/src/flags.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/sdk.ts
Adds a `rpc.tcp.secure` flag for the node, which enables the ability to change sensitive config via tcp. Disabled by default.
```
[ ] Yes
[x] No
```
> Add TCP Secure flag to allow secure config over TCP

- ironfish-cli/src/command.ts
- ironfish-cli/src/flags.ts
- ironfish/src/fileStores/config.ts
https://linear.app/ironfish/issue/IRO-1489/fix-flag-defaults-overriding-config-file-values
We found a bug where the base command was setting config overrides for
values that are the same as the flags default value. This causes the
config file to be ignored.
Now, we only set the config override if it's different from the default,
which allows the config not to be over-ridden with the flag default.
> Dont set config overrides unless not default value

- ironfish-rust/README.md
Fix outdated links in the README file that refer to the Sapling related librustzcash modules
No code has been changed
It is a documentation change. Everything is backward compatible
My graffiti is chaoslab.network
> Fix the Sapling related links

- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/chainProcessor.ts
- ironfish/src/rpc/routes/chain/followChain.ts
ChainProcessor was added as part of the syncing service for iterating from one block hash to another, including forks. We can use that same code in `accounts` to reduce some duplication and slim down that file a bit, since it's already fairly large.
I did a bit of refactoring on ChainProcessor in this PR -- The only part that's necessary is setting hash to previousBlockHash when removing blocks. I tried to keep the changes to individual commits so they can be reverted if they're not desirable.
Fixes IRO-1490
I ran on a node from scratch and verified that expected transactions still get discovered and added to the balance. Forking is a bit difficult to test on a live chain, but we have a test in accounts.test.ts that validates forking.
Is this a breaking change? If yes, add notes below on …
> Fix up ChainProcessor and use in Accounts store for processing blocks

- ironfish-cli/package.json
- ironfish-cli/scripts/build.sh
- ironfish-cli/src/command.ts
- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
- ironfish-cli/src/hooks/version.ts
- ironfish-cli/src/package.ts
- ironfish/package.json
- ironfish/src/network/peerNetwork.ts
- ironfish/src/node.ts
- ironfish/src/package.ts
- ironfish/src/platform.ts
- ironfish/src/rpc/routes/node/getStatus.ts
- ironfish/src/sdk.ts
This makes a change so that previously, the version sent out everywhere
and the agent string was driven by the library. This doesn't tell the
full story, because the real version is the person who is consuming the
library and potentially writing custom code on top of the
library.
This lets users who consume the library override the package and produce
their own agent and version library using the new Package type that you
can produce from a Package.json file and pass down into the node.
https://linear.app/ironfish/issue/IRO-1392/fix-node-versioning
```js
// old
Peer Agent    if/cli/36c71af
// new
Peer Agent    ironfish-cli/0.1.19/36c71af
```
Test using brew beta and locally
what additional work is required, if …
> Allow version to be driven by lib consumer

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/rpc/routes/node/getStatus.ts
* Add a gauge for total heap
* Show Memory instead of RSS in the status command
Updated unit test
```
[ ] Yes
[x] No
```
> feat(cli,ironfish): Show heap total in status and rename RSS to Memory

- ironfish-cli/src/commands/miners/start.ts
- ironfish/src/utils/file.test.ts
- ironfish/src/utils/file.ts
- ironfish/src/utils/math.test.ts
- ironfish/src/utils/math.ts
This PR wil now format the hash rate in metric increments similar to
file sizes while still printing the original value. It also adds tests
for the FileUtils, and fixes a few bugs I saw with rounding that
produced odd values.
```javascript
// old
Mining block 76858 on request 32... ⣷ 2276451 H/s
// new
Mining block 76858 on request 32... ⣷ 2.27 MH/s (2276451)
```
Added tests and tested miner locally
```
[ ] Yes
[x] No
```
> Format miner hash rate using metric system

- ironfish-cli/src/commands/debug.ts
Create a `debug` command for the CLI which will house data that will be helpful in debugging issues. For now, just has accounts head information, and a few bits about the OS and tool versions.
Resolves IRO-1484
`yarn start:once debug`
`yarn start:once debug --datadir ~/.null`
```
[ ] Yes
[x] No
```
> Add debug command with accounts head info

- ironfish/src/account/accountsdb.ts
Fixes an issue where the node takes longer to start up as the number of transactions in the accounts database increases.
Fixes IRO-1512
Verified it's still possible to shut down/start up the node and check balance.
```
[ ] Yes
[x] No
```
> Fix slow startup when accounts store is full

- .gitattributes
`yarn lint` fails when running on Windows with a repository pulled via GitHub Desktop. (Issue #923)
I believe the issue is with the addition of carriage returns to each line.
Adding a .gitattributes file to have .ts, .js, and .json files end with LF, not CR-LF when pulled into a Windows environment.
`yarn lint` passes with .gitattributes:
> C:\Users\mjolnir\Documents\GitHub\ironfish>yarn lint
> yarn run v1.22.17
> $ lerna run lint -- --max-warnings=0
> lerna notice cli v4.0.0
> lerna info versioning independent
> lerna info Executing command in 2 packages: "yarn run lint --max-warnings=0"
> lerna info run Ran npm script 'lint' in 'ironfish' in 58.3s:
> $ tsc -b && tsc -b tsconfig.test.json && eslint --ext .ts,.tsx,.js,.jsx src/ --max-warnings=0
> lerna info run Ran npm script 'lint' in …
> Fix CR-LF issue on Windows and GitHub Desktop #923

- config/jestNodeEnvironment.js
- ironfish/src/account/accounts.ts
- ironfish/src/chainProcessor.test.ts
- ironfish/src/chainProcessor.ts
- ironfish/src/rpc/routes/chain/followChain.ts
Allows for canceling a ChainProcessor.update call midway through. ChainProcessor.update has the potential to be long-running, which can block shutdown of the node. Particularly relevant in Accounts, which waits for updateHead to finish before writing to the DB on shutdown.
Fixes IRO-1513
Updating the account balance should still work, and shutting down the node while updating the balance should not prevent the node from continuing to recalculate balance after starting it back up.
```
[ ] Yes
[X] No
```
> Add AbortSignal to ChainProcessor.update

- ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/verifier.ts
We have a mechanism in our blockchain such that when we validate an
invalid block, we remember that block hash and reject that block if we
ever see another block with that hash again as an optimization.
The issue is that future rejects of that same block reject with reason
"error" which is very confusing. It should remember the rejection reason
and reject with the original reason.
Write tests and run the node
```
[ ] Yes
[x] No
```
> Chain should reject invalid with the same reason

- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
- ironfish/src/fileStores/internal.ts
- ironfish/src/node.ts
Generates a unique node id for telemetry in the internal store. This value is reset on every first run or set if it does not already exist on start.
Manually tested and updated unit test.
```
[ ] Yes
[x] No
```
> feat(ironfish): Generate telemetry node id in internal store

- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.test.perf.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/rpc/routes/accounts/getBalance.ts
- ironfish/src/rpc/routes/accounts/removeAccount.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.ts
- ironfish/src/workerPool/messages.ts
- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/tasks/getUnspentNotes.ts
- ironfish/src/workerPool/tasks/index.ts
Adds a worker pool task for getUnspentNotes, which is used when calculating an account's balance. Note that this does not make the balance calculation faster, just frees up the main thread when doing balance work.
I'm not sure if this is the right level of abstraction for worker pool tasks -- this'll probably have to be tweaked as more functionality in the accounts store is moved to the worker pool.
Balance calculation should work as before.
```
[ ] Yes
[x] No
```
> Add GetUnspentNotes worker pool task

- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
This fixes the issue outlined in github issue [#880](https://github.com/iron-fish/ironfish/issues/880).
This is happening because of how we handle rescans.
1. When a rescan occurs, the wallet will never update itself until the rescan completes.
2. When the node starts and a rescan has started it will always try to rescan first
This means that because the rescan is broken, the wallet is stuck in a broken
state permanently. Let's now dive into why the rescan is broken.
```
G -> A1 -> A2
-> B2 -> B3
Accounts Head: A2
Chain Head:    B3
```
When we do a rescan, we try to iterate from the genesis block (G) to the
accounts head (A2), but the block chain has re-orged to B3, the newer heaviest
chain. If the accounts head were to update, it would reorganize as well to B3.
Unfortunately, once a scan …
> Fix rescan when account head is on a fork

- ironfish-cli/src/commands/accounts/pay.test.ts
- ironfish-cli/src/commands/accounts/pay.ts
I got caught by filling out all the fields only to get an error at the end. This checks it before the user is prompted with interactive questions.
Ran the command
```
[ ] Yes
[x] No
```
> Check synced status before starting pay command

- ironfish/src/fileStores/fileStore.ts
- ironfish/src/fileSystems/fileSystem.ts
- ironfish/src/fileSystems/nodeFileSystem.ts
- ironfish/src/network/messageRouters/fireAndForget.test.ts
- ironfish/src/network/messageRouters/globalRpc.test.ts
- ironfish/src/network/messageRouters/gossip.test.ts
- ironfish/src/network/messageRouters/rpc.test.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/addressManager.test.ts
- ironfish/src/network/peers/addressManager.ts
- ironfish/src/network/peers/peerAddress.ts
- ironfish/src/network/peers/peerConnectionManager.test.ts
- ironfish/src/network/peers/peerConnectionManager.ts
- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/network/testUtilities/helpers.ts
- ironfish/src/network/testUtilities/mockHostsStore.ts
- ironfish/src/node.ts
- ironfish/src/sdk.ts
This PR implements peer persistence by saving peer addresses to `hosts.json` on a defined interval and at shutdown; connected peers are saved to a `priorPeers` list and possible, un-connected peers are saved to a `possiblePeers` list. If there is persisted peer information at startup, the node will prioritize trying to connect to peers to which it was connected in the past before using the possible peers list.
This also decreases the amount of `peerListRequest` spam by changing the interval to 60 seconds and sending a request upon peer connection.
Note that there is room for optimization in the related code, e.g. capping the amount of `possiblePeers`.
Added tests. Ran the node and it successfully connected to the main network with no harmful effects. Starting the node with persisted host …
> Peer Persistence

- ironfish-cli/package.json
- ironfish-cli/src/commands/accounts/create.test.ts
- ironfish-cli/src/commands/accounts/create.ts
- ironfish-cli/src/commands/accounts/export.ts
- ironfish-cli/src/commands/accounts/import.ts
- ironfish-cli/src/commands/accounts/pay.test.ts
- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/accounts/remove.test.ts
- ironfish-cli/src/commands/accounts/remove.ts
- ironfish-cli/src/commands/accounts/rescan.ts
- ironfish-cli/src/commands/backup.ts
- ironfish-cli/src/commands/chain/export.ts
- ironfish-cli/src/commands/chain/readdblock.ts
- ironfish-cli/src/commands/chain/repair.ts
- ironfish-cli/src/commands/faucet.test.ts
- ironfish-cli/src/commands/faucet.ts
- ironfish-cli/src/commands/miners/mined.ts
- ironfish-cli/src/commands/miners/start.ts
- ironfish-cli/src/commands/peers/list.ts
- ironfish-cli/src/commands/reset.ts
- ironfish-cli/src/commands/restore.ts
- ironfish-cli/src/commands/swim.ts
- ironfish-cli/src/commands/testnet.ts
- yarn.lock
[cli-ux](https://classic.yarnpkg.com/en/package/cli-ux) package is deprecated now. This PR contains migration from cli-ux to [@oclif/core](https://classic.yarnpkg.com/en/package/@oclif/core).
All changes were made by instructions from [package migration manual](https://github.com/oclif/core/blob/main/src/cli-ux/README.md).
Also, there are some other "old" @oclif/* packages in project (like [@oclif/command](https://classic.yarnpkg.com/en/package/@oclif/command), [@oclif/config](https://classic.yarnpkg.com/en/package/@oclif/config), etc). They all marked as "in maintenance mode" and replaced by @oclif/core. It's probably better to do their migration in another PR.
Whole refactoring pretty transparent: import another namespace from new package and use it instead of old one. I tested every …
> Migrate from deprecated cli-ux to @oclif/core

- ironfish/src/node.ts
- ironfish/src/telemetry/telemetry.test.ts
- ironfish/src/telemetry/telemetry.ts
- ironfish/src/testUtilities/nodeTest.ts
Before shutting the node down or disabling telemetry, submit a point which indicates the node is offline.
Manually tested and updated unit tests.
```
[ ] Yes
[x] No
```
> feat(ironfish): Submit offline point and flush when stopping telemetry

- README.md
Ran into an error https://github.com/iron-fish/ironfish/issues/983 caused by python3 not being installed. Node-gyp v8.4.1 requires python3.7+.
Updated the readme to include this tidbit of info.
```
[ ] Yes
[x ] No
```
> README update for python error on `yarn install`

- ironfish/src/utils/currency.test.ts
- ironfish/src/utils/currency.ts
Localization error is causing languages that use `,` instead of `.` to break (ie de_DE). Applying "en-US" in toLocaleString() to prevent this error.
> Fix Issue #875

- ironfish-cli/src/commands/start.test.ts
- ironfish-cli/src/commands/start.ts
- ironfish-cli/src/commands/testnet.ts
- ironfish-cli/src/images.ts
*Changes*
- Properly prints the right command to enable telemetry
- Ties the code to a variable so that there will be a build error if
the key changes
- Make testnet command ask user to opt into telemetry
*Other changes.*
- Optimize first run so it doesn't need to spin up the RPC layer just
to set commands
`> ironfish start`
```
::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
::::::::::::: ::::::::::        :::::::::
:::::::::::::::::::::          ::::::::::
:::::::::::::::::::::          :::::::::
::::::::::::: ::::::::::        :::::::::
::::::::::::::   ::::::::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::: …
```
> Improve usability around telemetry

- ironfish-cli/src/commands/debug.ts
This is not perfect, as it only checks for unique CPU model names, but it's an improvement over just grabbing the first CPU model name. Also not a huge improvement, just something that occurred to me while seeing people discussing multiple CPUs
```
[ ] Yes
[x] No
```
> Debug command will now show multiple CPU models

- ironfish/src/syncer.ts
- ironfish/src/telemetry/interfaces/metric.ts
- ironfish/src/telemetry/telemetry.ts
This submits a new telemetry if the block has been successfully added.
I decided to only submit this telemtry so if invalid blocks are sent,
they aren't added to our data points. We also add data points for forks
and not forks, so that we can measure properly.
I will submit to local API with local influx attached.
```
[x] Yes
[ ] No
```
> Add new telemetry for block propagation

- ironfish/src/telemetry/interfaces/field.ts
- ironfish/src/telemetry/interfaces/tag.ts
The interfaces before did not ensure that if you put "string" that you
then passed a string in the value. These union types now ensure that the
value matches the type that is specified.
Run tests, no testing needed.
```
[ ] Yes
[x] No
```
> Convert telemetry types to strict union types

- ironfish/src/telemetry/interfaces/metric.ts
- ironfish/src/telemetry/telemetry.test.ts
- ironfish/src/telemetry/telemetry.ts
Also standardize on values not duplicating their measurement prefix. We'll need to update the grafana and influx queries.
Check queries in influxdata and grafana.
```
[ ] Yes
[x] No
```
> Make separate measuresments for each telemetry

- ironfish-rust-nodejs/Cargo.lock
- ironfish-rust-nodejs/Cargo.toml
- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/src/structs/note.rs
- ironfish-rust-nodejs/src/structs/transaction.rs
NAPI-rs 2.1.0 fixed the BigInt issue I reported previously, so it should be safe to update now.
Tests should pass -- they previously failed when there was a BigInt issue with napi-rs.
```
[ ] Yes
[X] No
```
> Update to latest napi-rs to fix BigInt usage

- ironfish/src/rpc/clients/rpcClient.ts
Minor change to RpcClient to utilize the ApiNamespace enum for route definition. Since we have a non-stringly-typed enum already, using it here just minimizes the risk of a typo that breaks a route.
Also reorganized a couple routes to group routes by their namespace a little bit better.
```
[ ] Yes
[ ] No
```
> Update RpcClient routes to use ApiNamespace enum

- ironfish/src/node.ts
- ironfish/src/telemetry/telemetry.ts
We are doing this to reduce cardinality. Indexes are created from the
combination of measurement and tags. This means every node session ends
up getting it's own indexes which blows out our cardinality and causes
causes InfluxDB to stop processing data. You can read more about this
issue here:
https://docs.influxdata.com/influxdb/cloud/write-data/best-practices/resolve-high-cardinality
Ran the node
```
[ ] Yes
[x] No
```
> Move telemetry tags to fields

- ironfish-cli/src/commands/start.ts
The issue is that Node.Init() happens before the telemetry node id is
created for the first time. We simply move that up, and configure it on
the SDK itself which gets passed to the constructed node.
Ran the node with a reproduction case.
```
[ ] Yes
[x] No
```
> Fix ordering issue in creating telemetry node id

- ironfish-cli/src/commands/miners/mined.ts
Adding a progress update to the end of mined.ts to update scanning progress at 100%. 
```
[ ] Yes
[x] No
```
> FIX: miners:mined status when completed - issue #748

- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/src/structs/note_encrypted.rs
- ironfish/src/primitives/noteEncrypted.ts
- ironfish/src/workerPool/tasks/getUnspentNotes.ts
In debugging issue #1022, I used mat-if/chaos (https://github.com/iron-fish/ironfish/commit/dafb58cf71ca641fa9fce3722ce88065094554b6) to help reproduce the issue. I was able to fix a bunch of the crashing on that branch with this change, but I'm not sure that this will completely address the crashing in that issue mentioned earlier.
Ran the makefile and chaos script from the above commit.
```
[ ] Yes
[X] No
```
> Return a Buffer instead of a NativeNote from decryption functions

- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/node.ts
- ironfish/src/syncer.ts
- ironfish/src/telemetry/telemetry.ts
This code moves the metrics monitor inside the telemetry service so the telemetry service can choose memory data to send on an interval.
Existing unit tests and ran node.
```
[ ] Yes
[x] No
```
> feat(ironfish): Move metrics monitor inside telemetry

- ironfish/src/telemetry/telemetry.ts
We can reduce the frequency to flush telemetry points to the API.
Manually tested and ran the node.
```
[ ] Yes
[x] No
```
> feat(ironfish): Update telemetry flush and metrics intervals to 5m

- ironfish-cli/src/commands/config/edit.ts
Pass config into `launchEditor` so it can fall back to config key `editor` if `$EDITOR` is not picked up
Fixes #964 
```
[ ] Yes
[ ] No
```
> Allow config:edit to reference the config

- ironfish/src/fileStores/hosts.ts
There's been some reports of a JSON parse error when reading `hosts.json`; it looks like a null Unicode marker or empty string is being written. While we investigate why that may be happening, it may be prudent to allow for the node to continue to start if there's an error. Thus, for the `hostsStore` class, we try to load `hosts.json` and if there's a `ParseJsonError`, then we get rid of the corrupted content by overwriting with a valid JSON structure (this file is meant to be ephemeral anyways).
All tests pass. Additionally, I tested the parsing with a correctly-formed file, an incorrectly-formed file, and a nonexistent file.
```
[ ] Yes
[x] No
```
> Fix parse error for hosts.json

- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
Just more data to help triage issues faster by adding a field for `debug` output in the bug template.
```
[ ] Yes
[ ] No
```
> Add a field for pasting `debug` command output to bug report template

- CONTRIBUTING.md
Updates the CONTRIBUTING.md file to mention that people should branch off of staging rather than master.
Text-only change.
```
[ ] Yes
[X] No
```
> Change CONTRIBUTING.md to reference staging branch

- ironfish/src/memPool/memPool.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/node.ts
- ironfish/src/rpc/routes/node/getStatus.ts
This code change adds the node's mempool size into the metrics monitor and pulls this new value instead in the status command.
```
[ ] Yes
[x] No
```
> feat(ironfish): Add mempool size to metrics monitor

- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/index.js
- ironfish-rust-nodejs/src/structs/note_encrypted.rs
- ironfish-rust-nodejs/src/structs/spend_proof.rs
- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish/src/genesis/makeGenesisBlock.ts
- ironfish/src/primitives/transaction.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/workerPool/tasks/createMinersFee.ts
- ironfish/src/workerPool/tasks/createTransaction.ts
This is an attempt at fixing the issue in #1022 -- All the scripts we had to reproduce the issue haven't reproduced the issue on this branch, so I'm hoping it does the trick. It somewhat makes sense to me why this might be an issue, since we saw issues with creating new instances of classes using napi factory functions.
@mat-if helped a great deal with finding a reproduction case for this and debugging the issue, so he deserves just as much credit on this one.
Tests should pass -- beyond that, @mat-if and I both run our reproduction cases several times and couldn't get the crash from #1022 to happen.
```
[ ] Yes
[X] No
```
> Return Buffers from Rust NAPI-RS code

- ironfish/src/telemetry/telemetry.ts
Send the size of the node's mempool from the metrics monitor to telemetry.
Manually tested.
```
[ ] Yes
[x] No
```
> feat(ironfish): Submit mempool size in telemetry

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/rpc/routes/node/getStatus.ts
- ironfish/src/telemetry/telemetry.ts
This will show the pending and submitted counts in status
```
> ironfish status
Version              0.1.24 @ src
Node                 STARTED
Heap Used            36.66 MiB / 38.86 MiB
Memory               632.40 MiB
P2P Network          CONNECTED - In: 3.01 KB/s, Out: 6.34 KB/s, peers 34
Mining               STOPPED - 0 miners, 0 mined
Mem Pool             0 tx
Syncer               IDLE @ 0.03 blocks per seconds | avg time to add block 18.3 ms
Blockchain           SYNCED @ HEAD 000000000000f195f34bd5b6e375b8fb2d9560137a6a2edda25dbf04740d25fd (126775)
Telemetry            STARTED - 6 <- 3 pending
Workers              STARTED - 0 -> 0 / 6 - 0 jobs Δ, 10.96 jobs/s
```
Run status
what additional work is required, …
> Show telemetry counts in status

- ironfish-cli/src/commands/chain/forks.ts
As seen in https://github.com/iron-fish/ironfish/issues/996, running the `chain:forks` command appears to be unresponsive to users and they are unable to quit. The command is responsive and does in fact work, but the message text `Press Q to quit` does not appear on the bottom of the window as intended. It seems that calling `footer.clearBaseLine(0)` removes the message from the content.
All tests pass. Ensured that the message appears as intended on several different terminal emulators.
```
[ ] Yes
[x] No
```
> Ensure quit message text is shown for chain:forks

- ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
While running Mat's chaos script, this log popped up:
`An error occurred while creating the new block Expected value not to be undefined`
It looks like transactions can get removed from the mempool while iterating through the cloned priority queue. I think it's probably good enough to continue past transactions if they're undefined.
Otherwise, if we want to "lock" transactions while iterating through the priority queue, we might want a way to indicate to callers to that the queue processing needs to be restarted, or provide a lock around the transactions.
Added a failing test to verify it not behaves as expected.
```
[ ] Yes
[X] No
```
> Fix undefined value when creating a block

- ironfish-cli/src/commands/status.ts
- ironfish/src/rpc/routes/node/getStatus.ts
Tech PR to fix wrong usage of type system: 
1. GetStatusResponseSchema::blockSyncer.status has wrong list of possible values
1. GetStatusResponse::blockSyncer.status was `string` instead of union of literals. Because of which condition [`content.blockSyncer.status === 'IDLE'`](https://github.com/iron-fish/ironfish/blob/1f3dc311c6db990313f81ae7d8046d19e8b2ce93/ironfish-cli/src/commands/status.ts#L75) was always false - content.blockSyncer.status could be `idle` but not `IDLE`.
Run `yearn test`. 
```
[ ] Yes
[x] No
```
> Fix block syncer status

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/rpc/routes/node/getStatus.ts
I consolidated the memory status line into 1 line, and now report it as
heap, rss, avialable. This will be useful to see how much memory people
have on their machines when they report out of memory bugs or crashes
when they paste their status.
```
> ironfish status
Version              0.1.24 @ src
Node                 STARTED
Memory               Heap: 43.07 MiB / 58.11 MiB (74.1%), RSS: 679.09 MiB (1.0%), Free: 14.60 GiB (77.2%)
P2P Network          CONNECTED - In: 144.96 KB/s, Out: 12.65 KB/s, peers 49
Mining               STOPPED - 0 miners, 0 mined
Mem Pool             0 tx
Syncer               IDLE @ 0 blocks per seconds | avg time to add block 25.59 ms
Blockchain           SYNCED @ HEAD 000000000001c44b37ec468d723b2b5367fb51d8bf90031fa96a3e16e1f2f615 (126819)
Telemetry …
```
> Consolidate memory status

- ironfish/src/workerPool/errors.ts
Stacks from job errors were not being properly assigned and propagated through the RPC layer. This change should allow us to identify potential sources of errors more quickly.
Threw an error in one of the worker pool tasks and called said task. Ran through a debugger and made sure that the stack is available.
```
[ ] Yes
[x] No
```
> Properly propagate job error stack

- ironfish/src/assert.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/typedefs/node-ipc.d.ts
This bug is surfacing because rpc.Stop() is hanging forever, because
underneath is stops all the current adapters. When the IpcAdapter tries
to stop, it waits for all the connections to end. The problem is that
IpcServer.stop() doesn't termiante the connections. This new change will
terminate the underlying connections causing all the connections to end,
thus stopping IpcAdapter.stop() from hanging.
This was first documented in this PR, which a hack was added just to
ignore RPC stop in this case.
https://github.com/iron-fish/ironfish/pull/1011
Ran the RPC layer with the node
```
[ ] Yes
[X] No
```
> Make IpcAdapter.stop() destroy all sockets

- ironfish/src/account/accounts.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/fileStores/hosts.ts
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/addressManager.ts
- ironfish/src/network/testUtilities/mockIdentity.ts
- ironfish/src/network/testUtilities/mockPrivateIdentity.ts
- ironfish/src/rpc/routes/workers/getStatus.test.ts
- ironfish/src/workerPool/job.test.slow.ts
These imports contribute to circular dependency issues and are mostly
created by people using auto import in vscode. Unfortunately there's no
way to fix this in the vscode importer so these kind of crop up. We can
look at creating an eslint rule for these.
Build code
```
[ ] Yes
[x] No
```
> Fix '..' imports

- ironfish/src/utils/blockutil.test.ts
Increase test coverage of utils/blockchain.ts (93.61% lines).
Note: the name of the new file is blockutil.test.ts, not blockchain.test.ts due to an interaction with running `yarn test blockchain` - both blockchain.test.ts files execute, but none of the "describe" nor "it" messages are printed out.
Also leaving isBlockMine() untested - it's a trivial function and makes more sense to be tested with transaction.ts
Yarn link, yarn test
```
[ ] Yes
[X] No
```
> Blockchain test coverage

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/rpc/routes/node/getStatus.ts
Refactoring of Syncer section:
1. Syncer section of status looks different from others: `@` as first delimiter for "@ 12.3 blocks per seconds" message and `|` as second delimiter for "| avg time to add block 34.5 ms" message. Almost all other sections uses `-` and `,`.
1. A lot of questions in many chats "why miner is not mining". The problem - miner wait until node syncing. Show progress of syncing helps to resolve issue.
New look of status:
Manual testing:
1. Reset database by `ironfish reset` and run node to watch progress in status (long operation).
1. Run `ironfish status -f` to watch all states of syncer.
Is this a breaking change? If yes, add notes below on why this is breaking and what additional work is required, if any.
```
[ ] Yes
[x] No
```
> Add syncing progress to status

- ironfish/src/primitives/blockheader.test.ts
- ironfish/src/primitives/blockheader.ts
If you use < > or == it doesn't do what you think. You want to check the
contents by using .compare.
Write tests and run node
```
[ ] Yes
[x] No
```
> Fix Buffer not using .compare to check equality

- ironfish-cli/src/commands/accounts/balance.test.ts
- ironfish-cli/src/commands/accounts/balance.ts
- ironfish-cli/src/commands/accounts/pay.test.ts
- ironfish-cli/src/commands/accounts/pay.ts
- ironfish/src/account/accounts.ts
- ironfish/src/rpc/routes/accounts/getBalance.ts
- ironfish/src/utils/currency.test.ts
- ironfish/src/utils/currency.ts
Some improvements and fixes for the `accounts` command. 
1 - enhancing validation checks for `accounts:pay`
2 - fix long number error. amount and fee values need to be wrapped in `Number()` for `displayIronAmountWithCurrency()`, which fixes issue identified in https://github.com/iron-fish/ironfish/issues/699
3 - add max amount check for `isValidAmount()` to prevent absurdly large values, to fix https://github.com/iron-fish/ironfish/issues/699
4 - add `accountName` for `accounts:balance`.
```
[ ] Yes
[x] No
```
> improving `accounts` command

- ironfish-cli/.yarnrc
- ironfish-cli/src/commands/faucet.ts
Improve Faucet
- email should be a required flag in the CLI prompt (because it is required by the client)
- `Too many faucet requests` and `You entered an invalid email.` errors result in `error Command failed with exit code 1.`, as seen in https://github.com/iron-fish/ironfish/issues/961. Improve error handling to exit gracefully here.
```
[ ] Yes
[x] No
```
> Faucet improvements (fix bug #961)

- ironfish/src/common/serializable.ts
- ironfish/src/workerPool/serializableMessage.ts
- ironfish/src/workerPool/workerMessage.ts
_Please note that this PR is being opened against the `serialize-worker-pool` branch._
Added a serializable interface; it's placed in a top-level common folder in order to aid future serialization efforts. Also, added a base serializable worker message class; each task request/response type will be adjusted to use this new class.
All tests pass.
```
[ ] Yes
[x] No
```
> Add serializable interface and base serializable worker message class

- ironfish/src/typedefs/bufio.d.ts
- ironfish/src/workerPool/job.ts
- ironfish/src/workerPool/messages.ts
- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/tasks/handlers.ts
- ironfish/src/workerPool/tasks/index.ts
- ironfish/src/workerPool/tasks/submitTelemetry.test.ts
- ironfish/src/workerPool/tasks/submitTelemetry.ts
- ironfish/src/workerPool/tasks/workerMessage.ts
- ironfish/src/workerPool/tasks/workerTask.ts
- ironfish/src/workerPool/worker.ts
* Add a request, response, and task class for submitting telemetry
* Remove `deserialize` from `Serializable`. Make this `static` instead per child class
* Use NodeJS `BufferEncoding` type in `bufio.d.ts` and add some more methods / functions
* Add union types for `Buffer`s, `UInt8Array`, and `WorkerMessage`. This change and most added type guards are temporary and will be cleaned up when merging `serializable-worker-pool` to `staging`
Some notes:
* I put a config of handlers [here](https://github.com/iron-fish/ironfish/compare/serialize-worker-pool...feature/iro-1613?expand=1#diff-f9de8a5c7cdfb19380c8e5bf337f48dff0f1ef6fc26a6837ee23f3eb31d28e06R8-R10) that use singletons from a child class. I'm open to refactoring this. I chose this since the types are cleaner since the abstract class …
> feat(ironfish): Convert telemetry submission to serializable messages

- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
I saw the longer try/catch pattern but jest has a way to do this that's
a bit cleaner.
Run tests
```
[ ] Yes
[x] No
```
> Simplify sendTransaction tests to use error matching

- ironfish/src/rpc/routes/transactions/__fixtures__/sendTransaction.test.ts.fixture
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
I wanted to combine these multi tests since they are very very simple now that the error catching is so small. I think it's also nice to see that the single test just checks against a few inputs.
Run testse
```
[ ] Yes
[x] No
```
> Combine single and multi sendTransaction tests

- ironfish/src/rpc/routes/transactions/__fixtures__/sendTransaction.test.ts.fixture
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.ts
This adds the ability to configure the Transaction.expirationSequence
inside of the RPC sendTransaction() which you could not do before.
Run tests and run our pool to use this new feature
```
[ ] Yes
[x] No
```
> Add ability to specify tx expiration delta in RPC

- ironfish/src/workerPool/job.ts
- ironfish/src/workerPool/messages.ts
- ironfish/src/workerPool/pool.test.ts
- ironfish/src/workerPool/tasks/handlers.ts
- ironfish/src/workerPool/tasks/index.ts
- ironfish/src/workerPool/tasks/jobError.ts
- ironfish/src/workerPool/tasks/workerMessage.ts
- ironfish/src/workerPool/worker.ts
Added serializable job error to worker pool and adjusted worker pool to use serializable job error instead of the old job error class.
Ensured the node still runs properly and a thrown error gets serialized and deserialized correctly.
```
[ ] Yes
[x] No
```
> Add serializable job error to worker pool

- config/eslint-config-ironfish/index.js
- config/eslint-plugin-ironfish/file.ts
- config/eslint-plugin-ironfish/index.js
- config/eslint-plugin-ironfish/index.test.js
- config/eslint-plugin-ironfish/package.json
- config/eslint-plugin-ironfish/tsconfig.json
- yarn.lock
See pull request #1094  for related fixes.
Ran yarn lint locally to compare, doesn't seem to add any appreciable time to lint times. Added some dummy lines in code to test as well.
```
[ ] Yes
[ ] No
```
> Add lint rule for Buffer comparison

- ironfish-rust-nodejs/Cargo.lock
- ironfish-rust-nodejs/Cargo.toml
- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/index.js
- ironfish-rust-nodejs/src/structs/note.rs
- ironfish/src/genesis/makeGenesisBlock.ts
- ironfish/src/primitives/note.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/workerPool/tasks/createMinersFee.ts
- ironfish/src/workerPool/tasks/createTransaction.ts
The upgraded version of NAPI-rs fixes factory functions causing intermittent errors when run in worker threads. This allows us to get rid of the NativeNoteBuilder that we added to work around the issue, saving an extra serialization.
Tests should pass, and if you're interested in verifying that the fix seems to work, you can check out my repro in https://github.com/dguenther/napi-rs-issues/tree/1073.
```
[ ] Yes
[X] No
```
> Upgrade napi-rs and remove NoteBuilder

- ironfish-cli/src/commands/chain/export.ts
Fixes #997
Default path of `ironfish chain:export` command is constant and relative - `../ironfish-graph-explorer/src/data.json`. It means command will always fail except when called from `~/ironfish/*` subfolder (in situation when `-p` flag is not set). It possible to fix such behavior using `process.env.PWD`.
There is no test for this command - it should be tested manually. Run `ironfish chain:export` w/o `-p` flag from different places.
```
[ ] Yes
[x] No
```
> Fix default path of chain:export command

- ironfish/src/fileStores/config.ts
Provides a larger time window of 2 hours, so that slower machines are still likely to have some shares submitted, although it will take 2 hours to reach the "expected" hashrate.
```
[ ] Yes
[x] No
```
> Update the window of time used by the hashrate calculation

- ironfish-cli/src/commands/miners/pool/start.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/poolShares.ts
This allows solo miners with multiple mining machines to utilize the pool without having to create pointless transactions that will waste IRON on transaction fees
Tested that the flag was set correctly in both cases of disablePayout being provided and not provided
```
[ ] Yes
[x] No
```
> Add a flag to skip payouts for the pool

- ironfish-cli/scripts/build.sh
ironfish-cli got renamde to ironfish causing the exclude to be missed. updated that to use the new package name
```
[ ] Yes
[ ] No
```
> Fix ironfish recursive package during docker build

- ironfish/src/mining/poolMiner.ts
- ironfish/src/mining/stratum/stratumClient.ts
- ironfish/src/mining/stratum/stratumServer.ts
- Pool listens on 0.0.0.0
- Miner doesn't try to mine if not connected to the pool
- Cleanup connection logs for pool server
```
[ ] Yes
[ ] No
```
> Small fixes to the Pool and Pool Miner

- ironfish-cli/src/commands/miners/pools/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/stratum/stratumServer.ts
This adds a new --host command to the mining pool which specifies the host information to bind to. It can be a host, a port, or both for usability
Run the pool
```
[ ] Yes
[x] No
```
> Make miner pool stratum host and port flag configurable

- ironfish/package.json
- yarn.lock
This removes the dependency on `mrmr` which was causing build issues
```
[ ] Yes
[ ] No
```
> Use updated bfilter to avoid mrmr dep with build issues

- ironfish/src/mining/discord.ts
We are printing ore and saying it's iron, but this way it will say that
it's probably displayed in iron.
**OLD**
```
Successfully paid out 21 users for 5493500766 $IRON 5,493,500,766.00000000 in
transaction 34cca2955dcb6d37ac117520c412daa22298268b2fa28f03d74ba9042afbe37f
```
**NEW**
```
Successfully paid out 21 users for $IRON 54.93500766 in transaction
34cca2955dcb6d37ac117520c412daa22298268b2fa28f03d74ba9042afbe37f (3)
```
Start new chain and test discord messages with lower payout interval
```
[ ] Yes
[x] No
```
> Fix pool payout discord message

- ironfish-cli/src/commands/peers/show.ts
- ironfish/src/network/messages.ts
- ironfish/src/network/peers/connections/connection.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/rpc/routes/peers/getPeerMessages.ts
Expand the type of `parseMessage` to accept a `Buffer`. A lot of utility and helper methods throw an Error if buffers are passed. This is going to an intermediate branch and is unused, so it will be a temporary type guard for now.
N/A, will be tested as messages are converted over
```
[ ] Yes
[x] No
```
> feat(ironfish): Expand `parseMessage` to take `string | Buffer`

- ironfish-rust/src/mining/thread.rs
The hashrate reporting from the thread isn't dividing by the total thread count, so it was overestimating hashrate exponentially
Fixes #1173 
```
[ ] Yes
[x] No
```
> Miner's self reported hashrate needs to take into account how many threads are running

- ironfish-rust-nodejs/src/lib.rs
May not be the most correct way to solve this issue, so open to suggestions.
Silence dead code warnings because I'm tired of looking at them. As far as I can tell, there is no real way for the rust analyzer to know that these functions are called because we export the struct, and that's the end of that. It has no visibility into the javascript side of things to see if we're using the methods.
```
[ ] Yes
[x] No
```
> Add allow dead code flags for napi struct methods

- ironfish/package.json
- yarn.lock
There are some dev dependencies in node-datachannel that show up in an audit, so we can version bump to clean that up.
Run a node and ensure it syncs.
```
[ ] Yes
[X] No
```
> Upgrade node-datachannel to 0.2.4

- ironfish-cli/src/commands/peers/show.ts
- ironfish/jest.setup.env.js
- ironfish/src/network/messages.test.ts
- ironfish/src/network/messages.ts
- ironfish/src/network/messages/identify.ts
- ironfish/src/network/messages/interfaces/networkMessageHeader.ts
- ironfish/src/network/messages/networkMessage.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/connections/connection.test.ts
- ironfish/src/network/peers/connections/connection.ts
- ironfish/src/network/peers/connections/webRtcConnection.test.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.test.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/localPeer.test.ts
- ironfish/src/network/peers/localPeer.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/rpc/routes/peers/getPeerMessages.ts
- ironfish/src/typedefs/bufio.d.ts
* Create binary serializable message for peer identity
* Add missing unit tests
* Add type guards for network messages when sending / receiving packets
Added unit test and manually ran node.
```
[ ] Yes
[x] No
```
> feat(ironfish): Make identify message buffer serializable

- ironfish/src/mining/stratum/stratumServer.ts
Discord user rpanic, the creator of peak-pool found an error in our stratum server: we don't catch errors thrown by the server socket, only the client sockets. This fixes that so now errors thrown by the server socket are caught and handled properly, so that the pool no longer crashes on client-connection related errors
Can test this by throwing in a process.exit() at the end of StratumClient.subscribe function
```
[ ] Yes
[ ] No
```
> Catch error events on the Pool's stratum TCP socket

- ironfish/src/network/messages.test.ts
- ironfish/src/network/messages.ts
- ironfish/src/network/messages/disconnecting.test.ts
- ironfish/src/network/messages/disconnecting.ts
- ironfish/src/network/messages/identify.test.ts
- ironfish/src/network/messages/identify.ts
- ironfish/src/network/messages/interfaces/networkMessageHeader.ts
- ironfish/src/network/messages/networkMessage.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/connections/connection.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/typedefs/bufio.d.ts
* Migrate disconnecting message to be buffer serializable
* Add missing unit tests for identify
* Remove message id from network message
Added unit tests.
```
[ ] Yes
[x] No
```
> feat(ironfish): Make disconnecting message buffer serializable

- ironfish/src/fileStores/hosts.ts
- This is an error from which we recover, so avoid surfacing it in normal execution so that users don't get concerned about it
- Explain that we are overwriting it, in case people are looking for the error/file
```
[ ] Yes
[x] No
```
> Log hosts json parsing error as debug instead of warn

- .github/workflows/deploy-npm-ironfish-rust-nodejs.yml
https://github.com/iron-fish/ironfish/actions/runs/2092061971 Ran without the publish step
Two different build issues surfacing at about the same time:
1. napi-rs released newer versions, and apparently newer versions of docker images which were causing build errors since we aren't using that updated version yet. Fixed this by pinning to last known good docker image versions
2. github decided to publish updated versions of their ubuntu runner which included an update of npm from 8.3.1 to 8.5.0 which includes a breaking change causing workspace settings to cascade
Related PR: https://github.com/npm/cli/pull/4372
Issue: https://github.com/npm/cli/issues/2546
Fixed this by adding the `--no-workspaces` flag when building `ironfish-rust-nodejs` package via npm …
> Fix CI build steps

- .github/workflows/deploy-npm-ironfish-rust-nodejs.yml
Should be able to just slide through without needing any version changes since it's just a build change and the npm builds were never released for last release
```
[ ] Yes
[ ] No
```
> STAGING -> MASTER

- ironfish/src/network/messageRouters/globalRpc.test.ts
- ironfish/src/network/messageRouters/globalRpc.ts
- ironfish/src/network/messageRouters/rpc.test.ts
- ironfish/src/network/messageRouters/rpc.ts
- ironfish/src/network/messages.ts
- ironfish/src/network/messages/cannotSatisfyRequest.test.ts
- ironfish/src/network/messages/cannotSatisfyRequest.ts
- ironfish/src/network/messages/networkMessage.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/connections/connection.ts
Migrate cannot satisfy request response to binary serialization 
Unit tests
```
[ ] Yes
[x] No
```
> feat(ironfish): Convert `CannotSatisfyRequest` to buffer serialization

- ironfish/src/fileStores/config.ts
- ironfish/src/fileStores/fileStore.ts
- ironfish/src/fileStores/hosts.ts
- ironfish/src/fileStores/internal.ts
- ironfish/src/fileStores/keyStore.ts
- ironfish/src/network/testUtilities/mockHostsStore.ts
- ironfish/src/node.ts
- ironfish/src/sdk.test.ts
- ironfish/src/sdk.ts
Doing some refactoring and moving the default dataDir up to the level of the node and sdk. We don't want to set defaults deep in the code
Running current test suite
```
[ ] Yes
[X] No
```
> Refactor default dataDir in node and sdk

- ironfish-rust-nodejs/Cargo.lock
- ironfish-rust-wasm/Cargo.lock
- ironfish-rust/Cargo.lock
- ironfish-rust/Cargo.toml
- ironfish-rust/src/lib.rs
- ironfish-rust/src/note.rs
Removes the shrinkwraprs library, since we're not really using it anywhere.
Tests should pass as expected
```
[ ] Yes
[X] No
```
> Remove shrinkwraprs

- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/rpc/adapters/memoryAdapter.ts
- ironfish/src/rpc/request.ts
Node is not being used on the request object so simplifying this code. It seems like the request being sent to a node should not already know about the node it's being sent to
```
[ ] Yes
[X] No
```
> remove node from request object

- ironfish/src/rpc/adapters/ipcAdapter.ts
Code cleanup, removing unused `node` field in the `IpcAdapter`. `IpcAdapter` accesses the node through the `Server` and should not need to know about the node directly. It is also not being used anywhere currently. Also adding stricter type validation to the `renderError` function since it is always called with an `Error` object
Current testing suite
```
[ ] Yes
[X] No
```
> Remove node from ipc adapter

- ironfish/src/rpc/adapters/memoryAdapter.ts
Removing an unused field `server` from the `memoryAdapter`. None of the other adapters use server either, just `server.router`
Existing tests
```
[ ] Yes
[X] No
```
> Remove server from memory adapter

- codecov.yml
We are reducing converage requirements down until large refactoring
projects are complete. We will increase this before main net launch and
find the correct target and improve our code coverage.
We'll most likely also refactor our testing infrastructure, like how we
handle fixtures.
```
[ ] Yes
[x] No
```
> Reduce coverage requirements down

- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/adapters/tcpAdapter.ts
- ironfish/src/sdk.ts
The node module `node-ipc` is a simple wrapper around native node `net` code. It's possible to replace this library with native TCP sockets from the `net`  lib. This PR is to replace the `node-ipc` server functionality but still expects requests to be formatted as if they are from `node-ipc` clients. Later we will replace the `node-ipc` client as well
Existing testing suite
```
[ ] Yes
[X] No
```
> Replace node-ipc server native node TCP functionality

- ironfish/src/network/messages/cannotSatisfyRequest.ts
- ironfish/src/network/messages/disconnecting.test.ts
- ironfish/src/network/messages/disconnecting.ts
- ironfish/src/typedefs/bufio.d.ts
Reduces the size of the disconnecting message. Rounds the disconnect timestamp to seconds and puts it in a u32 instead of a u64.
Tests should pass, and will test the serialize-networking branch again before opening that PR.
```
[ ] Yes
[X] No
```
> Shrink disconnecting message

- ironfish/src/network/messages/signal.test.ts
- ironfish/src/network/messages/signal.ts
- ironfish/src/network/messages/signalRequest.test.ts
- ironfish/src/network/messages/signalRequest.ts
Reduces the size of the signal and signalRequest messages.
Tests should pass, and will retest two nodes connecting in the serialize-networking branch.
```
[ ] Yes
[X] No
```
> Reduce size of the signal and signalRequest messages

- ironfish/src/rpc/adapters/tcpAdapter.ts
This should have gone in with https://github.com/iron-fish/ironfish/pull/1214. Making sure to clean up the TCP server once the adapter is stopped
Current testing suite
```
[ ] Yes
[X] No
```
> Close TCP server on tcpAdapter stop()

- ironfish/src/rpc/request.ts
- ironfish/src/rpc/routes/chain/getBlockInfo.ts
The function `Request.end(data?: TResponse, status?: number)` is taking a status parameter but it is not being used anywhere currently. Every call is just relying on the default 200 status. I'm thinking we should remove this for now unless it starts to be used somewhere
Current testing suite
```
[ ] Yes
[X] No
```
> Remove unused status code in Request

- ironfish/src/network/messages/getBlocks.ts
- ironfish/src/network/messages/gossipNetworkMessage.ts
- ironfish/src/network/messages/interfaces/networkMessageHeader.ts
- ironfish/src/network/messages/newBlock.test.ts
- ironfish/src/network/messages/newBlock.ts
- ironfish/src/network/messages/newTransaction.test.ts
- ironfish/src/network/messages/newTransaction.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/connections/connection.ts
- ironfish/src/network/utils/block.ts
Changes the NewBlock message to use the same serialization as GetBlocksResponse via a util (for now, this could be refactored), and changes nonce on gossip messages to use bytes directly rather than a variable string.
Tests should pass, and will manually test serialize-networking once all the changes are ready.
```
[ ] Yes
[X] No
```
> Shrink newBlock and change nonce

- yarn.lock
Fix for https://github.com/advisories/GHSA-xvch-5gv4-984h, I don't know that any of our code could actually be affected by this, but it's a pretty quick update.
Tests should pass, not expected to be breaking.
```
[ ] Yes
[X] No
```
> Upgrade minimist to 1.2.6

- ironfish/src/workerPool/tasks/submitTelemetry.test.ts
- ironfish/src/workerPool/tasks/submitTelemetry.ts
Serializing almost any float would cause an error as the float would be
serialized as a uint which will cause bufio to throw an error. Floats
need to be written as doubles in bufio.
See more here, https://github.com/bcoin-org/bufio/blob/91ae6c93899ff9fad7d7cee9afd2a1c4933ca984/lib/encoding.js#L441-L444
Added a new test
```
[ ] Yes
[x] No
```
> Fix telemetry serializing floats

- ironfish/package.json
- yarn.lock
sqlite3 package is under new management, which broke the downloads of the pre-compiled binaries. The upside is that they finally released an updated version with the changes we were using, so now we can use the regular npm version. See https://github.com/TryGhost/node-sqlite3/issues/1572 for more information about the change in ownership.
This might also remove/minimize the python dependency: https://github.com/TryGhost/node-sqlite3/pull/1570
```
[ ] Yes
[ ] No
```
> Update to proper sqlite3 version

- ironfish/src/mining/poolMiner.ts
- ironfish/src/mining/soloMiner.ts
The goal is to allow miners a cleaner log output so that they only see the block found/submitted messages, which are higher value than the new work messages. The new work messages can still be displayed by passing the `-v` or `--verbose` flag
```
[ ] Yes
[ ] No
```
> Move "new work" messages to debug

- ironfish/src/account/accountsdb.ts
- ironfish/src/account/database/transactions.test.ts
- ironfish/src/account/database/transactions.ts
Use binary serializable encoder for the transactions store in the Accounts DB.
Existing unit tests and added new tests for the encoder.
```
[ ] Yes
[x] No
```
> feat(ironfish): Refactor serialization for the accountsdb transaction store

- .gitattributes
Been running into this a lot when dealing with params files. Also have seen it pop up for the png file in the graph explorer module. According to the git docs, this should stop that from happening: https://git-scm.com/docs/gitattributes
```
[ ] Yes
[ ] No
```
> Update gitattributes to ignore certain file extensions when looking at line-endings

- ironfish/src/account/accountsdb.ts
Re-use types and replace encoding in Accounts DB stores
N/A
```
[ ] Yes
[x] No
```
> fix(ironfish): Use value types and proper encoding for `transactions` and `noteToNullifiers`

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/merkletree/database/leaves.test.ts
- ironfish/src/merkletree/database/nodes.test.ts
- ironfish/src/merkletree/database/nodes.ts
- ironfish/src/merkletree/merkletree.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/testUtilities/helpers/merkletree.ts
- ironfish/src/workerPool/tasks/createTransaction.test.slow.ts
Adds an Encoding class for Nodes in the merkle tree. The encoding uses binary serialization to write the merkle tree node into the key/value store.
Tests should pass, and will do a complete manual test on the serialize-database branch.
*Everything in the database serialization will be breaking changes*
```
[X] Yes
[] No
```
> Refactor node database serialization in merkle tree

- ironfish/src/account/accountsdb.ts
- ironfish/src/account/database/meta.test.ts
- ironfish/src/account/database/meta.ts
Create encoding for the meta store in the Accounts DB
Unit tests
```
[ ] Yes
[x] No
```
> feat(ironfish): Refactor serialization for accountsdb meta store

- ironfish/src/storage/levelup/database.ts
The meta store only contains the database version field, which is a number.
Tests should pass, and we'll do a full manual test on the serialize-database branch when it's finished.
*All of the database encoding changes should be breaking changes.*
```
[X] Yes
[] No
```
> Refactor meta store to use a more specific encoding

- ironfish/src/account/accountsdb.ts
- ironfish/src/storage/database/encoding.ts
The Accounts DB has two stores with hash strings as keys. This PR introduces a new encoding for these keys to be written as buffer hashes.
Will test after changes are merged in the `serialize-database` intermediate branch.
```
[ ] Yes
[x] No
```
> feat(ironfish): Create `StringHashEncoding` for hash keys in stores

- ironfish/src/network/peers/connections/webSocketConnection.ts
See title
Run node
```
[ ] Yes
[x] No
```
> feat(ironfish): Don't parse messages if websocket connection receives non-buffer

- ironfish/src/account/validator.test.ts
- ironfish/src/account/validator.ts
`haveAllowedCharacters` allowed any letter from the alphabet, which is not correct since they are always hexadecimal representation. Also seemed kind of arbitrary that we only allowed lowercase, so changed that too.
Closes IRO-1797 (probably)
```
[ ] Yes
[ ] No
```
> Allowed characters should be limited to hexadecimal, and be case insensitive

- ironfish-cli/src/commands/reset.ts
When starting a node after the database version has been increased, a warning pops up indicating the user should run `ironfish reset`.
However, the reset command also loads some database data in order to attempt to back up the accounts. This will fail, since the database structure has changed. Regardless, the command would never actually back up the accounts, since it doesn't try to load accounts from the database before writing out the backup file.
I think the main use case of the reset command should be to set the databases back to their original state, and upgrading the database should be covered by the database migration project, when that's completed. To this effect, I added an additional warning that running this command will delete your accounts.
```
/!\ WARNING: This will …
```
> Update reset command to work with database changes

- ironfish/src/merkletree/database/leaves.test.ts
- ironfish/src/merkletree/database/leaves.ts
- ironfish/src/merkletree/database/nodes.test.ts
- ironfish/src/merkletree/database/nodes.ts
- ironfish/src/merkletree/merkletree.ts
- ironfish/src/merkletree/schema.ts
- ironfish/src/testUtilities/helpers/merkletree.ts
- ironfish/src/testUtilities/matchers/merkletree.ts
The merkle tree is storing the keys of the database as fields on the value object as well. This is unnecessary, since they're always the same in both places, so we can remove them from the values object.
Connected two nodes and mined on both of them
```
[ ] Yes
[ ] No
```
> Remove indices from merkle tree database values

- ironfish/src/webApi.ts
Block head response was accidentally renamed from `.hash` to `.block_hash` in https://github.com/iron-fish/ironfish/pull/1181. Fixing that change here
```
[ ] Yes
[X] No
```
> Fix block hash rename

- ironfish/src/webApi.ts
`deposits/head` returns `{block_hash: ""}` instead of `{hash: ""}`
```
[ ] Yes
[X] No
```
> Update response object for deposits head request

- ironfish-cli/src/commands/chain/genesisblock.ts
- ironfish-cli/src/commands/start.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/genesis/genesisBlock.ts
- ironfish/src/genesis/makeGenesisBlock.ts
- ironfish/src/primitives/index.ts
- ironfish/src/primitives/target.ts
Adds a `--difficulty` flag to the `chain:genesisblock` command to allow for generating a genesis block with a specific difficulty.
Also removes the `--coins` flag, since the supply curve is hardcoded to expect a certain number of coins in the genesis block anyway.
Fixes IRO-1849
Try generating a genesis block with different `--difficulty` flags and make sure the command changes the resulting `target` field. You can also try replacing `genesisBlock` and check that the mining difficulty changes.
```
[ ] Yes
[X] No
```
> Make target configurable in genesis block creation

- ironfish-cli/package.json
- ironfish-rust-nodejs/npm/darwin-arm64/package.json
- ironfish-rust-nodejs/npm/darwin-x64/package.json
- ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json
- ironfish-rust-nodejs/npm/linux-arm64-musl/package.json
- ironfish-rust-nodejs/npm/linux-x64-gnu/package.json
- ironfish-rust-nodejs/npm/linux-x64-musl/package.json
- ironfish-rust-nodejs/npm/win32-x64-msvc/package.json
- ironfish-rust-nodejs/package.json
- ironfish/package.json
Bumps the versions of ironfish-cli to 0.1.31, ironfish to 0.0.9, and ironfish-rust-nodejs to 0.1.5.
```
[ ] Yes
[ ] No
```
> Bump to 0.0.9, 0.1.31, 0.1.5

- ironfish-cli/src/commands/deposit.ts
> Deposit cmd shows tx confirmation fee in correct denomination

- ironfish/src/account/database/accounts.test.ts
- ironfish/src/account/database/accounts.ts
- ironfish/src/account/database/meta.test.ts
- ironfish/src/account/database/meta.ts
- ironfish/src/network/messages/identify.test.ts
- ironfish/src/network/messages/identify.ts
- ironfish/src/workerPool/tasks/getUnspentNotes.test.ts
- ironfish/src/workerPool/tasks/getUnspentNotes.ts
More serialization encoding changes for any user-inputtable strings. Continuation of #1282 
```
[ ] Yes
[ ] No
```
> Any user-inputtable strings being serialized use utf8 encoding

- ironfish-cli/src/commands/reset.ts
- ironfish/src/fileStores/hosts.ts
After performing a mandatory upgrade, many peers in the hosts.json file will be on the older version still, so connection attempts are wasted on these peers. I'm not sure that we remove peers from hosts.json until they're disposed in the PeerManager either, so they might hang around for a while.
Locally tested
```
[ ] Yes
[X] No
```
> delete the hosts.json file on a database reset

- ironfish-cli/src/commands/reset.ts
- ironfish/src/fileStores/hosts.ts
After performing a mandatory upgrade, many peers in the hosts.json file will be on the older version still, so connection attempts are wasted on these peers. I'm not sure that we remove peers from hosts.json until they're disposed in the PeerManager either, so they might hang around for a while.
Tested locally
```
[ ] Yes
[X] No
```
> delete hosts file on "ironfish reset" command

- ironfish-cli/src/commands/miners/start.ts
- Can be disabled with `--no-richOutput`
```
[ ] Yes
[ ] No
```
> Miner cmd: add hashrate as rich cli ux action

- ironfish-cli/src/commands/miners/start.ts
Fix typo `Staring` -> `Starting`
Run the node
```
[ ] Yes
[x] No
```
> refactor(cli): Fix typo when starting miner

- ironfish-cli/src/commands/start.ts
After running ironfish reset, the node used to create an account for the user if one didn't exist on next startup. We broke that with a [recent change](https://github.com/iron-fish/ironfish/pull/1288/files#diff-f746f6e76b029871c0e5cc11c3752b1043ac76a0cee18e8eaf8bae23ebdf916cL74) to ironfish reset. This changes functionality to not only create a default account if it's the first run but instead check every time if there are any accounts and if not, create a default.
Tested locally
```
[ ] Yes
[X] No
```
> If there is no default account on startup, create one

- ironfish-cli/src/commands/deposit.ts
From this Github issue: https://github.com/iron-fish/ironfish/issues/1317
The description of the flag makes it sound like it's a delta, and some of the verification checks act like it's a delta, but we're passing the value to expirationSequence rather than expirationSequenceDelta. This PR makes explicit to pass a value for expirationSequenceDelta and uses that value correctly when sending the transaction.
Tested locally
```
[] Yes
[X] No
```
> Fix deposit --expirationSequence flag

- ironfish-cli/src/commands/service/syncTransactions.ts
For sync transactions we don't actually care about the number of blocks, but rather the number of transactions. 500 is probably low, but given the current state of the API I'd rather err on the side of caution
```
[ ] Yes
[ ] No
```
> Sync transactions counts transactions in buffer instead of blocks

- ironfish/src/rpc/routes/accounts/getPublicKey.test.ts
- ironfish/src/rpc/routes/accounts/utils.test.ts
- ironfish/src/rpc/routes/mining/__fixtures__/blockTemplateStream.test.slow.ts.fixture
- ironfish/src/rpc/routes/mining/blockTemplateStream.test.slow.ts
- ironfish/src/rpc/routes/mining/blockTemplateStream.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/testUtilities/routeTest.ts
Fixes the transaction expiration crash when mining. I added a test for it, but the test takes quite a bit of setup to get working, so I could use a second opinion on it.
Fixes IRO-1876
New test should pass.
```
[ ] Yes
[ ] No
```
> Add a try-catch around new block creation

- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/sdk.ts
We added the enableNativeRpcTcpAdapter  to test out the new TCP server functionality that was created in https://github.com/iron-fish/ironfish/pull/1214. That functionality has been tested for the the last few weeks by team members running nodes locally so we want to officially transition to the new adapter and remove the flag.
Testing by team members
```
[ ] Yes
[X] No
```
> remove enableNativeRpcTcpAdapter flag and switch to native TCP adapter

- ironfish-cli/src/commands/miners/mined.ts
- ironfish/src/rpc/routes/mining/exportMined.ts
- Adjusts `miners:mined` command to use `MinedBlocksIndexer`
- Add CLI flag for scanning forks for mined blocks
- Add CLI flag for searching for mined block info given a block hash
Mined blocks on a local chain and ensured that mined blocks were properly returned in each case.
```
[ ] Yes
[x] No
```
> Adjustment to miners:mined RPC route

- ironfish-cli/src/commands/reset.ts
Added indexes folder to the reset command.
Synced blocks into a fresh data directory and successfully ran the reset command.
```
[ ] Yes
[ ] No
```
> Add indexes to reset command

- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/sdk.ts
This reverts commit 6dd1388b49ee43f8b3f5ac2a1a602c740f189e1b.
The native TCP RPC was causing payouts to time out on the mining pool. The payout would get created successfully in the sqlite database, but then seem to time out on the sendTransaction call. Reverting this for now so it doesn't block version bumps.
```
[ ] Yes
[X] No
```
> Revert "remove enableNativeRpcTcpAdapter flag and switch to native TCP adapter (#1388)"

- ironfish/src/rpc/clients/memoryClient.ts
- ironfish/src/sdk.test.ts
- ironfish/src/sdk.ts
- ironfish/src/testUtilities/routeTest.ts
The [MemoryClient](https://github.com/iron-fish/ironfish/blob/c6a17e98b1f9add2e5727ae3f03676fe14ad0fac/ironfish/src/rpc/clients/memoryClient.ts#L22) is an interface to all the methods you can call on a node like /getStatus , /accounts/balance  etc. It is similar to the TcpClient or IpcClient but it does not connect to a server remotely. Instead it just makes direct function calls to the node. Because of this we want to refactor it to not have all the same functions that an RpcClient might have such as connect . If it is just making direct function calls then it doesn't make sense to connect  to anything. This should simplify the code quite a bit and make it easier to tackle TCP security because we don't have to worry about the MemoryClient functionality which should be unrelated to TCP …
> Refactor MemoryClient

- ironfish/src/rpc/adapters/adapter.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/rpc/adapters/memoryAdapter.ts
- ironfish/src/rpc/adapters/tcpAdapter.ts
- ironfish/src/rpc/clients/memoryClient.ts
- ironfish/src/rpc/server.ts
There seems to be a lot of unused code in the RPC layer that getting rid of would greatly simplify future refactoring.
Unit tests and local testing
```
[ ] Yes
[X] No
```
> Remove dead code in RPC layer

- ironfish/src/rpc/adapters/memoryAdapter.ts
- ironfish/src/rpc/clients/memoryClient.ts
- ironfish/src/rpc/routes/accounts/create.test.slow.ts
- ironfish/src/rpc/routes/accounts/getPublicKey.test.ts
- ironfish/src/rpc/routes/accounts/rescanAccount.test.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
- ironfish/src/rpc/routes/chain/getChainInfo.test.ts
- ironfish/src/rpc/routes/config/getConfig.test.ts
- ironfish/src/rpc/routes/config/setConfig.test.ts
- ironfish/src/rpc/routes/faucet/getFunds.test.ts
- ironfish/src/rpc/routes/mining/blockTemplateStream.test.slow.ts
- ironfish/src/rpc/routes/node/getLogStream.test.ts
- ironfish/src/rpc/routes/node/getStatus.test.ts
- ironfish/src/rpc/routes/node/stopNode.test.ts
- ironfish/src/rpc/routes/workers/getStatus.test.ts
- ironfish/src/sdk.ts
- ironfish/src/testUtilities/routeTest.ts
The MemoryAdaper is supposed to be analogous to a TcpAdapter and IpcAdapter . All 3 implement the IAdapter  interface that can start and stop the adapter. The main difference of the MemoryAdaper  is that it is not running a server. It does not need to be stopped or started. It is just making function calls directly to the internal Router  code.
This also means that the idea of a client (MemoryClient) server (MemoryAdaper) relationship doesn't make much sense since the client and server are directly connected they should be the same code. For this reason we want to get rid of the MemoryAdapter  and just call Router.route  directly from the MemoryClient . Either that or greatly reduce the code in each and remove unnecessary orchestration.
Unit tests + local testing …
> Combine MemoryAdapter and MemoryClient functionality

- ironfish/src/account/accounts.ts
Ensure database updates for notes -> nullifiers are atomic within the same transaction.
N/A
```
[ ] Yes
[x] No
```
> fix(ironfish): Use `tx` object when updating `noteToNullifier` map

- ironfish-cli/src/commands/miners/pools/start.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/poolShares.ts
Addresses https://github.com/iron-fish/ironfish/issues/1419. This change adds a flag to the `miners:pools:start` command to correctly override `balancePercentPayout` in the config.
Currently the config variable `poolBalancePercentPayout` doesn't represent an actual percentage because we are using it incorrectly. Instead it represents a divisor. So
- `config.poolBalancePercentPayout = 2` would pay out 50%
- `config.poolBalancePercentPayout = 3` would pay out 33%
- `config.poolBalancePercentPayout = 4` would pay out 25%
- etc
This change allows you to run `ironfish miners:pools:start --balancePercentPayout=30` and it will actually pay out 30%. If you do not pass in the `--balancePercentPayout` flag, it will retain it's original functionality. This is temporary to allow people running pools …
> add flag to override pool balance payout percentage

- ironfish/src/mining/poolShares.ts
- ironfish/src/utils/bigint.test.ts
- ironfish/src/utils/bigint.ts
Adding some clarity around BigInt.divide function and making sure to use it in mining pool code
```
[ ] Yes
[X] No
```
> Use bigint division in mining pool

- ironfish/src/rpc/adapters/ipcAdapter.test.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/rpc/adapters/tcpAdapter.ts
- ironfish/src/rpc/clients/ipcClient.ts
- ironfish/src/rpc/clients/tcpClient.test.ts
- ironfish/src/rpc/clients/tcpClient.ts
requires that a logger be passed to each RPC adapter and client. passing a
logger makes it easier to configure logging.
```
[ ] Yes
[X] No
```
> fix: removes default createRootLogger from RPC adapters and clients

- ironfish-cli/src/commands/miners/pools/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/index.ts
- ironfish/src/mining/lark.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/poolShares.ts
Since Discord message may get blocked for some reasons. Lark as well as FeiShu (in China) provides better experience especially for Chinese miners. 
This PR Add lark support for Ironfish Pool which implements same functionality as Discord, like disconnect report, payout report etc.
```
[ ] Yes
[x] No
```
> FEAT: support lark message

- ironfish/src/memPool/memPool.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/testUtilities/mocks.ts
There is a bug where users are being kicked from connections if they
rebroadcast transactions to us that we already have. The issue is that
wallest are programmed to rebroadcast transactions if we don't accept
them up until their expiry time. However, acceptTransaction() returns
false if we already have the transaction. We also punish any user
for if acceptTransaction() returns false. You can see the issue
here.
Update tests
```
[ ] Yes
[x] No
```
> Fix incorrectly kicking peers if we have the TX

- ironfish/src/rpc/adapters/ipcAdapter.test.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/rpc/adapters/tcpAdapter.ts
- ironfish/src/rpc/clients/ipcClient.ts
- ironfish/src/rpc/clients/tcpClient.test.ts
- ironfish/src/rpc/clients/tcpClient.ts
Reverts iron-fish/ironfish#1498
on second thought...
requiring that a logger is passed to constructors in the RPC layer has a couple of disadvantages that I'm aware of:
1. it runs counter to the way we've implemented and/or are implementing things through other parts of the codebase
2. a logger isn't a functional requirement for these classes: i expect to need to pass a host and a port for a TCP client, but not necessarily a logger
the benefits to passing a logger into these constructors only accrue when we take the time to configure the logger first and pass it in. a requirement for the logger alone doesn't get us that
> Revert "fix: removes default createRootLogger from RPC adapters and clients"

- ironfish/src/rpc/clients/tcpClient.ts
> fix: don't log 'failed to connect' in TCP client if connection successful

- ironfish-cli/package.json
- ironfish-cli/src/commands/miners/mined.ts
- ironfish-cli/src/typedefs/supports-hyperlinks.d.ts
- ironfish-cli/src/utils/terminal.ts
- yarn.lock
Some terminals does not support hyperlink, which is diplayed as a result of miners:mined command. This PR adds a fallback and displays just an explorer url in such case.
```
[ ] Yes
[x] No
```
> Add fallback mined block url if terminal doesn't support hyperlinks

- ironfish-graph-explorer/src/index.html
The 'integrity' attribute allows for the browser to verify that externally hosted files (for example from a CDN) are delivered without unexpected manipulation. Without this attribute, if an attacker can modify the externally hosted resource, this could lead to XSS and other types of attacks. To prevent this, include the base64-encoded cryptographic hash of the resource (file) you’re telling the browser to fetch in the 'integrity' attribute for all externally hosted files.
```
[ ] Yes
[ ] No
```
> Add: TLS. Pin version. Integrity

- ironfish/src/network/peerNetwork.ts
The main thing at this point, is that this would disconnect people who
were creating transactions on a fork. I don't think we'll need to bring
this back, it also seems like this was resolved by other changes
mat added to not accept mempool entries for conflicting or invalid
transactions. We should instead build confirmation and fix forking.
Run node in production
```
[ ] Yes
[x] No
```
> Delete disconnecting peers for non acceptable tx

- ironfish-cli/src/command.ts
- ironfish/src/account/accounts.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/logger/index.ts
- ironfish/src/logger/reporters/console.test.ts
- ironfish/src/logger/reporters/console.ts
- ironfish/src/mining/lark.ts
- ironfish/src/mining/manager.ts
- ironfish/src/mining/poolMiner.ts
- ironfish/src/mining/soloMiner.ts
- ironfish/src/mining/stratum/stratumClient.ts
- ironfish/src/mining/stratum/stratumServer.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/rpc/adapters/tcpAdapter.ts
- ironfish/src/rpc/clients/tcpClient.ts
- ironfish/src/rpc/routes/node/getLogStream.test.ts
- ironfish/src/sdk.ts
For a better way to parse the output of logs we want the ability to log to JSON in the console.
This PR also includes changes to log lines to make parsing logs safer. It will be easier to log in different formats if the logging interface is more well defined. This PR changes the Logger from taking (...args: any[]) to taking (message: string, ...args: []Record<string, string | number>). This will make it easier for us to convert our logs to JSON
Testing locally and unit tests
```
[ ] Yes
[X] No
```
> Add ability to log to JSON in the console

- ironfish/src/mining/poolDatabase/migrations/002-add-shares-index.ts
- ironfish/src/mining/poolDatabase/migrations/index.ts
Quick addition to the pool database to potentially increase IO throughput. Can verify the change here: https://www.db-fiddle.com/f/69hrM4VPVFR23Xt7Hd7SPb/0
Testing locally on existing pool database
```
[ ] Yes
[ ] No
```
> Pool database: Add index on createdAt for share table

- ironfish/src/indexers/minedBlocksIndexer.test.ts
- ironfish/src/indexers/minedBlocksIndexer.ts
- ironfish/src/node.ts
The head hash of `MinedBlockIndexer`'s meta table should be reset instead of throwing an error, if its head hash in is not found in the chain.
Reproduction, as per @NullSoldier:
1. Start the node and sync blocks
2. Delete the `databases` folder
3. Start the node
Ensured that the node now starts properly and logs an error message.
```
[ ] Yes
[x] No
```
> Reset chainProcessor hash if index head not found in database

- ironfish-cli/src/commands/miners/start.ts
- ironfish/src/mining/stratum/stratumServer.ts
2 small text updates
1) start mining pool connected id at 1 and not 0
2) redundant 'connected to node' msg that can be removed from solo mining start log
```
[ ] Yes
[x] No
```
> small text updates

- ironfish-cli/src/commands/service/sync.ts
I moved the max upload to a flag default in case we need to change this again, so we don't need to change the code. We can just terraform a configuration change. The value also shows up in the --help this way.
```
> ironfish service:sync --help
FLAGS
-m, --maxUpload=<value>  [default: 20] The max number of blocks to sync in once batch
```
Run the command and play with inputs
```
[ ] Yes
[x] No
```
> Move max upload in syncer to flag

- ironfish/src/syncer.ts
Remove the whitelist property on the Syncer because it is never used
Unit tests
```
[ ] Yes
[X] No
```
> Remove whitelist from Syncer

- ironfish/src/account/accounts.ts
Many bugs have been reported relating to tx failures and account balance problems. I've hit these myself quite consistently.
While debugging, I found that https://github.com/iron-fish/ironfish/blob/master/ironfish/src/account/accounts.ts#L714-L740 in `accounts/createTransaction` is causing the problem. This wouldn't update successfully, the tx would then fail with `Insufficient funds`, and querying the account balance afterward would show incorrect values. 
`nullifier.toString('hex')` should be `unspentNote.hash` 👇 
```
// Update our map so this doesn't happen again
const noteMapValue = this.noteToNullifier.get(nullifier.toString('hex'))
if (noteMapValue) {
this.logger.debug(`Unspent note has index ${String(noteMapValue.noteIndex)}`)
await …
```
> fix: transaction errors & account balance issues

- ironfish/src/fileStores/config.ts
Add a configuration in the file store for the minimum number of block confirmations required when computing an account balance (during fetching or sending in a transaction)
N/A
```
[ ] Yes
[x] No
```
> feat(ironfish): Add config variable for minimum block confirmations

- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/routes/config/getConfig.test.ts
We've been using the same default batch size of 10,000 since before we made the miner ~20-30x faster. Making the batch size 2.5x is fairly conservative, but should still result in slightly less time spent on things that are not actually hashing to find valid blocks. Even on my laptop, I was running a batch size of 50k in ~15ms. Note that I don't really expect this to have much impact, just something that occurred to me recently and was an easy change.
```
[ ] Yes
[ ] No
```
> Bump up the default batch size

- ironfish/src/rpc/adapters/tcpAdapter.ts
I noticed that the TcpAdapter does not wait for clients to close, which
means there are clients still connected, and RPC routes still executing
onceo TcpAdapter.stop() has finished executing. We genenerally want
stop() to finish when TcpAdapter has fully stopped, and not in the
middle.
Call `ironfish stop` to test this code path
```
[ ] Yes
[x] No
```
> Add TcpAdapter waiting for clients to disconnect

- ironfish/src/mining/poolDatabase/database.ts
- ironfish/src/mining/poolDatabase/migrations/003-add-transaction-hash.ts
- ironfish/src/mining/poolDatabase/migrations/index.ts
- ironfish/src/mining/poolShares.ts
Currently pool payouts don't record which transaction hash they were completed with. This is causing some issues when trying to debug how the payout was completed. We are also running into an issue where some transaction hashes cannot be found and there is no way to work backwards to tell which payouts they were associated with
Local testing
DB Fiddle testing the queries: https://www.db-fiddle.com/f/hk54YMjkve6A2QiwvsdBrT/2
```
[ ] Yes
[X] No
```
> Add transaction hash to pool payouts table

- ironfish/src/fileStores/config.ts
- ironfish/src/mining/poolShares.ts
we believe that some payout transactions from the pool are expiring. we have a
default expiry of 20 blocks for such transactions. these changes increase the
expiry to 60. with one minute block times this should be roughly equivalent to
half of the duration of the payout interval. adding a config value for this
field will help to change it without a code change if necessary.
```
[ ] Yes
[X] No
```
> feat: adds a config variable for pool payout expiration, sets default

- ironfish/src/rpc/clients/tcpClient.test.ts
- ironfish/src/rpc/clients/tcpClient.ts
the connect method returns a promise, but does not propagate any connection
errors from connectClient, so that promise always resolves even if connection
fails.
these changes throw the error from connectClient if connection is not retried.
1. Run `yarn start status -f --rpc.tcp`
2. See no output
3. Start a node
4. Continue to see no output
```
[ ] Yes
[X] No
```
> fix: throws error if tcp client connection fails

- ironfish/src/fileStores/config.ts
- ironfish/src/mining/poolShares.ts
Revert "feat: adds a config variable for pool payout expiration, sets default (#1587)"
This reverts commit c96f138de90e8311e96a28357d1ae5b30bf5c6f6.
- removes hardcoded sequence delta of 20 for payout transactions
```
[ ] Yes
[X] No
```
> feat: uses defaultTransactionExpirationSequenceDelta instead of pool-specific option

- ironfish-cli/src/commands/accounts/balance.ts
Adds a little more information for this ticket https://linear.app/ironfish/issue/IRO-1890/clarify-unconfirmedconfirmed-balance-on-deposits-cmd
Run `yarn start accounts:balance --help`
```
[ ] Yes
[x] No
```
> Add more description for accounts:balance

- ironfish/src/workerPool/pool.ts
The original value of 200 is not ideal anymore, as we have code that can kick off 300 jobs at a time, which would cause other jobs to be skipped. One example of this is when a block comes in, we kick off a `VerifyTransaction` job for every transaction in the block, which currently can be 301. If a gossiped transaction comes in at the same time, we are likely to not gossip that transaction when checking if the queue is saturated, even though it will no longer be momentarily. With a value of 500, we can expect a block to come in, with some leeway for other jobs before we count it as saturated.
This is a band-aid fix, ideally we can come up with a better way to consider a queue maxed/saturated. Perhaps based on the number of jobs/second that the pool has done within the last minute, so this …
> Increase the max queue default size for the worker pool

- ironfish-cli/src/commands/chain/forks.ts
Just some minor tweaks since I've been looking at this screen a lot lately. Padding some columns, added graffiti. Graffiti isn't terribly useful, but could be used if we find a pool mining on a fork, we could potentially reach out and debug, notify, etc. Not all of these appear to be currently-mined forks, some seem to be blocks being gossiped around from a while ago.
```
[ ] Yes
[ ] No
```
> CLI: `chain:forks` now shows graffiti, proper spacing for some columns

- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/roundrobinqueue.ts
Prior to this change, the worker pool could receive a large number of jobs for one job type, which would effectively block other job types from executing until they are finished. Ideally, consumers of a job queue should not have to worry about stalling other job types, so this creates a simple round robin queue, which just iterates over the types each time a job is executed to ensure they are all executed in a somewhat timely fashion.
Closes IRO-2095
```
[ ] Yes
[ ] No
```
> Add a round robin queue to the worker pool

- ironfish/src/account/accounts.ts
- ironfish/src/workerPool/tasks/getUnspentNotes.ts
This code change is a follow-up to this [PR](https://github.com/iron-fish/ironfish/pull/1518). The changes are effectively the same, but includes a batch size to reduce starvation within the worker pool.
Running this locally seems to give around a 5-6x speedup.
Run the node (`accounts:balance` and `deposit`).
```
[ ] Yes
[x] No
```
> feat(ironfish): Batch jobs to fetch unspent notes

- ironfish/src/rpc/adapters/socketAdapter/protocol.ts
- ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts
- ironfish/src/rpc/clients/tcpClient.test.ts
- ironfish/src/rpc/clients/tcpClient.ts
- ironfish/src/rpc/messageBuffer.test.ts
- ironfish/src/rpc/messageBuffer.ts
a tcp socket is modeled as a stream of bytes. we use tcp sockets to send and
receive json-formatted messages, but there is no guarantee that a tcp segment
will contain a full message or messages. it's possible, especially with larger
messages, that we read data from the socket in the middle of a message.
attempting to parse such partial messages results in json parsing errors.
- implements a MessageBuffer class to encapsulate the logic required
for buffering partial messages read from a socket
- adds a MessageBuffer to TcpClient
- adds a MessageBuffer to each SocketClient
- updates 'data' event listeners to use MessageBuffers
- adds MESSAGE_DELIMITER to protocol definitions
- `yarn test` tests pass
- local testing running node and commands over tcp
- local testing running node and pool
Is …
> feat: adds message buffering to rpc tcp sockets

- ironfish-cli/src/commands/stop.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/clients/rpcClient.ts
- ironfish/src/rpc/clients/secureTcpClient.ts
- ironfish/src/rpc/clients/tcpClient.ts
- ironfish/src/sdk.ts
This feature was not working to begin with, and not well supported. I
will remove the rest from the IPC client once we delete the IPC client
and adapter soon.
Ran the node and RPC layer
```
[ ] Yes
[x] No
```
> Remove rpcRetryConnect from TCP adapters

- ironfish-cli/src/commands/deposit.ts
- ironfish-cli/src/commands/service/faucet.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/poolShares.ts
- ironfish/src/mining/soloMiner.ts
- ironfish/src/rpc/adapters/adapter.ts
- ironfish/src/rpc/adapters/ipcAdapter.test.ts
- ironfish/src/rpc/adapters/ipcAdapter.ts
- ironfish/src/rpc/adapters/memoryAdapter.ts
- ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts
- ironfish/src/rpc/adapters/tcpAdapter.ts
- ironfish/src/rpc/adapters/tlsAdapter.ts
- ironfish/src/rpc/clients/client.ts
- ironfish/src/rpc/clients/index.ts
- ironfish/src/rpc/clients/ipcClient.ts
- ironfish/src/rpc/clients/memoryClient.ts
- ironfish/src/rpc/clients/socketClient.ts
- ironfish/src/rpc/clients/tcpClient.test.ts
- ironfish/src/rpc/clients/tcpClient.ts
- ironfish/src/rpc/clients/tlsClient.ts
- ironfish/src/rpc/server.ts
- ironfish/src/sdk.test.ts
- ironfish/src/sdk.ts
- ironfish/src/testUtilities/routeTest.ts
This renames them to be inline with the RPC system, and makes clients
names consistent with adapter names.
```
IronfishClient -> RpcClient
IronfishRpcClient -> RpcSocketClient
IronfishIcpClient       -> RcpIpcClient
IronfishTcpClient       -> RcpTcpClient
IronfishSecureTcpClient -> RcpTlsClient
MemoryClient            -> RpcMemoryClient
IAdapter -> IRpcAdapter
SocketAdapter -> RpcSocketAdapter
IpcAdapter    -> RpcIpcAdapter
TcpAdapter    -> RpcTcpAdapter
TlsAdapter    -> RpcTlsAdapter
MemoryAdapter -> RpcMemoryAdapter
```
Ran the node, and build the project
```
[ ] Yes
[x] No
```
> Rename all RPC adapter classes

- ironfish/src/mining/stratum/stratumServer.ts
- ironfish/src/mining/stratum/stratumServerClient.ts
It should never be undefined, but this provides us a guarantee
Run the pool
```
[ ] Yes
[x] No
```
> Don't accept clients without a remote address

- ironfish/src/fileStores/config.ts
- ironfish/src/mining/stratum/stratumServer.ts
Introduce a tracker which counts the number of active connections to the pool per external IP-address. If the maximum number is reached, decline future transactions. 
```
[ ] Yes
[x] No
```
> pool: limit number of concurrent tcp connections per ip

- ironfish-cli/Dockerfile
Updated node.js to the latest LTS stable version 16.15.1 from 16.13.0.
The new version is 7 version ahead of the previous version. The new version was released on June 1st 2022, and is 7 months and 5 days ahead of the previous version.
None needed
```
[ ] Yes
[✓ ] No
```
graffiti: ironfishup
> Updated nodejs

- ironfish-cli/src/commands/miners/pools/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/webhooks/webhookNotifier.ts
- hyperlinks block header hash hex string and transaction hash hex string to
block explorer
- changes message in transaction success to indicate transaction created, but
pending
created discord server and webhook, tested messages with local pool
```
[ ] Yes
[X] No
```
> feat: adds links to block explorer in webhook messages

- ironfish/src/mining/stratum/stratumClient.ts
This matches the reconnect delay time we have in our normal connection
process here, https://github.com/iron-fish/ironfish/blob/6dfc736e0f1fbfeeebaeb67962d7c73bc3072626/ironfish/src/mining/stratum/stratumClient.ts#L89
Run node and force disconnects
```
[ ] Yes
[x] No
```
> Add reconnect timeout to disconnect

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/GENERAL.yml
- .github/ISSUE_TEMPLATE/PROPOSAL.yml
- CONTRIBUTING.md
- README.md
This brings a much needed update to our contributor documentation. We're seeing a lot of third party contributors to our repository. Many of these bug fixes are great, but some of them are doing things we want to discourage. This tries to outline what those things are, and gives examples of them.
It also creates a new simple recommendation for making a change that goes against the rules, by filing a Fish Improvement Proposal (FIP).
- Updates CONTRIBUTING.md
- Adds a new FIP proposal issue template
- Updates README.md to mention CONTRIBUTING.md
No tests needed
```
[ ] Yes
[x] No
```
> Update CONTRIBUTORS.md and supporting information

- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/memPool/memPool.test.ts
- `ironfish/src/memPool/memPool.test.ts` doesn't need to loop through block txs to get the miner's fee. use the first block.
- code comment in `ironfish/src/genesis/genesis.test.slow.ts` is not needed. should've been removed with https://github.com/iron-fish/ironfish/commit/5beeedc2f5cd149da04379aed8c92bd48f52741a.
run yarn test
```
[ ] Yes
[x] No
```
> small test script cleanup

- ironfish-cli/src/commands/miners/start.ts
- ironfish/src/mining/poolMiner.ts
- ironfish/src/mining/stratum/stratumClient.ts
background:
the StratumClient and MiningPoolMiner are tightly coupled -- an instance of one
type holds a reference to an instance of the other type. this coupling makes it
difficult to use StratumClient without a MiningPoolMiner. a developer might want
to do this if they were to implement their own miner, or if they wanted to use
the StratumClient to receive messages outside of a mining context (e.g., to get
status information from the pool).
- removes miner property from StratumClient
- modifies StratumClient to emit message bodies after validating
tested with local mining pool and miner
```
[ ] Yes
[X] No
```
> decouples StratumClient from MiningPoolMiner

- .github/CODEOWNERS
- .github/ISSUE_TEMPLATE/BUG-REPORT.yml
- .github/ISSUE_TEMPLATE/GENERAL.yml
We renamed the engineering group, so update the CODEOWNERS for this repository.
N/A
```
[ ] Yes
[x] No
```
> chore(): Fix CODEOWNERS to use `@iron-fish/engineering`

- ironfish-cli/src/commands/accounts/address.test.ts
- ironfish-cli/src/commands/accounts/address.ts
- ironfish/src/rpc/routes/accounts/getPublicKey.ts
I'm doing this because I think this is a more common terminology for
this concept. Yes, it is a public key but most users in our community
know this as the address. I created an alias so the old command is still
usable.
Delete your build folder in ironfish-cli and rebuild, then run the commands.
```
[ ] Yes
[x] No
```
> Rename accounts:publickey to accounts:address

- ironfish/src/syncer.ts
This would lead to a hanging promise, a crafty bug.
Run the node
```
[ ] Yes
[x] No
```
> Fix not canceling the syncer event loop on stop

- ironfish/package.json
- yarn.lock
v0.17.1 of libdatachannel had a notable memory usage improvement on a per-Peer basis: https://github.com/paullouisageneau/libdatachannel/releases/tag/v0.17.1 So it'd be nice to see if this improves performance/memory usage with high peer counts (e.g. the bootstrap node)
Node should connect as expected.
```
[ ] Yes
[X] No
```
> Update node-datachannel to 0.3.4

- ironfish/src/mining/pool.ts
- ironfish/src/mining/stratum/stratumPeers.ts
- ironfish/src/mining/stratum/stratumServer.ts
- ironfish/src/mining/webhooks/webhookNotifier.ts
This adds a new StratumPeers system, which tracks bad clients and bans them. It also manages ban timers, and punishment timers. This also ports the old badClients concept into a shadow ban, which is needed because we don't reject peers with bad versions yet.
Run pool, and connect with malicious client.
```
[ ] Yes
[x] No
```
> Add stratum server peer management

- ironfish/src/network/peers/peerManager.ts
While testing out #1683, I noticed that extra block messages were being sent in a network of 3 connected nodes. I found that we were filtering out knownPeers from the PeerList message we send in response to PeerListRequest message. This seems like a convenient bandwidth optimization, but since we also use knownPeers for reducing bandwidth as part of our gossip strategy, it causes extra gossip messages to be sent.
I suspect that transaction and block bandwidth will likely outweigh the bandwidth saved from not including known peers in the PeerList response. The upcoming block/transaction gossip model won't rely on knownPeers either.
See the example below:
In this example, we have 3 nodes: A, B, and C. Each node is connected to each other node. If, as Node A, I'm aware that Node B is …
> Send known peers in PeerList message

- ironfish/src/mining/stratum/stratumPeers.ts
- ironfish/src/mining/stratum/stratumServer.ts
When a stratum client is banned and reconnects, resend the ban so they know whey they are rejected. This uses more bandwidth during a DDOS attack but I think the usability improvement is ok. It's split into 2 commits, one is refactoring the send() method to take a socket so we can send data to sockets that aren't fully connected into clients.
I throw this into the subscribe call...
```javascript
if (Math.random() > 0.33) {
this.peers.ban(client, {
message: `Invalid public address: ${client.publicAddress}`,
})
return
}
```
```
[ ] Yes
[x] No
```
> Resend ban to StratumClient on reconnection

- ironfish-cli/src/commands/miners/pools/start.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/stratum/stratumPeers.ts
- ironfish/src/mining/stratum/stratumServer.ts
This is in case people don't want it, or we need an escape hatch if this ends up over banning people.
Run the pool and enable / disable the option and set the version wrong, or send wrong messages.
```
[ ] Yes
[x] No
```
> Add option to disable miner pool client banning

- ironfish/src/account/accounts.ts
- ironfish/src/account/database/decryptableNotes.test.ts
- ironfish/src/account/database/decryptableNotes.ts
Store serialized notes that are decryptable by accounts in the node directly in the database. This enables fetching unspent notes (and computing balance) much faster. We can also remove the worker pool job.
Covered by existing unit tests.
```
[x] Yes
[ ] No
```
> feat(ironfish): Store serialized notes in the accounts db

- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/account/database/meta.ts
Part 1 of 2 for changing the meta store to the new format: rename `defaultAccountName` to `defaultAccountId` and associated changes.
These changes were just to make the internal logic more consistent around using the id. I think another improvement to consider is making the functions on `accounts` all work off id instead of name, but need to think through that more and didn't want to gum up this PR too much
```
[ ] Yes
[ ] No
```
> Change defaultAccountName in db to defaultAccountId

- ironfish/src/account/accountsdb.ts
Compared timing of `loadTransactionsFromDb` in `accounts.ts` with the ~100k note/transaction datadir:
Before: ~4300ms
After: ~1900ms
Closes IRO-2255
```
[ ] Yes
```
> Use `getAllIter()` to fetch key and value when loading accounts data

- ironfish-cli/src/commands/status.ts
This was confusing to users because it wouldnt show your progress if it
hasn't found a peer to sync from. From https://discord.com/channels/771503434028941353/816795916627345450/992069044591145021
Run tests and run locally
```
[ ] Yes
```
> Always show syncer progress if not synced

- ironfish/src/account/account.ts
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.ts
- ironfish/src/common/constants.ts
- ironfish/src/primitives/note.ts
- ironfish/src/primitives/noteEncrypted.ts
- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/tasks/__fixtures__/decryptNotes.test.ts.fixture
- ironfish/src/workerPool/tasks/decryptNotes.test.ts
- ironfish/src/workerPool/tasks/decryptNotes.ts
- ironfish/src/workerPool/tasks/handlers.ts
- ironfish/src/workerPool/tasks/workerMessage.ts
- ironfish/src/workerPool/worker.ts
We currently decrypt notes in the main thread when syncing transactions in the accounts module. This code change migrates this processing to the worker pool.
Note: We return a `serializedNote` from the worker job. This is currently unused in `staging`, but is part of the other broader accounts changes.
Created unit tests for serialization; existing unit tests should cover logic.
```
[ ] Yes
```
> feat(ironfish): Move note decryption when syncing transactions to worker pool

- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/mining/manager.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/primitives/transaction.test.slow.ts
- ironfish/src/primitives/transaction.ts
- ironfish/src/rpc/routes/chain/followChain.ts
- ironfish/src/rpc/routes/chain/getBlock.ts
- ironfish/src/rpc/routes/chain/getBlockInfo.ts
- ironfish/src/rpc/routes/chain/getTransactionStream.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.ts
- ironfish/src/testUtilities/mocks.ts
For P2P transaction gossip we need a hash of the transaction that commits to the witness (signature). We will use this hash to record which transactions have been gossiped to which peers. Zcash's [ZIP-239](https://zips.z.cash/zip-0239#motivation) provides a good explanation of this need and how using a hash that does not commit to the witness can be a security flaw for transaction gossip
```
[ ] Yes
[X] No
```
> Add witness hash method to transactions

- ironfish-cli/src/commands/chain/export.ts
Currently, block sequence is displayed as a number of processed blocks in a progress bar. This can lead to incorrect number if user passed a block to start from:
This PR fixes this issue:
Tested locally
```
[ ] Yes
```
> Fix chain:export progress bar

- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/types.ts
- ironfish/src/telemetry/telemetry.ts
- ironfish/src/utils/enums.ts
As part of transaction gossip we want to see how much bandwidth we are using to send and received transaction messages. We could combine this work by just adding telemetry metrics for every message type. 
Tested on local node
```
[ ] Yes
[X] No
```
> Telemetry for network bandwidth usage per message type

- ironfish/src/telemetry/telemetry.ts
The default map iterator uses entries()
Run normal tests
```
[ ] Yes
```
> Remove .entires() call on iterating a map

- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/syncer.ts
Adds a knownBlockHashes LRU to peers. This isn't particularly useful with the current block propagation model, but will be used for the next one.
One potentially dangerous area is the gossip was changed to add the block hashes to all knownPeers and determine whether to rebroadcast the message based on the presence of the hash on a peer, rather than looking at the peer's knownPeers directly.
This doesn't cause any problems in testing, and I think the only potential edge cases would be if a peer is rapidly connecting and disconnecting, causing the LRU to get reset, but a block shouldn't get rebroadcast for an extended duration regardless.
Fixes IRO-2226
Added a test for gossip, and tested gossip between a network of 3 peers. …
> Track known block hashes on Peers

- ironfish-cli/src/commands/start.test.ts
- ironfish/src/account/account.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
This copies references to data structures in the wallet to an individual account to improve the account behavior, primarily fetching unspent notes. Currently, the entire map is passed into the account - it will be partitioned by account IDs in a subsequent PR.
```
[ ] Yes
```
> refactor(ironfish): Move decryptedNotes into Account

- ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/mining/manager.test.slow.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/primitives/transaction.ts
- ironfish/src/testUtilities/mocks.ts
We need to gossip transactions by a hash that includes the transaction signature. For this we will also need to add the ability to query the mempool by that hash. Currently the mempool references hash by the unsignedHash. Read more about necessity of the new hash in the [Coda](https://coda.io/d/Gossip_d7HSvA-Pxcz/Transaction-Gossip-Research_sulxZ)
Unit tests + dev testing on network
```
[ ] Yes
```
> Replace transaction hashing method in mempool

- ironfish/src/account/account.ts
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
Remove nullifier to note hash mapping from wallet and encapsulate behavior inside account
```
[ ] Yes
```
> refactor(ironfish): Encapsulate `nullifierToNote` inside account

- README.md
Want to make it clear that we expect normal users to use npm, brew, docker etc instead of building from source, as the other methods are much easier to use
```
[ ] Yes
```
> Update README with information about preferred installation methods

- ironfish/src/account/account.ts
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.test.ts
- ironfish/src/account/accounts.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
Move interactions for the transaction map into the account. This still has all transactions for each account, that will be updated in a subsequent PR since this focuses on encapsulation
```
[ ] Yes
```
> refactor(ironfish): Encapsulate transactions inside account

- ironfish/src/network/messageRegistry.ts
- ironfish/src/network/messages/pooledTransactionsRequest.test.ts
- ironfish/src/network/messages/pooledTransactionsRequest.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/types.ts
Outlined in the [transaction gossip proposal](https://coda.io/d/Gossip_d7HSvA-Pxcz/Transaction-Gossip_sulxZ#_luNdn). We should create a new network message that allows nodes to query for transactions by hash. This would be in response to receiving a new gossiped hash from a node.
```
[ ] Yes
```
> Create network message for querying for transactions based on hash

- ironfish/src/network/peerNetwork.ts
- ironfish/src/node.ts
- ironfish/src/telemetry/telemetry.ts
Outlined in the [transaction gossip proposal](https://coda.io/d/Gossip_d7HSvA-Pxcz/Transaction-Gossip-Proposal_suP5z#_luhjb). We want to be able to measure transaction propagation speed similar to how we do with block propagation. We should add this to telemetry
Local testing
```
[ ] Yes
```
> Log transaction propagation to telemetry

- ironfish/src/telemetry/telemetry.ts
RollingAverage can produce a negative number which seems
like it should be a bug. Investigate then delete this TODO.
```
[ ] Yes
```
> Clamp telemetry floats to 0

- ironfish/src/account/account.ts
- ironfish/src/account/accounts.ts
* Only return mapping of account IDs -> decrypted notes if notes are available to remove unnecessary `syncTransaction` calls
* Check if transactions need to be updated before hitting the DB
```
[ ] Yes
```
> feat(ironfish): Only sync transactions for accounts that can decrypt notes

- ironfish-cli/src/commands/accounts/rescan.ts
- ironfish/src/account/accounts.ts
- ironfish/src/rpc/routes/accounts/rescanAccount.ts
This adds a couple of improvements to rescan
- Simplifies the flags
- Throws an error if we manage to do this on an unloaded
accounts
- Warns if we start a scan and a scan was not started
Run rescan
```
[ ] Yes
```
> Minor rescan improvements

- ironfish/src/account/accounts.ts
- ironfish/src/node.ts
When were rescanning, we start a scan, then wait for the lock on the
updateHead() method. However, this may take a long time. It's possible
the head updating was aborted because the node is shutting down. The
issue is that we don't also check if the scan was aborted as soon as
the updateHead() lock is released.
This means we could start scanning when the node is shutting down which
will prevent it from shutting down properly.
1. Have a lot of blocks to scan
2. `yarn start  accounts:rescan --reset --local`
3. `yarn start start`
4. Close node in the middle of the reset
5. Start node, it'll start updating the head right away but it will take a long time
6. `yarn start  accounts:rescan --reset`
* This should get stuck at waiting for scan to start
7. `ironfish stop`
Is this a breaking change? …
> Abort rescan if aborted after waiting for head

- ironfish/src/fileStores/config.ts
- ironfish/src/mining/stratum/messages.ts
- ironfish/src/mining/stratum/stratumPeers.ts
- ironfish/src/mining/stratum/stratumServer.ts
We now require the stratum client version and enable banning. Users should upgrade to 37 before 39 is released.
Modify client to send lower version, or undefined version and see what happens.
```
[x] Yes
```
> Require stratum client version

- ironfish-cli/src/commands/miners/pools/status.ts
- ironfish-cli/src/commands/miners/start.ts
- ironfish/src/mining/pool.ts
- ironfish/src/mining/poolMiner.ts
- ironfish/src/mining/stratum/messages.ts
- ironfish/src/mining/stratum/stratumClient.ts
- ironfish/src/mining/stratum/stratumServer.ts
- ironfish/src/mining/stratum/stratumServerClient.ts
Add miner name for each mining server/PC to distinguish different physical machines. For example, if I run 2 mining server on official pool and one of them is down, for now I have to check the mining log for each server. With this PR, I can realize which one is down immediately with miners:status command.
Local test.
```
[ ] Yes
```
> FEAT: more miner status info

- ironfish/src/account/accounts.ts
- ironfish/src/blockchain/blockchain.ts
Still technically updates all accounts in the syncTransaction call, but now updates the outdated accounts so that we can save progress if we stop it for any reason
```
[ ] Yes
```
> scanTransactions updates progress incrementally

- ironfish/src/account/accounts.ts
**Builds on #1775**
Scans transactions for accounts that are specifically relevant, so we aren't scanning transactions for accounts that don't need it, and don't "set back" account progress
```
[ ] Yes
```
> Only scan transactions for accounts where it is relevant

- ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
Adds a handler for GetBlockTransactionsRequest, which responds with the transactions on a given block corresponding to the differentially-encoded indexes.
Note that this message isn't sent in the block propagation code yet.
Added tests for the message handler.
```
[ ] Yes
```
> Add handler for GetBlockTransactionsRequest

- ironfish/src/account/accounts.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
If you submit transactions that make it onto the main chain on an account and import that account (in a separate directory, machine, etc.), your transactions will show as `pending` since `submittedSequence` was never populated for these records. That value is only set for locally initiated transactions. We should update the check to use `blockHash`. This PR also updates the status to include a `forked` status.
cc @wd021 
Manual test
```
[ ] Yes
```
> fix(ironfish): Remove `submittedSequence` check in `accounts:transactions`

- ironfish-rust/src/merkle_note.rs
- ironfish-rust/src/note.rs
- ironfish-rust/src/receiving.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/tests.rs
- Add derived `Default` trait
- Change usage of `Memo([0; 32])` to `Memo::default()`
There looks like some other cleanup we can do, specifically around serializing/deserializing, but this is a good easy win
```
[ ] Yes
```
> Add default trait to memo for better memo ergonomics

- ironfish/src/network/messages/pooledTransactions.ts
This should be using PooledTransactionResponse rather than PooledTransactionRequest.
```
[ ] Yes
```
> Fix message type on pooled transaction response

- ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/testUtilities/mocks.ts
Outlined in the [transaction gossip proposal](https://coda.io/d/Gossip_d7HSvA-Pxcz/Transaction-Gossip_sulxZ#_luNdn). Currently we determine whether to process a transaction or not based on if we've seen the nonce value the transaction message is sent with. This will not be viable once we move to gossiping transactions by hash instead of the full transaction because we will not have the nonce, only the hash. This PR replaces the nonce check with 3 other checks to determine if we need to process the transaction or not.
1) Does the transaction need to be synced to the wallet?
2) Does the transaction need to be synced to the mempool?
3) Do we have any peers that have not yet seen this transaction that we need to send it to?
For the 3rd check this PR also adds an RLU cache per peer that stores …
> Replace gossip nonces with peer seen transaction filter

- ironfish-cli/src/commands/debug.ts
This will be helpful to debug out of memory issues and see if people
have increased this some how, or have less than expected.
New Output:
```
Iron Fish version       0.1.38 @ src
Iron Fish library       0.0.16 @ src
Operating system        Darwin arm64
CPU model(s)            Apple M1 Pro
CPU threads             10
RAM total               16.00 GiB
Heap total              4.01 GiB
Node version            v16.15.1
ironfish in PATH        true
Telemetry enabled       false
```
Run debug, no test needed.
```
[ ] Yes
```
> Show max heap sizes in debug command

- ironfish/src/account/account.ts
Reduced destructuring to keep fields that belong to models on those
models. In one example were hiding a reference to an existing variable
because of a destructure.
-
```
[ ] Yes
```
> Try to keep models intact

- ironfish-cli/src/commands/debug.ts
FIP: #1858
Adding nodeName and blockGraffiti information to debug command via sdk.config.get()
```
[ ] Yes
```
> Add nodeName and blockGraffiti to debug command

- ironfish-rust-nodejs/Cargo.lock
- ironfish-rust-nodejs/Cargo.toml
- ironfish-rust/Cargo.lock
- ironfish-rust/Cargo.toml
- ironfish-rust/src/keys/mod.rs
- ironfish-rust/src/keys/public_address.rs
- ironfish-rust/src/merkle_note.rs
- ironfish-rust/src/merkle_note_hash.rs
- ironfish-rust/src/note.rs
- ironfish-rust/src/receiving.rs
- ironfish-rust/src/serializing.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/tests.rs
Version bumps of all of the librustzcash related deps as they tend to move in lock-step. Also re-organized the list so it's alphabetical and bumped up all of the other rust lib versions as well. Specifically needed to get us to >0.11 for `bellman` for the batch proof verification.
```
[ ] Yes
```
> Upgrade rust dependencies

- ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/peers/peerManager.ts
Outlined in the [transaction gossip proposal](https://coda.io/d/Gossip_d7HSvA-Pxcz/Transaction-Gossip_sulxZ#_luNdn). Create an rolling bloom filter that stores which transaction hashes different peers have seen.
```
[ ] Yes
```
> Replace gossip nonce filter with seen transaction filter

- ironfish/src/network/messageRegistry.ts
- ironfish/src/network/messages/getCompactBlock.test.ts
- ironfish/src/network/messages/getCompactBlock.ts
- ironfish/src/network/messages/newBlockV2.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/types.ts
- ironfish/src/network/utils/block.ts
Adds a GetCompactBlock RPC message for the new block propagation model. The handlers will come in future PRs.
Fixes IRO-2315
Fixes IRO-2316
Added tests for the messages.
```
[ ] Yes
```
> Create GetCompactBlock request and response messages

- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/index.js
- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish-rust/src/receiving.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
- ironfish/src/workerPool/pool.ts
- ironfish/src/workerPool/tasks/handlers.ts
- ironfish/src/workerPool/tasks/verifyTransactions.ts
- ironfish/src/workerPool/tasks/workerMessage.ts
- ironfish/src/workerPool/worker.ts
This includes a new worker task to verify multiple transactions at a time, which allow us to batch the spend and receipt proof verification. This was a new feature added in bellman 0.11 or 0.12, which lets us speed up the computation time required for verifying blocks.
This will improve speeds in the following scenarios:
- Block syncing (both actual syncing and when new blocks are gossiped)
- Block template verification (when miners find a block)
Here are some benchmarks:
Note that "batch w/ multicore" was a test using `verify_multicore` on the batch verifiers instead of the plain `verify`. This uses an internal-to-bellman `rayon` threadpool. I opted to not include this, as the speed-up is minor and I suspect it might cause issues on machines with less than 8 threads, although I don't …
> Batch verify transactions

- ironfish-cli/src/commands/peers/list.ts
- ironfish-cli/src/commands/status.ts
This will enable rendering of full-width unciode characters in terminals which replaced this characters to '??', '?', ''
I turned on this options in 2 places of code, status command (with possible issue in node name and graffiti) and peers list comand with -fenas flag (here we can get issue with node name).
Local testing
```
[ ] Yes
```
> Enable fullUnicode rendering for blessed

- ironfish/src/utils/time.test.ts
- ironfish/src/utils/time.ts
This new function is useful when rendering milliseconds as human amounts
of time. IE: 1150 milliseconds is 1s and 150ms. Useful for count downs,
or estimations.
Run new tests
```
[ ] Yes
```
> Add new renderSpan() to render time to human text

- ironfish-cli/bin/ironfish
- ironfish-cli/package.json
- ironfish-cli/src/commands/debug.ts
Exposing the garbage collector is a useful thing for developers. We can
start taking advantage of it in new memory bench marking tools that can
do certain things if the GC is exposed.
1. Run debug command with yarn
2. Run debug command with ./bin/ironfish with `IRONFISH_EXPOSE_GC` as `true`
```
[ ] Yes
```
> Add IRONFISH_EXPOSE_GC to expose garbage collector

- ironfish/src/storage/database/store.ts
These types let you extract the key and value from an IDatabaseStore
type. How to use:
```typescript
const store = db.addStore<{ key: string, value: AccountsValue }>(...)
type key = DatabaseStoreKey<typeof store> // string
type value = DatabaseStoreValue<typeof store> // value
```
Types only, no tests.
```
[ ] Yes
```
> Add DatabaseStoreValue and DatabaseStoreKey

- ironfish/src/account/accountsdb.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/indexers/minedBlocksIndexer.ts
- ironfish/src/mining/stratum/stratumClient.ts
- ironfish/src/mining/stratum/stratumServer.ts
- ironfish/src/mining/stratum/version.ts
- uses `VERSION_<PROTOCOL | DATABASE>[_<name>]` as a standard pattern for
version constants
- exports version constants for chain database, account database, and mined
block indexer so that they can be accessed in sdk clients
```
[ ] Yes
```
> standardizes naming of version constants

- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/store.ts
- ironfish/src/storage/levelup/store.ts
Need this for migrations
Added new tests
```
[ ] Yes
```
> Support IDatabaseStore.clear() in a transaction

- ironfish/src/account/database/decryptedNotes.ts
The field was already made not null, but the encoding was not updated to match.
Run encoder tests
```
[ ] Yes
```
> Make DecrypytedNote transactionHash enc not null

- ironfish/src/merkletree/merkletree.test.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/database.ts
- ironfish/src/testUtilities/helpers/merkletree.ts
- ironfish/src/testUtilities/helpers/storage.ts
We need the ability to create non unique stores in the DB layer. The
only reason we even had this restriction is because of indexed DB. It
will only be used during migrations.
Run new tests.
```
[ ] Yes
```
> Allow non unqiue IDatabaseStore

- ironfish-rust-nodejs/Cargo.lock
- ironfish-rust/Cargo.lock
- ironfish-rust/Cargo.toml
A follow-up to https://github.com/iron-fish/ironfish/pull/1901 which pinned it in the lock file via `cargo update -p libc`. This feels a little more "explicit"
```
[ ] Yes
```
> Add explicit version pin instead of hoping that our Cargo.lock doesn't get reset for any reason

- ironfish-cli/src/commands/migrations/start.ts
- ironfish/src/logger/index.ts
- ironfish/src/migrations/migration.ts
- ironfish/src/migrations/migrator.ts
If you wanted logging in migrations you would need to use console.log,
but now we generate a logger per migration with a tag that has the
migration name. We also use logger levels, to silence it so we don't
need a conditional logger.
1. Run `migrations:start`
2. Run `migrations:start --quiet`
3. Run `migrations:status`
```
[ ] Yes
```
> Support logging in migrations

- ironfish-cli/src/commands/migrations/start.ts
- ironfish/src/migrations/migration.ts
- ironfish/src/migrations/migrator.ts
This will allow you to abort the migration after it's been run. If you
pass this, it will only try to run the last migration.
Run migrations with dry run and ensure no writes occurred by re-running the migration.
```
[ ] Yes
```
> Add dry run support to migrator

- ironfish-cli/src/commands/chain/importSnapshot.ts
- ironfish-cli/src/commands/service/snapshot.ts
when using `service:snapshot` to create a snapshot, the resulting zip file
contains a directory matching the database name. if a user later imports that
snapshot then the database name in the snapshot shouldn't need to match the name
that their node uses.
- uses `strip` to remove the database directory on unzip
- creates a 'snapshot' directory and unzips the contents of the snapshot there
before moving to the user's database directory
- fixes snapshot to create directories on 'path', importSnapshot to resolve
'path'
- run `ironfish start --datadir=~/.ironfish-new --database=new` to create a new node with a small db
- run `ironfish service:snapshot --datadir=~/.ironfish-new --path=~/.test-new --database=new` to snapshot the database
- run `fish chain:importSnapshot …
> removes database name from snapshot on unzip

- ironfish-cli/src/commands/chain/importSnapshot.ts
- ironfish-cli/src/commands/service/snapshot.ts
- ironfish/src/fileStores/config.ts
snapshots are written to and downloaded to a random directory within the
system's `$TEMPDIR`. this can create duplicate snapshots and downloads and makes
the snapshots difficult to find.
- adds `tempDir` getter to config
- replaces os tempDir with node tempDir in snapshot commands
built atop #1911
- run `ironfish start --datadir=~/.ironfish-new` to create a new node with a small database
- run `ironfish service:snapshot --datadir=~/.ironfish-new `
- `ls ~/.ironfish-new/temp/ironfish_snapshot.tar.gz`
- run `ironfish chain:importSnapshot --datadir=~/.ironfish-new` (downloading the snapshot from s3 will take a long time, but  you can see that the file is going into `~/.ironfish-new/temp/`) …
> adds 'temp' directory in dataDir, uses it in snapshot commands

- ironfish/src/account/accounts.test.ts
This is now failing on this branch because accounts are in memory.
None
```
[ ] Yes
```
> Fix test for duplicate key import

- ironfish-cli/src/commands/chain/importSnapshot.ts
- ironfish-cli/src/commands/service/snapshot.ts
- ironfish-cli/src/utils/snapshot.ts
- ironfish/src/fileStores/config.ts
- moves DEFAULT_BUCKET_ constant to ironfish-cli
- changes constant to bucket instead of URL
- builds bucketUrl from bucket name and uses `s3-accelerate` in URL to use
transfer acceleration
- changes flag on snapshot from bucketUrl to bucket
```
[ ] Yes
```
> uses s3 transfer acceleration for snapshot downloads

- ironfish-cli/src/commands/chain/readd-block.ts
- ironfish-cli/src/commands/deposit-all.ts
- ironfish-cli/src/commands/service/sync-transactions.ts
Convert all camel case commands to snake case. We should not use commands like `chain:resetBlocks` it should always be `chain:reset-blocks`. This is the standard git uses, and the one we will use too. However, you should avoid using snake case at all cost and always try to user a single word if you absolutely can even if it's less descriptive. 
No testing needed.
```
[ ] Yes
```
No breaking changes because all commands were hidden, but they had aliases added anyway.
> Convert all camel case commands to snake case

- ironfish-cli/src/commands/chain/download.ts
- converts command name to kebab-case 🍢
- changes download confirmation to make block update clearer, removes name of
snapshot file from message
manual testing
```
[ ] Yes
```
> renames importSnapshot to chain:download

- ironfish-cli/src/commands/backup.ts
- ironfish-cli/src/commands/restore.ts
- ironfish-cli/src/commands/service/snapshot.ts
- ironfish-cli/src/utils/index.ts
- ironfish-cli/src/utils/s3.ts
- ironfish-cli/src/utils/tar.ts
Backup does not work because files are too big to not use multipart
uploads. This fixes a key command by factoring out the upload code to be
used by backup.
Run backup with a public bucket under https://s3.console.aws.amazon.com/s3/buckets
```
[ ] Yes
```
> Fix backup command by using snapshot upload

- ironfish-cli/src/commands/chain/download.ts
This is a result of joining datadir, which is always resolved from
config.
https://github.com/iron-fish/ironfish/blob/master/ironfish/src/fileStores/fileStore.ts#L16
Run `ironfish chain:download`
```
[ ] Yes
```
> Dont resolve tempDir

- ironfish-cli/src/commands/chain/download.ts
*Before*
```
Moving snapshot from... ...done
```
*After*
```
Moving snapshot from ...done
```
Run `chain:download`
```
[ ] Yes
```
> Remove dots because oclif already adds them

- ironfish-cli/src/commands/chain/download.ts
This shows up in help and helps users to understand what the URL should
be to customize it without reading our code.
```
> ironfish chain:download --help
Download and import a chain snapshot
USAGE
$ ironfish chain:download [-v] [--config <value>] [--datadir <value>] [-d <value>] [-b <value>] [-p <value>] [--confirm]
FLAGS
-b, --bucketUrl=<value>  [default: https://ironfish-snapshots.s3-accelerate.amazonaws.com] Bucket URL to download snapshot from
-d, --database=<value>   [default: default] the name of the database to use
-p, --path=<value>       Path to snapshot file
-v, --verbose            set logging level to verbose
--config=<value>         [default: config.json] the name of the config file to use
--confirm                confirm without asking
--datadir=<value>        [default: …
```
> Provide the default bucket URL in the parameters

- ironfish/src/webApi.ts
If any error occurs it would just restart syncing. Now it only assumes it should start from the genesis block if the API returns a 404, which is an expected response.
https://github.com/iron-fish/ironfish-api/blob/master/src/events/deposits.controller.ts#L41
Modify the URL And check the results of what this does.
```
[ ] Yes
```
> Dont restart syncing if the API does not respond

- ironfish-cli/src/commands/chain/download.ts
- ironfish-cli/src/commands/service/snapshot.ts
- ironfish-cli/src/snapshot.ts
- changes flag from 'bucketUrl' to 'url'
- makes default url cloudfront distribution url
- moves DEFAULT_SNAPSHOT_BUCKET definition to snapshot command -- the only place
it's used
```
[ ] Yes
```
> replaces s3 bucket url with cloudfront url in chain:snapshot

- ironfish-cli/src/commands/service/snapshot.ts
don't use local path as S3 key
manual testing of manifest upload
```
[ ] Yes
```
> uses 'manifest.json' for s3 key name

- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/telemetry/telemetry.ts
Address IRO-2362 and IRO-2363. Adds stats for total memory and OS CPU core count.
```
[ ] Yes
```
> Add total memory and OS CPU core count to startup telemetry

- ironfish/src/telemetry/telemetry.ts
Adds RSS value to periodic telemetry payload.
Adjust telemetry whitelist in API and ensure that values are being added.
```
[ ] Yes
```
> Add RSS to telemetry payload (#1917)

- ironfish-cli/src/commands/chain/download.ts
WriteStream emits 'close'. 'end' is never emitted, so the download does not
resolve at completion.
- modify `chain:download` to download the manifest instead of a snapshot, see that it finishes download successfully after change. patch for testing attached:
[test.patch.txt](https://github.com/iron-fish/ironfish/files/9274012/test.patch.txt)
```
[ ] Yes
```
>  handles 'close' event instead of 'end' event

- ironfish-cli/package.json
bumps the CLI version in order to release fix for `chain:download`
```
[ ] Yes
```
> bumps the CLI version to 0.1.43

- ironfish-cli/src/commands/chain/download.ts
There is a simple issue here in that during an error, resolve() is
called after reject() is called. This is because 'close' is ALWAYS
called no matter what if the stream finishes, or there is an error.
You can verify this if you add console logs to the writer handlers in
the staging branch.
1. Add console logs to writer handers
2. Cause an error to happen and see that 'error' is fired then 'close' is fired
3. This causes reject() then resolve() to trigger
```
[ ] Yes
```
> Dont snapshot resolve after reject

- ironfish/package.json
This is causing some REAL weird stuff if you try to install js deps
https://github.com/iron-fish/ironfish/blob/master/ironfish-rust-nodejs/package.json#L3
```
[ ] Yes
```
> rust-nodejs version is referencing the wrong version

- ironfish-cli/src/commands/chain/download.ts
This was a simple copy paste error that is being fixed. It should be _ok_ without this, but this properly cleans up the event.
Run `ironfish chain:download`
```
[ ] Yes
```
> Fix unsubscribing from the incorrect event

- ironfish/package.json
- package.json
- yarn.lock
Not in the yarn.lock either, but I learned if you `yarn install` from `/ironfish` you get it added as a dependency. If you `yarn install` from root, you do not. Fun!
```
[ ] Yes
```
> Remove unused highlight.js resolution

- ironfish/src/account/accounts.ts
- ironfish/src/node.ts
- ironfish/src/telemetry/telemetry.ts
In order to track transaction propagation we want to know when the transaction was created. Right now we log transaction propagation but not transaction creation. This means that in a certain timeframe (3hr) our best estimate for when to start looking at propagation time is the first event we see for each transaction. This is not always accurate and we could be starting in the middle of the timeframe for some transactions. Knowing when the transaction was actually first created would be useful for these queries.
```
[ ] Yes
```
> add telemetry for transaction creation

- ironfish/src/account/account.ts
- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/old/headers.ts
- ironfish/src/migrations/data/013-wallet-2/old/stores.ts
Migrate TransactionValue.sequence which we need to calculate from the Blockchain data so I'm freezing the headers store here.
Run the migration and check for crashes.
```
[ ] Yes
```
> Migrate transaction sequence for Wallet 2.0

- ironfish-cli/src/commands/chain/download.ts
For some reason fileHandle.createWriteStream() is undefined, so use the
method from the core fs module to see if this fixes it. I don't know why
the original issue is happening and we have no repro. My best guess is
that the users node libs are not correct.
This potentially fixes https://github.com/iron-fish/ironfish/issues/1972
Run `ironfish chain:download`
```
[ ] Yes
```
> Dont create file handle first for writing

- ironfish-cli/src/commands/backup.ts
- ironfish-cli/src/utils/tar.ts
This let's you only upload accounts if you want. This also fixes matching the excludes as patterns which is how the built in CLI excludes works.
Run `ironfish backup --no-mined --no-chain --acounts`
```
[ ] Yes
```
> Add the ability to exclude the chain DB in backup

- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/old/stores.ts
migration relies on block headers to set sequences in transactions during
migration. headers are present in chain database, so we need to load the chain
database as part of the accounts migration.
- creates and opens chain db at start of wallet migration
- adds old headers store to chain db instead of accounts db
- ran migration locally and verified that no transactions were dropped following changes
```
[ ] Yes
```
> loads chain database as part of wallet 2.0 migration

- ironfish-cli/src/commands/accounts/transactions.ts
The expiration was set to extended which requires the accounts:transactions 
command to be flaged with -x to show expiration sequence.
Fixes: https://github.com/iron-fish/ironfish/issues/1997
Tested successfully
No
```
[ ] Yes
```
graffiti: ironfishup
> Fix accounts:transactions to show expiration by default

- ironfish/src/account/account.ts
- ironfish/src/account/accountsdb.ts
- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/accounts.ts
- ironfish/src/migrations/data/013-wallet-2/new/balances.ts
- ironfish/src/migrations/data/013-wallet-2/new/decryptedNotes.ts
- ironfish/src/migrations/data/013-wallet-2/new/headHashes.ts
- ironfish/src/migrations/data/013-wallet-2/new/meta.ts
- ironfish/src/migrations/data/013-wallet-2/new/noteToNullifier.ts
- ironfish/src/migrations/data/013-wallet-2/new/nullifierToNoteHash.ts
- ironfish/src/migrations/data/013-wallet-2/new/stores.ts
- ironfish/src/migrations/data/013-wallet-2/new/transactions.ts
- ironfish/src/migrations/data/013-wallet-2/old/accounts.ts
- ironfish/src/migrations/data/013-wallet-2/old/headers.ts
- ironfish/src/migrations/data/013-wallet-2/old/meta.ts
- ironfish/src/migrations/data/013-wallet-2/old/noteToNullifier.ts
- ironfish/src/migrations/data/013-wallet-2/old/nullifierToNote.ts
- ironfish/src/migrations/data/013-wallet-2/old/stores.ts
- ironfish/src/migrations/data/013-wallet-2/old/transactions.ts
- ironfish/src/migrations/data/013-wallet-2/readme.md
- ironfish/src/migrations/data/index.ts
This migration will upgrade the wallet schema from 11 to 13, and prevent needing a database reset.
The migration freezes the stores for version 11, and 13 into the data folder for migration for use by the migration. You need to freeze the stores, and cannot use the stores in the wallet because they could change with a new migration introduced after this.
I've outlined all of the changes occurring in this migration here, https://github.com/iron-fish/ironfish/blob/account-migration/ironfish/src/migrations/data/013-wallet-2/readme.md#summary
1. Run migration on a wallet and check the balance afterwards to see if it's the same
2. Check the migration has run on a wallet with multiple accounts, and that it works
what …
> Add migration for Wallet 2.0

- ironfish-cli/src/commands/chain/prune.ts
- ironfish-cli/src/commands/migrations/start.ts
https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/src/flags.ts#L50
```
[ ] Yes
```
> Remove short-hand `-d` for `--dry` since it is already in use by the database flag

- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish-rust/src/transaction/mod.rs
Allows `batch_verify_transaction` to take any iterable of type `&Transaction`, which allows us to avoid extra allocations on both call sites.
- In `Transaction::verify`, we use [`std::iter::once`](https://doc.rust-lang.org/std/iter/fn.once.html) to turn the singular item into an iter over that object instead of allocating a `Vec`.
- In `verify_transactions` in the NAPI crate, we can call `iter()` to give us an iterator over the items, turning them into references, instead of having to re-allocate a `Vec` of `&Transaction`, since we already have a `Vec` of owned `Transactions` in the function.
Closes IRO-2358, IRO-2051
```
[ ] Yes
```
> Deduplicate batch verify logic

- ironfish/src/telemetry/telemetry.ts
There was a bug introduced in https://github.com/iron-fish/ironfish/pull/1981. When trying to submit without fields we throw an error. However we should check to see if fields are empty after we have concatenated default fields.
```
[ ] Yes
```
> Allow submitting telemetry without fields

- ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
- ironfish/src/network/__fixtures__/transactionFetcher.test.ts.fixture
- ironfish/src/network/messageRegistry.ts
- ironfish/src/network/messages/newTransactionV2.test.ts
- ironfish/src/network/messages/newTransactionV2.ts
- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/network/testUtilities/helpers.ts
- ironfish/src/network/transactionFetcher.test.ts
- ironfish/src/network/transactionFetcher.ts
- ironfish/src/network/version.ts
- ironfish/src/testUtilities/mocks.ts
When receiving a new transaction hash from another peer the node needs to fetch the full transaction. The fetcher defines logic for fetching the transaction from one or multiple peers as well as resolving transactions if it hears a gossip message of the full transaction. More is described in the [Transaction Gossip Proposal](https://coda.io/d/Gossip_d7HSvA-Pxcz)
Unit tests
```
[ ] Yes
```
> Create transaction fetcher and gossip transactions by hash

- ironfish/src/network/transactionFetcher.ts
When we receive a transaction hash we want to wait some time to see if we receive the full transaction from someone else before requesting it. Increasing this time to 1s because the extra 500ms should be negligible for transaction propagation and this will give some more time to receive the full transaction from the network
Tested with local network
```
[ ] Yes
```
> Increase time to wait to receive full transaction

- tools/version-bump.js
Adds a script that can be run to increment the patch versions of our npm packages.
Ran the script locally.
```
[ ] Yes
```
> Add script to bump package versions

- ironfish-cli/scripts/build.sh
We previously had some `node_mode` being downloaded to the `ironfish-cli/node_modules` folder (`tweetnacl`). When this dependency was removed in https://github.com/iron-fish/ironfish/pull/1872 `ironfish-cli/node_modules` was empty. This caused the copy command to fail because the folder was empty. Changing the copy command to be resilient to the folder being empty 
```
[ ] Yes
```
> fix docker build script

- ironfish-cli/src/commands/accounts/notes.test.ts
- ironfish-cli/src/commands/accounts/notes.ts
- ironfish/src/rpc/routes/accounts/getNotes.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.ts
each account stores decrypted notes that it owns. leveraging this store saves
some decryption time when collecting notes for the 'accounts:notes' command.
it's still necessary to iterate over transactions to decrypt notes where the
account is the spender since these are not stored on the account.
- run `accounts:notes > old.txt`
- make/checkout changes
- run `accounts:notes > new.txt`
- compare output with `diff old.txt new.txt`
```
[ ] Yes
```
> updates wallet.getNotes to read from account's decryptedNotes

- ironfish-cli/scripts/build.sh
Tried to use `rsync --ignore-missing-args` to copy files to a folder even if the folder is empty. This works for newer rsync versions but for older rsync versions the `--ignore-missing-args` flag does not exist. The macos virtual environment has the older version of rsync which is what we use to run our [homebrew deploy github action](https://github.com/iron-fish/ironfish/actions/workflows/deploy-brew.yml). So the command was failing there. Changing this to just ignore failures when copying this specific node_modules directory
Tested locally
```
[ ] Yes
```
> fix erroring of rsync command

- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/nullifierToNoteHash.ts
- ironfish/src/migrations/data/013-wallet-2/new/stores.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/accountsdb.ts
This is the first step in removing hex strings from wallet 2.0. We don't ever want to store hex strings.
Run wallet 2.0 migrations and check the balance.
```
[ ] Yes
```
> Nullifier to note to buffer

- ironfish-cli/src/commands/status.test.ts
- ironfish-cli/src/commands/status.ts
- ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/rpc/routes/node/getStatus.ts
This can be helpful for determining how much memory the mempool is using. We are importing a lot of transactions now and we may want to give users the option of limiting their mempool size. The `sizeBytes` function will help with that. Also adding it to the status command we can watch out for memory hungry mempools
Local testing and unit tests
```
[ ] Yes
```
> show mempool memory usage in status command

- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/index.js
- ironfish-rust-nodejs/src/lib.rs
- ironfish-rust/src/keys/public_address.rs
- ironfish/src/account/validator.test.ts
- ironfish/src/account/validator.ts
Just checking that a public address is a hex string of 86 characters is not enough, because it might not be a valid subgroup point when broken down into the diversifier and transmission key pair. So by properly parsing it, we validate that it is indeed an actually valid public key.
Benchmarking the perf difference:
The old node function ran in an average of 1 microsecond, the new function takes around 350 microseconds since it does a lot more work, but 0.3ms is still plenty fast for proper validation.
Closes IRO-2472
```
[ ] Yes
```
> Try to actually parse a public address for validation

- ironfish/src/primitives/transaction.ts
This shouldn't get called very often, but wallet2.0 is definitely calling it a lot
```
[ ] Yes
```
> Cache unsigned hash on Transaction, same way we cache the signed hash

- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/deposit-all.ts
- ironfish-cli/src/commands/deposit.ts
These commands currently will spin up a memory client if a node isn't running, but given the node needs to be connected to a network, it doesn't really make sense to do that. Instead, they should only try connecting to a running node.
```
[ ] Yes
```
> Force pay and deposit commands to connect to a running node

- ironfish/package.json
- ironfish/src/account/accounts.test.slow.ts
- ironfish/src/account/accounts.test.ts
- ironfish/src/blockchain/blockchain.test.perf.ts
- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/mining/manager.test.slow.ts
- ironfish/src/mining/manager.test.ts
- ironfish/src/primitives/block.test.ts
- ironfish/src/primitives/transaction.test.slow.ts
- ironfish/src/rpc/routes/chain/getBlock.test.ts
- ironfish/src/rpc/routes/chain/getChainInfo.test.ts
- ironfish/src/rpc/routes/faucet/getFunds.test.ts
- ironfish/src/rpc/routes/mining/blockTemplateStream.test.slow.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/strategy.test.slow.ts
- ironfish/src/syncer.test.ts
- ironfish/src/workerPool/job.test.slow.ts
- ironfish/src/workerPool/pool.test.ts
Fix for https://github.com/iron-fish/ironfish/issues/1968
using these default timeouts
`test` -> 5s (default)
`test:slow` -> 60s
`test:perf` -> 60s
deleting all unnecessary hardcoded timeout values
- run yarn test, yarn test:slow, yarn test:pref in `/ironfish`
```
[ ] Yes
```
> Cleanup test timeout values

- ironfish-cli/src/commands/accounts/notes.test.ts
- ironfish-cli/src/commands/accounts/notes.ts
- ironfish-cli/src/commands/accounts/transactions.test.ts
- ironfish-cli/src/commands/accounts/transactions.ts
- ironfish/src/primitives/index.ts
- ironfish/src/rpc/routes/accounts/getNotes.ts
- ironfish/src/rpc/routes/accounts/getTransaction.ts
- ironfish/src/rpc/routes/accounts/utils.ts
- ironfish/src/wallet/account.ts
each account's decryptedNotes store tracks notes that the account owns, but not
outgoing 'spender' notes that were created by transactions that the account
created.
these outgoing notes are useful for seeing a full 'statement' of an account's
activity.
outside of this sort of CLI output there's currently no need to store decrypted
outgoing notes for an account.
- defines `getTransactionNotes` account method to get decrypted note
information (incoming and outgoing) for a transaction's notes
- adds 'owner' field to accounts:transactions and accounts:notes commands. owner
makes a bit more sense here than 'spender'.
example output for `accounts:transactions -t . . .`:
```
Account: default (ebfb2c0)
Transaction: c9155dd1df98b64e6525a94a53ad831da11726e80317771e231c01f9fd9ad3c6
Status: completed …
```
> adds 'spender' notes back into accounts CLI output

- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/decryptedNotes.ts
- ironfish/src/migrations/data/013-wallet-2/new/stores.ts
- ironfish/src/rpc/routes/accounts/utils.ts
- ironfish/src/typedefs/buffer-map.d.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/database/decryptedNoteValue.test.ts
- ironfish/src/wallet/database/decryptedNoteValue.ts
- ironfish/src/wallet/wallet.ts
- changes decryptedNotes key encoding to BufferEncoding
- changes decryptedNotes storage of nullifier from string to buffer
- updates wallet-2 migration for decryptedNotes
- changes noteHashesBySequence and nonChainNoteHashes to use BufferSets to store
note hashes
- ran migrations on partially rescanned pool account
- compared output of `accounts:balance`, `accounts:notes`, `accounts:transactions` between current branch and `accounts-performance` branch
```
[ ] Yes
```
> updates account to store note hashes as buffers

- ironfish-cli/src/commands/backup.ts
Closes #2066 
The code for backup actually doesn't try to pass credentials, so this edits it to follow the pattern used in `snapshot.ts`, in which you can provide credentials via flag or via env vars and those will be passed into the `S3Client` constructor
Upload now works.
```
[ ] Yes
```
> fix #2066, allow chain backup

- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/rpc/routes/accounts/getTransaction.ts
- ironfish/src/rpc/routes/accounts/utils.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/accounts.test.ts
- ironfish/src/wallet/wallet.ts
- updates transaction stores
- updates wallet 2 migration
- removes unnecessary extra deletes from old transaction store in migrations
there is an issue with this approach -- the block explorer uses unsigned hashes,
so the `accounts:transactions -t <hash>` command needs to loop through all of
an account's transactions to find one by unsigned hash.
ran migration, tested `accounts:notes`, `accounts:transactions`
```
[ ] Yes
```
> updates wallet to store transactions by hash with signature

- ironfish/src/wallet/wallet.ts
There is a bug where we don't wait for the create account transaction to
complete before we insert the account into the in memory stores.
This leads to situations where an account is available to things like rescan,
but haven't been added to the database yet which we require. Because of the
awaits, it's possible to yield back to the code that will update the account
heads. This leads to crashes where you can load an account but it'll crash when
the headHashes table for that account is empty.
We need to wait for the TX to commit, before we expose it to in memory,
or set it as the default.
**How to Reproduce Crash**
1. Have a blockchain database with at least 10k blocks (or rescan will finish too fast)
2. Run your node with --verbose to see that it's rescanning
3. Create an account using …
> Fix create account / scan race condition

- ironfish/src/migrations/data/013-wallet-2.ts
this adds an error case to the migration in case someone tries to migrate a corrupt wallet.
Run this with a corrupt wallet, and without.
```
[ ] Yes
```
> Add error case in migration for nullifierToNote

- ironfish-cli/src/command.ts
This will be helpful when debugging user's problems. The default oclif
error catcher does not do this unless debug mode is enabled.
We need to catch ExitError now because oclif throws an ExitError even if you use this.exit(0) to exit succesfully so we forward those into oclif now.
Add some `throw new Error()` and run the command to trigger it.
```
[ ] Yes
```
> Display stack when CLI crashes

- ironfish-cli/bin/ironfish
- ironfish-cli/package.json
Source maps weren't being used, but now they will be used. They are
already included in our production bundles.
1. Add `throw new Error('Hello World')` anywhere in the code base
2. Test using `yarn start ____`
3. Test using `./bin/ironfish ____`
```
[ ] Yes
```
> Enable source maps in dev and prod

- ironfish-cli/src/commands/deposit-all.ts
I noticed my depositAll would crash without an error. We now show the
error properly so it can be debugged.
```
[ ] Yes
```
> Throw sendTransaction error in deposit-all

- ironfish-cli/src/commands/chain/download.ts
Windows users may run into EBUSY when running chain:download as the command
removes their existing chain database. increase the maxRetries from 0 to 10 to
try to get around this.
- sets maxRetries to 10
- users 'force' to ignore errors when the path does not exist instead of
checking for the path first
```
[ ] Yes
```
> retries 'rm' on chain database to address EBUSY errors

- ironfish-cli/src/commands/deposit-all.ts
Before if balance changes while creating a transaction, it would crash
before.
Throw a `NotEnoughFundsError` inside of sendTransaction to trigger this.
```
[ ] Yes
```
> deposit-all should not exit if balance changes

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.ts
- renames Accounts.removeTransaction to deleteTransaction to match Account
method
- removes hash from deleteTransaction parameters, reads it from transaction
passed to the method instead
- renames merkleHash to noteHash
purely cosmetic changes 💅 
```
[ ] Yes
```
> refactors wallet transaction deletion

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/accounts.test.slow.ts
- ironfish/src/wallet/database/accountsdb.ts
fixes transaction expiration with multiple accounts
expiring transactions on a wallet with multiple accounts may fail with `Error:
nullifierToNote mappings must have a corresponding decryptedNote`.
expiring transactions deletes the transaction from all accounts in the wallet.
each account loads all transactions and all nullifiers from the database, but
loads only the decrypted notes that it owns. the error occurs when a transaction
uses a nullifier to try to load a decrypted note that it does not own.
the solution suggested here is for each account to load only the nullifiers that
correspond to decrypted notes that the account owns. along with filtering
nullifiers by account it makes sense to filter transactions by account.
- adds test of expiring transactions on node with multiple …
> filters nullifiers and transactions by account on load

- ironfish/src/wallet/accounts.test.slow.ts
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
the `replace*` methods in the wallet database clear all keys for a datastore
before setting the key-value pairs from a map passed to the method. however,
each map might only have key-value pairs for a single account in the wallet.
this results in clearing all decrypted notes from the database whenever an
account saves its decrypted notes map.
- adds test of saving and reloading with multiple accounts
- moves `clear` out of `replace*` methods into a separate method for each
datastore
- uses `clear` in `Accounts.reset` instead of using `saveAccountsToDb` to clear
keys from the database
- adds unit test to verify decryptedNotes aren't cleared by save from another account …
> separates clearing databases from replacing keys

- ironfish-cli/src/commands/repl.ts
This adds a simple JS repl to interact with the node to read and test
data.
```bash
> ironfish repl
Examples:
Get the head block hash
> chain.head.hash.toString('hex')
Get the head block sequence
> chain.head.sequence
Get a block at a sequence
> await chain.getHeaderAtSequence(1)
List all account names
> accounts.listAccounts().map((a) => a.name)
Get the balance of an account
> await accounts.getBalance('default')
Use the RPC node/getStatus
> (await client.status()).content
Storing repl history at /Users/user/.ironfish/temp/repl_history.txt
Type .exit or press CTRL+C to quit
> await chain.getHeaderAtSequence(1)
BlockHeader {
sequence: 1,
previousBlockHash: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
noteCommitment: { …
```
> Add repl command to interact with the node

- ironfish-rust/src/proofs/circuit/create_asset.rs
- ironfish-rust/src/proofs/circuit/mint_asset.rs
- ironfish-rust/src/proofs/circuit/output.rs
- ironfish-rust/src/proofs/circuit/sapling.rs
- ironfish-rust/src/proofs/circuit/spend.rs
Test mint asset circuit with an asset created from the create asset circuit. This will still need to verify the witness path 
Added unit test
```
[ ] Yes
```
> feat(rust): Add test for minting an asset after creating it

- ironfish-cli/src/commands/debug.ts
- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/headHashes.ts
- ironfish/src/migrations/data/013-wallet-2/new/stores.ts
- ironfish/src/storage/database/encoding.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/accounts.test.ts
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
makes storage of hashes consistent with other wallet datastores.
- defines NullableBufferEncoding
- updates wallet-2 migration
ran migration
ran some accounts commands and verified output
ran the node and verified that account head hash progresses
```
[ ] Yes
```
> changes headHashes to encode values as buffers

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/__fixtures__/transactionValue.test.ts.fixture
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/database/transactionValue.test.ts
- ironfish/src/wallet/database/transactionValue.ts
changes the `transaction` field of `TransactionValue` to an instance of the
`Transaction` primitive instead of a serialized transaction buffer. avoids
defining a separate anonymous type elsewhere in wallet and avoids using spread
operator to coax TransactionValue into that type.
```
[ ] Yes
```
> deserializes transaction on TransactionValue

- ironfish/src/indexers/minedBlocksIndexer.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/errors.ts
- ironfish/src/storage/levelup/transaction.ts
You cant use db transactions across code because they buffer reads /
writes that then get committed to the DB they were created for. That
means data from one DB will accidently get written to the wrong DB.
```
[ ] Yes
```
> Prevent db tx from being used across databases

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/decryptedNoteValue.test.ts
- ironfish/src/wallet/database/decryptedNoteValue.ts
- ironfish/src/wallet/wallet.ts
- ironfish/src/workerPool/tasks/decryptNotes.test.ts
- ironfish/src/workerPool/tasks/decryptNotes.ts
DecryptedNote deserialized from worker tasks is very similar to
DecryptedNoteValue. these changes rename 'merkleHash' in DecryptedNote to 'hash'
and rename 'noteIndex' in DecryptedNoteValue to 'index'. some additional
refactoring of syncTransaction (removing account from parameters and return
values of decryptNotesFromTransaction) allows us to use the DecryptedNote type
in place of anonymous types in the wallet.
- renames merkleHash to hash
- renames noteIndex to index
- uses DecryptedNote type instead of anonymous types
```
[ ] Yes
```
> renames decrypted note fields for consistency

- ironfish/src/consensus/verifier.ts
#2037 added additional verification to new transactions to check their spends. For now, we want to allow spends with INVALID_SPEND error into accounts + mempool because we're often creating spends with tree size and root at the head of the chain, rather than a reasonable confirmation range behind it. These blocks (and spends) can become valid if the chain forks to them.
```
[ ] Yes
```
> Re-allow invalid spends into mempool and accounts

- ironfish/src/storage/database.test.ts
- ironfish/src/storage/database/database.ts
- ironfish/src/storage/database/store.ts
- ironfish/src/storage/database/types.ts
- ironfish/src/storage/database/utils.ts
- ironfish/src/storage/levelup/database.ts
- ironfish/src/storage/levelup/store.ts
This now supports key ranges for all range based database operations. That means you can use any operations like clear(), getAllKeys() filtered to a subset of rows.
This also adds a new storage utility file to help generate buffer key range prefixes easily.
Run the new written tests, and run the node.
```
[ ] Yes
```
> Add key ranges to all range based DB ops

- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/service/faucet.ts
- ironfish-cli/src/commands/status.ts
- ironfish-cli/src/utils/currency.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/mining/manager.ts
- ironfish/src/node.ts
- ironfish/src/rpc/clients/client.ts
- ironfish/src/rpc/routes/node/getStatus.ts
This expose 3 new meters in our status related to mining when you pass --all to `ironfish status`
- Time to construct a new block given transactions
- Time to calculate transactions from the mem pool for the new block
- Total time to generate a block template
```
> ironfish status --all
Version              0.1.45 @ src
Node                 STARTED
Node Name            JASON💪💎🚀
Block Graffiti       JASON💪💎🚀
Memory               Heap: 829.85 MiB -> 849.71 MiB / 4.00 GiB (20.2%), RSS: 2.68 GiB (16.8%), Free:
77.87 MiB (99.5%)
P2P Network          CONNECTED - In: 7.35 KB/s, Out: 1.88 KB/s, peers 3
Mining               STARTED - 1 miners, 0 mined, get txs: 0.0638ms, block: 30.5735ms, template:
253.2487ms
Mem Pool             Size: 0 tx, Bytes: 0 B
Syncer               IDLE - progress: 84.49% …
```
> Expose mining performance times in node status

- ironfish/src/consensus/verifier.ts
Transactions have to be turned into Rust transactions when we run verification in the worker pool anyway, so we may as well not do it on the main thread (since it's fairly slow)
```
[ ] Yes
```
> Remove unnecessary transaction verification

- ironfish/src/utils/bench.ts
Adding a `withSegment` function to `BenchUtils` was extremely useful when doing a lot of the memory benchmarking, might as well make it available to the codebase.
```
[ ] Yes
```
> Add a withSegment fn to improve ux of bench utils

- ironfish-cli/package.json
- ironfish-cli/src/commands/start.ts
This will use a randomly assigned port if the default inspect port is in use. Otherwise you get a message like this `Starting inspector on 127.0.0.1:9229 failed: address already in use` printed.
1. Run `yarn start start`
2. Run `yarn start debug`
3. See that `Starting inspector on 127.0.0.1:9229 failed: address already in use` is not printed
```
[ ] Yes
```
> Hide inspect port in use error

- ironfish-cli/jest.setup.js
- ironfish/jest.setup.js
- ironfish/src/index.test.ts
- ironfish/src/storage/database.test.ts
- ironfish/src/testUtilities/helpers/storage.ts
- ironfish/src/testUtilities/nodeTest.ts
- ironfish/src/testUtilities/utils.ts
This was taking up all the system storage, and not getting cleaned up.
This now stores all test node data directories inside of /testdbs with
our other data. This directory gets deleted at the start of each run.
Run tests, and check ./testdbs
```
[ ] Yes
```
> Store all test data in the repo

- ironfish-cli/Dockerfile
- ironfish-cli/scripts/build.sh
Takes my local docker image from like 1.3gb to 450mb
Closes IRO-2555
```
[ ] Yes
```
> Ignore /target dir in build script, minor dockerfile improvements

- ironfish-cli/src/commands/config/index.ts
- ironfish-cli/src/commands/migrations/index.ts
Feature #2092, move additional commands (`migrations:status` and `config:show`) to their respective root commands (`migrations` and `config`). Leave in original commands as aliases for now (to be deleted eventually).
- Tested both `migrations` and `config` commands to ensure they perform the same operation as `migrations:status` and `config:show`.
```
[ ] Yes
```
> Move commands migrations:status and config:show to their root commands

- ironfish-cli/src/commands/status.ts
https://linear.app/ironfish/issue/IRO-2569/dont-clear-ironfish-status-on-disconnect
local test 
```
[ ] Yes
```
> Show status response after disconnect

- ironfish-cli/src/commands/status.ts
- ironfish/src/rpc/routes/node/getStatus.ts
Addressing [this issue](https://github.com/iron-fish/ironfish/issues/2147) about the SYNCED  field on the status command being confusing. Changing the output of that status to show the time since the head block (e.g. 30s, 10m etc). I think that would be more informative that just saying chain is SYNCED which we determine by checking if the chain is less than 5 hours behind
Local tests
```
[ ] Yes
```
> Add time since HEAD timestamp to status command

- ironfish/src/metrics/meter.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/metrics/rollingAverage.ts
- ironfish/src/network/messageRegistry.ts
- ironfish/src/network/peerNetwork.ts
- ironfish/src/telemetry/telemetry.ts
- ironfish/src/utils/bench.ts
Adds telemetry messages that log, on a per-message basis, the average response time and average success rate for RPC messages.
The telemetry fields won't be added until sampling at least 10 requests, to avoid biasing the success percentage too much.
Tested locally by adding logs in development.
```
[ ] Yes
```
> Add telemetry for RPC response times and success rate

- ironfish/src/rpc/clients/ipcClient.ts
- ironfish/src/rpc/clients/socketClient.ts
- ironfish/src/rpc/clients/tcpClient.ts
Both the `IPCClient` and the `TCPClient` implemented cleaning up and rejecting all the pending requests when the connection was closed by the server. This functionality is the same for both clients so should probably be done at the `SocketClient` level. Also `IPCClient` and `TCPClient` should not be concerned with pending requests, they should only know about how to transfer data to and from the server, not the content of the data (i.e. messageId)
Local testing + unit tests
```
[ ] Yes
```
> Share close functionality between socket adapters

- ironfish/src/rpc/routes/accounts/getNotes.ts
- ironfish/src/rpc/routes/accounts/getTransaction.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/accounts.test.slow.ts
- ironfish/src/wallet/accounts.test.ts
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
reads transactions from database instead of holding all transactions in memory.
- converts all reads of transactions to use database
- removes test of loading transactions into cache
- refactors saveDecryptedNoteSequence to take a note hash and a sequence instead of loading a transaction
- updated unit tests
- ran `accounts:transactions` on migrated pool account
```
[ ] Yes
```
> evict transactions cache from account

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
- removes unnecessary conversion from undefined to null if the transaction is not in the database
```
[ ] Yes
```
> fixes loadTransaction undefined case

- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish-rust/src/receiving.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/tests.rs
We pass this around in a lot of places. These were probably more relevant before the librustzcash upgrades, but now I think it's cleaner to just use them at the specific call-sites since there's very few of them.
```
[ ] Yes
```
> Cleanup Sapling references

- ironfish/src/wallet/accounts.test.ts
- ironfish/src/wallet/wallet.ts
I realized this broke when a merge from staging changed the logic to always coerce the start points into non null value.
The test has been broken for awhile
```
[ ] Yes
```
> Fix rescan not picking up new accounts

- ironfish/src/mining/pool.ts
- ironfish/src/mining/soloMiner.ts
- ironfish/src/rpc/adapters/ipcAdapter.test.ts
- ironfish/src/rpc/clients/socketClient.ts
- ironfish/src/rpc/response.ts
- ironfish/src/rpc/stream.ts
Reported [here](https://github.com/iron-fish/ironfish/issues/2148). When a server disconnects from a client during a streaming request it causes the client to crash. This is because the handling of the disconnect error (`.catch()`) is not attached until after `reject` is called on the request. This causes the `reject` to be treated as an unhandled promise reject. This default behavior for this in node is to crash the process. This fix adds a `.catch` statement so that even if the error is ignored it still will not crash the process
Local testing
```
[ ] Yes
```
> Fix RPC stream kills process on disconnect

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/primitives/block.test.ts
- ironfish/src/primitives/block.ts
This is now consistent with Block.spends
```
[ ] Yes
```
> Rename Block.allNotes -> Block.notes

- ironfish-rust/src/primitives/asset_type.rs
- ironfish-rust/src/proofs/circuit/create_asset.rs
- ironfish-rust/src/proofs/circuit/mint_asset.rs
- ironfish-rust/src/proofs/circuit/mod.rs
- ironfish-rust/src/proofs/circuit/spend.rs
- ironfish-rust/src/proofs/circuit/util.rs
There's duplicated logic when computing the pre-image from asset info or building note contents for hashing. This change moves the repeated code into a utils file. I spent too long debugging a test and it was a minor difference between the two blocks of code.
Run this unit test for sanity:
```sh
running 1 test
test proofs::circuit::mint_asset::test::test_create_mint_asset_and_spend_circuit ... ok
```
The mint constraints are broken; I will address that in a subsequent PR.
```
[ ] Yes
```
> refactor(rust): Move note content and preimage building to util file

- ironfish-cli/src/commands/chain/benchmark.ts
Adds a `chain:benchmark` command that copies blocks from the current node to a new node to benchmark the time it takes to add blocks.
```
[ ] Yes
```
> Add chain:benchmark command for testing add block time

- ironfish-cli/src/commands/chain/benchmark.ts
This changes 3 things about the new chain:benchmark command
- Creates tempdir if it doesn't exist (would crash before) (https://github.com/iron-fish/ironfish/pull/2217/commits/6002ab6ffdb5cc94f0b248b099bbe016680d5a05)
- Waits for the node DB to become available now versus crashing (https://github.com/iron-fish/ironfish/pull/2217/commits/ba043930fcc22033b2825500ddccf0f597de05f0)
- Uses TimeUtils.renderSpan to render the bench mark time because it would round down for less than 1 second time before (https://github.com/iron-fish/ironfish/pull/2217/commits/d5f35877eed982158ba1c7eaf3342fed5f0fcfa8)
```
> ironfish chain:benchmark --datadir ~/.ironfis-bench --blocks 1
Opening node... done.
Opening temp node in /Users/jasonspafford/.ironfish4/temp/benchmark-JxFF6K... done.
Total time to import 1 …
```
> Fix benchmark crash when temp directory doesn't exist

- ironfish-cli/src/commands/chain/download.ts
our snapshot file sizes exceed cloudfront limits. there may be a file limit of 50GB (requests for files larger than this fail) and there definitely is a limit of 30GB for caching.
local testing with `chain:download` on both the old snapshot that succeeds with cloudfront and the new snapshot that fails with cloudfront
```
[ ] Yes
```
> downloads snapshots directly from s3

- package.json
- yarn.lock
We were using a very outdated version of lerna. Updating seemingly worked with no breaking changes. The 5.0 release even indicates that's likely the case.
`yarn`
`yarn test`
`yarn lint`
from root dir
```
[ ] Yes
```
> Update lerna to 5.5.2

- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/decryptedNotes.ts
- ironfish/src/primitives/note.ts
- ironfish/src/rpc/routes/accounts/utils.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/__fixtures__/decryptedNoteValue.test.ts.fixture
- ironfish/src/wallet/database/decryptedNoteValue.test.ts
- ironfish/src/wallet/database/decryptedNoteValue.ts
We're just doing the same here that we did to TransactionValue already.
Run migration again
```
[ ] Yes
```
> Have DecryptedNoteValue encoder handle Note

- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
`id` is already on AccountValue, we don't need to construct this object.
```
[ ] Yes
```
> Stop returning id and AccountValue

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/accountsdb.ts
If we just include the hash at the AccountDB level, we don't need to construct these objects further up. We should probably move hash to DecryptedNoteValue later.
```
[ ] Yes
```
> Include hash when iterating DecryptedNotes

- ironfish-rust/src/proofs/circuit/mint_asset.rs
- ironfish-rust/src/proofs/mod.rs
- ironfish-rust/src/proofs/notes/mint_asset_note.rs
- ironfish-rust/src/proofs/notes/minting_asset.rs
- ironfish-rust/src/proofs/notes/mod.rs
- ironfish-rust/src/transaction/mod.rs
Start migrating to the new pattern and move params / descriptions for minting assets into a struct
Added unit tests for mint asset proof
```
[ ] Yes
```
> feat(rust): Add parameters and abstract minting assets to notes

- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.ts
It was too hard to figure out if these were exclusive or inclusive, so they don't need to be passed around anymore.
```
[ ] Yes
```
> Changed getBalance() to take confirmations

- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/nonChainNoteHashes.ts
- ironfish/src/migrations/data/013-wallet-2/new/sequenceToNoteHash.ts
- ironfish/src/migrations/data/013-wallet-2/new/stores.ts
- ironfish/src/storage/database/encoding.test.ts
- ironfish/src/storage/database/encoding.ts
- ironfish/src/storage/database/utils.test.ts
- ironfish/src/storage/database/utils.ts
- ironfish/src/utils/buffer.ts
- ironfish/src/wallet/__fixtures__/account.test.ts.fixture
- ironfish/src/wallet/__fixtures__/accounts.test.ts.fixture
- ironfish/src/wallet/account.test.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
This PR will remove `sequenceToNoteHashes` and `nonChainNoteHashes`. These two are being moved to database stores that will be fetched from using range queries.
- Added new tests
- Rerun migration
```
[x] Yes
```
> Move account in memory caches to accounts DB

- ironfish-cli/src/commands/service/snapshot.ts
adds webhook command-line option to `service:snapshot`.
includes snapshot block sequence in webhook message.
local testing with snapshot and discord webhook
```
[ ] Yes
```
> notifies webhook after snapshot upload

- ironfish/src/wallet/wallet.ts
DepositAll command is catching an error with the error code `INSUFFICIENT_BALANCE`, but `createTransaction` was throwing a default Error, without that code, which leads the command to shut down.
```
[ ] Yes
```
> Set proper Error type and message on Insufficient funds case

- ironfish-cli/src/commands/chain/download.ts
we previously unzipped the snapshot to the 'temp' directory before moving files to the chain database. unzipping directly to the chain database directory will skip the move step and may circumvent errors users have run into while moving files
- remove contents of chainDatabasePath before unzipping
- ensure that chainDatabasePath exists
- unzip directly into chainDatabasePath
local chain:download
```
[ ] Yes
```
> unzip snapshot directly to chainDatabasePath

- ironfish-cli/src/commands/chain/download.ts
the snapshot file downloaded from s3 is ~50GB in size. after unzipping the snapshot and moving the database into place the snapshot file remains.
changes `chain:download` to automatically remove the snapshot file after a successful import.
- adds 'cleanup' and 'no-cleanup' options to `chain:download`
- factors download logic into separate method for readability
- adds error message to failed imports with direction on how to retry importing a downloaded snapshot
tested importing a snapshot locally with and without cleanup
```
[ ] Yes
```
> clean up snapshot download after import

- ironfish/src/wallet/database/accountsdb.ts
- ironfish/src/wallet/wallet.ts
Found a bunch of issues where account was put into a map or removed from it before the DB transaction would commit leading to various bugs.
```
[ ] Yes
```
> Fix exposing account before TX commits

- ironfish/src/migrations/data/013-wallet-2.ts
It was not filling out a balance for any accounts without notes which would cause crashes
```
[x] Yes
```
> Fix balance migration in 013

- ironfish-cli/src/commands/accounts/balance.ts
- ironfish-cli/src/commands/deposit-all.ts
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/rpc/routes/accounts/getBalance.ts
- ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
- ironfish/src/utils/currency.ts
- ironfish/src/wallet/account.test.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/accounts.test.slow.ts
- ironfish/src/wallet/accounts.test.ts
- ironfish/src/wallet/wallet.ts
I started this PR by trying to add an explain flag to balance. I now pass through all the data used to calculate balance through the API so that it can be explained. I'm half considering that these should be a different RPC, but we can pass them through for now.
I started creating a new CurrencyUtils because the existing one is a mess. Things that take amounts are taking numbers, which should be an immediate sign that overflow errors are happening since amounts are bigint and numbers are capped at 54 bits in Javascript. I can't go in and fix all the old places so I figure we should just start creating a new one and delete the old ones in another PR.
This also changes balance to not show the unconfirmed balance by default and hides it behind the explain flag. Too many people were getting …
> Rewrite balance command and add --explain

- ironfish-rust/src/primitives/asset_type.rs
- ironfish-rust/src/proofs/circuit/mint_asset.rs
- ironfish-rust/src/proofs/notes/mint_asset_note.rs
- ironfish-rust/src/proofs/notes/minting_asset.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
Ticket: https://linear.app/ironfish/issue/IRO-2628/clean-up-mint-asset-parameters-abstraction-and-fix-tests
Fixed in branch
```
[ ] Yes
```
> fix(rust): Clean up mint asset params and fix unit tests

- ironfish/src/consensus/consensus.ts
Reduce the time to consider the chain `SYNCED` from 5hrs to 1hr. This affects things like whether the node processes incoming transactions or not. We've been seeing that when nodes are not on the latest HEAD but are still considered `SYNCED`, the mempool starts to fill up. This is because there are potentially 5hrs worth of transactions that might be added to the mempool. If that number of transactions is too large it could cause a cycle where the node slows down and just becomes further and further behind leading to more transactions building up.
The long term solution to this would be to add an efficient limit on the size of the mempool so that when one transaction comes in, the lowest priority transaction will be evicted. Reducing the synced time however is a short term fix that will …
> Reduce synced time to 1hr (60 blocks)

- ironfish-cli/src/commands/chain/download.ts
some users may want to download snapshots to a location other than datadir/temp. for instance, a user might want to download the snapshot file to a separate mounted disk.
- adds `-o` option for full download path
local testing with `chain:download -o`
```
[ ] Yes
```
> adds output path option for snapshot download

- ironfish-cli/src/commands/accounts/remove.ts
This name was wrong, and it doesnt trim the account like the others. Should we pull out some of these so they are shared?
```
[ ] Yes
```
> Standardize account flag to match other commands

- ironfish-cli/src/commands/accounts/transactions.ts
All other account commands use an arg for the account instead of a flag
```
[ ] Yes
```
> Change transactions to use account arg

- ironfish-cli/src/commands/accounts/transaction.ts
- ironfish-cli/src/commands/accounts/transactions.ts
- ironfish/src/rpc/routes/accounts/getTransaction.ts
- ironfish/src/rpc/routes/accounts/types.ts
- ironfish/src/wallet/account.ts
Moved most of the logic out of accounts:transactions into its own command. I feel like that command was overloaded and not doing what you expect anyway. I expect when I pass a TX hash for it to display the same output, but filtered on only that transaction. Instead it has a totally alternate flow.
Run `ironfish accounts:transaction`
```
[x] Yes
```
> Move account:transaction to its own command

- ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts
- ironfish/src/rpc/adapters/tcpAdapter.test.ts
- ironfish/src/rpc/clients/tcpClient.ts
Tracking down this https://github.com/iron-fish/ironfish/actions/runs/3140473380/jobs/5101893603
```
@ironfish/sdk: node:internal/errors:464
@ironfish/sdk:     ErrorCaptureStackTrace(err);
@ironfish/sdk:     ^
@ironfish/sdk: Error: Server is not running.
@ironfish/sdk:     at new NodeError (node:internal/errors:371:5)
@ironfish/sdk:     at Server.close (node:net:1628:12)
@ironfish/sdk:     at Object.onceWrapper (node:events:509:28)
@ironfish/sdk:     at Server.emit (node:events:390:28)
@ironfish/sdk:     at emitCloseNT (node:net:1681:8)
@ironfish/sdk:     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
@ironfish/sdk:   code: 'ERR_SERVER_NOT_RUNNING'
@ironfish/sdk: }
```
what additional …
> Fix staging test failures

- ironfish/src/network/peerNetwork.test.ts
- ironfish/src/network/peerNetwork.ts
This is causing a bunch of "Received non-buffer message" disconnects. It shouldn't have been impacting peer connectivity because the message was intended to gracefully disconnect from the peer anyway, but it at least reduces network/improves peer behavior.
```
[ ] Yes
```
> Fix improperly serialized disconnect message

- ironfish/src/rpc/routes/accounts/getTransaction.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
- ironfish/src/wallet/account.ts
updates getTransaction and getTransactions to use getTransactionByUnsignedHash to load specific transactions from the account.
we need to search by unsignedHash (for now) because we use the unsigned hash for the transaction in the block explorer and cli output. users have no way of finding the other hash.
```
[ ] Yes
```
> adds method to get transaction by unsignedHash

- ironfish-cli/src/commands/accounts/notes.ts
- ironfish-cli/src/commands/accounts/transactions.ts
- ironfish/src/rpc/routes/accounts/getNotes.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
Remove the account name header from the output for `accounts:notes` and `accounts:transactions` (and correspondingly remove this field from `GetAccountTransactionsResponse` and `GetAccountNotesResponse`. The user either enters the specifies the account or the default account is used, so displaying the account name is redundant.
Ran the commands with test notes/transactions.
```
[ ] Yes
```
> Remove account name from accounts:notes and accounts:transactions output

- ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts
- ironfish/src/rpc/server.ts
Review with https://github.com/iron-fish/ironfish/pull/2269/files?diff=split&w=1
This code was constructing response manually, when we already support that through ResponseError handling in the adapter.
This is fixing this comment: https://github.com/iron-fish/ironfish/pull/2224/files#r979296411
Covered by existing tests. IT will be sending back the same thing to the client.
```
[ ] Yes
```
> Use ResponseError and don't make manual responses

- ironfish-cli/src/utils/s3.ts
- ironfish/src/blockchain/blockchain.ts
- ironfish/src/mining/stratum/errors.ts
- ironfish/src/network/peers/connections/errors.ts
- ironfish/src/rpc/adapters/errors.ts
- ironfish/src/rpc/clients/errors.ts
- ironfish/src/storage/database/encoding.ts
- ironfish/src/storage/database/errors.ts
- ironfish/src/syncer.ts
- ironfish/src/utils/json.ts
- ironfish/src/wallet/errors.ts
- ironfish/src/workerPool/tasks/jobAbort.ts
- ironfish/src/workerPool/tasks/jobError.ts
So it renders properly inside of Error.toString()
Resolves https://linear.app/ironfish/issue/IRO-2155
Create any subclass of an `Error` and use `toString()`
```
[ ] Yes
```
> Set Error.name on all Error subclass

- ironfish/src/rpc/routes/accounts/getNotes.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
- ironfish/src/rpc/routes/mining/exportMined.ts
Fix the bug where some RPCs continue streaming when the request is closed.
Ran commands locally.
```
[ ] Yes
```
> Stop streaming when the connection is closed

- ironfish-cli/src/commands/accounts/transactions.ts
- ironfish/src/migrations/data/013-wallet-2.ts
- ironfish/src/migrations/data/013-wallet-2/new/pendingTransactionHashes.ts
- ironfish/src/migrations/data/013-wallet-2/new/stores.ts
- ironfish/src/wallet/__fixtures__/account.test.ts.fixture
- ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
- ironfish/src/wallet/account.test.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.test.slow.ts
- ironfish/src/wallet/wallet.test.ts
- ironfish/src/wallet/wallet.ts
- ironfish/src/wallet/walletdb/walletdb.ts
users sending transactions want to know the status of their transactions and to know if their transactions have expired without being processed. if expired transactions are deleted from the database then there is no record that they were attempted.
changes 'deleteTransaction' to 'expireTransaction' and does not delete expired transactions from the database. still deletes notes from expired transactions from the database since the account doesn't own these notes
wallet will lose any record of expired transactions on reset since there is no history of expired transactions on the chain
sent an expired transaction, saw its status in 'accounts:transactions'
```
[ ] Yes
```
> keeps transactions in accountsdb on expiration

- ironfish/src/wallet/__fixtures__/wallet.test.slow.ts.fixture
- ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
- ironfish/src/wallet/wallet.test.slow.ts
- ironfish/src/wallet/walletdb/walletdb.ts
It's already incremented in the prefix range calculator. We generated the fixtures because stale fixtures also allowed the test to pass in the first place.
Run tests, they were passing because the fixture was stale.
```
[ ] Yes
```
> Fix expiration range not to include extra sequence

- ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
- ironfish/src/memPool/index.ts
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/memPool/priorityQueue.test.ts
- ironfish/src/memPool/priorityQueue.ts
- ironfish/src/memPool/priorityQueueTestHelpers.ts
- yarn.lock
If the mempool is very large, adding blocks takes longer because as part of adding blocks we also [remove transactions in that block from the mempool](https://github.com/iron-fish/ironfish/blob/staging/ironfish/src/memPool/memPool.ts#L145). We also remove expired transactions. Both of these actions require a [O(n) operation to remove transactions](https://github.com/lemire/FastPriorityQueue.js/blob/7b70143f3c826288bd1aeeb2b13484374e003b52/FastPriorityQueue.js#L144) from the priority queue.
Because we do a linear scan of all transactions looking for the one to delete, removing transactions takes on average n/2 calls to [hash.equals()](https://github.com/iron-fish/ironfish/blob/ed3ecac87960440c0e2627e548e50d1491695143/ironfish/src/memPool/memPool.ts#L223). Doing some profiling. with a …
> Constant delete priority queue

- ironfish/src/rpc/routes/accounts/removeAccount.ts
- ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
- ironfish/src/wallet/wallet.test.ts
- ironfish/src/wallet/wallet.ts
- ironfish/src/wallet/walletdb/walletdb.ts
Clear records in stores for a deleted account. Adds a store to keep track of IDs of accounts that have yet to be cleaned up and then processes this clean up in the background.
Ran `accounts:remove` locally.
```
[ ] Yes
```
> Update account deletion to clean up records in stores

- ironfish-cli/src/commands/status.ts
- ironfish/src/metrics/cpuMeter.ts
- ironfish/src/metrics/metricsMonitor.ts
- ironfish/src/rpc/routes/node/getStatus.ts
Adds CPU usage to the status command. Calculates the % of CPU the process is using across all cores of the operating system
Tested locally
```
[ ] Yes
```
> Add cpu usage statistics to /status command

- ironfish-cli/src/commands/chain/download.ts
some users have run into errors when downloading snapshots when they do not have enough space for both the snapshot archive and the unzipped snapshot. unzipping directly into place has the unfortunate side-effect of leaving the node in an unrecoverable state if the unzipping operation fails: the download process removes all files from the database before beginning to unzip.
these changes revert to unzipping to a temporary location before moving the snapshot files into the database
```
[ ] Yes
```
> reverts to unzipping and moving snapshot download

- ironfish-cli/src/command.ts
- ironfish-cli/src/flags.ts
- ironfish/src/fileStores/config.ts
- ironfish/src/sdk.test.ts
This flag was unused, removing it should also trigger people to know that something important has changed in our security model.
Try to pass in the flag
```
[x] Yes
```
> Remove rpcTcpSecure CLI flag

- ironfish-cli/src/commands/accounts/notes.ts
enforces uniform column width to accommodate different memo lengths between notes. each note is rendered in its own table after changing to streaming responses, so dynamic column width results in uneven columns across rows.
a column width of 33 accommodates the maximum memo length (32 bytes) plus one space between columns
Before:
After:
```
[ ] Yes
```
> sets minWidth for memo column in accounts:notes

- ironfish-cli/src/commands/status.ts
Change the node mempool status 'Size' field to 'Count' to more accurately represent that it displays the transaction count.
```
[ ] Yes
```
> Change mempool status size field to count

- ironfish/src/wallet/__fixtures__/recentFeeCache.test.ts.fixture
- ironfish/src/wallet/queue.ts
- ironfish/src/wallet/recentFeeCache.test.ts
- ironfish/src/wallet/recentFeeCache.ts
Refactor Fee estimation. https://github.com/iron-fish/ironfish/pull/2075
- Create a queue class
- Create Recent Fee Cache with add, delete and get suggest fee methods
unit tests
```
[ ] Yes
```
@hughy @NullSoldier @mirayadav
> Create Recent Fee Cache in Queue structure

- ironfish/src/fileStores/config.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.ts
This loaded all TX when creating a note and joinin its related
transaction to get its sequence.
Run existing tests, and try creating a transaction on a big account.
```
[ ] Yes
```
> Dont materialize unspent notes when creating a tx

- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/mining/manager.test.slow.ts
Use sum of transaction sizes as mempool consensus size. Rename `memPool.size()` function to `memPool.count()` to more accurately represent what it returns.
```
[ ] Yes
```
> Use consensus transaction size in mempool

- ironfish/package.json
- yarn.lock
Fix https://github.com/iron-fish/ironfish/issues/2262 by bumping node-datachannel to v0.3.6. [Mac M1 binaries were released with v0.3.6](https://github.com/murat-dogan/node-datachannel/issues/120).
```
[ ] Yes
```
> Bump node datachannel

- ironfish/src/rpc/routes/accounts/getBalance.ts
- ironfish/src/rpc/routes/accounts/getTransaction.ts
changes accounts commands to output the account name (e.g., 'default') instead of the displayName (e.g., 'default (1234567)') that includes characters from an account ID that isn't meaningful to the user.
some users have been confused by the extra characters and wondered whether they map to the account's keys somehow.
before:
after:
```
[ ] Yes
```
> uses account name instead of displayName in rpc

- ironfish-cli/src/commands/deposit.ts
Fixes https://github.com/iron-fish/ironfish/issues/2363. There's a floating precision bug on [L116 in deposit.ts](https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/src/commands/deposit.ts#L116). We could add a new decimal type, but comparing ORE rather than IRON circumvents this and we already do this in deposit-all.
Test `deposit` command. 
```
[ ] Yes
```
> Fix floating point bug

- ironfish-cli/src/commands/service/snapshot.ts
service:snapshot is failing sporadically with ENOENT errors. what seems to be happening is that between the start of the 'tar.create' and the end of it, files are removed from the database. LevelDB compaction may be running in the background and merging recent chain database changes.
manually execute database compaction prior to zipping the database to try to prevent compaction during the zip process.
The error that this aims to address is very difficult to reproduce. Local testing of creating snapshots verifies that the compaction doesn't adversely affect snapshot creation, but can't confirm that the ENOENT issue is fully resolved.
```
[ ] Yes
```
> compacts chain db before creating snapshot

- ironfish-cli/src/commands/accounts/transactions.ts
- ironfish/src/rpc/routes/accounts/getTransactions.ts
Implementation https://github.com/iron-fish/ironfish/issues/2347
```
[ ] Yes
```
> get lastest transactions

- ironfish/src/fileStores/config.test.ts
- ironfish/src/fileStores/config.ts
Fixes: https://github.com/iron-fish/ironfish/issues/1924
Adds additional validations to `ConfigOptions` by means of the `yup` API.
Added unit tests for configuration schema validations, and applying the default config against the schema.
No
null
> Validate config file options (`ConfigOptions`)

- ironfish/src/fileStores/config.ts
`nodeWorkersMax = -1` is an easy way to enable all cpu cores for workerPool. Since some miners have already work with this flag for a long time, config rules running now will force them to make some changes. And most of them have no idea about physical and logic cpu cores, it's complicated to enable all cpu cores with `nodeWorkersMax = 10 or 20`. 
```
[ ] Yes
```
> Config rules of nodeWorkersMax

- ironfish/src/storage/levelup/database.ts
compact attempts to call compactRange on the instance of levelup, but it is the db that will be an instance of LevelDOWN. changes the compactRange call to use the db instance.
resolves in the 'else' case of compact. process currently exits if compaction is not feasible.
tested with recent changes to service:snapshot #2360 
```
[ ] Yes
```
> fixes database compact to use db instance

- ironfish/src/network/utils/serializers.ts
Use the transaction serializers in other serializer functions so that reading, writing, and getting the size of transactions is standardized.
```
[ ] Yes
```
> Use transaction serializers in other serializer functions

- ironfish/src/event.ts
- ironfish/src/network/peers/addressManager.test.ts
- ironfish/src/network/peers/addressManager.ts
- ironfish/src/network/peers/connectionRetry.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
- ironfish/src/network/peers/peer.test.ts
- ironfish/src/network/peers/peer.ts
- ironfish/src/network/peers/peerConnectionManager.test.ts
- ironfish/src/network/peers/peerConnectionManager.ts
- ironfish/src/network/peers/peerManager.test.ts
- ironfish/src/network/peers/peerManager.ts
- ironfish/src/network/testUtilities/helpers.ts
Opening this as a draft to give some visibility into the work here.
```
[ ] Yes
```
> Only store peers in CONNECTED or CONNECTING states

- .github/workflows/build-ironfish-rust-nodejs.yml
- .github/workflows/ci.yml
- .github/workflows/deploy-brew.yml
- .github/workflows/deploy-node-aws.yml
- .github/workflows/deploy-node-github-beta.yml
- .github/workflows/deploy-node-github.yml
- .github/workflows/deploy-npm-ironfish-cli.yml
- .github/workflows/deploy-npm-ironfish-rust-nodejs.yml
- .github/workflows/push-version-to-api.yml
- .github/workflows/rust_ci.yml
Github shows a warning that Node.js 12 actions are deprecated (See this CI job for an example): https://github.com/iron-fish/ironfish/actions/runs/3277372608
This updates the actions to newer, supported versions.
```
[ ] Yes
```
> Fix Github Action warnings

- ironfish-rust-nodejs/src/lib.rs
- ironfish-rust-nodejs/src/nacl.rs
- ironfish-rust-nodejs/src/structs/note.rs
- ironfish-rust-nodejs/src/structs/note_encrypted.rs
- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish-rust/src/errors.rs
- ironfish-rust/src/keys/mod.rs
- ironfish-rust/src/keys/public_address.rs
- ironfish-rust/src/keys/view_keys.rs
- ironfish-rust/src/merkle_note.rs
- ironfish-rust/src/merkle_note_hash.rs
- ironfish-rust/src/nacl.rs
- ironfish-rust/src/note.rs
- ironfish-rust/src/receiving.rs
- ironfish-rust/src/serializing.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
Simplify ironfish-rust to single error type and create a small helper for converting to napi errors
The goal here is to make it a little easier to work with errors, spending less time thinking about which type is correct. This also makes it easier to extend functionality (implement From/Into traits, etc).
```
[ ] Yes
```
> Simplify Rust error types

- .github/workflows/ci.yml
- .github/workflows/deploy-brew.yml
- .github/workflows/deploy-npm-ironfish-cli.yml
- .github/workflows/rust_ci.yml
We no longer need to define the crates individually since rust-cache finds the parent workspace and uses it. Each individual rust job will only compile what it uses (ie `ironfish-zkp` will only compile its used dependencies), so there doesn't appear to be a need to be specific. We still key each rust job separately, so that the `ironfish-zkp` and `ironfish-rust` jobs don't contaminate the `-nodejs` job, which is the most important one that it used by most of our other CI jobs and contains the built nodejs bindings.
There may be some further optimizations to be made here. For example, running `cargo test` at the root will now run all rust tests across all workspace crates.
what additional work is required, if …
> Fix rust-cache CI step to use the proper workspace target directory

- .github/workflows/build-ironfish-rust-nodejs.yml
6 hours ago, macos-latest was changed to point to macos-12 instead of 11: https://github.com/actions/runner-images/releases/tag/macOS-11%2F20221018.1
We got lucky to discover this now and not during a release period by chance because I happened to break our CI job. What a coincidence.
We'll probably want to figure out why 12 is breaking eventually, but this will at least unblock us until that time.
Before: https://github.com/iron-fish/ironfish/actions/runs/3292592939
After: https://github.com/iron-fish/ironfish/actions/runs/3292697171
```
[ ] Yes
```
> Pin macos-11 for CI builds

- ironfish-rust-nodejs/src/lib.rs
I kept wondering why some of the napi code was complaining about dead code.. Would be neat if napi enforced the pub keyword more strictly like it does for `#[napi(object)]` 
```
[ ] Yes
```
> Use pub keyword in for napi to fix "dead code"

- ironfish-cli/src/commands/chain/benchmark.ts
Add the ability to give a target directory to add blocks on top of. Also print out incremental results of blocks/spends/notes per second
Local testing
```
[ ] Yes
```
> Update chain benchmark

- ironfish/src/consensus/consensus.ts
- ironfish/src/memPool/recentFeeCache.test.ts
- ironfish/src/memPool/recentFeeCache.ts
changing the block size limit from a maximum number of transactions to a maximum size in bytes will prompt miners to prioritize transactions by fee rate ($ORE/byte) instead of fee.
- implements getFeeRate to caculate the fee rate for a given transaction from its fee and its size
- changes FeeEntry to FeeRateEntry such that RecentFeeCache tracks fee rates instead of fees
- changes getSugggestedFee to estimateFeeRate
```
[ ] Yes
```
> changes RecentFeeCache to use fee rates

- ironfish-rust/src/keys/mod.rs
Per the [Sapling spec](https://github.com/zcash/zips/blob/main/protocol/sapling.pdf), on page 32, if the spend authorizing key is zero, the key should be thrown away and a new one regenerated.
I suspect we'll never actually hit this error, but it's probably possible.
```
[ ] Yes
```
> Spend authorizing key should never be 0

- ironfish-rust-nodejs/tests/demo.test.slow.ts
- package.json
(Re-)introduce project wide `test:slow` command, since I've been using it a lot more often while working between the nodejs and rust codebases.
Also did a little lint cleanup in the nodejs tests.
Next steps I want to take are to introduce proper lint rules/command for -nodejs folder, as well as begin properly testing more of the NAPI bindings via JS tests, so this PR is kind of step 1 of that process.
I also wouldn't mind a `test:all` command at some point but don't feel like dedicating the time to figuring that out yet.
```
[ ] Yes
```
> Add global lerna test:slow command

- ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture
- ironfish/src/consensus/consensus.ts
- ironfish/src/consensus/verifier.test.ts
- ironfish/src/consensus/verifier.ts
Enforce block size limit of 2 MB.
Added a new consensus upgrade for this limit on block 252000, estimated to occur on October 31, 2022 at 12:30 pm ET. All users will need to upgrade by then.
Added tests to `verifier.test.ts` to confirm the block size limit is enforced after consensus upgrade V2.
Can also test by lowering the activation height (`V2_MAX_BLOCK_SIZE`) and max block size (`MAX_BLOCK_SIZE_BYTES`) and trying to sync - all blocks larger than max size set should be marked as invalid.
```
[X] Yes
```
> Add V2 consensus upgrade for block size limit

- ironfish-cli/src/commands/deposit-all.ts
- ironfish/src/utils/bigint.ts
I noticed some currency amounts in deposit all were in numbers that should be ore. We should _always_ take strings and parse them into bigints for ore amounts.
```
Balance
Confirmed:   $IRON 0.00021458
Unconfirmed: $IRON 0.00021458
Pending:     $IRON 0.00021458
--- Completed Transactions (0) ---
```
I ran the command manually and looked at the UI.
```
[ ] Yes
```
> Convert some deposit-all numbers to bigints

- ironfish-rust-nodejs/src/structs/note.rs
- ironfish-rust/src/keys/public_address.rs
- ironfish-rust/src/merkle_note.rs
- ironfish-rust/src/note.rs
- ironfish-rust/src/receiving.rs
- ironfish-rust/src/spending.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/tests.rs
Felt like overkill to open a PR for each one of these, so here's a cleanup PR. Might be easiest to review the individual commits
- [Remove verbose add/sub operations for transaction balance](https://github.com/iron-fish/ironfish/commit/0f0025d20fcd13d0b7756b41a897642626e5dd29)
- [Remove expiration_sequence setter on posted Transaction](https://github.com/iron-fish/ironfish/commit/53a4ba0f14b9f98004a0572e563e1e2f90962879)
- [Simplify some math operations in Transactions](https://github.com/iron-fish/ironfish/commit/2c3e6127e493fe2f4af32917f169555666cd4aa7)
- [Use jubjub::Fr::random](https://github.com/iron-fish/ironfish/commit/798c4b4587fe579e5e30b309d66e013bb273a754)
- [Cleanup CtOption unwrap](https://github.com/iron-fish/ironfish/commit/350ad9f92496bcac14a7d27fb0d2b0231961328e)
- [Use …
> Rust minor code cleanup

- ironfish-cli/src/commands/accounts/pay.ts
- ironfish-cli/src/commands/chain/genesisblock.ts
- ironfish-cli/src/commands/deposit-all.ts
- ironfish-cli/src/commands/deposit.ts
- ironfish-cli/src/commands/miners/mined.ts
- ironfish-cli/src/utils/currency.ts
- ironfish/package.json
- ironfish/src/genesis/genesis.test.slow.ts
- ironfish/src/genesis/makeGenesisBlock.ts
- ironfish/src/mining/webhooks/webhookNotifier.ts
- ironfish/src/rpc/routes/mining/exportMined.ts
- ironfish/src/utils/currency.test.ts
- ironfish/src/utils/currency.ts
- ironfish/src/utils/fixedNumber.test.ts
- ironfish/src/utils/fixedNumber.ts
- yarn.lock
https://github.com/iron-fish/ironfish/issues/2363 This issue isn't resolved completely.
[There is a problem with the precision of the floating point number in javascript.](https://stackoverflow.com/questions/11695618/dealing-with-float-precision-in-javascript)
But **our code use number to calc the ores & iron, this is unsafe**. 
So I use bigint to represent ores, use string to represent iron, and convert every currency calc to ores calc to avoid the precision problem.
To convert between ore and iron, I use the @ethersproject/bignumber, this is an excellent project for Ethereum, and it's bignumber matches our needs.
And the MAXIMUM_IRON_AMOUNT is way beyond the Number.MAX_SAFE_INTEGER(Such as 9007199254740991 in chrome), so I convert it to the bigint
```
[] Yes
```
> Use bigint to calc currency to avoid float precision problem

- ironfish-cli/src/commands/rpc/token.ts
adds a command to retrieve or set the value of the rpcAuthToken key in internal.json
`ironfish rpc:token` prints out the token, if any.
`ironfish rpc:token --token=<value>` sets the token.
Closes https://airtable.com/appIXmGgVqP9QdbCf/pagcUNImP87iLU1r7?FG6K5=recUzR97TjxBboY00
```
[ ] Yes
```
> adds rpc:token cli command

- ironfish/src/memPool/__fixtures__/feeEstimator.test.ts.fixture
- ironfish/src/memPool/feeEstimator.test.ts
- ironfish/src/memPool/feeEstimator.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/node.ts
when initializing the fee estimator we use transactions from recent blocks without filtering transactions using the mempool. these blocks should be added to the queue such that the most recent block is at the end of the queue rather than the beginning.
- reverses queue when initializing fee estimator
- changes 'setUp' to 'init' to match other modules in the codebase
- makes chain a parameter of init instead of a property of the fee estimator since the chain is only used during init
- calls init within node.start
adds unit test to cover initialization with multiple blocks
```
[ ] Yes
```
> reverses blocks when setting up fee estimator

- ironfish-rust-nodejs/package.json
Per [a comment by @AmberKiso](https://github.com/iron-fish/ironfish/pull/2406#issuecomment-1292879341), the semicolon doesn't work on Windows platforms, so changing this to double ampersand.
```
[ ] Yes
```
> Change semicolon to ampersand for Windows support

- ironfish/src/fileStores/config.ts
- ironfish/src/memPool/feeEstimator.test.ts
- ironfish/src/memPool/feeEstimator.ts
- ironfish/src/node.ts
allows users to configure the fee estimator.
- adds feeEstimatorMaxBlocks to config
- renames numOfRecentBlocks to maxBlockHistory to match ETH config naming
- renames recentBlockNum argument to maxBlockHistory for consistency
- reads maxBlockHistory from config when constructing fee estimator
```
[ ] Yes
```
> adds config value for the maximum blocks in fee estimator history

- ironfish-rust-nodejs/build.rs
- ironfish-rust/src/lib.rs
- ironfish-rust/src/sapling_bls12.rs
This was changed in Rust 2018. While still supported, is awkward and mostly outdated. We can use regular imports for everything, so might as well be consistent.
More info: https://doc.rust-lang.org/edition-guide/rust-2018/path-changes.html#path-and-module-system-changes
```
[ ] Yes
```
> chore(rust): Remove deprecated usage of `extern`

- ironfish/src/memPool/feeEstimator.ts
- ironfish/src/primitives/noteEncrypted.ts
- ironfish/src/primitives/spend.ts
moves constants for noteEncrypted and spend serialized byte sizes to primitives modules for NoteEncrypted and Spend.
adds documentation of return value of estimateFeeRate.
```
[ ] Yes
```
> moves note/spend size constants to primitives

- ironfish-cli/src/commands/deposit-all.ts
- ironfish-cli/src/commands/deposit.ts
- ironfish-cli/src/utils/currency.ts
1. Replace `BigInt` & `toString` with `CurrencyUtils.decode` & `CurrencyUtils.encode` 
2. Use `bigint` for fee in `verifyCanSend`
3. Remove unnecessary convert.
```
[ ] Yes
```
> Normalization currency

- Cargo.toml
- ironfish-rust-nodejs/Cargo.toml
- ironfish-rust/Cargo.toml
- ironfish-zkp/Cargo.toml
Wanted to de-dupe the edition so it only needs to be updated in one place going forward. We can probably utilize more, the full list can be found here: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-package-table
```
[ ] Yes
```
> refactor(rust): Define shared values in cargo workspace

- ironfish/src/memPool/feeEstimator.test.ts
- ironfish/src/memPool/feeEstimator.ts
Change the fee rate calculation in `getFeeRate()` to improve precision by eliminating rounding during the bytes to kb conversion.
Updated tests in `feeEstimator.test.ts`.
```
[ ] Yes
```
> Improve precision in fee rate calculation

- ironfish-cli/src/commands/service/estimate-fee-rates.ts
periodically fetches fee rate estimates from the estimateFeeRate RPC and submits them to telemetry.
- converts fee rate to iron/kb in order to submit float value instead of bigint
- fetches low, medium, high fee rates from rpc
tested with local node, logging estimates instead of submitting to telemetry
```
[ ] Yes
```
> adds service command to send fee rate estimates to telemetry

- ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
- ironfish/src/memPool/memPool.test.ts
- ironfish/src/memPool/memPool.ts
- ironfish/src/mining/manager.ts
- ironfish/src/network/utils/serializers.ts
- Update mining manager to skip transactions that are larger than max block size
- Update mempool to order transactions by highest fee rate (ore/KB) instead of just fee
Updated `orderedTransactions` test in `memPool.test.ts`.
```
[ ] Yes
```
> Update mining transaction picking logic to use fee rate instead of fee

- ironfish-cli/src/commands/chain/download.ts
uses 'strict' mode during unzip to treat errors as failures (including ENOSPC errors). warns users that downloading and unzipping will require 2x the size of the snapshot in free disk space.
- Filled the disk of my AWS node instance, then tried to unzip another snapshot 😈 
```
[ ] Yes
```
> fixes silent failures in chain:download

- ironfish/src/fileStores/config.ts
- ironfish/src/memPool/feeEstimator.test.ts
- ironfish/src/memPool/feeEstimator.ts
- ironfish/src/node.ts
updates FeeEstimator to accept an object that configures the fee rate percentiles associated with low, medium, and high priority fee rates.
- adds config variables for low, medium, and high percentiles
- removes percentile constants
- updates queues to be an object with low/medium/high properties and removes checks on lookups using priority levels
- refactors method to fetch lowest fee rates from block to return sorted list instead of map
```
[ ] Yes
```
> allows configuration of fee estimator percentiles

- ironfish/src/memPool/feeEstimator.test.ts
- ironfish/src/memPool/feeEstimator.ts
defers division by 1000 in conversion from (bytes * ore/kb) to ore. rounding transaction size before computing fee leads to imprecise fee calculation.
```
[ ] Yes
```
> increases precision of fee calculation

- ironfish/src/consensus/consensus.ts
Added the consensus upgrade for max block limit to block 255000, estimated to occur on November 2, 2022 at 1:30 pm ET. All users will need to upgrade by then. Relevant changes are included in https://github.com/iron-fish/ironfish/pull/2378.
```
[X] Yes
```
> Push V2 consensus upgrade (block size) to activate at block 255000

- ironfish-rust/src/lib.rs
- ironfish-rust/src/outputs.rs
- ironfish-rust/src/transaction/mod.rs
Rename to be consistent with refactor plan
N/A
```
[ ] Yes
```
> refactor(rust): `OutputProof` -> `OutputDescription`

- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/tests.rs
Update the fee field name for a `Transaction`
N/A
```
[ ] Yes
```
> refactor(nodejs,rust): `Transaction.transaction_fee` -> `Transaction.fee`

- ironfish-rust-nodejs/index.d.ts
- ironfish-rust-nodejs/src/structs/transaction.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/tests.rs
Refactor the `transaction_fee` field because it's not accurate
N/A
```
[ ] Yes
```
> refactor(nodejs,rust): `ProposedTransaction.transaction_fee` -> `ProposedTransaction.value_balance`

- ironfish/src/wallet/wallet.ts
We make a call to [withReference](https://github.com/iron-fish/ironfish/blob/6651ab318530a7bd86aa82b83fbaf5ef8e0ebf28/ironfish/src/wallet/wallet.ts#L408) in the wallet code that is not necessary. This seems to be a relic of older code.
Deserializing the transaction into an underlying Rust Transaction struct can be slow, and in the past it was also leaking memory to keep a constructed Rust transaction object around. So the withReference function keeps track of how many references we have to a Rust object and once we don't need the reference anymore it deletes the Rust object.
previously in this wallet code we probably needed to access multiple fields on the Rust object. One of those calls was a call to `unsignedHash` on the Transaction. We [replaced …
> Remove transaction withReference wallet

- ironfish/src/wallet/wallet.ts
if a user downloads a snapshot and an account's head hash is not in the chain, then their node cannot recover unless the account database is removed.
- changes getLatestHeadHash to behave the same way as getEarliestHeadHash and set the head hash to null if the header is not found
1. create account
2. use `ironfish repl` to set the head hash for that account to a random string
3. try to start the node
with changes applied, starting the node results in a rescan
```
[ ] Yes
```
> resets head hash if header is null in getLatestHeadHash

- ironfish/src/syncer.ts
The block download speed was missing parentheses, so it was calculating (blocks.length) + (1 / elapsedSeconds) rather than (blocks.length + 1) / elapsedSeconds.
This should give us a more accurate view of the block download speed.
```
[ ] Yes
```
> Fix block download speed calculation

- ironfish-cli/src/commands/accounts/pay.ts
Update account:pay command with fee estimate. 
```
yarn start accounts:pay -v -a 10 -t acc03c941600e99cb0e53d9062826071a00af58905606aaabc4afc57d9626855b58724394b1a05d0d4a742
$ yarn build && yarn start:js accounts:pay -v -a 10 -t acc03c941600e99cb0e53d9062826071a00af58905606aaabc4afc57d9626855b58724394b1a05d0d4a742
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run accounts:pay -v -a 10 -t acc03c941600e99cb0e53d9062826071a00af58905606aaabc4afc57d9626855b58724394b1a05d0d4a742
Connecting to /Users/yajun/.ironfish/ironfish.ipc
Enter the fee amount in $IRON (min: 0.00000001 recommended: 0.00000365) [0.00000365]:
You are about to send:
$IRON 10.00000000 plus a transaction fee of $IRON …
```
> Update pay cmd with fee estimate

- README.md
We no longer need mingw for Windows builds, so we can get rid of that step. I also switched the node link over to 16.x for now, and cleaned up the python/visual c++ requirements to match node-gyp's page: https://github.com/nodejs/node-gyp#on-windows
```
[ ] Yes
```
> Update README for latest Windows installation requirements

- ironfish-cli/src/commands/deposit-all.ts
- ironfish-cli/src/commands/deposit.ts
- ironfish-cli/src/commands/fees.ts
- ironfish-cli/src/utils/currency.ts
Use new fee estimation for 
- deposit
- deposit-all
- fees
Use medium priority level as the fee estimation.
local
```
yarn start deposit
$ yarn build && yarn start:js deposit
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run deposit
Insufficient balance: 0.00000000 IRON.  Fee (0.00000365 IRON) + minimum deposit (0.1 IRON) = total required (0.10000365 IRON)
```
```
yarn start deposit -f 0.1
$ yarn build && yarn start:js deposit -f 0.1
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run deposit -f 0.1
Error reading the fee value, please enter a valid number.
```
```
yarn start …
```
> Update deposit and deposit-all with new fee estimation

- ironfish/src/fileStores/config.ts
> Default to 5 for blocksPerMessage which should increase sync stability

- ironfish/src/blockchain/blockchain.ts
- ironfish/src/merkletree/merkletree.ts
When validating transactions, the validator loops through every spend in the transaction and compares the spend’s commitment to the note tree’s hash at the spend’s tree size. To do this, it recalculates the root hash of the note tree at the spend’s tree size. Since our transaction creation uses block-aligned tree sizes for spend commitments, there should be a clustering of common tree sizes in spends. Adding a cache here should greatly reduce the amount of rehashing needed in the merkle tree when adding a block.
Local testing and unit tests
```
[ ] Yes
```
> Cache pastRoot function in merkle tree

- ironfish/src/network/peerNetwork.ts
- ironfish/src/syncer.test.ts
- ironfish/src/syncer.ts
Currently we sequentially download a group of blocks (20) and then add them to the chain. If we parallelize this we can start adding blocks while we are downloading the next group of blocks from peers. After some improvements to addBlock such as caching pastRoot and batch adding notes to the merkle tree addBlock time has improved a lot. Now the limitation seems to be more around downloading blocks. We're seeing download speeds anywhere from 0.5 - 20 blocks per second depending on the peer and connection. We are seeing add block times of ~1-2 blocks/s. If we parallelize these we could potentially double syncing speed. 
Local testing and unit tests
```
[ ] Yes
```
> Parallelize downloading and adding blocks

- ironfish/src/wallet/__fixtures__/account.test.ts.fixture
- ironfish/src/wallet/account.test.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.ts
- ironfish/src/wallet/walletdb/walletdb.ts
limits the wallet to iterate only over pending transactions in rebroadcastTransactions.
implements loadPendingTransactions to yield transactions with expiration sequence equal to 0 or greater than the given head sequence
- removes check on expired transactions in rebroadcastTransactions
- updates tests
NOTE: repeat of #2504, but targeted to staging
```
[ ] Yes
```
> iterate over pending transactions for rebroadcast

- ironfish-rust/src/assets/asset.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/value_balances.rs
- ironfish-zkp/src/circuits/mint_asset.rs
We will soon need to check balances per asset as we add mints and burns. This code change adds a new data structure for value balances with a temporary hard-coded identifier for the native asset.
```
[ ] Yes
```
> feat(rust): Add value balances by asset identifier to Transaction

- ironfish/src/network/peers/connections/webRtcConnection.ts
- ironfish/src/network/peers/connections/webSocketConnection.ts
> avoids logging unparsed buffers in error message

- ironfish/src/blockchain/blockchain.test.ts
- ironfish/src/blockchain/blockchain.ts
When we add blocks we verify transactions and update the Merkle tree sequentially. We could see speedup if we parallelize these two operations
Unit tests and local testing of syncing
```
[ ] Yes
```
> Parallelize verify transactions

- ironfish-cli/src/commands/fees.ts
changes fees command to only output fee rates unless '--explain' is passed. the explain flag causes the command to also output information on how fee rates are computed and estimated.
without `--explain`:
```
Fee Rates ($ORE/kB)
low:    488
medium: 622
high:   622
```
with `--expain`:
```
Fee rates are estimated from the distribution of transaction fees over the last 10 blocks.
The fee rate for each transaction is computed by dividing the transaction fee in $ORE by the size of the transaction in kB.
The low, medium, and high rates each come from a percentile in the distribution:
low:    10th
medium: 20th
high:   30th
Fee Rates ($ORE/kB)
low:    488
medium: 622
high:   622
```
what additional work is required, …
> adds an 'explain' flag to the fees command

- ironfish-zkp/src/bin/generate_params.rs
Run `cargo run --release --bin generate_params <circuit>` where `<circuit>` is one of `all`, `spend`, or `output`
Still requires manually moving the params files into params folder for now
```
[ ] Yes
```
> feat(zkp): Add quick script to regenerate params

- ironfish-cli/src/commands/accounts/transaction.ts
- ironfish/src/rpc/routes/accounts/getTransaction.ts
- ironfish/src/rpc/routes/accounts/types.ts
- ironfish/src/rpc/routes/accounts/utils.ts
- ironfish/src/wallet/account.ts
- ironfish/src/wallet/wallet.ts
Add spender note information for `getTransaction` route. https://github.com/iron-fish/ironfish/issues/2412
```
[ ] Yes
```
> show note for spender in getTransaction

- ironfish/src/blockchain/blockchain.ts
If for some reason an error is throw when calling `verifyBlockAdd` we want to handle that. Without the `catch` the error would be thrown in an unhandled promise and crash the node
Unit tests and local testing
```
[ ] Yes
```
> Catch error in parallel transaction verification

- ironfish/src/syncer.ts
We are sometimes getting an error when a peer disconnects that causes the node to crash. This is most likely related to changes related to [parallelizing addBlock and download blocks](https://github.com/iron-fish/ironfish/pull/2491)
Unit tests and tested disconnected peer locally
```
[ ] Yes
```
> Fix error when peer disconnects while syncing

- ironfish/package.json
- ironfish/src/network/peers/connections/webRtcConnection.ts
- yarn.lock
The broken Windows prebuilt binaries were fixed in this commit: https://github.com/murat-dogan/node-datachannel/commit/d087a7a5868d326e85ff4e08f465ce896e2845cc If someone on Windows has attempted to install this version, the older, nonworking version will be cached. But previously we had shipped 0.3.6, so none of our users should have installed 0.4.0.
As with 0.3.6, this has the benefit of adding support for prebuilt binaries on M1 machines (not requiring OpenSSL + cmake to be installed)
Also switched from calling `peer.close()` to `peer.destroy()`, since it also handles cleaning up callbacks. I ran this overnight to ensure it didn't crash.
```
[ ] Yes
```
> Update node-datachannel to 0.4.0

- ironfish-cli/src/commands/status.ts
From https://github.com/iron-fish/ironfish/issues/2186. Account status and scanning output shows `-1`. Hiding this now.
```
[ ] Yes
```
> Fix account status display

- ironfish-rust/src/mining/mine.rs
- ironfish-rust/src/mining/thread.rs
Closes https://github.com/iron-fish/ironfish/issues/2185
Previously, the miner would check values at the batch size boundaries more than once, leading to wasted work. This change prevents that from happening by making the end value less than the start of the next batch size
```
[ ] Yes
```
> Fix overlapping values for mining randomness

- ironfish/src/memPool/__fixtures__/feeEstimator.test.ts.fixture
- ironfish/src/memPool/feeEstimator.test.ts
Some of the fee estimator tests were failing when regenerating the fixtures. Several of them were due to one of the transactions not being accepted into the mempool due to duplicate spends -- I addressed this by creating two separate accounts to receive/spend tokens.
Another one was due to the estimated fee changing -- I'll follow up on this to double-check the value makes sense.
```
[ ] Yes
```
> Fix errors when regenerating fixtures for fee estimator tests

- ironfish-rust/src/lib.rs
- ironfish-rust/src/transaction/mod.rs
- ironfish-rust/src/transaction/outputs.rs
- ironfish-rust/src/transaction/spending.rs
Cleaning up the root level a bit, plus these just make more sense in the transaction module
```
[ ] Yes
```
> refactor(rust): move spends and outputs into transaction module

- ironfish-cli/src/commands/chain/rewind.ts
- ironfish/src/blockchain/blockchain.ts
rewind needs to remove blocks from the database: otherwise, when the node starts syncing again it rejects the blocks it receives from its peers as database duplicates.
removes all blocks at each sequence (including those on forks) one sequence at a time.
- rewound chain
- started node, and confirmed that it started adding blocks again
```
[ ] Yes
```
> changes chain:rewind to remove blocks
