iron-fish/ironfish

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.ts

wallets may have negative balances after the following sequence of events:
- transaction *A* created, mined on block *x*
- output notes from *A* now have `sequenceToNoteHash` mappings with sequence of *x*
- re-org removes transaction *A* from chain
- notes from *A* added to `nonChainNoteHashes`
- notes from *A* still have sequence *x* in `sequenceToNoteHash`
- balance calculated for account
- notes from *A* subtracted from pending balance because they are marked as sequence *x* in `sequenceToNoteHash`
- notes from *A* subtracted again from unconfirmed balance because they are in `nonChainNoteHashes`
the solution is to be sure to remove the entry in `sequenceToNoteHash` when *x* is removed from the chain. the notes do not have sequence data (yet), so we cannot remove this index when we …

fixes cause of negative balances

---

ironfish-cli/src/commands/start.ts

adds a check to the node `start` command that determines whether the chain contains the corrupt double spend block at sequence 270446. if the chain has this block the node will fail to start and the user will be prompted to run `chain:repair`.
1. Ran start with a node that does not have the corrupt block, confirmed that it starts
2. Ran start with a node that does have the corrupt block, confirmed that it exits immediately
```
[ ] Yes
```

checks for corrupt block in chain before starting

---

ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
ironfish/src/blockchain/blockchain.test.ts

1. create a transaction
2. create a fork with a double spend
3. reorg to a chain without the double spend
4. try to create the double spend again, after the consensus change
this test expects the second double spend to fail because of the consensus change. however, the test fails because the reorg has removed the nullifier from the original transaction from the chain nullifiers merkle tree.
```
[ ] Yes
```

adds test that reproduces double spend afer consensus change

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts

it is curently possible for a note to be spent on a fork, but, after reorg, a nullifierToNote mapping is left in the database.
this can result in an error when expiring transactions based on the following sequence:
```
1. transaction A created, mined on a fork
2. transaction B created, spending a note from A
3. reorg from the fork containing A, nullifiers for notes in A set to null (but
not remeoved from nullifierToNote)
4. transaction A expires, removing notes from the database (still not removing
nullifiers from nullifierToNote, since the referential integrity is broken)
5. transaction B expires, but expiration fails because the nullifier from the
spend in B maps to a note that has been deleted
```
fixes the referential integrity issue by deleting nullifierToNote entry during …

deletes nullifier from nullifierToNote if nullifier set to null on note

---

ironfish/src/blockchain/blockchain.ts

Adding the notes and nullifiers to the merkle tree as a batch will speed up block construction a bit, especially with the larger block size.
```
[ ] Yes
```

Batch merkle tree adds when constructing a new block

---

ironfish-cli/src/commands/deposit-all.ts

There is a bug where the wallet potentially returns a negative balance. Until we fix this issue we don't want the depositAll command to be failed by it.
Local testing
```
[ ] Yes
```

Handle negative balances in depositAll

---

ironfish/src/network/peers/peer.test.ts
ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerManager.test.ts

Peer.punish was closing the connection, which triggers dispose to be run in the peerManager, which removes event handlers from the Peer's Events, before the onBanned event was emitted. So peers weren't being banned when punish was called. This swaps the order to fix the banning.
```
[ ] Yes
```

Fix peer.punish not banning peers

---

ironfish-zkp/src/circuits/output.rs
ironfish-zkp/src/circuits/spend.rs
ironfish-zkp/src/constants.rs

Replace Payment Address with Subgroup Point in Output and Spend
unit tests
```
[ ] Yes
```
@mat-if @rohanjadvani

Replace Payment Address with Subgroup Point in Output and Spend

---

ironfish-cli/src/commands/start.ts

It's useful to run the node with no accounts to disable the wallet from scanning/decrypting notes, however the start command will always recreate accounts if you don't have one.
It's probably still useful on first run to create an account for users, but if a user chooses to remove that account, I don't think we need to create another one.
```
[ ] Yes
```

Only create a default account on first run

---

ironfish-cli/src/commands/chain/hardfork.ts
ironfish-cli/src/commands/chain/rewind.ts

we need to update the wallet while we rewind the chain. otherwise nodes will be forced to rescan because the wallet's head hash will not be in the chain anymore.
first disconnect blocks back to the rewind point.
next, update the wallet head, if necessary. only update the wallet head if its sequence is greater than the 'to' sequence of the rewind.
finally, remove all blocks back to the rewind point.
```
[ ] Yes
```

changes rewind update wallet head

---

ironfish-cli/src/commands/accounts/pay.ts
ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
ironfish/src/rpc/routes/transactions/sendTransaction.ts
ironfish/src/utils/currency.test.ts
ironfish/src/utils/currency.ts

These have nothing to do with our currency. They have everything to do with user input validation that is more like isValidFee(). Let's keep our currency conversion code separate from our user input. If any input should be done in CurrencyUtils it's to ensure the values are within valid ranges.
```
[ ] Yes
```

Remove CurrencyUtils.isValid*()

---

ironfish/src/fileStores/config.ts

Remove custom error message to show config key
Yup automatically gives an appropriate error message with key name and error message, if a custom error message is defined - it will become our responsibility to add the key name in that custom error message.
Here a custom error message was defined without a key name, so in case on error in key value. We were just getting:
`Error: Invalid URL` -> with no idea which key it is for
Removing the custom message which automatically fix the issue
`Error: explorerBlocksUrl must be a valid URL
`
Tested on local
No

fix config validator

---

ironfish-cli/src/commands/accounts/repair.ts

adds a cli command intended to fix balance and note indexing issues in the wallet without the need for a full rescan/reset of the wallet.
repairs the balance by recomputing it from 0 and adding all unspent notes. uses the chain to determine if each note has been spent and changes to spent if the note is marked as unspent
repairs sequenceToNoteHashes by ensuring that all notes that are on chain have the sequence of the transaction that created the note. any sequence to note hash mapping that does not have a note is removed.
repairs nonChainNoteHashes by removing any note hashes for notes that are on chain.
repairs nullifierToNoteHash by removing any nullifier that maps to a note that is not in the wallet or maps to a note that is not on the chain. …

adds accounts:repair command

---

ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/strategy.test.ts
ironfish/src/strategy.ts

This will disable rewards at a block `278500`. It allows increased deposits without diluting the point economy. This block is estimated to be mined at `Sun Nov 20 2022 16:30:09 GMT-0500 (Eastern Standard Time)`
We should delete this after phase 2 ends.
1. Start a new chain
2. Set V3_DISABLE_MINING_REWARD to a low number
3. Mine blocks past that and see that they work
```
[ ] Yes
```

Disable mining rewards in consensus for Phase 2 at block 278500

---

ironfish-cli/src/commands/config/edit.ts

This would crash because the directory passed to mkdtempdir has a 2 slash so it thinks its 2 folders that don't exist.
```
> ironfish config:edit --remote
Error: ENOENT: no such file or directory, mkdtemp '/var/folders/tn/zq9xjdyd347gzn6xbgpgdjxw0000gn/T/@ironfish/sdk-9ArQrX'
error Command failed with exit code 1.
```
Run the command
```
[ ] Yes
```

Fix config:edit --remote crashing

---

ironfish/src/fileStores/keyStore.test.ts
ironfish/src/fileStores/keyStore.ts
ironfish/src/utils/yup.ts

This adds validation to KeyStore.set(). Before, validation was unidirectional. Now it'll check the value against the schema going in. This also adds tests to validate this new behaviour.
Added tests and used `ironfish config:set` command, and edited the config to test.
```
[ ] Yes
```

Key store validate

---

ironfish/src/rpc/routes/config/uploadConfig.ts

It didn't mention the key that was causing the issue. Now it will print out the key with the invalid value.
before
```
ironfish config:set poolMaxConnectionsPerIp 'hello'
Could not convert "hello" from string to number
```
after
```
ironfish config:set poolMaxConnectionsPerIp 'hello'
poolMaxConnectionsPerIp has an invalid value: Could not convert "hello" from string to number
```
```
[ ] Yes
```

Improve RPC uploadConfig() errors

---

ironfish/src/testUtilities/fixtures.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts

the useAccountFixture used createAccount to create the account in a fixture, but importAccount when deserializing the fixture. one problem with this is that createAccount and importAccount set the head hash stored for an account differently. createAccount sets the head hash to the head of the chainProcessor -- we don't need to scan earlier blocks if we just created the account. importAccount sets the head hash to null -- we don't know when this account was created, so we need to scan the whole chain.
this leads to different behavior in tests when generating the fixtures vs. when reusing them.
these changes update useAccountFixture to set the head hash to the chainProcessor's hash after adding the account so that the head hash will match what it would have if we had created the account. …

fixes useAccountFixture to match createAccount logic

---

ironfish/src/consensus/consensus.ts

2809 blocks from now: Mon Nov 21 2022 15:33:23 GMT-0500 (Eastern Standard Time) at block 279900 
```
[ ] Yes
```

Change V3_DISABLE_MINING_REWARD to 279900

---

ironfish/src/testUtilities/fixtures.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts

the useAccountFixture used createAccount to create the account in a fixture, but importAccount when deserializing the fixture. one problem with this is that createAccount and importAccount set the head hash stored for an account differently. createAccount sets the head hash to the head of the chainProcessor -- we don't need to scan earlier blocks if we just created the account. importAccount sets the head hash to null -- we don't know when this account was created, so we need to scan the whole chain.
this leads to different behavior in tests when generating the fixtures vs. when reusing them.
these changes update useAccountFixture to set the head hash to the chainProcessor's hash after adding the account so that the head hash will match what it would have if we had created the account. …

Add back wallet unit tests to network-reset

---

ironfish-rust/src/assets/asset.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/merkle_note.rs
ironfish-rust/src/merkle_note_hash.rs
ironfish-rust/src/note.rs
ironfish-rust/src/serializing.rs
ironfish-rust/src/transaction/burns.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/spending.rs

We don't need the extra functions to convert to bytes, so removed those. Added a read_point function since that is a helper worth having. Cleaned up read/write functions so theyre more uniform and utilize the new read_point function properly
```
[ ] Yes
```

refactor(rust): Remove unnecessary to-bytes functions, add read_point function

---

Cargo.lock
ironfish-rust-nodejs/Cargo.toml
ironfish-rust-nodejs/src/nacl.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/public_address.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/serializing.rs

Since we already have these functions, we can skip using the crate. It's not a huge win since the package is still used in some sub-dependencies, but one less thing to worry about later (version conflicts, etc).
```
[ ] Yes
```

refactor(rust): Remove redundant hex crate

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/note.rs

Update NAPI bindings and expose note's asset identifier 
N/A
```
[ ] Yes
```

feat(rust-nodejs): Add `note.asset_identifier()`

---

ironfish-rust/src/note.rs

This technically works since both constants have the same value, but refactor to use the accurate memo variable.
N/A
```
[ ] Yes
```

refactor(rust): s/`GENERATOR_SIZE`/`MEMO_SIZE` when encrypting note

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/asset.rs
ironfish-rust-nodejs/src/structs/transaction.rs

Expose NAPI methods to mint and burn assets so we can update these descriptions when building a transaction.
N/A
```
[ ] Yes
```

feat(rust-nodejs): Add `transaction.mint` and `transaction.burn`

---

ironfish/src/primitives/block.test.ts
ironfish/src/primitives/block.ts
ironfish/src/primitives/blockheader.test.ts
ironfish/src/primitives/blockheader.ts
ironfish/src/testUtilities/matchers/blockchain.ts

`BlockHeaderSerde.equals()` and `BlockHeader.equals()` are only used in tests. We also don't need to be checking every field in the block header because we can re-use the hash for that.
Unit tests
```
[ ] Yes
```

Remove BlockHeaderSerde.equals and BlockSerde.equals

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/asset.rs
ironfish/src/primitives/note.ts
ironfish/src/primitives/transaction.ts
ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/__fixtures__/createTransaction.test.slow.ts.fixture
ironfish/src/workerPool/tasks/createTransaction.test.slow.ts
ironfish/src/workerPool/tasks/createTransaction.ts

* Update the create transaction worker pool message to accept an array of mints and an array of burns
* Expose asset identifier and native asset identifier from NAPI
* Expose asset identifier associated with Note
Add unit test
```
[ ] Yes
```

feat(ironfish,rust-nodejs): Update create transaction handler to include mints and burns

---

ironfish/src/storage/database/database.ts
ironfish/src/storage/levelup/database.ts
ironfish/src/storage/levelup/store.ts

the current implementation of the storage layer uses stores to interact with the database.
implements 'get' on the database to retrieve serialized values
changes the store implementation of get to be a wrapper around db.get that encodes the key and deserializes the value
```
[ ] Yes
```

implements 'get' on database in storage layer

---

ironfish/src/storage/database/database.ts
ironfish/src/storage/levelup/database.ts
ironfish/src/storage/levelup/store.ts

having 'put' implemented on the database ensures that we can write to a database without needed to write through a database store.
changes the store implementation to utilize db.put
```
[ ] Yes
```

implements 'put' on database in storage layer

---

ironfish/src/storage/database/database.ts
ironfish/src/storage/database/types.ts
ironfish/src/storage/database/utils.test.ts
ironfish/src/storage/database/utils.ts
ironfish/src/storage/levelup/database.ts
ironfish/src/storage/levelup/store.ts

This moves core underlying DB iterator into the DB itself from the store.
Added tests.
```
[ ] Yes
```

Move IDatabaseStore.getAllIter() to IDatabase

---

ironfish-cli/src/commands/accounts/repair.ts

expiring transactions may not work because of the `nullifierToNote` error that the `repairNullifierToNoteHash` function resolves.
reorders the repair functions so that nullifiers are fixed before expired transactions.
```
[ ] Yes
```

fixes nullifierToNote before repairing expired transactions

---

ironfish-cli/package.json
ironfish-cli/src/commands/backup.ts
yarn.lock

the backup command uses an S3 multipart upload to copy a zip of the chain and/or accounts databases to an S3 bucket.
this command fails if the AWS credentials aren't set properly in the S3Client. if there are no credentials set, we need not pass a 'credentials' object to the constructor.
fixes parsing of credentials to pass no credentials to the S3Client constructor if no credentials are passed to the command or set in the environment. 
this will allow uploads without access keys by using Cognito to create and fetch credentials for an identity.
- uploaded to public bucket with AWS credentials set via env, command-line, and credentials file
- unset all AWS credentials, removed credentials file, and uploaded using Cognito identity
Is this a breaking change? If yes, add notes below on why …

fixes backup command multipart uploads

---

ironfish/src/storage/database/database.ts
ironfish/src/storage/database/types.ts
ironfish/src/storage/database/utils.test.ts
ironfish/src/storage/database/utils.ts
ironfish/src/storage/levelup/database.ts
ironfish/src/storage/levelup/store.ts

This is so you can use the raw KVS database behaviour on the database itself, and the store just becomes a thin wrapper over the database functionality.
Existing tests, and new tests.
```
[ ] Yes
```

Move IDatabaseStore functionality into IDatabase

---

ironfish-cli/src/command.ts
ironfish-cli/src/commands/chain/genesisblock.ts
ironfish-cli/src/commands/reset.ts
ironfish-cli/src/commands/start.ts
ironfish-cli/src/flags.ts
ironfish/src/fileStores/config.ts
ironfish/src/node.ts
ironfish/src/sdk.test.ts
ironfish/src/sdk.ts

We don't need this functionality, and as new DB's were added it wasn't added for the other DB's as flags and other places.
Ran the node
```
[ ] Yes
```

Remove ability to customize database names

---

ironfish/src/rpc/routes/accounts/getNotes.ts
ironfish/src/rpc/routes/accounts/getTransaction.ts
ironfish/src/rpc/routes/accounts/getTransactions.ts
ironfish/src/rpc/routes/accounts/types.ts
ironfish/src/rpc/routes/chain/followChain.ts
ironfish/src/rpc/routes/chain/getBlock.ts
ironfish/src/rpc/routes/chain/getBlockInfo.ts
ironfish/src/rpc/routes/chain/getTransaction.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/rpc/routes/transactions/sendTransaction.test.ts
ironfish/src/rpc/routes/transactions/sendTransaction.ts
ironfish/src/wallet/account.ts

uses the signed transaction hash instead of the unsigned hash in every rpc response that returns a transaction hash.
we store transactions by signed hash in the wallet but return unsigned hashes in rpc responses. every user-facing transaction hash is currently an unsigned hash, so lookups iterate over all traansactions to find a match.
removes logic for finding transactions by unsigned hash.
NOTE: this will also have the effect of propagating signed hashes to the API instead of unsigned hashes
```
[ ] Yes
```

replaces unsigned transaction hashes in rpc responses

---

ironfish/src/fileStores/keyStore.test.ts
ironfish/src/fileStores/keyStore.ts

There is a bug here where if we load all the keys, we add them to a set to keep track of those keys. That set is used to determine which keys get saved when we call keyStore.save(). It's also used by keyStore.isSet(). Since we don't add the key to the set when we call keyStore.put(), if it matches the default value it's dropped, and isSet() will always return false.
Added a new test case to reproduce this bug.
```
[ ] Yes
```

Fix KeyStore not saving value if matching default

---

ironfish/src/fileStores/config.ts
ironfish/src/rpc/routes/config/getConfig.test.ts
ironfish/src/utils/yup.test.ts

The exported defaults are only used at the top if you need to reference it somewhere else. If it's not referenced somewhere else it should not be duplicated at the top of the file.
```
[ ] Yes
```

Materialize config defaults

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/consensus.ts
ironfish/src/defaultNetworkDefinitions.ts
ironfish/src/fileStores/config.ts
ironfish/src/networkDefinition.ts
ironfish/src/node.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.test.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/strategy.test.ts

Moved `maxSyncedAgeBlocks` to config from consensus since the entire network doesn't have to agree on it.
Updated tests.
```
[ ] Yes
```

Move maxSyncedAgeBlocks to config from consensus

---

ironfish-cli/src/commands/service/sync-masp-transactions.ts

Creates a base syncer, then split the two syncers (masp, and deposit) into separate commands.
The MASP command serialization is currently stubbed out until we update the `primitives` to handle multi-asset.
```
[ ] Yes
```

feat: masp transaction syncer

---

ironfish-cli/src/commands/chain/genesisblock.ts
ironfish/src/genesis/genesis.test.slow.ts
ironfish/src/genesis/makeGenesisBlock.ts

The genesis block command doesn't currently allow for more than a single recipient for the genesis coins. This adds support for loading a batch of allocations from a CSV file.
```
[ ] Yes
```

Allow loading genesis block allocations from CSV

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/chainProcessor.ts

we used to use the `isLinear` value while updating the `chainProcessor`, but after #2586 it is no longer used.
- changes findFork to only return a BlockHeader
- updates uses of findFork
- removes assertion that findFork return value is non-null in reorganizeChain because it cannot be null
```
[ ] Yes
```

removes unused isLinear from findFork return value

---

ironfish-cli/src/commands/accounts/address.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish/src/rpc/routes/accounts/getPublicKey.test.ts
ironfish/src/rpc/routes/accounts/getPublicKey.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/tasks/createMinersFee.ts

Remove generate public address flag from getPublicKey rpc
Rename geneartePublicAddress
unit tests
```
[ ] Yes
```
@dguenther

Remove generate public address flag from getPublicKey rpc

---

.github/workflows/ci.yml
yarn.lock

Needed because --frozen-lockfile is broken in yarn 1.x. We can probably go back to using --frozen-lockfile if we upgrade to yarn 2.x
Fail with outsanding yarn.lock changes: https://github.com/iron-fish/ironfish/actions/runs/3633233416/jobs/6130008284
Pass with no outstanding yarn.lock changes: https://github.com/iron-fish/ironfish/actions/runs/3633244719/jobs/6130032328
```
[ ] Yes
```

CI checks for yarn.lock changes manually

---

ironfish/src/memPool/priorityQueue.ts

We were getting reports of [issues](https://github.com/iron-fish/ironfish/issues/2376) with using the `.at` function on arrays so changing this to just index into the array directly. It looks like `.at()` is supported in [NodeJS 16 and onward](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at#browser_compatibility) so best guess is that these clients were running older node version but will try to confirm that. Either way it would be nice for it to work with older node versions anyway.
Unit tests
```
[ ] Yes
```

Remove array.at(0) function in PriorityQueue

---

ironfish/src/migrations/data/014-note-sequence.ts
ironfish/src/migrations/data/index.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/walletdb/decryptedNoteValue.test.ts
ironfish/src/wallet/walletdb/decryptedNoteValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

adds chain state fields to decryptedNotes store and implements data migration to populate these fields.
~~migration does not (yet) remove sequenceToNoteHash or nonChainNoteHashes stores. subsequent changes will modify wallet code to cease using these stores and then, finally, remove them.~~ Computing the balance will be much less efficient without sequenceToNoteHash and nonChainNoteHashes, but having chain state in decryptedNotes will make it easier to keep them in sync
```
[11:05:31.374] Applying 1 migrations:
[11:05:31.377]   014-note-sequence
[11:05:31.377] 
[11:05:31.377] Running 014-note-sequence...
[11:05:31.447] Adding chain state data to decryptedNotes...
[11:05:31.452] Migrating decrypted notes for account test...
[11:05:31.453] 	Migrated 0 decrypted notes for account test …
```

adds blockHash and sequence to decryptedNoteValue

---

ironfish/src/memPool/memPool.ts
ironfish/src/node.ts

The function is for opening DB connections, this function does not open a database.
The fee estimator should also not take a Wallet. It won't have access to it once we split it out, and the estimator should not be wallet aware. I will fix in a future PR.
```
[ ] Yes
```

Fix call to FeeEstimator.init() in openDB()

---

.github/workflows/rust_ci.yml

The goal here is to allow testing and linting to happen simultaneously without stepping on each other due to failures. A quick 5 second lint check should not stop a 5 minute test run and vice-versa.
Confirming `fmt` still works: https://github.com/iron-fish/ironfish/actions/runs/3650307611/jobs/6166123169
```
[ ] Yes
```

refactor(ci): Separate rust lint into a separate workflow

---

ironfish/src/consensus/consensus.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts

Removes the consensus parameter that allows for enabling/disabling the max block size, and leaves it always enabled now.
```
[X] Yes
```
Breaks compatibility with node versions that support not enabling a max block size in bytes.

Remove V2_MAX_BLOCK_SIZE consensus param

---

.github/workflows/rust_ci.yml

I removed the `-nodejs` workflow yesterday without thinking about how this no longer caches the NAPI bindings for other CI runs.
```
[ ] Yes
```

fix(ci): Re-add NAPI build for the rust cache

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/merkletree/database/leaves.test.ts
ironfish/src/merkletree/database/leaves.ts
ironfish/src/merkletree/merkletree.test.ts
ironfish/src/merkletree/merkletree.ts
ironfish/src/merkletree/schema.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/testUtilities/helpers/merkletree.ts
ironfish/src/testUtilities/matchers/merkletree.ts
ironfish/src/workerPool/tasks/createTransaction.test.slow.ts

Removes the element field from merkle tree leaves, since we only use it for tests. This should save a minimum of 328MB per 1000 blocks, assuming that all 1000 blocks only have a miners transaction.
```
[X] Yes
```

Remove element field from merkle tree leaves

---

ironfish-cli/bin/run

The CLI is built to run on node version 16. We have run into one [issue](https://github.com/iron-fish/ironfish/issues/2376) that arose from incompatible node version. We should require users to be using the correct node version so we do not run into these versioning errors.
Local testing
```
[ ] Yes
```

Require node 16

---

ironfish-rust/src/keys/ephemeral.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/public_address.rs
ironfish-rust/src/keys/test.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/merkle_note.rs
ironfish-rust/src/note.rs
ironfish-rust/src/transaction/outputs.rs

This creates a distinct struct to avoid having to mess around with tuples. It also removes the `generate_diffie_hellman_keys` function from the PublicAddress since it's no longer related to the PublicAddress with the removal of the diversifier
```
[ ] Yes
```

refactor(rust): Add a struct for ephemeral key pairs

---

ironfish/src/wallet/walletdb/walletdb.ts

* Update `balances` store to have a composite key of account prefix and asset identifier
* Default key usage to use native asset identifier (will be updated in subsequent PRs)
N/A
```
[ ] Yes
```

feat(ironfish): Update `balances` store in `walletdb` to include asset

---

.github/workflows/rust_ci.yml
.github/workflows/rust_ci_cache.yml

Due to the limitations of cache access [https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache), every PR following a change to rust code will have to rebuild until that change reaches master. If we build on every push to staging and master, we can make sure the rust cache is updated for staging as well.
Tested the trigger by adding this branch name to the branch list: https://github.com/iron-fish/ironfish/actions/runs/3690467909/jobs/6247495432
Testing a PR opened against this branch demonstrates that this will work for PRs opened against staging: …

feat(ci): Cache rust build on staging

---

ironfish/src/wallet/walletdb/walletdb.ts

setNoteHashSequence and deleteNoteHashSequence each make writes and/or deletes to multiple stores. these functions need to use database transactions to ensure that these db updates are atomic.
- adds 'withTransaction' wrapping to setNoteHashSequence to create a db transaction if one was note passed in
- changes tx argument to deleteNoteHashSequence to optional to match function signatures elsewhere in the wallet
- uses 'withTransaction' in deleteNoteHashSequence to ensure atomic changes
```
[ ] Yes
```

adds db transactions to note hash index updates

---

ironfish/src/merkletree/merkletree.test.ts
ironfish/src/merkletree/merkletree.ts

We used this on the nullifier merkle tree but removed the nullifiers in [this PR](https://github.com/iron-fish/ironfish/pull/2722). 
Unit tests
```
[ ] Yes
```

Remove contained from merkle tree

---

ironfish/src/blockchain/nullifierSet/nullifierSet.ts

This transaction was missed for connectBlock, disconnectBlock and clear. Other functions in NullifierSet do not need withTransaction because they only do one database operation but these functions with multiple operations should still be atomic even if no transaction is passed to them. Currently they are only atomic if a transaction is passed in
Unit tests
```
[ ] Yes
```

Add transaction to NullifierSet connect and disconnect

---

ironfish-rust/src/transaction/mod.rs

This isn't used as part of generating the genesis block any more, so we can remove it.
```
[ ] Yes
```

Remove post_genesis_transaction

---

ironfish/src/wallet/__fixtures__/wallet.test.slow.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.slow.ts

when a block is disconnected from the chain, the transactions on that block are pending: they may be included in a future block connected to the chain.
the wallet marks notes as spent when they are spent in pending transactions. when a block is disconnected, those notes are still marked as spent _unless_ the transaction was created by another wallet.
this is incorrect because the transaction is still pending even if a different wallet created it. marking the spent notes as unspent could result in the wallet creating double-spend transactions.
these changes fix this issue by only marking spent notes as unspent when a transaction expires.
- changes processTransactionSpends to only mark spends as spent, never unspent
- updates test to enforce correct handling of forked transactions from …

fixes wallet handling of fork transactions from other wallets

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/assets.test.ts
ironfish/src/blockchain/database/assets.ts

Add the identifier to the asset store for developer convenience. We could generally get it from the key, but the extra 32 bytes is fairly negligble as far as storage goes.
```
[ ] Yes
```

feat(ironfish): Add identifier to asset info store

---

ironfish-cli/src/commands/accounts/notes.ts
ironfish-cli/src/commands/accounts/transaction.ts
ironfish/src/primitives/note.ts
ironfish/src/rpc/routes/wallet/getNotes.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/types.ts

Manual testing was performed via booting up two nodes which emulated what the multiasset team did here:
https://www.loom.com/share/2e1908aca6ac4961a7d0d6cfe07b73bc
```
[ ] Yes
```

feat: add sender to cli outputs

---

ironfish/src/utils/async.ts
ironfish/src/wallet/wallet.ts

followup to #2695 
defines 'filterAccountsAsync' method to parallelize filtering accounts in the wallet based on an asynchronous function.
checks whether each account has already synced a transaction before calling addPendingTransaction. parallelizes these db checks.
```
[ ] Yes
```

parallelizes checking each account for pending transaction

---

ironfish-rust/src/merkle_note.rs

The comment on NOTE_ENCRYPTION_MINERS_KEYS indicated that the fixed key could be used to distinguish a note as a miner's note, but since we don't enforce that in consensus, the comment isn't accurate.
```
[ ] Yes
```

Update comment on note encryption miner keys constant

---

ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/utils.rs

Realized this code was too easy to get wrong because it was not clear what was happening.
- Removed `verify_proof` from the descriptions since it was only being used by the builders when creating the description. Since it wasn't used when verifying a transaction, it was too easy to add logic here that wouldn't get checked. The mint had a bug because of this - generator point was not being verified.
- Encapsulate all other verification logic into one function so as to not be a leaky abstraction
I think it's time to introduce a trait for descriptions, but I want to wait until the rust changes settle a bit so I'm not creating a ton of merge conflicts
```
[ ] Yes
```

refactor(rust): Encapsulate description verification and remove unused verify_proof functions

---

ironfish/src/merkletree/witness.ts
ironfish/src/primitives/__fixtures__/rawTransaction.test.ts.fixture
ironfish/src/primitives/note.ts
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/primitives/transaction.test.slow.ts
ironfish/src/testUtilities/fixtures.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/__fixtures__/postTransaction.test.ts.fixture
ironfish/src/workerPool/tasks/handlers.ts
ironfish/src/workerPool/tasks/postTransaction.ts
ironfish/src/workerPool/tasks/workerMessage.ts
ironfish/src/workerPool/worker.ts

This will make it so we can create a transaction, and post it separately. To do this a new model is being created called RawTransaction which is returned by wallet.createTransaction().
- Add Wallet.createTransaction() => RawTransaction
- Add Wallet.postTransaction(rawTransaction) => Transaction
- Add WorkerPool.postTransaction(rawTransaction) => Transaction
Remaining work after this PR merges in another PR
- Remove wallet from fee estimator
- Add test for WorkerPool.postTransaction()
- Add test for wallet.createTransaction()
Write new RawTransaction serializer test
```
[ ] Yes
```

Split out createTransaction() from postTansction()

---

.github/workflows/build-ironfish-rust-nodejs.yml
ironfish-rust-nodejs/package.json
yarn.lock

The aarch64-gnu tests seem to have broken due to an incompatible libc. Testing out changes to the github workflow
```
[ ] Yes
```

Test fixing docker build

---

ironfish/src/genesis/genesis.test.slow.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

if all accounts in the wallet are up to date (account head hash equal to chain processor head hash), then there are no blocks to scan. we implement a property on the wallet, shouldRescan, that checks this. however, scanTransactions does not check this when initializing a scan. if a scan starts with beginHash equal to endHash, then that block will be scanned again because chain.iterateBlockHeaders uses an inclusive range. this leads to adding the block to the account a second time.
- checks shouldRescan within scanTransactions before beginning a scan
- fixes genesis test that masked this issue
updates unit tests
```
[ ] Yes
```

wallet should not scan when all accounts up to date

---

.github/workflows/rust_ci.yml

The tarpaulin github action that we were using seemed to have some kind of flake when fetching info from the github API. It also seems possibly unmaintained. So, let's just do the simple thing without layers of abstraction causing difficulty - fetch the built binary and "install" it.
```
[ ] Yes
```

feat(ci): Fetch cargo-tarpaulin binary from github instead of using github action

---

ironfish/src/wallet/account.ts

Get `submittedSequence` from the existing, stored `transactionValue` if it exists, otherwise set it to `null`. This change is needed because `submittedSequence` should be the sequence when the transaction was submitted and not the block's sequence.
```
[ ] Yes
```

Fix submittedSequence in connectTransaction

---

ironfish/src/storage/database/database.ts
ironfish/src/storage/database/types.ts
ironfish/src/storage/levelup/database.ts
ironfish/src/storage/levelup/store.ts

Add `DatabaseIteratorOptions` to separate iteration params from key range params. Merge everything together before passing into levelup's `createReadStream`.
```
[ ] Yes
```

Add DatabaseIteratorOptions

---

ironfish/src/storage/database.test.ts
ironfish/src/storage/database/store.ts
ironfish/src/storage/database/types.ts
ironfish/src/storage/levelup/store.ts

Add support for iterating database entries by key order (levelDB default iteration is by sorted key order but our transaction cache didn't support this)
Added tests in `database.test.ts`
```
[ ] Yes
```

Add support for iterating database entries by key order

---

.github/workflows/build-ironfish-rust-nodejs.yml
.github/workflows/ci.yml
.github/workflows/deploy-brew.yml
.github/workflows/deploy-npm-ironfish-cli.yml
.github/workflows/deploy-npm-ironfish-rust-nodejs.yml
.github/workflows/deploy-npm-ironfish.yml
README.md
ironfish-cli/Dockerfile
ironfish-cli/bin/run
ironfish-cli/package.json
ironfish-rust-nodejs/npm/darwin-arm64/package.json
ironfish-rust-nodejs/npm/darwin-x64/package.json
ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json
ironfish-rust-nodejs/npm/linux-arm64-musl/package.json
ironfish-rust-nodejs/npm/linux-x64-gnu/package.json
ironfish-rust-nodejs/npm/linux-x64-musl/package.json
ironfish-rust-nodejs/npm/win32-x64-msvc/package.json
ironfish-rust-nodejs/package.json
yarn.lock

Requires the latest LTS, Nodejs 18, when running `ironfish`.
Leaving this in draft intentionally until after the next release, since there's a good chance it'll break some of the github actions.
```
[ ] Yes
```

Update to Nodejs 18

---

ironfish/src/blockchain/blockchain.ts

A while back a change was made to do block database updates and block verification in parallel. This works because saving the block is done within an atomic transaction and if block verification later fails then the transaction can be rolled back. There are a few in-memory updates however that are not done within the database transaction and would not be rolled back such as updating the `chain.head` and `chain.latest` in memory objects. This PR fixes a potential bug where chain.latest can be updated outside of a database transaction. 
Unit tests
```
[ ] Yes
```

Don't save latest until transaction commit

---

ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/rpc/routes/wallet/removeAccount.ts
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/__fixtures__/balanceValue.test.ts.fixture
ironfish/src/wallet/walletdb/balanceValue.test.ts
ironfish/src/wallet/walletdb/balanceValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

instead of storing only a bigint with the asset balance as the value in the balances store, stores an object containing the balance and the block hash and sequence of the most recent balance update.
now that we only update the balance when blocks are connected and disconnected from the chain the stored balance value corresponds to a specific chain state. storing this chain state alongside the balance will allow us to inform users of what chain state their balance reflects. a number of users were confused by balances while accounts were scanning during phase 2: their transactions would be on the chain, but the transaction wouldn't be reflected in their account balance because the account was behind the chain.
- defines BalanceValue type to include balance, blockHash, and sequence
- …

adds chain state fields to balances datastore

---

ironfish/src/rpc/routes/assets/mint.test.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/rpc/routes/wallet/getNotes.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts

All currency encoding should be done using CurrencyUtils.encode() and CurrencyUtils.decode()
```
[ ] Yes
```

Fix note encoding not using CurrencyUtils

---

ironfish/src/wallet/account.ts
ironfish/src/wallet/walletdb/__fixtures__/transactionValue.test.ts.fixture
ironfish/src/wallet/walletdb/transactionValue.test.ts
ironfish/src/wallet/walletdb/transactionValue.ts

users currently cannot see how much they sent or received in each transaction listed in the CLI. the only way to present this information to the user with the current walletDb schema would be to load each note and spend for each transaction each time we look up the transaction.
stores the balance delta for each asset on the value in the wallet transactions store.
serializes buffer map as a list of key-value pairs prepended with the length of the list. keys are 32-byte asset identifiers and values are bigints.
```
[ ] Yes
```

adds balance delta mapping to transactionValue

---

ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/value_balances.rs

Right now, its possible to add enough value to a transaction via mints
or spends such that it would overflow the `i64` type in the
`ValueBalance` struct. By using `checked_add`, we get some cleaner error
handling around this logic. Note that this doesn't functionally change
much, it's just more explicit error handling.
As a future improvement, we could use an
arbitrarily large value type for `ValueBalance` like `i128`, and change
the logic on `Transaction::post` to loop over the values and create
multiple change notes, allowing value transfers of greater than
`u64::MAX`, if we ever needed to.
```
[ ] Yes
```

feat(rust): use `checked_add` for `ValueBalance`

---

ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/transactionValue.test.ts
ironfish/src/wallet/walletdb/transactionValue.ts

in the past we only populated submittedSequence for transactions that the node created and submitted.
now we also populate submittedSequence for any transaction that is gossiped to the node.
submittedSequence should no longer be null for any transaction in the wallet.
- defaults submittedSequence to the block sequence for transactions found on blocks but not previously synced to the wallet through the mempool
```
[ ] Yes
```

fixes submittedSequence to be non-nullable

---

ironfish/src/primitives/transaction.test.slow.ts
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

most datastores in the wallet are keyed by account and managed by the account. headHashes is an exception in that the wallet writes to the datastore and uses an in-memory cache of values.
- removes in-memory headHashes cache
- removes wallet methods for writing to headHashes
- removes update of head hashes on wallet close (head hashes should only be updated when a block is connected or disconnected)
- defines updateHeadHash on the account instead of the wallet
```
[ ] Yes
```

delegates headHashes datastore to account

---

ironfish-cli/src/commands/wallet/balance.ts
ironfish/src/rpc/routes/wallet/getBalance.ts
ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

the account balance now includes chain state information (blockHash and sequence). includes this chain state in the balance CLI output so that it's clearer where on the chain the balance is reflective of.
```
[ ] Yes
```

displays balance head hash and sequence in CLI

---

ironfish-cli/src/commands/service/sync-multi-asset.ts
ironfish/src/webApi.ts

Rename multi-asset variables to match changes to API from `masp`->`multi-asset`
```
[ ] Yes
```

fix: bug in multi asset syncer

---

.github/workflows/rust_ci.yml

There appear to be occasional CI failures due to cargo tarpaulin's timeout of 60 seconds being hit. Let's try increasing this to see if it helps.
```
[ ] Yes
```

feat(ci): Increase timeout for cargo tarpaulin

---

ironfish-rust/src/errors.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs

Builds on #2851
The issue here is that we are indirectly enforcing a max value per description of `i64`, but allowing larger values. By using `as` to cast them, they would silently wrap, which will likely cause issues. By explicitly using `TryFrom` trait, we get checked casting.
```
[ ] Yes
```

feat(rust): Use fallible casting so values arent silently incorrect

---

ironfish/src/blockchain/blockchain.test.ts

This causes issues when we are, for example, regenerating test fixtures. We can override them via the CLI now, but the hardcoded one as a test argument take ultimate precedence.
```
[ ] Yes
```

fix(test): Remove hard-coded test timeout override

---

ironfish/src/defaultNetworkDefinitions.ts
ironfish/src/fileStores/internal.ts
ironfish/src/networkDefinition.ts

No default bootstrap node currently set for our network defintion. Adding here
```
[ ] Yes
```

chore: test bootstrap node definition and TESTING -> TESTNET rename

---

ironfish/src/wallet/wallet.ts

we should not automatically start a scan if the chainProcessor hash is null - if there are no accounts to scan then we should not scan. instead we can rely on the other check on 'isAccountUpToDate' in 'shouldRescan'.
- removes check on chainProcessor.hash in shouldRescan
- replaces extra call to shouldRescan in scanTransactions with early termination if beginHash is equal to endHash
```
[ ] Yes
```

fixes wallet scan failures

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

minersFee transactions have no expiration so they will remain in a pending state forever unless removed. there is no need to persist the minersFee transactions form a fork in the wallet: if they are added to the main chain again in a re-org then we will re-sync them.
- defines removeTransaction to execute the same logic as expireTransaction, but deletes the transaction from the database
- cleans up some unnecessary code in expireTransaction and deleteDecryptedNote
```
[ ] Yes
```

removes miners fee transactions from forked blocks

---

ironfish-cli/bin/run
ironfish-rust-nodejs/package.json

When users are told to upgrade to Node v18 they will also need to reinstall the `ironfish` package. This adds a message with those instructions. 
Tested locally
```
[ ] Yes
```

Add instructions to upgrading Node version

---

ironfish/src/wallet/wallet.test.ts

`getHeadHash` has been renamed as `getHead` in https://github.com/iron-fish/ironfish/commit/901b4ff2ccedb1ee2a3ef32a7eed1db9d5873932
```
[ ] Yes
```

Fix test fails

---

ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts

reading the account head at the wallet level is unnecessary since its only use there is to be passed down to the account.
- updates getBalance and getBalances to read account head in the account-level methods
- removes unnecessary db transaction in getBalance
```
[ ] Yes
```

reads head sequence at account level in balance methods

---

ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts

the wallet getUnspentNotes method filters all unspent notes that the account level method returns by the account's head sequence.
moving this filtering down to the account level method puts all of the filtering logic for unspent notes in one place.
```
[ ] Yes
```

filters by sequence in getUnspentNotes at account level

---

ironfish-cli/src/commands/service/sync-multi-asset.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts

1. Fixes bug in transaction syncer command. The condition should be reverse. Identified this bug by checking logs of `multi-asset-syncer` running in AWS after adding some multi asset transactions/blocks.
2. Decoding error was occurring in `getTransactionStream`, fixed that as well.
Tested in production by:
1. Created mint/burns with commands:
```
yarn run ironfish wallet:mint -a 100000 -f default -o 1 -n jowparks -m "minting on chain"
yarn run ironfish wallet:burn -i "8b03915814798e708ad6a3093ba2f283dcca537670b82e83d30a55077d3b4595" -a 1000 -f default -o 1
```
1. Updating database head to rescan chain with:
```
UPDATE multi_asset_head SET block_hash = 'd179d8b74987d6617267d46f4958554ba0df02d7e5e6117db02d6ff38fd0f6da' WHERE id = '1';
```
1. `yarn build && yarn`
1. Rescanning with multi …

fix: bug transactions in multi asset syncer and 

---

Cargo.lock

Probably should merge #2873 first so we can rebase and get the CI to run on this PR
Ran `cargo update -p regex --precise 1.5.6`
```
[ ] Yes
```

chore(rust): upgrade rust transitive dependency for security fixes

---

ironfish-cli/src/commands/wallet/repair.ts
ironfish/src/consensus/utils.ts
ironfish/src/consensus/verifier.ts
ironfish/src/memPool/memPool.test.ts
ironfish/src/memPool/memPool.ts
ironfish/src/mining/manager.ts
ironfish/src/wallet/wallet.ts

the logic of isExpiredSequence is very simple and is independent of any other state (i.e., it doesn't depend on the chain)
since this method is currently defined on the Verifier class it has a dependeny on the chain.
the wallet uses isExpiredSequence in several places. moving isExpiredSequence into a utils module removes a source of chain dependence in the wallet
```
[ ] Yes
```

moves isExpiredSequence off of Verifier

---

ironfish/src/webApi.ts

Reuses the existing API endpoint for `deposits/address` to get the IronBank Address. We will need this once we make a CLI command for users to automatically transfer assets to IronBank
```
[ ] Yes
```

chore: add multi asset address

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts

Since the public address size changed and we changed some of our key personalization strings, it was possibly to import an account that was in an invalid state by importing an incorrect (but technically valid) incoming and outgoing view key
```
[ ] Yes
```

feat(ironfish,cli): Change account import to only use spending key

---

ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish/src/fileStores/config.ts
ironfish/src/rpc/routes/wallet/getBalance.ts
ironfish/src/rpc/routes/wallet/getBalances.ts
ironfish/src/testUtilities/nodeTest.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

confirmations is a well-known concept in crypto.
the 'confirmations' name is much more concise and still expresses what the variable represents.
```
[ ] Yes
```

renames minimumBlockConfirmations to confirmations

---

ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/wallet/wallet.ts

- replaces 'header' variable naming with 'head'
- removes unnecessary 'getAccountHeadSequence' method
```
[ ] Yes
```

cleans up account head usage in wallet

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/wallet/wallet.ts

I'm thinking of replacing the AsyncGenerator return type to a regular array for iterateBlockTransaction in the blockchain here. It doesn't seem like we need a generator because there's no async operation for each transaction, and this would give the caller control over order of transactions.
```
[ ] Yes
```

feat(ironfish): Remove `AsyncGenerator` return type from `iterateBlockTransactions`

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/wallet/wallet.ts

* Fetching block transactions should be in the same order as on the block object
* Disconnecting block transactions should be done in reverse order
N/A
```
[ ] Yes
```

fix(ironfish): Keep consistent iteration in block connect events

---

ironfish/src/typedefs/bufio.d.ts
ironfish/src/wallet/walletdb/__fixtures__/transactionValue.test.ts.fixture
ironfish/src/wallet/walletdb/transactionValue.test.ts
ironfish/src/wallet/walletdb/transactionValue.ts

balance delta will be negative for any outgoing transaction
adds ReadBigI64/WriteBigI64 to bufio types to support reading negative bigint values
adds test of serialization and deserialization of negative balance delta
```
[ ] Yes
```

fixes transactionValue to use signed bigints in balance deltas

---

ironfish-cli/src/commands/wallet/transactions.ts

displays a check mark in the 'Creator' and 'Miner Fee' columns if those conditions are true, but a blank space otherwise.
Before:
After:
```
[ ] Yes
```

replaces 'x' with blank space in transactions cli

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts

allows users to specify confirmations for determining transaction status
```
[ ] Yes
```

adds 'confirmations' option to wallet:transactions

---

ironfish/src/webApi.ts

adds a missing 's': `deposit` -> `deposits`
https://api.ironfish.network/deposits/address
vs.
https://api.ironfish.network/deposit/address
```
[ ] Yes
```

fixes webApi URL for /deposits/address

---

ironfish-cli/src/commands/wallet/transaction.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/types.ts

updates the table of output notes to include the asset name and id for each note.
```
[ ] Yes
```

adds asset name, id to notes in wallet:transaction output

---

ironfish/src/rpc/routes/wallet/getTransactions.ts

before we indexed transactions by time we implemented a feature on the getTransactions endpoint to sort transactions and limit the number returned.
the implementation iterated over all transactions and maintained a priority queue of the 'n' most recent transactions.
now that we iterate over transactions in order of time it's much simpler to impose the limit by stopping early when we've streamed enough transactions back.
deletes the 'handle*' functions added to distinguish between the 'limit' and 'all' cases and uses the limit to return early from streaming all transactions.
```
[ ] Yes
```

simplifies getTransactions logic with limit

---

ironfish-cli/package.json
ironfish-cli/src/commands/wallet/send.ts
yarn.lock

Per the [oclif docs](https://oclif.io/docs/prompting#inquirer), they recommend the `inquirer` lib for this. We also had it installed already as a transitive dependency.
Since we're adding this new functionality: we should use this `inquirer` selector any time we have a known, finite list of things to select from. It's a huge improvement over making the user go look up the information out-of-band and then look up the flag to pass into the CLI.
```
[ ] Yes
```

feat(cli): Add asset selector for `wallet:send`

---

ironfish-cli/src/commands/wallet/send.ts

The short-form flags are not very clear, especially when used in examples. I would expect people looking at the examples to not be familiar with the CLI flags, so using the long-form ones should help clarify.
```
[ ] Yes
```

fix(cli): `wallet:send` examples use long-form arguments for clarity

---

ironfish/src/rpc/routes/wallet/mintAsset.ts

This PR proposes to change the wallet:mint rpc endpoint to allow empty metadata arguments. If no metadata is provided, the rpc endpoint will use an empty string.
Open to suggestions. `yarn test` passes but this behavior isn't explicitly tested.
```
[ ] Yes
[X] No
```

Make metadata an optional field in minting, else default to empty string

---

ironfish-cli/src/commands/peers/show.ts
ironfish-cli/src/commands/wallet/transaction.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/utils/time.ts

This adds a way to consistently render time in a human format across all of our CLI tools, and includes it in the SDK so other people can use our same time format.
**TimeUtils.renderDate()**
```bash
Timestamp     Hash                                                            
───────────── ────────────────────────────────────────────────────────────────
1/13/2023 EST 662fc308dc6ac9eb0a17595a2b107dc9574e2e3b8942bed19a5081c97086a072
```
**TimeUtils.renderTime()**
```bash
Timestamp      Hash                                                            
────────────── ────────────────────────────────────────────────────────────────
2:49:11 PM EST 662fc308dc6ac9eb0a17595a2b107dc9574e2e3b8942bed19a5081c97086a072
```
**TimeUtils.renderString()**
```bash
Timestamp                Hash …
```

Show timezones for all CLI timestamps

---

ironfish-cli/src/commands/wallet/transaction.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts

adds mintsCount and burnsCount to getTransaction RPC response and wallet:transactions CLI output
reorders notesCount and spendsCount to be consistent with ordering in wallet:transactions
```
[ ] Yes
```

adds mints count and burns count to wallet:transaction

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/rpc/routes/wallet/types.ts

the transactionValue stored in the walletDb now includes a mapping from assetId to the balance delta for that account and asset in the transaction. this allows us to return transaction amounts in our RPC responses and display them in the CLI.
serializes assetBalanceDeltas as a JSON string because yup does not support map types.
only includes the balance delta for IRON in the CLI output table. we can show balance deltas for all assets in a transaction more easily in the output for a single transaction in wallet:transaction
```
[ ] Yes
```

adds IRON amount to wallet:transactions output

---

ironfish-cli/src/commands/wallet/transaction.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/wallet/wallet.ts

defines TransactionType as one of miner, send, or receive.
a transaction has a miner type if it is a miner's fee transaction.
a transaction is a send if any of the spent notes belong to the account.
otherwise a transaction is a receive.
- adds TransactionType and getTransactionType to wallet
- replaces creator with type in getTransactions
- adds type to getTransaction
- removes isMinersFee from both endpoints
- updates CLI for wallet:transaction and wallet:transactions
```
[ ] Yes
```

replaces creator and isMinersFee with transaction type

---

ironfish-cli/src/commands/wallet/transaction.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts

Builds off of #2907 to dump all asset deltas when inspecting a single transaction.
Looking for input as to whether this is correct & whether this is the desired UX. 
Plan
```
[ ] Yes
[X] No
```

Display asset deltas when calling wallet:transaction

---

ironfish/src/wallet/errors.ts

`NotEnoughFundsError` just dumps the raw ore amounts and assetID. Use `CurrencyUtils.renderIron` instead.
`yarn test` locally detected no errors.
```
[ ] Yes
[X] No
```

Change NotEnoughFundsError to use CurrencyUtils.renderIron

---

ironfish-cli/package.json

These are only used to override topic descriptions as described here https://oclif.io/docs/topics
```
[ ] Yes
```

Remove topic overrides

---

ironfish-cli/src/commands/wallet/mint.ts

Avoid prompt if a new asset can be inferred from the flags
Using graffiti:
```sh
rohan@x13-nixos ~/g/i/ironfish-cli (refactor/rohan/mint-interactive)> f wallet:mint --name=$(f config:get blockGraffiti)
$ yarn build && yarn start:js wallet:mint '--name=yarn run v1.22.19' '--name=$ yarn build && yarn start:js config:get blockGraffiti' '--name=$ tsc -b' '--name=$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run config:get blockGraffiti' '--name="rohanjadvani"' '--name=Done in 3.13s.'
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:mint '--name=yarn run v1.22.19' '--name=$ yarn build && yarn …
```

fix(cli): Avoid prompt in mint if metadata or name provided

---

ironfish-cli/src/commands/wallet/balance.ts

Just saw this when tracking down a crash, though I'm not sure if this is related.
This caused this crash because the node probably wasn't updated. Either way we may not need this.
```
TypeError: Cannot read properties of undefined (reading 'toString')
at BalanceCommand.explainBalance (D:\repos\ironfish\ironfish-cli\src\commands\accounts\balance.ts:85:71)
at BalanceCommand.start (D:\repos\ironfish\ironfish-cli\src\commands\accounts\balance.ts:53:12)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at BalanceCommand.run (D:\repos\ironfish\ironfish-cli\src\command.ts:73:7)
at async BalanceCommand._run (D:\repos\ironfish\ironfish-cli\node_modules\@oclif\core\lib\command.js:80:22)
at async Config.runCommand …
```

Remove unneeded toString() in explain balance

---

ironfish-cli/src/commands/wallet/notes.ts
ironfish-cli/src/commands/wallet/transaction.ts
ironfish/src/rpc/routes/wallet/getNotes.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts

instead of serializing the asset name using utf-8 before sending over RPC serializes asset name as a hex string, like all other buffers.
uses BufferUtils.toHuman to render the asset name on the client side.
ran `wallet:notes` and `wallet:transaction` to ensure that asset name is still rendered correctly
```
[ ] Yes
```

changes RPC serialization of asset name to use hex

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/asset.ts

* Show single asset options in mint / burn so it's clear which asset is being operated on
* Add action to improve message
```sh
rohan@x13-nixos ~/g/i/ironfish-cli (feat/rohan/show-single-balance)> f wallet:mint
$ yarn build && yarn start:js wallet:mint
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:mint
Do you want to create a new asset (Y/N)?: N
? Select the asset you wish to mint 618c098d8d008c9f78f6155947014901a019d9ec17160dc0f0d1bb1c764b29b4 (rohancoin)
```
```
[ ] Yes
```

feat(cli): Improve usability when selecting asset

---

ironfish-cli/src/commands/wallet/mint.ts

new asset without confirm flag
existing asset without confirm flag
with confirm flag
```
[ ] Yes
```

feat(cli): add a confirm flag/step to mint

---

ironfish-cli/src/commands/faucet.ts
ironfish/src/rpc/routes/wallet/utils.ts

This is a bug fix for `ironfish faucet` command.
Proposed commands are fixed to correct: from `ironfish accounts` to `ironfish wallet`
Successful run of `ironfish faucet` command is needed to check if the suggested commands are correct
```
[ ] No, it's not. Cosmetic change
```

Fix_#2966-corrected-account-command-to-wallet

---

ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts
ironfish/src/wallet/errors.ts

removes message indicating that 'balance changed' since we no longer store pending balances.
NotEnoughFundsError when sending a transaction is now likely to occur if not enough notes are available to spend because of pending or unconfirmed transactions.
```
[ ] Yes
```

changes NotEnoughFundsError messages

---

ironfish-cli/src/commands/wallet/burn.ts

without confirm flag
with confirm flag
```
[ ] Yes
```

feat(cli): add confirm flag/step to burn

---

ironfish-cli/src/commands/reset.ts

use of `reset` command will now change `networkId` to its default value
```
[ ] Yes
```

fix: networkId defaults set upon run of reset command

---

ironfish/src/rpc/routes/faucet/getFunds.ts

We're sending 422 for all validation errors, with specific codes, and not printing out the right message.
It was originally added in https://github.com/iron-fish/ironfish/pull/562 and removed in https://github.com/iron-fish/ironfish/pull/1261
```
[ ] Yes
```

Fix catching validation error as invalid email

---

ironfish/src/wallet/errors.ts

purely cosmetic change to error text
```
[ ] Yes
```

removes extra ' character in error message

---

ironfish-cli/src/commands/service/faucet.ts

This probably wouldn't cause any issues, but just in case
```
[ ] Yes
```

fix(cli): Fix typo. Fake address should be 64 characters, not 63

---

ironfish/src/fileStores/config.ts
ironfish/src/fileStores/internal.ts

Since these got out of alignment, we couldn't actually override the config to use the dev network
```
[ ] Yes
```

fix(ironfish): align default network id for internal and config

---

.github/workflows/build-ironfish-rust-nodejs.yml

Problem: https://github.com/iron-fish/ironfish/actions/runs/3963411310/jobs/6791201687
Green test run: https://github.com/iron-fish/ironfish/actions/runs/3963638104/jobs/6791695422
```
[ ] Yes
```

fix(ci): dont build windows binary with zig

---

ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts

the confirmed balance for an account is equal to the unconfirmed balance of the account excluding any unconfirmed transactions.
we currently subtract the value of any notes received in unconfirmed transactions, but we do not add the value of any notes spent. this leads to a temporarily incorrect value computed for confirmed balance.
- fixes calculateUnconfirmedCountandConfirmedBalance to use transactions and transaction balance deltas
- changes CLI terms to refer to unconfirmed transactions instead of unconfirmed notes
- adds test confirming bug and fix
```
[ ] Yes
```

fixes calculation of confirmed balance

---

ironfish/src/rpc/routes/wallet/removeAccount.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

the purpose of resetting an account is to clear all of an account's data but preserve the account's keys and the record of the account.
this is functionally equivalent to deleting all account data except the data in the accounts store. however, this will crash for large accounts because we attempt to delete all data within a single database transaction.
instead of deleting the account outright we can use a mark and sweep strategy: 'resetAccount' marks an account as deleted so that its data is cleaned up asynchronously in the event loop.
to prevent deletion of the account record 'resetAccount' creates a new account with the same name and same key but a different account id. the id is not user facing and is only used for database storage.
- defines resetAccount
- splits the logic of …

fixes account reset to use mark and sweep

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/assetBalances.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

defines AssetBalances class to encapsulate helpful increment and update functions on BufferMap<bigint>
returns AssetBalances from connectTransaction and disconnectTransaction with the asset balance deltas for the transaction
updates the balance store once for each account on each block connect and disconnect
changes updateUnconfirmedBalances to update balance for all assets with the new hash and sequence as well as any balance delta
adds tests of updating balances for all assets on each block connect and disconnect
```
[ ] Yes
```

updates balances store for each block

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/table.ts

This will help render timestamp columsn better, by not having to re-guess the length of a timestamp column everywhere. This is particularly good for streaming tables.
Before
```
Timestamp                Status      Type    Hash                                                             Amount ($IRON)      Fee ($IRON)         Notes Spends Mints Burns Expiration
──────────────────────── ─────────── ─────── ──────────────────────────────────────────────────────────────── ─────────────────── ─────────────────── ───── ────── ───── ───── ──────────
1/19/2023 8:50:23 PM EST confirmed   receive 1b4d7e3775f7f9f3746cc1913bae0108ba65030918105b4597e663dfb1ad4a76 0.22877871          0.00000121          122   12     0     0     3536
1/18/2023 11:32:24 PM EST confirmed   send …
```

Create a timestamp column

---

ironfish-cli/src/commands/wallet/transaction.ts
ironfish/src/primitives/note.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/types.ts

Add owner address to output of the `wallet:transaction` cli command
```
fish wallet:transaction d14bfaf495231252fa6ca01a299435e7453ba10e08e393df3ee6a953e560276a --datadir="~/.phase3v9"                                                                                              ─╯
$ yarn build && yarn start:js wallet:transaction d14bfaf495231252fa6ca01a299435e7453ba10e08e393df3ee6a953e560276a '--datadir=~/.phase3v9'
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:transaction d14bfaf495231252fa6ca01a299435e7453ba10e08e393df3ee6a953e560276a '--datadir=~/.phase3v9'
Transaction: d14bfaf495231252fa6ca01a299435e7453ba10e08e393df3ee6a953e560276a
Account: default
Status: confirmed …
```

feat: owner address to transaction cli

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

the upper limit for expiration sequences in the pendingTransactionHashes key should be the maximum 32 bit integer value. '2 ^32' is equal to 34, because '^' is exclusive or, not exponentation.
fixes upper limit to use 2**32
```
[ ] Yes
```

fixes key range for pending transactions

---

ironfish-cli/src/commands/chain/genesisblock.ts
ironfish-cli/src/commands/miners/pools/start.ts
ironfish-cli/src/commands/service/estimate-fee-rates.ts
ironfish-cli/src/commands/service/forks.ts
ironfish-cli/src/flags.ts

Add a character shortcut for the --datadir flag since it's used often in development. Remove other -d flags because they are not used often
local testing. Also checked terraform to see that we are [not using -d flag](https://github.com/iron-fish/terraform/blob/1e667c6984b1827e8e7bc5f41bd94294acac7667/modules/pool/main.tf#L36)
```
[ ] Yes
```

Add char flag datadir

---

ironfish-rust-nodejs/src/structs/transaction.rs

We occasionally see segfaults coming from allocating a new reference to a buffer
in verifyTransactions. I wasn't able to easily reproduce this, but in other places
we use JsBuffer instead of Buffer, so trying that here as well.
```
[ ] Yes
```

Change Buffer to JsBuffer in verifyTransactions

---

ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
ironfish/src/blockchain/blockchain.test.ts

The test preventing burns and spends in the same transaction was failing to regenerate fixtures due to burning the native asset. Updated the test to use a non-native asset.
```
[ ] Yes
```

Fix blockchain.test.ts fixture regeneration

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/lib.rs
ironfish-rust/src/mining/thread.rs
ironfish-rust/src/mining/threadpool.rs
ironfish/src/mining/poolMiner.ts
ironfish/src/mining/soloMiner.ts

This will still submit multiple blocks in the case of having a high thread count and a very easy target, but it will be at most n submissions where n is the number of threads. This still allows the node to process and create a new block template, making it much harder for the node to get overloaded
```
[ ] Yes
```

fix: solo miner will wait for new work after submitting

---

ironfish-cli/src/commands/wallet/delete.ts

Renamed the `wallet:remove` command to `wallet:delete`
```
➜  ironfish-cli git:(austin/cli-rename-remove-cmd) yarn start wallet
$ yarn build && yarn start:js wallet
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet
List all the accounts on the node
USAGE
$ ironfish wallet:COMMAND
COMMANDS
wallet:accounts      List all the accounts on the node
wallet:address       Display your account address
wallet:balance       Display the account balance
wallet:balances      Display the account's balances for all assets
wallet:burn          Burn tokens and decrease supply for a given asset
wallet:create        Create a new account for sending and receiving coins
wallet:delete …
```

feat(cli): rename wallet:remove to wallet:delete

---

ironfish-cli/src/utils/table.ts

uses estimated maximum width when streaming
Before:
After:
```
[ ] Yes
```

fixes oclif custom timestamp column width

---

ironfish-cli/src/commands/wallet/transactions.ts

uses transaction type to determine whether to do fee correction on IRON amount in transaction.
renames 'Fee ($IRON)' column to 'Fee Paid ($IRON)' and only displays the fee if the account paid the transaction fee.
renames 'Amount ($IRON)' column to 'Net Amount ($IRON)' and only displays non-zero values.
defines type for TransactionRow and defines separate function for constructing the row from the transaction response.
Before:
After:
```
[ ] Yes
```

excludes fee paid from amount in transactions list

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts

adds tests that ensure that outgoing transactions have a transaction type of SEND, incoming transactions have a transaction type of RECEIVE, and miners fee transactions have a type of MINER.
mints and burns are treated as SENDs.
```
[ ] Yes
```

adds tests for getTransactionType

---

ironfish-cli/src/commands/service/ceremony.ts
ironfish-cli/src/trusted-setup/schema.ts
ironfish-cli/src/trusted-setup/server.ts

Parsing messages from clients using yup so un-parsable messages do not crash the server. Also paramtaraizing timeouts on the server side so we can increase them if clients are having trouble uploading or contributing in the allotted time 
Tested locally
```
[ ] Yes
```

parse client messages and pass in timeouts to server script

---

ironfish/src/telemetry/telemetry.ts

Add Influx support for tracking the duration required to create new block templates. [This accompanying PR](https://github.com/iron-fish/ironfish-api/pull/1194) in the `ironfish-api` repo adds the measurement `create_new_block_template_duration` to the Influx telemetry whitelist. 
- Builds successfully locally
```
➜  ironfish-cli git:(holahula/feat/influx-block-template-support) yarn start start
$ yarn build && yarn start:js start
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run start
::::::::::          :::::::::::::::::
::::::::::::       :::::::::::::::::::
:::::::::::::     :::::::::::::::::::::
::::::::::::::   ::::::::::::::::::::::::
::::::::::::: ::::::::::        ::::::::: …
```

feat(ironfish): add influx support for tracking the duration required to create new block templates

---

ironfish-cli/src/trusted-setup/server.ts

Don't allow more than one connection per ip for trusted setup ceremony
```
[ ] Yes
```

Don't allow more than one connection per ip for trusted setup ceremony

---

ironfish-cli/src/commands/ceremony.ts
ironfish-cli/src/trusted-setup/client.ts

Trusted setup does not use http so we need to remove that. Also adding some logic to display connection errors
```
[ ] Yes
```

Fix default host for trusted setup

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/flags.ts

There have been a number of issues raised relating to overflow/underflow of coin amounts people are inputting. See https://github.com/iron-fish/ironfish/issues/2984, https://github.com/iron-fish/ironfish/issues/3043, https://github.com/iron-fish/ironfish/issues/3066. 
This task is aimed at improving input checks by 
1) catching underflow errors from `decodeIron` that result in https://github.com/iron-fish/ironfish/issues/3066
2) checking fee/coin inputs are within the valid range of **MINIMUM_ORE_AMOUNT** to **MAXIMUM_ORE_AMOUNT**
test `wallet:send/mint/burn` commands with fee and coin inputs that are outside the valid range
```
[ ] Yes
```

Check validity of coin/fee input numbers

---

ironfish-cli/src/commands/peers/index.ts
ironfish-cli/src/types.ts

Need this for all oclif table features like --no-truncate
```
[ ] Yes
```

Pass oclif table flags into peers table

---

ironfish/src/rpc/routes/chain/getBlock.ts

`getBlock` returns a random block of the specified `index` (height), this pr proposes to return the only one on-chain block, which is the same as `getBlockInfo` route does now. So that `getBlockWithIndex` and `getBlockInfoWithSequence` return the block with same `hash`.
```
[ ] Yes
```

getBlock route returns on-chain block of the specified index

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/table.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/rpc/routes/wallet/types.ts

adds additional rows for each asset in a transaction beneath the native asset row.
each custom asset row displays the asset ID and the net amount of that asset in the transaction.
converts '*Count' columns to 'extended' columns that are not displayed by default.
updates getTransactions and getTransaction to include asset name in
assetBalanceDeltas with each transaction so that asset name can be displayed
with balances.
truncates the asset name column unless the '--extended' flag is passed to show
all columns in the table.
```
[ ] Yes
```

shows all assets for each transaction in transactions list

---

ironfish/src/rpc/routes/chain/getBlock.test.ts
ironfish/src/rpc/routes/chain/getBlock.ts

Use string as block difficulty in `getBlock`, instead of Number

---

ironfish/src/rpc/routes/chain/__fixtures__/getBlockInfo.test.ts.fixture
ironfish/src/rpc/routes/chain/getBlockInfo.test.ts
ironfish/src/rpc/routes/chain/getBlockInfo.ts

This adds a `confirmations` optional flag to the request, which will override the default config. Otherwise, it will use the default `confirmations` config to determine whether the block is confirmed or not. It will include this boolean in the response's `metadata` as `confirmed`
```
[ ] Yes
```

feat(ironfish): getBlockInfo RPC supports confirmation

---

ironfish/src/mining/pool.ts
ironfish/src/mining/poolShares.ts

The goal here is to simplify the pool logic a little bit. With the coming refactors, it will be much easier if we have the main logic in one place, so it can be extended and refactored without introducing a bunch of random timeouts or intervals. This also will make it easier to read and maintain the code going forward, I hope.
One thing I want to point out: I intentionally left the existing intervals in the pool class, since they're a bit more time-sensitive. It would feel awkward if these were getting delayed because of the event loop, which I expect to be a long running function much of the time. It will eventually check for confirmed blocks, transactions, etc. on top of doing more logic around figuring out payout amounts, payout buckets, etc. …

feat(ironfish): introduce an event loop for mining pool

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust/src/errors.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/test.rs

- Exposes Mnemonic phrase generation from the rust side into TS side. 
- Uses the `bip39` library we already have installed.
- Adds `LanguageCode` enum for usage typescript side. Sadly the support for enums is crap in napi, manual mapping is the best we can do.
I considered adding the function to a new `.rs` file (ie `keys.ts`) but I saw there was a pattern for key helper functions already set up in `lib.rs` didn't want to diverge in this PR.
[Next pull request will be added here. It will update the export command and call this NAPI function.](https://github.com/iron-fish/ironfish/pull/3207)
Tests
```
[ ] Yes
```

feat: export mnemonic (1/2)

---

ironfish-cli/src/command.ts

It's not easy to debug CLI errors from the RPC. You need to add a log here, but it's nicer if in verbose mode this automatically happens. This helped me locally, let me know if you think this is a good idea or not.
```
[ ] Yes
```

Debug log CLI error if it exists

---

ironfish-cli/src/trusted-setup/server.ts

The server would crash when banning users by IP because it hadn't bound the error handlers yet.
Also, the server didn't check if the current contributor has the same IP as the newly connected client.
```
[ ] Yes
```

trusted-setup: Fix server IP banning

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

a recent change (#2897) made decrypting spender notes optional. a side effect of that change is that the wallet no longer syncs transactions to an account if the account does not receive any notes from the transaction.
this is correct unless the account spent notes in the transaction and did not receive any notes in the transaction.
fixes syncing transactions without change received by checking whether an account owns any of the spends in the transaction.
syncs a transaction to an account if the account has decrypted output notes for the transaction OR the account owns any of the notes that were spent as inputs to the transaction.
```
[ ] Yes
```

fixes syncing transactions with no change

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/walletdb/transactionAmountsValue.test.ts
ironfish/src/wallet/walletdb/transactionAmountsValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

the transactions datastore includes a field 'assetBalanceDeltas' on each record that stores a mapping from asset ID to the net amount or balance delta for that asset in the transaction.
however, there are some cases, such as computing the amount of an asset that an account has available to spend, where it is useful to separate the amount that the account input into the transaction from the amount that the account received output from the transaction.
the transactionAmounts datastore stores the input and output amounts for each account, transaction hash, and asset id.
this datastore will allow us to efficiently compute the 'available' or 'spendable' balance by reading the amount spent in a transaction without iterating over a transaction's spends and looking up decrypted notes for those …

adds transactionAmounts datastore to walletDb

---

ironfish-cli/src/trusted-setup/server.ts

We were sending 0 indexed queue locations but we want to send 1 indexed
```
[ ] Yes
```

send correct queue location

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/test.rs

PR 1/2
Adds support rust/rust-nodejs for getting spending key string from words.
Unittests
```
[ ] Yes
```

feat: import mnemonic from words (1/2)

---

ironfish-cli/src/commands/wallet/export.ts

This was a misnamed function causing lints on staging to fail after merging #3218 and #3207 separately. Also, since this is exporting, I think it should be taking a spending key and outputting words, rather than taking words and outputting a spending key.
```
[ ] Yes
```

Swap wordsToSpendingKey for spendingKeyToWords

---

ironfish-cli/src/commands/chain/asset.ts

Fixing bug https://github.com/iron-fish/ironfish/issues/3234. Args name should be `id`.
Run `chain:asset` and check that bug is gone
```
[ ] Yes
```

Fix chain:asset args name

---

codecov.yml

We are not writing tests currently for `ironfish-cli` so this is conflating our actual code coverage reports. Removing this, we can revert this change if we start writing tests again for cli.
```
[ ] Yes
```

chore: remove codecov cli

---

ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts
ironfish-cli/src/utils/transaction.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts

https://asciinema.org/a/aV8PobDK15767HElhB7yMKez3
You can now pass --watch to send or use the new command wallet:transaction:watch
Run `ironfish wallet:transaction:watch` or `ironfish wallet:send --watch`
```
[ ] Yes
```

Add the ability to watch a transaction status

---

ironfish/src/rpc/routes/wallet/exportAccount.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/wallet/walletdb/accountValue.ts
yarn.lock

This PR proposes to add a `version` member to accounts, in case encoding/decoding changes in the future. Currently, that version is always `1`.
Unit tests.
```
[ ] Yes
[X] No
```

Exported accounts have a version

---

ironfish/src/migrations/data/017-sequence-encoding.ts
ironfish/src/migrations/data/index.ts
ironfish/src/storage/database/encoding.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

we store sequences in several walletDb datastores: sequenceToNoteHash, sequenceToTransactionHash, and pendingTransactionHashes
we use little-endian encodings in the keys for each of these stores. the problem is that we rely on iterating over the keys of these stores *in order* so that we can load keys using sequence ranges. we cannot use little-endian encodings for this kind of ordering; we need to use big-endian encoding instead.
- adds UInt32EncodingBE for big-endian encoding of Uint32 values
- replaces datastores using little-endian encodings with new ones using big-endian encodings
- adds data migration to replace the old stores with the new stores
- adds tests of WalletDB methods that rely on ordered iteration
- Added unit tests, ran on old datastores to confirm the issue
- Ran …

fixes little-endian encodings in walletDb

---

ironfish-cli/src/commands/ceremony.ts
ironfish-cli/src/trusted-setup/client.ts
ironfish-cli/src/trusted-setup/schema.ts
ironfish-cli/src/trusted-setup/server.ts
ironfish-cli/src/utils/s3.ts

For later usage we want to give the user the option to add a name to their contribution. This is in case we want to publicly display the contributions later on.
Local testing
```
[ ] Yes
```

add name to trusted setup submissions

---

ironfish-cli/src/trusted-setup/server.ts

- Add a VERIFYING state to the trusted setup server
- WIP
If a client disconnects while the server is verifying parameters, the server will continue with verifying + uploading the parameters, but will start the next client in the queue at the same time. We should effectively be locking around the process of verifying+uploading verified params to S3, and once a client has uploading their parameters, it's not too important whether they remain connected or not.
This PR adds an additional client state, VERIFYING, that is transitioned to once the client uploads their parameters. If the current contributor disconnects while in this state, the verification will continue.
```
[ …
```

trusted-setup: Handle client disconnects while server is verifying contributions

---

ironfish-cli/src/commands/service/ceremony.ts
ironfish-cli/src/trusted-setup/server.ts

Make banning duplicate contributions by IP the default but allow bypassing it with a command line flag
```
[ ] Yes
```

pass flag for IP banning

---

ironfish-cli/src/commands/service/ceremony.ts

The boolean flags are passed with `--flag` and do not accept an input. If the flag is passed, the result is true and if not the result is false. The current flag has a default of true which is confusing because if it's not passed then it should be false but it instead defaults to true
Local testing
```
[ ] Yes
```

Fix IP flag on trusted setup server

---

ironfish-cli/src/commands/wallet/send.ts

```
yajun@Yajuns-MacBook-Pro ironfish-cli % yarn start wallet:send --rawTransaction -o 0.00000001 -t "dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca" -a 0.00000001
$ yarn build && yarn start:js wallet:send --rawTransaction -o 0.00000001 -t dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca -a 0.00000001
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:send --rawTransaction -o 0.00000001 -t dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca -a 0.00000001
? Select the asset you wish to send d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 ($IRON)
You are about to send:
$IRON 0.00000001 plus a transaction fee of …
```

Add raw tx flag to wallet:send

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts

for an account with many transactions using 'ironfish wallet:transactions' may output a huge list of transactions
we have added '--limit' to support printing out a limited number of recent transactions instead of all of them.
however, we don't have any way of paginating through transactions, so if you want to see the 101st you need to view at least 101 transactions. this adds '--offset' to skip transactions when listing
```
[ ] Yes
```

adds --offset option to transactions list

---

ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/import.ts

A few cleanup items:
1. clean up output of JSON when piping to file
2. Add meaningful error message when failure to decode occurs
3. bug from not trimming newlines in pipe
```
fish wallet:which --datadir=~/.phase3v9
fish wallet:export --datadir=~/.phase3v9
fish wallet:export --datadir=~/.phase3v9 --json
fish wallet:export --datadir=~/.phase3v9 --mnemonic
fish wallet:export  throwaway ~/scratch/throwawayjson  --json --datadir=~/.phase3v9
fish wallet:export  throwaway ~/scratch/throwawaybech32 --datadir=~/.phase3v9
fish wallet:export  throwaway ~/scratch/throwawaymnemonic  --mnemonic --datadir=~/.phase3v9
cat ~/scratch/throwaway
fish wallet:export --mnemonic --datadir=~/.phase3v9
export ACCOUNT_BECH32="ironfishaccount0000010v3xjepz8g3rydtzv43rqwph95ukxvr9956rzcfj94sk2df395mnqwrpx9nxgd3ev3jky …
```

chore: cleanup from testing of import/export

---

ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/utils/language.ts

Detects language based on canonical env vars in shell for language codes
https://user-images.githubusercontent.com/26990067/216724561-8c00df9b-fe94-4a6c-aa1b-ecb77fa4bc57.mov
```
[ ] Yes
```

feat: detect language mnemonic export

---

ironfish-cli/src/trusted-setup/server.ts

When a client disconnected because of an error it was clearing the queue
```
[ ] Yes
```

Fix client disconnect on error

---

ironfish-cli/src/commands/chain/power.ts
ironfish/src/rpc/routes/chain/__fixtures__/getNetworkHashPower.test.ts.fixture
ironfish/src/rpc/routes/chain/getNetworkHashPower.test.ts
ironfish/src/rpc/routes/chain/getNetworkHashPower.ts

Adds CLI support via `ironfish chain:power <lookup> <height>` for retrieving the network's hash power. This builds on the core RPC functionality added in #3266.
**Full prompt**
```
➜  ironfish git:(holahula/feat/network-hashps-command) fish chain:power --help
$ yarn build && yarn start:js chain:power --help
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run chain:power --help
Show the network's hash power (hash/s)
USAGE
$ ironfish chain:power [LOOKUP] [HEIGHT] [-v] [--config <value>] [-d <value>]
ARGUMENTS
LOOKUP  [default: 120] The number of blocks to look back to calculate the power. This value must be > 0
HEIGHT  [default: -1] Estimate network speed at the time of the given height …
```

feat(ironfish-cli): Add CLI support for getting network hash power

---

ironfish-cli/src/commands/wallet/import.ts

When running interactive `wallet:import` in `ironfish-cli`, there is an intended feature that if a user doesn't have a mnemonic (or a bech blob, or a json), the CLI falls through to accepting the hex `spendingKey`. However, the `try`/`catch` meant to enable this behavior doesn't actually catch the error involved:
```
➜  ironfish-cli git:(staging) yarn start wallet:import
$ yarn build && yarn start:js wallet:import
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:import
Paste the output of wallet:export: ignore this and hit enter
Error: Could not detect a valid account format, please verify your account info input
at ImportCommand.stringToAccountImport …
```

Bugfix: account import TTY fallthrough

---

ironfish/src/rpc/routes/chain/getBlock.ts

I'm working on an ironfish explorer, which fetches most chain data with rpc call `getBlock` & `getBlockInfo`. Then I find that two `blockSize` of the specified block from, 1:  `chain.getBlock`, 2:  `chain.followChain`,  are different.
```
[ ] Yes
```

Use getBlockSize & getTransactionSize in getBlock rpc route

---

ironfish-cli/src/utils/asset.ts

Implementing https://github.com/iron-fish/ironfish/issues/3180. Adding confirmed balances to asset selection menu.
Run `ironfish wallet:send/burn/mint` and check balances when selecting the asset from menu
```
[ ] Yes
```

Add balances to asset menu

---

ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/import.ts
ironfish/src/utils/bech32m.test.ts
ironfish/src/utils/bech32m.ts
ironfish/src/utils/index.ts

This moves the bech32 encode/decode scheme to the SDK for reuse
tests
```
[ ] Yes
```

feat: move bech32 to SDK

---

ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/import.ts

This PR proposes to change the CLI `wallet:import` workflow to default to expecting a blob, such as: `ironfish wallet:import pasted_blob`, rather than what it currently expects, a path: `ironfish wallet:import /path/to/a/blob`.  Path can still be supplied with `--importPath`. If the user somehow supplies both a blob and a path, just the blob is used.
Mirroring this behavior, `wallet:export` now needs an explicit argument `--path` if you want to export to a path; it defaults to assuming you would like a blob output to console.
https://user-images.githubusercontent.com/5766842/217118129-15011ebe-d730-46d1-8fa2-c5d5fa4a22a4.mov
Not a breaking change, though users may have to update scripts if they use any, since the usage default changed.
```
[ ] Yes
[X] No
```

Change wallet import/export to mirror each other, and to expect blobs

---

.github/workflows/ci.yml

[Sometimes ](https://github.com/iron-fish/ironfish/pull/3268) my PRs don't seem to trigger CI workflows. I am not entirely sure what the root cause is, but this seems like a good start
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
```
[ ] Yes
```

fix(ci): ** as glob to pick up branch names with / in them

---

ironfish-cli/src/commands/fees.ts
ironfish-cli/src/commands/service/estimate-fee-rates.ts
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish/src/rpc/routes/chain/estimateFeeRates.ts

Rename fee rate options
Always display three options
local
```
yarn start wallet:send --rawTransaction -t dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
$ yarn build && yarn start:js wallet:send --rawTransaction -t dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:send --rawTransaction -t dfc2679369551e64e3950e06a88e68466e813c63b100283520045925adbe59ca
? Select the asset you wish to send d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6
($IRON) (0.00000005)
Enter the amount (balance: 0.00000005): 0.00000001
? Select the fee you wish to use for this transaction (Use arrow keys)
❯ …
```

Rename fee rate options

---

ironfish/src/rpc/routes/wallet/exportAccount.ts

Removes id from `exportAccount` RPC.
Before
```
fish wallet:export  --json --datadir=~/.phase3v9                                                                              ─╯
$ yarn build && yarn start:js wallet:export --json '--datadir=~/.phase3v9'
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:export --json '--datadir=~/.phase3v9'
{
"id": "25beb087-9c0e-41a2-ae51-708a1fd69deb",
"name": "throwaway",
"spendingKey": "8b610cdb12f5b4d84034325b6bfbde84ca8e45b5ee826e7d2e734fe62e52cd5b",
"incomingViewKey": "9007719c56e84730db86f1674f4e1a65041d3e6ca08cba1cf7db5326cb0ca807",
"outgoingViewKey": "b1e6de94e6fbb13fe3a905e94b3c5df6f8f5f0ea7010b5fbcfbcd535e6da7788",
"publicAddress": …
```

fix: remove id account export

---

ironfish-cli/src/commands/wallet/notes.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/table.ts

uses the same column formatting for 'Asset', 'Asset Name', and 'Asset ID' columns as wallet:transactions
moves logic for constructing asset column(s) to utils
replaces 'x' for unspent notes with '' in Spent column
reorders columns so that amount appears right after asset name
```
[ ] Yes
```

updates wallet:notes table formatting

---

ironfish/src/fileStores/config.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/database.ts
ironfish/src/mining/poolDatabase/migrations/005-add-payout-period-table.ts
ironfish/src/mining/poolDatabase/migrations/index.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

This adds a "payout period" with a fixed duration, such that any blocks or shares found during that time will be tied to that period. This will allow the pool to calculate the exact amount to payout each share in a deterministic fashion. Materializing explicit rows instead of relying on timestamps allows the code to be a bit more explicit and easier to reason about.
```
[ ] Yes
```

feat(ironfish): Add explicit payout period to mining pool

---

ironfish/src/mining/pool.ts
ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/database.ts
ironfish/src/mining/poolDatabase/migrations/006-add-block-table.ts
ironfish/src/mining/poolDatabase/migrations/index.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

**Builds on #3268** 
This introduces a new table to the mining pool database, block. The pool will insert a row every time it successfully submits a block. The event loop will check any unconfirmed blocks, and update their status accordingly. For now, that status includes whether it's on the main chain, and whether it's confirmed. This gives us the ability to track how much reward was earned within a specific timeframe.
```
[ ] Yes
```

feat(ironfish): mining pool tracks status of its submitted blocks

---

ironfish/src/mining/pool.ts
ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/database.ts
ironfish/src/mining/poolDatabase/migrations/007-add-payout-transaction-table.ts
ironfish/src/mining/poolDatabase/migrations/index.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

**Builds on #3275**
This introduces a new table which allows the pool to insert a row whenever it makes a new transaction. The event loop will update the status of any unconfirmed and unexpired transactions. This allows the pool to know what transactions it has made, as well as giving it the ability to re-pay out transactions in the event of one expiring.
```
[ ] Yes
```

feat(ironfish): mining pool tracks status of transactions its created

---

ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/database.ts
ironfish/src/mining/poolDatabase/migrations/008-add-payout-share-table.ts
ironfish/src/mining/poolDatabase/migrations/index.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

**Builds on #3285** 
This is functionally very similar to the existing shares. The only differences are that it is associated to a payout period and a payout transaction. This way, we know which payout period it belongs to, and which transaction it belongs to. This also allows us to make sure that a share is paid out again in the event of a payout transaction expiring.
The old logic/table will be removed in a follow-up commit that removes all of the old stuff in one change, to minimize disruption to the existing pool and make it easier to transition to the new logic.
```
[ ] Yes
```

feat(ironfish): add new share concept to mining pool

---

ironfish/src/network/peerNetwork.ts

This call to `alreadyHaveTransaction` is unnecessary here.
1. If the transaction is in the mempool that means that it can't have been included in a recent block. So `this.recentlyAddedToChain.has(hash)` is automatically false
2. We've already checked if it's in the mempool so `this.node.memPool.exists(hash)` is automatically true
3. That leaves the `alreadyHaveTransaction` check to be `!(false || true && !peersToSendTo))` which simplifies to `peersToSendTo`
4. We already only send to peers who haven't yet received the transaction in `peersToSendTo` so checking `peersToSendTo` is redundant
Also changing a nested if statement to an early return
```
[ ] Yes
```

Simplify re-gossip logic for transactions

---

ironfish/src/primitives/rawTransaction.ts
ironfish/src/testUtilities/helpers/merkletree.ts
ironfish/src/typedefs/bufio.d.ts
ironfish/src/wallet/walletdb/decryptedNoteValue.ts
ironfish/src/workerPool/tasks/sleep.ts
ironfish/src/workerPool/tasks/submitTelemetry.ts

There are many places where we write convert UTF8 to ascii that could be
causing problems. The default encoding to bufio is 'binary', which is an
alias to 'latin-1' which is effectively ASCII. This will change our
types to force users to specify the encoding to avoid issues like this.
I also changed our encodings over to use UTF-8.
This also fixes minting supply being broken.
Run existing tests, the change is a TS that will cause compiler errors if someone does not specify this.
It's not a breaking change because existing ASCII will still be decoded as single byte characters which is part of the UTF8 spec.
```
[ ] Yes
```

Fix ASCII encoding errors

---

ironfish/src/rpc/routes/chain/followChain.ts

We use this RPC command when uploading blocks to the API. Upload mints and burns as well
```
[ ] Yes
```

feat(ironfish): Return `mints` and `burns` in follow chain response

---

ironfish/src/mining/pool.ts
ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/database.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

**Builds on #3316** 
This introduces the core logic needed to create payouts with the new additions to the codebase. Specifically, it now knows which shares have been paid out, how much reward was earned in a payout period, whether its blocks and transactions are confirmed and whether transactions need to be undone in the database if they expire.
It lacks some of the polish of the existing payout logic, which will be moved over and tweaked as needed as we begin to remove the old logic.
```
[x] Yes
```

feat(ironfish): new payout logic for mining pool

---

ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/migrator.ts
ironfish/src/mining/poolShares.test.ts

Doesn't depend on any of the open mining pool PRs
Normal output is unaffected:
Tests don't spam a billion lines:
For reference, this is what it looked like before, which was already broken in its own way:
```
[ ] Yes
```

feat(ironfish): Allow the pool migrations to be silenced during tests

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/utils/table.ts

encapsulates logic for creating an oclif table column with fixed width. creates a column with minWidth set to the width and truncates the value returned by 'get' to the specified width
uses fixedWidth column in wallet:assets command
```
[ ] Yes
```

defines reusable fixedWidth column

---

ironfish-rust-nodejs/src/lib.rs
ironfish-rust/src/errors.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/test.rs

Minor refactor to return mnemonic type rather than generic string
test pass
```
[ ] Yes
```

chore: refactor mnemonic return type

---

ironfish-cli/src/commands/miners/pools/start.ts
ironfish/src/fileStores/config.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/mining/poolDatabase/database.ts
ironfish/src/mining/poolDatabase/index.ts
ironfish/src/mining/poolDatabase/migrations/005-add-payout-period-table.ts
ironfish/src/mining/poolDatabase/migrations/006-add-block-table.ts
ironfish/src/mining/poolDatabase/migrations/007-add-payout-transaction-table.ts
ironfish/src/mining/poolDatabase/migrations/008-add-payout-share-table.ts
ironfish/src/mining/poolDatabase/migrations/009-remove-old-tables.ts
ironfish/src/mining/poolDatabase/migrations/index.ts
ironfish/src/mining/poolDatabase/migrator.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts
ironfish/src/mining/webhooks/webhookNotifier.ts

The mining pool was at risk of creating transactions larger than the block size limit. We used this opportunity to refactor the logic so that it could handle batching payouts. This had a downstream effect of letting us improve the overall reliability of the mining pool.
New config option:
- `poolPayoutPeriodDuration`
Removed config options: 
- `poolBalancePercentPayout`
- `poolAttemptPayoutInterval`
- `poolSuccessfulPayoutInterval`
The pool now operates on a stricter 'payout period' concept. Every x minutes (default: 120 or 2 hours), a new payout period is created. Any blocks found or shares submitted during this time are part of that payout period. Once a payout period ends, and all of its associated blocks are confirmed, the pool will begin paying out in batches of 250 unique public …

Mining pool refactors

---

ironfish/src/fileStores/config.ts

By default if you listen on 0.0.0.0 then the node net server won't listen on the ipv6 adapter. IF you listen on :: which is the ipv6 equivilent it will set the net server in multi adapter mode and listen on both ipv6 and ipv4. If you want ipv6 only there is an extra parameter.
Read more, https://github.com/nodejs/node/issues/9390
```
[ ] Yes
```

Make the default pool host ipv6 compatible

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish/src/rpc/routes/wallet/burnAsset.test.ts
ironfish/src/rpc/routes/wallet/burnAsset.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.ts

Implementing https://github.com/iron-fish/ironfish/issues/3191. Burning asset now shows asset name and id in transaction confirmation, in the same way that minting asset does.
Run `ironfish wallet:burn` and see that asset name shows in the transaction confirmation
```
[ ] Yes
```

Add asset name to wallet:burn confirmation

---

ironfish/src/storage/database/encoding.ts
ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/walletdb/walletdb.ts

the unspentNoteHashes datastore is an index on note hashes that supports efficiently looking up the values of notes that are confirmed in a given sequence range and have not been spent in another transaction.
this query pattern supports computing the 'available' balance for an account and asset by summing the values of all notes that are confirmed and unspent.
the datastore uses a five-part compound key:
- account prefix
- asset ID
- sequence
- value
- note hash
the stored value is always null
the datastore is updated according to these rules:
- when a pending transaction is created
- remove entries for any note that is spent in the transaction
- when a transaction is connected
- add entries for all output notes (if they have not been spent in a
pending transaction)
- remove entries for …

adds unspentNoteHashes store to walletDb

---

ironfish/src/migrations/data/020-backfill-null-asset-supplies.ts
ironfish/src/migrations/data/index.ts
ironfish/src/rpc/routes/wallet/getAssets.test.ts
ironfish/src/rpc/routes/wallet/getAssets.ts
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/walletdb/assetValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

We found in the v0.1.66 release that users were running into null supply assertions crashing the wallet. This happened if an asset an account owns had 0 supply. The most common way this occurred was if a user burned their entire supply from previous mints.
Our asset value encoding was treating 0 as a nil value which later triggered that exception. 
This code change:
* Updates the encoding to properly check against null
* Adds a migration which clears assets the account owns and re-syncs from mints and burns
* Clears out assets from the original backfill in case that was failing
Ran against corrupted database and now working
```
[ ] Yes
```

fix(ironfish): Change asset supply truthy checks to be against null

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/note.rs
ironfish-rust-nodejs/src/structs/note_encrypted.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish/src/primitives/__fixtures__/note.test.ts.fixture
ironfish/src/primitives/note.test.ts
ironfish/src/primitives/note.ts

This PR exposes the ability to get the hash from a decrypted note. It also exposes hash() in the JS side for both encrypted and decrypted notes but renaming merkle_hash() to hash().
```
[ ] Yes
```

Add note.hash()

---

ironfish-cli/src/commands/wallet/mint.ts

Fix https://github.com/iron-fish/ironfish/issues/3386. Show mint asset name in human readable form.
Run `wallet:mint` and check format of asset name.
```
[ ] Yes
```

Show mint asset name in human readable form

---

ironfish/src/network/messages/peerList.ts
ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerCandidates.ts
ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerConnectionManager.ts
ironfish/src/network/peers/peerManager.test.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/network/testUtilities/helpers.ts

Changes peerCandidateMap to a class called PeerCandidates, which wraps the map. This makes it easier to dedupe and merge peer candidate entries.
The underlying problem causing the 'Already have a WebSocket connection, ignoring the new one' issue is that when adding nodes whose identity we don't know (like the bootstrap node), we need to fill in a temporary identity to distinguish it. We use the address+port for this purpose. Once connected to the bootstrap node though, the peer's identity is replaced by the identity received in the Identify message. The peerCandidateMap wasn't updated, though, so it would still see the old temporary identity as a separate peer and attempt to connect to the bootstrap node again.
Added a couple tests to cover this case.
Is this a breaking change? If yes, …

Fix 'Already have a WebSocket connection' message

---

ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
ironfish/src/network/messageRegistry.ts
ironfish/src/network/messages/__fixtures__/getBlockHeaders.test.ts.fixture
ironfish/src/network/messages/getBlockHeaders.test.ts
ironfish/src/network/messages/getBlockHeaders.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/testUtilities/helpers.ts
ironfish/src/network/types.ts

This message will replace `GetBlockHashes` as the message used for syncing in a follow-up change. It also includes a `skip` and `reverse` flag, for more flexible future usage.
```
[ ] Yes
```

feat(ironfish): Introduce new `GetBlockHeaders` network message

---

ironfish-cli/src/commands/wallet/prune.ts

Wallet prune command to remove expired transactions.
This PR only calls wallet db compact().
Removing expired tx will be a separate PR
locally run `yarn start wallet:prune`
```
yarn start wallet:prune
$ yarn build && yarn start:js wallet:prune
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:prune
Opening node... Done.
Compacting wallet database... done
✨  Done in 1.15s.
```
```
[ ] Yes
```

wallet prune

---

ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
ironfish/src/network/messageRegistry.ts
ironfish/src/network/messages/getBlockHeaders.test.ts
ironfish/src/network/messages/getBlockHeaders.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts

This allows us to use either a sequence or hash for the start parameter of a GetBlockHeaders request
Unit tests
```
[ ] Yes
```

feat(ironfish): GetBlockHeaders can take sequence or hash for start

---

ironfish/src/network/version.ts
ironfish/src/syncer.ts

**Builds on #3418** 
This allows us to use the new GetBlockHeaders message without requiring
a minimum version bump, as syncing from a peer on an older version will
default to the previously expected behavior of using GetBlockHashes.
Local testing
```
[ ] Yes
```

feat(ironfish): use GetBlockHeaders if peer has the appropriate version

---

ironfish-cli/src/commands/faucet.ts
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/delete.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/post.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/commands/wallet/use.ts
ironfish/src/rpc/routes/faucet/getFunds.test.ts
ironfish/src/rpc/routes/faucet/getFunds.ts
ironfish/src/rpc/routes/wallet/burnAsset.test.ts
ironfish/src/rpc/routes/wallet/burnAsset.ts
ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts
ironfish/src/rpc/routes/wallet/createTransaction.test.ts
ironfish/src/rpc/routes/wallet/createTransaction.ts
ironfish/src/rpc/routes/wallet/exportAccount.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.ts
ironfish/src/rpc/routes/wallet/postTransaction.test.ts
ironfish/src/rpc/routes/wallet/postTransaction.ts
ironfish/src/rpc/routes/wallet/removeAccount.ts
ironfish/src/rpc/routes/wallet/useAccount.ts

This standardizes on the name "account" for passing in an account as the context for all wallet operations.
We also weren't using getAccount() everywhere.
```
[ ] Yes
```

Make account rpc parameter uniform and use getAccount()

---

ironfish/src/rpc/routes/wallet/createTransaction.test.ts

Promise all is used to wait for multiple promises to resolve, or for 1 to reject. If we have 1 promise we should just await that 1 promise.
```
[ ] Yes
```

Remove promise-all usage in createTransaction.test

---

ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/test.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/note.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs

Updates the `SaplingKey` struct to contain the `ViewKey` struct instead of the `authorizing_key` and `nullifier_deriving_key` components.
Lots of reference changes from `SaplingKey.authorizing_key` to `SaplingKey.view_key.authorizing_key`.
Part 1 here https://github.com/iron-fish/ironfish/pull/3423
Part 3 here https://github.com/iron-fish/ironfish/pull/3433
Part 4 here https://github.com/iron-fish/ironfish/pull/3436
tests pass
```
[ ] Yes
```

feat: SaplingKey.view_key update (PR 2)

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust/src/keys/test.rs

Updates the NAPI bindings in the `ironfish-rust-nodejs` package for usage in typescript
What was originally:
```
export interface Key {
spending_key: string
incoming_view_key: string
outgoing_view_key: string
public_address: string
}
```
will now be:
```
export interface Key {
spending_key: string
view_key: string
incoming_view_key: string
outgoing_view_key: string
public_address: string
}
```
We can leave `incoming_view_key` returned for convenience or we can clean up at end of project, I don't have a strong preference.
PR 3 here: https://github.com/iron-fish/ironfish/pull/3433
Tests pass
```
[ ] Yes
```

feat: ViewKey rust nodejs (PR 4)

---

ironfish-cli/src/commands/chain/power.ts

```bash
$ ironfish chain:power 5432 --history 10
```
> The network power for block 43814 was 83.93 GH averaged over 10 previous blocks.
https://github.com/iron-fish/ironfish/pull/3445
```
[ ] Yes
```

Change chain:power to follow the new CLI ux guide

---

ironfish-cli/STYLE_GUIDE.md

This is not definitive, it's just a start.
https://github.com/iron-fish/ironfish/blob/jason/cliux/ironfish-cli/STYLE_GUIDE.md
```
[ ] Yes
```

Add start of a CLI style guide

---

ironfish/src/network/peerNetwork.ts
ironfish/src/utils/__fixtures__/blockutil.test.ts.fixture
ironfish/src/utils/blockchain.ts
ironfish/src/utils/blockutil.test.ts

Move and rename this function out of `PeerNetwork` class. It is really a blockchain utility function, so moving it to `BlockchainUtils` makes sense.
Unit tests
```
[ ] Yes
```

refactor(ironfish): move `resolveSequenceOrHash` fn

---

ironfish/src/utils/blockchain.ts

`isBlockMine` was a wrapper around a test utility function. It doesn't seem like a great idea to expose test utility functions as "normal" code path functions. Given that, and that the function was unused, removing it seems like a decent option.
```
[ ] Yes
```

refactor: remove unused blockchain util fn

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/note.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish/src/primitives/note.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

We only need the `nullifier_deriving_key` for verifying the nullifier, not the `spend_key`.  These changes are a result of the identification of view only wallet incompatibility from this PR review comment:
https://github.com/iron-fish/ironfish/pull/3335#discussion_r1103230014
TODO:
add links to previous PR in series and rename
Tests pass
```
[ ] Yes
```

feat: use view key for nullifier

---

ironfish-cli/src/commands/config/unset.ts
ironfish/src/fileStores/keyStore.ts
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/config/index.ts
ironfish/src/rpc/routes/config/unsetConfig.test.ts
ironfish/src/rpc/routes/config/unsetConfig.ts
ironfish/src/rpc/routes/config/uploadConfig.ts

This new command will unset a config variable
```
$ ironfish config:set blockGraffiti foo
$ ironfish config:get blockGraffiti
"foo"
$ ironfish config:unset blockGraffiti
$ ironfish config:get blockGraffiti
""
```
```
[ ] Yes
```

Add config:unset command

---

ironfish/src/rpc/routes/chain/getTransactionStream.test.ts
ironfish/src/rpc/routes/config/getConfig.test.ts
ironfish/src/rpc/routes/faucet/getFunds.test.ts
ironfish/src/rpc/routes/node/getStatus.test.ts
ironfish/src/rpc/routes/node/stopNode.test.ts
ironfish/src/rpc/routes/wallet/create.test.slow.ts

We don't need to use this unless you want a raw untyped request. Most of these tests only want the typed request, and in fact typing these found some bugs in the tests.
these are changes to the tests
```
[ ] Yes
```

Remove use of routeTest.client.request

---

ironfish-cli/src/commands/config/get.ts

Now `ironfish config:get` does not output json by default
```bash
$ ironfish config:get blockGraffiti
JASON💪💎🚀
$ ironfish config:get blockGraffiti --json
"JASON💪💎🚀"
```
```
$ ironfish config:get miningForce
false
$ ironfish config:get miningForce --json
false
```
```
$ ironfish config:get bootstrapNodes
test.bn1.ironfish.network,foo.ironfish.network
$ ironfish config:get bootstrapNodes --json
[
"test.bn1.ironfish.network",
"foo.ironfish.network"
]
```
```
[ ] Yes
```

Made config:get return non json by default

---

ironfish-cli/src/commands/wallet/import.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/genesis/genesis.test.slow.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/migrations/data/022-add-view-key-account.ts
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/workerPool/job.test.slow.ts
ironfish/src/workerPool/tasks/createMinersFee.ts

Refactor NAPI nodejs representation of `Key` to use default variable name export (instead of camel case).
tests pass
```
[ ] Yes
```

chore: remove snake case key

---

ironfish-cli/package.json
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/testnet.ts
yarn.lock

- Added to burn / send as well as mint
- Colorized output to be yellow 
- Skip in case API is unreachable
- Allow user to disable eligibility check for offline signing to work
```
[ ] Yes
```

Change eligibiliy check

---

ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts

This `AccountImport` type doesn't belong in the codebase. We already have a serialized version of account as `AccountValue`, all our code is mostly compatible with this.
tests pass and CLI works:
```
fish wallet:import  --datadir=~/.irfrefactorImport
Paste the output of wallet:export: ironfishaccount0000010v38vetjwd5k7m3z8gcjcgnwv9kk2g36yfjx2enpw4k8gg3vyfehqetwv35kue6tv4ujyw3zv4snzcfjvcckxvmyx9jrqcfnxyunqdryxuun2e33x5mnwdtrv4nrwwf4vcunycm9vg6nydpexqcx2dfevdjkgdmpvvmx2df4xqcnjvez9s38v6t9wa9k27fz8g3rzdecxvcnqetzx9snjefjxvmnjcmp89nrwcfcvverjve5v4snxdfcv5urxe35v56rwcehvsmnvcnyve3xxdrrxpnrvcenxqurgwpsx5crvcnzvenrqv3svymnvvpkxs6rxvfkxd3kgepnxuuk2cty8pjk2vekv93kyvfe8q6xvdn9x5cx2veexsekvvfhv33rwenxx56xxcmpygkzy6twvdhk66twvatxjethfdjhjg36ygersctzxe3ngefjxdsnverxvdnxxe34xf3xvdmyxy6rvdtrx5cngdm9vsunz …
```

chore: move AccountImport to accountImport RPC and use AccountValue in account.ts

---

ironfish/src/migrations/data/016-sequence-to-tx.ts
ironfish/src/migrations/data/017-sequence-encoding.ts
ironfish/src/migrations/data/018-backfill-wallet-assets.ts
ironfish/src/migrations/data/019-backfill-wallet-assets-from-chain.ts
ironfish/src/migrations/data/020-backfill-null-asset-supplies.ts
ironfish/src/migrations/data/021-add-version-to-accounts/schemaOld.ts

we've recently made changes to the way that accounts are stored in the walletdb. it's possible that a user may have a database that needs to apply migrations that rely on the old AccountValue encoding before applying the migration to the new encoding.
this results in an encoding error when an older migration (pre-021) attempts to read from the accounts store, which has not yet been migrated.
adds a function, GetOldAccounts, to simplify reading accounts from the old accounts store in older migrations. uses this function for loading accounts in all migrations before Migration021.
Running migrations before changes:
Running migrations after changes:
```
[ ] Yes
```

fixes walletdb migrations that rely on old accounts

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts

When trying to regenerate fixtures, this test was failing because there was likely new validation added to wallet. @hughy paired with me to update the test so validation passes.
tests pass
```
[ ] Yes
```

fix: fixes 'expired transaciton' test failure on fixture regenerate

---

ironfish-cli/src/commands/wallet/post.ts
ironfish/src/rpc/routes/wallet/postTransaction.test.ts
ironfish/src/rpc/routes/wallet/postTransaction.ts
ironfish/src/wallet/wallet.ts

It's unclear why there are 2 post functions in the wallet SDK. This combines them and adds an argument for the previous functionality.
```
[ ] Yes
```

Change post() to be postTransaction() with args

---

ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.ts

when loading values from nullifierToNoteHash we convert the return value from undefined to null if the key is not found in the datastore. we do not do this for any other datastore in the walletDb.
returns undefined when key is not found in the datastore to be consistent with other stores in the walletDb.
```
[ ] Yes
```

returns undefined for missing nullifierToNoteHash

---

ironfish/src/migrations/data/023-unspent-notes.ts
ironfish/src/migrations/data/023-unspent-notes/schemaNew.ts
ironfish/src/migrations/data/023-unspent-notes/schemaOld.ts
ironfish/src/migrations/data/index.ts
ironfish/src/storage/database/encoding.ts
ironfish/src/wallet/walletdb/walletdb.ts

iterates over all notes for each account
if a note is on the chain and has not been spent the migration adds an entry to the unspentNoteHashes datastore
Depends on #3349 
```
[ ] Yes
```

adds backfill for unspentNoteHashes

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/walletdb/walletdb.ts

uses the unspentNoteHashes store to calculate the available balance
the available balance is the amount of an asset that an account currently has available to spend in a new transaction. the available balance is equal to the sum of the values of all notes for the asset that are confirmed on the chain and have not been spent in any confirmed, unconfirmed, or pending transaction
adds 'loadUnspentNoteValues' to walletDb to iterate over the values of unspent notes for a given asset
calculates the available balance by using 'loadUnspentNoteValues' to sum the values of all unspent notes with confirmed sequences
Depends on #3349 
```
[ ] Yes
```

calculates available balance from unspent notes

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/notes.ts
ironfish-cli/src/commands/wallet/transactions.ts

in the assets, notes, and transactions commands in the wallet we accept a --no-header flag as one of the oclif table flags, but we don't handle it correctly.
uses the value of the flag to set 'showHeader' to remove the table header if a user passes --no-header.
Closes #3416
```
[ ] Yes
```

fixes --no-header flag in cli

---

ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts

we calculate the size of raw transactions incorrectly when those transactions contain mints of assets with unicode characters in either the name or metadata: we use 'sizeVarString' with the default binary encoding, but use 'writeVarString' with utf8 encoding. this results in an out of bounds write because the binary encoding is smaller than the utf8 encoding.
fixes the out of bounds write by using the utf8 encoding when calculating size.
adds test of serialization and deserialization of a mint with unicode characters.
1. added unit test
2. minted asset 💪💎🚀
```
[ ] Yes
```

fixes serialization of mints with unicode

---

ironfish/src/memPool/__fixtures__/recentlyEvictedCache.test.ts.fixture
ironfish/src/memPool/memPool.ts
ironfish/src/memPool/priorityQueueTestHelpers.ts
ironfish/src/memPool/recentlyEvictedCache.test.ts
ironfish/src/memPool/recentlyEvictedCache.ts

Adds a new `RecentlyEvictedCache` to the mempool. 
A later PR will introduce a maximum capacity to the mempool. When the mempool is full, it is possible for transactions to be evicted to make room for more appealing ones. These evicted transactions will be added to this new cache to prevent immediate re-submission into the mempool. As transaction validation is expensive, it does not make sense to validate a transaction, _t_,  if it is known that _t_ will not make it into the mempool (as it was recently evicted). 
The `RecentlyEvictedCache` has a maximum capacity determined by the upstream maximum capacity of the mempool. Transactions can only be removed from this cache in the two following ways:
1. The cache is full and a new transaction is added. The transaction with the highest …

feat(ironfish): add a recently evicted cache to the mempool

---

ironfish-cli/src/commands/fees.ts
ironfish/src/fileStores/config.ts

Small cleanup to add some missing keys to our yup config validator
Manually tested:
```
[ ] Yes
```

fix: add missing config fields to yup config validator

---

ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts

When we expire transactions, we can now check the nullifier -> transaction hash mapping to ensure notes are properly marked as unspent. 
It is possible that we can mark a note as spent from expiration and a pending transaction still exists for the account to spend the same note without an associated nullifier -> transaction hash mapping. 
Unit tests
```
[ ] Yes
```

feat(ironfish): Check nullifier -> transaction hash befor marking notes as unspent

---

ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash/new/index.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash/old/accountValue.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash/old/headValue.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash/old/index.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash/old/transactionValue.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash/stores.ts
ironfish/src/migrations/data/index.ts
ironfish/src/wallet/walletdb/walletdb.ts

For all accounts, load the transactions and backfill nullifier -> transaction hash from the database. If an account has not scanned or has no head, skip the backfill. If a transaction has expired, skip the backfill.
Manually run migration
```
[ ] Yes
```

feat(ironfish): Backfill `nullifierToTransactionHash`

---

ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/currency.ts
ironfish-cli/src/utils/fees.ts
ironfish/src/assert.ts

we use Promise.all to parallelize createTransaction requests for all three fee rates (slow, average, fast) when neither a fee nor fee rate are specified in the send command.
however, if the sender account does not have enough funds to pay the fast fee rate, then the whole transaction fails. the user cannot select the slow fee rate even if their account has enough funds to pay that fee.
handles insufficient balance errors when creating transactions for different fee rates. inserts an 'Insufficient funds' option into the inquirer prompt and throws the error if that option is selected.
removes parallelization of the three fee rate requests to simplify error handling. Promise.allSettled is an alternative that would preserve parallelization, but makes it more difficult to distinguish the type …

Handles insufficient funds for one or more fee rates

---

ironfish/src/fileStores/config.ts
ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
ironfish/src/memPool/memPool.test.ts
ironfish/src/memPool/memPool.ts
ironfish/src/memPool/recentlyEvictedCache.ts
ironfish/src/node.ts

Currently, there is no max size in the mempool. This means the mempool can grow indefinitely and is open to flooding attacks. A capacity will be implemented so that when reached, lowest-priority transactions will be evicted. The priority of a transaction is determined by its feeRate. We will also store a cache of recently evicted transactions as optimization for not re-processing transactions that have recently been evicted. For a recently-evicted transaction to be re-inserted into the mempool, it must increase its feeRate beyond the current mempool’s minimum transaction feeRate. 
```
[ ] Yes
```

Add max size to mempool

---

ironfish/src/network/peers/peerManager.ts
ironfish/src/network/testUtilities/helpers.ts
ironfish/src/network/testUtilities/mockLocalPeer.ts
ironfish/src/network/types.ts
ironfish/src/network/webSocketClient.ts
ironfish/src/network/webSocketServer.ts
ironfish/src/sdk.ts

The issue right now is that since we have the IsomorphicWebSocket, we lack the ability to set the options parameter for the ws WebSocket. The primary issue is that any connections created this way will not receive the maxPayload option, thus allowing anyone to send a message of any size (up to the default limit set in the library which is I think 100mb). By creating this class which extends ws WebSocket and sets default options in the constructor, we can create ws WebSockets with the maxPayload option set.
Unit tests and manual testing by running a node on testnest
```
[ ] Yes
```

feat: introduce WebSocketClient class to allow options parameter

---

ironfish-cli/src/commands/wallet/mint.ts

updates the mint command to use new utils. uses 'selectFee' and 'promptCurrency'.
simplifies some of the logical flow and messages to be more consistent with the send command where applicable (e.g., confirming before post)
adds 'offline' and 'watch' flags to match send
matches changes to the send command in #3525
ran 'mint' with a few different options, e.g.,
```
[ ] Yes
```

changes mint to use new utils

---

ironfish-cli/src/commands/wallet/import.ts

`wallet:import` doesn't just accept the output of `wallet:export`, it'll also accept a raw spending key. Update the prompt to reflect this.
Cosmetic prompt change, just leaning on unit tests.
```
[ ] Yes
[X] No
```

Update CLI import prompt

---

ironfish-cli/src/commands/wallet/burn.ts

updates the burn command to use new utils: promptCurrency, selectFee, watchTransaction
makes the burn command consistent with changes to send and mint
adds 'offline' and 'watch' flags to burn
ran a couple of `burn`s
```
[ ] Yes
```

changes burn to use new utils

---

ironfish/src/mining/manager.test.slow.ts
ironfish/src/rpc/routes/mining/blockTemplateStream.test.slow.ts
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/wallet.test.slow.ts

We don't need this except for 1-2 places so we can just set the account as default.
```
[ ] Yes
```

Revove default flag on AccountFixture

---

ironfish-cli/src/commands/wallet/send.ts

supports offline transactions by allowing send to run without the client connecting to a node
sent a transaction without a running node
```
[ ] Yes
```

allows send to run without node running

---

ironfish-cli/src/commands/chain/download.ts

Use r2 public domain when download snapshots data
```
yajun@Yajuns-MBP ironfish-cli % yarn start chain:download
$ yarn build && yarn start:js chain:download
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-d
Download 5.64 GB snapshot to update from block 41703 to 54404?
At least 11.29 GB of free disk space is required to download and unzip the snapshot file.
Are you sure? (Y)es / (N)o: y
Cleaning up snapshot file at /Users/yajun/.ironfish/temp/ironfish_snapshot_1677186168233.tar.e
✨  Done in 212.66s.
```
```
[ ] Yes
```

Download snapshots data from r2

---

ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
ironfish/src/memPool/memPool.test.ts
ironfish/src/memPool/memPool.ts

We keep a PriorityQueue of transactions to expire when a new block is connected. They are ordered by lowest expiration sequence. However we also use an expiration sequence of `0` to indicate a transaction that never expires. These 0 expiration transactions were going to the top of the queue and when checking to see if the next transaction should be expired it would look at a 0 expiration and say that the transaction does not need to be expired. This was blocking other transactions that actually did need to be expired.
```
[ ] Yes
```

Fix mempool transaction expiry bug

---

ironfish-cli/src/commands/service/faucet.ts
ironfish-cli/src/utils/currency.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts
ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts

checks available balance to see if an account has enough funds to send a transaction instead of confirmed balance.
available balance is the sum of all unspent note values and more accurately accounts for whether the account can send the transaction.
changes confirmed balance references in the following places:
- poolShares
- sendTransaction RPC
- promptCurrency
- faucet
```
[ ] Yes
```

fixes remaining confirmed balance checks

---

ironfish/src/network/messageRegistry.test.ts
ironfish/src/network/messages/identify.test.ts
ironfish/src/network/messages/identify.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/connections/webRtcConnection.test.ts
ironfish/src/network/peers/connections/webSocketConnection.test.ts
ironfish/src/network/peers/localPeer.ts
ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerFeatures.ts
ironfish/src/network/peers/peerManager.test.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/network/testUtilities/helpers.ts
ironfish/src/network/testUtilities/mockLocalPeer.ts
ironfish/src/network/version.ts
ironfish/src/syncer.ts

Adds a features field to the Identify message. For now, it allows for broadcasting to other peers whether your node supports syncing.
```
[ ] Yes
```

Add Features field to Identify message

---

ironfish-cli/src/commands/wallet/import.ts

Many editors put new lines at the end of file, and any file with a newline that contains bech32 won't be importable.
```
[ ] Yes
```

Trim file contents when importing an account

---

ironfish-cli/src/commands/wallet/import.ts

This is breaking import of bech32 accounts without a view key. Those keys will fail YUP validation during import.
```
[ ] Yes
```

Fix bech32 import for accounts without view key

---

ironfish-cli/src/commands/wallet/import.ts

This is breaking import of json accounts without a view key. Those keys will fail YUP validation during import.
```
[ ] Yes
```

Fix JSON import for accounts without a view key

---

ironfish-cli/src/utils/currency.ts
ironfish/src/utils/currency.ts

Users were typing iron in here, but this prompt accepted ore. Changes this to accept and decode iron now.
```
[ ] Yes
```

Change promptCurrency to accept iron not ore

---

ironfish/src/network/blockFetcher.test.ts
ironfish/src/network/messages/networkMessage.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/network/testUtilities/helpers.ts
ironfish/src/network/transactionFetcher.test.ts

This abstraction isn't really useful anymore since we pass the peer around with the message, so we can remove it and just emit the message directly.
```
[ ] Yes
```

Remove IncomingPeerMessage

---

ironfish-cli/src/commands/peers/index.ts
ironfish/src/rpc/routes/peers/getPeer.ts
ironfish/src/rpc/routes/peers/getPeers.ts

#3551 added features to the Identify message. This PR adds a `--features` flag to the `peers` command that displays what features a node has advertised in its Identify message.
Ran the command on a node with the syncing feature enabled and disabled to check that it appears (and doesn't) in the FEATURES column.
```
[ ] Yes
```

Display features in the peers list

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/currency.ts
ironfish-cli/src/utils/fees.ts
ironfish/src/utils/currency.ts

This will help parse the untyped errors from bignumber and add a new function to try and display them more cleanly.
It also now logs the reason for prompt errors. 
```bash
$ fishy wallet:send
Enter the amount (balance 0.00000000): 0.000000000005
Error: fractional component exceeds 8 decimals
Enter the amount (balance 0.00000000): fisdfjgdsdsfds
Error: invalid decimal value
Enter the amount (balance 0.00000000): -4
Error: Minimum is 0.00000001
Enter the amount (balance 0.00000000): 4
Enter the public address of the recipient:
```
```
[ ] Yes
```

Show nicer parsing errors in promptCurrency

---

ironfish-cli/package.json
ironfish/package.json
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peers/connections/webSocketConnection.ts
ironfish/src/network/webSocketServer.ts
yarn.lock

- Upgrade `ws` to the latest version
- Remove the dependency from CLI since it isn't being used
- Only big change is that "WebSocket was closed before the connection was established" error no longer raises an exception, but fires an onError event in the _next tick_ (https://github.com/websockets/ws/commit/d086f4bcbbe235f12f6fa2ddba5a8ce1342dac58) which means we can't easily remove the onerror handler. If we still want to remove the handler, we will likely have to do it in a `process.nextTick` call.
If you wish to confirm that the removal of the try-catch works, adding a nice obvious log to the onerror handler when the state is disconnected. Within about 2-5 minutes, you'll see the "WebSocket was closed before the connection was established" error being logged and no exception getting …

chore: upgrade ws websocket library

---

ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/transactionFetcher.ts

We are doing some checks that are redundant in the transaction fetcher. In the middle of the fetching cycle we are making sure the transactions didn't get added to a block or added to the mempool. But if they did the transaction fetcher would have already been notified and we would've stopped downloading the transaction. So doing these checks doesn't add any benefit
```
[ ] Yes
```

Remove unnecessary checks for transactions in transaction fetcher

---

ironfish/src/metrics/meter.ts
ironfish/src/metrics/metricsMonitor.ts
ironfish/src/telemetry/telemetry.ts

Adds support to configure the max # of samples tracked in a `meter.rollling_avg`
Using `rate5m` is causing issues with the telemetry graphs for `create_new_block_template` as the inclusion of 0 values when new block templates are not being created are skewing the results. Switching to `avg` so sample are only added when new block templates are being created. Max # of values tracking in the rolling avg is set to `100`
existing tests
```
[ ] Yes
[X] No
```

feat: adds support to configure the max rolling avg samples for meters

---

ironfish/src/fileStores/config.ts
ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/version.ts

This allows the message to rely on the max message size, or disk lookup limit to decide the max for a response, instead of an arbitrary block limit.
Also setting the default blocksPerMessage back up to 25, since this was lowered during phase 2.
Unit test. Tested with local nodes using a blocksPerMessage of 100.
```
[ ] Yes
```

feat: remove hard block limit for GetBlocksResponse

---

ironfish/src/memPool/memPool.test.ts
ironfish/src/memPool/memPool.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/transactionFetcher.test.ts

After adding max size to the mempool and adding a recently evicted cache we need to change transaction gossip logic to account for not all transactions being in the mempool.
```
[ ] Yes
```

Add PeerNetwork checks for updated mempool

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml

Noticed a lot of issues are due to users forget to restart ironfish node after upgrading. Adding this to the bug template.
```
[ ] Yes
```

Improve bug report template

---

ironfish/package.json
yarn.lock

This includes some performance improvements like using JsBuffer instead of Buffer, which we have done in our own NAPI code to minimize memory leaks. This version also includes a fix to make Iron Fish run on systems with non-standard ldd path, like NixOS.
Manually tested with some nodes, including mining and syncing
```
[ ] Yes
```

chore: bump @napi-rs/blake-hash

---

ironfish/src/migrations/data/021-add-version-to-accounts/schemaOld.ts
ironfish/src/migrations/data/024-unspent-notes.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/wallet/walletdb/accountValue.ts

the createdAt field or 'account birthday' will be used during account scanning to skip blocks that were created before the account was created.
adds a nullable createdAt date field. the field may be null for imported accounts. if an account is imported we cannot determine when the account was created without scanning the chain for the earliest transactions that involved that account.
theses changes do not yet support importing an account with a creation date. followup changes should add createdAt to account exports and make the field optional for imports.
```
[ ] Yes
```

adds createdAt field to Account

---

ironfish-cli/bin/run
ironfish-cli/package.json
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/signal_catcher.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust/src/lib.rs
ironfish-rust/src/signal_catcher.rs
yarn.lock

segfault-handler is a useful library, but requires a lot of extra
dependencies for our users since it compiles binaries on installation.
We can replace this with some napi rust functions that give us most of
what we need. This can later be extended to cover all the cases we want
it to, or split out into its own package.
- https://user-images.githubusercontent.com/97762857/222219291-74da43c8-8f09-4130-bdd4-3615ae863e34.png
Manually tested:
- Windows: only needed to install nodejs, yarn, rust. Built and started a node
- NixOS: Ran in a pure shell with only nodejs, yarn, rust. Built and started a node
- M1 Mac: Started and ran a node on testnet for several hours
```
[ ] …
```

feat: replace segfault-handler

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/asset.ts
ironfish/src/rpc/routes/wallet/getBalances.test.ts
ironfish/src/rpc/routes/wallet/getBalances.ts

Fix https://github.com/iron-fish/ironfish/issues/3477. `wallet:mint` should filter out non-owner assets. Adding `ownerOnly` flag to GetBalancesRequest rpc.
Run `ironfish wallet:mint` and see that non-owner assets no longer appear rom select screen. Run `ironfish wallet:send/burn` and confirm it still shows all assets.
```
[ ] Yes
```

Filter out non-owner assets from mint screen

---

ironfish-cli/src/utils/fees.ts

```
yajun@Yajuns-MBP ironfish-cli % yarn start wallet:send -t e4f6cab7e8774f74310fbfb4a345fac8fec289531914
$ yarn build && yarn start:js wallet:send -t e4f6cab7e8774f74310fbfb4a345fac8fec28953191bcc908265b74e4
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http4
? Select the asset you wish to send d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6
($IRON) (0.00000012)
Enter the amount (balance 0.00000012): 0.00000012
? Select the fee you wish to use for this transaction (Use arrow keys)
- Slow  (Not enough $IRON)
- Average  (Not enough $IRON)
- Fast  (Not enough $IRON)
❯ Enter a custom fee
``` …

Remove promise all

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.ts

import accounts fails following the addition of account birthdays with 'value.createdAt.getTime is not a function' because we do not parse any 'createdAt' into a date.
adds 'createdAt' to the required RPC fields in importAccount and ensures that the field is included in requests to importAccount.
manually tested various export/import conditions with and without the createdAt field:
- bech32
- json
- spendingKey
- mnemonic
- viewonly
```
[ ] Yes
```

fixes account import with account birthdays

---

ironfish-cli/src/commands/mempool/status.ts
ironfish/src/memPool/memPool.ts
ironfish/src/metrics/metricsMonitor.ts
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/mempool/getStatus.ts
ironfish/src/rpc/routes/mempool/index.ts
ironfish/src/rpc/routes/node/getStatus.ts
ironfish/src/telemetry/telemetry.ts

Adding a status command for the mempool to monitor the recently evicted cache. Also fixes a telemetry bug by sending number instead of a float
```
[ ] Yes
```

Add mempool status command

---

ironfish/package.json

`yarn add bech32`
after installing @ironfish/sdk, bech32 module cannot be found (e.g., https://discord.com/channels/771503434028941353/831945060777852998/1082211129796874311)
```
[ ] Yes
```

adds bech32 to dependencies for @ironfish/sdk

---

ironfish-cli/src/commands/wallet/delete.ts
ironfish/src/rpc/routes/wallet/removeAccount.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.ts

As it stands currently, `accounts:delete` only marks an account for deletion. This account is later deleted in the event loop. 
This feature proposes to add an option `--wait`. This will immediately force the cleanup code to be called. 
```
yarn start wallet:use killme
The default account is now: killme
```
```
yarn start wallet:delete --wait killme
Deleting account 'killme'... done
Account 'killme' successfully deleted.
```
```
yarn start wallet:accounts
default
```
```
[ ] Yes
[X] No
```

Feature: accounts:delete --wait

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts

if the length of the chain is shorter than the confirmation range we calculate a negative number for the maximum confirmed sequence. this results in an error when attempting to construct a key range with a negative value since the db encoding requires a non-negative integer value.
however, the genesis block is always confirmed, so the maximum confirmed sequence can never be less than 1.
fixes calculation of available balance by setting maxConfirmedSequence to be at least 1.
adds unit test for this case
Steps to reproduce:
```
rm -rf ~/.ironfishdev
yarn start start --datadir ~/.ironfishdev --networkId 2
yarn start wallet:balances --datadir ~/.ironfishdev
> The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -1
```
Is this a breaking change? If yes, add notes …

fixes balance calculation when confirmations >= chain length

---

ironfish-cli/src/commands/ceremony.ts

Giving some more information for users who try to run the `ironfish ceremony` command by telling them the ceremony is complete. We may still need this command in case of future setups / network upgrades. So for now, just exit the command with some information
```
[ ] Yes
```

Close trusted setup command

---

ironfish-cli/src/utils/currency.ts

when getting the balance to use in the prompt in 'promptCurrency' we do not use the name of the account passed to the function.
this results in getting the balance for the default account, which may not be the right one.
we get the balance for the right account in the asset selector, so you can see the issue clearly when using the asset selector for a non-default account and using the amount prompt afterwards.
Before:
After:
```
[ ] Yes
```

gets balance for correct account in promptCurrency

---

ironfish/src/network/types.ts

There's a gap in NetworkMessageType numbers after removing GetBlockHashes-related messages. This removes the gap, and also organizes the messages into subprotocols with space in between for adding additional messages in the future.
```
[ ] Yes
```

Renumber network messages

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/routes/wallet/importAccount.ts

If you import your default account (which has the name default) into a new wallet / data directory (and that database already has a default account), you will encounter an error that shows a duplicate name error. This is not a great UX, and it'd be nice to offer the user a chance to rename the account during the import.
* In the RPC request, throw a validation error if the account name already exists
* In the CLI check for a validation error and error code. If the code is account exists, prompt for a different name.
* If the same name is provided, error out
Existing behavior
https://user-images.githubusercontent.com/5459049/223557261-07949a5d-1ce6-4d21-8a38-8125cb188390.mp4
New behavior for same name
https://user-images.githubusercontent.com/5459049/223557529-aa1167d9-7966-46ae-b712-5d5f19 …

feat(cli,ironfish): Offer name change on duplicate name during import

---

ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust-nodejs/tsconfig.json
ironfish/src/consensus/verifier.ts
ironfish/src/primitives/target.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/syncer.test.ts
ironfish/src/testUtilities/helpers/blockchain.ts
ironfish/src/utils/bigint.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

There's no reason to wrap bigints in the bigint type. You can just use literals. This only replaces some places.
```
[ ] Yes
```

Replace bigint casting with bigint literal

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts

if the length of the chain is shorter than or equal to the confirmation range then we calculate a non-positive number for the maximum confirmed sequence. this results in an error when attempting to construct a key range for loading unspent notes from the unspentNoteHashes index.
the genesis block is always confirmed, so the maximum confirmed sequence can never be less than 1.
fixes getUnspentNotes by setting maxConfirmedSequence to be at least 1.
- added unit test
- steps to reproduce error:
```
> yarn start start -d ~/.ironfish-1
> yarn start wallet:import -d ~/.ironfish-1
> yarn start wallet:rescan --reset -d ~/.ironfish-1
> yarn start wallet:send --rawTransaction --offline --datadir=~/.ironfish-1 -t 0e0e42628ae521b5971b6a6c0384e41a623e6332249f86ef080184440d5e0840 -a 1 -o 0.00000001
``` …

fixes getUnspentNotes when confirmations >= chain length

---

ironfish/src/wallet/wallet.ts

The is confirmed check is done in `getUnspentNotes`
This is redundant check.
local cli
Before
```
yarn start wallet:send --rawTransaction --offline --datadir=~/.ironfish-1 -t 0e0e42628ae521b5971b6a6c0384e41a623e6332249f86ef080184440d5e0840 -a 1 -o 0.00000001 -v
$ yarn build && yarn start:js wallet:send --rawTransaction --offline '--datadir=~/.ironfish-1' -t 0e0e42628ae521b5971b6a6c0384e41a623e6332249f86ef080184440d5e0840 -a 1 -o 0.00000001 -v
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:send --rawTransaction --offline '--datadir=~/.ironfish-1' -t 0e0e42628ae521b5971b6a6c0384e41a623e6332249f86ef080184440d5e0840 -a 1 -o 0.00000001 -v
Connecting to …
```

Remove is confirmed check

---

ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.ts

all transactions on the genesis block are confirmed.
'wallet:balance --all' shows a 'confirmed' balance of 0 for the genesis account when the chain contains only the genesis block.
fixes calculation of confirmed balance by ensuring that the range of unconfirmed sequences starts at at least 2
'wallet:transactions' shows a single 'unconfirmed' transaction for the genesis account when the chain contains only the genesis block.
fixes display of transaction status by checking if transaction has sequence equal to genesis block sequence
Before:
After:
```
[ ] Yes
``` …

fixes genesis block transaction status

---

ironfish/src/rpc/routes/wallet/sendTransaction.ts

I'm reasonably sure the custom confirmation range should be passed in here, since we pass it in to node.wallet.send.
I could use a review from someone familiar with the wallet code to double-check though.
```
[ ] Yes
```
```
[ ] Yes
```

Use confirmations when checking balance in sendTransaction

---

ironfish/src/wallet/wallet.ts

scan state is updated with 'scan.signal'. we currently call 'scan.signal' within the logic of 'connectBlock' after scanning a transaction for an account. the result of this is that we only update the scan state for a sequence if some account in the wallet has a transaction at that sequence. the impact of this is that the output of `wallet:rescan' does not update as the scan progresses through the chain.
updates the scan state within 'scanTransactions' after each call to 'connectBlock' so that the scan state reflects that the block has been connected for all accounts.
before:
after:
related documentation pull request …

fixes scanTransactions to update ScanState after every block

---

ironfish-cli/src/commands/stop.ts
ironfish/src/rpc/routes/node/stopNode.ts

the 'stopNode' RPC shuts down the node before returning a response, so the cli client receives an error from the lost connection. IronfishCommand handles RPC connection errors and outputs 'Cannot connect to your node, start your node first.'. this is confusing both because we were able to connect to the node and because we successfully stopped it.
the stop command also silences RPC connection errors, so nothing is output if the node is already stopped when stop is run.
- returns a response from stopNode before shutting down the node
- removes error handling from 'client.connect' in stop command since the IronfishCommand abstract class handles these errors
- adds output to 'stop' command indicating that it asks the node to shut down
- start a node
- use 'ironfish stop' to …

improves output of stop command

---

ironfish-cli/src/commands/reset.ts

we likely do NOT want to delete users' accounts and keys after mainnet launch.
removes deletion of wallet database from 'reset' command. when the user starts a node on a new network after running reset, the wallet will automatically reset because the account heads will not be on the same chain as the network.
1. verify that node databases are on the wrong network
2. run `reset`
3. verify that accounts are still there
4. verify that wallet is reset once node starts successfully
```
[ ] Yes
``` …

avoids deleting wallet in reset command

---

ironfish-cli/src/commands/reset.ts

Reset should not change the `internal.json` file before the user has confirmed whether they wish to reset. Otherwise, when we switch the default network ID at mainnet, someone running `reset` who responds "No" will have their network ID out of sync with their database.
```
[ ] Yes
```
```
[ ] Yes
```

Fix reset changing internal.json before confirming

---

ironfish-cli/src/commands/mainnet.ts

Since we're resetting the node to first run, we should clear the enableTelemetry config to give users another chance to opt in to telemetry. We may as well also clear telemetryNodeId since we're changing networks too.
```
[ ] Yes
```
```
[ ] Yes
```

Reset enableTelemetry and telemetryNodeId

---

ironfish-cli/bin/run

This was an error that came up in slack: https://iron-fish.slack.com/archives/C02PF56HESK/p1678727391843899 I suspect some people are installing 32-bit versions by mistake.
If they do actually have 32-bit Windows computers, those would be at least 10 years old, which likely will end up struggling to run Iron Fish anyway (particularly since we recommend >4GB RAM)
```
[x] Yes
```
I updated the onboarding docs to specifically call out 64-bit installs: https://ironfish.network/docs/onboarding/installation-iron-fish …

Add error message when running from a windows 32-bit install

---

ironfish-cli/src/commands/ceremony.ts
ironfish-cli/src/commands/service/ceremony.ts
ironfish-cli/src/trusted-setup/server.ts
ironfish-cli/src/utils/s3.ts

For cost saving we are moving future trusted setup ceremonies to use Cloudflare R2 instead of S3
Locally tested a few contributions
```
[ ] Yes
```
```
[ ] Yes
```

Move ceremony command to R2

---

ironfish/src/rpc/clients/client.ts

Adds a client RPC call for `chain/getTransaction`. There are docs for the RPC function on [the website](https://ironfish.network/docs/onboarding/rpc/chain#chaingettransaction) but the route is not actually exposed on the client. 
existing tests
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```

fix: add client route for `chain/getTransaction`

---

ironfish/src/rpc/adapters/httpAdapter.ts

This PR fixes a bug where the `'Content-Type', 'application/json'` header was not set correctly before streaming a response.
It also slightly modifies streaming behavior. Some endpoints were streaming responses but we did not include a delimiter in the response. A delimiter was implicitly added because of the ` Transfer-Encoding: chunked` header but that delimiter doesn't show up in the final response of many HTTP clients because they just concatenate all the chunks together into one final response once the last chunk is received. This PR also adds a delimiter `\f` to the response so it can be easily separated into the individually streamed chunks.
If only one chunk is streamed by the response the delimiter is omitted.
Does this change require any updates to the Iron Fish Docs (ex. [the …

Add better support for streaming endpoints in HTTP

---

ironfish/src/rpc/routes/wallet/create.test.slow.ts
ironfish/src/rpc/routes/wallet/create.ts

if a node is online and syncing at the time of account creation it's possible to for an account head to be set to a block that is behind the wallet's chainProcessor.
if the account's head is behind the chain processor then the wallet will not scan any transactions for the account until the node is restarted.
runs scanTransactions after creating an account in the 'create' RPC so that a newly created account will be synced with the chainProcessor if it is behind. this matches the logic in the 'importAccount' RPC.
- start a new node so that the node is syncing
- create a new account
- use 'wallet:status' to see the the new account's head is moving forward with the default account …

starts scanTransactions after account creation

---

ironfish/src/rpc/adapters/httpAdapter.ts

Fixing a bug where the request close callback happens immediately. `req` object represents data coming from the client so once the client has streamed it's request 'close' event will be emitted. We want to wait until the client disconnects or the request is completed. This would be on the `res.on('close')` event. The response stream is separate from the request stream.
Tested locally
```
[ ] Yes
```
```
[ ] Yes
```

Fix request closing early

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

the chainProcessor tracks the head of the chain using both the hash and sequence of a block. when the wallet loads we currently only set the has of the chainProcessor equal to the latest headd hash from among the accounts in the wallet.
one consequence of not setting the sequence at load time is that if a user creates an account while the node is offline, the chainProcessor is not fully initialized and the newly created account has its head set to null instead of set equal to the latest head in the wallet. the new account then needs to scan the whole chain  to sync, even though it was just created and won't have any transactions earlier in the chain.
- defines getLatestHead to load the latest head (hash and sequence) from among all accounts
- sets both the hash and sequence of the …

sets chainProcessor sequence on wallet load

---

ironfish-cli/src/commands/ceremony/contributions.ts
ironfish-cli/src/commands/ceremony/index.ts
ironfish-cli/src/commands/ceremony/service.ts
ironfish-cli/src/utils/s3.ts

Adding a command to print out finalized contributions with metadata. This also moves all ceremony related commands to one folder
local testing
```
[ ] Yes
```
```
[ ] Yes
```

Add get contributions command for admin users

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

when importing an account with a non-null createdAt block we need to ensure that that block is on the same chain as the other accounts in the wallet. if it is on a different chain, on a fork, or ahead of the wallet's chain then we cannot correctly scan any transactions for that account.
- on import checks whether createdAt refers to a block in the node's chain and sets createdAt to null in the new account if not
- added unit tests
- create account on one node, export it
- import it into a second node running a different chain
- export it from the second node with --json to ensure that createdAt is null
related …

sets imported createdAt to null if not in chain

---

ironfish-cli/src/commands/wallet/prune.ts

> `wallet:prune` is a command to reduce the side of the wallet database by removing old data from the wallet and compacting the wallet database. We currently remove expired transactions and compact the database, but we don't clean up deleted accounts, so we should call forceCleanupDeletedAccounts as well.
Ran `wallet:prune` without incident.
```
[ ] Yes
[X] No
```
```
[ ] Yes
[X] No
```

Call forceCleanupDeletedAccounts at end of wallet:prune

---

ironfish/src/rpc/routes/wallet/burnAsset.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/utils/yup.test.ts
ironfish/src/utils/yup.ts

when using our custom 'currency' yup schema with a minimum value we do not catch errors from 'CurrencyUtils.decode'. this results in a non-yup error during validation if the value cannot be decoded.
an error other than 'yup.ValidationError' in an RPC endpoint crashes the node.
see #3662
- updates unit test. updated unit test fails before applying changes
- apply the attached diff to pass an invalid feeRate to the 'createTransaction' RPC
- use the 'send' command, pass the invalid feeRate, and crash the node
[test.diff.txt](https://github.com/iron-fish/ironfish/files/11056890/test.diff.txt)
related documentation pull …

fixes yup currency validation with min

---

.github/workflows/deploy-node-aws.yml
.github/workflows/deploy-node-github-beta.yml
.github/workflows/deploy-node-github.yml
ironfish-cli/scripts/deploy-docker.sh

When we deploy any docker images either from master or from another branch we only tag with `latest`. This can run into potential issues with production deploys if we don't always deploy from the master branch. Tagging docker images with their Github hash+branch / tag name will make our production deployments more stable
Testing by running Github action
```
[ ] Yes
```
```
[ ] Yes
```

Tag docker deploys with Github info

---

.github/workflows/deploy-node-aws.yml
.github/workflows/deploy-node-github-beta.yml
.github/workflows/deploy-node-github.yml

`GITHUB_REF` is not exactly the branch name so extracting it here
```
[ ] Yes
```
```
[ ] Yes
```

Fix GitHub branch ref

---

ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs

Add a `partial_verify` when building spends and output descriptions.
N/A
```
[ ] Yes
```
```
[ ] Yes
```

feat(rust): Add `partial_verify` when building spends and outputs

---

ironfish-cli/src/commands/reset.ts

Currently, there is no way to modify your network ID unless you manually edit the internal.json file. Combined with the usage of reset changing slightly to work more like a soft reset to allow changing between networks or just reset chain data, it makes sense to only optionally re-write the network ID if passed via flag. Otherwise, leave it unmodified
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): reset CLI command takes networkId flag and only modifies if given

---

ironfish/src/fileStores/config.ts

we've migrated the faucet to 'testnet.api.ironfish.network'. since the faucet will only ever work on the testnet, and never on mainnet, the default config should point to the testnet domain.
```
[ ] Yes
```
```
[ ] Yes
```

set default getFundsApi to testnet domain

---

ironfish/src/wallet/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

when adding a transaction to the wallet we use 'hasSpend' to iterate over all spends in the transaction to see whether the account spent any notes in the transaction before using 'addPendingTransaction' or 'connectTransaction'.
however, both of those methods _also_ iterate over all spends in the transaction. this can result in unnecessary, duplicative iteration over spends.
there is another drawback to the way we currently use 'hasSpend': the account 'addPendingTransaction' and 'connectTransaction' methods depend on the caller not to call them with any account and transaction where the account was not involved in the transaction. this is a bug waiting to happen.
- removes 'hasSpend' method
- does not check 'hasSpend' at wallet level before adding transaction to account
- updates account …

removes account hasSpend method

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

when using block-based account birthdays we need to ensure that the account birthday always refers to a block in the main chain.
on a block disconnect checks whether the account's createdAt field refers to the disconnected block. if it does, updates the account's createdAt field to the previous block. this ensures that createdAt refers to a block in the main chain at the end of a re-org.
- defines updateAccount to update the account stored in the walletDb and in the wallet's in-memory cache
- adds conditional update at the end of disconnectBlock
```
[ ] Yes
``` …

updates account createdAt if block disconnected

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

even if we have an account without a birthday we can use the createdAt field to save time in future wallet rescans by setting createdAt the first time the wallet connects a block that contains a transaction for that account.
updates connectBlock to set account.createdAt if the account had a transaction on the block and createdAt is null. if assetBalanceDeltas is not empty then the account had a transaction on the block.
```
[ ] Yes
```
```
[ ] Yes …
```

sets createdAt on first on-chain transaction

---

ironfish/src/mining/pool.ts
ironfish/src/mining/stratum/stratumServer.ts

the StratumServer has a property, 'subscribed', that it uses to count the number of subscribed miners.
we don't decrement that counter when a subscribed miner is disconnected because of an error. this causes the miner count in status messages to hover at an incorrect level after miner errors.
we also use the number of clients to indicate the number of miners when sending notifications for submitted blocks. this is not the right number since there may be connected clients that are only following the pool for status messages and aren't mining.
manual testing with discord hook to my own discord server. modified miner to send malformed messages.
before changes:
"Miners" keeps increasing after the miner idsconnects due to error
after changes:
"Miners" never increases from 0
Does this change …

fixes count of subscribed pool miners

---

ironfish/src/migrations/data/027-account-created-at-block.ts
ironfish/src/migrations/data/027-account-created-at-block/new/accountValue.ts
ironfish/src/migrations/data/027-account-created-at-block/new/headValue.ts
ironfish/src/migrations/data/027-account-created-at-block/new/index.ts
ironfish/src/migrations/data/027-account-created-at-block/old/accountValue.ts
ironfish/src/migrations/data/027-account-created-at-block/old/index.ts
ironfish/src/migrations/data/027-account-created-at-block/stores.ts
ironfish/src/migrations/data/index.ts
ironfish/src/wallet/walletdb/accountValue.ts
ironfish/src/wallet/walletdb/headValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

to support block-based account birthdays we will store the chain head (block hash and sequence) at the time the account was created.
adds migration to set createdAt to null for all existing accounts
- ran data migration and verified that createdAt was set to null with no other account data affected
```
[ ] Yes
```
```
[ ] Yes
```

migrates account createdAt from Date to HeadValue

---

ironfish/src/fileStores/config.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

by default the name of the account that a mining pool uses for payout transactions is hardcoded to 'default'. this poses two potential problems:
1. if the default account on the pool node is not 'default', then 'default' may not have any funds for payouts
2. 'default' may not exist on the pool node
instead of hardcoding the default value of the pool account name we can leave it unset by default. at the time of a payout the pool can then use the default account of its node.
- existing unit tests cover fetching default account from pool node via rpc
```
[ ] Yes
```
Is …

uses default node account in pool by default

---

ironfish/src/mining/__fixtures__/poolShares.test.ts.fixture
ironfish/src/mining/pool.ts
ironfish/src/mining/poolShares.test.ts
ironfish/src/mining/poolShares.ts

throws an error while starting a mining pool if payouts are enabled but there isn't an account to make payouts from.
- checks for account by name if poolAccountName is configured or checks for default account otherwise
- rearranges method calls in pool start to make RPC connection before starting MiningPoolShares instance
- manual testing: starting pool with non-existent account
```
[ ] Yes
```
```
[ ] Yes
```

checks if pool account exists on start if payouts enabled

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/table.ts

we've added a lot of logic to the 'wallet:transactions' command to format the table to make it easier to read in the CLI. however, this formatting logic removes data from the table that might be useful when outputting transaction data with the '--csv' or '--output' flags.
- refactors logic for assigning 'group' string to table rows for the same transaction into 'getRowGroup' method
- only includes the 'group' column in output if formatting the table for the CLI
- includes all transaction details (hash, fee, assetId, assetName, etc.) in each row if using '--csv' or '--output' flags
Manual testing:
I modified the `send` command to send multiple outputs in a single transaction to test formatting with multiple assets.
- Table output:
- CSV output:
```
Timestamp,Status,Type,Hash,Expiration,Fee …
```

conditionally formats cli transactions output

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

we need to ensure that the createdAt field of each account always refers to a block on the main chain (or is null). if we start the node and an account's createdAt block is not on the node's chain then we can't be sure that it ever will be (it could be on a fork at any time before or after the node's current head). in this case we need to reset the account's createdAt to null.
checks that createdAt is on chain for each account on wallet start and resets account data (including createdAt) if not
Closes IFL-27
- added unit tests
- created account
- used `ironfish repl` to set createdAt to fake block
- started node again
- used `ironfish repl` to see that account's createdAt reset to null …

IFL-27: resets account birthdays if not in chain

---

.github/workflows/deploy-brew.yml
.github/workflows/deploy-node-docker-image.yml
.github/workflows/deploy-npm-ironfish-rust-nodejs.yml
.github/workflows/rust_ci.yml

NodeJS 12 is being [deprecated in Github actions soon](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/). Upgrading our dependencies that use it to not use NodeJS 12 anymore
```
[ ] Yes
```
```
[ ] Yes
```

Updated GH Actions to not use NodeJS 12

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

if an account was created at a block that was later than the current scan block then it is not possible for the account to have any transactions on that block. we can speed up the scan for that account by skipping decryption for transactions on that block.
- defines 'shouldScanBlock' to determine whether an account should scan a block based on the account's createdAt field
- moves logic for decrpyting notes, connecting transactions on a block to a separate wallet method. this was done for readability to avoid deeply nested conditional logic in 'connectBlock'
- resets account and createdAt during scanning if createdAt refers to a block that is on a different chain or fork than the wallet's chainProcessor
- added unit test
- manual testing of skipping decryption
1. created an account
2. …

skips scanning blocks based on account birthday

---

ironfish/src/rpc/routes/wallet/addTransaction.test.ts
ironfish/src/rpc/routes/wallet/addTransaction.ts

Currently we have no info returned from RPC about the transaction that was added, this adds both if the transaction was accepted and what the hash is.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

feat: accept transactions response update

---

ironfish-cli/src/trusted-setup/server.ts

The previous implementation was using a single message buffer for all clients. This seemed to work because JS was single threaded but it also could have been introducing some bugs. Each client should have its own message buffer so messages don't conflict
Tested by running a server and client locally
```
[ ] Yes
```
```
[ ] Yes
```

Fix message buffer to be per client

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish/src/rpc/routes/wallet/types.ts

Exposes the last rebroadcast time in `wallet/getTransaction`. The field is named `submittedSequence` in the `TransactionValue` interface so the naming convention was kept. 
Existing tests
```
➜  ironfish git:(holahula/feat/expose-rebroadcast-time) ✗ fish wallet:transactions -d ~/.ironfish-simulator/node-b1f0 --limit 5 -t ccc358844370ab9f77dd1b1ef9b1beafceddb3c23a933b950315f4602afbb604 -x
$ yarn build && yarn start:js wallet:transactions -d /Users/austino/.ironfish-simulator/node-b1f0 --limit 5 -t ccc358844370ab9f77dd1b1ef9b1beafceddb3c23a933b950315f4602afbb604 -x
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:transactions -d /Users/austino/.ironfish-simulator/node-b1f0 …
```

refactor: expose last rebroadcast time in wallet/getTransaction

---

ironfish-cli/src/commands/ceremony/service.ts

Switching to a production endpoint that does not have inherent rate limiting
Local testing of contributions
```
[ ] Yes
```
```
[ ] Yes
```

Switch R2 to use prod endpoint

---

ironfish-cli/src/commands/wallet/transactions.ts

This reverts commit 0be0d68a4dc1a679873155b1a0c521955681fb2e.
```
[ ] Yes
```
```
[ ] Yes
```

Revert "optionally organizes wallet:transactions output by note"

---

ironfish/src/storage/database/errors.ts

When the DB is newer than your current software, the error is not very clear. It will still tell you to upgrade which is confusing. Now it will give you a better message.
```
[ ] Yes
```
```
[ ] Yes
```

Clarify db version error when db is newer

---

ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/rpc/routes/wallet/utils.ts

we have a couple of functions defined in the 'types' module. functions like these may fit better in 'utils' than in 'types'
```
[ ] Yes
```
```
[ ] Yes
```

moves wallet rpc util functions from types to utils

---

ironfish-cli/src/commands/wallet/import.ts

It was expecting an object for createdAt, but it used to be a ISO timestamp.
```
[ ] Yes
```
```
[ ] Yes
```

Make wallet:import handle wallets from version 71

---

simulator/src/simulator/simulation-node.ts

Adds support for running arbitrary ironfish cli commands in simulator simulations.
Demo simulation:
```js
export async function run(
logger: Logger,
options?: { persist?: boolean; duration?: number },
): Promise<void> {
const simulator = new Simulator(logger, options)
const nodes = []
for (let i = 0; i < 2; i++) {
nodes.push(await simulator.startNode())
}
const { stdout, stderr } = await nodes[0].executeCliCommandAsync('status', ['--all'])
logger.log(`stdout: ${stdout}`)
logger.log(`stderr: ${stderr}`)
nodes[1].executeCliCommand('status', ['--all'], {
onLog: (data) => {
logger.log(data)
},
onError: (err, stderr) => {
logger.error(`error: stderr: ${stderr}, ${err.message}, code: ${err.code || 'unknown'}`)
},
})
// wait for all nodes to be stopped
await simulator.waitForShutdown() …
```

feature(simulator): add support for running arbitrary ironfish cli commands

---

ironfish-cli/src/trusted-setup/server.ts

Since we may not have time for a pre-contribution period, adding a private queue for trusted setup contributions
Testing locally running server and client
```
[ ] Yes
```
```
[ ] Yes
```

Add private queue for trusted setup

---

ironfish-cli/scripts/import-export-test.sh
ironfish-cli/scripts/import-export-test/README

I noticed this was failing to run because my datadir database was a later version. I see it's using my actual datadir which I have my real data in. Changing this so it does not use a users real database to perform tests, and instead uses a test datadir.
```
[ ] Yes
```
```
[ ] Yes
```

Change importexport tests to use test datadir

---

.github/workflows/ci.yml
ironfish-cli/package.json
package.json

This test command was in the root package, but is only related to testing one package, the ironfish-cli. In the root we only run lerna there, and have each child package have their own set of commands that they own.
```
[ ] Yes
```
```
[ ] Yes
```

Move importexport tests to ironfish-cli

---

ironfish-cli/src/utils/transaction.ts
ironfish/src/wallet/wallet.ts

`ironfish wallet:transactions:watch` no longer quits if the transaction is not found. The `NOT_FOUND` state has been added as a `TransactionStatus` and is now integrated into the watch status loop 
Closes IFL-413
Successful watch:
```
➜  ironfish git:(holahula/fix/transaction-watch-404) ✗ fish wallet:send -d ~/.ironfish-simulator/node-e050 --watch
$ yarn build && yarn start:js wallet:send -d /Users/austino/.ironfish-simulator/node-e050 --watch
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:send -d /Users/austino/.ironfish-simulator/node-e050 --watch
Enter the amount (balance 48405.00000000): 1
Enter the public address of the recipient: …
```

refactor(ironfish): do not quit transaction:watch if the transaction is not found

---

ironfish-mpc/README.md

Picks a future randomness source that will be used to seal the parameters after public contributions are finished for trusted setup V2.
See previous PR for V1 randomness [here](https://github.com/iron-fish/ironfish/pull/3220)
```
[ ] Yes
```
```
[ ] Yes
```

Add beacon value for trusted setup V2

---

ironfish-cli/src/commands/ceremony/service.ts
ironfish-cli/src/trusted-setup/server.ts

The success message the user received at the end of the contribution was incorrect. Updating the download URL to be from R2. Also updating the default start date
Locally tested
```
[ ] Yes
```
```
[ ] Yes
```

Update download url trusted setup

---

ironfish-cli/src/commands/wallet/import.ts

This enables use of the --name flag which will override the import name
that comes from the data, or won't ask you for interactive import in the
case that you're importing a spend key only.
```
[ ] Yes
```
```
[ ] Yes
```

Allow specifying account name on import using flag

---

ironfish-cli/src/trusted-setup/server.ts

If the server encounters an error when verifying a contribution, the server can get into an unrecoverable state. Where `currentContributor.client` is null nut `currentContributor` is still defined. This means the trying to start the next contributor will not work
Local testing
```
[ ] Yes
```
```
[ ] Yes
```

Fix trusted setup error when verifying

---

ironfish-cli/scripts/import-export-test.sh

I had a hard time scanning the logs of this to see what it was doing. I simplified the logs and added two new things.
- Remove extraneous success logs
- Only log when each test is starting
- Don't delete the last test account created for perf boost
- Print out the time each test takes
- Add ENABLE_LOGS variable to show ironfish logs to help debugging
```
Running import by pipe:  ./import-export-test/0p1p65_blob.txt
Success in 0m1.838s
Running import by input: ./import-export-test/0p1p65_blob.txt
Success in 0m1.636s
Running import by path:  ./import-export-test/0p1p65_blob.txt
Success in 0m1.643s
Running import by pipe:  ./import-export-test/0p1p65_json.txt
Success in 0m1.761s
Running import by input: ./import-export-test/0p1p65_json.txt
Success in 0m1.633s
```
Does this change require any …

Make logs for importexport tests simpler

---

ironfish-cli/src/command.ts

I noticed that when ever an RPC error occurs the exit code is still 0. For these, we should be returning non zero exit codes. I'm not sure if there is an oclif bug reason for this to not do this but I think we should do this until we find a reason not to.
```
[ ] Requires documentation updates
[ ] Has breaking changes
```

Return error codes for RPC errors

---

ironfish-rust/src/signal_catcher.rs

This was the only failure in cargo build, excluding android os as well.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

fix: libc reference failing in android

---

ironfish/src/primitives/blockheader.ts
ironfish/src/primitives/target.test.ts
ironfish/src/primitives/target.ts

we define a maximum target value, but we don't enforce that a constructed Target instance is below the maximum target value.
- update fromDifficulty to return maxTarget for any difficulty >= minDifficulty
- updates blockheader to use bigint directly in verifyTarget instead of constructing Target from hash
```
[ ] Yes
```
```
[ ] Yes
```

enforces max target value in Target construction

---

ironfish/src/primitives/blockheader.ts
ironfish/src/primitives/target.test.ts
ironfish/src/primitives/target.ts

- fromDifficulty: division by zero when difficulty is 0
- toDifficulty: division by zero when target is 0
any difficulty value > 2**256 will give a target value of 0
note: ethereum uses the same calculation (2**256 / difficulty) for target, but some ethereum implementations (e.g., cpp-ethereum) used a 256-bit integer to store difficulty in the block header, which made a target of 0 impossible.
```
[ ] Yes
```
```
[ ] Yes
```

addresses zero division errors in Target calculation

---

ironfish-cli/src/commands/repl.ts

You can now use --no-db to not load the databases. This gives you access to the SDK without needing to load the data directory.
```
[ ] Yes
```
```
[ ] Yes
```

Allow opening the repl without opening the DB

---

ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts

adds transaction fields needed for developers to determine transaction status independently of the node
- adds blockHash and blockSequence to wallet/getAccountTransactions
- adds submittedSequence to responses for both wallet/getAccountTransaction and wallet/getAccountTransactions
- adds confirmations to wallet/getAccountTransaction and wallet/getAccountTransactions
- orders fields consistently between endpoints
```
[X] Yes
```
```
[ ] Yes
```

adds missing fields to wallet transaction RPCs

---

ironfish-cli/src/commands/chain/broadcast.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/chain/__fixtures__/broadcastTransaction.test.ts.fixture
ironfish/src/rpc/routes/chain/broadcastTransaction.test.ts
ironfish/src/rpc/routes/chain/broadcastTransaction.ts
ironfish/src/rpc/routes/chain/index.ts

Adds an RPC route and accompanying CLI command ( `ironfish chain:broadcast` ) for broadcasting a transaction to the network.
Closes IFL-411
- Included unit tests pass
Manual test:
1. Create raw transaction
```
➜  ironfish git:(holahula/feat/chain-broadcast-rpc) ✗ fish wallet:send -d ~/.ironfish-simulator/node-e050 --rawTransaction
$ yarn build && yarn start:js wallet:send -d /Users/austino/.ironfish-simulator/node-e050 --rawTransaction
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:send -d /Users/austino/.ironfish-simulator/node-e050 --rawTransaction
Enter the amount (balance 48782.00000000): 1
Enter the public address of the recipient: …
```

feature(ironfish): Add RPC route for `chain:broadcast`

---

ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/schema.ts

adds an index mapping transaction hash to block hash for all transactions on the main chain. the index will support looking up transactions on the chain using only the transaction hash. this lookup currently requires a block hash because the transactions store is keyed by block hash.
the index is a datastore with a TransactionHash (i.e., Buffer) key and a BlockHash (i.e., Buffer) value.
entries are inserted into the index for each transaction when a block is connected to the main chain (in saveConnect). entries are deleted from the index for each transaction when a block is disconnected from the main chain (in saveDisconnect).
Reference](https://ironfish.network/docs/onboarding/rpc/chain))? If …

adds transactionHashToBlockHash chain index

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/rpc/routes/chain/__fixtures__/getTransaction.test.ts.fixture
ironfish/src/rpc/routes/chain/getTransaction.test.ts
ironfish/src/rpc/routes/chain/getTransaction.ts

after adding an index from transaction hash to block hash in #3761 we no longer need to include a block hash in requests to chain/getTransaction. instead we can use the index to look up the hash of the block on the main chain that includes that transaction, if any.
- defines 'getHashByTransactionHash' to look up a block hash in 'transactionHashToBlockHash'
- changes 'blockHash' to an optional request parameter
- adds route tests for chain/getTransaction
```
[X] Yes
```
https://github.com/iron-fish/website/pull/359 …

makes blockHash optional in chain/getTransaction requests

---

ironfish/src/rpc/routes/wallet/postTransaction.test.ts
ironfish/src/rpc/routes/wallet/postTransaction.ts

sendTransaction includes the hash in its responses, but postTransaction does not.
a client _could_ hash the output themselves, but this adds an extra step and perhaps an extra dependency for the client.
- updates unit tests
```
[X] Yes
```
```
[ ] Yes
```

adds hash to response of wallet/postTransaction

---

ironfish/src/rpc/routes/faucet/getFunds.ts
ironfish/src/rpc/routes/router.test.ts
ironfish/src/rpc/routes/router.ts
ironfish/src/rpc/routes/wallet/addTransaction.ts
ironfish/src/rpc/routes/wallet/exportAccount.ts
ironfish/src/rpc/routes/wallet/getBalance.ts
ironfish/src/rpc/routes/wallet/getNotes.ts
ironfish/src/rpc/routes/wallet/getPublicKey.ts
ironfish/src/rpc/routes/wallet/getTransactions.test.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/rpc/routes/wallet/postTransaction.ts

The bug here is that the schema result is not used when routing requests. It means that any calls to default() will be ignored in the resulting request. No transformations will be made.
This fixes it so the transformed input is what is passed to the request and not the unsanitized input.
```
[ ] Yes
```
```
[ ] Yes
```

Use schema result when routing requests

---

ironfish/src/rpc/routes/wallet/getTransactions.test.ts
simulator/src/simulator/utils/accounts.ts

merging several PRs to staging without rebase introduced lint errors where RPC client methods were not accessed within their recently-added namespaces.
```
[ ] Yes
```
```
[ ] Yes
```

fixes lint errors from rpc client namespaces

---

ironfish/src/network/version.ts

We've had this sitting in the mainnet branch for a while, but since we're doing a network reset on staging, we can deploy this with the network reset.
We changed the IDs for some messages a while ago without updating the network version, but everything has mostly worked because we also reset the genesis block several times.
This resets us to the same min + protocol version to give us a consistent version for mainnet launch.
```
[ ] Yes
```
```
[x] Yes
```

Bump min network version to 22

---

ironfish-cli/src/commands/airdrop/constants.ts
ironfish-cli/src/commands/airdrop/split.ts
ironfish-cli/src/commands/chain/genesisblock.ts
ironfish-cli/src/utils/allocations.ts

Adds split command so that we can have pre-split notes for airdrop. Each airdrop transaction will contain all the ORE required for `AIRDROP_NOTES_IN_BLOCK` * FEE (10 ORE) plus the payouts for that transaction.
test in simulator
```
[ ] Yes
```
```
[ ] Yes
```

feat: airdrop split command

---

ironfish-cli/src/commands/airdrop/raw-transactions.ts
ironfish-cli/src/commands/airdrop/split.ts
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/wallet/createTransactionAirdrop.ts

Takes input allocations generated [from export](https://coda.io/d/_dMnayiE39lL/Airdrop_su_t8#_luHf9), bundles them based on max output notes per transaction, and writes them to file.
test in simulator
```
[ ] Yes
```
```
[ ] Yes
```

feat: airdrop allocations to raw transactions

---

ironfish-cli/src/commands/airdrop/post.ts

This will be run on air-gapped node to post the transactions with the spend key for airdrops.
simulation test
```
[ ] Yes
```
```
[ ] Yes
```

feat: airdrop post transactions

---

.github/workflows/deploy-node-docker-image.yml

we recently added the ability to deploy docker images tagged with the version tag (e.g., v0.1.76)
however, the workflow currently only deploys these tags if we are also deploying to and overwriting the 'latest' tag. this prevents us from deploying a tag from an earlier version, like v0.1.75, without overwriting the 'latest' image from the current version
we also use the 'github.event' context to determine if we're deploying a tag. this is incorrect since the only event that can trigger this workflow is 'workflow_dispatch', which does not have a 'ref_type' parameter, so `github.event.ref_type == 'tag'` will never be true.  instead we can use 'github.ref_type' which will refer to the branch or tag that the workflow was triggered from.
Does this change require any updates to the Iron Fish …

allows docker deploy with version tags only

---

ironfish/src/node.ts

Add a telemetry tag to separate mainnet and testnet telemetry
Tested by running node locally and verifying payload sent to telemetry endpoint
```
[ ] Yes
```
```
[ ] Yes
```

Separate mainnet + testnet telemetry

---

ironfish-cli/src/commands/mainnet.ts

adds changes from #3797 into 'mainnet' command.
clears old chain data from the walletdb that cannot be migrated or deleted by key following changes from network reset.
```
[ ] Yes
```
```
[ ] Yes
```

clears walletDb in 'mainnet' command

---

ironfish-cli/src/commands/status.ts
ironfish/src/defaultNetworkDefinitions.ts
ironfish/src/index.ts
ironfish/src/rpc/routes/node/getStatus.ts

Closes IFL-678
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Add network name to status. uses id as fallback

---

ironfish/src/webApi.ts

Sync over block header work for hash rate calculation
N/A
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Send block header work to API in sync

---

ironfish/src/fileStores/config.ts
ironfish/src/node.ts
ironfish/src/sdk.test.ts
ironfish/src/telemetry/telemetry.test.ts
ironfish/src/telemetry/telemetry.ts
ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/submitTelemetry.test.ts
ironfish/src/workerPool/tasks/submitTelemetry.ts

Send telemetry to the correct API endpoint depending on the network id
```
[ ] Yes
```
```
[ ] Yes
```

Separate telemetry by endpoint

---

ironfish-cli/src/commands/wallet/notes.ts
ironfish/src/rpc/routes/wallet/getNotes.ts

Adds note hash to `wallet/getAccountNotesStream` RPC
```
➜  ironfish git:(holahula/feat/add-hash-to-note-stream) fish wallet:notes -d ~/.ironfish-simulator/node-1c55 --columns="Memo","Sender","Note Hash","From Transaction"
$ yarn build && yarn start:js wallet:notes -d /Users/austino/.ironfish-simulator/node-1c55 '--columns=Memo,Sender,Note Hash,From Transaction'
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:notes -d /Users/austino/.ironfish-simulator/node-1c55 '--columns=Memo,Sender,Note Hash,From Transaction'
Memo                             Sender                                                   Note Hash …
```

feat(ironfish): add note hash to `wallet/getAccountNotesStream` RPC

---

ironfish/src/rpc/routes/chain/getTransaction.test.ts
ironfish/src/rpc/routes/chain/getTransaction.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts
ironfish/src/rpc/routes/wallet/getTransactions.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/rpc/routes/wallet/utils.ts

We don't return note hashes in several RPC responses where other fields from the note are returned. Add the hash where appropriate.
Updated existing unit tests.
```
[x] Yes
```
https://github.com/iron-fish/website/pull/398
```
[ ] Yes
```

feat(ironfish): Add missing note hashes from RPC responses

---

simulator/src/commands/start.ts
simulator/src/simulations/index.ts
simulator/src/simulations/send.ts
simulator/src/simulations/stability.ts
simulator/src/simulator/simulator.ts

Attempting to hook into `process.on('uncaughtException')` in the simulator to catch exceptions before process shutdwn does not work because oclif has built-in uncaught exception handlin so the exception never propagates to this level. Thus, when unexpected errors occur in user-written simulations, the simulator is unaware of them and is unable to gracefully shutdown. This can leave running `ironfish` processes hanging in the background which affects future simulation runs. 
By wrapping the simulation execution in a try-catch block, the uncaught exceptions / unhandled rejections can be caught before they reach oclif and the simulator can gracefully shutdown before exit.
The simulator needs to be created in the `start` cmd so it can catch unexpected simulation exits. 
Closes IFL-566
Sample …

fix(simulator): gracefully shutdown simulator on unexpected exit

---

ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish/src/rpc/routes/wallet/__fixtures__/getTransaction.test.ts.fixture
ironfish/src/rpc/routes/wallet/getTransaction.test.ts
ironfish/src/rpc/routes/wallet/getTransaction.ts

Follow-up to #3834 
Linear task https://linear.app/if-labs/issue/IFL-723/add-spend-to-rpc-walletgettransaction
Closes IFL-733
```
➜  ironfish git:(holahula/feat/wallet-get-transaction-vin) ✗ fish wallet:transaction 4b6ca31c20360291fd81d8f15ac2677236db0c6993fc2e95a0ae0acab3178eb2 -d ~/.ironfish-simulator/node-1c55
$ yarn build && yarn start:js wallet:transaction 4b6ca31c20360291fd81d8f15ac2677236db0c6993fc2e95a0ae0acab3178eb2 -d /Users/austino/.ironfish-simulator/node-1c55
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:transaction 4b6ca31c20360291fd81d8f15ac2677236db0c6993fc2e95a0ae0acab3178eb2 -d /Users/austino/.ironfish-simulator/node-1c55
Transaction: …
```

feat(ironfish): add spends to `wallet/getTransaction`

---

ironfish/src/rpc/routes/wallet/__fixtures__/createTransaction.test.ts.fixture
ironfish/src/rpc/routes/wallet/createTransaction.test.ts
ironfish/src/rpc/routes/wallet/createTransaction.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

supporting custom transaction funding will allow users and developers to choose the notes to spend in a transaction using whatever note selection algorithm they choose.
adds optional 'spendNoteHashes' parameter to 'wallet/createTransaction' rpc endpoint to accept a list of hex string note hashes to use to fund a transaction.
implements 'fundWithNoteHashes' to load decrypted notes from the specified hashes and use them to build the spends for a raw transaction. ensures that the specified notes have enough value to fund the transaction. requires that notes have an index so that a witness can be created.
does not check whether the notes have already been spent. this is intentional to support use cases like 'canceling' or 'speeding up' a transaction by creating a transaction that spends the …

adds custom transaction funding by note hash

---

ironfish/src/rpc/routes/wallet/getNotes.ts

We should return the note indices from the decrypted notes in the wallet for ease of use by developers.
N/A
```
[x] Yes
```
TODO: Will add
```
[ ] Yes
```

feat(ironfish): Return note indices in getNotes

---

ironfish/src/primitives/transaction.ts

This shouldn't practically cause any issues, but since fee is an i64, we could run into some bounds errors if we don't use bigint for deserialization.
Fixes IFL-741
```
[ ] Yes
```
```
[ ] Yes
```

Deserialize fee as BigI64

---

ironfish/src/rpc/routes/chain/getTransaction.ts

Use JsDoc `@deprecated` to mark this field as deprecated
```
[ ] Yes
```
```
[ ] Yes
```

refactor(ironfish): Properly mark `notesEncrypted` as deprecated

---

ironfish-cli/src/utils/transaction.ts

Fix https://github.com/iron-fish/ironfish/issues/3823. Remove unnecessary `Current status... !` from transaction:watch when status is already in desired state.
Before - 
```
wd021:~# ironfish wallet:transaction:watch abcd
Transaction abcd is confirmed
Current Status... !
```
After - 
```
wd021:~# ironfish wallet:transaction:watch abcd
Transaction abcd is confirmed
```
Run `wallet:transaction:watch` for confirmed transaction
```
[ ] Yes
```
```
[ ] Yes
```

Update cli text for transaction:watch

---

README.md

Updates readme documentation URL
Check if new URL works in https://github.com/iron-fish/ironfish/blob/c14dac9b9b17356ad388bd67c47678d4319fb0ed/README.md
```
[ ] Yes
```
```
[ ] Yes
```

docs: documentation url

---

ironfish/src/genesis/genesis.test.slow.ts

Ideally, we would not need to rely on hard-coded timeouts, since that messes with our `JEST_TIMEOUT` env var functionality. Using fixtures would require adding new, very specific fixtures and ultimately I think this logic is delicate enough that I'd prefer not to use fixtures.
Closes IFL-772
```
[ ] Yes
```
```
[ ] Yes
```

fix(test): add a significant timeout for add genesis transaction tests

---

tools/version-bump.js

Makes the default version bump the "minor" version instead of the patch as per the documentation outlined here: https://github.com/iron-fish/website/pull/422
Ran the following and inspected the git diff:
`node ./tools/version-bump.js`
`node ./tools/version-bump.js --rust`
`node ./tools/version-bump.js --patch`
`node ./tools/version-bump.js --patch --rust`
`node ./tools/version-bump.js --major`
`node ./tools/version-bump.js --major --rust`
```
[x] Yes
```
```
[ ] …
```

feat(tools): Version bump script can bump all version numbers

---

simulator/src/simulator/simulation-node.ts
simulator/src/simulator/utils/accounts.ts

`child_process.spawn()` cannot handle stringified JSON arguments. Importing the genesis block converts the genesis account into a string which needs `child_process.exec()` to run. 
This was broken by #3840, so `executeCliCommandAsync()` was re-added and renamed to `executeCliCommandWithExec()` with a disclaimer as to when to use this one. 
Soon
```
[ ] Yes
```
```
[ ] Yes
```

fix: use exec instead of spawn for complex cli commands

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/asset.rs
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/database/assetValue.test.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/rpc/routes/chain/getTransactionStream.test.ts
ironfish/src/rpc/routes/wallet/burnAsset.test.ts
ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts
ironfish/src/rpc/routes/wallet/createTransaction.test.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.test.ts
ironfish/src/rpc/routes/wallet/getAssets.test.ts
ironfish/src/rpc/routes/wallet/getBalances.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/wallet/account.test.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/walletdb/assetValue.test.ts
ironfish/src/wallet/walletdb/transactionValue.test.ts

The signature for `Asset` constructor was taking spending key, but it immediately converted it to public address in napi method. Having this take the public address instead allows us to calculate `RawTransaction` size deterministically _without_ the spending key. Which means we can calculate size of a transaction with a view only wallet.
Tests pass
```
[ ] Yes
```
Any user of the ecosystem that is constructing an `Asset` manually will break. I think it is unlikely anyone is doing this yet.
```
[x] Yes
```

feat(ifl-774): asset constructor use public address

---

ironfish/src/workerPool/pool.ts

`PostTransaction` was missing in `workers:status` in everywhere but display, this adds support for it
Closes IFL-649
```
Workers: STARTED - 0 -> 1 / 6 - -0.08 jobs Δ, 12.68 jobs/s
JOB                  | QUEUE | EXECUTE | ERROR | DONE
CreateMinersFee      |     0 |       0 |     0 | 37
DecryptNotes         |     0 |       0 |     0 | 99
PostTransaction      |     0 |       1 |     0 | 6
SubmitTelemetry      |     0 |       0 |     0 | 0
VerifyTransaction    |     0 |       0 |     0 | 0
VerifyTransactions   |     0 |       0 |     0 | 109
```
```
[ ] Yes
```
Is this a breaking change? …

feat: add support for `PostTransaction` in `workers:status`

---

ironfish-rust-nodejs/src/structs/note_encrypted.rs
ironfish/src/primitives/__fixtures__/rawTransaction.test.ts.fixture
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/primitives/spend.ts
ironfish/src/primitives/transaction.ts
ironfish/src/wallet/wallet.ts

Updates size to match https://github.com/iron-fish/ironfish/blob/master/ironfish/src/primitives/transaction.ts#L44
We have to account for change notes as well. We can determine if there will be change for each asset by calculating the total spends/mints/burns/outputs. If they equal 0, there will be no change note
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

ifl-744 add test/updates for calculating raw transaction size

---

simulator/src/simulations/getAccountTransaction.ts
simulator/src/simulations/index.ts

we have heard reports that the 'wallet/getAccountTransaction' endpoint does not always return every transaction.
this simulation creates three nodes and has two 'sender' nodes repeatedly send transactions to the 'receiver' node. for each transaction the simulation checks that the transaction can be found on the sender node and the receiver node using the 'wallet/getAccountTransaction' endpoint over HTTP.
running the simulation for ~1000 blocks did not find any transactions missing from either the sender or receiver.
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below …

adds a simulation for fetching transactions from getAccountTransaction

---

ironfish/src/primitives/__fixtures__/note.test.ts.fixture
ironfish/src/primitives/note.test.ts
ironfish/src/primitives/note.ts
ironfish/src/primitives/noteEncrypted.ts
ironfish/src/primitives/rawTransaction.ts

- Adding size methods for Note/NoteEncrypted primitives
- Add test to make sure these stay up to date
Our constants were becoming stale rather quickly (e.g. `NOTE_ENCRYPTED_SERIALIZED_SIZE_IN_BYTE`), so this pattern attempts to do two things. 
1. Tightly couple the size via a static method to our objects (rather than an unrelated constant)
2. Add a test that verifies this always stays up to date. It is currently possible to update the serialized size of these objects (rust side) without updating these methods. Now if these values change, the tests will break.
tests pass
```
[ ] Yes …
```

feat(ifl 776): size method note primitives

---

ironfish/src/rpc/routes/mempool/getTransactions.ts

inequality sign was wrong, if limit was passed as a parameter no transactions would be returned
n/a
```
[ ] Yes
```
```
[ ] Yes
```

fix: fix mempool/getTransactions limit parameter

---

ironfish-cli/src/commands/wallet/notes.ts
ironfish/src/rpc/routes/wallet/getAccountNotesStream.ts

Return note nullifier value in the response of wallet/getAccountNotesStream
```
yarn start wallet:notes
$ yarn build && yarn start:js wallet:notes
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:notes
module: @oclif/core@1.23.1
task: toCached
plugin: ironfish
root: /Users/yajun/ironfish/ironfish/ironfish-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Memo                             Sender Note Hash From Transaction Spent Asset ID                                                Asset Name                       Amount          Nullifier
──────────────────────────────── ────── ───────── ──────────────── ───── …
```

Return nullifier in rpc notes responses

---

ironfish/src/utils/buffer.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

- updates loadDecryptedNotes to accept a key range (gte, lt).
- adds BufferUtils for max and min of two nullable buffers to make it easier to construct key ranges with defaults.
```
[ ] Yes
```
```
[ ] Yes
```

adds pagination support to walletDb loadDecryptedNotes iterator

---

ironfish/src/rpc/routes/wallet/__fixtures__/utils.test.ts.fixture
ironfish/src/rpc/routes/wallet/utils.test.ts
ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/wallet/wallet.ts

the wallet/getAccountTransaction and wallet/getAccountTransactions RPC endpoints decrypt notes from the transaction so that we can return data for any output notes that an account sent to another address in the transaction.
we have to do this decryption because the walletDb doesn't store decrypted notes that an account doesn't own.
however, this decryption is applied to all notes in the transaction. we don't need to decrypt any notes that we already store in decrypted form in the walletdb (i.e., notes the account owns). we also don't need to try to decrypt any other output notes if the account was not the sender of the transaction since we won't be able to decrypt them.
avoids unnecessary decryption and adds unit tests.
adds unit tests
manual testing: compared output of `ironfish …

removes unnecessary note decryption in wallet transaction RPCs

---

ironfish-cli/src/commands/service/stats.ts

Combines fee-rates and forks service command into one. Once we are converted over I will delete the other two commands.
Tested against local host, was hitting `/telemetry` endpoint and subsequently `influx` for both:
```
[ ] Yes
```
```
[ ] Yes
```

feat(ifl-406): combine service commands

---

ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish/src/rpc/routes/wallet/__fixtures__/getAccountNotesStream.test.ts.fixture
ironfish/src/rpc/routes/wallet/getAccountNotesStream.test.ts
ironfish/src/rpc/routes/wallet/getAccountNotesStream.ts
ironfish/src/rpc/routes/wallet/getAccountTransaction.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/rpc/routes/wallet/utils.ts

defines a single RpcWalletNote type and schema, reuses across three wallet endpoints that return note data.
adds owner, index, nullifier, noteHash, and transactionHash fields to notes returned in transaction endpoints for consistency.
marks 'hash' field as deprecated. transaction endpoints used 'hash' and notes endpoint uses 'noteHash'.
marks 'isOwner' field as deprecated. this isn't very useful if the note contains the owner address. if clients need to compare the owner address to the public address for an account this is better done on the client side than the rpc.
existing unit tests
related documentation pull request for the …

makes notes from wallet RPCs uniform

---

.github/ISSUE_TEMPLATE/BUG-REPORT.yml

Graffiti isn't really relevant to bug reporting anymore now that the incentivized testnet has concluded.
```
[ ] Yes
```
```
[ ] Yes
```

Remove graffiti from the bug report template

---

.github/pull_request_template.md
ironfish/src/consensus/verifier.ts

This method takes in the consensus param as an argument (since it can vary between networks/nodes) and 
From discussion with Derek:
Joe:
Why would we need blockSize as a param for this task?
Seems like the blockSize will always be the same unless we update the concensus params (which would in turn update this method).
Derek:
since it’s configurable in the network params, we should assume that it might be different depending on the network. and in that case we need the consensus params for the node + the network the node is connected to
```
[ ] Yes
``` …

feat(ifl-779): add getMaxTransactionBytes method to the verifier

---

ironfish-cli/src/commands/chain/download.ts

chain:download on Windows was erroring out with the following error:
```
Error: EBUSY: resource busy or locked, unlink 'C:\Users\dguen\.ironfish\databases\chain\000015.ldb'
Removing existing chain data at C:\Users\dguen\.ironfish\databases\chain before importing snapshot... !
```
This change fixes the error by closing the DB before deleting it.
Fixes IFL-827
Fixes #3843
```
[ ] Yes
```
```
[ ] Yes
```

Fix Windows chain:download by closing DB before deleting

---

ironfish/src/fileStores/config.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/node.ts

In order to bypass the maxPeers config for incoming connections a whitelist for incoming Websocket connections needs to be added.
Tested on local node
```
[ ] Yes
```
```
[ ] Yes
```

Add incoming peer whitelist by IP

---

ironfish-cli/src/commands/chain/download.ts

Check network Id in chain:download cli. Download testnet snapshot if the network Id is 0.
local 
```
yajun@Yajuns-MBP ironfish-cli % yarn start chain:download --datadir=~/testnet/.ironfish
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run chain:download '--datadir=~/testnet/.ironfish'
root: /Users/yajun/ironfish/ironfish/ironfish-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
Download 16.98 MB snapshot to update from block 4348 to 9700? 
At least 33.97 MB of free disk space is required to download and unzip the snapshot file.
Are you sure? (Y)es / (N)o: Y
Downloading snapshot from https://testnet.snapshots.ironfish.network/ironfish_snapshot_16829533249 …
```

Check network version on chaindownload

---

ironfish-cli/src/commands/status.ts
ironfish/src/rpc/routes/node/getStatus.ts

Peer ID isn't available through any RPC endpoint or CLI command currently. Exposing that here
Local testing
https://github.com/iron-fish/website/pull/442
```
[X] Yes
```
```
[ ] Yes
```

Add peer identity to status command

---

ironfish/src/metrics/index.ts
ironfish/src/rpc/adapters/httpAdapter.ts
ironfish/src/rpc/routes/rpc/getStatus.ts

This adds support for outputting `RpcHttpAdapter` status under the `rpc/getStatus` route
Output of `ironfish rpc:status -f`
```
STARTED: true
[RpcIpcAdapter]
Clients:          2
Requests Pending: 2
Routes Pending:   node/getStatus, rpc/getStatus
Inbound Traffic:  0 B/s
Outbound Traffic: 2.99 KiB/s
Outbound Total:   170.76 KiB
Inbound Total:    190 B
RW Backlog:       0 B / 0 B
[RpcHttpAdapter]
Clients:          2
Requests Pending: 2
Routes Pending:   mempool/getStatus, rpc/getStatus
Inbound Traffic:  0 B/s
Outbound Traffic: 788 B/s
Outbound Total:   23.11 KiB
Inbound Total:    66 B
RW Backlog:       0 B / 0 B
```
related documentation …

adds support for `RpcHttpAdapter` in `rpc/getStatus` route

---

ironfish-rust/src/lib.rs

We've done a trusted setup, so these comments are no longer necessary.
```
[ ] Yes
```
```
[ ] Yes
```

Remove outdated comments in ironfish-rust

---

ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
ironfish/src/memPool/memPool.test.ts
ironfish/src/memPool/memPool.ts
ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture
ironfish/src/network/peerNetwork.test.ts

While it is not possible to double spend in this way due to checking for this when adding a block to the chain, this kind of transaction could cause issues for miners by getting them to create invalid blocks. By checking for this on gossip and when adding a transaction to the mempool, we remove that possibility.
It is not necessary to check this in all of the places that we are, but it is a relatively cheap check, so if we re-introduce the flaw in one place in the future, it will still get caught.
Closes IFL-848
Unit tests for the mempool, blockchain and verifier 
```
[ ] Yes
```
Is …

fix(ironfish): Check for transactions with duplicate nullifiers earlier

---

.cargo/config.toml
.github/workflows/rust_ci.yml
Cargo.lock
Cargo.toml
README.md
benchmarks/Cargo.toml
benchmarks/README.md
benchmarks/benches/asset.rs
benchmarks/benches/merkle_note.rs
benchmarks/benches/sapling_key.rs
benchmarks/benches/transaction.rs
benchmarks/src/lib.rs
ironfish-rust/Cargo.toml
ironfish-rust/benches/transaction.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/test_util.rs
ironfish-rust/src/transaction/mod.rs

Due to limitations of how Cargo and Rust work, we would have been limited in how robust we could make the benchmark code without doing things like including `criterion` as a non-dev dependency. While we could still gate it as an optional dependency, it just feels kind of bad to do it that way. 
By creating a separate package, we can create all the benchmark code we want without worrying about it getting included in the binaries we deliver with the node.
Eventually, we may even consider adding Typescript benchmark code here as well. Haven't really thought through that, but we have plenty of flexibility now.
Closes IFL-813
Closes IFL-815
Closes IFL-819
Closes IFL-820
Closes IFL-824 …

test: introduce some basic benchmarks

---

.github/workflows/deploy-brew.yml

Homebrew deploys aren't working because the Github action is running on a 
deprecated version of MacOS.
Fixes IFL-935
```
[ ] Yes
```
```
[ ] Yes
```

Update brew workflow to macos-12

---

ironfish/src/wallet/account.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

updates transaction loading methods in walletDb to accept an optional DatabaseKeyRange. supports using database keys to paginate the wallet/getTransactions RPC endpoint.
Closes IFL-799
adds unit tests
```
[ ] Yes
```
```
[ ] Yes
```

adds pagination support to walletDb loadTransactions iterator

---

ironfish/src/merkletree/merkletree.test.ts
ironfish/src/merkletree/merkletree.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts

modifies 'witness' to accept a size parameter to construct a witness at a past tree size.
if constructing a witness at a past size we need to recompute the hashes of all nodes in the tree that included leaves that were not in the tree at that size.
defines 'pastRightSiblingHashes' to recompute hashes along the path from the rightmost leaf of a tree at a past size to the root. returns a mapping from node index to the hash at that index for the past root.
adds merkletree unit test to verify that we can correctly recompute witnesses at past tree sizes.
adds unit tests
```
[ ] Yes
```
Is …

adds support for creating witnesses at past sizes

---

ironfish-cli/src/commands/wallet/send.ts

`ironfish wallet:send` always use the default account balance when user chooses custom fee, this PR fixes.
```
[ ] Yes
```
```
[ ] Yes
```

Fix bad account balance for custom fee

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts

If users manually pass in an account or confirmations value, we should pass that along to the custom fee selector.
```
[ ] Yes
```
```
[ ] Yes
```

Add confirmations and account to mint,burn,send fee selector

---

ironfish/src/node.ts
ironfish/src/sdk.test.ts

Adds agent to telemetry tags so we can differentiate node app
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

feat(ifl-934): agent to telemetry tags

---

ironfish/src/rpc/routes/chain/__fixtures__/getNoteWitness.test.ts.fixture
ironfish/src/rpc/routes/chain/getNoteWitness.test.ts
ironfish/src/rpc/routes/chain/getNoteWitness.ts

the merkle tree now supports creating witnesses at past tree sizes. this allows us to create witnesses using a confirmation range.
adds a confirmations request parameter to the chain/getNoteWitness rpc. use confirmations to determine the confirmed tree size before creating a witness for the note at that tree size.
Closes IFL-880, IFL-881
```
[X] Yes
```
```
[ ] Yes
```

adds confirmations to chain/getNoteWitness

---

ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts

when a miner submits a block to the mining manager the manager discards the block if the chain has changed. that is, if the submitted block no longer connects to the chain head.
however, if the submitted block is heavier than the curremt chain head then the manager should add this block to the chain.
- removes unnecessary check that chain head exists
- does not discard submitted block if it is heavier than the current chain head
```
[ ] Yes
```
``` …
```

checks if submitted block is heavier when chain changed

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/metrics/metricsMonitor.ts
ironfish/src/storage/database/database.ts
ironfish/src/storage/levelup/database.ts
ironfish/src/telemetry/telemetry.ts

Create size() function for level DB
Create a new chainDatabaseSize metric
unit test
```
[ ] Yes
```
```
[ ] Yes
```
@rohanjadvani @NullSoldier @dguenther

Add chain database size to telemetry

---

ironfish/package.json

Realized when I was trying to run them all that it was running them in multiple threads and the timeout is too short for some of the longer running perf tests
```
[ ] Yes
```
```
[ ] Yes
```

fix: typescript perf tests run in band, longer timeout

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/flags.ts

the IronFlag takes a 'largerThan' parameter but prints an error message using the 'minimum'. this results in a misleading error message. for example, when using a fee of 0 ORE:
'Error: The minimum fee is $ORE 0'
- changes 'largerThan' to 'minimum'
- changes logic to use less than instead of less than or equal to trigger error messages
- changes flag usage to use minimums of 1 ORE for fees
before:
after:
```
[ ] Yes
```
```
[ ] Yes
```

fixes error message from IronFlag

---

ironfish-cli/src/commands/service/sync.ts
ironfish/src/webApi.ts

moves 'syncBlocks' to a separate method
defines 'syncTransactionGossip' method to invoke the 'event/onTransactionGossip' RPC and submit transactions to the API
updates 'sync' to run both of these methods in coroutines
updates 'webApi' with a 'transactions' method. matches transaction serialization with serialization from 'followChainStream' for transactions submitted to API with blocks.
manual testing: ran syncer locally and synced transaction to testnet api: 5c1fa0c851957d46585addf64567fb6ab93f980d23d0d698a6ab49cfc2eb7e1b
```
[ ] Yes
```
Is this a breaking change? If yes, add notes …

updates sync service to submit transaction gossip to api

---

ironfish-cli/src/commands/wallet/send.ts

No longer prompt for a memo if `--memo ''` is specified on the command line.
Previously, running `wallet:send --memo ''` would prompt for a memo interactively. With this change, the tool instead accepts an empty memo and moves on without any interactive prompt.
Before this change:
*   No `--memo` argument provided: prompt displayed
```
$ yarn start wallet:send --amount 0.00000001 --fee 0.00000001 --to ...
Enter the memo (or leave blank): 
...
```
*   Empty argument to `--memo`: **prompt displayed**
```
$ yarn start wallet:send --amount 0.00000001 --fee 0.00000001 --to ... --memo ''
...
```
After this change:
*   No `--memo` argument provided: prompt displayed
```
$ yarn start wallet:send --amount 0.00000001 --fee 0.00000001 --to ...
Enter the memo (or leave blank): 
...
```
*   Empty …

Allow empty strings in the `--memo` argument of `wallet:send`

---

ironfish/src/rpc/routes/chain/followChainStream.ts

This change exposes the expiration information of transactions in the output of `chain/followChainStream`. This new field is always present, even with the expiration is set to 0.
Checked the output of `curl -s http://127.0.0.1:8021/chain/followChainStream` and verified that the `expiration` field is present and contains an integer value.
https://github.com/iron-fish/website/pull/457
No, because this only adds a new field; it does not alter/delete existing fields.

Add the 'expiration' field to transactions returned by followChainStream

---

Cargo.toml
benchmarks/Cargo.toml
ironfish-rust-nodejs/Cargo.toml
ironfish-rust/Cargo.toml
ironfish-zkp/Cargo.toml

Added description, keywords, and links to the crates that will be published to crates.io (plus a few more crates for consistency).
Also added a version number to the `ironfish-rust` -> `ironfish-zpk` dependency: this version number will be required in order to publish `ironfish-rust` to crates.io.
Ran `cargo publish --dry-run` for `ironfish-zkp`, and inspected the resulting `.crate` files. Relevant output:
```
[package]
edition = "2021"
name = "ironfish_zkp"
version = "0.1.0"
authors = ["Iron Fish <contact@ironfish.network> (https://ironfish.network)"]
description = "Sapling API and zero-knowledge proving mechanism for the Iron Fish node"
homepage = "https://ironfish.network/"
readme = "README.md"
keywords = [
"iron-fish",
"sapling",
"zero-knowledge",
]
license = "MIT OR Apache-2.0" …
```

Prepare rust crates' metadata for publishing

---

.github/workflows/rust_ci.yml
Cargo.lock
benchmarks/Cargo.toml
benchmarks/benches/asset.rs
benchmarks/benches/merkle_note.rs
benchmarks/benches/sapling_key.rs
benchmarks/benches/transaction.rs
ironfish-rust-nodejs/Cargo.toml
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/nacl.rs
ironfish-rust-nodejs/src/rolling_filter.rs
ironfish-rust-nodejs/src/signal_catcher.rs
ironfish-rust-nodejs/src/structs/asset.rs
ironfish-rust-nodejs/src/structs/note.rs
ironfish-rust-nodejs/src/structs/note_encrypted.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust-nodejs/src/structs/witness.rs
ironfish-rust/Cargo.toml

Rename the crate in order to better follow the Rust conventions. In particular: https://rust-lang.github.io/api-guidelines/naming.html
> Crate names should not use -rs or -rust as a suffix or prefix. Every
> crate is Rust! It serves no purpose to remind users of this constantly.
Rebuilt the repository, and verified that the CLI program starts correctly.
N/A
Not a breaking change (yet) thanks to the fact that `ironfish_rust` is not public.

Rename the `ironfish_rust` crate to just `ironfish`

---

Cargo.lock
ironfish-rust/Cargo.toml
ironfish-rust/src/nacl.rs

-   Update `crypto_box` to the latest version (from 0.7 to 0.8).
`crypto_box` 0.7 had a [`crypto_box::Box` type alias](https://docs.rs/crypto_box/0.7.2/crypto_box/type.Box.html) that was equivalent to `crypto_box::SalsaBox`. In 0.8, this alias was removed, hence changed all code to use `SalsaBox` explicitly.
-   Updated `crossbeam-channel` to use a version that is not yanked.
Rebuilt workspace and ran tests.
N/A

Update `crypto_box` and `crossbeam-channel`

---

ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

Fixes a bug where calling `wallet:transaction` or `wallet:transactions` on a transaction with more than 255 output notes would only display at most the first 255 results.
The decryptNotes task passes in the number of notes to decrypt as a u8, but bufio only bounds-checks if a number is a safe integer when writing numbers, and we don't do any verification that the number of results matches the number of inputs, so it's possible to overflow the value. In the wallet's transaction processing code, we decrypt notes in batches of 20, so this doesn't affect it. But when calling `wallet:transaction` or `wallet:transactions`, we attempt to decrypt output notes as a spender in one batch, and since transactions can have several hundred notes, this opens up the possibility for this bug.
The PR's …

Fix wallet:transaction decrypting at most 255 notes

---

ironfish-cli/src/commands/service/stats.ts
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/rpc/routes/chain/getChainInfo.ts
ironfish/src/rpc/routes/node/getStatus.ts
ironfish/src/telemetry/telemetry.ts

Move chain db size to stats cmd
Add chain db size to node getStatus response
Remove chain db size from telemetry class and blockchain class
locally run `yarn start service:stats` 
log chain db size to console
```
yajun@Yajuns-MBP ironfish-cli % yarn start service:stats
$ yarn build && yarn start:js service:stats
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run service:stats
module: @oclif/core@1.23.1
task: toCached
plugin: ironfish
root: /Users/yajun/ironfish/ironfish/ironfish-cli
See more details with DEBUG=*
(Use `node --trace-warnings ...` to show where the warning was created)
chain DB size 3486947512
```
Does this change require any updates to the Iron Fish Docs (ex. [the RPC …

Move chain db size out of telemetry class and into stats cmd

---

ironfish-cli/src/commands/service/stats.ts

The fork count metric stop working after calling chainDB first in the metrics loop. It stucks at line 60 `await this.sdk.client.chain.getConsensusParameters()`
The fork count start to work after the reorder.
local run service:stats
```
[ ] Yes
```
```
[ ] Yes
```
@iron-fish/engineering

Reorder stats cmd

---

ironfish-cli/package.json
yarn.lock

`yarn audit` found 49 high-severity and 3 moderate-severity vulnerabilities in our dependencies (see [IFL-1093](https://linear.app/if-labs/issue/IFL-1093) for details). This PR updates them all.
These changes are the result of a mix of using `npx yarn-audit-fix`, and manually fixing the `@aws-sdk` dependency versions.
* `yarn audit` reports no problem
* node can start and operating correctly
* tests pass successfully
N/A
N/A

Update dependencies to fix vulnerabilities found by `yarn audit`

---

ironfish/src/utils/bench.ts
ironfish/src/utils/math.ts

This function does a few things:
- Has a configurable warm-up period, to settle V8 hot-path optimizations and whatever else
- Has a configurable number of iterations which is used to collect aggregate information
- Calculates the min, max, avg, median across the iterations. Does not include the warm-up iterations
- Renders the aggregate stats
Example usage:
``` typescript
const results = await BenchUtils.withSegmentIterations(10, 100, async () => {
const _x = await tsPool.decryptNotes(payload)
})
const title = `[DecryptNotes: workers: ${test.workers}, notes: ${
test.notes
}, canDecrypt: ${test.canDecrypt.toString()}]`
console.log(BenchUtils.renderSegmentAggregate(results, title))
```
Example output:
```
[DecryptNotes: workers: 1, notes: 5, canDecrypt: true]
Iterations: 100
Time: min: …
```

test: Add an improved benchmark util for typescript

---

ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts

submitBlockTemplate calls verifyBlock and returns INVALID_BLOCK if verification fails. if verification succeeds, then submitBlockTemplate calls addBlock.
addBlock also calls verifyBlock (by way of connect, addHeadToChain, and verifyBlockAdd), so the first verification call is unnecessary.
removes the first block verification and the INVALID_BLOCK result.
- update existing unit test
```
[ ] Yes
```
```
[ ] Yes
```

removes extra block verification on submitted blocks

---

ironfish-cli/src/commands/service/stats.ts

Log chain db size in stats cmd
locally run yarn start service:stats
```
[ ] Yes
```
```
[ ] Yes
```
@danield9tqh

Log chain db size in stats 

---

ironfish/src/mining/manager.ts

when creating a new block template the mining manager collects a list of transactions to include in the block.
the mining manager iterates over transactions in the mempool, verifies the spends in the transactions, and tracks the total size and total fee from included transactions.
we iterate over the list of included transactions twice after collecting them: once to read the fee from the transaction and again to sum the fees.
these changes remove the extra iterations over included transactions. performance gains will be neglible.
```
[ ] Yes
``` …

removes loops from getNewBlockTransactions

---

.github/workflows/rust_ci.yml
Cargo.lock
ironfish-rust/Cargo.toml
ironfish-rust/src/assets/asset_identifier.rs
ironfish-rust/src/errors.rs
ironfish-rust/src/keys/ephemeral.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/public_address.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/merkle_note.rs
ironfish-rust/src/merkle_note_hash.rs
ironfish-rust/src/note.rs
ironfish-rust/src/sapling_bls12.rs
ironfish-rust/src/test_util.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/utils.rs
ironfish-rust/src/witness.rs
ironfish-zkp/Cargo.toml
ironfish-zkp/src/bin/generate_params.rs
ironfish-zkp/src/circuits/mint_asset.rs
ironfish-zkp/src/circuits/output.rs
ironfish-zkp/src/circuits/spend.rs
ironfish-zkp/src/circuits/util.rs
ironfish-zkp/src/constants.rs
ironfish-zkp/src/primitives/value_commitment.rs
ironfish-zkp/src/util.rs

This reverts commit 77b21e260a6444e928521edca00145bf73aa29dc.
This was working before, but something has changed such that our x86 darwin builds are not working. Testing x86 darwin locally appears to work just fine, so it's unclear what the issue is. It's possible that something in the build CI jobs has changed, a version or something, but nothing seemed immediately obvious and we don't want to hold up the release until we figure it out.
See https://github.com/iron-fish/ironfish/actions/runs/5269744219
Green build on this PR: https://github.com/iron-fish/ironfish/actions/runs/5272051494
related documentation pull request for the …

Revert "Blstrs (#3922)"

---

ironfish/src/mining/poolMiner.ts

the poolMiner only updates its target when it receives a 'set_target' message, and not when it receives new work from the pool.
the pool only sends 'set_target' when the miner first connects, so a pool miner uses the same target for the duration of its connection.
the miner outputs a log message with its target each time it receives new work, but this is misleading.
updates the pool miner message to output a slice of the header sent for new work, which matches the log output of the pool when it sends new work.
Closes #3839 
```
[ ] Yes
```
Is this a breaking change? If yes, add notes …

updates poolMiner log message on new work

---

ironfish-cli/src/commands/mempool/transactions.ts
ironfish-cli/src/commands/peers/banned.ts
ironfish-cli/src/commands/peers/index.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/notes.ts
ironfish-cli/src/commands/wallet/transactions.ts

in many of our CLI command that use oclif tables we include the 'sort' flag. however, if we are displaying streamed responses in a table then the sort flag doesn't work because each response is a separate table.
- removes 'sort' flag from commands where it can't be used
- adds message if 'sort' is used along with 'follow' and can't be supported in peers commands
- removes default setting of 'STATE' for sort in peers command: the table flags are global, so this was being applied to every command that includes the sort flag
Relates to #3944
```
[ ] Yes
``` …

fixes usage of oclif table sort flag

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/mining/manager.ts

Miners are getting the error message `Error creating block template: Cannot create a block with a previous header that does not match` when the head changes during a template creation. This is sometimes expected behavior so when it is we don't want to surface this error to users
```
[ ] Yes
```
```
[ ] Yes
```

Fix error message when chain head changes

---

.github/workflows/ci.yml

Currently, there is no check for fixtures when new tests are added. By checking for fixture changes during CI, we won't forget to check in the fixtures anymore.
Closes IFL-1113
CI run with a placeholder test with a missing fixture: 
https://github.com/iron-fish/ironfish/actions/runs/5323380651
```
[ ] Yes
```
```
[ ] Yes
```

feat(ci): Check for missing test fixtures

---

ironfish/package.json
ironfish/src/blockchain/blockchain.test.perf.ts
ironfish/src/mining/manager.test.perf.ts
ironfish/src/primitives/transaction.test.perf.ts
ironfish/src/workerPool/tasks/workerMessages.test.perf.ts

Only generate test report for `yarn test:perf:report`
`yarn test:perf` will print the same result as before
`yarn test:perf:report`
`yarn test:perf`
```
[ ] Yes
```
```
[ ] Yes
```
@mat-if

Add back print result

---

.github/pull_request_template.md
ironfish/src/blockchain/blockchain.test.perf.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/mining/manager.ts
ironfish/src/workerPool/tasks/workerMessages.test.perf.ts

Remove the expect check in perf tests
yarn test:perf
```
[ ] Yes
```
```
[ ] Yes
```
@mat-if

Remove expect check in perf tests

---

.github/workflows/build-ironfish-rust-nodejs.yml

GitHub CI runs now include a step to print CPU features before running the builds. This is useful because, as we have seen, the GitHub fleet uses a mix of CPUs in their fleet, and those features may be auto-detected by some build scripts and result in different build artifacts.
This works for Linux, MacOS and Windows. I couldn't find a way to make Windows print all the features, but we have the model, which can be used to guess what features may be available at build time.
Test run: https://github.com/iron-fish/ironfish/actions/runs/5339615241
Note the new "Record CPU information" step at the beginning of each build.
Example outputs (truncated):
*   Linux:
```
▸ Run cat /proc/cpuinfo
processor   : 0
vendor_id   : GenuineIntel
cpu family  : 6
model       : 79
model name  : Intel(R) Xeon(R) …
```

Record CPU information during GitHub CI runs

---

.github/workflows/rust_ci.yml
ironfish-rust/Cargo.toml
ironfish-zkp/Cargo.toml

Blstrs builds using CPU instructions that may not be present on older hardware. Github Actions hardware pool has some of this older hardware, leading to broken builds in some cases.
Rust benchmarks on a c6i.large (2vCPU, 4gb RAM)
```
asset::new
STAGING : 142.64 µs
PORTABLE: 97.957 µs
BLSTRS  : 89.686 µs
asset::new_with_nonce
STAGING : 65.369 µs
PORTABLE: 44.218 µs
BLSTRS  : 40.830 µs
merkle_note::decrypt_note_for_spender
STAGING : 866.14 µs
PORTABLE: 765.79 µs
BLSTRS  : 700.06 µs
merkle_note::decrypt_note_for_owner
STAGING : 788.39 µs
PORTABLE: 719.39 µs
BLSTRS  : 659.66 µs
sapling_key::generate_key
STAGING : 268.66 µs
PORTABLE: 259.10 µs
BLSTRS  : 236.38 µs
transaction::simple
STAGING : 9.0264 s
PORTABLE: 8.1176 s
BLSTRS  : 6.3045 s
transaction::all_descriptions
STAGING : 10.753 s …
```

fix(rust,zkp): Utilize portable flag for blstrs

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts

optimistically sends new block templates to connected clients (miners and pools) before block verification.
we currently verify a block before sending the template out. however, if the block verification fails, then the node will crash.
block verification takes time, and miners could be mining on an old template or an empty template while verification runs. instead, we can send out the template(s) as quickly as possible and verify afterwards.
- makes block verification optional in newBlock
- does not verify block for empty block template
- verifies 'full' template after sending it out to clients
- re-sends empty template if verification of full template fails
- performance testing, time from block connect to template stream:
- staging: ~13-18ms for empty, ~1200-1600ms …

verifies block template after streaming

---

ironfish-cli/src/commands/browse.ts
ironfish-cli/src/utils/index.ts
ironfish-cli/src/utils/platform.ts
ironfish/src/platform.ts

This new command will attempt to open your data dir in your gui file explorer. The purpose is to make it easier to discover where your config and data directory is. I added support for the 2 systems I know what the finder process is. Others can submit PR's to add support for their environment.
Run `ironfish browse` on your platform.
```
[x] Yes
```
https://github.com/iron-fish/website/pull/468
```
[ ] Yes
```

Add browse CLI command

---

ironfish/src/workerPool/job.test.slow.ts
ironfish/src/workerPool/job.ts
ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/worker.ts

the worker pool tracks the state of a job by assigning it a status and by assigning it to a worker. that assignment, placing the job in the worker's jobs map, occurs before sending the job to the worker. the job's status is also set to 'executing' before sending the job to the worker thread.
if an error occurs in sending the job to the worker, such as when serializing the job, then we do not reset these statuses: the job is left in an 'executing' state even though it is not executing, and the worker keeps the job in its map even though it never received it.
at this point the worker pool will not assign any more jobs to that worker.
- catches errors from 'worker.send' and sets the job status to 'error'
- moves assignment of the job to the worker's data structures to 'job.execute' and only …

handles errors sending jobs to worker threads

---

ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.ts

This brings it inline with our other APIs, and makes it more extensible. This is in preparation for adding another argument to this function too. It also makes it more backwards compatible for consumers of the SDK, because adding new parameters won't break existing users.
Just a type change, so we only need to run tests.
```
[x] Yes
```
Anyone using the SDK that was calling Wallet.send() will need to update their callsites.

Change Wallet.send() to accept an object

---

ironfish/src/workerPool/tasks/submitTelemetry.ts

some node runners have seen telemetry jobs failing when a telemtry attempts to serialize a field that's expected to be an integer.
rounds numeric values for integer fields.
adds additional details to error messages for TypeErrors when serializing telemetry fields.
```
[ ] Yes
```
```
[ ] Yes
```

adds context to telemetry TypeErrors

---

.github/workflows/ci.yml
.gitignore
ironfish/jest.setup.env.js
ironfish/src/blockchain/blockchain.test.perf.ts
ironfish/src/mining/manager.test.perf.ts
ironfish/src/primitives/transaction.test.perf.ts
ironfish/src/testReporter/testReporter.ts
ironfish/src/testUtilities/utils.ts
ironfish/src/utils/bench.ts
ironfish/src/workerPool/tasks/workerMessages.test.perf.ts

- Add influx csv annotation to test report, this makes the data format compatible with influx rules, see https://docs.influxdata.com/influxdb/latest/reference/syntax/annotated-csv/?_gl=1*9jmu3q*_ga*MTI2Nzk0MjkwMS4xNjg0ODc2Mjc1*_ga_CNWQ54SDD8*MTY4NzgwMjQ3Ny42MC4xLjE2ODc4MDg0NTEuNTMuMC4w
- Add influx set up in github CI, upload test reports to Influx
- Wrap the console log in perf test in a util function 
- Jest test reporter makes the console log in verbose form, set global console before each test in jest config
yarn test:perf
yarn test:perf:report
```
[ ] Yes
``` …

Add annotation to test report

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/event/index.ts
ironfish/src/rpc/routes/event/onReorganizeChain.ts

streams the block headers for the old head, the new head, and header for the point of the fork: the block at which the two forks diverged
adds an event to the blockchain reorganizeChain method to emit these headers on each reorg
supports monitoring chain reorgs over time
- ran two nodes with two miners to create forks
- connected to RPC endpoint and logged events
```
[ ] Yes
```
```
[ ] Yes
```

adds event/onReorganizeChain RPC

---

.github/workflows/ci.yml
.github/workflows/perf_test.yml

Move perf test to separate workflow, so it will only trigger on :
push to staging and master
PR on master
github workflow
```
[ ] Yes
```
```
[ ] Yes
```
@danield9tqh

Move perf test to separate workflow

---

ironfish/src/assets/assetsVerificationApi.test.ts
ironfish/src/assets/assetsVerificationApi.ts
ironfish/src/assets/assetsVerifier.test.ts
ironfish/src/assets/assetsVerifier.ts
ironfish/src/assets/index.ts
ironfish/src/index.ts
ironfish/src/node.ts

This is a new system that periodically pulls information about verified assets. The main class is `AssetsVerifier`, which can be used like this:
```typescript
const assetsVerifier = new AssetsVerifier(...options)
assetsVerifier.start() // fetch assets verification information and refresh them every 6 hours
assetsVerifier.verify(assetId) // returns one of:
// - { status: 'unknown' }
// - { status: 'verified' }
// - { status: 'unverified' }
```
For now this system is always enabled in the node, and cannot be configured or turned off. These features will come in future pull requests, together with support for persistent caching, local lists, better error handling with retries, and more.
- Unit tests
- Start the node and verify that the new system is running and refreshing itself at a regular …

Initial implementation of the AssetsVerifier system

---

.github/workflows/perf_test.yml

Adds the ability to run the github action on demand, so we can run it on branches prior to merging to staging. Also disables uploading the data to influx if they are ran this way.
```
[ ] Yes
```
```
[ ] Yes
```

feat(ci): add ability to run the perf tests on demand

---

ironfish/src/assets/assetsVerificationApi.ts
ironfish/src/assets/assetsVerifier.test.ts
ironfish/src/assets/assetsVerifier.ts

Changed the error to a warning (suggested by @NullSoldier on https://github.com/iron-fish/ironfish/pull/3993), and added two debug statements to know when the list is getting fetched.
- start the node with `--verbose` and observe the "downloading"/"refreshing" messages appearing in the logs
- cause the API to be unreachable and observe the warning
No doc change required.

Improve logging in the assets verifier system

---

.github/workflows/perf_test.yml

Perf test workflow stuck at influxdb set up step after changed to run on mac mini. 
Initial error is 
```
/Users/ironfish/actions-runner/_work/_actions/influxdata/influxdb-action/v3/install-influxdb.sh: line 12: wget: command not found
tar: Error opening archive: Failed to open 'influxdb2-2.6.0-linux-amd64.tar.gz'
```
After installing wget on the mac mini, it still stuck on the same step without any error
see https://github.com/iron-fish/ironfish/actions/runs/5405690415/jobs/9821580327
I manually installed influx cli on the mac mini, so we can remove this step in the github workflow
run it in the github action
related documentation …

Remove influx set up step in Github workflow

---

ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts
ironfish/src/wallet/wallet.ts

This RPC did not support passing feeRate to this RPC. I restructured it so it's now supported.
```
[x] Yes
```

Add feeRate to RPC Wallet/sendTransaction

---

ironfish-cli/src/commands/debug.ts
ironfish/src/fileStores/config.ts
ironfish/src/node.ts
ironfish/src/testUtilities/nodeTest.ts

Users can now enable or disable the verified assets feature by setting `enableAssetVerification`. By default, this is `true`.
Observe that:
- when `enableAssetVerification` is `true` (default), the RPC endpoints return either "verified" or "unverified"
- when `enableAssetVerification` is `true` (default), the RPC endpoints return "unknown"
Also check the output of `ironfish debug`.
```
$ ironfish start --rpc.http
$ ironfish start debug
Asset Verification enabled       true
$ curl -s http://localhost:8021/wallet/getBalance | jq
{
"assetVerification": {
"status": "unverified"
},
}
$ ironfish config:set enableAssetVerification false
$ ironfish debug
Asset Verification enabled       false
$ curl -s http://localhost:8021/wallet/getBalance | jq
{
"assetVerification": {
"status": "unknown"
},
} …
```

Add a configuration value for enabling/disabling the asset verification system

---

ironfish/src/assets/assetsVerificationApi.ts
ironfish/src/fileStores/config.ts
ironfish/src/node.ts

The new configuration parameter `assetVerificationApi` can be used to change the API URL.
Changing this configuration value requires the node to be restarted in order for the change to be picked up. This is consistent with the behavior of other similar parameters like `telemetryApi`.
Start the node and observe the default URL:
```
$ ironfish start --verbose |& grep -w verified
Downloading list of verified assets from https://api.ironfish.network/assets?verified=true
```
Change the config, restart the node, and observe the new URL:
```
$ ironfish config:set assetVerificationApi https://testnet.api.ironfish.network/assets?verified=true
$ ironfish start --verbose |& grep -w verified
Downloading list of verified assets from https://testnet.api.ironfish.network/assets?verified=true
```
Config …

Add a configuration value for customizing the asset verification URL

---

ironfish/src/fileStores/config.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/connections/webRtcConnection.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/node.ts

We currently use Twilio and Google as STUN servers to facilitate WebRTC. If users are not confortable with this we should give them the option to use another server (possibly in the future a team run server). Making this configurable for now
Tested locally + unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Make STUN servers configurable

---

.github/workflows/perf_test.yml

The influx config only need to be created once since its running on the same machine. Remove that command in Github workflow
Solving the error in GH workflow https://github.com/iron-fish/ironfish/actions/runs/5409999241/jobs/9830857314
`Error: failed to create config "ghaction": config "ghaction" already exists` 
Run GH workflow
```
[ ] Yes
```
```
[ ] Yes
```
@mat-if @danield9tqh

Remove creating influx config in GH Workflow

---

.github/workflows/perf_test.yml

Auth credential is already set in env variables. Based on the doc https://docs.influxdata.com/influxdb/cloud/reference/cli/influx/write/#examples, no need to pass in from the cli flags.
When we pass both, it also cause the error 
```
Error: ambiguous org: use OrgId or OrgName, but not both. OrgID: fdcfe96f6c31245a, OrgName: fdcfe96f6c31245a
```
locally run  influx write --bucket ironfish-telemetry-mainnet --format=csv --file /Users/yajun/ironfish/ironfish/ironfish/test-reports/manager.test.perf.csv
gh workflow
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why …

Use env vars for Influx Auth credentials

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/walletdb/accountValue.ts

Makes `AccountImport.name` optional, this will enable encoders/decoders to use this type. Related to:
https://github.com/iron-fish/ironfish/pull/4011
unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(ifl-1233): account name optional

---

.github/workflows/perf_test.yml

The workflow is stuck at post rust cache step 
https://github.com/iron-fish/ironfish/actions/runs/5425262695/jobs/9865787228
At rust cache step, it has
```
... Restoring cache ...
No cache found.
```
It seems this step is not needed to run on mac mini.
gh workflow
```
[ ] Yes
```
```
[ ] Yes
```
@mat-if

Remove rust cache step in perf test workflow

---

ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/walletdb/accountValue.ts

Adds encoder options to encoder/decoders
tests/lint pass
```
[ ] Yes
```
```
[ ] Yes
```

feat: encoder options for AccountEncoder type

---

.github/workflows/check-pr-branch.yml

This will fail if the PR has a base branch of master and does not contain the word master in the PR title. This still allows release PRs and other emergency PRs, while creating a quick and easy check to make sure PRs aren't accidentally going into master.
I wanted the override keyword to be "MASTER", but the github actions expressions treat strings as case-insensitive, so good enough for now.
Tested this on a small repo: https://github.com/mat-if/libuv-playground/actions/workflows/testing.yml
```
[ ] Yes
``` …

feat(ci): Add a lint check for PRs against master

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/wallet/walletdb/accountValue.ts

pushes serialization of createdAt as HeadValue to the RPC; serialization of the block hash as a hex string is only needed for sending RPC responses
makes createdAt type uniform across AccountImport and AccountValue
closes IFL-1259
```
[ ] Yes
```
```
[ ] Yes
```

adds separate RpcAccountImport type

---

ironfish/src/typedefs/bufio.d.ts
ironfish/src/wallet/account/encoder/bech32json.test.ts
ironfish/src/wallet/account/encoder/bech32json.ts
ironfish/src/wallet/account/encoder/json.test.ts
ironfish/src/wallet/account/encoder/json.ts
ironfish/src/wallet/account/encoder/mnemonic.test.ts
ironfish/src/wallet/account/encoder/mnemonic.ts
ironfish/src/wallet/account/encoder/spendingKey.test.ts
ironfish/src/wallet/account/encoder/spendingKey.ts

Adds `Encoder`s for the existing account export types:
- spendingKey
- mnemonic
- JSON
- Bech32m JSON
These encoders throw instead of return null as this removes opinion about what should be done with returned encoder value. 
These will be used when we update the CLI code to import these encoders, rather than containing the code explicitly.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

feat(ifl-1233): create existing encoders

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/utils/asset.test.ts
ironfish-cli/src/utils/asset.ts
ironfish/src/utils/buffer.ts
ironfish/src/utils/index.ts
ironfish/src/utils/string.ts

Verified assets are now displayed in green and with a checkmark in the output of `wallet:assets`, `wallet:balance`, and `wallet:balances`. The output of `wallet:balances` is also sorted to display verified assets before other assets.
The output of these commands when passing `--output=csv|json|yaml` is unchanged.
The asset name may get truncated when getting printed in a table cell. This can happen, for example, when running `wallet:balances` when the terminal window is too narrow. If the name of a verified asset gets truncated, the ANSI escape sequence that makes the text color go from green to normal may get truncated too. As a consequence of that, the green color may "spill" over the rest of the output, making other unverified assets appear as green too.
This is a bug in oclif, which …

Highlight verified assets in the output of cli commands

---

ironfish/src/typedefs/bufio.d.ts
ironfish/src/wallet/account/encoder/bech32.test.ts
ironfish/src/wallet/account/encoder/bech32.ts
ironfish/src/wallet/walletdb/accountValue.ts

encodes account data as a buffer by concatenating fields together before encoding the hex string using bech32.
copies buffer encoding pattern from walletdb/accountValue
adds unit tests
```
[ ] Yes
```
```
[ ] Yes
```

implements bech32 account encoder

---

.github/workflows/check-pr-branch.yml

This wasn't changing back to green when the base branch changes because it would only run if the base branch is main. Therefore, we'll need to run it on all PRs, and check if the branch is master alongside the keyword in the job if-expression.
```
[ ] Yes
```
```
[ ] Yes
```

fix(ci): Base branch check should update to green if base changes

---

ironfish-rust-nodejs/package.json
ironfish/package.json

We use node version 18, but our node-app is stuck using version 16. This just formalizes what we already know. We need to support at least version 16 for now in our rust and SDK package.
Run tests on Github CI.

Set SDK node compatability to >=16

---

ironfish/src/wallet/account/encoder/account.test.ts
ironfish/src/wallet/account/encoder/account.ts
ironfish/src/wallet/account/encoder/bech32.test.ts
ironfish/src/wallet/account/encoder/bech32.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/account/encoder/json.ts
ironfish/src/wallet/account/encoder/mnemonic.ts

Adds `encodeAccount/decodeAccount` which can be used in place of the individual encoders to:
1. Always use recommended encoder from SDK
2. Try all decoders on string instead of trying each encoder
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

feat(ifl-1237): encodeAccount/decodeAccount generalized functions

---

ironfish/src/wallet/account/encoder/account.test.ts
ironfish/src/wallet/account/encoder/bech32.ts
ironfish/src/wallet/account/encoder/bech32json.ts
ironfish/src/wallet/account/encoder/json.ts

If the `option->name` is passed to a `decoder`, we should rename the corresponding account in the `AccountImport`
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

feat(ifl-1263): support account rename decoding

---

ironfish/src/metrics/meter.ts

`Date` does not use a monotonic clock and it may jump in the past, or in the future. At such, it's not a good candidate for measuring performance. This PR switches from using `Date` to using `performance`, which has the following advantages:
- **`performance.now()` is a monotonic clock**: it cannot travel in the past, and it is not subject to system adjustments
- `Date.now()` has millisecond precision and resolution, `performance.now()` has microsecond resolution, and high precision depending on the platform
- Both `Date.now()` and `peformance.now()` return a timestamp in milliseconds; the difference is that `Date.now()` is an integer, `performance.now()` is a floating-point number (and this is ok because the code that uses the timestamp does floating-point arithmetic on it, so no code …

Use `performance.now()` instead of `Date.now()` for performance measurements

---

ironfish/src/assets/assetsVerificationApi.ts
ironfish/src/assets/assetsVerifier.test.ts
ironfish/src/assets/assetsVerifier.ts
ironfish/src/fileStores/fileStore.ts
ironfish/src/fileStores/index.ts
ironfish/src/fileStores/keyStore.ts
ironfish/src/fileStores/verifiedAssets.ts
ironfish/src/node.ts

The verified assets cache is now stored in `$DATADIR/cache/verified-assets.json` (default on *nix: `~/.ironfish/cache/verified-assets.json`).
- The cache is saved only when the API returns new data.
- The cache file can be safely removed at any time. It will be rewritten at the next update from the API, or the next node restart.
- The cache file may be corrupted. In that case, the node will ignore it and move one.
- Note though that if the cache file contains invalid data (e.g. `assetIds` is set to a number instead of an array), this may result in exceptions that will prevent the node from starting.
- Restarting the node causes the cache to be immediately revalidated, regardless of how long has passed since the last revalidation. A future PR may improve this by storing the last …

Verified assets: implement persistent caching

---

ironfish-cli/src/commands/wallet/export.ts
ironfish/src/wallet/account/index.ts
ironfish/src/wallet/index.ts

removes account encoding logic from export CLI and uses the exportAccount RPC to encode accounts in the desired format instead
```
hughy@Hughs-MacBook-Pro ironfish % fish wallet:export test
yarn run v1.22.18
$ yarn build && yarn start:js wallet:export test
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:export test
ifaccount1xqcnqvpsxsmngd34xuenwdry8qukyepsxu6rgdpkx5erzwrzvyerjvtpvgexgwfkxqukvvmzv5exyce5x56nzvmpxyek2drzvyurxc3ex93rgvfexesnxdtx8qmr2dtxvvuk2d35x5crxwfhxg6n2vnzxc6rwctpv5crswfnvvmnjdfkxp3rgve5v3nrxc3j8ymrgde4xguxywtzv3nrgvphxfjrjcm9xsmnvdekx9nxxefhvyerwetzvc6nxerpvyuxzde4893kgdtzvc6rzdnpvgmrxvf4xy6nzv3sxesnxce4x5mkycf3vvcxxdfexe3rjdpsxpjrqcenvsurxvt9x5ukzcfh8qcrvd …
```

updates export CLI for RPC changes

---

ironfish/src/assets/assetsVerifier.test.ts
ironfish/src/assets/assetsVerifier.ts

When the command line client is running but not connected to any node, use the persisted cache (if present) to get and display verified assets information.
- Start the node so that it can fetch the verified assets information and write the cache to disk (this requires https://github.com/iron-fish/ironfish/pull/4020)
- Stop the node
- Run `ironfish wallet:balances`, or similar commands
Expected behavior: verified assets should appear as green with a checkmark.
No doc change needed.

Verified assets: use the persisted cache when the node is not running

---

ironfish/src/fileStores/verifiedAssets.ts

Reuse the already-existing `temp` directory instead of creating a new `cache` directory.
Launch the node and observe the `$DATADIR/temp/verified-assets.json` file appearing.
No doc change required

Verified assets: place the cache in the `temp` directory

---

ironfish/src/assets/assetsVerificationApi.test.ts
ironfish/src/assets/assetsVerificationApi.ts

People can now use local files as their source for verified asset information.
```
$ cat <<EOF > /tmp/assets.json
{
"data": [ {"identifier": "51f33a2f14f92735e562dc658a5639279ddca3d5079a6d1242b2a588a9cbf44c"} ]
}
EOF
$ ironfish config:set assetVerificationApi file:///tmp/assets.json
$ ironfish start
$ ironfish wallet:balances
```
No doc change required

Verified assets: add support for `file:///` URIs as the source of verified assets

---

ironfish/src/wallet/account/encoder/account.ts

Rolls up errors from attempted decoders.
```
fish wallet:import
Paste the output of wallet:export, or your spending key: own bicycle nasty chaos type agent amateur inject cheese spare poverty charge ecology portion frame earn garden shed bulk youth patch sugar physical family
Account could not be decoded, decoder errors:
JsonEncoder: Unexpected token o in JSON at position 0
MnemonicEncoder: Name option is required for mnemonic key encoder
SpendingKeyEncoder: Name option is required for spending key encoder
Bech32JsonEncoder: Invalid bech32 JSON encoding
Bech32Encoder: Could not decode account own bicycle nasty chaos type agent amateur inject cheese spare poverty charge ecology portion frame earn garden shed bulk youth patch sugar physical family using bech32 
```
Does this change require …

fix: roll up errors from decodeAccount function

---

ironfish/src/wallet/account/encoder/account.test.ts
ironfish/src/wallet/account/encoder/account.ts
ironfish/src/wallet/account/encoder/bech32.ts
ironfish/src/wallet/account/encoder/bech32json.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/account/encoder/json.ts
ironfish/src/wallet/account/encoder/mnemonic.ts
ironfish/src/wallet/account/encoder/spendingKey.ts

This introduces `DecodeFailed` and `DecodeInvalid`. The former error will not cause `decodeAccount` to panic. If we have a valid account but the import process fails for some reason, we throw an `DecodeInvalid` which will raise an exception rather than passing through.
```
fish wallet:import --name ffff                                                                                                                                                                                                                           
Paste the output of wallet:export, or your spending key: own bicycle nasty chaos type agent amateur inject cheese spare poverty charge ecology portion frame earn garden shed bulk youth patch sugar physical family
Account ffff imported.
Run "ironfish wallet:use ffff" to set …
```

fix: decode error bubbling

---

ironfish/src/assets/assetsVerificationApi.test.ts
ironfish/src/assets/assetsVerificationApi.ts
ironfish/src/assets/assetsVerifier.test.ts

Change the assets verifier to use the new API endpoint introduced by https://github.com/iron-fish/ironfish-api/pull/1572.
```
$ # if running the api locally
$ ironfish config:set assetVerificationApi http://localhost:8003/assets/verified
$ ironfish start --verbose |& grep asset
```
Observe the endpoint being properly queried without errors.
No doc change required

Verified assets: use the new `/verified/assets` API endpoint

---

ironfish/src/wallet/account/encoder/account.ts
ironfish/src/wallet/account/encoder/bech32.ts
ironfish/src/wallet/account/encoder/bech32json.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/account/encoder/json.ts
ironfish/src/wallet/account/encoder/mnemonic.ts
ironfish/src/wallet/account/encoder/spendingKey.ts

I think it makes sense for the DecoderFailed error to contain the name of the decoder that it was produced from. It also makes the code a bit simpler when you are relying on accumulating errors, but need a new wrapper type because you lose the encoder name in the error.
```
[ ] Yes
```
```
[ ] Yes
```

Add encoder name to DecoderFailed

---

ironfish/src/rpc/routes/chain/__fixtures__/broadcastTransaction.test.ts.fixture
ironfish/src/rpc/routes/chain/broadcastTransaction.test.ts
ironfish/src/rpc/routes/chain/broadcastTransaction.ts

the chain/broadcastTransaction RPC endpoint can be used to prompt a node to broadcast a valid posted transaction over the network.
however, the endpoint does not add the transaction to the node's mempool before broadcasting. the transaction should be added to the mempool for parity with the wallet's broadcast implementation.
```
[ ] Yes
```
```
[ ] Yes
```

adds transactions to mempool in broadcastTransaction rpc

---

ironfish/src/rpc/routes/wallet/burnAsset.ts

If an account is burning an asset, it should have the asset in its database. This reduces dependency on the chain.
Covered by existing behavior
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Query account instead of chain when burning asset

---

ironfish/src/rpc/routes/wallet/getAccountTransaction.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.ts
ironfish/src/rpc/routes/wallet/utils.ts

Use the wallet database when calculating asset balance deltas
Covered by existing behavior
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Query account in `getAssetBalanceDeltas`

---

ironfish/src/rpc/routes/wallet/getAccountNotesStream.ts

The assets related to an account's notes should be present in the wallet database, so reduce chain dependency.
Covered by existing behavior
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Query asset from account in `getAccountNotesStream`

---

ironfish/src/fileStores/config.ts

running a standalone wallet requires config options for the wallet's RPC connection to a node, for the wallet's RPC server, and for the wallet's worker pool
adds config options to the Config store and sets default values:
- sets default options for wallet node RPC connections to mirror node RPC server defaults
- sets defaults for wallet RPC server to match defaults for node RPC server
- uses separate default IPC filepath for wallet RPC server
- uses separate default TLS files for wallet RPC server
- uses distinct port for each TCP and HTTP server
- uses same defaults for wallet worker pool as node worker pool
config options are defined, but not yet used
Reference](https://ironfish.network/docs/onboarding/rpc/chain …

adds standalone wallet config options

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/blockchain/index.ts

Adds a database layer to encapsulate read/writes/deletes. This diff focuses on only moving the `headers` store so the PR size doesn't get too large and moving `open`/`close` lifecycle methods.
```
[ ] Yes
```
```
[ ] Yes
```

refactor(ironfish): Encapsulate block header DB operations

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

moves expireTransactions from the eventLoop to the chainProcessor.onAdd handler function so that the wallet only expires transactions when a block is added to the chain
refactors expireTransactions to take a block sequence instead of reading a header from the chain thereby removing a chain dependency
updates unit tests and regenerates fixtures
```
[ ] Yes
```
```
[ ] Yes
```

expires wallet transactions on block connect

---

ironfish-cli/package.json
ironfish-rust-nodejs/npm/darwin-arm64/package.json
ironfish-rust-nodejs/npm/darwin-x64/package.json
ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json
ironfish-rust-nodejs/npm/linux-arm64-musl/package.json
ironfish-rust-nodejs/npm/linux-x64-gnu/package.json
ironfish-rust-nodejs/npm/linux-x64-musl/package.json
ironfish-rust-nodejs/npm/win32-x64-msvc/package.json
ironfish-rust-nodejs/package.json
ironfish/package.json
simulator/package.json

1.5.0 -> 1.6.0
Node builds and runs fine.
N/A
N/A

Bump node version to 1.6.0

---

.github/workflows/publish-binaries.yml

Uses `caxa` library to package `ironfish` cli into single executable binary.
Currently codesigning is not functional because of the way that caxa packages files onto the end of the `go` generated binary.
Testing artifact upload url was done by hardcoding this URL:
`# upload_url: https://uploads.github.com/repos/iron-fish/ironfish/releases/111185314/assets?name=${{ steps.set_paths.outputs.zip }}`
Tested locally with `act` 
https://github.com/nektos/act
Used command:
`act --artifact-server-path /tmp/artifacts --container-architecture linux/amd64 -W .github/workflows/publish-binaries.yml`
Tested binary on local machines:
Linux
```
blue@blue-Standard-PC-Q35-ICH9-2009:~/Downloads$ wget https://release.ironfish.network/0.1.76/linux_amd64/ironfish
--2023-04-17 15:42:27-- …
```

feat: create ironfish binary

---

ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

moves rebroadcastTransactions out of the wallet eventLoop and into the chain processor onAdd handler
passes the block sequence to rebroadcastTransactions to avoid reading from the chain
leaves transaction verification in for now pending changes to use broadcastTransaction RPC for broadcasting from wallet
- updates unit tests
```
[ ] Yes
```
```
[ ] Yes
```

rebroadcasts on block connect

---

ironfish/src/rpc/routes/chain/getAsset.test.ts
ironfish/src/rpc/routes/chain/getAsset.ts

We need this field to be returned from the node client in the wallet.
Unit test
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add `nonce` to `chain/getAsset`

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/assetValue.test.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/migrations/data/023-wallet-optional-spending-key.ts
ironfish/src/migrations/data/028-backfill-assets-owner.ts
ironfish/src/migrations/data/028-backfill-assets-owner/new/assetValue.ts
ironfish/src/migrations/data/028-backfill-assets-owner/new/index.ts
ironfish/src/migrations/data/028-backfill-assets-owner/old/assetValue.ts
ironfish/src/migrations/data/028-backfill-assets-owner/old/index.ts
ironfish/src/migrations/data/028-backfill-assets-owner/stores.ts
ironfish/src/migrations/data/index.ts

**Relies on #4075**
This adds an owner field to the asset DB alongside the now-renamed creator field. This is to store the current owner of an asset, whenever that changes, so we have the current owner and can verify the proof properly with the correct owner.
Closes IFL-1325
```
[ ] Yes
```
```
[ ] Yes
```

[asset-security] feat: add asset owner field to chain DB

---

ironfish/src/node.ts
ironfish/src/rpc/clients/memoryClient.ts
ironfish/src/rpc/routes/router.test.ts
ironfish/src/sdk.test.ts
ironfish/src/wallet/wallet.ts

* Makes node and router nullable in memory client
* Passes memory client into wallet
Refactored null references in existing unit tests. Otherwise, covered by existing behavior.
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Pass memory client into wallet

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.ts

Fetch the witness of a note from the node client in the wallet. Additionally remove unused note tree size as we can rely purely on confirmations now.
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Fetch note witness from node client in wallet

---

ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/transactionFetcher.test.ts
ironfish/src/node.ts
ironfish/src/rpc/routes/event/onTransactionGossip.test.ts

For standalone wallet project we are adding a feature where a node can be running without running wallet. This would allow miners for example to run a mining node and not waste resources on running a wallet. For this we cannot blindly call wallet functions from the PeerNetwork assuming the wallet is started. This also provides a consistent callback function for syncing transactions to both the local wallet and any remote wallets listening to the node
Unit tests
```
[ ] Yes
``` …

Remove direct wallet dependency wallet from PeerNetwork

---

ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/memPool/memPool.ts
ironfish/src/node.ts
ironfish/src/rpc/routes/wallet/addTransaction.ts
ironfish/src/wallet/wallet.ts

Standalone wallet should know whether or not its creating invalid transactions based on consensus parameters like max block size and min transaction fee. It could query this information from a full node but reasonably it seems more efficient for the wallet to store its own consensus parameters. The downside is that wallet consensus params could become out of sync due to a hardfork. This might deserve some discussion but proposing this solution because it reduces RPC calls and removes need for adding additional verifyCreatedTransaction RPC endpoint
Unit tests
```
[ ] Yes
```
Is this a …

Store consensus on wallet and use it for wallet/addTransaction RPC

---

ironfish/src/rpc/routes/wallet/getAccountTransaction.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.ts
ironfish/src/rpc/routes/wallet/utils.test.ts
ironfish/src/rpc/routes/wallet/utils.ts

An incremental improvement towards not using the node inside wallet RPC calls
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

remove node dependencies in get transactions rpc

---

ironfish/src/rpc/routes/chain/followChainStream.ts

The only field in the Transaction primitive that uses the Rust Transaction is `unsignedHash`, and we no longer return that in followChainStream, so we don't have any need to create a Rust transaction when creating block responses for the chain stream. This improves block processing time by roughly 30% (Tested by scanning first 4000 blocks of skynet).
Tests should pass, and also modified `service:sync` to run against the local chain to verify performance changes.
```
[ ] Yes
``` …

Remove withReference from followChainStream

---

ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/rpc/routes/wallet/addTransaction.ts
ironfish/src/wallet/wallet.ts

removes onBroadcastTransaction event from wallet and uses node client and chain/broadcastTransaction RPC to broadcast transactions from the wallet during transaction creation, rebroadcast, and wallet/addTransaction
updates unit tests
```
[ ] Yes
```
```
[ ] Yes
```

uses node client to broadcast transactions

---

ironfish/src/node.ts
ironfish/src/wallet/wallet.ts

Transaction is already added to the mempool as part of `broadcastTransaction` and the onTransactionCreated callback is not used anywhere currently
Unit tests + simulation tests
```
[ ] Yes
```
```
[ ] Yes
```

Remove unused mempool and onCreateTransaction from Wallet

---

ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/version.rs
ironfish/src/primitives/mintDescription.ts
ironfish/src/primitives/transaction.ts
ironfish/src/wallet/wallet.test.ts

This PR introduces a new transaction serialization version: V2. When this new version is used, `MintDescription` gets a new optional field: `transferOwnershipTo`, which will be used to allow transferring the minting permission to an arbitrary account.
Unit tests
No doc changes needed yet as this is a purely internal change (not exposed through RPC).
This change is backward compatible, but using the new transaction version will introduce a hard fork in the network.

Add the `transferOwnershipTo` field to MintDescription

---

ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

the wallet depends on the chain for verifying transactions before rebroadcasting them. however, the chain/broadcastTransaction RPC verifies transactions during rebroadcast on the node
removes chain dependency from the wallet by removing wallet-side transaction verification during rebroadcast
```
[ ] Yes
```
```
[ ] Yes
```

removes wallet transaction verification during rebroadcast

---

ironfish/src/rpc/routes/chain/followChainStream.ts
ironfish/src/wallet/__fixtures__/remoteChainProcessor.test.ts.fixture
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/remoteChainProcessor.test.ts
ironfish/src/wallet/remoteChainProcessor.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

the standalone wallet will depend on a remote node running a ChainProcessor and sending block events over the chain/followChainStream RPC
the RemoteChainProcessor mimics the behavior of the ChainProcessor but uses chain/getChainInfo and chain/followChainStream to update
update uses chain/followChainStream to stream block events _until_ it reaches the head of the remote chain from the initial call
the onAdd and onRemove Events on the RemoteChainProcessor emit transaction data in addition to the block header since transaction data arrives in the RPC response with the block data
updates wallet methods and tests to accommodate the change in event interface
defines WalletBlockHeader and WalletBlockTransaction types to represent the data required from the RemoteChainProcessor to sync …

implements RemoteChainProcessor

---

ironfish/src/rpc/routes/wallet/addTransaction.test.ts
ironfish/src/rpc/routes/wallet/addTransaction.ts

The RPC call to chain/broadcastTransaction already adds the transaction to the mempool. This was added in https://github.com/iron-fish/ironfish/pull/4105 and https://github.com/iron-fish/ironfish/pull/4099. 
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Remove mempool dependency in wallet/addTransaction

---

ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

removes chain.iterateBlockHeaders in scanTransactions and replaces with an instance of RemoteChainProcessor
preserves 'locking' logic of existing implementation so that only one scanTransactions or updateHead call can run at a time
reads current chain head using getChainInfo at start of scan so that ScanState can track progress towards an end sequence
always updates the chainProcessor hash and sequence to those of the processor used for scanning after a scan finishes. this is because the scan will go to the current head of the remote node, which may be further than the chain processor
- updates unit tests
- manual testing:
- ran `wallet:rescan` and checked balances before and after …

refactors scanTransaction to use RemoteChainProcessor

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/network/messages/getBlockTransactions.test.ts
ironfish/src/network/messages/getBlocks.test.ts
ironfish/src/network/messages/getCompactBlock.test.ts
ironfish/src/network/messages/newCompactBlock.test.ts
ironfish/src/network/messages/newTransactions.test.ts
ironfish/src/network/messages/pooledTransactions.test.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/primitives/block.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/testUtilities/fixtures/transactions.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/walletdb/decryptedNoteValue.test.ts
ironfish/src/wallet/walletdb/transactionValue.test.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/postTransaction.test.ts
ironfish/src/workerPool/tasks/verifyTransactions.test.ts

updates the fixture to take a node instead of a wallet, use the wallet and the chain from the node
updates all tests that use this fixture to pass a node instead of a wallet
```
[ ] Yes
```
```
[ ] Yes
```

removes use of wallet.chain in useMinersTxFixture

---

ironfish/src/rpc/routes/wallet/__fixtures__/getAccountsStatus.test.ts.fixture
ironfish/src/rpc/routes/wallet/getAccountsStatus.test.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.ts
ironfish/src/wallet/wallet.ts

For `wallet/getAccountsStatus` command we return whether the node contains the account head or not. Moving this call to use a node client in the case of a standalone wallet
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Make remote call for account status

---

ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts
ironfish/src/wallet/wallet.ts

This makes 2 changes
1) No longer check whether the remote not is connected to the peer network before attempting to send a transaction. 
- Removing this check because the wallet can attempt rebroadcasting a transaction asynchronously so the node doesn't need to have peers for the transaction to eventually succeed
2) Checking the remote node to see if its head is synced instead of assuming there will always be a local node
Unit tests + local testing
```
[ ] Yes
``` …

Make remote call to node to see if its synced enough to create a tranaction

---

ironfish/src/node.ts
ironfish/src/rpc/routes/wallet/getAssets.ts
ironfish/src/rpc/routes/wallet/getBalance.ts
ironfish/src/rpc/routes/wallet/getBalances.ts
ironfish/src/wallet/wallet.ts

AssetsVerfier needs to be accessible in RPC calls to a standalone wallet
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Use assetsVerifier on wallet for RPC calls

---

ironfish/src/wallet/wallet.ts

uses chainHasBlock and the nodeClient to check if chainProcessor hash and account birthdays are in the chain instead of relying on a chain instance
```
[ ] Yes
```
```
[ ] Yes
```

removes uses of chain in wallet start

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/post.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish/src/primitives/transaction.test.slow.ts
ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/postTransaction.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.ts

* If `broadcast` is set to true in posting, return if the transaction was accepted into the mempool and broadcasted successfully
* Log out messages in CLI if either the transaction was not accepted or broadcasted
Unit tests and running CLI
```
[X] Yes
```
TODO @rohanjadvani 
```
[ ] Yes
```

feat(cli,ironfish): Log warning if errors happen during broadcast

---

ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/utils.rs

When switching from bellman to bellperson, the batch verification function changed. Previously, the proof verification would return a 
`Result` with `Err` in every error case and `Ok(())` otherwise, but now it returns `Err` in some error cases and `Ok(bool)` in cases where the proof 
can't be verified with the given proof verification key. This PR fixes this check and adds tests to verify the change.
Adds additional Rust tests and verifies that the tests failed before and pass with this change.
```
[ ] Yes
``` …

Fix checking result of proof verification and add tests

---

ironfish/src/migrations/data/000-template.ts
ironfish/src/migrations/data/014-blockchain.ts
ironfish/src/migrations/data/015-wallet.ts
ironfish/src/migrations/data/016-sequence-to-tx.ts
ironfish/src/migrations/data/017-sequence-encoding.ts
ironfish/src/migrations/data/018-backfill-wallet-assets.ts
ironfish/src/migrations/data/019-backfill-wallet-assets-from-chain.ts
ironfish/src/migrations/data/020-backfill-null-asset-supplies.ts
ironfish/src/migrations/data/021-add-version-to-accounts.ts
ironfish/src/migrations/data/021-add-version-to-accounts/schemaOld.ts
ironfish/src/migrations/data/022-add-view-key-account.ts
ironfish/src/migrations/data/023-wallet-optional-spending-key.ts
ironfish/src/migrations/data/024-unspent-notes.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash.ts
ironfish/src/migrations/data/026-timestamp-to-transactions.ts
ironfish/src/migrations/data/027-account-created-at-block.ts
ironfish/src/migrations/data/028-backfill-assets-owner.ts
ironfish/src/migrations/migration.ts
ironfish/src/migrations/migrator.ts
ironfish/src/rpc/routes/router.ts
ironfish/src/utils/node.ts
ironfish/src/walletNode.ts

This migration specifically depends on both the wallet and chain database. We want:
* This migration to run only for full nodes (node running with the wallet)
* This migration to not crash for standalone wallets
* This migration to not create a chain db file directory on a new standalone wallet start
Run migrations on existing and new data directories
```
[ ] Yes
```
```
[ ] Yes
```

refactor(ironfish): Check for backfill before opening db in migration 19

---

ironfish/src/fileStores/config.ts

Since we're moving to the concept of a wallet node and preventing a node / standalone wallet to run at the same time, we can re-use the existing config.
N/A
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Remove wallet specific config

---

ironfish-cli/src/commands/chain/benchmark.ts
ironfish-cli/src/commands/chain/repair.ts
ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/genesis/addGenesisTransaction.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/rpc/routes/chain/getNoteWitness.test.ts
ironfish/src/rpc/routes/chain/getNoteWitness.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/testUtilities/matchers/blockchain.ts

Spoke with @NullSoldier and decided to keep the original pattern of notes and nullifiers directly under the blockchain.
N/A
```
[ ] Yes
```
```
[ ] Yes
```

refactor(ironfish): Move notes and nullifiers from db to blockchain

---

ironfish/src/storage/database/errors.ts

swaps the current database version with the code database version in the error message:
```
Your database is newer than your node.
Your database is 27 and your node is 29.
```
changes to
```
Your database is newer than your node.
Your database is 29 and your node is 27.
```
manual testing
```
[ ] Yes
```
```
[ ] Yes
```

fixes error message when database is ahead of node

---

ironfish/src/fileStores/config.ts
ironfish/src/rpc/adapters/tlsAdapter.ts
ironfish/src/sdk.ts

* Add back node connection config flags
* Add rpc auth token config flag
* Add `walletNode` method to SDK
N/A, will be tested in a subsequent change
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add SDK method to create wallet node

---

ironfish/src/migrations/migrator.ts
ironfish/src/walletNode.ts

When checking if migrations have been applied or reverting, we can save some work by storing the databases on the migrator. This should never change throughout use of the migrator.
N/A
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Move databases to migrator constructor

---

ironfish-cli/src/commands/wallet/prune.ts
ironfish/src/utils/node.ts

allows standalone wallets to prune expired transactions and compact the walletDb
- manual testing with `wallet:prune`
```
[ ] Yes
```
```
[ ] Yes
```

uses WalletNode instead of FullNode in wallet:prune

---

ironfish/src/node.ts
ironfish/src/rpc/routes/wallet/addTransaction.ts
ironfish/src/rpc/routes/wallet/getAccountTransaction.ts
ironfish/src/rpc/routes/wallet/getAssets.ts
ironfish/src/rpc/routes/wallet/getBalance.ts
ironfish/src/rpc/routes/wallet/getBalances.ts
ironfish/src/rpc/routes/wallet/rescanAccount.ts
ironfish/src/wallet/wallet.ts
ironfish/src/walletNode.ts

This PR reverts some recent changes that passed down propertes like `assetsVerifier` to the `Wallet` simply so they could be accessed in RPC handlers. Now that we have the concept of a `WalletNode` these propoerties make more sense to live at the node level and not the `Wallet` since they are not being used internally in the `Wallet`
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Clean up unnecessary wallet properties

---

ironfish/src/rpc/routes/chain/__fixtures__/getBlock.test.ts.fixture
ironfish/src/rpc/routes/chain/getBlock.test.ts
ironfish/src/rpc/routes/chain/getBlock.ts

Adds serialization of `Transaction`s to `getBlock` RPC.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

feat: serialized transactions get block

---

Cargo.toml

The [v2 resolver](https://doc.rust-lang.org/cargo/reference/resolver.html#feature-resolver-version-2) is the default for crates using the 2021 Rust edition, but it's not the default for virtual workspaces. This commit enables the v2 resolver for all our crates.
Excerpt from [Default Cargo feature resolver](https://doc.rust-lang.org/edition-guide/rust-2021/default-cargo-resolver.html):
> If you are using a [virtual workspace](https://doc.rust-lang.org/cargo/reference/workspaces.html#virtual-manifest), you will still need to explicitly set the [`resolver` field](https://doc.rust-lang.org/cargo/reference/resolver.html#resolver-versions) in the `[workspace]` definition if you want to opt-in to the new resolver.
In fact, sometimes (but not always), when working crates I see the following …

Use Cargo resolver v2

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

avoids resetting account data due to network mismatch or missing forked blocks.
resets account birthday to null if the sequence is at or ahead of the head of the node's chain and the block hash is not in the node chain. this occurs when the birthday is on a fork or a different network.
if the birthday is on a different chain then it can't be used in scanning, so must be set to null.
moves check of account birthdays in 'start' to follow check of chainProcessor head so that birthdays are not reset if the chainProcessor can't scan.
stops scan for account if birthday not in chain:
- if we reach the sequence of an account's birthday but find that it doesn't match
the chain then the account came from a different network or fork.
- we should have checked blocks before that sequence, but skipped …

does not reset account data if birthday not in chain

---

ironfish/src/rpc/routes/chain/getTransaction.ts

Add asset `name` and `metadata` in mint part of `chain/getTransaction` response.
```
[ ] Yes
```
```
[ ] Yes
```

rpc: mint details in chain/getTransaction

---

ironfish/src/node.ts
ironfish/src/wallet/wallet.ts

uses the wallet nodeClient to connect to the event/onTransactionGossip RPC to sync pending transactions from the node to the wallet
runs syncTransactionGossip in a coroutine on each eventLoop iteration to handle failures and disconnects in the stream
adds a boolean isSyncingTransactionGossip to avoid concurrent syncing streams
removes event-based sync from peerNetwork
- simulator testing
```
[ ] Yes
```
```
[ ] Yes
```

syncs pending transactions from event/onTransactionGossip

---

ironfish/src/blockchain/blockchain.ts

from the docstring of find fork: 'If one block is a linear fast forward to the other with no forks, then the earlier block will be returned.'
in the case of a linear fast forward where both blocks are on the head chain we can short-circuit the findFork logic and immediately return the earlier block without iterating from one block to the other.
this helps speed up wallet rescans that make multiple calls to the 'chain/followChainStream' RPC: each call finds the fork between the current head of the node's chain and the hash passed to the RPC
- existing unit tests
```
[ ] Yes
```
Is …

speeds up findFork for linear fast forward case

---

ironfish/src/fileStores/config.ts
ironfish/src/rpc/response.ts
ironfish/src/rpc/routes/chain/__fixtures__/followChainStream.test.ts.fixture
ironfish/src/rpc/routes/chain/followChainStream.test.ts
ironfish/src/rpc/routes/chain/followChainStream.ts
ironfish/src/wallet/remoteChainProcessor.test.ts
ironfish/src/wallet/remoteChainProcessor.ts
ironfish/src/wallet/wallet.ts

remoteChainProcessor uses the chain/followChainStream RPC to stream block events from a node. the endpoint can write messages to the queue much more quickly than the wallet consumes them because the wallet decrypts the notes on each transaction on each block as it processes the stream
adds a 'limit' parameter to the chain/followChainStream RPC to close the stream once that number of events have been streamed to the client
adds a wallet config, 'walletSyncingMaxQueueSize', to configure the limit to use when syncing or scanning using the RemoteChainProcessor
updates scanTransactions to make multiple calls to 'update' until the RemoteChainProcessor instance used for scanning has reached a sequence greater than or equal to the head of the chain when the scan began
- unit tests
- manual …

adds limit to block events in remoteChainProcessor updates

---

ironfish-cli/src/commands/rpc/status.ts
ironfish-cli/src/commands/wallet/accounts.ts
ironfish-cli/src/commands/wallet/address.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/create.ts
ironfish-cli/src/commands/wallet/delete.ts
ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/notes.ts
ironfish-cli/src/commands/wallet/post.ts
ironfish-cli/src/commands/wallet/rename.ts
ironfish-cli/src/commands/wallet/rescan.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/commands/wallet/status.ts
ironfish-cli/src/commands/wallet/transaction/add.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/commands/wallet/use.ts
ironfish-cli/src/commands/wallet/which.ts
ironfish-cli/src/commands/workers/status.ts
ironfish-cli/src/utils/asset.ts
ironfish-cli/src/utils/currency.ts
ironfish-cli/src/utils/fees.ts
ironfish-cli/src/utils/transaction.ts
ironfish/src/sdk.ts

The SDK creates an RPC client when initialized. Config, rpc, wallet, and worker namespaced CLI commands connect to this RPC client but need to work for both a full node and standalone wallet. This code change adds a new SDK method to connect to the client property but default to a wallet node's memory client on failures or if local / remote is not forced.
We can move this as a utility into the CLI as well, but it seems better to offer this in the SDK for both node types.
There were alternatives that were considered (ex. writing the running context to a store), but this is a quick and functional solution without side effects that can be iterated upon in the future.
Running CLI commands under the updated namespaces …

feat(cli,ironfish): Add SDK method to connect to wallet rpc client

---

ironfish-cli/src/commands/config/edit.ts
ironfish-cli/src/commands/config/get.ts
ironfish-cli/src/commands/config/index.ts
ironfish-cli/src/commands/config/set.ts
ironfish-cli/src/commands/config/unset.ts
ironfish-cli/src/utils/clients.ts
ironfish/src/sdk.ts

The CLI commands under the config namespace can be run for both a standalone wallet and full node. This code change creates a client wrapper that does not open the database and uses a wallet node to instantiate an RPC client.
Some considerations as part of this change:
* We can create a parent `IronfishNode` class which the `FullNode` and `WalletNode` inherit from, and that can be used in this call. This design seems like a convenience rather than getting a benefit of a lot of shared logic (outside of just storing properties). This would also need some updates to the migration system and potentially refactoring how arguments are passed into the RPC.
* We can use the existing `connectRpc` and add some arguments. This can be a future improvement as there's probably a way to leverage …

feat(cli,ironfish): Create a CLI helper to create a config client

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/primitives/block.ts

**Relies on #4146**
With the addition of the owner field to the mint description, we need to verify that mint descriptions are using the correct owner as defined by the current state of chain and subsequently the chain asset database.
Closes IFL-1327
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat: Verify mint description owner in blocks

---

ironfish/src/rpc/routes/wallet/getAccountsStatus.test.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

using the head of the chain for the wallet's connected node allows the wallet to set the account birthday based on the chain state instead of based on the state of the other accounts in the wallet (i.e., using the chainProcessor).
- manual testing: create new account in wallet with no accounts, see that it is set to the head of the chain without rescan
```
[ ] Yes
```
```
[ ] Yes
```

sets createdAt to chain head for new accounts

---

ironfish/src/wallet/wallet.ts

if the wallet does not have a nodeClient it cannot read the chain head from the node.
in that case we can only set the account createdAt to null on account creation.
this enables a standalone wallet to create accounts without an active connection to a node.
```
[ ] Yes
```
```
[ ] Yes
```

sets account.createdAt to null if nodeClient null

---

ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/wallet.ts

importAccount has two dependencies on a node connection: it checks to see if the account birthday is in the chain and it (by default) begins a scan following import. if there is no connection to a running node the wallet cannot do either of these things.
fixes node connection dependencies in import:
- sets account createdAt to null if it cannot be checked against the chain. this is what the wallet does during import if the account birthday is not found in the chain
- skips rescanning if there is no node connection
manual testing
```
[ ] Yes
``` …

fixes account import if wallet not conneted to node

---

ironfish/src/rpc/routes/wallet/getAccountsStatus.ts

the wallet/getAccountsStatus RPC returns a boolean 'headInChain' field for each account
populating that field requires a connection to a node
changes the field to optional so that a standalone walletNode can return a status response without a connection to a running node
```
[X] Yes
```
```
[ ] Yes
```

getAccountsStatus returns undefined headInChain without node

---

ironfish/src/sdk.ts

If you call wallet node for commands that require a node client, these won't work if the data directory is a full node. This infers the context and falls back on a full node if needed.
This is a temporary measure and further cleanup will come.
Ran wallet commands on full node without remote node running
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add fallback logic if wallet node is called for full node

---

ironfish-cli/src/commands/start.ts
ironfish-cli/src/commands/wallet/start.ts
ironfish/src/sdk.ts

Switching between a full node and standalone per data directory is unsupported behavior. This adds a usability check in the start commands.
* Updates SDK to return a context to allow for initial migrations to run based on which start command is run
Ran start and wallet:start in different data directories:
* New data directory with start
* New data directory with wallet:start and node configuration options
* wallet:start in a full node data directory
* start in a standalone data directory
```
[ ] Yes
``` …

feat(cli,ironfish): Check running context in start and wallet:start

---

ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/primitives/mintDescription.ts
ironfish/src/primitives/transaction.ts
ironfish/src/rpc/routes/chain/followChainStream.ts

Changed `transferOwnershipTo` to a buffer so that it's easier to write code like `mint.transferOwnershipTo || mint.owner`.
Unit tests
No doc change required.

MintDescription: make `transferOwnershipTo` a `Buffer` to be consistent with `owner`

---

ironfish-cli/src/commands/status.ts
ironfish/package.json
ironfish/src/rpc/routes/node/getStatus.ts
yarn.lock

There's a bug in the node app where the app crashes on launch on the codesigned macOS build. Creating a build without libuv-monitor fixes it. Since we're just using it for debugging, for now it'll be easier to remove it and just re-add it to debug builds when we want to inspect them.
```
[] Yes
```
We never added docs on this, so nothing to remove from the docs.
```
[X] Yes
```

Remove libuv-monitor from SDK

---

ironfish-cli/README.md

README update for the CLI commands. As a new dev on the team, I thought it would be useful to have documentation to the CLI linked here. Also, making it clear that you can run the same commands on a different network (devnet) was helpful. 
```
[ ] Yes
```
```
[ ] Yes
```

adding information to readme about cli docs on the website

---

ironfish-cli/src/commands/start.ts
ironfish/src/rpc/routes/faucet/getFunds.test.ts
ironfish/src/rpc/routes/miner/blockTemplateStream.test.slow.ts
ironfish/src/rpc/routes/wallet/burnAsset.test.ts
ironfish/src/rpc/routes/wallet/create.test.slow.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

The fixture regeneration is failing on the wallet because of birthdays in account creation. The birthday is set to the node client's head (if defined), which is the local memory client in the test suite. Therefore, it'll always be the genesis block when we expect it to be null in some cases. 
We could update some of the tests to use the genesis, but that behavior is already covered. It's useful to still test null `createdAt` values since offline account creation should be supported with a standalone wallet that is not connected to a remote node.
This code change updates the wallet method to take an option for whether or not to set the birthday.
Updated unit tests …

test(cli,ironfish): Add option to set birthday on account create

---

ironfish-rust/src/transaction/mod.rs

Since #4210, this check is no longer necessary. We need to remove it to support the v2 transition.
```
[ ] Yes
```
```
[ ] Yes
```

remove hardcoded transaction version check in batch verify

---

ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust-nodejs/tests/transaction.test.slow.ts
ironfish-rust/src/transaction/mod.rs

Previously, these functions would call `.unwrap()` on Results instead of bubbling up the error. These functions now properly bubble up the error instead of using unwraps and panics.
Closes IFL-1522
```
[ ] Yes
```
```
[ ] Yes
```

`transaction_signature_hash` functions return a result instead of panic

---

ironfish-cli/src/commands/start.ts

Adding an `wallet` and `no-wallet` flag to control wallet rescan and note decryption
Add these flags when running the start command. Depending on these values, when you try to rescan transactions, it should fail/ pass. 
There is also an `enableWallet` config setting. Set that value and ensure that the flag that is set in the cli command overrides the config value. 
```
[ ] Yes
```
```
[ ] Yes
```

adding enable wallet flag to node start command

---

ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/defaultNetworkDefinitions.ts
ironfish/src/networkDefinition.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/strategy.test.ts

**Merging into a feature branch `asset-security`**
Adds a consensus parameter for enabling v2 transactions which enable the transferring of ownership of assets. 
Additionally adds a helper function for getting the correct transaction version for a specific block sequence.
Closes IFL-1330
```
[ ] Yes
```
```
[ ] Yes
```

Add a consensus parameter for asset ownership

---

ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts

when importing an account using ironfish-wallet-cli the wallet's 'nodeClient' may be null.
if the nodeClient is null then it is not possible to rescan. however, that does not mean that the wallet should use skipRescan! skipRescan sets the head of the account equal to the head of the chainProcessor. this results in the wallet incorrectly skipping the rescan automatically if it is not connected.
- adds regression test
```
[ ] Yes
```
```
[ ] Yes
```

fixes importAccount rescan if wallet not connected to node

---

ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
ironfish/src/mining/manager.test.slow.ts

If you ran `yarn test:slow manager -u` a few times, you'd see this test occasionally fail. This was due to the mempool fee estimation with the low fees creating non-deterministic transaction order. By using bigger fees, we get the desired determinism
```
[ ] Yes
```
```
[ ] Yes
```

fix: manager test was non-deterministic due to mempool fee estimation

---

ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts

**Builds on #4234**
This no longer checks the version when transactions are broadcast. This is because there isn't an easy way to verify any particular version is correct. A transaction could become valid due to a re-org or a consensus parameter activating at a specific block sequence.
Unit tests

check the transaction version when adding blocks

---

ironfish/src/rpc/routes/event/onTransactionGossip.ts
ironfish/src/wallet/wallet.ts

When the wallet listens for incoming unconfirmed transactions, limit the, number of transactions the wallet can queue up before it starts dropping them.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Check transactions validity before syncing to the wallet

---

benchmarks/benches/transaction.rs
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust/src/lib.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/version.rs
ironfish/src/consensus/verifier.test.ts
ironfish/src/genesis/addGenesisTransaction.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/strategy.test.slow.ts

Removes `TRANSACTION_VERSION` const, since it no longer makes sense as a default value.
Closes IFL-1530
```
[ ] Yes
```
```
[ ] Yes
```

remove hardcoded transaction version const

---

ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts

Often times, this function will be called with something like `chain.head.sequence - confirmations`. This would lead to incorrect logic when activation sequences are set to 1 on a fresh chain. Primarily, this will only affect devnet, but leads to simpler logic since we won't have to special case this logic everywhere we want to check it. A sequence will never be below 1, since the genesis sequence is 1.
Unit tests
N/A
Not a breaking change since this function is not used yet

Use a floor of 1 for sequence when checking active consensus params

---

ironfish/src/rpc/routes/faucet/getFunds.ts
ironfish/src/sdk.ts

enables standalone wallet to implement faucet command
manual testing with faucet command in ironfish-wallet-cli
```
[ ] Yes
```
```
[ ] Yes
```

adds faucet namespace to walletNode RPC server

---

ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/wallet.ts

when a user imports an account the wallet starts scanning the chain for transactions involving that account.
if a user imports multiple accounts into a single wallet, then only the first import will initiate a scan: secondary imports will not scan because a scan is already in progress. this forces the user to restart their node to start scanning for the other imported accounts.
updates importAccount to force a new scan to start on each import
adds 'force' parameter to 'scanTransactions'
fixes #4216
- manual testing: imported multiple accounts to a wallet and checked 'wallet:status' to see that all accounts were scanning
related …

restarts wallet scan on import

---

ironfish/src/walletNode.ts

There's a missing argument in the lambda that prevents the wallet from starting again on a retry connection.
https://github.com/iron-fish/ironfish/assets/5459049/0574bfb4-6b07-4b6b-8026-c950f2c9b736
```
[ ] Yes
```
```
[ ] Yes
```

fix(ironfish): Pass missing `startWallet` argument

---

.github/workflows/rust_ci.yml

We have been seeing an occasional timeout, seemingly related to `test_batch_verify_wrong_params` which is a long-running test due to the nature of what it is testing. Long-running tests are likely to be common with the Rust code, so we should increase the timeout for now.
CI
N/A
No

update rust ci test timeout from 3 to 5 minutes

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

changes wallet updateHead to iteravely update the chainProcessor until it reaches the chain head
updateHead currently only calls 'update' once per invocation which will sync a limited number of blocks from the node's chain. this slows syncing since the wallet only calls updateHead as part of its eventLoop method which runs at most once per second
- manual testing with ironfish-wallet-cli
```
[ ] Yes
```
```
[ ] Yes
```

updateHead updates to chain head

---

ironfish/src/rpc/routes/wallet/remove.ts

deleting an account with a non-zero balance requires confirmation from the user. however, if the account is scanning then the balance may not be accurate at the time that a user tries deletion.
requires confirmation from the user if they try to delete an account while it is scanning
- started rescan
- tried to delete account with zero balance and saw that confirmation was needed
```
[ ] Yes
```
```
[ ] Yes
```

delete requires confirmation if account scanning

---

ironfish/src/rpc/routes/wallet/getNodeStatus.ts

For the standalone wallet, fetching the node status hangs if the node client is disconnected. This change updates the handler to throw an error if the client is disconnected.
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Throw error if wallet node client is disconnected

---

ironfish/src/wallet/wallet.test.ts

the test of updateHead fails when fixtures are regenerated, but passes if they already exist
this is because creating an account may update the wallet's chainProcessor head state, but importing an account does not
(https://linear.app/if-labs/issue/IFL-1585/createaccount-and-importaccount-inconsistent)
fixes test to pass indpendently of fixture generation by always updating the wallet head to the genesis block before adding more blocks
- tested with fixture regeneration and without
```
[ ] Yes
```
what …

fixes wallet.updateHead test to be independent of fixture generation

---

ironfish/src/wallet/wallet.ts

This commit is purely a refactor of the current wallet logic, and should not alter the user-visible behavior of the wallet in any way. This refactor is foundational work needed to support the transfer of asset ownership (via `transferOwnershipTo`) in the future.
What this commit does, in a nutshell, is that it makes the backfilling code run before the transaction gets processed:
before this change: account.addPendingTransaction(...) -> backfill assets
after this change: backfill assets -> account.addPendingTransaction(...)
This will greatly simplify the processing of mints with `transferOwnershipTo` inside `addPendingTransaction`.
Existing tests should not break.
No doc change required.

When an unknown asset is seen in a wallet transaction, backfill its information from the chain db before processing the transaction

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish/src/wallet/account/account.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

The `wallet:assets` command does not show `$IRON` whether or not you have the native asset. This includes the asset in the streaming response.
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli,ironfish): Return native asset when streaming wallet assets

---

ironfish/src/network/__fixtures__/blockFetcher.test.ts.fixture
ironfish/src/network/blockFetcher.test.ts
ironfish/src/network/blockFetcher.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/telemetry/telemetry.ts

Track originating peer for block gossip through telemetry
Unit tests + local testing
```
[ ] Yes
```
```
[ ] Yes
```

Track originating peer for block gossip

---

ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/networkDefinition.ts
ironfish/src/strategy.test.slow.ts

Existing consensus activation flag has type of number, the issue is before a block sequence is picked for the activation we need to have a fake placeholder for the activation block sequence. 
This PR make the flag type nullable, so we can leave the block sequence as null before we decide on the actual sequence.
unit test
```
[ ] Yes
```
```
[ ] Yes
```
@mat-if @andreacorbellini

Make activation flag nullable

---

Cargo.lock
ironfish-rust/Cargo.toml
ironfish-rust/src/assets/asset.rs

Add a simple test to check that the serialization/deserialization for `Asset` in Rust works correctly.
No doc changes required.

Add (de)serialization for `Asset`

---

ironfish-cli/src/commands/chain/asset.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish/src/consensus/verifier.ts
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/rpc/routes/wallet/createTransaction.ts
ironfish/src/wallet/account/account.ts

Adds a `--transferOwnershipTo` flag to `wallet:mint` CLI command.
Closes IFL-1329
Manual testing:
- Pre-activation
- Imminent activation (creates a v2 transaction in anticipation of activation <15 blocks away)
- Post activation
```
[x] Yes
```
https://github.com/iron-fish/website/pull/545
No

Add transferOwnershipTo support to CLI/RPC

---

ironfish/package.json
ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture
ironfish/src/memPool/feeEstimator.ts
ironfish/src/memPool/memPool.test.ts
ironfish/src/memPool/memPool.ts
ironfish/src/memPool/recentlyEvictedCache.test.ts
ironfish/src/memPool/recentlyEvictedCache.ts
ironfish/src/rpc/routes/mempool/getTransactions.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/wallet/wallet.ts
yarn.lock

When calculating a feeRate for a transaction we are using BigInt even though transaction feeRates can potentially be a decimal value which BigInt cannot represent. For example the fee / kb of the following transactions are the same even though one has a higher fee
Fee: 1
Bytes: 2500
FeeRate (kB): `(BigInt(1) * BigInt(1000)) / BigInt(2500) = 1 // rounded up`
Fee: 2
Bytes: 2500
FeeRate (kB): `(BigInt(2) * BigInt(1000)) / BigInt(2500) = 1 // rounded up`
This has led to any fee below a certain amount being ~4 ore being treated the same in mempool sorting
- Existing mempool unit tests + new unit tests for Decimal library
- Performance tests done on mempool insertion …

Use Decimal library to make feeRates deterministic

---

README.md

Add links to GH CI jobs on the badges in readme
```
[ ] Yes
```
```
[ ] Yes
```

Add links to CI jobs on badges

---

ironfish-cli/src/commands/reset.ts
ironfish/src/wallet/wallet.ts

the 'ironfish reset' command deletes the chain database and most wallet datastores
however, it does not clear the 'heads' store. this prevents the wallet from starting the next time the node starts because the account head will reference a block that is missing from the chain
updates 'ironfish reset' to use 'wallet.reset' to reset all database stores, including the heads store
adds arguments to reset, resetAccounts to optionally reset the 'createdAt' field on each account
resets account 'createdAt' field in 'ironfish reset' if the command is used to change from one network to another because the createdAt field will reference a block on a different chain after changing networks
- manual testing:
- used `ironfish reset --networkId=` to reset and change networks
- used `ironfish start` to …

resets account heads and birthdays in reset command

---

ironfish/src/rpc/adapters/memoryAdapter.ts
ironfish/src/rpc/routes/chain/getTransactionStream.test.ts
ironfish/src/rpc/routes/event/onTransactionGossip.test.ts
ironfish/src/rpc/routes/miner/blockTemplateStream.test.slow.ts
ironfish/src/rpc/routes/node/getLogStream.test.ts

When tests are testing streaming endpoints they should close the connection at the end of the test so the node can clean up. It doesn't look like that's happening correctly currently.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

fix memory client close handlers

---

Cargo.toml
ironfish-rust/src/assets/asset.rs
ironfish-rust/src/assets/asset_identifier.rs
ironfish-rust/src/errors.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/public_address.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/nacl.rs
ironfish-rust/src/note.rs
ironfish-rust/src/serializing/aead.rs
ironfish-rust/src/serializing/mod.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/utils.rs
ironfish-rust/src/transaction/value_balances.rs
ironfish-rust/src/transaction/version.rs

Currently we have no backtrace when an error occurs in rust. This makes debugging in javascript and `ironfish-rust-nodejs` very challenging. This PR uses `std::backtrace` to include backtrace info into the returned error information.
If we include debug info with our profile:
```
RUST_BACKTRACE=1 yarn test:slow                                                                                                                                                                     yarn run v1.22.19
$ jest --testPathIgnorePatterns --testMatch "**/*.test.slow.ts"
FAIL   @ironfish/rust-nodejs  tests/demo.test.slow.ts
● Demonstrate the Sapling API › Should create a standard transaction
InvalidBalance
Backtrace:
0: std::backtrace_rs::backtrace::libunwind::trace
at …
```

feat: rust std::backtrace

---

ironfish/src/rpc/routes/chain/getTransaction.ts
ironfish/src/rpc/routes/wallet/types.ts

Marking counts fields as deprecated. User should use count the number of subObjects returned instead. 
```
[ ] Yes
```
```
[ ] Yes
```

marking counts fields as deprecated

---

.github/workflows/ci-regenerate-fixtures.yml

Notify slack that the CI job to run tests that regenerate fixtures has failed
Testing running the job manually
```
[ ] Yes
```
```
[ ] Yes
```

Notify Slack of fixture regeneration failure

---

ironfish/src/rpc/routes/wallet/burnAsset.test.ts
ironfish/src/rpc/routes/wallet/burnAsset.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.ts

Adding a `transaction` object to the response from Mint and Burn asset. This way, the user has access to both the `asset` and `transaction` when creating/ burning an asset, creating a more consistent experience wrt `createTransaction` and `postTransaction`
Note: I removed the `transactionHash` field. This was added as a replacement to the `hash` field for a better naming convention here https://github.com/iron-fish/ironfish/pull/4294/files. Since we haven't release this change, it's OK to remove it all together and point the user to the transaction object. 
Example result: 
```json
{
"status": 200,
"data": {
"asset": {
"id": "fe6daf7a862592f4111497aed4da7c9dc9bf060a5a769ef8a3a998d7b4ad0757",
"metadata": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```

adding full transaction object to burn and mint asset response

---

ironfish/src/rpc/routes/chain/exportChainStream.ts
ironfish/src/rpc/routes/chain/types.ts
ironfish/src/rpc/routes/peer/getBannedPeers.ts
ironfish/src/rpc/routes/peer/getPeerMessages.ts
ironfish/src/rpc/routes/peer/getPeers.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.ts
ironfish/src/rpc/routes/wallet/getBalance.ts
ironfish/src/rpc/routes/wallet/getBalances.ts
ironfish/src/rpc/routes/wallet/getNotes.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/rpc/routes/worker/getStatus.ts
ironfish/src/rpc/types.ts

Formatting them in the following order: 
- fields
- objects
- optional fields 
- deprecated fields
```
[ ] Yes
```
```
[ ] Yes
```

formatting all rpc objects in the same order

---

ironfish-cli/src/commands/service/bridge-relay.ts
ironfish-cli/src/commands/service/bridge/relay.ts

adds a service command to act as a relay; decrypting deposit transactions on Iron Fish and calling the bridge contract on Ethereum
relies on remote node to decrypt transactions with a given view key via chain/getTransactionStream
waits until block confirmed before processing deposit transactions
- created bridge account
- ran relay with bridge account's incoming view key
- sent deposit transaction to bridge account
```
[ ] Yes
```
```
[ ] Yes
```

initializes service:bridge-relay command

---

ironfish-cli/src/commands/chain/download.ts

As the chain snapshot grows larger, it's increasingly inconvenient for the download to error midway, which requires restarting from 0. This PR checks if the server supports range requests, and if so, passes a range header to the server if a previously existing file with the same name is in the temp directory.
```
[ ] Yes
```
```
[ ] Yes
```

Support resuming snapshot downloads if supported

---

ironfish-cli/src/commands/status.ts

Some endpoints make sense for the server to initiate streaming. Endpoints that only trigger when an event happens on the server side. Status however is not one of those endpoints. Refreshing the status every Xms is something the client should probably handle instead of the server side. Removing usages of the status streaming endpoint so we can eventually deprecate it
Tested status command with following locally
```
[ ] Yes
```
```
[ ] Yes
```

Don't use streaming endpoint in status CLI

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/webApi.ts

gets head hash from '/bridge/head' if head flag is not set
posts head hash to '/bridge/head' after processing all deposits from a confirmed block
- ran `service:bridge:relay` without starting head, stopped process after a few blocks
- ran again, observed that it started at the most recently processed head
```
[ ] Yes
```
```
[ ] Yes
```

updates bridge-relay to use API for head state

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts

Fee rate is accepted in send transaction, mint and burn also "send" transactions. Adding the ability to include fee rate for these transaction wallet apis as well. 
```
[ ] Yes
```
```
[ ] Yes
```

Adding feerate to mint and burn

---

.github/workflows/deploy-bridge-docker-image.yml

pushes to 'bridge-prototype' branch will trigger a docker image deployment with the 'bridge-prototype' tag
```
[ ] Yes
```
```
[ ] Yes
```

adds github workflow to deploy bridge-prototype docker image

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/webApi.ts

updates the 'service:bridge:relay' command to invoke the 'bridge/send' API endpoint to trigger minting tokens on the destination chain
calls 'bridge/send' only once per Iron Fish block to try to process blocks atomically
adds 'sender' to each note in the response of 'chain/getTransactionStream' RPC so that we can pass the sender address to the bridge API for validation
depends on https://github.com/iron-fish/ironfish-bridge/pull/8
```
[ ] Yes
```
```
[ ] Yes
```

bridge relay triggers mints via API

---

ironfish-cli/src/commands/service/bridge/deposit.ts
ironfish-cli/src/utils/currency.ts
ironfish/src/webApi.ts

'service:bridge:deposit' creates a bridge deposit request to the bridge API and displays the returned key to use in the deposit transaction memo
```
[ ] Yes
```
```
[ ] Yes
```

creates bridge deposit command

---

ironfish/src/fileStores/config.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/connections/connection.ts
ironfish/src/network/peers/connections/webRtcConnection.ts
ironfish/src/network/peers/connections/webSocketConnection.ts
ironfish/src/network/peers/localPeer.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/node.ts

From what I understand, this doesn't function correctly, and we have better tooling for this now (see ironfish-tank folder)
Ran lint, tests, and manually ran a node on mainnet
N/A
```
[x] Yes
```
This removes the `simulateLatency` config option and functionality

Remove unused simulate-latency code

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/webApi.ts

request id is a number, not a string
manual testing: ran `service:bridge:relay` to sync a deposit to local bridge api
```
[ ] Yes
```
```
[ ] Yes
```

fixes bridge request id type in relay service

---

ironfish-cli/src/commands/service/bridge/release.ts
ironfish/src/webApi.ts

adapted from 'faucet' service
polls bridge api for WIRON->IRON requests to process
creates a transaction with an output for each request returned, as available balance allows
updates bridge api with destination_transaction and state change after transaction creation
- manual testing: connected to local bridge api, sent transaction
```
[ ] Yes
```
```
[ ] Yes
```

adds 'release' service command

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts

updates chain/getTransactionStream to optionally accept an outgoingViewKey to use to decrypt notes
compares the sender address to the bridge address to determine if the bridge sent the transaction
collects confirmed transactions that the bridge sent and passes them to the bridge api to update request statuses to 'CONFIRMED'
- created record in local bridge api database with PENDING_IRON_RELEASE_TRANSACTION_CONFIRMATION status
- sent 'release' transaction matching record
- ran relay, verified status updated to CONFIRMED
```
[ ] Yes
``` …

updates bridge relay to watch for confirmed release transactions

---

ironfish-cli/src/commands/service/bridge/relay.ts

we use note memos to track the bridge request ID associated with transactions
if the memo is non-numeric then the transaction can't be tied to any bridge request in the api
```
[ ] Yes
```
```
[ ] Yes
```

filters out non-numeric memos before sending to bridge api

---

ironfish-cli/src/commands/service/bridge/deposit.ts

prompts the user to enter an address if one was not provided instead of requiring the flag be set
manual testing
```
[ ] Yes
```
```
[ ] Yes
```

adds prompt for eth dest address to deposit

---

ironfish/src/rpc/routes/wallet/__fixtures__/getAccountTransactions.test.ts.fixture
ironfish/src/rpc/routes/wallet/getAccountTransactions.test.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.ts

Adds a reverse sorting RPC field to allow for returning transactions sorted ascending and descending by timestamp.
Added a test for the new RPC field.
```
[ ] Yes
```
```
[ ] Yes
```

Allow ascending and descending sorting in account transactions RPC

---

ironfish-cli/package.json
ironfish-cli/src/commands/service/bridge/deposit.ts
ironfish/src/webApi.ts
yarn.lock

eth addresses are only 20 bytes in length, so we can fit the eth address into an Iron Fish note memo instead of first creating a record with a uuid through the api
adds eth address validation to avoid sending transactions with invalid addresses by mistake
strips '0x' from start of eth addresses (addresses are valid with or without the prefix)
uses binary string encoding for eth addresses in memos
removes createDeposit from WebApi
Resolves IFL-1753
manual testing
```
[ ] Yes
``` …

sends eth address in deposit memo

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/primitives/note.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/webApi.ts

adds 'memoHex' function to the Note to be able to return the memo as a string without stripping out non-human-readable characters
returns 'memoHex' with each note in getTransactionStream
decodes eth address from memo by converting to utf8, then base64, then back to hex. the memo string is converted to a buffer with utf8 encoding during transaction creation, so we need to convert it to a utf8 string before converting to a base64 string
updates request payload for '/bridge/send'
manual testing with deposit changes and bridge API changes
```
[ ] Yes
``` …

updates relay service to decode eth address from memo

---

ironfish-cli/package.json
simulator/package.json
yarn.lock

These packages need to use the version declared in ironfish/package.json for the monorepo workspace to work properly. If the version differs, these packages will not pick up changes made in the SDK
Make a change in the SDK and see if it is reflected when starting a node via the CLI
N/A
N/A

Fix version dependency for sdk

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/asset.ts

In `selectAsset` and `ironfish wallet:transactions`, the account flag and confirmation flag weren't being passed to the getAsset RPC call. This resulted in an error when running `ironfish wallet:transactions <nonDefaultAccount>` when the non-default account had custom assets that the default account did not:
```
No asset found with identifier 2822ed1455752040fd780d43d64f56ea624be6f17c5c96e20ae06ff3f2c7ec39
```
Fixed this by passing the flags through to `getAsset`.
```
[ ] Yes
``` …

Fix custom asset fetching when passing a non-default account to wallet:transactions

---

ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/flags.ts

Fixes: IFL-1714
https://linear.app/if-labs/issue/IFL-1714/cli-crashes-with-assetid-flag
Result (on Testnet)
Invalid hex value for asset id: 
Valid hex value: 
```
[ ] Yes
```
```
[ ] Yes
```

Adding hex flag to handle invalid hex field

---

ironfish/src/fileStores/config.ts
ironfish/src/network/peerNetwork.ts

Limiting size of node name to 32 letters. Other peers cannot connect to you if you have a long node name. 
```
[ ] Yes
```
```
[ ] Yes
```

adding string length limit to node name

---

ironfish-cli/src/commands/status.ts

With previous changes in https://github.com/iron-fish/ironfish/pull/4312 the status stream breaks if a node disconnects in the middle of a status follow. Fixing that problem
Tested locally
```
[ ] Yes
```
```
[ ] Yes
```

Fix status follow erroring out

---

ironfish/src/fileStores/config.ts
ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts
ironfish/src/node.ts

When the preemptive block creation is disabled, the mining manager prioritizes creating blocks with transactions (if there are any in the mempool) over creating empty blocks.
The primary target for this PR is the fish tank (simulator): sometimes, when running simulations that involve sending transactions, those transactions do not get mined and the simulations time out. Thanks to this PR, the simulations succeed 100% of the time and run much faster.
1. Run a miner with the default configuration, and verify that preemptive block creation is enabled (i.e. the default behavior hasn't changed)
2. Run a miner with `preemptiveBlockMining: false`, send a transaction, and verify that it gets mined immediately
Doc change: https://github.com/iron-fish/website/pull/557

Mining Manager: make preemptive block creation optional

---

ironfish-cli/src/commands/service/bridge/release.ts

propagates status name change from API:
PENDING_IRON_RELEASE_TRANSACTION_CONFIRMATION changed to PENDING_DESTINATION_RELEASE_TRANSACTION_CONFIRMATION
```
[ ] Yes
```
```
[ ] Yes
```

updates status for pending release

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish-cli/src/commands/service/bridge/release.ts
ironfish/src/webApi.ts

'next_wiron_requests' renamed to 'next_release_requests'
'update_wiron_requests' renamed to 'update_requests'
ran both `relay` and `release` against local test api
```
[ ] Yes
```
```
[ ] Yes
```

updates webApi bridge endpoints

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/webApi.ts

relay services hits the '/bridge/burn' api endpoint for any transaction it receives for non-native assets
this will rely on the api to determine if the asset sent to the bridge was a valid asset that can be released on the Ethereum side
adds 'bridgeBurn' WebApi method
manual testing sending custom asset to bridge
```
[ ] Yes
```
```
[ ] Yes
```

updates relay service to hit /bridge/burn endpoint

---

ironfish-cli/src/commands/service/bridge/release.ts
ironfish/src/webApi.ts

On each loop, query for the next mint transaction that is pending creation on Iron Fish
Manual testing
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli,ironfish): Process mint transactions in release service

---

ironfish-cli/src/commands/service/bridge/release.ts
ironfish/src/webApi.ts

updates the bridge release service to process pending burn transactions
on each iteration the release service will check whether the wallet is ready to make transactions before processing a pending release and a pending burn
uses the burnAsset endpoint to create a burn transaction for a single request at a time
- sent 'buttcoin' to bridge account
- ran relay changes from #4365 to sync to local api
- ran release to create burn transaction
```
[ ] Yes
```
what additional work is required, if …

release service creates burn transactions

---

ironfish-cli/src/commands/service/bridge/release.ts
ironfish/src/webApi.ts

Uses `bridge/release` endpoint instead of `next_release_requests`
```
fish service:bridge:release --datadir ~/.devnet                                                                   ─╯
$ yarn build && yarn start:js service:bridge:release --datadir /Users/joe/.devnet
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run service:bridge:release --datadir /Users/joe/.devnet
Fetching bridge account
Using account default
No bridge requests, waiting 5s
```
```
[ ] Yes
```
Is this a …

chore: refactor next release

---

ironfish-cli/src/commands/service/bridge/release.ts

for each iteration of the release service loop the burn process combines multiple pending burn requests into a single burn transaction
- sent multiple deposits
- ran relay
- ran release and created a single burn transaction for both requests:
```
Burn: [
{
"id": 33,
"asset": "213c1795b756e3237a6b7bd1e30b943c079c38f12d831b870152c96a7a9b7f26",
"amount": "1"
},
{
"id": 34,
"asset": "213c1795b756e3237a6b7bd1e30b943c079c38f12d831b870152c96a7a9b7f26",
"amount": "2"
}
] f2afe7e76bdbd0b3d3283050e50965a49e562984dc548c91ece31f451c6f8d8e
```
```
[ ] Yes
``` …

processes multiple burns in a single transaction

---

ironfish-cli/src/commands/service/bridge/relay.ts
ironfish/src/webApi.ts

adds 'getBridgePendingBurnRequests' method to WebApi
for each confirmed block, fetches the list of pending burn requests from the bridge api and compares the transactions in the block to the pending burn transactions
pushes update to api setting status of confirmed burns to 'PENDING_DESTINATION_RELEASE_TRANSACTION_CREATION'
manual testing - ran relay to pick up confirmed burn transactions and submit updates to api
```
[ ] Yes
```
```
[ ] Yes
```

relays confirmed burn transactions to bridge api

---

ironfish-cli/src/commands/service/bridge/release.ts

mints are on the destination side, not the source
uses 'PENDING_DESTINATION_MINT_TRANSACTION_CONFIRMATION' status after creating mint transaction
```
[ ] Yes
```
```
[ ] Yes
```

fixes status of pending mints

---

ironfish/src/fileStores/config.ts
ironfish/src/network/blockFetcher.test.ts

The default maxPeers is 50, as is the current default targetPeers. The logic is currently such that you continuously open outbound connections until you reach targetPeers. If targetPeers threshold is met, but maxPeers is not, you will continue accepting inbound connections. By setting these values separately, we create a buffer to allow for more inbound connections. This should have a downstream effect of allowing other peers to each peer saturation faster.
Unit tests, manual testing a node
N/A
N/A

Set the default targetPeers value to 45

---

ironfish/src/primitives/note.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/rpc/routes/wallet/getAccountNotesStream.test.ts
ironfish/src/rpc/routes/wallet/getAccountNotesStream.ts
ironfish/src/rpc/routes/wallet/utils.ts

the 'memo' method on the Note class returns the memo as a human-readable string by using 'BufferUtils.toHuman' on a utf8 decoded string of the memo
this human-readable representation may lose some information from the memo
returning the buffer instead allows sdk clients to choose how to interpret the data encoded in the note memo
for instance, a memo might contain a base64-encoded Ethereum public address. if this string is treated as a human-readable utf8 string, then the encoded address cannot be recovered accurately
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below …

changes Note.memo() to return Buffer

---

ironfish-cli/src/commands/peers/index.ts

Show the names of the peers as an option for the `peers` command
```
[ ] Yes
```
```
[ ] Yes
```

removing node name from hidden in the peer command

---

ironfish/src/network/blockFetcher.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/peer.ts
ironfish/src/rpc/routes/node/getStatus.ts
ironfish/src/syncer.test.ts
ironfish/src/syncer.ts

The Syncer's `findPeer` function will now choose 8 random peers. Of these peers, it will measure the round-trip-time of a blockHeadersRequest of the genesis block. It then chooses the fastest of these peers to sync from.
Additionally, it will check again on a growing interval (2, 4, 8... up to 60) minutes. The purpose of this is that it should check frequently on initial node startup, as the number of connected peers grows so that it has a good chance of selecting a good peer to sync from early.
It includes the current syncing peer in the checks on the interval, so that if you find a good quality peer, you are likely to continue syncing from that peer unless you find a better one.
Closes IFL-1781
- Manual testing
- Unit tests where applicable
N/A
N/A

Add better peer selection logic to the syncer

---

ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerManager.ts

Removing a function because it's only used in one test
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Remove getPeerOrThrow function

---

ironfish/src/network/peers/addressManager.test.ts
ironfish/src/network/peers/addressManager.ts
ironfish/src/network/peers/peerManager.ts

Realized that we no longer need the peer manager referenced in the address manager. Address manager is more isolated now. When we inevitably rip out the address manager, this will make things easier. 
```
[ ] Yes
```
```
[ ] Yes
```

address manager doesn't require the peer manager reference anymore

---

ironfish/src/syncer.ts

Right now, the log will trigger every 2 seconds regardless of the node being fully synced or not. We should only display this log if there's a possibility to sync
Start a local node in verbose log mode
N/A
N/A

moving findPeer log lower to avoid constant spam of the message

---

README.md
ironfish-cli/bin/run
ironfish-cli/package.json
ironfish-rust-nodejs/package.json
ironfish/package.json
simulator/bin/run
simulator/package.json

Since NodeJS LTS version was just bumped to v20, we need to support it properly.
- Bumps any minimum versions of 16 to 18
- Allows the CLI and the main entrypoint to support 18 _or higher_
- Update install instructions to simply reference latest LTS version so we can avoid manually bumping it all the time
Tested running a node on NodeJS 18 and 20
https://github.com/iron-fish/website/pull/561
We are removing NodeJS 16 support. This was only semi-supported in the first place so it should not be a huge change, but is worth noting.

Support a minimum of NodeJS v18

---

ironfish/src/network/messages/networkMessage.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/connections/connection.ts
ironfish/src/network/peers/connections/webRtcConnection.ts
ironfish/src/network/peers/connections/webSocketConnection.ts
ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerManager.ts

Shorten displaying NetworkMessage code for readability
```
[ ] Yes
```
```
[ ] Yes
```

Simplify displaying NetworkMessage in logs

---

ironfish/src/network/peers/peer.ts

Move compute state from connections into setState
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Move compute state from connections into setState

---

.github/workflows/build-ironfish-rust-nodejs.yml
.github/workflows/ci-regenerate-fixtures.yml
.github/workflows/ci.yml
.github/workflows/deploy-brew.yml
.github/workflows/deploy-npm-ironfish-cli.yml
.github/workflows/deploy-npm-ironfish-rust-nodejs.yml
.github/workflows/deploy-npm-ironfish.yml
.github/workflows/perf_test.yml
.github/workflows/publish-binaries.yml

Since we officially support NodeJS v18 and v20 (https://github.com/iron-fish/ironfish/pull/4395), we should test them in CI as well.
CI
N/A
N/A

Test multiple NodeJS versions in CI

---

ironfish/src/fileStores/fileStore.test.ts
ironfish/src/fileStores/fileStore.ts

According to the documentation: "It is unsafe to use filehandle.writeFile() multiple
times on the same file without waiting for the promise to be fulfilled (or rejected)."
https://nodejs.org/api/fs.html#filehandlewritefiledata-options
We have had several complaints especially from Windows users about the json file being corrupted.
We call this function several places in our codebase without waiting for the promise to complete.
This mutex is used to prevent multiple writes to the same file.
```
[ ] Yes
``` …

adding save and create file mutex

---

ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerCandidates.ts
ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerConnectionManager.ts
ironfish/src/network/peers/peerManager.test.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/network/testUtilities/helpers.ts

A WebSocket address with a port but no host is not a valid address. Catch these cases earlier so we can have better type safety in the rest of the code
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Normalize WebSocket fields on Peer

---

ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerCandidates.ts
ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerConnectionManager.ts
ironfish/src/network/peers/peerManager.test.ts
ironfish/src/network/peers/peerManager.ts
ironfish/src/network/testUtilities/helpers.ts

For Peer candidates remove the unrepresentable state of having a null address but a non-null port. Also in this PR changing the way we process PeerList messages. If a peer sends us a PeerList containing a null `address` but non-null `port` just set the `wsAddress` to null instead of throwing an error. This would cause the node to crash if a peer sent us a message like that
Running local node + unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Normalize WS Address on Peer Candidates

---

ironfish-cli/src/commands/peers/index.ts
ironfish/src/rpc/routes/peer/getPeer.ts
ironfish/src/rpc/routes/peer/getPeers.ts
ironfish/src/rpc/types.ts

Adding connection direction field to the peers command. Required an RPC change for the GetPeer and GetPeers endpoints
```
[ ] Yes
```
```
[ ] Yes
```

adding peer direction to rpc peers command

---

ironfish/src/network/peers/peerManager.ts

We have a duplicate `onStateChanged.on` call that can be combined to one. 
```
[ ] Yes
```
```
[ ] Yes
```

combining call on state changed to one location

---

ironfish/src/rpc/routes/chain/getTransactionStream.ts

- optionally decrypts notes for spender - adds optional outgoingViewKey to request - attempts to decrypt using outgoingViewKey if decryption fails using incomingViewKey
- adds sender address to note responses
- returns memo as hex string instead of human-readable utf8 string
supports relay applications (e.g., bridges) that require information on outgoing transactions and may encode non-human-readable data in memos
```
[ ] Yes
```
```
[X] Yes
```
Changes the `memo` …

updates getTransactionStream for relay integration

---

ironfish/src/wallet/__fixtures__/wallet.test.slow.ts.fixture
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.test.ts

These tests have been timing out occasionally on CI, so move them to the slow suite so they won't hit the timeout
Unit tests
N/A
N/A

move wallet tests that are timing out on CI to slow tests

---

ironfish/src/fileStores/config.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/peerManager.ts

These are old values I'm assuming that are no longer relevant, so might as well define a singular source of truth and use that. Follows our usual pattern of defining defaults with the config and utilizing where needed
N/A
N/A

Replace old hard-coded default numbers with config

---

ironfish/src/fileStores/config.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerConnectionManager.ts
ironfish/src/node.ts
ironfish/src/utils/array.ts

The peer connection manager will now disconnect from peers if there are more than maxPeers connected peers. Additionally, if keepOpenPeerSlot is set, it will disconnect if there are more than maxPeers - 1 connected peers. This can be used by nodes who want to ensure they are allowing incoming connections regardless of them being near/at capacity
Unit tests
Manual testing
```
[x] Yes
```
https://github.com/iron-fish/website/pull/564
N/A

Add keepOpenPeerSlot flag; disconnect from peers if above limit

---

ironfish/src/network/peers/peerManager.ts

This uses connected nodes instead of non-disconnected nodes to determine if a node should continue making outbound connections and accepting inbound connections. The main change here is that we are making the assumption that most node connections will fail, so this allows a node to have more active connection attempts. The end goal should be faster peer saturation. This does introduce the possibility of a node to have more than maxPeers connected peers. The current assumption is that natural attrition will take care of this, however, it would be a low amount of effort to add additional logic to prune peers if above maxPeers if it ends up being an issue.
Manual testing: run `ironfish peers --all`
N/A
N/A

Use connected peers when deciding peer limits

---

yarn.lock

This should fix [dependabot vulnerability #73](https://github.com/iron-fish/ironfish/security/dependabot/73). Note that Babel is used only by Jest (unless I'm mistaken), so this shouldn't affect our runtime.
Unit tests
No doc changes required

Update `@babel/traverse` to 7.23.2

---

Cargo.lock

This should fix two dependabot alerts:
- rustix: https://github.com/iron-fish/ironfish/security/dependabot/74
- openssl: https://github.com/iron-fish/ironfish/security/dependabot/64
This commit should only affect optional build-dependencies (rustix and openssl are optional dependencies of reqwest, which is used to download the sapling params if they're not part of the crate), so this should have no impact on the node.
Verified that the repository builds fine
No doc change required.

Update ironfish-rust build-dependencies

---

ironfish/src/fileStores/fileStore.test.ts

We need to wait for one more node event loop to complete to ensure the test is not flaky. I believe it's because we need two promises to settle and depending on when they are launched in the event loop, the first one will settle on the second loop instead of the first. 
```
[ ] Yes
```
```
[ ] Yes
```

fixing file store test flaky ness

---

ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerConnectionManager.ts

Previously, this loop would get executed every event loop iteration regardless of whether it could even create new connections. Now, it will only run if we can actually create new connections, saving a bit of overhead when it is not useful.
Also includes a light refactor to break this chunk of code into a function for easier reading and testing.
Unit tests, manually tested
N/A
N/A

Only loop through peer candidates if we can create new connections

---

ironfish/src/network/peers/peerManager.test.ts
ironfish/src/network/peers/peerManager.ts

Removes the logical inconsistency that would allow trying the same peer as a brokering peer multiple times even if we didn't necessarily need it more than once.
This tackles that by changing the logic in the `initWebRtcConnection` function
In draft state at the moment, I'll update unit tests if this is viable solution
```
[ ] Yes
```
```
[ ] Yes
```

returning list of brokering peers to try a variety of brokering peers for web rtc connections

---

ironfish/src/rpc/adapters/ipcAdapter.test.ts
ironfish/src/rpc/adapters/tcpAdapter.test.ts
ironfish/src/sdk.test.ts

This is not the right way, because os.tmpdir() does not give you a new random directory per call. You need to create a new directory using that as the root with a random name yourself. These tests are all affectively using the tmpdir() root to store ironfish files in.
Run tests
```
[ ] Yes
```
```
[ ] Yes
```

Fix tests using os.tmpdir()
