iron-fish/ironfish

ironfish/src/blockchain/blockchain.test.ts, ironfish/src/merkletree/hasher.ts, ironfish/src/merkletree/merkletree.ts, ironfish/src/primitives/noteEncrypted.ts, ironfish/src/rpc/routes/chain/followChain.ts, ironfish/src/rpc/routes/chain/getBlock.ts, ironfish/src/strategy.test.slow.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/wallet/account.test.ts, ironfish/src/wallet/account.ts, ironfish/src/workerPool/tasks/decryptNotes.ts
Simple rename PR
Reported relative to this doc:
https://coda.io/d/Engineering-Launch-Scratchpad_dpB9I5Fc9CG/Engineering-Launch-Scratchpad_suEgt#_lu1wj
unittests
```
[ ] Yes
```
=> chore: rename merklehash to hash

Cargo.lock, ironfish-rust-nodejs/Cargo.toml, ironfish-rust-nodejs/package.json, yarn.lock
This should fix #2985 (and all the duplicates I haven't gone through to close yet)
```
[ ] Yes
```
=> fix(napi): upgrade napi version to fix segfault

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> chore: version bump 0.1.62

ironfish/src/network/transactionFetcher.ts
A transaction's 'sources' are peers that we can request that full transactions from. We were storing this list of peers in a separate map of TransactionHash -> sources but it makes sense to store them in the map of TransactionHash -> TransactionState. This removes some unrepresentable states. For example when we've received a transaction and it is `PROCESSING` we no longer care about who we can request it from.
Unit tests
```
[ ] Yes
```
=> Add sources to transactions state in transaction fetcher

ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/flags.ts, ironfish/src/wallet/wallet.ts
=> account for spends when estimate size

ironfish-rust/src/keys/mod.rs
Instead of hardcoding `32` everywhere, moved this size to a constant. It will be useful for the import/export work that @EvanJRichard and I are working on.
unittests pass
```
[ ] Yes
```
=> chore: const spending key size

ironfish/src/memPool/feeEstimator.test.ts, ironfish/src/memPool/feeEstimator.ts, ironfish/src/node.ts
```
[ ] Yes
```
@NullSoldier @hughy
=> Remove wallet in fee estimator

Cargo.lock, ironfish-rust-nodejs/Cargo.toml
Haven't been able to repro the crash, and this is the version we used for much of phase 2.
```
[ ] Yes
```
=> fix(napi): Downgrade to known-good version without segfaults

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump to version 0.1.63

ironfish-cli/src/commands/wallet/transactions.ts
uses a single row for a transaction if only one asset in the transaction had a net balance change (exluding the fee paid)
uses multiple rows for a transaction if the transaction had multiple assets sent and/or received in the transaction
- moves construction of columns to separate function
- defines minimum asset name width as half of the maximum instead of basing it in the column header
- constructs all rows for a transaction within a single function
```
[ ] Yes
```
=> updates CLI transactions list UX

ironfish/src/rpc/routes/chain/getTransaction.ts
Transaction `mint` and `burn` data is public. Add this part data to `chain.getTransaction`, so that 3rd partly like explorer can track all asset (same as erc20 tokens)
- `mint / burn` activities
- `asset` total supply and current supply
```
[ ] Yes
```
=> Add mint/burn information to chain.getTransaction route

ironfish/src/rpc/routes/wallet/exportAccount.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/wallet.ts, ironfish/src/wallet/walletdb/accountValue.test.ts, ironfish/src/wallet/walletdb/accountValue.ts, yarn.lock
I tested it wrong, that PR actually breaks `wallet:export`. Revert it until I track down the issue. 
Ran `wallet:export` with this PR, it works again. 
```
[ ] Yes
```
=> Revert Export Accounts Version PR

ironfish-cli/src/commands/ceremony.ts, ironfish-cli/src/commands/service/ceremony.ts, ironfish-cli/src/trusted-setup/client.ts, ironfish-cli/src/trusted-setup/schema.ts, ironfish-cli/src/trusted-setup/server.ts
Gate the trusted setup ceremony by start date
```
[ ] Yes
```
=> Add start date to ceremony

ironfish-cli/src/commands/wallet/post.ts, ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/rpc/routes/wallet/__fixtures__/postTransaction.test.ts.fixture, ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts, ironfish/src/rpc/routes/wallet/mintAsset.test.ts, ironfish/src/rpc/routes/wallet/postTransaction.test.ts, ironfish/src/rpc/routes/wallet/postTransaction.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Offline post with offline flag
add PR https://github.com/iron-fish/ironfish/pull/3161
unit tests and locally yarn start wallet:post --offline
```
yajun@Yajuns-MacBook-Pro ironfish-cli % yarn start wallet:post 01000000000000000100000000000000a8e83eba78f07ddc4c214763d88b9fb17643e4a43329d8179ba73fa33d840b36b2d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac60500000000000000e057a9b835fdbe4598208bcd302dce44db7d0950f59ff81bb5803083709b490a46617563657420666f722032393732310000000000000000000000000000000010fc9e32e36ec5a2d2e51eb3aceb55c5d2c4733b409f8ab0d0f48b0fd21936d737fe13000000000020179f2684440a7189dd41562660a34e308cf82ca0700d0189cc8e1be410bb7f52200000000000000001209a7ea8d7ca4f076a90cac0c091babbd7a434e52d2ec38de12d1746c882fd186001201d4341b2032bbdf8847173e4b993e5e3b9c32c6c64be8be5145 …
```
=> Offline post

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump CLI version to v0.1.64

ironfish/src/rpc/routes/wallet/getNotes.ts
streams notes grouped by transaction using the same transaction ordering as getTransactions
Account.getNotes returns notes by note hash, which is not a useful ordering for a human
```
[ ] Yes
```
=> groups notes by transaction in getNotes RPC

ironfish-cli/src/commands/wallet/burn.ts
Refactor wallet:burn 
add raw tx flag
```
yarn start wallet:burn
$ yarn build && yarn start:js wallet:burn
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:burn
? Select the asset you wish to burn 2d637dad655c2979f21bebf81b499060341e5abb0b20c310c945556df405fb57 (raw tx)
Enter the amount to burn in the custom asset: 1
? Select the fee you wish to use for this transaction low: 0.00000001 IRON
You are about to burn:
2d637dad655c2979f21bebf81b499060341e5abb0b20c310c945556df405fb57 1.00000000 plus a transaction fee of $IRON 0.00000001 with the account default
* This action is NOT reversible *
Do you confirm (Y/N)?: N
Transaction aborted.
✨  Done in 34.55s.
```
``` …
```
=> Wallet:burn

ironfish-cli/src/trusted-setup/server.ts
The trusted setup server needs to buffer messages in case a client sends a message that does not fit into a single `onData` call. Currently this does not happen but just in case
```
[ ] Yes
```
=> Add message buffer to trusted setup server

ironfish-cli/package.json, ironfish/package.json
=> Bump node to v0.1.65

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust-nodejs/tests/demo.test.slow.ts, ironfish/src/consensus/verifier.test.ts, ironfish/src/genesis/makeGenesisBlock.ts, ironfish/src/primitives/rawTransaction.ts, ironfish/src/strategy.test.slow.ts, ironfish/src/workerPool/tasks/createMinersFee.test.ts, ironfish/src/workerPool/tasks/createMinersFee.ts
existing unit test
```
[ ] Yes
```
=> Rename transaction output

ironfish-cli/src/commands/wallet/export.ts
Just doing some pair programming with joe and saw we could move related code together.
```
[ ] Yes
```
=> Moved related export code together

ironfish-cli/src/commands/peers/banned.ts, ironfish/src/network/peers/peer.ts, ironfish/src/network/peers/peerManager.test.ts, ironfish/src/network/peers/peerManager.ts, ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/peers/getBannedPeers.ts, ironfish/src/rpc/routes/peers/index.ts
Add RPC of banned peers for debugging network conditions
```
[ ] Yes
```
=> Add banned peers RPC

ironfish/src/mining/poolDatabase/database.test.ts, ironfish/src/mining/poolDatabase/database.ts, ironfish/src/mining/poolShares.test.ts, ironfish/src/mining/poolShares.ts
This introduces some basic scaffolding for the poolDatabase and MiningPoolShares classes. While this change doesn't introduce any meaningful unit tests, it will enable testing with the refactor PRs, so that we can be more confident in the changes being made.
```
[ ] Yes
```
=> test(ironfish): introduce some test scaffolding for the mining pool

ironfish-cli/src/commands/service/faucet.ts, ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/post.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish/src/blockchain/blockchain.test.ts, ironfish/src/mining/poolShares.ts, ironfish/src/mining/webhooks/webhookNotifier.ts, ironfish/src/primitives/rawTransaction.test.ts, ironfish/src/primitives/rawTransaction.ts, ironfish/src/rpc/routes/wallet/__fixtures__/createTransaction.test.ts.fixture, ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts, ironfish/src/rpc/routes/wallet/createTransaction.test.ts, ironfish/src/rpc/routes/wallet/createTransaction.ts, ironfish/src/rpc/routes/wallet/sendTransaction.test.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/testUtilities/fixtures/transactions.ts, ironfish/src/testUtilities/helpers/transaction.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
finds remaining uses of 'receives' to describe the outputs of a transaction and renames to 'outputs'
```
[ ] Yes
```
=> finishes renaming 'receives' -> 'outputs'

package.json, yarn.lock
Output from lerna runs are now more intelligible.
tests pass
```
[ ] Yes
```
=> chore: update lerna

ironfish-cli/src/commands/wallet/import.ts
- Adds attempt to import raw spending key
- Clarifies the account import when a failure occurs
- swaps the order of the prompt for failed import to disambiguate the requested "name"
https://user-images.githubusercontent.com/26990067/217382192-ca672514-865d-4541-8404-8c81bce7fecf.mov
```
[ ] Yes
```
=> fix: autoimport spend key + clarifications

ironfish/src/mining/poolDatabase/database.test.ts, ironfish/src/mining/poolDatabase/database.ts, ironfish/src/mining/poolShares.ts, ironfish/src/mining/webhooks/webhookNotifier.ts
**Builds on #3322** 
```
[ ] Yes
```
=> refactor(ironfish): Mining pool notifications updated with the new logic

ironfish-cli/src/commands/miners/pools/start.ts, ironfish/src/fileStores/config.ts, ironfish/src/mining/pool.ts, ironfish/src/mining/poolDatabase/database.test.ts, ironfish/src/mining/poolDatabase/database.ts, ironfish/src/mining/poolDatabase/index.ts, ironfish/src/mining/poolDatabase/migrations/007-add-payout-transaction-table.ts, ironfish/src/mining/poolDatabase/migrations/008-add-payout-share-table.ts, ironfish/src/mining/poolDatabase/migrations/009-remove-old-tables.ts, ironfish/src/mining/poolDatabase/migrations/index.ts, ironfish/src/mining/poolShares.test.ts, ironfish/src/mining/poolShares.ts
**Builds on #3336** 
```
[ ] Yes
```
=> refactor(ironfish): Remove old pool logic and test logic we kept

ironfish/src/mining/poolDatabase/database.test.ts, ironfish/src/mining/poolDatabase/database.ts, ironfish/src/mining/poolShares.ts
=> fix(ironfish): Mining pool deletes shares that cannot be paid out

ironfish/src/wallet/account.ts
There's no way to get an asset from an account right now
```
[ ] Yes
```
=> Expose way to get asset from account

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump for version 66

ironfish/src/mining/poolDatabase/database.ts, ironfish/src/mining/poolShares.test.ts
=> fix(ironfish): pool only pays out ended periods

ironfish-cli/src/commands/wallet/balances.ts, ironfish/src/rpc/routes/wallet/getBalances.test.ts, ironfish/src/rpc/routes/wallet/getBalances.ts
=> Return assetName in wallet.getBalances() route

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/utils/asset.ts
This also makes it so it returns the whole "asset" and not just the ID
```
[ ] Yes
```
=> Remove extra query from selectAsset

ironfish-cli/package.json, ironfish/package.json
=> bumps versions for release of v0.1.67

ironfish-cli/src/commands/wallet/mint.ts, ironfish/src/primitives/rawTransaction.test.ts, ironfish/src/primitives/rawTransaction.ts
=> Readable mint error

ironfish/src/mining/stratum/stratumServer.ts, ironfish/src/mining/stratum/stratumServerClient.ts
This will prevent the leak from happening in StratumServer
```
[ ] Yes
```
=> Move unsubscriptions to stratumServer

ironfish-cli/src/commands/service/faucet.ts, ironfish/src/mining/poolShares.ts, ironfish/src/rpc/routes/wallet/sendTransaction.test.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts
This RPC hasn't been touched in awhile and I'm doing a pass on all of these with rohan for normalization purposes.
```
[ ] Yes
```
=> Clean up sendTransaction RPC

ironfish/src/rpc/routes/wallet/burnAsset.test.ts, ironfish/src/rpc/routes/wallet/burnAsset.ts, ironfish/src/rpc/routes/wallet/createTransaction.ts, ironfish/src/rpc/routes/wallet/mintAsset.test.ts, ironfish/src/rpc/routes/wallet/mintAsset.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts, ironfish/src/utils/currency.ts, ironfish/src/utils/yup.test.ts, ironfish/src/utils/yup.ts
And remove the need for validating this in all the RPCS.
```
[ ] Yes
```
=> Add currency yup validator

ironfish-cli/src/commands/wallet/prune.ts
```
yajun@Yajuns-MBP ironfish-cli % yarn start wallet:prune --dryrun
$ yarn build && yarn start:js wallet:prune --dryrun
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:prune --dryrun
Opening node... Done.
Process Account bobatea (60597d2).
Account bobatea (60597d2) has 1 expired transactions
Compacting wallet database... done
✨  Done in 2.57s.
yajun@Yajuns-MBP ironfish-cli % yarn start wallet:prune --dryrun --no-expire
$ yarn build && yarn start:js wallet:prune --dryrun --no-expire
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:prune --dryrun --no-expire …
```
=> Remove expired transaction

ironfish/src/primitives/rawTransaction.ts, ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts, ironfish/src/rpc/routes/wallet/createTransaction.ts, ironfish/src/rpc/routes/wallet/mintAsset.test.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/testUtilities/fixtures/transactions.ts, ironfish/src/testUtilities/helpers/transaction.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Also simplified the code by moving the size calculation into rawTransaction()
Also simplified the code by moving the size calculation into rawTransaction()
```
[ ] Yes
```
=> Convert wallet.createTransaction() to use options

ironfish/src/rpc/routes/wallet/createTransaction.test.ts, ironfish/src/rpc/routes/wallet/createTransaction.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts, ironfish/src/wallet/wallet.ts
Reduced the code down a lot and made it fairly linear. Also removed online / synced 
```
[ ] Yes
```
=> Simplify createTransaction route

ironfish/src/node.ts, ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/rpc/routes/wallet/burnAsset.ts, ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts, ironfish/src/rpc/routes/wallet/mintAsset.test.ts, ironfish/src/rpc/routes/wallet/mintAsset.ts, ironfish/src/rpc/routes/wallet/postTransaction.ts, ironfish/src/rpc/routes/wallet/sendTransaction.test.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
No reason to have to pass it in, make it consistent with our other objects. If you need a high level system you should take it into the constructor.
```
[ ] Yes
```
=> Add mempool to wallet constructor

ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/rpc/routes/wallet/createTransaction.test.slow.ts, ironfish/src/rpc/routes/wallet/mintAsset.test.ts, ironfish/src/rpc/routes/wallet/postTransaction.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
I'm going to add more options to this
```
[ ] Yes
```
=> Convert wallet.post() to use options

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
We are also bumping rust and the SDK
```
[ ] Yes
```
=> Version bump for release 0.1.68

ironfish-cli/STYLE_GUIDE.md, ironfish-cli/src/commands/wallet/post.ts
The progress bar is faked, and we should use an action spinner instead. Also added UX guidelines for this.
```
[ ] Yes
```
=> Replace progress bar with action in wallet:post

ironfish/src/memPool/feeEstimator.test.ts, ironfish/src/memPool/feeEstimator.ts, ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/chain/estimateFeeRate.test.ts, ironfish/src/rpc/routes/chain/estimateFeeRate.ts, ironfish/src/rpc/routes/chain/estimateFeeRates.test.ts, ironfish/src/rpc/routes/chain/estimateFeeRates.ts, ironfish/src/rpc/routes/chain/index.ts
This splits them out into 2 different very clear RPCs.
Added tests
```
[ ] Yes
```
=> Split out estimateFeeRate() and estimateFeeRates()

ironfish-cli/src/commands/fees.ts, ironfish/src/fileStores/config.ts, ironfish/src/memPool/feeEstimator.test.ts, ironfish/src/memPool/feeEstimator.ts, ironfish/src/node.ts, ironfish/src/rpc/routes/chain/estimateFeeRate.test.ts, ironfish/src/rpc/routes/chain/estimateFeeRate.ts, ironfish/src/rpc/routes/chain/estimateFeeRates.test.ts, ironfish/src/rpc/routes/chain/estimateFeeRates.ts, ironfish/src/rpc/routes/wallet/createTransaction.ts
finishes renaming fee rate priority levels from low, medium, and high to slow, average, and fast.
```
[ ] Yes
```
=> changes remaining low/medium/high references

ironfish/src/typedefs/bufio.d.ts, ironfish/src/wallet/walletdb/decryptedNoteValue.ts, ironfish/src/workerPool/tasks/sleep.ts, ironfish/src/workerPool/tasks/submitTelemetry.ts
And fix all the spots its not specified.
```
[ ] Yes
```
=> Change bufio types sizeVarString to force encoding

ironfish-cli/src/commands/chain/prune.ts, ironfish-cli/src/commands/chain/rewind.ts, ironfish-cli/src/commands/wallet/repair.ts
I find that some cli desc use 'does' while others use 'do'. This PR changes 'does' to 'do' to match most desc cases.
```
[ ] Yes
```
=> Normalization of cli description

ironfish/src/wallet/walletdb/walletdb.ts
Create a store which will help track spending of the same note in the wallet
N/A
```
[ ] Yes
```
=> feat(ironfish): Create `nullifierToTransactionHash` store

ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/utils/currency.ts
This now changes cli send to use the new fee and currency prompts. It also simplifies the logic a lot.
Create some transactions using it.
```
[ ] Yes
```
=> Change send to use new CLI prompts

ironfish/src/rpc/routes/wallet/__fixtures__/postTransaction.test.ts.fixture
Was seeing this when running tests locally, so checking them in
```
[ ] Yes
```
=> chore: add missing test fixtures

ironfish-cli/package.json, ironfish/package.json
Bump node version
```
[ ] Yes
```
=> Release 02/24/23

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts
fixes a flaky wallet test that depended on the ordering of output notes in a transaction.
changes the test to find the correct note from the transaction.
```
[ ] Yes
```
=> fixes flaky wallet test, regenerates fixtures

ironfish-mpc/README.md
Adding information about the final contribution value to be used by the trusted setup parameters
```
[ ] Yes
```
=> Commit beacon randomness

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump to 0.1.71

.github/pull_request_template.md
Since we regularly add / update RPC behavior, we should try to keep ourselves accountable for documentation updates.
N/A
```
[ ] Yes
```
=> chore(): Add section for docs to PR template

ironfish-cli/src/commands/wallet/post.ts
Allow offline post transaction without broadcast
```
yarn start wallet:post --help
$ yarn build && yarn start:js wallet:post --help
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:post --help
Post a raw transaction
USAGE
$ ironfish wallet:post [TRANSACTION] [-v] [--config <value>] [-d <value>] [--rpc.tcp] [--rpc.ipc] [--rpc.tcp.host <value>] [--rpc.tcp.port <value>] [--rpc.tcp.tls] [--rpc.auth <value>]
[--account <value>] [--confirm] [--broadcast]
ARGUMENTS
TRANSACTION  The raw transaction in hex encoding
FLAGS
-d, --datadir=<value>   [default: ~/.ironfish] The path to the data dir
-v, --verbose           Set logging level to verbose
--account=<value>       The account that …
```
=> wallet post allow no for broadcast flag

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump to version 0.1.72

.github/workflows/deploy-brew.yml, ironfish-cli/scripts/deploy-brew.sh
run ./ironfish-cli/scripts/deploy-brew.sh locally
run https://github.com/iron-fish/ironfish/actions/workflows/deploy-brew.yml
```
[ ] Yes
```
```
[ ] Yes
```
=> Upload ironfish-cli release to R2

ironfish/src/rpc/routes/chain/getBlock.ts
Adding note size and commitment to the block header RPC
Local testing
```
[ ] Yes
```
```
[ ] Yes
```
=> Add noteSize and noteCommitment to getBlock RPC

ironfish-cli/package.json, ironfish/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump to v0.1.73

ironfish-cli/src/commands/chain/genesisadd.ts, ironfish/src/genesis/__fixtures__/genesis.test.slow.ts.fixture, ironfish/src/genesis/addGenesisTransaction.ts, ironfish/src/genesis/genesis.test.slow.ts, ironfish/src/genesis/index.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> feat: genesisadd CLI command

ironfish-rust/src/assets/asset.rs
When instantiating an asset, it was calling `asset_hash_to_point`, and then converting the hash array into an `AssetIdentifier`, which also calls `asset_hash_to_point`. Because of this, this function does not need to call it anymore.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> fix(rust): Instantiating an asset only calls the hash to point function once

ironfish-zkp/src/constants.rs
Not used anymore
```
[ ] Yes
```
```
[ ] Yes
```
=> chore(zkp): Remove unused pedersen personalization

ironfish-cli/src/commands/ceremony/service.ts, ironfish-cli/src/utils/s3.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add region to service command

ironfish-cli/scripts/import-export-test.sh
This allows tests to be run multiple times even if they fail in the middle.
```
[ ] Yes
```
```
[ ] Yes
```
=> Delete importexport test datadir before starting

ironfish-cli/scripts/import-export-test/0p1p66_mnemonic.txt, ironfish-cli/scripts/import-export-test/0p1p67_mnemonic.txt, ironfish-cli/scripts/import-export-test/0p1p68_mnemonic.txt, ironfish-cli/scripts/import-export-test/0p1p70_mnemonic.txt, ironfish-cli/scripts/import-export-test/0p1p71_mnemonic.txt, ironfish-cli/scripts/import-export-test/0p1p72_mnemonic.txt
We should only store this when the mnemonic or spending key version changes. This shaves off a few minutes of test time from this test.
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove duplicate mnemonics

ironfish/src/rpc/routes/wallet/types.ts, ironfish/src/rpc/routes/wallet/utils.ts
introduced in #3728 and inadvertently removed in #3733
- manual testing with `wallet:transactions`
```
[ ] Yes
```
```
[ ] Yes
```
=> restores submittedSequence to wallet transaction RPCs

ironfish-cli/src/commands/wallet/transactions.ts
adds a '--notes' flag to the 'wallet:transactions' command. when '--notes' is passed, each transaction is listed with one row per decryptable output note in the transaction.
each note row includes the amount of the note, the asset id and name of the note, and the public addresses of the sender and recipient.
notes are ordered so that notes in the native asset are listed first for each transaction.
Closes IFL-318 and IFL-409
`ironfish wallet:transactions --notes`
`ironfish wallet:transactions --notes --csv`
```
Timestamp,Status,Type,Hash,Expiration,Submitted Sequence,Fee Paid ($IRON),Asset ID,Asset Name,Amount,Sender Address,Recipient Address
3/29/2023 1:21:20 PM PDT,confirmed,receive,c5fcbb81e2e4411dd7218ee8071fb093e311bdff098d7b3c7f9648bbc239b653,36689,36661,,d7c86706f5817aa718cd1cfad0323 …
```
=> optionally organizes wallet:transactions output by note

ironfish/src/primitives/target.test.ts, ironfish/src/primitives/target.ts
We don't use this anywhere, and it's an impractically high difficulty, so it just makes the constructor more complicated.
Fixes IFL-495
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove undefined from Target constructor

ironfish/src/rpc/routes/chain/getTransaction.ts
https://github.com/iron-fish/website/pull/362
```
[ ] Yes
```
```
[ ] Yes
```
=> Add index & noteIndex in chain/getTransaction

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps package versions for v0.1.75

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump to version 0.1.76

ironfish/src/merkletree/index.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Export NoteHasher in merkle tree from

ironfish-cli/src/commands/wallet/send.ts
Closes IFL-690
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli): add memo to interactive mode and display it in confirmation

ironfish-cli/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Version 1.0.1

ironfish-cli/src/commands/airdrop/airdrop.ts, ironfish-cli/src/commands/airdrop/split.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> fix: airdrop fee adjustment

ironfish/src/rpc/routes/chain/getTransaction.test.ts, ironfish/src/rpc/routes/chain/getTransaction.ts
Linear task https://linear.app/if-labs/issue/IFL-723/add-spend-to-rpc-walletgettransaction
unit test
```
[ x] Yes
```
```
[ ] Yes
```
@holahula
=> Add spends to chain/getTransaction

ironfish/src/defaultNetworkDefinitions.ts, ironfish/src/networkDefinition.ts
Makes devnet consistent with all the other networks
No testing needed
```
[ ] Yes
```
```
[ ] Yes
```
=> Rename DEV -> DEVNET

ironfish-cli/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps versions for v1.1.0

simulator/src/simulator/misc.ts, simulator/src/simulator/simulation-node.ts, simulator/src/simulator/simulator.ts, simulator/src/simulator/utils/accounts.ts
These are a set of miscellaneous changes from working on the `airdrop` project. Since that project will never be merged into staging, these changes were pulled out.
Tests coming soon
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(simulator): misc changes from working on airdrop

simulator/src/commands/start.ts, simulator/src/simulator/simulator.ts
Adding a flag to do verbose logging in the simulator
```
[ ] Yes
```
```
[ ] Yes
```
=> Add verbose logging to simulator

ironfish/README.md
Sdk does not have wallet anymore, update the readme to use wallet from sdk node
```
[ ] Yes
```
```
[ ] Yes
```
@dguenther @ironfish-eng
=> Update ironfish repo readme

ironfish-cli/src/commands/service/faucet.ts
the faucet service always uses the default account for transactions.
this prevents us from combining the api-node and pool-node because mining and pool payouts also use the default account. this could create issues if the faucet and pool are sending transactions out from the same account.
adds a flag to set the account to send faucet payouts from.
- ran the faucet service locally using a non-default account
- used the faucet and received the transaction from the non-default account
```
[ ] Yes
``` …
=> adds account flag to faucet service command

ironfish/src/mining/manager.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> chore: remove unneeded AsyncUtil usage in mining manager

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> ironfish v1.2.0, @ironfish/rust-nodejs v1.1.0

benchmarks/benches/transaction.rs, benchmarks/src/lib.rs
Relatively simple benchmarks for a single transaction and 5 transactions batched.
Closes IFL-877
```
[ ] Yes
```
```
[ ] Yes
```
=> test: transaction verification benchmarks

simulator/src/simulator/simulation-node.ts
see title
flag was missed in #3897 
```
[ ] Yes
```
```
[ ] Yes
```
=> fix(simulator): turn http adapter on by default

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps package versions for v1.3.0

ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
test fixture files dropped during recent changes
```
[ ] Yes
```
```
[ ] Yes
```
=> adds test fixtures for mining manager tests

ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture, ironfish/src/mining/manager.test.slow.ts, ironfish/src/mining/manager.ts, ironfish/src/rpc/routes/miner/blockTemplateStream.test.slow.ts
This was leading to an issue where time to send out blocks was almost 2x slower than before this change since it would only send out "full" blocks, despite creating both empty and full blocks.
A quick measurement of wall-clock time on my laptop from when the head changed to when a block template was sent out:
- master: ~450ms
- staging: ~450 - 1000ms
- With bug fixed: ~17ms
While investigating this bug, I ran across a few other issues:
- Due to a priority check, subsequent empty blocks were getting dropped instead of being sent out when they should.
- Example: Chain changes head to block 5. Manager creates empty template 6 (priority 0), sends it out. Manager creates full template 6 (priority 1), sends it out. Chain changes head to block 6. Manager creates empty template 7 (priority 0), …
=> fix: Fix mining manager not sending out empty block templates

ironfish/src/rpc/routes/wallet/__fixtures__/rename.test.ts.fixture
```
[ ] Yes
```
```
[ ] Yes
```
=> adds missing fixture for rename rpc

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps versions for v1.4.0

ironfish-cli/src/utils/index.ts, ironfish-cli/src/utils/s3.test.ts, ironfish-cli/src/utils/s3.ts
Found this one util file did not adhere to our convention so I made it consistent.
We should only need to let tests run.
=> Standardize util exports for S3 utils

ironfish/src/primitives/__fixtures__/transactionVerify.test.perf.ts.fixture, ironfish/src/primitives/transactionVerify.test.perf.ts
Create transaction verify perf test, with input and output in the range of [1, 100]
yarn test:perf:report
yarn test transactionVerify.test.perf.ts --testPathIgnorePatterns
```
[ ] Yes
```
```
[ ] Yes
```
@mat-if @danield9tqh
=> Create tx verification perf test

ironfish-cli/src/commands/service/stats.ts
adds a loop to the stats command to listen to a stream of reorganizeChain events from the node and submit reorg data to telemetry.
submits the hash and sequence of the old head, the new head, and the block at which the forks diverged.
- running stats command and logging telemetry submissions
```
[ ] Yes
```
```
[ ] Yes
```
=> adds chain reorgs to stats command

ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/wallet/getBalance.ts
All the parameters are optional so the body should be optional.
Run the tests for RPC.
=> Make RPC getBalance body optional

.github/workflows/perf_test.yml
Run perf test on mac mini
monitor the github workflow
```
[ ] Yes
```
```
[ ] Yes
```
@danield9tqh @mat-if @dguenther
=> Run perf test on mac mini

ironfish/src/mining/manager.ts
Handles the `HeadChanged` error correctly if it occurs on the first template created. Very small fix but just makes all error messages consistent for the manager
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Consistently handle template creation errors in mining manager

ironfish/src/blockchain/blockchain.ts, ironfish/src/mining/manager.ts
Reverts iron-fish/ironfish#3972. Reverting because of accidental merge to master
=> Revert "Fix error message when chain head changes"

Cargo.lock, ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish-rust/Cargo.toml, ironfish-zkp/Cargo.toml, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Version bump 1.5.0

ironfish-cli/src/commands/wallet/export.ts, ironfish/src/rpc/routes/wallet/exportAccount.test.ts, ironfish/src/rpc/routes/wallet/exportAccount.ts, ironfish/src/rpc/routes/wallet/importAccount.test.ts, ironfish/src/wallet/account/encoder/account.test.ts, ironfish/src/wallet/account/encoder/account.ts, ironfish/src/wallet/account/encoder/encoder.ts, ironfish/src/wallet/account/index.ts, ironfish/src/wallet/index.ts
Build was failing due to export. 
- Fixes exports
- Renames format so it is more explicit for a generic export
build passes
```
[ ] Yes
```
```
[ ] Yes
```
=> fix: import failure

ironfish-cli/src/commands/wallet/import.ts
This is only used in one place, so we can just pass this in.
Minor change, no testing needed.
=> Remove temporary variable rescan

ironfish/package.json, yarn.lock
```
[ ] Yes
```
```
[ ] Yes
```
=> chore: update libuv-monitor 0.0.5 for node-app compatibility changes

ironfish/src/node.ts, ironfish/src/telemetry/telemetry.ts
Remove unused telemetry method
N/A
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(ironfish): Remove `submitNewTransactionCreated` telemetry

ironfish/src/rpc/routes/faucet/getFunds.ts, ironfish/src/rpc/routes/wallet/burnAsset.ts, ironfish/src/rpc/routes/wallet/createTransaction.ts, ironfish/src/rpc/routes/wallet/exportAccount.ts, ironfish/src/rpc/routes/wallet/getAccountNotesStream.ts, ironfish/src/rpc/routes/wallet/getAccountTransaction.ts, ironfish/src/rpc/routes/wallet/getAccountTransactions.ts, ironfish/src/rpc/routes/wallet/getAssets.ts, ironfish/src/rpc/routes/wallet/getBalance.ts, ironfish/src/rpc/routes/wallet/getBalances.ts, ironfish/src/rpc/routes/wallet/getNotes.ts, ironfish/src/rpc/routes/wallet/getPublicKey.ts, ironfish/src/rpc/routes/wallet/mintAsset.ts, ironfish/src/rpc/routes/wallet/postTransaction.ts, ironfish/src/rpc/routes/wallet/remove.ts, ironfish/src/rpc/routes/wallet/rename.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts, ironfish/src/rpc/routes/wallet/use.ts, ironfish/src/rpc/routes/wallet/utils.test.ts, ironfish/src/rpc/routes/wallet/utils.ts
Refactoring some helper functions to facilitate move to standalone wallet
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Only pass in wallet to RPC helper function getAccount

ironfish-cli/src/commands/service/sync.ts, ironfish/src/rpc/adapters/memoryAdapter.ts, ironfish/src/rpc/routes/chain/__fixtures__/followChainStream.test.ts.fixture, ironfish/src/rpc/routes/chain/followChainStream.test.ts, ironfish/src/rpc/routes/chain/followChainStream.ts, ironfish/src/rpc/routes/chain/getTransaction.test.ts, ironfish/src/rpc/routes/chain/getTransaction.ts, ironfish/src/rpc/routes/chain/types.ts, ironfish/src/rpc/routes/wallet/getAccountTransaction.ts, ironfish/src/rpc/routes/wallet/getAccountTransactions.ts, ironfish/src/rpc/routes/wallet/types.ts
Standalone wallet will need fully serialized transactions from the block stream in order to attempt decryption.
Unit testing + testing chain stream locally
```
[X] Yes
```
```
[ ] Yes
```
=> Send serialized transactions on chain stream

ironfish/src/rpc/routes/chain/getBlock.test.ts, ironfish/src/rpc/routes/chain/getBlock.ts, ironfish/src/utils/error.ts, ironfish/src/wallet/wallet.ts
Encapsulates if a chain has a block with a call using the node client
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(ironfish): Check if chain has block from node client

ironfish/src/rpc/routes/chain/getAsset.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Fetch asset data from the chain using the node client
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(ironfish): Fetch chain asset from node client

ironfish/src/wallet/wallet.ts
Use the node client to fetch the head
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(ironfish): Fetch chain head from node client

ironfish/src/node.ts, ironfish/src/wallet/wallet.ts
the wallet no longer directly depends on a Blockchain instance
```
[ ] Yes
```
```
[ ] Yes
```
=> removes chain from wallet

ironfish/src/rpc/routes/wallet/createTransaction.ts
Switch over to use of node client for standalone wallet
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Use node client for wallet/createTransaction RPC

ironfish/src/rpc/routes/wallet/createTransaction.ts, ironfish/src/rpc/routes/wallet/rescanAccount.test.ts, ironfish/src/rpc/routes/wallet/rescanAccount.ts, ironfish/src/wallet/wallet.ts
Switch over wallet rescanAccounts RPC to use remote node client
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Use node client for wallet/rescanAccounts

Cargo.lock, ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish-rust/Cargo.toml, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump ironfish to 1.7.0, @ironfish/rust-nodejs to 1.6.0, Rust crate to 0.3.0

ironfish/src/node.ts, ironfish/src/walletNode.ts, ironfish/src/workerPool/pool.ts
Create the `WalletNode` as the entry point for a standalone wallet
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Create WalletNode to start standalone wallet

ironfish/src/migrations/data/029-backfill-assets-owner-wallet.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> fix: migration import path changed

ironfish/src/rpc/routes/wallet/sendTransaction.ts
Making conditional code a little more readable
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Refactor conditional send transaction

ironfish/src/blockchain/blockchain.ts, ironfish/src/fileStores/config.ts, ironfish/src/rpc/routes/chain/__fixtures__/followChainStream.test.ts.fixture, ironfish/src/rpc/routes/chain/followChainStream.test.ts, ironfish/src/rpc/routes/chain/followChainStream.ts, ironfish/src/wallet/remoteChainProcessor.test.ts, ironfish/src/wallet/remoteChainProcessor.ts, ironfish/src/wallet/wallet.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> hotfix to address OOM errors during wallet scanning

ironfish-cli/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps versions for hotfix 1.7.1

ironfish/src/rpc/routes/chain/followChainStream.ts, ironfish/src/rpc/routes/chain/getAsset.test.ts, ironfish/src/rpc/routes/chain/getAsset.ts, ironfish/src/rpc/routes/chain/types.ts
```
[x] Yes
```
https://github.com/iron-fish/website/pull/506
```
[ ] Yes
```
=> add owner field to follow chain stream and get assets RPCs

ironfish/src/rpc/routes/wallet/create.ts
Don't scan if there is no node client
Tested in  new directory
```
[ ] Yes
```
```
[ ] Yes
```
=> fix(ironfish): Check for node client in create

ironfish-cli/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Hotfix 1.7.1 merge master into staging

ironfish-cli/package.json, ironfish/package.json, simulator/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> Hotfix 1.7.1 staging master conflicts merge

ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture, ironfish/src/consensus/verifier.test.ts, ironfish/src/consensus/verifier.ts
Unit test
Wrote a script to verify there aren't any blocks that would trigger this new validation
```
[ ] Yes
```
```
[ ] Yes
```
=> reject blocks containing transactions with an incorrect version

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
Version was bumped with:
`./tools/version-bump.js --rust`
```
[ ] Yes
```
```
[ ] Yes
```
=> bump version for release (1.8.0)

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts
The wallet scan method checks the config, so clean up some unit tests to use that
Regenerate wallet fixtures
```
[ ] Yes
```
```
[ ] Yes
```
=> test(ironfish): Fix scan transaction wallet fixtures

ironfish/src/wallet/__fixtures__/wallet.test.slow.ts.fixture, ironfish/src/wallet/wallet.test.slow.ts
Set birthdays to null in slow wallet test
Regenerate fixtures
```
[ ] Yes
```
```
[ ] Yes
```
=> test(ironfish): Fix slow wallet test fixtures

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, simulator/package.json
Bump package versions
```
[ ] Yes
```
```
[ ] Yes
```
=> chore(cli,ironfish,rust-nodejs,simulator): Bump release versions

ironfish/src/webApi.ts
Related: https://github.com/iron-fish/ironfish-api/pull/1615
API change should be deployed after this PR is released, I believe
Closes IFL-1357
N/A
No
=> Add mint asset creator field to transaction api calls

ironfish/src/rpc/routes/chain/getBlock.test.ts, ironfish/src/rpc/routes/chain/getBlock.ts, ironfish/src/rpc/routes/chain/types.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add more information to getBlockResponse

ironfish/src/rpc/routes/wallet/types.ts, ironfish/src/rpc/routes/wallet/utils.ts
Adding mints and burns to RpcAccountTransaction. 
```
[ ] Yes
```
```
[ ] Yes
```
=> adding burns and mints to the account transaction

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts
Fix test that was failing when fixtures were regenerated 
```
[ ] Yes
```
```
[ ] Yes
```
=> Fix fixture regeneration failures for diable wallet test

ironfish/src/rpc/clients/socketClient.ts
After a connection is established, `RpcSocketClient` does not register any error handler. If a communication error happens (for example, the connection is dropped abruptly), then Node.js will terminate the whole process with an error like this:
```
node:events:491
throw er; // Unhandled 'error' event
^
Error: read ECONNRESET
at __node_internal_captureLargerStackTrace (node:internal/errors:491:5)
at __node_internal_errnoException (node:internal/errors:621:12)
at TCP.onStreamRead (node:internal/stream_base_commons:217:20)
Emitted 'error' event on Socket instance at:
at emitErrorNT (node:internal/streams/destroy:151:8)
at emitErrorCloseNT (node:internal/streams/destroy:116:3)
at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
errno: -104,
code: 'ECONNRESET', …
```
=> Handle socket read/write errors

ironfish/package.json, yarn.lock
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump SDK version to 1.10.1

ironfish/src/fileStores/config.ts
Found this typo. I'm going to yeet these config options as well.
=> Fix typo in comment

ironfish-cli/src/commands/service/bridge/deposit.ts, ironfish/src/webApi.ts
defaults to hardcoded bridge address instead of reading bridge address from api
manual testing
```
[ ] Yes
```
```
[ ] Yes
```
=> removes deposit api dependency

ironfish-cli/src/snapshot.ts
Progress on unzipping was incorrect and handling other possible errors when parsing URLs
Tested snapshot locally
```
[ ] Yes
```
```
[ ] Yes
```
=> Fix some small bugs in snapshot code

ironfish/src/sdk.ts, ironfish/src/utils/asset.ts
Adding some exports to the SDK that are used in the node app
```
[ ] Yes
```
```
[ ] Yes
```
=> Add exports to sdk package

ironfish/src/network/peers/addressManager.ts
Slight readability improvement in the address manager
```
[ ] Yes
```
```
[ ] Yes
```
=> removing filter connected identities from address manager

ironfish/src/network/peers/peerManager.ts
We maintain this pattern pretty consistently throughout the codebase, and it makes it hard to find the start/stop functions easily because they're buried deep in the file compared to other classes.
N/A
N/A
=> Move PeerManager start/stop functions near constructor

ironfish/src/network/peers/peerManager.ts, ironfish/src/utils/array.ts
Removing duplicate check for empty list when sampling array
```
[ ] Yes
```
```
[ ] Yes
```
=> Simplify ArrayUtils.sample

ironfish/src/network/peers/peerCandidates.ts
Removing unused function from peer candidates class
```
[ ] Yes
```
```
[ ] Yes
```
=> Rahul removing unused function in peer candidates

ironfish/src/network/peers/peerManager.ts
Simplify error handling in identify message code
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Simplify error handling in identify message code

ironfish/src/network/peers/peerCandidates.ts, ironfish/src/network/peers/peerConnectionManager.ts, ironfish/src/network/peers/peerManager.ts
Easier to read/ understand code. Some improvements to double checking the peer candidate object exists
```
[ ] Yes
```
```
[ ] Yes
```
=> simplifying logic in peer connection manager - connectToEligiblePeers and eventLoop

ironfish/src/network/peers/peerManager.ts
No logic changes, just some readability improvements
```
[ ] Yes
```
```
[ ] Yes
```
=> tryDisposePeer and getConnectionRetry

ironfish/src/fileSystems/nodeFileSystem.ts
When writing a file, we now do a couple extra things:
- Write to a temp file first, and rename if the write was successful. Usually, renames are considered atomic operations, so if it fails for some reason, we should keep the original file intact.
- After writing the contents of the file, we call sync to try to force a buffer flush and ensure the file is written before we close it. NodeJS implements this functionality by adding a `flush` option to the `writeFile` utility function starting in NodeJS 21, but it will be a long time before we can use that.
Closes IFL-1795
Manual testing, keyStore and fileStore unit tests
N/A
N/A
=> Implement a safer file write function

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Version bump for release
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump to version 1.12.0

ironfish/src/rpc/adapters/ipcAdapter.test.ts, ironfish/src/rpc/adapters/tcpAdapter.test.ts, ironfish/src/sdk.test.ts
These were satisfied and the tests now pass
Run tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove TODO around test network ID

ironfish-cli/src/commands/logs.ts, ironfish-cli/src/commands/reset.ts, ironfish-cli/src/commands/start.ts, ironfish-cli/src/commands/stop.ts, ironfish-cli/src/commands/wallet/prune.ts
This is only used by the standalone wallet and should not be referenced in the CLI.
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove IronfishNode from CLI

ironfish/src/network/peerNetwork.ts
Setting up for upcoming changes to bootstrap node start up connections
```
[ ] Yes
```
```
[ ] Yes
```
=> Peer network breakup start function

ironfish-cli/README.md
```
[ ] Yes
```
```
[ ] Yes
```
=> test merging into feature branch Update README.md

ironfish/src/fileStores/config.ts
This causes issues if you ever re-use these types anywhere else.
Just changes types, no testing needed.
```
[ ] Yes
```
```
[ ] Yes
```
=> Fix types using '' instead of string

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Bumps SDK, CLI to 1.14.0, as well as related packages.
```
[ ] Yes
```
```
[ ] Yes
```
=> SDK and CLI v1.14.0

.github/workflows/publish-binaries.yml
Cleans up naming in github action for publishing binaries
```
[ ] Yes
```
```
[ ] Yes
```
=> chore: cleanup gha name

Cargo.lock, ironfish-rust-nodejs/Cargo.toml, ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/index.js, ironfish-rust-nodejs/src/fish_hash.rs, ironfish-rust-nodejs/src/lib.rs, ironfish-rust-nodejs/tests/fish_hash.test.slow.ts
Adds the `fish_hash` dependency and napi bindings for the dependency
Unit tests
N/A
N/A
=> Add fish_hash library and bindings

ironfish-rust/src/transaction/mints.rs
Not sure how this broken test passed CI from a previous PR. Fixing the test. 
```
[ ] Yes
```
```
[ ] Yes
```
=> test_add_signature test fix

ironfish-rust-nodejs/src/frost.rs, ironfish-rust-nodejs/src/lib.rs
NAPI binding for corresponding PR here
https://github.com/iron-fish/ironfish/pull/4554
Will add integration test once primitives are exported.
```
[ ] Yes
```
```
[ ] Yes
```
=> feat: frost round one napi binding

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Use createdAt as head of imported account

ironfish/src/sdk.ts
There's no reason to declare this variable in this scope.
```
[ ] Yes
```
```
[ ] Yes
```
=> Move auth token into if statement

ironfish/src/rpc/response.ts
This is optional and you don't need to pass it in
```
[ ] Yes
```
```
[ ] Yes
```
=> Default timeout to null

ironfish/src/rpc/routes/node/getStatus.ts
not sure why this is on the next line
```
[ ] Yes
```
```
[ ] Yes
```
=> Move weird await usage

ironfish/src/rpc/adapters/httpAdapter.ts
This fixes a typo pointed out in another PR
No testing needed
```
[ ] Yes
```
```
[ ] Yes
```
=> Fixed typo of delimiter

ironfish/src/wallet/wallet.ts
Removes an unused function 
```
[ ] Yes
```
```
[ ] Yes
```
=> remove get unspent notes

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Version bump to 1.17.0
```
[ ] Yes
```
```
[ ] Yes
```
=> Version bump to CLI version 1.17.0

ironfish/src/blockHasher.ts, ironfish/src/mining/pool.ts, ironfish/src/mining/stratum/stratumServer.ts, ironfish/src/mining/utils.ts, ironfish/src/serde/BlockTemplateSerde.ts
Update the reference pool to correctly validate FishHash blocks
Running pool locally against FishHash miners
```
[ ] Yes
```
```
[ ] Yes
```
=> Pool validates FishHash blocks

ironfish-rust-nodejs/src/structs/transaction.rs
NAPI binding that allows construction of `Transaction` (signed) from `UnsignedTransaction` using aggregated signature shares from FROST signing protocol.
N/A, ser/de only
```
[ ] Yes
```
```
[ ] Yes
```
=> feat: sign_frost napi binding

ironfish/src/migrations/data/030-value-to-unspent-note.ts, ironfish/src/migrations/data/030-value-to-unspent-note/new/index.ts, ironfish/src/storage/database/encoding.test.ts, ironfish/src/storage/database/encoding.ts, ironfish/src/wallet/walletdb/walletdb.test.ts, ironfish/src/wallet/walletdb/walletdb.ts
Adds a new PrefixArrayEncoding that will ultimately replace the existing PrefixEncoding. The goal here is a slightly better syntax.
```
[ ] Yes
```
```
[ ] Yes
```
=> Add new PrefixArrayEncoding

ironfish-rust/src/transaction/tests.rs
- creates ProposedTransaction
- builds transaction to create UnsignedTransaction
- signs transaction to create PostedTransaction
- verifies transaction
```
[ ] Yes
```
```
[ ] Yes
```
=> adds test of simple transaction signing

ironfish/src/blockchain/blockchain.ts
Removing unecessary double deserialization of the seed genesis block on Blockchain startup
Unit tests + running node on mainnet on a new node
```
[ ] Yes
```
```
[ ] Yes
```
=> Only deserialize genesis seed block once in chain

ironfish/src/blockHasher.test.ts, ironfish/src/consensus/consensus.ts, ironfish/src/node.ts, ironfish/src/strategy.test.slow.ts
This was just an alias for another type.
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove TestnetConsensus

ironfish/src/migrations/data/024-unspent-notes.ts, ironfish/src/migrations/data/024-unspent-notes/new/index.ts, ironfish/src/migrations/data/030-value-to-unspent-note.ts, ironfish/src/migrations/data/030-value-to-unspent-note/old/index.ts, ironfish/src/wallet/walletdb/walletdb.ts
Changes unspentNoteHashes to PrefixArrayEncoding as well.
Existing tests cover this.
```
[ ] Yes
```
```
[ ] Yes
```
=> Convert unspentNoteHashes to PrefixArrayEncoding

Cargo.lock, ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/lib.rs, ironfish-rust/Cargo.toml, ironfish-rust/src/mining/mine.rs, ironfish-rust/src/mining/thread.rs, ironfish-rust/src/mining/threadpool.rs, ironfish/src/mining/poolMiner.ts, ironfish/src/mining/soloMiner.ts
Add FishHash CPU support to the rust miner
```
[ ] Yes
```
```
[ ] Yes
```
=> Use FishHash in rust miner

ironfish-cli/src/commands/miners/start.ts, ironfish/src/fileStores/config.ts, ironfish/src/mining/soloMiner.ts
Add FishHash support to the solo CPU miner
Running devnet with FishHash enabled locally
```
[ ] Yes
```
```
[ ] Yes
```
=> Add FishHash to solo miner

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/lib.rs, ironfish-rust-nodejs/tests/unsigned.test.slow.ts, ironfish/src/testUtilities/fixtures/transactions.ts
Step 1 in the overall goal of updating the account value to include nsk instead of pgk. 
```
[ ] Yes
```
```
[ ] Yes
```
=> replacing pgk with nsk

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps versions for sdk v1.19.0

ironfish/src/networks/definitions/devnet.ts, ironfish/src/networks/definitions/mainnet.ts, ironfish/src/networks/definitions/testnet.ts
Just a small change to make peoples life better.
1. Consensus parameters
2. Genesis block
3. Definition
```
[ ] Yes
```
```
[ ] Yes
```
=> Reorganize each definition file to be

ironfish/src/consensus/consensus.ts, ironfish/src/networks/network.test.ts, ironfish/src/networks/network.ts, ironfish/src/node.ts
Now the network creates the consensus from the definition.
```
[ ] Yes
```
```
[ ] Yes
```
=> Move Consensus into Network

ironfish/src/blockchain/blockchain.ts, ironfish/src/blockchain/database/blockchaindb.ts
Moving some database logic to the BlockchainDB class to simplify Blockchain logic
Unit tests + running node locally on mainnet
```
[ ] Yes
```
```
[ ] Yes
```
=> Use helper functions for updating blockchain sequence->hashes index

ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/multisig/createSigningShare.ts, ironfish/src/rpc/routes/multisig/index.ts
Fixes issue with types, naming, and export of RPC.
```
[ ] Yes
```
```
[ ] Yes
```
=> fix: typo signing share rpc naming

ironfish/src/rpc/routes/wallet/multisig/aggregateSigningShares.ts
Multisig/Frost related.
We moved the RPCs for multisig into the `wallet` namespace so we should be using an account directly in the RPCs.
https://github.com/iron-fish/ironfish/pull/4682
N/A, Integration test will cover this.
```
[ ] Yes
```
```
[ ] Yes
```
=> refactor: aggregate signing share account

ironfish-cli/src/commands/wallet/multisig/create-signing-package.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(IFL-2173): create signing package cli

Cargo.lock
```
[ ] Yes
```
```
[ ] Yes
```
=> Update `ironfish-frost` to the latest version

ironfish-cli/src/commands/wallet/multisig/sign.ts, ironfish/src/rpc/routes/wallet/multisig/aggregateSignatureShares.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> fix(cli,ironfish): Fix broadcast in aggregating shares

ironfish-cli/src/commands/wallet/multisig/account/create.ts
Remove hard-coded 0
```
[ ] Yes
```
```
[ ] Yes
```
=> fix(cli): Fix hardcoded name

ironfish-cli/src/commands/wallet/multisig/account/create.ts
changes 'Identifier' to 'Identity' to match logic changes
```
[ ] Yes
```
```
[ ] Yes
```
=> fixes leftover use of 'Identifier' term

Cargo.lock, ironfish-rust-nodejs/Cargo.toml, ironfish-rust-nodejs/src/fish_hash.rs, ironfish-rust/Cargo.toml, ironfish-rust/src/mining/mine.rs, ironfish-rust/src/mining/thread.rs
Upgrading FishHash to include changes suggested by audit
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Upgrade fish hash to include audit changes

ironfish/src/wallet/walletdb/accountValue.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> removing duplicate import name

ironfish/src/blockHasher.test.ts, ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture, ironfish/src/blockchain/blockchain.test.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/consensus/consensus.test.ts, ironfish/src/consensus/consensus.ts, ironfish/src/consensus/verifier.ts, ironfish/src/networks/definitions/devnet.ts, ironfish/src/networks/definitions/mainnet.ts, ironfish/src/networks/definitions/testnet.ts, ironfish/src/networks/networkDefinition.ts, ironfish/src/rpc/routes/chain/getConsensusParameters.ts, ironfish/src/testUtilities/nodeTest.ts
Code implementation of [this discussion](https://discourse.ironfish.network/t/91)
Writing unit tests and simulations
```
[ ] Yes
```
```
[ ] Yes
```
=> Add checkpoints to blockchain

ironfish-cli/src/commands/wallet/multisig/create-signature-share.ts, ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish/src/primitives/unsignedTransaction.ts
Add some useful logs when participants are creating signature shares
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli,ironfish,rust-nodejs): Render unsigned transaction details for signature share creation

ironfish/src/rpc/routes/wallet/__fixtures__/createTransaction.test.ts.fixture
fixtures generated before asset ownership changes disabled for devnet
regenerates fixtures on latest staging
```
[ ] Yes
```
```
[ ] Yes
```
=> fixess bad fixtures for createTransaction

ironfish-cli/src/commands/wallet/notes/combine.ts
Small refactor that makes `fetchNotes` more generalizable. 
This is a small step towards adding a countdown timer for all transaction related CLI commands
```
[ ] Yes
```
```
[ ] Yes
```
=> notes length check refactor

.github/release.yml
Adding some rules to make auto generated release notes better
```
[ ] Yes
```
```
[ ] Yes
```
=> Add some rules for auto-release notes

Cargo.lock
This update ships new features and improvements related to authentication and encryption.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Update to the latest version of ironfish-frost

ironfish-rust-nodejs/src/frost.rs
- Removed unnecessary `Vec` allocations
- Removed unnecessary uses of `Result`
- Compactified expressions / removed boilerplate code
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Improvements to `ironfish-rust-nodejs/src/frost.rs`

ironfish-cli/src/commands/wallet/balances.ts
Head sequence shows a hash instead of the sequence
```sh
ironfish/ironfish-cli on  rohan/ifl-2304-add-authentication-to-commitments [$] via 🐳 desktop-linux is 📦 v1.20.0 via  v20.10.0
❯ f wallet:balances -d ~/.ironfish-testnet --all
yarn run v1.22.18
$ yarn build && yarn start:js wallet:balances -d /home/rohan/.ironfish-testnet --all
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:balances -d /home/rohan/.ironfish-testnet --all
Account: default
Asset Name Asset Id Available Balance Confirmed Balance Unconfirmed Balance Pending Balance Head Hash Head Sequence
────────── ──────── ───────────────── ───────────────── ─────────────────── ─────────────── ───────── …
```
=> fix(cli): Fix `wallet:balances` to render sequence in sequence column

ci/lintHeaders.sh
Simplifies the logic in the headers lint check
```
[ ] Yes
```
```
[ ] Yes
```
=> simplifying lint headers script

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
2.0 version bump for the mainnet hardfork
```
[ ] Yes
```
```
[ ] Yes
```
=> v2.0 Version Bump

ironfish-cli/src/commands/wallet/multisig/signature/create.ts
Add a new line before rendering the signature share
Manual testing
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli): Update new line in `wallet:multisig:signature:create`

.github/pull_request_template.md
Adds the labels to the PR template.
```
[ ] Yes
```
```
[ ] Yes
```
=> Add labels to PR template

ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts, ironfish-cli/src/commands/wallet/multisig/commitment/create.ts, ironfish-cli/src/commands/wallet/multisig/participant/create.ts, ironfish-cli/src/commands/wallet/multisig/participant/index.ts, ironfish-cli/src/commands/wallet/multisig/participants/index.ts, ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts, ironfish-cli/src/commands/wallet/multisig/signature/create.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> multisig command in index

ironfish-cli/src/commands/wallet/notes/combine.ts, ironfish-cli/src/utils/note.ts
This function will be reused by wallet send and wallet notes combine commands.
```
[ ] Yes
```
```
[ ] Yes
```
=> Move fetchNotes to utils

ironfish/src/networks/definitions/mainnet.ts
Add checkpoint for the first FishHash block on mainnet
Running node locally on mainnet with the checkpoint + syncing node locally with checkpoint
```
[ ] Yes
```
```
[ ] Yes
```
=> Add FishHash mainnet checkpoint

ironfish-cli/package.json, yarn.lock
Add command for generating autocomplete files for CLI
Local testing
```
[ ] Yes
```
```
[ ] Yes
```
=> Add autocomplete for SDK

ironfish/src/assets/assetsVerificationApi.test.ts, ironfish/src/assets/assetsVerificationApi.ts, ironfish/src/assets/assetsVerifier.test.ts, ironfish/src/fileStores/verifiedAssets.ts
Adds the additional fields outlined in the spec. There's more renaming to be done, but I didn't want to clobber the git diff too much in one PR.
Unit tests
N/A
No
=> add additional fields to asset verification code

ironfish/src/storage/levelup/store.ts, ironfish/src/storage/levelup/transaction.ts
our LevelupStore implementation has several methods for iterating over keys and values in the store: 'getAllIter', 'getAll', 'getAllValuesIter', 'getAllValues', 'getAllKeysIter', and 'getAllKeys'. these methods all use 'getAllIter', which always deserializes all keys and all values. this results in unnecessary deserialization of values when using 'getAllKeysIter' or 'getAllKeys' and likewise for keys when using 'getAllValuesIter' or 'getAllValues'.
updates LevelupStore to use lazy deserialization: only deserializing keys or values during iteration if required.
- changes LevelupTransaction to cache using database-encoded keys as Buffers instead of converting those Buffers to strings
- defines LevelupStore._getAllIter to yield encoded keys. yields encoded values where deserialized value is …
=> lazy deserialization in levelup db iter methods

ironfish/src/wallet/walletdb/walletdb.ts
removes 'replaceNullifierToNoteHash'
```
[ ] Yes
```
```
[ ] Yes
```
=> removes unused walletDb method

Cargo.lock, ironfish-rust-nodejs/src/multisig.rs, supply-chain/config.toml, supply-chain/imports.lock
Also pruned some cargo-vet audits while there.
Unit tests.
```
[ ] Yes
```
```
[ ] Yes
```
=> Update ironfish-frost to the latest version

ironfish-rust/src/frost_utils/split_spender_key.rs
`split_spender_key` currently has a lot of code copied from `SaplingKey::new`, but it doesn't need to: the results these computations can be obtained directly from `SaplingKey`.
* unit tests
* verified through some assertions (now removed) the the keys generated with the old code correspond to the keys outputted by the new code
```
[ ] Yes
```
```
[ ] Yes
```
=> Simplify the code for `split_spender_key`

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/utils/currency.ts
This was causing an issue where minting a new asset would default to the iron default of 8 decimal places instead of the custom asset default of 0
No
No
=> Fix an issue with the mint command where the id was not properly being passed

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Bumping version for 2.2.0 release
```
[ ] Yes
```
```
[ ] Yes
```
=> Bump version to 2.2.0

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/multisig.rs, ironfish-rust/src/frost_utils/account_keys.rs, ironfish-rust/src/frost_utils/mod.rs, ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/wallet/multisig/dkg/index.ts, ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts, ironfish/src/rpc/routes/wallet/multisig/dkg/round3.ts
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Implement `wallet/multisig/dkg/round3` RPC

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
Indicate exactly which public packages need to be passed in the interactive prompt
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli): Improve prompt in round3 to indicate which packages from what round are needed

ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
Additional tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Multisig DKG: test that, at the end of round 3, participant identities are recorded correctly

ironfish/src/utils/currency.test.ts, ironfish/src/utils/currency.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove unused renderIron function

ironfish-cli/src/commands/wallet/multisig/dealer/create.ts, ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts, ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts, ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
Un-hide multisig commands
N/A
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli): Unhide multisig commands

ironfish-cli/package.json, ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/commands/wallet/chainport/status.ts, ironfish-cli/src/utils/asset.ts, ironfish-cli/src/utils/chainport.ts, yarn.lock
The following commands have been added to the wallet command:
1. chainport send - Send tokens from the Iron Fish network to a target network selected by a user.
2. chainport status - Check the status of a chainport transaction.
```
[ ] Yes
```
```
[ ] Yes
```
=> Chainport Bridge

ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/commands/wallet/chainport/status.ts, ironfish-cli/src/commands/wallet/transaction/index.ts, ironfish-cli/src/commands/wallet/transactions.ts, ironfish-cli/src/utils/chainport.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> use appropriate endpoints depending on mainnet/ testnet

ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/commands/wallet/chainport/status.ts, ironfish-cli/src/utils/chainport.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> adding testnet check to cli commands

ironfish-cli/src/commands/wallet/transaction/index.ts
Closes IFL-2558
Before:
After:
Manual
N/A
N/A
=> Asset balance deltas now display in the correct denomination

ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/utils/chainport.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Finding asset verification from chainport's api

ironfish-cli/src/commands/wallet/chainport/send.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> conditionally rendering asset id

ironfish-cli/src/commands/wallet/chainport/send.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> cli ux action for waiting for chainport network response

ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/commands/wallet/chainport/transaction.ts, ironfish-cli/src/utils/chainport.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Adding chainport target transaction summary

ironfish-cli/src/utils/chainport/chainport.ts, ironfish-cli/src/utils/chainport/index.ts, ironfish-cli/src/utils/chainport/types.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> moving chainport types to new file

ironfish-cli/src/commands/wallet/chainport/transaction.ts, ironfish-cli/src/commands/wallet/transaction/index.ts, ironfish-cli/src/commands/wallet/transactions.ts, ironfish-cli/src/utils/chainport/chainport.ts, ironfish-cli/src/utils/chainport/config.ts, ironfish-cli/src/utils/chainport/details.ts, ironfish-cli/src/utils/chainport/index.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> combining chainport transaction logic

ironfish/src/rpc/routes/node/getStatus.ts
This returns the logic that was here before for backwards compatability.
```
[ ] Yes
```
```
[ ] Yes
```
=> Return latest account head in node status

ironfish-cli/package.json, yarn.lock
Didn't think we were still using this but this broke docker builds, woops
N/A
N/A
=> upgrade oclif cli tool

ironfish/src/rpc/routes/wallet/setAccountHead.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Update comment on setAccountHead blocks field

ironfish/src/rpc/routes/wallet/serializers.ts, ironfish/src/rpc/routes/wallet/types.ts, ironfish/src/wallet/account/account.ts, ironfish/src/wallet/exporter/encoders/json.ts
This code would never execute.
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove version account version default

ironfish-cli/src/utils/chainport/types.ts
Chainport made some updates to the types of their API. This PR reflects those updates. This change does not impact our logic
Link to slack: https://iflabs.slack.com/archives/C0677Q1AGDD/p1718602248403459?thread_ts=1718290421.506409&cid=C0677Q1AGDD
```
[ ] Yes
```
```
[ ] Yes
```
=> update chainport transaction api types

ironfish/src/workerPool/tasks/workerMessages.test.perf.ts
uses new DecrypNotesRequest format
```
[ ] Yes
```
```
[ ] Yes
```
=> fixes workerMessages perf test

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
version bump for v2.4
```
[ ] Yes
```
```
[ ] Yes
```
=> version bump for v2.4

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust/src/transaction/evm.rs, ironfish-rust/src/transaction/tests.rs, ironfish/src/consensus/__fixtures__/verifier.evm.test.ts.fixture, ironfish/src/consensus/verifier.evm.test.ts, ironfish/src/primitives/__fixtures__/rawTransaction.test.ts.fixture, ironfish/src/primitives/evmDescription.ts, ironfish/src/primitives/rawTransaction.test.ts, ironfish/src/primitives/rawTransaction.ts, ironfish/src/primitives/transaction.test.ts, ironfish/src/primitives/transaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> gas limit/gas price on `EvmDescription`

ironfish-cli/src/commands/wallet/mint.ts
Adds ability to create unsigned transaction through the mint command. Adds the `unsignedTransaction` flag. 
```
[ ] Yes
```
```
[ ] Yes
```
=> add ability to create unsigned transaction for mint cli command

ironfish-cli/src/commands/wallet/burn.ts
Add unsigned transaction flag to `wallet:burn`. Similar to `wallet:send` and `wallet:mint`
```
[ ] Yes
```
```
[ ] Yes
```
=> Add unsigned transaction flag to `wallet:burn`

ironfish/src/blockchain/blockchain.ts, ironfish/src/blockchain/database/blockchaindb.ts, ironfish/src/consensus/verifier.ts, ironfish/src/storage/database/database.ts
moves the 'transaction' and 'withTransaction' methods from the abstract 'Database' class into a separate 'TransactionalDatabase' class
BlockchainDB extends TransactionalDatabase to allow it to reuse the implementation of 'withTransaction'
changes 'BlockchainDBTransaction' type annotations back to IDatabaseTransaction
```
[ ] Yes
```
```
[ ] Yes
```
=> defines TransactionalDatabase to reuse withTransaction

ironfish/src/blockchain/database/blockchaindb.ts, ironfish/src/blockchain/schema.ts
Adds store so that we can have contracts that own assets
```
[ ] Yes
```
```
[ ] Yes
```
=> adds store to map contract addresses to the assets they own

ironfish/src/utils/array.test.ts
These didn't have tests
I added new tests
```
[ ] Yes
```
```
[ ] Yes
```
=> Add test for ArrayUtils

ironfish-cli/package.json, yarn.lock
Updating to latest version for compatibility with latest zondax release
```
[ ] Yes
```
```
[ ] Yes
```
=> update to latest ledger hq version

.github/workflows/deploy-npm-ironfish-rust-nodejs.yml, .github/workflows/publish-binaries.yml, ironfish-cli/package.json, ironfish/package.json, ironfish/src/wallet/scanner/scanState.ts
hotfix to address memory leak introduced in v2.4.0
includes changes to GitHub Actions workflows to fix release process
```
[ ] Yes
```
```
[ ] Yes
```
=> hotfix 2.4.1

ironfish-cli/package.json, ironfish/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> version bump for v2.4.1

ironfish/src/wallet/wallet.ts
I think this will allow us to add a new accounts accessor that just returns the accounts itself.
```
[ ] Yes
```
```
[ ] Yes
```
=> Rename Wallet.accounts -> Wallet.accountsById

ironfish-cli/src/commands/repl.ts, ironfish-cli/src/commands/wallet/prune.ts, ironfish/README.md, ironfish/src/rpc/routes/wallet/addTransaction.ts, ironfish/src/rpc/routes/wallet/getAccounts.ts, ironfish/src/rpc/routes/wallet/getAccountsStatus.ts, ironfish/src/wallet/scanner/walletScanner.ts, ironfish/src/wallet/wallet.ts
Replace listAccounts() with this new property.
```
[ ] Yes
```
```
[ ] Yes
```
=> Add Wallet.accounts property

ironfish-cli/src/commands/chain/rewind.ts
This is part of the CLI usability audit.
https://linear.app/if-labs/issue/IFL-2778/make-chainrewind-hidden
```
[ ] Yes
```
```
[ ] Yes
```
=> Make chain:rewind command hidden

ironfish-cli/src/commands/chain/transactions/info.ts, ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/chain/getTransaction.ts
```
Block hash:          0000001d808cf14f0666620f48b058fd8fb454baf968d975b7a6bb698428ffb3
Transaction hash:    18e6c735e0c950ad9c859f7f593fb442c834dcf43e2d5b1575fae1499e3d225d
Fee:                 $IRON 0.00000002
Expiration sequence: 575110
Transaction size:    2.35 KiB
Notes output:        3
Notes spent:         2
Mint count:          0
Burn count:          0
```
Closes IFL-2776
N/A
=> Add `chain:transactions:info` command

ironfish/src/consensus/__fixtures__/verifier.evm.test.slow.ts.fixture, ironfish/src/consensus/verifier.evm.test.slow.ts, ironfish/src/consensus/verifier.ts, ironfish/src/evm/evm.ts, ironfish/src/testUtilities/fixtures/transactions.ts, ironfish/src/testUtilities/helpers/transaction.ts
Verifies mints are valid, does not verify native asset.
test passes
```
[ ] Yes
```
```
[ ] Yes
```
=> Shield verification of mints 

ironfish/src/consensus/__fixtures__/verifier.evm.test.slow.ts.fixture, ironfish/src/consensus/verifier.evm.test.slow.ts, ironfish/src/consensus/verifier.ts
Verification of burns, with mocked `TxResult`
tests pass
```
[ ] Yes
```
```
[ ] Yes
```
=> add check for verification of unshield/burns

ironfish-cli/package.json, ironfish-cli/src/commands/chain/assets/info.ts, ironfish-cli/src/commands/chain/broadcast.ts, ironfish-cli/src/commands/chain/download.ts, ironfish-cli/src/commands/chain/export.ts, ironfish-cli/src/commands/chain/forks.ts, ironfish-cli/src/commands/chain/power.ts, ironfish-cli/src/commands/chain/prune.ts, ironfish-cli/src/commands/chain/status.ts, ironfish-cli/src/commands/chain/transactions/info.ts, ironfish-cli/src/commands/wallet/prune.ts
Adjusted them to fit the style guide here https://github.com/iron-fish/ironfish/blob/master/ironfish-cli/STYLE_GUIDE.md#command-description
Run `ironfish chain`
```
[ ] Yes
```
```
[ ] Yes
```
=> Adjust descriptions of chain commands

.github/workflows/deploy-npm-ironfish-rust-nodejs.yml, .github/workflows/publish-binaries.yml, ironfish-cli/package.json, ironfish/package.json, ironfish/src/wallet/scanner/scanState.ts, yarn.lock
Merge pull request #5116 from iron-fish/hotfix/2.4.1
hotfix 2.4.1
```
[ ] Yes
```
```
[ ] Yes
```
=> adds hotfix changes from master for v2.4.1

ironfish-cli/src/commands/evm/deploy-contract.ts
updates the deploy-contract command example to deploy the global contract to a hardcoded address
proves that we can deploy the contract to a predetermined address of our choosing
```
[ ] Yes
```
```
[ ] Yes
```
=> deploys global contract to hardcoded address

ironfish/src/rpc/routes/chain/getBlock.ts, ironfish/src/rpc/routes/chain/getBlocks.ts, ironfish/src/rpc/routes/chain/utils.ts
These were duplicated under the wrong file. Must have been due to a merge issue.
```
[ ] Yes
```
```
[ ] Yes
```
=> Delete dupliacate RPC serializers

ironfish-cli/src/command.ts, ironfish-cli/src/commands/chain/blocks/info.ts, ironfish-cli/src/ui/json.ts
Also implements it for the `chain:blocks:info` command
Closes IFL-2819
Yes
N/A
=> Add ability to use JSON flag with CLI commands

ironfish-cli/src/commands/chain/assets/info.ts, ironfish-cli/src/commands/chain/benchmark.ts, ironfish-cli/src/commands/mempool/status.ts, ironfish-cli/src/commands/miners/pools/status.ts, ironfish-cli/src/commands/rpc/status.ts, ironfish-cli/src/commands/status.ts, ironfish-cli/src/commands/wallet/balance.ts, ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/commands/wallet/transaction/index.ts
This converts a lot of our manually configured card layouts to use our new ui card element. This simplifies the formatting so we have more consistent, easier to use card formatting across the CLI.
Manual
N/A
N/A
=> Convert existing commands to use new ui card

ironfish-cli/STYLE_GUIDE.md
This should help users figure out how to design the output of their commands.
```
[ ] Yes
```
```
[ ] Yes
```
=> Update style guide to document command output info

ironfish-cli/src/flags.ts
=> Move the flags in baseFlags into the global category

ironfish/src/blockchain/__fixtures__/blockchain.test.ts.fixture, ironfish/src/evm/evm.ts
Fund global account for unshielding funds
```
[ ] Yes
```
```
[ ] Yes
```
=> Fund global account

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Version bump for release
```
[ ] Yes
```
```
[ ] Yes
```
=> version bump for v2.5

ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/tests.rs
Adds private/public iron delta to the evm description
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```
=> balancing successful for private/public iron

ironfish-cli/package.json, ironfish-cli/src/commands/chain/download.ts, ironfish-cli/src/commands/chain/export.ts, ironfish-cli/src/commands/chain/forks.ts, ironfish-cli/src/commands/chain/prune.ts, ironfish-cli/src/commands/chain/status.ts
**Before**
```
TOPICS
chain       show asset information
```
**After**
```
TOPICS
chain       commands for the blockchain
```
```
[ ] Yes
```
```
[ ] Yes
```
=> Update chain description

ironfish-cli/package.json, yarn.lock
I don't think anyone used this, and it's confusing showing up in the list.
```
[ ] Yes
```
```
[ ] Yes
```
=> Delete autocomplete plugin

ironfish-cli/package.json, ironfish-cli/src/commands/browse.ts, ironfish-cli/src/commands/config/index.ts, ironfish-cli/src/commands/faucet.ts, ironfish-cli/src/commands/fees.ts, ironfish-cli/src/commands/logs.ts, ironfish-cli/src/commands/migrations/index.ts, ironfish-cli/src/commands/peers/index.ts, ironfish-cli/src/commands/repl.ts, ironfish-cli/src/commands/reset.ts, ironfish-cli/src/commands/rpc/status.ts, ironfish-cli/src/commands/start.ts, ironfish-cli/src/commands/status.ts, ironfish-cli/src/commands/stop.ts, ironfish-cli/src/commands/wallet/accounts.ts, ironfish-cli/src/commands/workers/status.ts
In an attempt to make them follow the style guide
```
[ ] Yes
```
```
[ ] Yes
```
=> Update command descriptions

ironfish/src/consensus/verifier.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add verification for native asset shield and unshield

ironfish-cli/src/ui/table.ts
=> use ui json element instead of custom json parsing

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/index.js
Forgot to update the output index files in #5218
N/A
```
[ ] Yes
```
```
[ ] Yes
```
=> chore(rust-nodejs): Update Napi JS index file

ironfish-cli/src/commands/debug.ts
=> CLI debug command uses card output and has json support

ironfish-cli/src/commands/fees.ts
=> CLI fees command uses card output and has json support

ironfish/src/rpc/routes/eth/__fixtures__/sendRawTransaction.test.ts.fixture, ironfish/src/rpc/routes/eth/sendRawTransaction.test.ts, ironfish/src/rpc/routes/eth/sendRawTransaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add support for shield/unshield in eth/sendRawTransaction

ironfish-cli/src/commands/migrations/index.ts, ironfish-cli/src/commands/migrations/revert.ts, ironfish-cli/src/commands/migrations/start.ts, ironfish/src/migrations/migrator.ts
...
```
[ ] Yes
```
```
[ ] Yes
```
=> update migrations descriptions, migrations list supports json

ironfish-cli/src/commands/peers/add.ts, ironfish-cli/src/commands/peers/banned.ts, ironfish-cli/src/commands/peers/info.ts
=> update peers descriptions, show -> info, add json to info

ironfish-cli/src/commands/rpc/status.ts, ironfish-cli/src/commands/rpc/token.ts
=> update rpc descriptions, add json output

ironfish-cli/src/commands/workers/status.ts
=> update workers status cli desc, add json

ironfish/src/networks/definitions/evmnet.ts, ironfish/src/networks/networkDefinition.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add evm network

ironfish-cli/src/commands/wallet/transactions/post.ts
Making these commands consistent with our style guide
```
[ ] Yes
```
```
[ ] Yes
```
=> Move wallet:post -> wallet:transactions:post

ironfish-cli/src/commands/wallet/transactions/watch.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> move `wallet:transaction:watch` -> `wallet:transactions:watch`

ironfish-cli/src/commands/wallet/transactions/import.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> move `wallet:transaction:import` -> `wallet:transactions:import`

ironfish-cli/src/commands/wallet/transactions/decode.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> move `wallet:transaction:view` -> `wallet:transactions:decode`

ironfish-cli/src/commands/wallet/transactions/post.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add hiddenAlias for wallet:transactions:post

ironfish-cli/src/commands/wallet/transactions/sign.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> move `wallet:sign` -> `wallet:transactions:sign`

ironfish-cli/src/commands/wallet/transactions/info.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Move `wallet:transaction` to `wallet:transactions:info`

ironfish-cli/src/commands/evm/sendTransaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> updates sendTransaction to use sendRawTransaction

ironfish-cli/src/commands/wallet/index.ts
This is a part of the CLI usability audit.
```
[ ] Yes
```
```
[ ] Yes
```
=> Move `wallet:accounts` -> `wallet`

ironfish-cli/src/commands/wallet/transactions/decode.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> `wallet:transactions:decode` prompts for transaction before account

ironfish-cli/src/commands/wallet/address.ts, ironfish-cli/src/commands/wallet/assets.ts, ironfish-cli/src/commands/wallet/balance.ts, ironfish-cli/src/commands/wallet/balances.ts, ironfish-cli/src/commands/wallet/export.ts, ironfish-cli/src/commands/wallet/import.ts, ironfish-cli/src/commands/wallet/notes/index.ts, ironfish-cli/src/commands/wallet/reset.ts, ironfish-cli/src/commands/wallet/scanning/off.ts, ironfish-cli/src/commands/wallet/scanning/on.ts, ironfish-cli/src/commands/wallet/transactions.ts, ironfish-cli/src/commands/wallet/transactions/import.ts, ironfish-cli/src/commands/wallet/transactions/info.ts, ironfish-cli/src/commands/wallet/transactions/post.ts, ironfish-cli/src/commands/wallet/transactions/watch.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> move args to be above flags in wallet command definitions

ironfish-cli/src/commands/evm/sendTransaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Evm data in sendTransaction

ironfish/src/rpc/routes/wallet/getPublicKey.test.ts, ironfish/src/rpc/routes/wallet/getPublicKey.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Evm public address

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts, ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture, ironfish/src/wallet/walletdb/walletdb.test.ts, ironfish/src/wallet/walletdb/walletdb.ts
* Add decrypt method to wallet
* Add decrypt method to walletdb
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(ironfish): Add decrypt method to wallet

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/commands/wallet/import.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/multisig/account/participants.ts, ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts, ironfish-cli/src/commands/wallet/multisig/commitment/create.ts, ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts, ironfish-cli/src/commands/wallet/multisig/signature/create.ts, ironfish-cli/src/commands/wallet/notes/combine.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/commands/wallet/transactions/decode.ts, ironfish-cli/src/commands/wallet/transactions/post.ts
This makes it more clear that it expects a name of an account
```
[ ] Yes
```
```
[ ] Yes
```
=> Update wallet command flag description for account

ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/eth/__fixtures__/sendTransaction.test.ts.fixture, ironfish/src/rpc/routes/eth/index.ts, ironfish/src/rpc/routes/eth/sendTransaction.test.ts, ironfish/src/rpc/routes/eth/sendTransaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> eth/sendTransaction RPC (WIP)

ironfish-cli/src/commands/wallet/create.ts, ironfish-cli/src/commands/wallet/transactions.ts, ironfish-cli/src/commands/wallet/transactions/info.ts, ironfish-cli/src/commands/wallet/transactions/post.ts, ironfish-cli/src/commands/wallet/transactions/watch.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Rename account args to name in wallet

ironfish-cli/package.json, ironfish-cli/src/commands/wallet/address.ts, ironfish-cli/src/commands/wallet/assets.ts, ironfish-cli/src/commands/wallet/balance.ts, ironfish-cli/src/commands/wallet/balances.ts, ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/create.ts, ironfish-cli/src/commands/wallet/delete.ts, ironfish-cli/src/commands/wallet/export.ts, ironfish-cli/src/commands/wallet/import.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/notes/index.ts, ironfish-cli/src/commands/wallet/prune.ts, ironfish-cli/src/commands/wallet/rename.ts, ironfish-cli/src/commands/wallet/rescan.ts, ironfish-cli/src/commands/wallet/reset.ts, ironfish-cli/src/commands/wallet/scanning/off.ts, ironfish-cli/src/commands/wallet/scanning/on.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/commands/wallet/status.ts, ironfish-cli/src/commands/wallet/transactions.ts, ironfish-cli/src/commands/wallet/transactions/decode.ts, ironfish-cli/src/commands/wallet/transactions/import.ts, ironfish-cli/src/commands/wallet/transactions/info.ts, ironfish-cli/src/commands/wallet/transactions/post.ts, ironfish-cli/src/commands/wallet/transactions/sign.ts, ironfish-cli/src/commands/wallet/transactions/watch.ts, ironfish-cli/src/commands/wallet/use.ts, ironfish-cli/src/commands/wallet/which.ts
Makes command descriptions in line with the style guide.
```
[ ] Yes
```
```
[ ] Yes
```
=> Update wallet command descriptions

ironfish-cli/src/commands/wallet/transactions/delete.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add `wallet:transactions:delete` command

ironfish/src/networks/definitions/evmnet.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> adds default bootstrap node for evmnet

ironfish-cli/src/commands/evm/sendTransaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> update send cli command

ironfish-cli/src/commands/wallet/address.ts
Also convert the output to a card
```
[ ] Yes
```
```
[ ] Yes
```
=> Make wallet:address support JSON output

ironfish-cli/src/commands/wallet/address.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> displays evm public address in wallet:address

ironfish-cli/src/commands/evm/shield.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> fixes sending undefined nonce as string in shield

ironfish/src/primitives/rawTransaction.ts
signature fields were not included in raw transaction submitted to worker pool, so signature was replaced during post
manual testing running `evm:shield` command
```
[ ] Yes
```
```
[ ] Yes
```
=> serializes evm signature fields in RawTransactionSerde

ironfish/src/evm/evm.ts, ironfish/src/rpc/routes/eth/sendRawTransaction.ts, ironfish/src/rpc/routes/eth/sendTransaction.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> throwing exception if generated during evm simulation

ironfish-contracts/util/build_gold.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Evm gold build script

ironfish-contracts/contracts/Counter.sol
```
[ ] Yes
```
```
[ ] Yes
```
=> adds simple counter contract for testing

ironfish-cli/src/commands/evm/shield.ts
The parameters are strings not byte arrays, followup from @hughy PR.
```
[ ] Yes
```
```
[ ] Yes
```
=> updates addresses to be strings

ironfish-cli/src/commands/evm/sendTransaction.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/consensus/verifier.ts, ironfish/src/primitives/evmDescription.ts, ironfish/src/primitives/rawTransaction.test.ts, ironfish/src/primitives/rawTransaction.ts, ironfish/src/primitives/transaction.test.ts, ironfish/src/rpc/routes/eth/__fixtures__/sendTransaction.test.ts.fixture, ironfish/src/rpc/routes/eth/sendTransaction.test.ts, ironfish/src/rpc/routes/eth/sendTransaction.ts, ironfish/src/rpc/routes/wallet/createTransaction.test.ts, ironfish/src/wallet/wallet.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> add ability to send evm transaction that has no events

ironfish-cli/src/commands/evm/balance.ts
Previously, it required an ethereum address. Now this address is an optional parameter.
```
[ ] Yes
```
```
[ ] Yes
```
=> evm:balance gets default account balance by default

ironfish/src/wallet/account/account.ts
account.getBalances() will now always yield the native coin even if there are no notes for it.
Review with https://github.com/iron-fish/ironfish/pull/5308/files?diff=split&w=1
1. Run `ironfish wallet:balances`
2. See that iron balance is now visible
```
[ ] Yes
```
```
[ ] Yes
```
=> Always yield native balance in balances

ironfish/src/wallet/account/__fixtures__/account.test.ts.fixture, ironfish/src/wallet/account/account.test.ts, ironfish/src/wallet/account/account.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Closes IFL-2851
```
[ ] Yes
```
```
[ ] Yes
```
=> Disallow creation of accounts with no names

ironfish-cli/src/commands/wallet/balance.ts, ironfish-cli/src/commands/wallet/balances.ts, ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/export.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts, ironfish-cli/src/commands/wallet/multisig/commitment/create.ts, ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts, ironfish-cli/src/commands/wallet/multisig/signature/create.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/commands/wallet/transactions/post.ts, ironfish-cli/src/commands/wallet/transactions/watch.ts
This does nothing as all flags are by default required: false.
```
[ ] Yes
```
```
[ ] Yes
```
=> Delete required:false in flags which is default

ironfish-cli/src/commands/wallet/rename.ts
Changes the arg names to fit our new camel case underscore standard.
```
[ ] Yes
```
```
[ ] Yes
```
=> Change wallet:rename arg names

ironfish-cli/src/commands/status.ts
Show if the wallet is locked in the status command
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli): Update status to show when the wallet is locked

ironfish/src/rpc/routes/eth/estimateGas.ts
mocked until we get gas working
```
[ ] Yes
```
```
[ ] Yes
```
=> eth_estimateGas mocked

ironfish/src/rpc/routes/eth/ethRouter.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Fix ethRouter schema

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts, ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts, ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
In preparation for adding ledger support to the DKG rounds, this commit adds a `--ledger` flag to the `dkg round1`, `dkg round2`, and `dkg round3` commands. This flag will be used to specify that the user wants to use a Ledger device to perform DKG operations
```
[ ] Yes
```
```
[ ] Yes
```
=> Add ledger flag to dkg rounds

ironfish-cli/src/commands/wallet/decrypt.ts, ironfish-cli/src/commands/wallet/encrypt.ts, ironfish-cli/src/commands/wallet/lock.ts, ironfish-cli/src/commands/wallet/unlock.ts
Unhide encryption related commands
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli): Unhide encryption CLI commands

ironfish-cli/src/commands/wallet/multisig/dealer/create.ts, ironfish/src/wallet/index.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> feat(cli,ironfish): Improve export for AccountImport

ironfish-cli/src/commands/wallet/multisig/sign.ts
This fits with the latest changes in the ledger app/ sdk.
```
[ ] Yes
```
```
[ ] Yes
```
=> Review ledger transaction before commitment

ironfish-cli/src/ui/prompt.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Fix logical error on catching duplicates

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts, ironfish-cli/src/commands/wallet/multisig/sign.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Rename interactive step Identity to Participant Identity

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Rename newAccount flag in dkg create command to name

ironfish-cli/src/commands/wallet/chainport/send.ts, ironfish-cli/src/ui/prompts.ts, ironfish-cli/src/utils/chainport/config.ts
Mainnet support for chainport CLI
```
[ ] Yes
```
```
[ ] Yes
```
=> chainport config update with mainnet fields

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts, ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Fix minor typos (show -> shown)

ironfish-cli/src/utils/ledger.ts
Before it just said: "Do you confirm?"
```
[ ] Yes
```
```
[ ] Yes
```
=> explicityly asking to broadcast ledger transaction

ironfish-cli/src/commands/wallet/multisig/account/participants.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> wallet:multisig:account:participants displays your identity separately

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bumps versions for v2.7.0

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Store backup of ledger account on disk

ironfish-cli/src/multisigBroker/adapters/adapter.ts, ironfish-cli/src/multisigBroker/adapters/tcpAdapter.ts, ironfish-cli/src/multisigBroker/clients/client.ts, ironfish-cli/src/multisigBroker/messages.ts, ironfish-cli/src/multisigBroker/server.ts
Because this code was mostly copy and pasted from the stratum protocol.
```
[ ] Yes
```
```
[ ] Yes
```
=> Remove references to stratum in MultisigBroker

ironfish-cli/src/ui/retry.ts
This does a better thing depending on the error.
```
[ ] Yes
```
```
[ ] Yes
```
=> Render error in ui/retry

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
This will prefer the account name if specified and always use or create that.
```
[ ] Yes
```
```
[ ] Yes
```
=> Prefer the account name as the participant name

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
This unifies the ledger vs non ledger identity creation in `ironfish wallet:multisig:dkg:create`
```
[ ] Yes
```
```
[ ] Yes
```
=> Cleanup DKG identity creation

ironfish-cli/package.json, yarn.lock
We use this in our ledger integration
```
[ ] Yes
```
```
[ ] Yes
```
=> Add @ledgerhq/errors package to package.json

ironfish-cli/package.json, yarn.lock
We were using different versions so this was not the same instance of the class.
```
[ ] Yes
```
```
[ ] Yes
```
=> Use the same ledgerhq/errors as other lib

ironfish-cli/src/ui/ledger.ts
This uses the new ledger ui.
```
[ ] Yes
```
```
[ ] Yes
```
=> Switch sendTransaction to use ledger UI

ironfish-cli/src/ui/ledger.ts
Now they know when to look down at their device
```
[ ] Yes
```
```
[ ] Yes
```
=> Have ledger ui tell the user to approve

ironfish-cli/src/ledger/ledger.ts
DKG app uses a custom return code for rejection that is separate from the single signer app.
```
[ ] Yes
```
```
[ ] Yes
```
=> Handle DKG reject message

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Show account name public packages

ironfish-cli/src/commands/wallet/chainport/send.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> unhide chainport:send

ironfish-cli/src/ledger/ledger.ts
This happens during operations occasionally when the transport fails.
```
[ ] Yes
```
```
[ ] Yes
```
=> Handle DeviceDisconnected Error

ironfish-cli/src/commands/wallet/multisig/sign.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> use numberprompt for total participants in multisig sign

ironfish-cli/package.json, yarn.lock
This removes console logs and is the final release verison.
```
[ ] Yes
```
```
[ ] Yes
```
=> Upgrade ledger-ironfish-js to 1.0.0

ironfish-cli/src/ledger/ledger.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Handle ledger DisconnectDevice error

ironfish-cli/src/ledger/README.md
These are the error codes that are changing with the new 0.5.4 version of the DKG app.
```
[ ] Yes
```
```
[ ] Yes
```
=> Update readme documentation on error codes returned

ironfish-cli/src/ledger/ledgerMultiSigner.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add an ability to request identity based on approval

ironfish-cli/src/commands/wallet/multisig/ledger/backup.ts
This makes the UI nicer by using our new reliable ledger connector.
```
[ ] Yes
```
```
[ ] Yes
```
=> Upgrade ledger:backup cmd to use ledger action

ironfish-cli/src/multisigBroker/clients/client.ts
error messages from the multisig broker server include the originating messageId in the error message. the client should cancel retries for a message that results in an error message from the server
Closes IFL-3067
```
[ ] Yes
```
```
[ ] Yes
```
=> client cancels retry on error message

ironfish-cli/src/multisigBroker/errors.ts, ironfish-cli/src/multisigBroker/messages.ts, ironfish-cli/src/multisigBroker/server.ts
error codes from the server will help the client to determine how to handle the error message
Closes IFL-3072
```
[ ] Yes
```
```
[ ] Yes
```
=> adds error codes to multisig broker error messages

ironfish-cli/src/multisigBroker/clients/client.ts
throws an error if client is unable to connect to multisig broker server within one minute
repurposes unused property 'disconnectUntil' into 'tryConnectUntil'
Closes IFL-3055
manual testing
```
[ ] Yes
```
```
[ ] Yes
```
=> adds connection timeout to multisig broker client

ironfish-cli/src/multisigBroker/clients/client.ts, ironfish-cli/src/multisigBroker/constants.ts, ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts, ironfish-cli/src/multisigBroker/utils.ts
Closes IFL-3059
```
[ ] Yes
```
```
[ ] Yes
```
=> removes unused code from multisigBroker module

supply-chain/audits.toml, supply-chain/config.toml, supply-chain/imports.lock
Pruned some exempted crates.
```
cargo vet
```
N/A
N/A
=> Ran `cargo vet prune`

ironfish-rust/src/transaction/tests.rs
this test sometimes takes over 4 minutes on CI. by splitting it up, we normalize the run time across the test shards, creating a more consistent run time between the CI shards. other upside is that if one of these test fails, it will be easier to see at a glance which one is failing by the name.
local: cargo test --release
ci tests
```
[ ] Yes
```
```
[ ] Yes
```
=> split very long running test into smaller tests

ironfish-cli/package.json, ironfish/package.json, package.json, yarn.lock
this resolves some security alerts from github
ran node
ran tests
N/A
N/A
=> update axios from 1.7.2 to 1.7.7

.github/workflows/rust_ci.yml
Running with `--all-features` will catch issues like the one fixed in PR #5599.
Observe the CI output
N/A
N/A
=> Run `clippy` with `--all-features`

ironfish-rust/src/transaction/tests.rs
adds a test that signs a transaction with a different key than the key used to generate proofs for the transaction
the test confirms that signing the transaction with the wrong key succeeds, but the transaction does not verify
```
[ ] Yes
```
```
[ ] Yes
```
=> validates the point of failure for signing tx with wrong key

ironfish/src/rpc/routes/wallet/create.test.ts, ironfish/src/rpc/routes/wallet/createAccount.test.ts
I don't know why these tests were made slow, but they are very fast to run so I'm upgrading them to not slow tests.
```
@ironfish/sdk  src/rpc/routes/wallet/create.test.ts (5.003 s)
✓ should create an account (129 ms)
✓ should set the account as default (68 ms)
✓ should fail if name already exists (80 ms)
✓ should start scanning transactions for the new account (82 ms)
@ironfish/sdk  src/rpc/routes/wallet/createAccount.test.ts
✓ should create an account (96 ms)
✓ should set the account as default (67 ms)
✓ should fail if name already exists (80 ms)
✓ should start scanning transactions for the new account (84 ms)
✓ should set account createdAt if passed (93 ms)
✓ should set account createdAt to null (94 ms)
```
Run `yarn test`
Does this change require any updates to the Iron Fish Docs (ex. …
=> Make account tests not slow

.github/workflows/ci.yml, ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/index.js
Failed run: https://github.com/iron-fish/ironfish/actions/runs/11712239302/job/32622473563?pr=5626
```
[ ] Yes
```
```
[ ] Yes
```
=> Add lint for rust binding changes

ironfish/src/wallet/walletdb/walletdb.ts
remove setNoteHashSequence from the walletDb and moves the logic inline into saveDecryptedNote; the only method that called setNoteHashSequence
existing unit tests
```
[ ] Yes
```
```
[ ] Yes
```
=> inlines logic of setNoteHashSequence

ironfish-cli/src/commands/wallet/transactions/index.ts, ironfish-cli/src/flags.ts
```
[ ] Yes
```
```
[ ] Yes
```
=> Add new date flag and use it in transactions cmd

Cargo.lock, ironfish-rust-wasm/Cargo.toml, ironfish-rust-wasm/src/lib.rs, ironfish-rust-wasm/src/transaction/mod.rs, supply-chain/audits.toml, supply-chain/imports.lock
Added bindings for `Transaction`
Unit tests
N/A
N/A
=> WASM: expose the `Transaction` type

README.md
The list was outdated and I couldnt find the other projects.
=> Update readme repos list

ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
when a user passes the '--ledger' flag to the
'wallet:multisig:commitment:create' command they intend to use a Ledger device to create a signing commitment. the identity used _must_ be the identity from the Ledger device, so read the identity from the device instead of from the walletDB
Closes IFL-3169
1. start devnet node
2. mine devnet blocks
3. create multisig account using ledger
4. fund multisig account with transaction from default account
5. create unsigned transaction from multisig account
6. create signing commitment with multisig account and ledger
```
[ ] Yes
```
Is this a …
=> reads identity from ledger in 'wallet:multisig:commitment:create'

ironfish-rust-wasm/src/note.rs, ironfish-rust/src/note.rs
```
[ ] Yes
```
```
[ ] Yes
```
=> WASM: add bindings for `Note.commitment_point()`

ironfish-rust-wasm/src/circuits.rs, ironfish-rust-wasm/src/lib.rs, ironfish-rust/src/transaction/spends.rs, ironfish-zkp/src/circuits/mint_asset.rs, ironfish-zkp/src/circuits/output.rs, ironfish-zkp/src/circuits/spend.rs, ironfish-zkp/src/primitives/value_commitment.rs
```
[ ] Yes
```
```
[ ] Yes
```
=> WASM: add bindings for zero-knowledge circuit structs

ironfish-rust-wasm/src/transaction/mod.rs, ironfish-rust-wasm/src/transaction/proposed.rs
```
[ ] Yes
```
```
[ ] Yes
```
=> WASM: add bindings for `ProposedTransaction`

Cargo.lock, ironfish-rust-wasm/Cargo.toml
```
[ ] Yes
```
```
[ ] Yes
```
=> 0.2.0 wasm version bump

ironfish/src/rpc/routes/chain/followChainStream.ts
followChainStream: removed main key from block.
```
[X] Yes - https://github.com/iron-fish/website/pull/783
```
```
[X] Yes - breaking-change-rpc
```
=> followChainStream: removed main key from block

ironfish-rust-wasm/DEPLOYMENT.md, ironfish-rust-wasm/README.md
```
[ ] Yes
```
```
[ ] Yes
```
=> Update wasm README with deployment instructions

ironfish-cli/package.json, ironfish/package.json
```
[ ] Yes
```
```
[ ] Yes
```
=> bump version to 2.12
