iron-fish/ironfish

ironfish/src/network/peers/peerCandidates.ts

Peer name was not getting set when a new PeerList comes in
Tested locally + unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Pass along peer name to candidate list

---

ironfish-cli/Dockerfile

Moved from `node:18-bullseye-slim` to `node:20-bookworm-slim`.
Built a new image and tested with fishtank.
No doc change needed.

Update the Docker image to Node 20 and Debian Bookworm

---

ironfish-cli/src/commands/start.ts

Uses the function added in #4344 in the CLI start command to bootstrap the node's network identity.
```
[ ] Yes
```
```
[ ] Yes
```

Use sdk getPrivateIdentity function

---

ironfish/src/migrations/data/000-template.ts
ironfish/src/migrations/data/014-blockchain.ts
ironfish/src/migrations/data/015-wallet.ts
ironfish/src/migrations/data/016-sequence-to-tx.ts
ironfish/src/migrations/data/017-sequence-encoding.ts
ironfish/src/migrations/data/018-backfill-wallet-assets.ts
ironfish/src/migrations/data/019-backfill-wallet-assets-from-chain.ts
ironfish/src/migrations/data/020-backfill-null-asset-supplies.ts
ironfish/src/migrations/data/021-add-version-to-accounts.ts
ironfish/src/migrations/data/021-add-version-to-accounts/schemaOld.ts
ironfish/src/migrations/data/022-add-view-key-account.ts
ironfish/src/migrations/data/023-wallet-optional-spending-key.ts
ironfish/src/migrations/data/024-unspent-notes.ts
ironfish/src/migrations/data/025-backfill-wallet-nullifier-to-transaction-hash.ts
ironfish/src/migrations/data/026-timestamp-to-transactions.ts
ironfish/src/migrations/data/027-account-created-at-block.ts
ironfish/src/migrations/data/028-backfill-assets-owner.ts
ironfish/src/migrations/data/029-backfill-assets-owner-wallet.ts
ironfish/src/migrations/migration.ts
ironfish/src/migrations/migrator.ts
ironfish/src/node.ts
ironfish/src/walletNode.ts

This reduces the need for a full node for the Migrator dependencies. It allows anyone to run migrations that can satisify the migrator context requirements. This is useful for letting another CLI other than ironfish-cli run migrations, like the standalone CLI wallet.
```
[ ] Yes
```
```
[ ] Yes
```

Isolate migrator dependencies

---

ironfish/src/memPool/feeEstimator.ts
ironfish/src/memPool/recentlyEvictedCache.ts
ironfish/src/node.ts
ironfish/src/walletNode.ts

Many classes in the codebase take an optional logger parameter, but because it's optional, we often forget to pass it. Fixed a few places where logger should have been propagated through.
```
[ ] Yes
```
```
[ ] Yes
```

Fix some missing logger parameters

---

ironfish-cli/src/commands/peers/index.ts

Since we are displaying a single table, we can sort the output for the follow state.
```
[ ] Yes
```
```
[ ] Yes
```

Sorting for peers command 

---

ironfish/src/network/peers/peerConnectionManager.test.ts
ironfish/src/network/peers/peerConnectionManager.ts

When trying to maintain the max peer count allowed, the peer connection manager should not disconnect whitelisted nodes. The expectation for whitelisted nodes is that they should essentially be treated special and assumed to always be connected.
Closes IFL-1812
Unit test
N/A
N/A

PeerConnectionManager should not disconnect whitelisted nodes

---

ironfish/src/rpc/server.test.ts
ironfish/src/rpc/server.ts

This fixes a timing attack where the comparater for strings is not constant time. You can find the password over time by trying different bytes which allow you to get closer and closer to the actual password.
See https://en.wikipedia.org/wiki/Timing_attack
```
[ ] Yes
```
```
[ ] Yes
```

Fix an RPC timing attack

---

ironfish/src/network/peers/connections/webSocketConnection.ts
ironfish/src/network/peers/peer.ts
ironfish/src/network/peers/peerCandidates.ts
ironfish/src/network/peers/peerManager.ts

Changing WebSocketConnection to use address type instead of host and port
Running locally + unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Add WSAddress type to connection

---

ironfish-cli/src/commands/wallet/address.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/create.ts
ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/notes.ts
ironfish-cli/src/commands/wallet/post.ts
ironfish-cli/src/commands/wallet/rename.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/commands/wallet/use.ts

trimming the account name makes any account with leading or trailing whitespace unusable with the cli
we don't trim whitespace in the rpc or sdk when creating accounts, so it's possible for users to have accounts that have leading or trailing whitespace
limits scope from #4303 to account name inputs in the wallet only
manual testing
```
[ ] Yes
```
```
[ ] Yes
```

removes account name trimming in wallet cli inputs

---

ironfish/src/fileStores/config.ts

These config options are only used by an external repository and should not be added to the SDK config itself.
```
[ ] Yes
```
```
[x] Yes
```
Anyone who is using these will no longer be able to set these in the config.

Remove standalone wallet config from SDK

---

ironfish-cli/src/commands/wallet/send.ts

Add ability to send notes in the transaction command.
After a lot of back and forth with these PRs (https://github.com/iron-fish/ironfish/pull/4464 and https://github.com/iron-fish/ironfish/pull/4459), I decided it was best to at least get this out there for our users and work on more UX improvements including warnings for larger transactions in subsequent PRs. 
Manual testing. 
```
[ ] Yes
```
```
[ ] Yes
```

adding ability to select notes in the transaction send command

---

ironfish-rust/src/keys/public_address.rs
ironfish-rust/src/keys/test.rs
ironfish-rust/src/merkle_note.rs
ironfish-rust/src/note.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs

We do not use a diversifier in ironfish. This decision was made to allow auditability of fund sources when someone is receiving funds and uses their incoming view key to decrypt incoming funds.
Because of this transparency of sender, there is no longer a concept of a transmission key, which was an opaque version of the public address. This changes removes the vestigial naming.
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```

chore(IFL-1355): removes reference to transmission key

---

ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/spends.rs

The RedDSA specification (and the Rust crates that implement it) has slightly deviated from the code we're using. The changes make the signatures backward compatible, but the code we have written needs to change in order to be compatible. This commit adds some comments to the relevant code so that if in the future someone attempts to update the RedDSA crates, they won't have to spend hours to figure out what's wrong.
Not a code change
No doc change required

Add warnings about a change to the RedDSA spec

---

ironfish-cli/src/snapshot.ts

No significant issue here, but generally we should prefer performance.now or process.hrtime when tracking durations to avoid odd bugs with computer clocks changing. Similar PR was made to the node app: https://github.com/iron-fish/ironfish-node-app/pull/69
Tested that snapshots still time out properly when disconnecting from the Internet.
```
[ ] Yes
```
```
[ ] Yes
```

Use performance.now for snapshot duration

---

ironfish-cli/src/commands/wallet/status.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.test.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.ts

We don't provide an RPC for determining whether an account is view-only. We could do this by exporting the account and checking for the presence of a spending key, but it'd be more straightforward to provide a flag directly in getAccountsStatus.
Fixes IFL-1900
Added a test to verify viewOnly is set.
```
[x] Yes
```
https://github.com/iron-fish/website/pull/574
```
[ ] Yes
```

Return whether account is view only from getAccountsStatus RPC

---

ironfish-cli/src/commands/wallet/import.ts

Currently, if someone passes `--path` as well as an invalid argument or flag, the command will try to parse the invalid arg/flag as an account and fail. This attempts to add a clearer error message to that situation. I didn't want to log the exact unexpected argument in case someone pasted both their private key and a --path argument, and I felt it was better to clarify with the user if both were passed rather than just assuming one vs the other. Open to opinions here though.
Ran `yarn start wallet:import --json --path ~/default.json` and ensured the message displays, then removed `--json` and ensured the import works.
related …

Display a clearer error when passing --path and an invalid argument

---

ironfish-cli/src/commands/peers/add.ts
ironfish/src/rpc/routes/peer/addPeer.test.ts
ironfish/src/rpc/routes/peer/addPeer.ts

Wait for the result of the connection before returning from the add peer command
Tested locally + unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Wait for connection status on add peer command

---

.github/workflows/publish-binaries.yml
tools/build-binary.go

Previous build used [caxa](https://github.com/leafac/caxa), this is problematic for two reasons:
1. Original system had a malformed binary that prevented signing https://github.com/leafac/caxa/issues/40
2. The package is now archived.
This now removes dependency on that code (although it uses quite a bit of the `go` code from that repo) and rewrites the binary packaging to make the binary signable.
Build successful here (contains downloadable binaries):
https://github.com/iron-fish/ironfish/actions/runs/7187149184?pr=4479#artifacts
Note:
I tried notarizing with Apple, which seems successful, but the application is still being flagged as malicious, will need to do some digging as to why.
Runs:
```
$ ./ironfish
Unpackaging ironfish application, this may take a minute when run for the first …
```

feat: signable binary

---

ironfish-cli/package.json
ironfish/package.json

No rust changes. Ran `node ./tools/version-bump.js`
```
[ ] Yes
```
```
[ ] Yes
```

bumping versions release v 1.15

---

.github/workflows/ci-regenerate-fixtures.yml
.github/workflows/perf_test.yml

Tests don't run on Node 18 any more, but the perf tests and regenerate fixtures actions were still using Node 18.
```
[ ] Yes
```
```
[ ] Yes
```

Bump perf test and regenerate fixture node versions to 20

---

.github/workflows/publish-binaries.yml

Sign binaries for macos/windows
Build successful for all:
https://github.com/iron-fish/ironfish/actions/runs/7254275380?pr=4490#artifacts
Windows signed correctly:
MacOS signed correctly (no rejection at runtime of binary):
```
[ ] Yes
```
```
[ ] Yes
```

Sign ironfish binaries

---

.github/workflows/publish-binaries.yml

This PR addresses an issue with the binary github action (gha) builder/uploader.
Somehow there was no error when running when the `github.event*` were not populated (when testing on a feature branch). But when they were (during the context of a release) and error was occurring as zip file extention wasn't being included by the zip step. This explicitly adds the `.zip` extention and resolves the error.
For release v`1.15.0` I manually created a branch off master, retrieved the upload url for the release via github actions:
```bash
curl -H "Authorization: token :token" \
-H "Accept: application/vnd.github.v3+json" \
https://api.github.com/repos/iron-fish/ironfish/releases/tags/v1.15.0
```
And manually updated the `${{github.event.*}}` references to point to that release. The manually run …

fix: binary gha bug with zip filename

---

ironfish/src/network/blockFetcher.test.ts
ironfish/src/network/blockFetcher.ts
ironfish/src/network/messages/getBlockHeaders.ts
ironfish/src/network/messages/getBlocks.test.ts
ironfish/src/network/messages/getBlocks.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/network/testUtilities/helpers.ts
ironfish/src/network/utils/serializers.ts
ironfish/src/primitives/block.ts
ironfish/src/primitives/blockheader.ts

Preparation for upcoming hashing algorithm changes. The hashing algorithm becomes more expensive and requires a 75mb light cache to calculate. Instead of doing this calculation in the network message deserialization we should do it more explicitly further up the chain. For this we need another representation of a block without a hash (RawBlockHeader + RawBlock)
```
[ ] Yes
```
```
[ ] Yes
```

Use RawBlock for network messages

---

Cargo.lock
ironfish-rust/Cargo.toml

Upgrades `blake3` to allow compatibility with `reddsa` frost which currently a dependency being pulled in by `ironfish-frost`.
https://github.com/iron-fish/ironfish-frost/blob/main/Cargo.toml#L16
This version of blake3 was released on Sept 20th.
https://github.com/BLAKE3-team/BLAKE3/releases/tag/1.5.0
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

chore: upgrade blake3

---

Cargo.lock
ironfish-mpc/Cargo.toml

Upgrades byteorder dependency to be compatible with version needed for `ironfish-rust`
```
[ ] Yes
```
```
[ ] Yes
```

chore: Upgrade ironfish mpc dependency

---

ironfish-cli/src/commands/miners/pools/start.ts
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/notes/combine.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/explorer.ts
ironfish/src/fileStores/config.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/webhooks/index.ts
ironfish/src/mining/webhooks/webhookNotifier.ts
ironfish/src/rpc/clients/client.ts

This PR accomplishes two tasks:
1. The CLI now shows the correct link for transactions whether they are made on mainnet or testnet
2. Any logic relating to ironfish's block explorer is removed from the SDK
The second change is related to an ongoing effort to only have information that is necessary for the blockchain operation in the SDK. Finding blocks and transactions on the block explorer is a layer on top of the network but not part of the network itself. For this it seems to make sense to remove this information from the SDK to the CLI.
- Tested running a pool on mainnet + testnet to see if urls match
- Tested transaction send on testnet to see if URL is correct …

Move block explorer urls to CLI client side and out of the SDK

---

ironfish/src/genesis/makeGenesisBlock.ts

BlockHeader class fields will be changed to be readonly so that a BlockHeader fields cannot be accidentally updated without updating the hash. This requires updating genesis block creation to not directly modify these block header fields
Unit tests + creating a new genesis block locally
```
[ ] Yes
```
```
[ ] Yes
```

Use readonly BlockHeader fields in genesis block creation

---

Cargo.lock
ironfish-rust/Cargo.toml

1. Add `ironfish-frost = { git = "https://github.com/iron-fish/ironfish-frost.git" }`
2. Update `rust-toolchain.toml` to `channel='nightly'` as minimal update is only available on nightly
3. run `cargo update -Z minimal-versions -p cpufeatures -p proc-macro2 -p serde`
4. revert change to `rust-toolchain.toml`
5. `cargo build` success
6. profit
tests pass
```
proc-macro2 1.0.59 -> 1.0.76 vs 1.0.60
```
```
[ ] Yes
```
```
[ ] Yes
```

chore: Update ironfish rust for frost minimal

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/structs/key_packages.rs
ironfish-rust-nodejs/src/structs/mod.rs

https://linear.app/if-labs/issue/IFL-2018/create-napi-struct-for-trusted-dealer-key-packages
```
[ ] Yes
```
```
[ ] Yes
```

adding trusted dealer key package napi struct

---

ironfish-cli/src/commands/wallet/notes/combine.ts

Minimum 1 second to combine notes. 
```
[ ] Yes
```
```
[ ] Yes
```

show minimum 1 second when combining notes

---

ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/unsigned.rs

Adds `UnsignedTransaction` structure boilerplate.
This will be used in Frost multisig, the unsigned transaction will be propagated to the participants for partial signing of mints/spends, which the coordinator will then accumulate into a finalized signature.
Currently there is no construction of this object, I will add a test when we add the `build` method on the `ProposedTransaction` which will generate an `UnsignedTransaction`.
```
[ ] Yes
```
```
[ ] Yes
```

feat: add unsigned transaction, unsigned mint, unsigned spend serde

---

ironfish/src/fileStores/config.test.ts
ironfish/src/fileStores/config.ts
ironfish/src/mining/poolDatabase/database.test.ts
ironfish/src/node.ts
ironfish/src/sdk.ts
ironfish/src/utils/yup.test.ts
ironfish/src/utils/yup.ts

https://github.com/iron-fish/ironfish/pull/4475/files?diff=split&w=1
This allows you to extend Config with custom extended config types. It
does now require you to pass the extended defeults into the Config()
constructor even if you are not extending it for type reasons.
This makes the Config API slightly more burdensome to use but it's a
small price to pay. This also leads to a breaking compatability change in
the SDK in the case that third parties are creating a Config. I'll document
this in the release notes.

Add ability to extend Config

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/headers.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/genesis/addGenesisTransaction.ts
ironfish/src/genesis/genesis.test.slow.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts
ironfish/src/network/messages/getBlocks.test.ts
ironfish/src/network/messages/getCompactBlock.test.ts
ironfish/src/network/messages/newCompactBlock.test.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/primitives/block.test.ts
ironfish/src/primitives/block.ts
ironfish/src/primitives/blockheader.test.ts
ironfish/src/primitives/blockheader.ts
ironfish/src/serde/BlockTemplateSerde.ts
ironfish/src/strategy.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/utils/blockutil.test.ts

FishHash will need a global cache as well as check activation height to hash a block header. Move block header hashing to strategy class to facilitate this
```
[ ] Yes
```
```
[ ] Yes
```

Hash block header with strategy class

---

benchmarks/benches/merkle_note.rs
ironfish-rust/src/merkle_note.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs

Previously the `spender_key` (root key) was being passed to `MerkleNote` constructor, `output.build()` and `mint.build()`. This caused unnecessary propagation of the the `SaplingKey` type to each of these structures.
This refactor passes only the keys that are required for the processes of constructing merkle notes, outputs, mints.
Example
Before:
```
MerkleNote::new(&spender_key, &note, &value_commitment, &diffie_hellman_keys);
```
After
```
MerkleNote::new(
&spender_key.outgoing_view_key(),
&note,
&value_commitment,
&diffie_hellman_keys,
);
```
tests pas
```
[ ] Yes
```
Is this a …

refactor: remove unneeded key build output mints

---

benchmarks/benches/transaction.rs
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust-nodejs/tests/transaction.test.slow.ts
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish/src/consensus/verifier.test.ts
ironfish/src/genesis/addGenesisTransaction.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/workerPool/tasks/createMinersFee.ts

when signing transactions with FROST we will not have a full, valid SaplingKey to pass as the 'spender_key'. FROST will also require that public key randomness is shared between signers with randomized parameters used as an input to signing.
spender_key is only used when posting ProposedTransactions, so these changes remove it from the struct and instead pass it as an input to each of the post functions
~~public_key_randomness is only used in the context of _partial_post, so these changes remove public_key_randomness from the struct and initialize a randomized public address from randomness only when needed~~
related documentation …

removes spender_key from ProposedTransaction

---

ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish-rust/src/transaction/utils.rs

This allows us to take the necessary keys and go from a `ProposedTransaction` (raw transaction data), to an `UnsignedTransaction`, which will be used for frost multisig.
This introduces a bit of code duplication in the `post()` and `build()` code paths of `ProposedTransaction`, I suggest we move the `post` and `_partial_post` methods to `UnsignedTransaction` so that we can deduplicate the logic. Then on `ProposedTransaction`.
New test passes
```
[ ] Yes
```
```
[ ] …
```

feat: Add build method proposed transaction

---

README.md

Added 'audit' section in the main README. 
Noticed we've had a few follow up questions about our audit and that generally people had a hard time finding it. Adding it in the main README to increase visibility.

Adding audit info in the main readme

---

ironfish-cli/package.json
ironfish-rust-nodejs/npm/darwin-arm64/package.json
ironfish-rust-nodejs/npm/darwin-x64/package.json
ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json
ironfish-rust-nodejs/npm/linux-arm64-musl/package.json
ironfish-rust-nodejs/npm/linux-x64-gnu/package.json
ironfish-rust-nodejs/npm/linux-x64-musl/package.json
ironfish-rust-nodejs/npm/win32-x64-msvc/package.json
ironfish-rust-nodejs/package.json
ironfish/package.json

- Bump CLI to 1.16.0
- Bump SDK to 1.16.0
- Bump rust to 1.13.0
```
[ ] Yes
```
```
[ ] Yes
```

Bump version to 0.16.0 CLI

---

ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs

1. This refactor removes code duplication for `_partial_post` and `build` method of `ProposedTransaction`. 
The original code path was 
Standard transaction:
`ProposedTransaction -> Transaction`
Multisig
`ProposedTransaction -> UnsignedTransaction -> Transaction` 
Now the code path is the same for both.
`ProposedTransaction -> UnsignedTransaction -> Transaction` 
2. Splits `build/_partial_post` logic into two separate methods where `add_change_notes` is added. This allows us to only add change notes to the `post`ed transactions, and not the miners fee.
NOTE: The `post` method bound to `ProposedTransaction` remains the same, so any higher level code should remain unchanged
tests pass …

refactor posting of proposed/unsigned transaction

---

ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/wallet/walletdb/accountValue.ts

multiSigKeys includes three fields needed for an account to participate in a FROST signing group: identifier, keyPackage, and proofGenerationKey
the identifier field is still to be determined as either a public key identifier for the participant, or a private key from which we can derive the public key identifier
the keyPackage is the key package generated for the participant during key generation and contains the participant's authorizing key shard
the proofGenerationKey is a key shared by the signing group that is needed for any participant to generate spend or mint proofs
```
[ ] …
```

adds optional multiSigKeys to AccountValue

---

ironfish/src/workerPool/tasks/workerMessages.test.perf.ts

The PR #4544 broke perf tests with new changes to typescript eslint. This fixes the account type.
```
[ ] Yes
```
```
[ ] Yes
```

Fix typescript eslint in perf tests

---

ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/lib.rs

Adds nodejs binding for `ProposedTransaction.build()` along with necessary deserialization.
```
[ ] Yes
```
```
[ ] Yes
```

feat: add napi method proposed transaction build

---

ironfish/src/rpc/routes/wallet/sendTransaction.test.slow.ts

This test passed on my PR and is failing on staging. Requires a 2 line fix
This is the original PR: https://github.com/iron-fish/ironfish/pull/4545
```
[ ] Yes
```
```
[ ] Yes
```

fixing wallet/sendTransaction slow test setting route test isready and synced to true

---

ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs

Adding a method to split a sapling key. 
Defining the ShareSecretConfig
These two items are dependencies for splitting the spender key which will be next
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```

Rahul/ifl 2044 1 add rust method to split a sapling key into shares for FROST

---

ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/wallet/walletdb/accountValue.ts

uses hex strings and stores multisig keys as buffers in the wallet db instead of using utf8 strings
this more closely matches the precedent set with our other keys and may simplify ser/de between TypeScript and Rust
```
[ ] Yes
```
```
[ ] Yes
```

stores multiSigKeys as hex instead of utf8

---

.gitignore
ironfish-rust/src/frost_utils/mod.rs
ironfish-rust/src/frost_utils/round_one.rs
ironfish-rust/src/lib.rs

Introduces a wrapper method for `frost::round1::commit` that provides a `u64` as seed. This is a convenience wrapper that allows us to avoid importing the `rand` library into in our `ironfish-rust-nodejs` bindings library. 
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

Frost round one rust

---

ironfish/src/blockHasher.test.ts
ironfish/src/blockHasher.ts
ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/defaultNetworkDefinitions.ts
ironfish/src/networkDefinition.ts
ironfish/src/node.ts
ironfish/src/sdk.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/strategy.test.ts
ironfish/src/strategy.ts
ironfish/src/testUtilities/nodeTest.ts

Add a consensus parameter for FishHash activation and use it to determine how to hash blocks according to seqeunce
- Unit tests
- running dev network
- syncing mainnet from genesis + monitoring RAM usage
```
[ ] Yes
```
```
[ ] Yes
```

Add FishHash to node verification

---

ironfish-rust/src/errors.rs
ironfish-rust/src/frost_utils/mod.rs
ironfish-rust/src/frost_utils/round_two.rs

Wrapper around [round two](https://github.com/ZcashFoundation/reddsa/blob/038505d6c51a13b58193d2767710227fcbe2b799/src/frost/redjubjub.rs#L328) of frost signing protocol.
The wrapper is implemented here only so that the `rand` package is not needed as dependency when using this function (ie in `ironfish-rust-nodejs`
A test here is difficult because it requires splitting the keys, performing round one, coordinator creating the signing package, and then round two can be performed. We should test this in a mock integration test once the rust components are completed.
```
[ ] Yes
```
Is …

feat: frost round two in ironfish-rust

---

ironfish-rust-nodejs/src/frost.rs

NAPI binding for round_two implementation (generating signature share).
Related `ironfish-rust` changes:
https://github.com/iron-fish/ironfish/pull/4558
```
[ ] Yes
```
```
[ ] Yes
```

feat: round_two napi binding for frost signing

---

ironfish-cli/src/commands/start.ts
ironfish/src/network/identity.ts
ironfish/src/node.ts
ironfish/src/sdk.test.ts
ironfish/src/sdk.ts

Currently, we manage the network identity in the `start` CLI command, which requires some code duplication for everyone instantiating the node (The CLI and the node app, at least). My goal with this PR was to bring the saving and loading into the SDK without changing any behavior when `generateNewIdentity` is used or an identity is passed in to `sdk.node()`. See below for the current vs new behaviors:
Saving and loading `networkIdentity` is delegated to the CLI start command.
* If no identity is set in internal.json, one will be generated when `sdk.node()` is called. It is then saved to `internal.json` in the `start` command.
* If an identity is set in internal.json, a new one will be generated when `sdk.node()` is called. Instead, the `start` command should load the identity and pass it …

Load or generate networkIdentity if none is passed

---

ironfish/src/rpc/routes/wallet/exportAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/account/encoder/bech32.test.ts
ironfish/src/wallet/account/encoder/bech32.ts
ironfish/src/wallet/account/encoder/json.test.ts

updates bech32 and json account encoders
adds multiSigKeys to RpcAccountImport
increases account version
```
[ ] Yes
```
```
[ ] Yes
```

adds multiSigKeys to account imports, exports

---

ironfish/src/rpc/routes/chain/getConsensusParameters.test.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.ts

Return all consensus parameters from the endpoint `chain/getConsensusParameters` and fix the naming of `allowedBlockFutureSeconds`
Unit tests + running HTTP adapter and making query
```
[ ] Yes
```
```
[X] Yes
```
Adds values to `chain/getConsensusParameters` and fixes the naming of `allowedBlockFutureSeconds`
https://github.com/iron-fish/website/pull/584

Add missing consensus params to chain/getConsensusParameters

---

ironfish/src/blockHasher.ts
ironfish/src/consensus/consensus.ts
ironfish/src/fileStores/config.ts
ironfish/src/node.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/strategy.test.ts
ironfish/src/strategy.ts

For power users like mining pools they may want to enable the full 4GB FishHash cache to increase performance of verifying block headers. This gives that option as a config value
```
[ ] Yes
```
```
[ ] Yes
```

Add config value for building the full FishHash context

---

ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/unsigned.rs

Creates signing package from the commitments received from frost round one of multisig protocol. `SigningPackage` is used in round two by participant to generate signing shares.
Note that I removed the return of `public_key_randomness`, since the participants should be able to retrieve this value from the `UnsignedTransaction` during validation.
N/A, wrapper method
```
[ ] Yes
```
```
[ ] Yes
```

feat: frost create signing package rust

---

ironfish/src/blockHasher.ts
ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/consensus/verifier.ts

Change the `Consensus.isActive` function to only take one sequence. It seems like all usages should want to by default use the activation sequence of the parameter so there should be no reason to have to pass it in. 
```
[ ] Yes
```
```
[X] Yes
```
This changes a the exported function `Consensus.isActive` in the SDK

Refactor isActive function on Consensus

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/tests.rs

Adds change notes as a method that is executed if the transaction is a miners fee (only special type of transaction that doesn't balance). The only reason this method exists is so that no change notes are added for miner fee transactions, otherwise it would always be run inside the `build()` method.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

chore: Ironfish rust refactor add change

---

ironfish/src/mining/pool.ts
ironfish/src/mining/soloMiner.ts

Add the consensus parameters to pool and solo miner to be able to switch at the FishHash activation sequence.
Unit test + running pool miner / solo miner on devnet
```
[ ] Yes
```
```
[ ] Yes
```

Query the full consensus parameters in the pool and solo miners

---

ironfish-cli/src/utils/fees.ts
ironfish/src/rpc/adapters/errors.ts
ironfish/src/rpc/adapters/httpAdapter.ts
ironfish/src/rpc/adapters/ipcAdapter.test.ts
ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts
ironfish/src/rpc/adapters/tcpAdapter.test.ts
ironfish/src/rpc/routes/chain/getBlock.test.ts
ironfish/src/rpc/routes/chain/getNetworkHashPower.test.ts
ironfish/src/rpc/routes/faucet/getFunds.ts
ironfish/src/rpc/routes/router.ts
ironfish/src/rpc/routes/wallet/create.test.slow.ts
ironfish/src/rpc/routes/wallet/create.ts
ironfish/src/rpc/routes/wallet/createAccount.ts
ironfish/src/rpc/routes/wallet/createTransaction.test.ts
ironfish/src/rpc/routes/wallet/createTransaction.ts
ironfish/src/rpc/routes/wallet/rename.test.ts
ironfish/src/rpc/routes/wallet/renameAccount.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.test.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts

To keep this consistent with other RPC types.
```
[ ] Yes
```
```
[ ] Yes
```

Rename ERROR_CODES TO RPC_ERROR_CODES

---

ironfish/src/rpc/adapters/httpAdapter.test.ts
ironfish/src/rpc/adapters/httpAdapter.ts
ironfish/src/rpc/clients/httpClient.ts
ironfish/src/rpc/clients/index.ts

This adds a new RpcHttpClient to the SDK which allows you to make HTTP requests against the RpcHttpAdapter.
**HttpAdapter Bugs**
- Crash if you send a chunk and then send a response because headers try to send twice
- Crash if you send an RpcValidationError after a chunk was sent because headers try to send twice
- Fixed not sending delimter before rendering an error to the client which would cause client to crash when parsing 2 messages as 1 JSON payload.
Still need to add tests and check on postman that some of the requests still work.
```
[ ] Yes
``` …

Add RpcHttpClient

---

ironfish-cli/src/commands/start.ts
ironfish/src/fileStores/config.ts
ironfish/src/networkDefinition.ts
ironfish/src/node.ts
ironfish/src/sdk.ts

The `customNetwork` config value was originally added to be able to pass in a path to a custom network definition when first initializing a node in a data directory. After the data directory has been initialized the `customNetwork` config value is useless because the network cannot be changed.
Passing along the `customNetworkPath` string accomplishes this same goal of being able to use a custom JSON file and removes the unecessary config option.
Started up a new node with the customNetwork flag on startup pointing to a JSON file
```
[ ] Yes
``` …

Remove customNetwork config value

---

ironfish-rust/src/frost_utils/split_spender_key.rs

This removes the need to clone the sapling key everywhere. 
```
[ ] Yes
```
```
[ ] Yes
```

split spender key takes a borrowed sapling key

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/structs/transaction.rs

adds binding for 'UnsignedTransaction::signing_package' to create a siging package from participant signing commitments
returns the SigningPackage serialized as a hex string
the signing package is created from the signing commitments that each participant generates in round 1. the signing package is then used as an input for generating signature shares in round 2 and for aggregating signature shares
```
[ ] Yes
```
```
[ ] Yes
```

adds napi binding for signing package

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/frost.rs

adds napi decorator to generate TypeScript
changes type of seed to u32 to support serialization from TypeScript
changes return type to String
```
[ ] Yes
```
```
[ ] Yes
```

fixes napi binding for frost round two

---

ironfish/src/primitives/rawTransaction.ts

refactors logic for adding spends, outputs, mints, and burns into '_build' to produce a 'NativeTransaction'
'build' uses '_build' to produce a NativeTransaction then calls 'build' on the NativeTransaction to produce a serialized UnsignedTransaction
the multisig signing flow will require an UnsignedTransaction for generating a signing package
```
[ ] Yes
```
```
[ ] Yes
```

adds build method to rawTransaction

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/unsigned.rs

1. adds a method to retrieve the public key randomness from the unsigned transaction
2. adds a napi binding and generates the ts code
```
[ ] Yes
```
```
[ ] Yes
```

public key randomness napi binding

---

ironfish-cli/src/command.ts

Currently a command run with only `--rpc.tcp.host` or `--rpc.tcp.port` will fail to connect to remote nodes unless the `--rpc.tcp` flag is also provided. This makes that argument optional in that case.
```
[ ] Yes
```
```
[ ] Yes
```

feat: enable rpc.tcp automatically if tcp port or host is provided

---

ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

Removes the check to prevent importing another account with the same view key. This allows the user to be multiple participants in a frost signing group. 
```
[ ] Yes
```
```
[ ] Yes
```

allow import an account with the same view key

---

ironfish/src/fileStores/config.ts
ironfish/src/networkDefinition.ts

The `networkDefinitionPath` value is used for storing custom network definitions in the node's data directory. There doesn't seem to be any good reason to make the path to this file customizable. Quite the opposite, it seems like it could add complexity if different dataDirs store their network definitions in different files. Making this static relative to the dataDir
Starting a new node with a customNetwork locally
```
[X] Yes
```
https://github.com/iron-fish/website/pull/593 …

Make config networkDefinitionPath static

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/structs/key_packages.rs
ironfish/src/wallet/wallet.test.slow.ts

This makes the `key_packages` part of the struct forward compatible with additional fields, also moves the split key to `frost.rs` since this is frost specific code.
N/A
```
[ ] Yes
```
```
[ ] Yes
```

chore: minor refactor split secret

---

ironfish-cli/src/commands/start.ts
ironfish/src/fileStores/config.ts
ironfish/src/networkDefinition.ts
ironfish/src/node.ts
ironfish/src/sdk.ts
ironfish/src/testUtilities/nodeTest.ts

The `networkId` config value is used to pass an id from the CLI to the node. After the `networkId` is set in a data directory though (on first startup) there is no need to change this config value. So it's essentially only used on the first run. It's better to not store this in the config if its unable to be set later on. 
Starting up a local node with the networkId flag and starting up a node with no flag to make sure it sets to mainnet
```
[X] Yes
```
https://github.com/iron-fish/website/pull/594
what …

Remove networkId from config

---

ironfish/src/rpc/adapters/tests/adapterTest.ts

These timeouts used to exist before I created the standardized testing suite.
The timeouts are needed because of the long time it takes to bind to ports on the github action runner hosts.  It's some times many seconds long.
```
[ ] Yes
```
```
[ ] Yes
```

Add timeouts back to RPC tests

---

Cargo.lock
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/tests/frost.test.slow.ts
ironfish-rust/Cargo.toml
ironfish/src/wallet/wallet.test.slow.ts

implements 'serialize' and changes constructor to deserialize from buffer
adds separate static 'random' method to generate random secret
pins ironfish-frost dependency to 'main' branch from git repo in order to pick up latest changes
updates tests to use 'random' instead of constructor
```
[ ] Yes
```
```
[ ] Yes
```

updates ParticipantSecret napi with serde

---

ironfish/src/rpc/routes/multisig/createSigningCommitment.test.ts
ironfish/src/rpc/routes/multisig/createSigningCommitment.ts
ironfish/src/rpc/routes/multisig/index.ts
ironfish/src/rpc/routes/multisig/types.ts

Adds RPC for creating signing commitment using the FROST protocol
Adds a type file that includes common types for the multi sign RPC
```
[ ] Yes
```
```
[ ] Yes
```

Rahul/ifl 2052 add multisig/createsigningcommitment

---

ironfish/src/primitives/unsignedTransaction.ts

This (or modification to the napi binding of `UnsignedTransaction`) is needed in order to generate fixtures for UnsignedTransactions.
N/A
```
[ ] Yes
```
```
[ ] Yes
```

chore: add UnsignedTransaction primitive

---

ironfish/src/rpc/routes/multisig/createSigningCommitment.test.ts

The test I wrote earlier didn't need the participants to be set up. This dramatically simplifies the test
```
[ ] Yes
```
```
[ ] Yes
```

chore: simplifies signing commitment test

---

README.md

Tests will segfault if you're not using Node.js 20, but I'm not sure that's documented anywhere clearly. I'll add this to the README for now, but it might be interesting to see if we could add something to the jest setup script that prints an error instead if you're using an older version of Node.js.
None needed for a README change.
Our developer docs don't reference this, that I've seen
```
[ ] Yes
```
```
[ ] Yes
```

Require Node.js 20 for tests in README

---

ironfish/src/fileStores/fileStore.test.ts
ironfish/src/fileStores/fileStore.ts

Our users seem to have a recurring problem where if a fileStore .json file is empty, the app crashes. This prevents it from happening in effect creating an empty json object, which then gets replaced with the required json object
```
[ ] Yes
```
```
[ ] Yes
```

filestore handles empty file

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust-nodejs/tests/unsigned.test.slow.ts
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish/src/primitives/rawTransaction.ts
ironfish/src/wallet/wallet.test.slow.ts

UnsignedTransaction.build currently takes both a ViewKey _and_ a PublicAddress as inputs
with a couple of small changes we can derive the public address from the view key so that we don't need to pass both of them around
this simplifies the signatures for build from TypeScript through napi and into Rust
```
[ ] Yes
```
```
[ ] Yes
```

derives public_address from view_key in build

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/multisig/__fixtures__/createSigningPackage.test.ts.fixture
ironfish/src/rpc/routes/multisig/createSigningCommitment.test.ts
ironfish/src/rpc/routes/multisig/createSigningPackage.test.ts
ironfish/src/rpc/routes/multisig/createSigningPackage.ts
ironfish/src/rpc/routes/multisig/createTrustedDealerKeyPackage.test.ts
ironfish/src/rpc/routes/multisig/index.ts
ironfish/src/testUtilities/fixtures/transactions.ts

1. Adds `createSigningPackage` RPC
2. Exposes typed RPC calls to the SDK for usage in tests (and js sdk)
3. Adds test fixture for `UnsignedTransaction`
```
[ ] Yes
```
```
[ ] Yes
```

feat(IFL-2027): createSigningPackage RPC

---

ironfish/src/testUtilities/fixtures/transactions.ts

one PR added a fixture, another PR changed the arguments of a function that the fixture called
when both PRs merged soon after each other, we ended up with a broken build
removes the extra argument
```
[ ] Yes
```
```
[ ] Yes
```

removes publicAddress from build args in fixture

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/genesis/addGenesisTransaction.ts
ironfish/src/genesis/genesis.test.slow.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts
ironfish/src/network/messages/getBlocks.test.ts
ironfish/src/network/messages/getCompactBlock.test.ts
ironfish/src/network/peerNetwork.test.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/node.ts
ironfish/src/primitives/block.test.ts
ironfish/src/primitives/block.ts
ironfish/src/primitives/blockheader.test.ts
ironfish/src/primitives/blockheader.ts
ironfish/src/serde/BlockTemplateSerde.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/strategy.test.ts
ironfish/src/strategy.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/utils/blockutil.test.ts

This is a move in an effort to delete Strategy. This moves the `Strategy.newBlock` and `Strategy.newBlockHeader` methods onto Blockchain and renames them to indicate they are just conversion functions.
```
[ ] Yes
```
```
[ ] Yes
```

Move RawBlock/Header constructors onto Bockchain

---

ironfish/src/wallet/wallet.test.slow.ts

The goal is to make it explicit in the test that the participants all have the same address.
This is solely a stylistic change. 
```
[ ] Yes
```
```
[ ] Yes
```

Changes frost test to use participantB address

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs

exposing 'sign' on the TypeScript side will be useful in the future for signing transactions with pre-computed proofs, and it will be useful now for testing
```
[ ] Yes
```
```
[ ] Yes
```

adds napi binding for UnsignedTransaction.sign

---

ironfish/src/primitives/__fixtures__/transaction.test.slow.ts.fixture
ironfish/src/primitives/transaction.test.slow.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts

This wallet test for createTransaction() was incorrectly in transaction.test.slow. It was testing an error as a result of calling Wallet.createTransaction().
```
[ ] Yes
```
```
[ ] Yes
```

Move wallet test to wallet.test.ts

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/genesis/genesis.test.slow.ts
ironfish/src/mining/manager.ts
ironfish/src/mining/minersFeeCache.ts
ironfish/src/primitives/transaction.test.slow.ts
ironfish/src/rpc/routes/miner/blockTemplateStream.test.slow.ts
ironfish/src/strategy.test.slow.ts
ironfish/src/strategy.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/testUtilities/fixtures/transactions.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/workerPool/job.test.slow.ts

This moves the createMinersFee() off Strategy to Blockchain.
```
[ ] Yes
```
```
[ ] Yes
```

Move createMinersFee() to Blockchain

---

ironfish/src/rpc/routes/multisig/createSigningShare.ts

Wrapper around `roundTwo` method, which I will rename in subsequent PR to `createSigningShare` (along with `roundOne`->`createSigningCommitment`).
At this point the test becomes pretty complicated just to test serialization. Decided not to add a test here since the underlying code is tested thoroughly.
```
[ ] Yes
```
```
[ ] Yes
```

feat: create signing share

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/frost.rs
ironfish-rust/src/frost_utils/mod.rs
ironfish-rust/src/frost_utils/signing_commitment.rs
ironfish-rust/src/frost_utils/signing_share.rs
ironfish-rust/src/transaction/tests.rs
ironfish/src/rpc/routes/multisig/createSigningCommitment.ts
ironfish/src/rpc/routes/multisig/createSigningShare.ts
ironfish/src/wallet/wallet.test.slow.ts

Cleanliness refactor that purely renames:
1. `roundOne` -> `createSigningCommitment`
2. `roundTwo` -> `createSigningShare`
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```

chore: refactor frost utils

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/structs/key_packages.rs
ironfish-rust/src/frost_utils/split_spender_key.rs
ironfish-rust/src/transaction/tests.rs
ironfish/src/rpc/routes/multisig/createTrustedDealerKeyPackage.ts
ironfish/src/wallet/wallet.test.slow.ts

we plan to store proofAuthorizingKey (nsk) on each account in the walletDb instead of storing proofGenerationKey (ak, nsk)
updates split_secret to return proofAuthorizingKey as part of the TrustedDealerKeyPackage instead of proofGenerationKey
propagates changes through napi
```
[ ] Yes
```
```
[ ] Yes
```

updates TrustedDealerKeyPackage to use proofAuthorizingKey

---

ironfish/src/rpc/routes/multisig/createTrustedDealerKeyPackage.test.ts
ironfish/src/rpc/routes/multisig/createTrustedDealerKeyPackage.ts

RPC returns proofAuthorizingKey (nsk) instead of proofGenerationKey
```
[ ] Yes
```
```
[ ] Yes
```

updates createTrustedDealerKeyPackage to return nsk

---

ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/__fixtures__/buildTransaction.test.ts.fixture
ironfish/src/workerPool/tasks/buildTransaction.test.ts
ironfish/src/workerPool/tasks/buildTransaction.ts
ironfish/src/workerPool/tasks/handlers.ts
ironfish/src/workerPool/tasks/workerMessage.ts
ironfish/src/workerPool/worker.ts

we offload PostTransaction to the worker pool because proof generation is compute intensive and could otherwise bog down the node process
creating an UnsignedTransaction using 'build' generates proofs and would create the same problem
the new job allows us to offload compute to the worker pool in RPC calls that build UnsignedTransactions
```
[ ] Yes
```
```
[ ] Yes
```

adds BuildTransaction worker job

---

ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/buildTransaction.test.ts
ironfish/src/workerPool/tasks/buildTransaction.ts

uses proofAuthorizingKey instead of proofGenerationKey as input to build
changes sizes of serialization for key change
```
[ ] Yes
```
```
[ ] Yes
```

fixes BuildTransaction worker task

---

ironfish/src/testUtilities/fixtures/transactions.ts

Now that the account schema contains proof authorizing key we can use it directly instead of generating the signing key
```
[ ] Yes
```
```
[ ] Yes
```

using proof authorizing key in useUnsignedTxFixture

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/wallet/__fixtures__/buildTransaction.test.ts.fixture
ironfish/src/rpc/routes/wallet/buildTransaction.test.ts
ironfish/src/rpc/routes/wallet/buildTransaction.ts
ironfish/src/rpc/routes/wallet/index.ts
ironfish/src/wallet/wallet.ts

buildTransaction takes a serialized RawTransaction and returns a serialized UnsignedTransaction
adds a 'build' method to the Wallet. for now, derives proofGenerationKey either from an account's spendingKey or from the account's multiSigKeys. invokes the buildTransaction worker pool task to build a RawTransaction
```
[ ] Yes
```
```
[ ] Yes
```

adds wallet/buildTransaction RPC

---

ironfish-cli/src/commands/wallet/send.ts

if flag is set uses the wallet/buildTransaction RPC to build the raw transaction to send
outputs unsigned transaction as hex string before exiting
flag is exclusive to the rawTransaction so that the command will output either a rawTransaction or an unsignedTransaction
flag is hidden
```
[ ] Yes
```
```
[ ] Yes
```

adds unsignedTransaction flag to send command

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts

Asset ownership changes through mints can only be verified for blocks being added to the main chain. We only store the asset owner at the current head so verifying asset ownership on a fork would not work
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Verify mint ownership on block connect instead of on add

---

ironfish/src/wallet/account/encoder/base64.json.test.ts
ironfish/src/wallet/account/encoder/base64json.ts

Adds a new encoder that takes the output of the json encoder and base64 encodes it. We are using this due to length issues from bech32 with new FROST fields (the public key package is unbounded).
Unit test
Example encoded account:
```
ifaccounteyJ2ZXJzaW9uIjo0LCJuYW1lIjoidGVzdCIsInNwZW5kaW5nS2V5IjpudWxsLCJ2aWV3S2V5IjoiYjU5MzhjNGVmN2FhMWJiYzZiMmQzNmJjZmZlOWIxY2M2YWYwMjY4Zjg3OTVhNzE5YTI3MzVhZGRiMjdhMzYwMzEyOTJmMTRhM2IwZjBlZGE5NDdjZDNjMDBjMTljZGVjYzI1Zjg5YjE5NWMyOGU2MmRhZTgzMWU0NWExOGM0NTIiLCJpbmNvbWluZ1ZpZXdLZXkiOiJkZGEyOGQ5ZWYwNjZiMDQ1ZGE1NzQwNzc5MTI0ZTlhNmRkMDkzZjZhMDY1ZWI2ZDhkNjAzNzIyMmU4MDJkNzAwIiwib3V0Z29pbmdWaWV3S2V5IjoiOWY3ZGVkZjMyYTQ4ZmIxYmIxNmUyMmEzYzgyOTNmMjdkY2VmYmZjNmQ3MDkyYjVkODEwYmM4NjcxZmY1ODkyZiIsInB1YmxpY0FkZHJlc3MiOiJlZDIwOGRmNWJiZjE3MjY2Y2IyNzQxMmQ1YzFiYTQzOTE3ODAzYTQyMDQ2 …
```

feat(ironfish): Add base64json encoder

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/multisig/aggregateSigningShares.ts
ironfish/src/rpc/routes/multisig/index.ts

takes a publicKeyPackage, an unsignedTransaction, a signingPackage for that transaction, and a list of signatureShares for that signingPackage
uses UnsignedTransaction.signFrost to aggregate the signatureShares, sign the transaction, and produce a signed transaction
returns a signed transaction serialized as hex
RPC integration test will be added in a followup PR
```
[ ] Yes
```
```
[ ] Yes
```

adds multisig/aggregateSigningShares RPC

---

ironfish/src/rpc/routes/wallet/multisig/__fixtures__/createSigningShare.test.ts.fixture
ironfish/src/rpc/routes/wallet/multisig/createSigningShare.test.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningShare.ts

changes the RPC to take an account name as a request parameter instead of a serialized keyPackage
loads the account for the given name and asserts that it is a multisig signing account before using the keyPackage from that account
this avoids passing a keyPackage, which contains a sensitive secret, from being passed through an RPC request
- updates to follow in integration test (#4681)
```
[ ] Yes
```
```
[ ] Yes
```

changes createSigningShare RPC to take an account name

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/errors.rs
ironfish-rust/src/frost_utils/signing_share.rs
ironfish-rust/src/transaction/tests.rs
ironfish/src/rpc/routes/wallet/multisig/aggregateSigningShares.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningShare.ts
ironfish/src/wallet/wallet.test.slow.ts

Updates serialization of signature share to include identifier. This allows us to have a single string output for the identifier/signingShare.
Note: We now have to pass in identifier to this method just so the serialization can include identifier in the hex string.
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```

refactor: serialization signature share

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish/src/rpc/routes/wallet/multisig/aggregateSigningShares.ts
ironfish/src/wallet/wallet.test.slow.ts

Renames `signFrost` to be consistent with `aggregateSignatureShares` RPC.
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```

chore: refactor sign frost naming

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/adapters/errors.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.ts

This fixes a bug where you are not prompted to enter a new name for the account in the case that the import is decoded in the server side.
1. Create an account with name `default`
2. Create a second account with name `default`
3. Import `default #2` into node with `default #1`
4. You are not prompted to enter a new name
```
[ ] Yes
```
```
[ ] Yes
```

Allow user to input a new name if duplicate

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/frost_utils/mod.rs
ironfish-rust/src/frost_utils/signature_share.rs
ironfish-rust/src/transaction/tests.rs
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/wallet/multisig/__fixtures__/createSignatureShare.test.ts.fixture
ironfish/src/rpc/routes/wallet/multisig/aggregateSignatureShares.ts
ironfish/src/rpc/routes/wallet/multisig/createSignatureShare.test.ts
ironfish/src/rpc/routes/wallet/multisig/createSignatureShare.ts
ironfish/src/rpc/routes/wallet/multisig/index.ts
ironfish/src/wallet/wallet.test.slow.ts

the frost crates use the term SignatureShare to refer to a part of a signature, but we have used the term SigningShare
the term 'SigningShare' can be confused with the 'signing_share' part of a key package, used to create signing commitments and signature shares
renames SigningShare to SignatureShare in rust types, napi bindings, and multisig RPCs
```
[ ] Yes
```
```
[ ] Yes
```

renames SigningShare to SignatureShare

---

ironfish-cli/src/commands/wallet/mint.ts
ironfish/src/rpc/routes/wallet/createTransaction.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.ts

removes minimum mint amount from cli, rpc endpoints
it is useful to be able to mint an asset with 0 supply. for example, create an asset before minting tokens corresponding to deposits
- manually created asset with 0 supply, asset displayed in `wallet:assets` command
```
[ ] Yes
```
```
[ ] Yes
```

allows minting asset with 0 supply

---

ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/soloMiner.ts
ironfish/src/networks/definitions/devnet.ts
ironfish/src/networks/definitions/mainnet.ts
ironfish/src/networks/definitions/testnet.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.test.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.ts

Nullable types work much better in many contexts. The make the return types for RPC endpoints specifically much easier
Unit tests
```
[ ] Yes
```
```
[X] Yes
```
This changes the type of `ConsensusParameters` exported from the SDK. It also changes the type of network definition files for anyone running on a custom network

Change consensus params type to nullable

---

ironfish-rust/src/frost_utils/signing_commitment.rs
ironfish-rust/src/frost_utils/split_secret.rs
ironfish-rust/src/frost_utils/split_spender_key.rs

ThreadRng shouldn't be used directly as it restricts the kinds of random number generators that people can pass as an input
```
[ ] Yes
```
```
[ ] Yes
```

Remove uses of `ThreadRng`

---

ironfish-rust/src/signal_catcher.rs

When building ironfish-rust for Android, I got a build error around multiple definitions of display_trace.
We could probably consider pulling the trace library out of ironfish-rust, but for now I fixed to not include one of the functions.
```
[ ] Yes
```
```
[ ] Yes
```

Fix multiple display_trace definitions on android build

---

ironfish-cli/src/commands/wallet/multisig/identity/create.ts

adds a cli command that generates a random secret and outputs the identity and identifier for that secret
useful for creating identifiers for testing for now, but doesn't interact with any RPC or persist any data
```
> fish wallet:multisig:identity:create
Identity:
721710619274d7f93e147cef1332f3aa54352d0b20c26eef086e6bfdfded532c60ad497130bbf0f037f22fb6f218923b8d5130afab326577e983d13dd89f100568a7bf61b2f8335c623b6a42fac96a00b539be0ffece7f3ee53ba656e63c0975415f79f9053918a3be7536f85d84422d827eb9673089eaafa9768fd59890e5710a
Identifier:
b53d7eb64e152844bec434d9d26bd9014b52ad763f13cb130bb06ae1e7cbae02
```
related documentation pull request …

adds wallet:multisig:identity:create

---

ironfish/src/rpc/routes/wallet/multisig/createSignatureShare.ts

This was the cause of the issue during our multi sig testing 
```
[ ] Yes
```
```
[ ] Yes
```

make account param optional for createSignatureShare

---

ironfish-cli/src/commands/wallet/send.ts

sets 'account' param in the buildTransaction RPC call
- created unsigned transaction with non-default account using `wallet:send`
```
[ ] Yes
```
```
[ ] Yes
```

fixes creating unsigned tx from non-default account

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/adapters/errors.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/account/encoder/mnemonic.ts
ironfish/src/wallet/account/encoder/spendingKey.ts

This fix will now prompt the user to enter a name in the case that an encoder throws an error because an account name was not provided. This gest caught and forwarded to the front end so they can prompt the user for a name to then try the import again.
1. Create an account
2. Get the mnemonic
3. Delete the account
4. Import the account by mnemonic
5. See you are now prompted for a name
```
[ ] Yes
```
```
[ ] Yes
```

Prompt user to enter a name for nameless account

---

ironfish/src/rpc/routes/wallet/multisig/createSigningPackage.test.ts
ironfish/src/testUtilities/fixtures/account.ts

The tests that I've written for deterministic nonces need to create new accounts and add funds to them every time, so having an utility function helps saving some repeated lines of code.
```
[ ] Yes
```
```
[ ] Yes
```

Add `useAccountAndAddFundsFixture` to simplify tests

---

ironfish/src/fileStores/config.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/stratum/clients/client.ts
ironfish/src/mining/stratum/messages.ts
ironfish/src/mining/stratum/stratumServer.ts
ironfish/src/mining/stratum/stratumServerClient.ts
ironfish/src/mining/stratum/version.ts

To help test FishHash and to allow users to solo-mine before the FishHash hardfork. All Ironfish miniers currently support TRM Stratum. Most of this code was taken from https://github.com/Kerney666/ironfish/blob/trm_stratum/TRM_STRATUM.md
Running pool against miner locally
```
[ ] Yes
```
```
[ ] Yes
```

Support TRM Stratum in testnet pool

---

ironfish/src/fileStores/config.ts
ironfish/src/mining/stratum/messages.ts
ironfish/src/mining/stratum/stratumServer.ts
ironfish/src/mining/stratum/stratumServerClient.ts

Add a new version of stratum for post FishHash pools. This change allows mining pools to set the graffiti as opposed to miners setting the graffiti with current TRM stratum protocol. Pools will send `xn`/extra nonce field to miners to distinguish miner search space 
Locally testing running pool against reference miner
```
[ ] Yes
```
```
[ ] Yes
```

Add Ironfish Stratum V3 (post-fishhash) to reference pool

---

ironfish/src/fileStores/config.ts

The reference pool miner is still on V1 and doesn't work with the pool unless you update the config. Making it easier for development until the pool miner is updated to V3
Locally tested pool + miner on V1
```
[ ] Yes
```
```
[ ] Yes
```

Support V1 miner by default

---

ironfish-cli/src/commands/wallet/multisig/create-signature-share.ts
ironfish-cli/src/utils/longPrompt.ts
ironfish/src/rpc/routes/wallet/multisig/createSignatureShare.ts

Prompting mechanism for long text input truncates with `Cli.ux.prompt` and is very laggy when using `inquirer` library. 
When using the `CliUx` of `oclif/core` I see truncation of input.
This creates a simple wrapper around the node native input system for prompting long text.
https://github.com/iron-fish/ironfish/assets/26990067/42d8b8c6-2e25-480b-a34c-fd3eea1bd64a
Tested on macOS and linux, same behavior exists on both systems.
```
[ ] Yes
```
```
[ ] Yes
```

feat: large prompt signature share

---

ironfish/src/fileStores/fileStore.test.ts

This test is sometimes failing on the second expect `expect(writeFileSpy).toHaveBeenCalledTimes(2)`. Changing this to wait for everything to execute until checking that the file is saved for a second time. This still tests the desired functionality because the test is testing that "The 2nd save IS NOT called until the first save resolves". That is still being tested with these changes and we can make the test less flaky without reducing coverage.
Unit tests
```
[ ] Yes
```
what additional work is required, …

Fix flaky fileStore test

---

ironfish-rust/src/serializing/aead.rs

Adds comment about this method only being used with unique keys, misuse could result in secret leakage.
Came across this when comparing our code to the post here:
https://andrea.corbellini.name/2023/03/09/authenticated-encryption/
N/A
```
[ ] Yes
```
```
[ ] Yes
```

chore: code comment encryption

---

ironfish/src/blockHasher.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/consensus.test.ts
ironfish/src/consensus/consensus.ts
ironfish/src/consensus/verifier.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/soloMiner.ts
ironfish/src/networks/definitions/devnet.ts
ironfish/src/networks/definitions/mainnet.ts
ironfish/src/networks/definitions/testnet.ts
ironfish/src/networks/networkDefinition.ts
ironfish/src/primitives/target.test.ts
ironfish/src/primitives/target.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.ts

- Modifies the `Target` class to allow for different max buckets, instead of the previous hard-coded 99 max buckets.
- Introduces a consensus parameter to allow a switch to a larger max buckets value (200) at a hard-fork sequence.
Previously, with 99 buckets, the maximum downward difficulty shift per block was around 4.83%., taking about 16.5 minutes. Once this sequence is activated, the max buckets value will change to 200, allowing a maximum shift downward of around 9.77%, taking roughly 33 minutes to reach this maximum.
This does not affect upward difficulty change.
The goal here is to allow a network to adjust difficulty easier in the event of a large amount of hashrate being removed from the network to maintain stability. The biggest gain here is that Testnet will get stuck less …

Add a consensus parameter for adjusting the max difficulty buckets

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/verifier.ts
ironfish/src/mining/pool.ts
ironfish/src/mining/soloMiner.ts
ironfish/src/primitives/target.test.ts
ironfish/src/primitives/target.ts

Introduces a one-time difficulty adjustment of `(difficulty / 100)` at the sequence that FishHash activates. The reasoning here is that FishHash has dramatically lower hashrate than the current blake3 algorithm. Initial testing shows a slowdown of 250-500x on GPUs. The reasoning for only adjusting by 100 is because we don't want to overshoot and make things too easy, but this still keeps the blocktime in the realm of usable.
If we say the current blake3 hashrate is 1,000,000, and the FishHash hashrate is 250x lower, that's 4,000. If it's 500x, it's 2,000.
Based on that blake3 hashrate, and a 60 second blocktime, the given difficulty would be 60,000,000. Given these FIshHash hashrates, we would see blocktimes in the 4-8 hour range. This is not good. If we simply divide by 100, we land on a …

Add a one-time difficulty adjustment when FishHash activates

---

ironfish/src/rpc/routes/wallet/create.test.slow.ts
ironfish/src/rpc/routes/wallet/createAccount.ts

wallet.createAccount already checks for duplicate names
instead of checking in both RPC and wallet sdk, the RPC catches the error that the wallet sdk throws and handles it with the appropriate RPC response
- ran `wallet:create` to create accounts, verified that behaviour unchanged for duplicate and unique names
```
[ ] Yes
```
```
[ ] Yes
```

removes duplicate check for duplicate name in createAccount

---

ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

adds a datastore to the walletDb to store each 'ParticipantSecret' that a multisig user generates
uses a string 'name' as the key and stores the secret as a buffer as the datastore value
```
[ ] Yes
```
```
[ ] Yes
```

adds walletdb multisigSecrets

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/note.rs
ironfish-rust/src/note.rs
ironfish/src/genesis/addGenesisTransaction.ts
ironfish/src/genesis/makeGenesisBlock.ts
ironfish/src/testUtilities/fixtures/blocks.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/tasks/createMinersFee.ts

the NativeNote napi constructor takes the memo to be a utf-8 string that is then converted to bytes when constructing a Memo
this prevents clients from easily constructing a memo from arbitrary bytes
changes constructor to take the memo as a JsBuffer
clients treating memos as strings should convert to buffers before constructing Notes
```
[ ] Yes
```
```
[ ] Yes
```

changes NativeNote napi to take memo as buffer

---

ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish/src/rpc/routes/wallet/multisig/aggregateSignatureShares.ts
ironfish/src/rpc/routes/wallet/multisig/integration.test.slow.ts
ironfish/src/wallet/wallet.test.slow.ts

Removes unsigned transaction from aggregate signature share. 
This is continuation of the work that was started here #4734 
Update tests
```
[ ] Yes
```
```
[ ] Yes
```

removing unsigned transaction from aggregate signature share

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish/src/primitives/__fixtures__/unsignedTransaction.test.ts.fixture
ironfish/src/primitives/unsignedTransaction.test.ts
ironfish/src/primitives/unsignedTransaction.ts

* Adds getter methods to the unsigned transaction struct
* Adds a `descriptions` method on the Napi layer to fetch parts of an unsigned transaction
* Adds a method to the JS primitive to fetch descriptions
Unit test
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish,rust,rust-nodejs): Return descriptions from unsigned transaction

---

ironfish/src/networks/definitions/testnet.ts

Per the [hardfork FIP](https://fips.ironfish.network/fips/fip-10-hardfork-1) addactivation height for testnet 
Writing simulations + running hardfork activation on devnet
```
[ ] Yes
```
```
[X] Yes
```
This is a breaking change for the Testnet network

Add activation sequence for testnet

---

ironfish-cli/package.json
ironfish-rust-nodejs/npm/darwin-arm64/package.json
ironfish-rust-nodejs/npm/darwin-x64/package.json
ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json
ironfish-rust-nodejs/npm/linux-arm64-musl/package.json
ironfish-rust-nodejs/npm/linux-x64-gnu/package.json
ironfish-rust-nodejs/npm/linux-x64-musl/package.json
ironfish-rust-nodejs/npm/win32-x64-msvc/package.json
ironfish-rust-nodejs/package.json
ironfish/package.json

Version bump for v1.20.0. This version includes the testnet hardfork sequence
Local testing of node
```
[ ] Yes
```
```
[ ] Yes
```

Bump version to 1.20.0

---

Cargo.lock
ironfish-rust-nodejs/src/frost.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs

Updating Cargo dependencies related to frost, in particular `frost-rerandomized`, which went from 1.0.0-rc.0 to 1.0.0 and introduced a backward-incompatible change (`Randomizer` moved to the crate root).
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Update frost-related Cargo dependencies

---

ironfish-cli/src/commands/wallet/multisig/create-signature-share.ts

The command does not use signerIdentity and does not start properly. I think we can remove this flag.
```sh
❯ f wallet:multisig:create-signature-share --datadir=~/.ironfish-test
yarn run v1.22.21
$ yarn build && yarn start:js wallet:multisig:create-signature-share '--datadir=~/.ironfish-test'
$ tsc -b
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:multisig:create-signature-share '--datadir=~/.ironfish-test'
›   Error: The following error occurred:
›     Missing required flag signerIdentity
›   See more help with --help
```
Ran the command. …

fix(cli): Remove signerIdentity from create-signature-share

---

Cargo.lock
ironfish-rust-nodejs/src/nacl.rs
ironfish-rust/Cargo.toml
ironfish-rust/src/nacl.rs

The goal is to have only one version of `rand` and `rand_core` in our dependency tree.
Before this commit, we had two versions of `rand_core`: 0.6.4 and 0.5.1. The 0.5 version lacks some features that some of our crates needs, and this causes some minor annoyances from time to time, especially when adding new dependencies or updating existing ones. With this commit, 0.5.1 is gone and only 0.6.4 is left, so similar dependency conflicts won't happen again in the future.
Unit tests
```
[ ] Yes
```
what …

Update crypto_box and tiny-bip39 to the latest version

---

ironfish-cli/src/commands/wallet/transaction/index.ts

defines getter functions to extract assetId, memo from each note displayed in the table
notes are paired with asset information, so the default getter doesn't work to extract fields from the nested note object
Before:
```
$ fish wallet:transaction 62f9886197898988da46f23c3034b4c0a2836c73934107aab5526bbc6ec00f2a -d ~/.if.dev
Transaction: 62f9886197898988da46f23c3034b4c0a2836c73934107aab5526bbc6ec00f2a
Account: test
Status: confirmed
Type: receive
Timestamp: 2/21/2024 1:54:54 PM PST
Fee: $IRON 0.00000001
Block Hash: 00000002078575e210c512a5ca8cff2c431ccb4ffbe7ebd6bf981dff59ab8f7b
Block Sequence: 192882
Notes Count: 1
Spends Count: 1
Mints Count: 0
Burns Count: 0
Sender: 16ee4de18adff9aaf5519f63de91f594bc346b07f3981527899db073691a966c
---Notes---
Amount     Asset Name Asset Id Spent Memo …
```

fixes rendering of notes in wallet:transaction

---

ironfish-cli/src/commands/repl.ts

For faster debugging in the repl command expose all the SDK exported functions
Tested running repl locally
```
[ ] Yes
```
```
[ ] Yes
```

Add SDK exports to repl

---

ironfish/src/primitives/unsignedTransaction.ts

The static method is incorrectly creating a native unsigned transaction instead of using the `fromSigningPackage` method.
```
[ ] Yes
```
```
[ ] Yes
```

fix(ironfish): Fix unsigned transaction creation from signing package

---

ironfish/src/wallet/account/encoder/base64json.ts

Base64JsonEncoder: correctly strip the 'ifaccount' prefix

---

ironfish-cli/src/commands/wallet/multisig/create-signature-share.ts

a 'signing share' is a part of a key, but a 'signature share' is a part of a signature
we've made this change in almost all of our multisig naming, but we missed this output
```
[ ] Yes
```
```
[ ] Yes
```

changes 'signing' to 'signature' in cli output

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

Max buffer length is currently not enforced in `createTransaction`. I ran into this when passing in a string that is longer than 32 bytes. The code happily truncated the memo without error or warning.
Tests pass
```
[ ] Yes
```
```
[ ] Yes
```

fix: throw on max buffer length exceeded

---

ironfish-cli/src/commands/miners/start.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/lib.rs
ironfish-rust/src/mining/mine.rs
ironfish-rust/src/mining/thread.rs
ironfish-rust/src/mining/threadpool.rs
ironfish/src/mining/pool.ts
ironfish/src/mining/poolMiner.ts
ironfish/src/mining/soloMiner.ts
ironfish/src/mining/stratum/clients/client.ts

Move the CPU pool miner to use V3 of ironfish stratum
Tested running against local pool on fishhash and blake3
```
[ ] Yes
```
```
[ ] Yes
```

Move pool miner to V3

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/structs/key_packages.rs
ironfish-rust/src/frost_utils/split_spender_key.rs
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.test.ts
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.ts

- Rename `verifying_key` (used by FROST) to `authorizing_key` (used by Iron Fish)
- Drop `verifyingKey`/`authorizingKey` from the output of `createTrustedDealerKeyPackage` as it is not needed
- Remove the term "coordinator" in places where it should actually be "trusted dealer"
- Rename 1-letter variables
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Improve the terminology used around multisig

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/frost.rs

This allows NodeJS code to encrypt/decrypt arbitrary data to a multisig participant.
Tests will be written in a future PR that adds multisig account encryption.
```
[ ] Yes
```
```
[ ] Yes
```

Multisig: add encryption/decryption primitives to ParticipantIdentity and ParticipantSecret

---

ironfish/src/testUtilities/nodeTest.ts
ironfish/src/testUtilities/routeTest.ts

These afterEach would execute in parallel causing the DB to close before the node shuts down. This causes any code still running that's not aborted to cause a crash.
```
[ ] Yes
```
```
[ ] Yes
```

Fix route and node test cleanups

---

ironfish-cli/src/commands/wallet/multisig/account/create.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningCommitment.test.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningPackage.test.ts
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.test.ts
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.ts
ironfish/src/rpc/routes/wallet/multisig/integration.test.slow.ts

The `wallet/multisig/createTrustedDealerKeyPackage` RPC now creates base64 accounts directly, instead of delegating this operation to the CLI. This change is a pre-requisite for multisig account encryption.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Multisig wallet: generate TDK accounts on the server side

---

.github/workflows/publish-binaries.yml

We got reports that the latest binaries (v1.20.0) were actually of v1.19.0. Looking into this, I suspect what happened was that the github version was tagged prior to the npm release finishing. This change ensures that ONLY the correct version will be pulled from npm, and the job will fail if the specified version has not yet been published.
Fixes IFL-2308
I set up a test repo to emulate the release steps. The github action on release simply tries to download the specified version of ironfish from npm and then run `ironfish status`.
v1.20.0 which succeeded: https://github.com/mat-if/foo/actions/runs/8100633100
v.1.21.0 which does not exist yet, so it errored out: https://github.com/mat-if/foo/actions/runs/8100653355
N/A
N/A

Ensure that the release binaries are built using the right version

---

ironfish-rust/src/frost_utils/split_secret.rs
ironfish-rust/src/frost_utils/split_spender_key.rs

Problem: The trusted dealer provides the spending key to create the package. This means that the trusted dealer has the capability to sign the transaction on their own terms without the participants being involved. 
Solution: We generate a separate key that is discarded while partially creating the package (it generates the nullifier key and outgoing view key). This means that the trusted dealer no longer will be able to sign the transaction and only all the participants can do so. 
```
[ ] Yes
```
what …

creating new signing key when splitting secret from dealer

---

ironfish-cli/src/commands/wallet/multisig/identity/create.ts

Slight convenience/ UX improvement. 
If the name flag is not passed in ask the user for it
```
[ ] Yes
```
```
[ ] Yes
```

name flag optional for multisig identity create

---

ironfish/src/wallet/account/encoder/base64json.test.ts
ironfish/src/wallet/account/encoder/base64json.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/account/encoder/multisig.ts

Multisig accounts can be encrypted as follows:
```ts
const encoder = new Base64JsonEncoder()
encoder.encode(account, {
encryptWith: { kind: 'MultisigIdentity', identity: ... })
```
and decrypted as follows:
```ts
decodeAccount(encodedAccount, { multisigSecret: ... })
```
Base64 multisig encrypted accounts differ from regular base64 encoded accounts from the prefix: `ifaccount` vs `ifmsaccount`.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Add functionality to Base64JsonEncoder to encrypt multisig accounts

---

ironfish/src/networks/definitions/testnet.ts

Testnet hardfork has been completed. Adding a checkpoint to point to the first FishHash block so that the chain cannot re-org previous to it
Running a node with the checkpoint on testnet
```
[ ] Yes
```
```
[ ] Yes
```

Add testnet checkpoint for FishHash hardfork

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/frost.rs
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.ts
ironfish/src/testUtilities/keys.ts
ironfish/src/wallet/wallet.test.slow.ts

Avoid generating the key in Rust, then moving it to TypeScript, and then moving it back to Rust. Generate the key directly in Rust. This avoids copies that leave secrets in memory, reducing the attack surface.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Multisig: move key generation to the Rust layer

---

ironfish/src/rpc/routes/wallet/multisig/createIdentity.test.ts
ironfish/src/rpc/routes/wallet/multisig/createIdentity.ts
ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.ts

Check if there is an existing account name before creating a secret
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Check for duplicate account name when creating secret

---

ironfish/src/networks/definitions/mainnet.ts

Adding code to intitiate the first hardfork. Hardfork is described further in [FIP-10](https://fips.ironfish.network/fips/fip-10-hardfork-1)
Extensive testing has been done on the FishHash hardfork including excecuting the hardfork on testnet with the same parameters  
```
[X] Yes
```
```
[X] Yes
```
Once released this change will initiate a hardfork at the given block sequence

Add mainnet hardfork sequence for hardfork 1

---

ironfish-cli/src/commands/wallet/multisig/commitment/create.ts

refers to creating a signing commitment instead of a signature share
```
[ ] Yes
```
```
[ ] Yes
```

fixes description for confirm flag in commitment:create

---

ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts

if a user uses the '--no-broadcast' flag they will need the serialized transaction to be able to broadcast the transaction using 'transaction:add'
```
[ ] Yes
```
```
[ ] Yes
```

outputs serialized transaction from signature:aggregate

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/adapters/errors.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/account/encoder/encoder.ts
ironfish/src/wallet/account/encoder/multisig.ts

A multisig secret name is required when importing from the TDK. Improve the UX to prompt for the secret if the name isn't provided.
RPC is covered by existing tests.
Manually tested CLI
```sh
❯ f wallet:import -d ~/.ironfish-testnet ifmsaccount2AtiArQwrhmMtU...
Enter the name of the multisig secret: rj
```
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli,ironfish): Throw error for multisig secret during import

---

ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/utils/longPrompt.ts

Long prompt for identities when creating commitment 
Added some additional formatting to long prompt
```
[ ] Yes
```
```
[ ] Yes
```

uses long prompt for fetching identities when creating a commitment

---

ironfish-cli/src/commands/wallet/multisig/participant/create.ts
ironfish/src/rpc/routes/wallet/multisig/createParticipant.test.ts
ironfish/src/rpc/routes/wallet/multisig/createParticipant.ts

wallet/multisig/createParticipant returns DUPLICATE_ACCOUNT_NAME error code if account name or multisig secret name already exists
only prompts for new name if the error was from a duplicate name
```
[ ] Yes
```
```
[ ] Yes
```

handles errors in participant creation

---

ironfish-rust-nodejs/src/frost.rs

Preserves order of identities when returning key packages for each identity
```
[ ] Yes
```
```
[ ] Yes
```

preserves order of identities when returning key packages

---

ironfish/src/rpc/routes/wallet/multisig/createSigningCommitment.ts

when a user creates a signing commitment using a multisig account their account identity must be included in the list of signers in order for the commitment to be valid
automatically includes the account's participant identity whether or not it was passed to wallet/multisig/createSigningCommitment. relies on ironfish-frost for deduplication when creating nonces
manual testing: created commitment without specifying own identity in CLI, commitment still valid, transaction sent
```
[ ] Yes
```
what additional …

automatically include account identity for commitment

---

ironfish-rust-nodejs/src/frost.rs
ironfish-rust/src/errors.rs
ironfish-rust/src/frost_utils/split_secret.rs
ironfish-rust/src/frost_utils/split_spender_key.rs
ironfish-rust/src/transaction/tests.rs

- Check for duplicate identities to make sure that max_signers is calculated correctly and according to expectations
- Check for hash collisions in FROST identifiers
- Removed unnecessary allocations and cloning
- Removed unused error kinds
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Multisig: make `split_spender_key`/`split_secret` more robust

---

ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/frost.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish/src/primitives/unsignedTransaction.ts

allows user to confirm list of signers from signing package before creating signature share
- adds NativeSigningPackage to napi layer, defines 'signers' and 'unsigned_transaction' methods
- removes 'from_signing_package' from UnsignedTransaction, NativeUnsignedTransaction in favor of constructing from NativeSigningPackage
```
[ ] Yes
```
```
[ ] Yes
```

displays signers during signature share creation

---

ironfish-cli/src/commands/wallet/multisig/dealer/create.ts

Update the prompt when creating the trusted dealer if we need to manually paste identities
Manual test
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Use `longPrompt` when creating dealer

---

ironfish-cli/src/utils/transaction.ts

if a user tries to view details of an unsigned transaction that their account isn't involved in then there may be no output for the transaction details. this may be confusing when multisig commands prompt them to confirm, but there are no details visible to confirm
always renders the 'Notes sent' and 'Notes received' headings if the transaction has output notes
outputs a message that no notes could be decrypted if no sent or received notes decryptable
manual testing: create a commitment with the wrong account.
before:
after:
```
[ ] Yes
``` …

updates unsigned tx details to always show output for notes

---

ironfish-cli/src/commands/wallet/multisig/dealer/create.ts
ironfish-cli/src/commands/wallet/multisig/participant/index.ts
ironfish/src/rpc/clients/client.ts

prompts for new name until the user inputs a unique name
checks names before trusted dealer so that import doesn't fail after accounts have been created
includes small fix to RPC method to provide default undefined params
```
[ ] Yes
```
```
[ ] Yes
```

checks coordinator name against accounts and identities

---

ironfish/src/assets/assetsVerificationApi.test.ts
ironfish/src/assets/assetsVerificationApi.ts
ironfish/src/assets/assetsVerifier.test.ts
ironfish/src/assets/assetsVerifier.ts
ironfish/src/node.ts

Use the abstracted file system so that asset verification can work in other contexts besides NodeJS
```
[ ] Yes
```
```
[X] Yes
```
SDK breaking change. Need to pass file system into asset verfier classes

Use NodeFileSystem for AssetVerifier

---

ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/utils/multisig.ts

some of the multisig commands have very long inputs. it would be nice to be able to pass in a file instead
defines a single schema for a JSON file containing any inputs to a command in the multisig transaction signing flow
adds util functions for loading multisig JSON file and resolving input options with any flags. uses flags over json settings if both are set
adds path flag to each command in multisig signing flow: 'commitment:create', 'commitment:aggregate', 'signature:create', 'signature:aggregate'
manual testing
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below …

supports json file input to multisig transaction commands

---

ironfish/src/rpc/routes/wallet/multisig/__fixtures__/createSignatureShare.test.ts.fixture
ironfish/src/rpc/routes/wallet/multisig/createSignatureShare.test.ts
ironfish/src/rpc/routes/wallet/multisig/createSignatureShare.ts

checks each signer identity in the input signing package against the set of participants for the account
throws an error upon finding a signer that doesn't belong to the set
manual testing with `wallet:multisig:signature:create`
```
[ ] Yes
```
```
[ ] Yes
```

verifies signing package signers in createSignatureShare

---

ironfish/src/rpc/routes/wallet/exportAccount.test.ts
ironfish/src/rpc/routes/wallet/exportAccount.ts

When exporting an account with `viewOnly: true`, the multisig secret (i.e. the authorization key shard) should be omitted from the output.
* unit tests
* create a multisig account, export it as view only, verify that the output does not include any secrets
```
[ ] Yes
```
```
[ ] Yes
```

Multisig: do not include the multisig secret when exporting view-only account

---

ironfish/src/merkletree/merkletree.test.ts
ironfish/src/merkletree/merkletree.ts

when calculating witnesses at past tree sizes we cache the sibling hashes of left nodes at the past tree size
the merkle tree has separate datastores for nodes and leaves. the cache is keyed by node index, not leaf index.
when building the cache we incorrectly set a leaf index to a sibling hash. if that index is visited as a node index when creating the witness, then the cached value may be used incorrectly resulting in an invalid commitment.
the commitment may still be correct if that node index corresponds to a right node or if the node index is overwritten by the correct sibling hash in the cache while building the past root
there are four criteria for the merkle tree, past size, and witness index that produce an incorrect commitment:
1. the leaf at leaf index `pastSize - 1` is a right …

fixes incorrect sibling hash caching during witness creation

---

ironfish/src/rpc/routes/chain/getBlock.test.ts
ironfish/src/rpc/routes/chain/getChainInfo.test.ts
ironfish/src/rpc/routes/chain/getConsensusParameters.test.ts
ironfish/src/rpc/routes/chain/getNetworkInfo.test.ts
ironfish/src/rpc/routes/chain/getNoteWitness.test.ts
ironfish/src/rpc/routes/wallet/exportAccount.test.ts
ironfish/src/rpc/routes/wallet/getAccountStatus.test.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.test.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.test.ts
ironfish/src/rpc/routes/wallet/getPublicKey.test.ts
ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningCommitment.test.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningPackage.test.ts

This replaces code like the following:
await routeTest.client.request<FooResponse>('foo', ...).waitForEnd()
with:
await routeTest.client.foo(...)
Not all the uses of `request` have been replaced in this PR: only the trivial ones. The remaining ones require a bit more involved changes.
This PR also fixes some typing errors in the request parameters, and fixes some tests that were using `try`/`catch` instead of `expect` (the try/catch approach had the problem that if the RPC did not throw any exception, the test would have not failed).
Unit tests
```
[ ] Yes
``` …

Replace uses of `request<T>(...)` in tests with the appropriate method from `RpcClient`

---

.github/workflows/rust_ci.yml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This PR introduces several commits to do the following:
- initialize `cargo vet` in the repository
- import some audits from trusted organizations
- vet some dependencies we use
- run `cargo vet` as part of the GitHub CI
- run `cargo vet`: verify that it succeeds. At the time of writing, it reports:
```
Vetting Succeeded (93 fully audited, 25 partially audited, 225 exempted)
```
- verify that dependencies are vetted as part of the GitHub CI on this PR
```
[ ] Yes
```
what additional work is required, if …

Add "cargo vet" for supply chain verification

---

ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/currency.ts

This makes it more clear, however it also reveals a confusing issue we have. When using custom assets, why are we entering iron? What should we refer to the coin denomination for that asset? These issues will need to be fixed goign forward from a UX perspective.
```
[ ] Yes
```
```
[ ] Yes
```

Clarify when users are entering iron denominations

---

ironfish-cli/src/commands/wallet/notes/combine.ts
ironfish-cli/src/utils/transaction.ts

Adds a transaction timer class that abstracts the timer logic away from combine notes. 
This is in setup for adding the timer to `wallet:send`
```
[ ] Yes
```
```
[ ] Yes
```

Adds a transaction timer class to reuse

---

ironfish-cli/src/commands/wallet/transactions.ts

requires using the '--notes' flag because memos are only available on notes, not transactions
selects only a few columns for visibility
```
[ ] Yes
```
```
[ ] Yes
```

adds memos to 'wallet:transactions' output

---

ironfish/src/rpc/routes/wallet/getAccountNotesStream.ts
ironfish/src/rpc/routes/wallet/getAccountTransaction.test.ts
ironfish/src/rpc/routes/wallet/types.ts
ironfish/src/rpc/routes/wallet/utils.ts

the 'memo' included with each note is modified to remove non-human-readable characters. if the memo included in the note is encoding data then this can make it impossible to recover the data from the rpc response.
adds memoHex to return the memo as a hex string to preserve memo data in wallet rpc responses
- updates unit test
```
[X] Yes
```
https://github.com/iron-fish/website/pull/658
```
[ ] Yes
```

adds memoHex to RpcWalletNote

---

.github/workflows/deploy-node-docker-image.yml

adds deploy step to deploy to image to github for branch refs
adds rule to deploy docker image on push to staging
```
[ ] Yes
```
```
[ ] Yes
```

allows deploying Docker images for staging branch

---

ironfish/src/mining/pool.ts

The pool will recalculate the target of the new block template every 10 seconds. Right now, once it reaches the max target for that block, it stops sending out updated block templates with the new target and timestamp. This leads to an issue where once the max target has been reached for that block, the timestamp is never updated, so a block that takes, for example, 3 hours to mine, will still say 34 minutes because that was the last time the timestamp was updated.
By removing this check, the timestamp will be changed every 10 seconds, leading to more accurate block times for the reference pool implementation.
Closes IFL-2453
Manually tested on a local devnet
N/A
N/A

Pool: always send out a new block template

---

ironfish/src/wallet/wallet.ts

tl;dr: when called delete account on a node that is rescanning, head is deleted for the account before it is deleted from in memory store of `wallet.accounts`.
RPC Client - delete account sent to remote node. Occasionally, node will crash saying head isn't set. 
Order of events that cause failure:
1. Client: Account import requested
2. Node: Imports account, rescan initiated
3. Client: Account delete requested
4. Node: Head is deleted [here](https://github.com/iron-fish/ironfish/blob/923fc6972f44444988addbc6b50fed4b6bb60983/ironfish/src/wallet/wallet.ts#L1675-L1685), but subsequent code line  `this.accounts.delete(account.id)` is not yet called.
5. Node: New block `connect` is called, `wallet.accounts` still contains account created from step 1/2.
Manual testing, difficult to reproduce. …

fix: rescanning account crash delete

---

ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts

We stop processing RPC messages when an exception occurs. This means that all pending RPC messages don't process and the connection remains open. 
This removes the returns we have and continues to process messages as they come in. 
Run this CLI command to replicate: 
```typescript
/* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at https://mozilla.org/MPL/2.0/. */
import { Flags } from '@oclif/core'
import { IronfishCommand } from '../command'
import { RemoteFlags } from '../flags'
export class FeeCommand extends IronfishCommand {
static description = `Get fee distribution for most recent blocks`
static flags = {
...RemoteFlags,
explain: Flags.boolean({
default: false, …
```

continue to process messages when exceptions occur

---

.github/workflows/publish-binaries.yml

Update naming for standalone binary
```
[ ] Yes
```
```
[ ] Yes
```

chore: standalone naming

---

ironfish-cli/package.json
yarn.lock

Downgrading oclif autocomplete plugin to match our oclif version (2)
Running docker build locally
```
[ ] Yes
```
```
[ ] Yes
```

Update autocomplete version to use correct version of Oclif

---

.github/workflows/publish-binaries.yml

[## Summary
Previously `macos-latest-large` was M1 runner. `macos-latest-xlarge` is now m1. Adds arch check and manual workflow dispatch (for backfilling use cases).
Tested here:
https://github.com/iron-fish/ironfish/actions/runs/8605207764/job/23580976352?pr=4881
output from downloaded/extracted binaries:
```
file ironfish 
ironfish: Mach-O 64-bit executable arm64
file ironfish                                                                                                                                                                                                  
ironfish: Mach-O 64-bit executable x86_64
```
related …

fix: adjust GHA runner apple binary to publish arm64

---

.github/workflows/publish-binaries.yml

Adds workflow dispatch ref so that programmatic triggering can happen with this param when running from a different branch (ie `staging`).
```
[ ] Yes
```
```
[ ] Yes
```

fix: add dispatch param

---

ironfish/src/rpc/routes/config/getConfig.test.ts
ironfish/src/rpc/routes/config/setConfig.test.ts
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.test.ts
ironfish/src/rpc/routes/worker/getStatus.test.ts

This is a follow up to 98fcad2e45a8f699893d03f70d2defa2fd86b84a and removes a few more uses of `request()` in tests.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Cleanup more uses of `request()` in tests

---

ironfish/src/mining/webhooks/webhookNotifier.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/rpc/routes/wallet/createTransaction.ts
ironfish/src/rpc/routes/wallet/sendTransaction.ts
ironfish/src/utils/currency.test.ts
ironfish/src/utils/currency.ts
ironfish/src/wallet/errors.ts

Adds a new render function for currency that handles custom decimal places for verified assets. Additionally, it will use the verified asset symbol when including the name instead of the asset id, which will improve readability a lot for verified assets.
Unit tests
N/A
N/A

Add new currency render function

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/utils/asset.ts

When the node fails to query the verified asset lists, it is unknown which assets are verified. This should be displayed inline with the assets. It also cleans up the code a bit so that warnings are not logged inline with rendering data.
Unit tests + running commands on testnet node
```
[ ] Yes
```
```
[ ] Yes
```

Render question mark for unknown assets

---

ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts
ironfish-cli/src/commands/wallet/notes/combine.ts
ironfish-cli/src/commands/wallet/notes/index.ts
ironfish-cli/src/commands/wallet/post.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/asset.ts
ironfish-cli/src/utils/currency.ts
ironfish-cli/src/utils/fees.ts
ironfish-cli/src/utils/note.ts
ironfish-cli/src/utils/transaction.ts

Use the new currency render function in the CLI. See #4879 for more information about that function
Manual testing
N/A
N/A

Use new render function in the CLI

---

ironfish/src/rpc/routes/wallet/multisig/dkg/round1.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round1.ts

when a user runs round1 of dkg with a given secret name they must also include the identity for that secret in the list of participants
updates the round1 rpc to automatically add that identity if it's missing instead of throwing an error
```
[ ] Yes
```
```
[ ] Yes
```

automatically add identity for secretName to round1 participants

---

Cargo.lock
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/index.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.ts

- updates ironfish-frost version to latest main
- defines round2 in ironfish-rust-nodejs
- defines round2 RPC endpoint
```
[ ] Yes
```
```
[ ] Yes
```

implement dkg/round2 RPC

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts

adds a cli command to run round1 of the dkg protocol
takes flags for secret name, identities of particicpants, and minimum signers
logs encrypted secret package and public package to command-line
```
[ ] Yes
```
```
[ ] Yes
```

add dkg round1 cli command

---

ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts

runs round2 of DKG and logs round2 encrypted secret package and each public package to the command-line
```
[ ] Yes
```
```
[ ] Yes
```

add DKG round2 CLI command

---

ironfish-rust/src/keys/mod.rs

If the random scalar generated is zero (which is a rare occurrence, almost impossible, and has the same probability to occur as guessing somebody's private key), `SaplingKey::generate_key` is supposed to generate a new random scalar and try again. The current code however, does not generate a new random scalar if that occurs, resulting in an infinite loop.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Avoid an infinite loop in `SaplingKey::generate_key`

---

ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/wallet/wallet.ts

The `--name` flag is ignored when importing public packages from a dealer. This overwrites the secret name if it's provided, otherwise defaults to it.
Update a unit test
```
[ ] Yes
```
```
[ ] Yes
```

fix(ironfish): Use CLI flag option for encrypted trusted dealer imports

---

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.ts

* Returns name and public address from round3 rpc endpoint
* Adds CLI command for dkg round 3
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli,ironfish): Add `wallet:multisig:dkg:round3`

---

Cargo.lock
supply-chain/audits.toml
supply-chain/imports.lock

Fixes:
- https://github.com/iron-fish/ironfish/security/dependabot/76 (openssl)
- https://github.com/iron-fish/ironfish/security/dependabot/81 (h2)
- https://github.com/iron-fish/ironfish/security/dependabot/91 (mio)
- https://github.com/iron-fish/ironfish/security/dependabot/93 (h2)
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Update Cargo dependencies to fix dependabot alerts

---

ironfish-cli/src/commands/wallet/rescan.ts
ironfish/src/rpc/routes/wallet/rescanAccount.test.ts
ironfish/src/rpc/routes/wallet/rescanAccount.ts

resets account createdAt to null on all accounts if the 'full' option is set on requests to wallet/rescanAccount. this forces rescans for all accounts to start at the genesis block instead of beginning at the account birthday.
adds '--full' flag to wallet:rescan command.
- manual testing: checked account createdAt in JSON export before and after starting a rescan with `wallet:rescan --full`
```
[ ] Yes
```
```
[ ] Yes
```

add option to force full account rescan from genesis

---

ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts

When calling `importAccount` with an `RpcAccountImport` and a non-undefined `name`, the `name` parameter used to be ignored. This is no longer the case: passing a non-undefined `name` now overrides the name of the `RpcAccountImport`.
Unit tests
No doc change required because the current doc (https://ironfish.network/developers/documentation/rpc/wallet/import_account) does not specify any limitations for `name`
This is a breaking change because the behavior of calls to `importAccount` using `name` has changed.

Always honor the `name` parameter passed to `importAccount`

---

ironfish-cli/src/commands/wallet/post.ts

Adds a -f flag to specify the account the transaction is being sent from 
The raw transaction input is not optional and can be entered using a long prompt
```
[ ] Yes
```
```
[ ] Yes
```

Standardizing post CLI command

---

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.ts

Allow an override of the secret name for the account name during round 3
Updated unit test
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli,ironfish): Add flag to override name in round3

---

ironfish-cli/src/commands/wallet/transactions.ts

The `wallet:transactions` command was not accounting for asset decimals when showing amounts
Tested running locally on devnet
```
[ ] Yes
```
```
[ ] Yes
```

Show the correct decimal amount in wallet:transactions command

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/utils/multisig.ts

if no secretName is passed via flags allow the user to select one of their existing names from a list
in round1 allow users to create a new secret name from the list
makes it easier for users to know which secret names they have and can use in the context of the dkg commands. allows users to start the dkg process without running the participant:create command first
manual testing with dkg commands
```
[ ] Yes
```
```
[ ] Yes
```

select secret name from list in dkg commands

---

ironfish/src/rpc/routes/wallet/multisig/dkg/round3.ts

This adds a new `--rescan` option to force the rescan of the account created during round 3. It also properly handles the case where `--rescan` is not provided by calling `skipRescan()`.
**NOTE:** This behavior differs from the "standard" `importAccount` command, which triggers a rescan by default. The reason for defaulting to no rescan is that it should be a rare event (although not impossible) to have a newly created DKG account that has transactions associated to it.
```
[ ] Yes
``` …

Multisig DKG Round 3: add an option to rescan the imported account

---

ironfish-cli/src/commands/wallet/multisig/participant/create.ts

the next step instruction refers to the dealer in trusted dealer keygen, so it doesn't always apply now that we support dkg
```
[ ] Yes
```
```
[ ] Yes
```

removes 'next step' from participant:create output

---

Cargo.lock
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
ironfish/src/rpc/routes/wallet/multisig/integration.test.slow.ts

At the end of round 2, output a single public package, instead of *n*−1 per-participant packages.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Multisig DKG: use the round 2 "combined" public packages

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish/src/rpc/routes/wallet/multisig/dkg/round1.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round1.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
ironfish/src/rpc/routes/wallet/multisig/integration.test.slow.ts

Disambiguate names by *always* specifying what round the input or output refers to.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Multisig DKG: prefix every occurrence of "package" with the round number

---

ironfish-cli/src/commands/wallet/multisig/account/participants.ts

renames the command to make it clearer that the command will list all of the participant identities in the group for a given account and not all participant identities that the wallet has created
maintains the old command name as a deprecated alias
```
[ ] Yes
```
```
[ ] Yes
```

renames wallet:multisig:participants to wallet:multisig:account:participants

---

ironfish-cli/src/commands/wallet/multisig/participants/index.ts

List out a table of participant names and identities
Manually ran the command
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Add CLI command to list identities

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/currency.ts
ironfish/src/utils/currency.test.ts
ironfish/src/utils/currency.ts
ironfish/src/utils/fixedNumber.ts

Standardizing which function we use for parsing decimal values to BigInts
```
[ ] Yes
```
Removes exports `ParseFixedError` and `isParseFixedError` from `CurrencyUtils` and changes the error value in `CurrencyUtils.tryMajorToMinor`

Use ironfish decimal parsing function

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round1.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round1.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round2.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.ts
ironfish/src/rpc/routes/wallet/multisig/integration.test.slow.ts

the term 'secretName' does not make it clear that the name should be the same as the one used with 'participant:create', that is, the name of a participant
renames the flag and rpc parameter 'secretName' to 'participantName' across all dkg cli commands and rpc endpoints
changes flag character from s to n. in round3, this also requires changing the 'accountName' flag character from n to a
adds an alias 'name' for 'participantName' in all dkg commands
manual testing: created an account by running all three dkg rounds
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on …

renames secretName to participantName

---

ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/dealer/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts

clarifies which participant identities are expected when prompting for a list of identities on the command line in 'commitment:create', 'dealer:create', and 'dkg:round1'
```
[ ] Yes
```
```
[ ] Yes
```

updates text of identities prompts

---

ironfish-cli/src/commands/wallet/transaction/view.ts

allows users to view details for a transaction without needing to use the REPL
useful for situations where you have a serialized transaction, but don't know what's in it
manual testing with raw, unsigned transaction
```
[ ] Yes
```
```
[ ] Yes
```

adds cli command to view details for raw, unsigned transactions

---

ironfish/src/memPool/recentlyEvictedCache.ts

This log pops up a lot in verbose mode and isn't that useful unless it's non-zero.
```
[ ] Yes
```
```
[ ] Yes
```

Only log transaction flushing if non-zero

---

ironfish/src/wallet/wallet.ts

The `eventLoopResolve` field on Wallet isn't used anywhere.
```
[ ] Yes
```
```
[ ] Yes
```

Remove unused eventLoopResolve in Wallet

---

ironfish/src/wallet/remoteChainProcessor.ts

`block.previous` is deprecated in our RPC layer, and elsewhere we use `block.previousBlockHash`, so updating this call.
```
[ ] Yes
```
```
[ ] Yes
```

Remove use of deprecated block.previous in RemoteChainProcessor

---

ironfish/src/migrations/data/021-add-version-to-accounts/schemaOld.ts

This code is not correct in the first place because it should never use current encoders or models in a migration.
Unused code.
```
[ ] Yes
```
```
[ ] Yes
```

Remove old migration code

---

ironfish/src/wallet/account/account.ts
ironfish/src/wallet/wallet.ts

This was merging an AccountValue type and walletDB into this. There's no reason to do that since the intent is to accept an AccountInfo, and a WalletDB constructor.
Run existing tests
```
[ ] Yes
```
```
[ ] Yes
```

Change account not to have 1 object constructor

---

ironfish/src/wallet/wallet.ts

I don't think the sequence values on the updateHead ScanState are used, but this fixes the TODO to update them properly by following the same pattern used for the rescan ScanState.
```
[ ] Yes
```
```
[ ] Yes
```

Fix scan state TODO in wallet code

---

ironfish/src/blockchain/blockchain.test.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/rpc/routes/chain/getBlocks.ts
ironfish/src/rpc/routes/chain/utils.ts

This adds a new method to the block chain by adding a new matching
method getBlockAtSequence which matches getHeaderAtSequence. It also
does not conflate data fetching with serialization so getBlocks is a lot
cleaner now.
Added a new test
```
[ ] Yes
```
```
[ ] Yes
```

Separate out block getter from RPC serialization

---

ironfish-cli/src/commands/wallet/notes/combine.ts

Adds raw transaction flag to notes:combine
Usecase: Create a transaction and post it separately using `wallet:post`. This is a common pattern we use with with other transaction types as well
```
[ ] Yes
```
```
[ ] Yes
```

adds raw transaction flag to combine notes

---

ironfish-cli/src/commands/wallet/rescan.ts
ironfish/src/rpc/routes/wallet/rescanAccount.ts

I'm open to opinions on whether this is more clear or not, but I was a bit confused by what was meant by a full scan. It looks like it only deletes createdAt from all accounts in the wallet before resetting them.
```
[ ] Yes
```
```
[ ] Yes
```

Update description of wallet:rescan

---

ironfish-cli/src/commands/wallet/transaction/view.ts

displays account names in alphabetical order when no account is specified by flags
before:
after:
```
[ ] Yes
```
```
[ ] Yes
```

sorts accounts by name in 'wallet:transaction:view'

---

ironfish/src/rpc/routes/wallet/startScanning.test.ts
ironfish/src/rpc/routes/wallet/startScanning.ts
ironfish/src/rpc/routes/wallet/stopScanning.test.ts
ironfish/src/rpc/routes/wallet/stopScanning.ts
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

This will persist scanningEnabled to the DB
```
[ ] Yes
```
```
[ ] Yes
```

Persist Account.scanningEnabled

---

ironfish/src/migrations/data/032-add-account-scanning.ts
ironfish/src/migrations/data/032-add-account-syncing/new/AccountValue.ts
ironfish/src/migrations/data/032-add-account-syncing/new/HeadValue.ts
ironfish/src/migrations/data/032-add-account-syncing/new/index.ts
ironfish/src/migrations/data/032-add-account-syncing/old/AccountValue.ts
ironfish/src/migrations/data/032-add-account-syncing/old/HeadValue.ts
ironfish/src/migrations/data/032-add-account-syncing/old/index.ts
ironfish/src/migrations/data/032-add-account-syncing/stores.ts
ironfish/src/migrations/data/index.ts
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/walletdb/accountValue.ts

This adds migration 032 to add a new field to AccountValue called `scanningEnabled` which is going to be used for controlling if an account should scan or not.
Run the migration and check the DB to see if the value persist or not.
```
[ ] Yes
```
```
[ ] Yes
```

Add syncingEnabled migration

---

ironfish/src/utils/types.ts
ironfish/src/wallet/exporter/encoders/bech32.ts
ironfish/src/wallet/exporter/encoders/multisigKeys.ts

These should not share the same encoder. It's possible to break old wallets by updating the account value Multisig encoder. There should be _no_ code share between the exporter system and the DB schemas.
Existing wallet import / export tests cover this.
```
[ ] Yes
```
```
[ ] Yes
```

Give bech32 encoder it's own multisig encoder

---

ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/wallet/exporter/accountImport.ts
ironfish/src/wallet/exporter/multisig.ts
ironfish/src/wallet/interfaces/multisigKeys.ts
ironfish/src/wallet/wallet.ts

These should not be located in the database schema module. They should be in the exporter code since it's only related to exporting and importing wallet data.
Existing tests and typescript checks cover this.
```
[ ] Yes
```
```
[ ] Yes
```

Moved multisig importing into wallet/exporter

---

ironfish/src/migrations/data/031-add-pak-to-account/new/AccountValue.ts
ironfish/src/migrations/data/031-add-pak-to-account/new/MultisigKeys.ts
ironfish/src/wallet/interfaces/multisigKeys.ts

031 is not using the correct multisig encoder that matches AccountValue. This leads to errors when you try to use the new migration for 31 in any future migration such as 32.
Run the migration on an old database.
```
[ ] Yes
```
```
[ ] Yes
```

Fix migration 031 to use proper multisig encoder

---

ironfish-cli/src/commands/mempool/transactions.ts
ironfish-cli/src/commands/peers/banned.ts
ironfish-cli/src/commands/peers/index.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/notes/index.ts
ironfish-cli/src/commands/wallet/status.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/table.ts

we typically do not want to truncate data that we display, especially hashes
- wraps oclif 'CliUx.ux.table.flags()' and adds a 'truncate' flag which defaults to false
- includes 'no-truncate' as a hidden flag that defaults to the inverse of the 'truncate' flag. this allows passing table flags to the oclif table constructor without handling our own truncate flag
- replaces all uses of oclif table flags with our own constant
manual testing with '--truncate' and '--no-truncate'
```
[ ] Yes
``` …

defaults cli tables to no-truncate

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/expiration.ts

Users will typically want to specify an expiration sequence when creating a raw or unsigned transaction, as otherwise by default they'll have 15 blocks to submit the transaction, which may not be long enough to sign it and submit it.
The check is optional, so if users leave the prompt blank, it'll use the default.
Manually tested: 
```
[ ] Yes
```
```
[ ] Yes
```

Prompt for expiration sequence when creating raw or unsigned transactions in CLI

---

ironfish-cli/src/commands/wallet/prune.ts

adds an '--account' flag to the 'wallet:prune' command to allow pruning expired transactions for one account at a time
manual testing
```
[ ] Yes
```
```
[ ] Yes
```

supports pruning expired tx for one account

---

ironfish-cli/src/utils/asset.ts

This will be useful for the integration with chainport to only display supported assets as options.
```
[ ] Yes
```
```
[ ] Yes
```

Adds ability to filter assets in cli utils

---

ironfish/src/rpc/routes/wallet/getAccountStatus.test.ts
ironfish/src/rpc/routes/wallet/getAccountsStatus.test.ts
ironfish/src/rpc/routes/wallet/setAccountHead.test.ts
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/wallet.test.slow.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

When downloading a snapshot for a new chain the option to set a new account's head value to the snapshot head would improve scanning performance.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Allow wallet to take createdAt for new account

---

ironfish-cli/src/utils/asset.ts

For mint, burn and send display whether the asset is verified or not and sort by verified assets
Tested locally
```
[ ] Yes
```
```
[ ] Yes
```

Show verified checkmark when selecting asset and sort by verified

---

ironfish/src/rpc/routes/wallet/setAccountHead.test.ts
ironfish/src/rpc/routes/wallet/setAccountHead.ts

Updates setAccountHead to take block hashes as well as transaction hashes. This avoids the need to do transaction-to-block lookups and dedupe the block headers when a block includes multiple relevant transactions.
```
[ ] Yes
```
```
[ ] Yes
```

Change setAccountHead to take blocks instead of transactions

---

ironfish-cli/src/utils/chainport/utils.ts

This summary will be used in the wallet:transaction command
Example output (outgoing transaction): 
```
[ ] Yes
```
```
[ ] Yes
```

adds chainport transaction summary util

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/utils/chainport/config.ts
ironfish-cli/src/utils/chainport/index.ts
ironfish-cli/src/utils/chainport/utils.ts
ironfish-cli/src/utils/index.ts

Detects bridge transactions in the transactions command. Example output: 
```
[ ] Yes
```
```
[ ] Yes
```

detect bridge transactions in wallet:transactions command

---

ironfish-cli/package.json
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts
ironfish-cli/src/utils/chainport/index.ts
yarn.lock

Also adds the web3-validator dependency to the ironfish-cli package.json to validate ethereum addresses
Send a bridge transaction using different assets to separate ethereum addresses that stake (eg: 0x5DF170F118753CaE92aaC2868A2C25Ccb6528f9a)/ don't stake(0x7A68B1Cf1F16Ef89A566F5606C01BA49F4Eb420A) PortX tokens. 
```
[ ] Yes
```
```
[ ] Yes
```

Adds wallet:chainport:send CLI command

---

ironfish-cli/src/commands/chain/rewind.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

This function is just a projection of a more generalized function and doesn't need to exist.
Updated tests
```
[x] Yes
```
Added to release docs
```
[ ] Yes
```

Remove Wallet.getLatestHeadHash()

---

ironfish-cli/src/commands/wallet/chainport/send.ts

Adds the feerate flag to this command
```
[ ] Yes
```
```
[ ] Yes
```

adds feerate to flags of chainport CLI command

---

ironfish/src/rpc/routes/chain/serializers.ts
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/scanner/remoteChainProcessor.test.ts
ironfish/src/wallet/scanner/remoteChainProcessor.ts
ironfish/src/wallet/scanner/scanState.ts
ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/wallet/wallet.ts

I have no idea why these types were introduced, but they were not necessary. You can just use the basic primitives we already have and not introduce brand new types to the code base.
There will be further changes to delete the initial index calculation and push it further down to the place where you actually loop over the transactions.
Existing tests cover the scanning and chain processor.
```
[ ] Yes
```
```
[ ] Yes
```

Delete WalletBlockHeader and WalletTransaction

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/notes/index.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts
ironfish-cli/src/commands/wallet/transactions.ts

some wallet commands take 'account' as a positional argument when it may make more sense as a flag.
adds account flag to commands that list things for an account: assets, balances, notes, transactions
adds account flag where commands are oriented around a transaction rather than an account: wallet:transaction, wallet:transaction:watch
parse flags and args so that account flag is preferred, but account arg still accepted
updates arg description to display that argument is deprecated
manual testing
```
[ ] Yes
``` …

adds account flag to wallet commands

---

ironfish/src/rpc/routes/wallet/setAccountHead.ts
ironfish/src/wallet/scanner/remoteChainProcessor.ts
ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

This was only used in a few places, and it's better for people down the callstack to calculate this since they are also given the header as well.
This is easier to review with https://github.com/iron-fish/ironfish/pull/5027/files?diff=split&w=1
```
[ ] Yes
```
```
[ ] Yes
```

Remove RemoteChainProcessor calculating noteIndex

---

ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/multisig/dealer/create.ts
ironfish/src/rpc/routes/wallet/exportAccount.test.ts
ironfish/src/rpc/routes/wallet/exportAccount.ts
ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/rpc/routes/wallet/multisig/createSigningCommitment.test.ts
ironfish/src/rpc/routes/wallet/multisig/integration.test.slow.ts

For backwards compatability, we used to allow users to import/export AccountImport types instead of strings. Now we only allow importing / exporting encoded accounts.
```
[x] Yes
```
https://github.com/iron-fish/website/pull/709
```
[x] Yes
```
Added to the release draft

Removes the ability to import/export AccountImport

---

ironfish-cli/src/args.ts
ironfish-cli/src/commands/blocks/show.ts
ironfish-cli/src/commands/chain/asset.ts
ironfish-cli/src/commands/chain/benchmark.ts
ironfish-cli/src/commands/chain/download.ts
ironfish-cli/src/commands/chain/export.ts
ironfish-cli/src/commands/chain/readd-block.ts
ironfish-cli/src/commands/chain/rewind.ts
ironfish-cli/src/commands/config/get.ts
ironfish-cli/src/commands/config/set.ts
ironfish-cli/src/commands/config/unset.ts
ironfish-cli/src/commands/peers/show.ts
ironfish-cli/src/commands/rpc/token.ts
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/delete.ts
ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/notes/combine.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/commands/wallet/transaction/import.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts

oclif already trims by default. By adding these trims, we're overriding the behavior of oclif and closing unintentional escape hatches for cases where a leading/trailing space might be intended when wrapping the arg or flag in quotation marks.
There are a few more places where `trim` is being used in the CLI commands, but they are generally being used as part of more complex split functions, or are deep enough down the call stack that I didn't want to potentially cause issues for now.
N/A
N/A

Remove unnecessary trims from CLI commands

---

ironfish/src/wallet/validator.ts

This function isn't checking if you have allowed characters, its specifically checking if a string is hex encoded. This makes it more clear.
```
[ ] Yes
```
```
[ ] Yes
```

Rename isHexEncoding to be more clear

---

ironfish/src/rpc/routes/wallet/setAccountHead.ts

We only need the transactions in this place so we don't need the materialized projection.
```
[ ] Yes
```
```
[ ] Yes
```

Remove usage of chain.getBlockTransactions

---

ironfish-cli/src/commands/blocks/show.ts
ironfish-cli/src/commands/chain/asset.ts
ironfish-cli/src/commands/chain/broadcast.ts
ironfish-cli/src/commands/chain/export.ts
ironfish-cli/src/commands/chain/power.ts
ironfish-cli/src/commands/chain/repair.ts
ironfish-cli/src/commands/chain/show.ts
ironfish-cli/src/commands/config/get.ts
ironfish-cli/src/commands/config/set.ts
ironfish-cli/src/commands/config/unset.ts
ironfish-cli/src/commands/peers/show.ts
ironfish-cli/src/commands/wallet/address.ts
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/create.ts
ironfish-cli/src/commands/wallet/delete.ts
ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/reset.ts
ironfish-cli/src/commands/wallet/scanning/off.ts
ironfish-cli/src/commands/wallet/scanning/on.ts
ironfish-cli/src/commands/wallet/transaction/import.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transaction/view.ts
ironfish-cli/src/commands/wallet/transaction/watch.ts
ironfish-cli/src/commands/wallet/use.ts

~~**Builds on #5031**~~ (merged)
Normalize arg destructuring and remove a few extra `as` casts
N/A
N/A

Normalize arg destructuring and remove a few extra `as` casts

---

ironfish/src/sdk.ts
ironfish/src/testUtilities/nodeTest.ts

This argument was unused.
```
[ ] Yes
```
```
[ ] Yes
```

Remove the `fishHashContext` argument from `sdk.node()`

---

ironfish/src/testUtilities/nodeTest.ts
ironfish/src/workerPool/pool.ts

The worker pool is a thread pool that allows multiple jobs to run concurrently. The worker pool is normally started only when a full node is initialized. If a full node is not initialized, then no separate thread is started, and jobs are not run concurrently but sequentially.
This means that the performance of CLI commands that use the worker pool, like `wallet:rescan`, can vary drastically depending on whether a full node is running or not. This behavior is not documented and far from obvious from a user prospective.
To always offer the best performance, this commit changes the worker pool to ensure that threads are always spawned before executing any job.
with a node NOT running:
- Run `wallet:rescan` before this change. Observe that the CPU utilization does not exceed 100%
- Run …

Automatically start the worker pool if a job is submitted

---

ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/rpc/routes/wallet/multisig/createTrustedDealerKeyPackage.ts
ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/testUtilities/matchers/index.ts
ironfish/src/testUtilities/matchers/string.ts
ironfish/src/wallet/exporter/account.ts
ironfish/src/wallet/exporter/encoder.ts
ironfish/src/wallet/exporter/encoders/base64json.test.ts
ironfish/src/wallet/exporter/encoders/base64json.ts
ironfish/src/wallet/exporter/encryption.test.ts
ironfish/src/wallet/exporter/encryption.ts
ironfish/src/wallet/exporter/multisig.ts

This fixes the fact that we attempted to add encryption to our encoder
itself, but it was nerver fully inserted into the encoding because the
decoding flow never used the wallet to try all the secrets. This means
the encryption of an encoded account was only half in the encoding
system, and half out.
This introduces a very clear separate module at
Wallet/Exporter/Encryption which has all the methods to handle
encryption.
- Added new tests
- Revised old tests
```
[ ] Yes
``` …

Separate out account decoding from encrypting

---

ironfish/src/blockchain/blockchain.ts

`VerifyError` becomes `VerifyError: Transaction is a duplicate` when thrown
N/A
N/A

Add error message for VerifyError

---

ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/utils/chainport/types.ts
ironfish-cli/src/utils/chainport/utils.ts

Chainport just sent us some new information about how to use the transaction status API. These changes reflect the new interaction. 
There is also a difference in types. Chainport either sends us an empty object or a body with all keys that either have a type of string or null. 
Examples below: 
Pending transaction: 
Confirmed transaction: 
```
[ ] Yes
```
```
[ ] Yes
```

update parsing of chainport status API to new interface

---

ironfish-cli/src/commands/wallet/transactions.ts

The error here is that the error in `getAccountTransactionsStream` becomes unhandled, because we pause the event loop to wait on `getNetworkInfo`. The error handler for `getAccountTransactionsStream` isnt registered until we await it's content stream later on. Unfortunately because `getNetworkInfo` prevents that form happening it'll be treated as an unhandled exception which crashes in oclif itself.
Revert the code and use `ironfish wallet:transactions gidhjfgdfsgfdsfgds`. The account should not exist and it will reproduce the error.
```
[ ] Yes
```
Is this a breaking change? If yes, …

Fix transactions cmd not handling streaming errors

---

ironfish-cli/package.json
ironfish/package.json
ironfish/src/assets/assetsVerificationApi.ts
package.json
yarn.lock

Our axios version is fairly old and has a few reported vulnerabilities. This PR updates it to the latest version.
Fixes IFL-2665
```
[ ] Yes
```
```
[ ] Yes
```

Update axios to 1.7.2

---

ironfish-rust-nodejs/src/lib.rs
ironfish-rust/src/sapling_bls12.rs

The Sapling parameters defined in `ironfish::sapling_bls12::SAPLING` are behind a `lazy_static`. As such, the parameters are not loaded until accessed fo the first time. The purpose of `initializeSapling` is to acccess the parameters to ensure that they get loaded early.
The current implementation of `initializeSapling` was calling `.clone()` on `ironfish::sapling_bls12::SAPLING`, causing large amounts of memory to be allocated and written, only to be discarded shortly afterwards. The implementation has been changed to just dereference `SAPLING`, without doing anything else. This is enough to trigger `lazy_static` to load the parameters.
Also:
- Removed the `Arc` from `ironfish::sapling_bls12::SAPLING`: `Arc` is used to extend lifetimes in multithreaded environments, but the lifetime of …

Change `initializeSapling` to avoid cloning

---

Cargo.lock
ironfish-rust-nodejs/Cargo.toml
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/lib.rs
ironfish/src/fileStores/config.ts
ironfish/src/workerPool/pool.ts
supply-chain/audits.toml
supply-chain/imports.lock

This commit changes the default value for `nodeWorkersMax` to the number of CPU cores, minus one, capped at 16. Before this change, `nodeWorkersMax` was hardcoded to 6.
As a consequence of this change, most users with empty configuration will observe a larger number of workers spawned. Users who run on systems with SMT enabled and wi.
For example: on a system with 2 cores, with SMT enabled (4 logical CPUs in total), and empty configuration: before this change, the number of workers would have been .
The rationale behind using the number of CPU cores rather than the number of logical CPUs is that the worker pool should mostly be used for CPU-bound and CPU-intensiv.
This commit also changes the default value for `nodeWorkers` to be based on the number of processing units available to the …

Improve the calculation for the number of workers in the worker pool

---

ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

All the use cases for `DecryptNotesTask` involve passing a bunch of notes to decrypt for the same account(s), and with the same options. To save bandwidth, and to allow future optimizations, it makes sense to group all account keys into a single input parameter, so that they don't have to be repeated for each and every note.
This changes the request serialization size from `O(accounts * notes)` to `O(accounts + notes)`.
This change may not offer a huge performance boost by itself, but it allows future improvements, including:
* the use of faster decryption algorithms when more than 1 account is involved
* fewer (de)serializations of account keys
* better batching of decrypt requests, and larger batches of encrypted notes with less memory overhead
Unit tests
N/A
SDK breaking change:
- the …

Change `DecryptNotesRequest` to require a common list of accounts and options

---

ironfish/src/workerPool/tasks/decryptNotes.ts

In the vast majority of the cases, a `DecryptNotesResponse` will contain zero or close-to-zero decrypted notes. It makes sense to have the serialization of `DecryptNotesResponse` optimize for those cases.
This changes the serialization size of `DecryptNotesResponse` from `O(null_notes + non_null_notes)` to `O(non_null_notes)`.
This introduces a small size overhead in the case where the are a lot of decrypted notes. We could in theory have `DecryptNotesResponse` choose between sparse and dense serialization based on how many decrypted notes there are, but that case is so rare, and the overhead so small, that it's not worth optimizing for it.
Unit tests
N/A
N/A

Change `DecryptNotesResponse` to use a sparse serialization format

---

ironfish/src/rpc/routes/wallet/resetAccount.test.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

now that we use networkId in account imports to determine whether the createdAt sequence refers to a block on the same chain the hash is no longer needed. it is mostly vestigial, like the appendix or the wings of a kiwi bird
these changes remove remaining references to createdAt.hash
existing unit tests
```
[ ] Yes
```
```
[ ] Yes
```

removes references to account createdAt hash

---

ironfish/src/node.ts
ironfish/src/wallet/scanner/chainProcessorWithTransactions.ts
ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

This PR changes it so if you're running the wallet inside of the node,
instead of iterating the chain using the RPC system it'll use the
chain directly. This is a large performance optimziation when scaanning
the blockchain.
There is no new test here, but the RemoteChainProcessor has tests, and the ChainProcessor already has tests.
```
[ ] Yes
```
```
[ ] Yes
```

Have WalletScanner use chain directly if available

---

ironfish-cli/src/commands/wallet/import.ts
ironfish/src/rpc/routes/wallet/__fixtures__/importAccount.test.ts.fixture
ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/wallet.ts

adds a 'createdAt' field to ImportAccountRequest that takes a sequence to use for the account's createdAt field
if a 'createdAt' sequence is passed to importAccount, then the account's createdAt uses that sequence and an empty hash (hash is no longer used in createdAt)
adds createdAt flag to wallet:import command
- adds unit test for rpc
- manual testing with cli
```
[X] Yes
```
https://github.com/iron-fish/website/pull/712
```
[ ] Yes
```

supports setting createdAt on account import

---

ironfish-cli/src/utils/chainport/requests.ts
ironfish-cli/src/utils/chainport/types.ts

1. Adds a new makeChainportRequest function that wraps the existing makeRequest function and adds error handling for chainport requests
2. This function takes a generic type parameter T that represents the expected response type
3. If the response is not successful, the function throws an error with the response status and message
For reference, this is their new error return type schema https://iflabs.slack.com/archives/C0677Q1AGDD/p1718793349123629
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it with `breaking-change-rpc` or …

Adds error handling to chainport requests

---

ironfish-cli/package.json
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/utils/chainport/address.test.ts
ironfish-cli/src/utils/chainport/address.ts
yarn.lock

Reduces our dependency on web3-validator which is a large package and is not used in many places. Only dependency used now is keccak which is used in the checksum validation function.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Replaces isAddress depdenency with our own implementation

---

ironfish-cli/src/utils/chainport/requests.ts
ironfish-cli/src/utils/chainport/types.ts

Reflects the latest changes from Chainport's API error objects
Example error blacklisted address: 
Example error exception thrown on Chainport's end: 
```
[ ] Yes
```
```
[ ] Yes
```

updates error handling to their new API response 400 object

---

ironfish/src/__fixtures__/chainProcessor.test.ts.fixture
ironfish/src/chainProcessor.test.ts
ironfish/src/chainProcessor.ts
ironfish/src/wallet/scanner/chainProcessorWithTransactions.ts
ironfish/src/wallet/scanner/walletScanner.ts

This adds similar optional pagination that the RemoteChainProcessor has to the ChainProcessor. This is useful if you want to stop after a certain amount of blocks to perform other work.
```
[ ] Yes
```
```
[ ] Yes
```

Introduce optional pagination to ChainProcessor

---

.github/workflows/deploy-npm-ironfish-rust-nodejs.yml
.github/workflows/publish-binaries.yml

These jobs were still using v3, which is incompatible with v4 internally even though we didn't use any of the external stuff that changed.
https://github.com/iron-fish/ironfish/actions/runs/9653954995
N/A
N/A

Update remaining artifact github actions to v4

---

Cargo.lock
ironfish-rust-nodejs/Cargo.toml
ironfish-rust-nodejs/package.json
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/stats.rs
ironfish-rust/Cargo.toml
ironfish-rust/src/merkle_note.rs
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This commit adds an optional feature (that can be enabled only during local development) to print the number of cryptographic operations performed for note decryption and encryption.
This feature is enabled by building `ironfish-rust-nodejs` through `yarn build:stats`. After doing that, and after starting `ironfish-cli` through `yarn start <command>`, it is possible to trigger the printing of the statistics by sending `SIGUSR1` to the CLI process. The statistics will look like this:
```
Elliptic Curve Point Multiplication Stats:
• affine muls: 0
• extended muls: 752
Note Encryption Stats:
• total: 3
Note Decryption Stats:
• for owner: 107 (17 [15.89%] successful)
• for spender: 3 (3 [100.00%] successful)
```
All the code related to this feature is in Rust only, and hidden behind a feature …

Add a development-only feature to print statistics related to notes encryption

---

ironfish/src/__fixtures__/chainProcessor.test.ts.fixture
ironfish/src/chainProcessor.test.ts
ironfish/src/chainProcessor.ts

We only ever cared if work was done, not that the specific hash was changed from the original. This does change the behaviour, but I looked at everywhere it's used and it should not affect the overall behaviour.
```
[ ] Yes
```
```
[ ] Yes
```

Simplify ChainProcessor return logic

---

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts

makes it explicit that this should be the round 2 secret package
manual testing: 
```
[ ] Yes
```
```
[ ] Yes
```

fixes dkg round3 prompt for secret package

---

ironfish-cli/src/commands/wallet/rescan.ts

Running `wallet:rescan` when not connected to a node produces output like the following:
```
Scanning blocks: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 60 / 624032 | 0.00 / sec | ETA: N/AAdded block seq: 100, hash: 00000...bd9a1
Scanning blocks: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 128 / 624032 | 0.00 / sec | ETA: N/AAdded block seq: 200, hash: 00000...c61b7
Scanning blocks: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 282 / 624032 | 0.00 / sec | ETA: N/AAdded block seq: 300, hash: 00000...194db
```
That is: the progress bar output is disrupted by the scanner logs.
This commit suppresses the logs coming from the wallet so that the progress bar is the only output displayed.
Run `yarn start wallet:rescan` while a node is NOT running and observe the output.
N/A
N/A

Suppress logs during nodeless wallet rescans

---

ironfish-cli/src/commands/test-evm.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/__fixtures__/verifier.evm.test.ts.fixture
ironfish/src/consensus/verifier.evm.test.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/primitives/evmDescription.ts
ironfish/src/wallet/wallet.ts

Simple `EvmDescription` verification via the EVM. This is a roundtrip transaction that passes through rust, to node typescript, and then to EVM.
Simply verifies the transaction is executable. Only form of validation explicitly done is signature for the unit test.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

adds minimal verification to ironfish transactions for evm

---

ironfish-cli/src/commands/wallet/send.ts

Make unsignedTransaction flag visible in send command. Will be required for adding signatures using ledger devices to this transaction. 
```
[ ] Yes
```
```
[ ] Yes
```

Make unsignedTransaction flag visible in send command.

---

ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

The goal of this PR is to move that chunk of code to a location where it's more easily reusable. The plan is to use the new method introduced here in PR-5058: that PR will be changed to not call `WorkerPool.decryptNotes()` anymore, but rather call `WorkerPool.execute()` to obtain the individual jobs.
Unit tests
N/A
N/A

DecryptNotes: move the code that groups notes by account from WorkerPool to the response class

---

ironfish-cli/src/commands/chain/repair.ts
ironfish-cli/src/commands/chain/rewind.ts
ironfish-cli/src/commands/test-evm.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/blockchaindb.test.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/blockchain/index.ts
ironfish/src/chainProcessor.test.ts
ironfish/src/consensus/verifier.evm.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/evm/database.ts
ironfish/src/evm/evm.ts
ironfish/src/network/peerNetwork.ts
ironfish/src/storage/database/transaction.ts
ironfish/src/storage/levelup/store.ts
ironfish/src/typedefs/buffer-map.d.ts
ironfish/src/wallet/scanner/remoteChainProcessor.test.ts
ironfish/src/wallet/wallet.test.ts

the ethereumjs packages implement their own systems for committing changes to the underlying database
plumbing our own database transaction objects down through several layers will require significant refactoring to evm caching and database access
BlockchainDBTransaction wraps an IDatabaseTransaction and inserts logic to use the evm stateManager's checkpoint logic for committing and reverting state changes
implements transaction and withTransaction methods on the BlockchainDB and replaces access of the underlying db instance with these transaction methods to ensure that BlockchainDBTransactions are used
moves stateManager directly onto BlockchainDB to support access in transaction context …

implements BlockchainDBTransaction to wrap EVM state changes

---

ironfish/src/workerPool/tasks/jobAbort.ts
ironfish/src/workerPool/worker.ts

`Job.abort()` sends a `JobAborted` request to the worker. `Worker.onMessageFromParent()` is able to handle such requests, but `Worker.parseRequest()` rejects them. Fixed `Worker.parseRequest()` so that such requests are no longer rejected.
Also fixed `JobAbortedMessage.deserializePayload()` to return the correct type.
N/A
N/A

Fix `Worker` handling of `JobAborted` requests

---

ironfish/src/fileStores/config.ts
ironfish/src/utils/asyncQueue.test.ts
ironfish/src/utils/asyncQueue.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/scanner/__fixtures__/noteDecryptor.test.ts.fixture
ironfish/src/wallet/scanner/__fixtures__/walletScanner.test.ts.fixture
ironfish/src/wallet/scanner/noteDecryptor.test.ts
ironfish/src/wallet/scanner/noteDecryptor.ts
ironfish/src/wallet/scanner/walletScanner.test.ts
ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/pool.ts

A wallet scan currently works like this:
```mermaid
graph LR;
r[read block]-->d[decrypt notes]
d-->u[update accounts]
u-.->r
```
*read block* and *update accounts* are primarily IO-bound operations, and they run in the main thread only. This means that while *read block* and *update accounts* are running, the CPUs are under-utilized.
To maximize CPU utilization (and therefore improve scan performance), the scan has been changed to look like this:
```mermaid
graph LR;
r[read block]-.->r
r-->q[queue]
q-->d[decrypt notes]
d-->u[update accounts]
```
With this new algorithm, *read block* will try to read as many blocks as possible, without stopping, and place them on a queue. The queue is consumed and notes are decrypted in parallel inside the worker threads. Because *read block* is …

Maximize decryption parallelism during wallet scans

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/note_encrypted.rs
ironfish-rust/src/merkle_note.rs
ironfish-rust/src/serializing/mod.rs
ironfish/src/primitives/noteEncrypted.ts
ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

Wallet scans get the blocks/transactions/notes from the chain db. The chain db contains data that has already been validated in the past (or that otherwise is assumed to be valid). For this reason, it should be possible to speed up scans by skipping expensive validation performed when parsing notes.
More specifically, `NoteEncrypted` parses some elliptic curve points in compressed form. The regular parsing done through `jubjub::SubgroupPoint::from_bytes()` involves an expensive check: it checks whether the uncompressed point belongs to the prime-order subgroup. This check is perfromed using elliptic curve point multiplication, which is the most predominant and slowest operation happening during wallet scans.
Due to this check, for each note, the wallet currently performs two elliptic …

Fast construction of `NoteEncrypted` during wallet scans

---

ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.ts

In the case that the records to cleanup is very high, we shouldn't load all of them in memory before cleaning up. We should only load 1 leveldb memory block at most. This will ensure if there is a bad feedback loop this list won't permanently grow and continue to use more memory as it tries to clean up accounts.
This also ensures that the account record deletion is considered a record so deleting thousands of empty account cleanup records doesn't run forever.
Running this with a lot of wallets and using the reset command.
```
[ ] Yes
```
Is this a breaking change? If yes, add notes …

Wallet cleanup should use an iter to load records

---

config/eslint-config-ironfish/index.js
config/eslint-plugin-ironfish/index.js
ironfish/src/utils/asyncQueue.test.ts
ironfish/src/wallet/scanner/noteDecryptor.ts

@andiflabs did some great investigation to discover that Promise.race leaks memory, and the TL;DR is it'll be easiest to generally avoid using Promise.race. I added a lint rule to catch uses of this in the future, and added workarounds for our current use.
Run `status -f` and watch the memory usage while rescanning to observe it doesn't rapidly increase.
```
[ ] Yes
```
```
[ ] Yes
```

Add lint rule to not use Promise.race

---

ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/wallet/wallet.ts

Calling `Wallet.reset()` while a scanning is running can sometimes result in race conditions. In particular, `WalletScanner` may attempt to query account heads at the same time while accounts are being reset, resulting in errors.
This commit fixes the problem by using database transactions (1) while `WalletScanner` read accounts and (2) while `Wallet.reset()` updates accounts.
This commit also adds transactions in `Wallet.getEarliestHead()` and `Wallet.getLatestHead()`. These methods are not used during scanning, but they suffer from the same kind of problem.
Note that this commit fixes specific race conditions related to getting the list of accounts to scan, but other race conditions that affect scanning may still exist.
N/A
N/A

Prevent race conditions when getting list of accounts during scanning

---

ironfish/src/wallet/wallet.ts

If we keep the DB transaction outside of options objects to the end, starting transactions becomes cleaner. Most places already do this.
```
[ ] Yes
```
```
[ ] Yes
```

Move transactions outside of options

---

ironfish/src/wallet/scanner/scanState.ts

when started the Meter class sets an interval to update its underlying arrays. if the meter is not stopped then this interval will keep running and keep the meter in the heap and leaks the meter memory.
the WalletScanner creates a new ScanState and a new Meter for each scan. when the wallet is at the head of the chain this creates a new scan each time a block is added.
fixes the memory leak by ensuring that the ScanState Meter is stopped when the scan completes and its interval function is cleared
memory profiling with Chrome Developer Tools
```
[ ] Yes
```
Is this a breaking change? …

stops scanState meter on scan completion

---

ironfish/src/rpc/routes/wallet/postTransaction.ts
ironfish/src/wallet/wallet.ts

replaces 'getAccountByPublicAddress' with a more generic 'findAccount' that takes a predicate
uses findAccount in postTransaction to find the account that has the same public address and is a spending account
fixes issue where wallet has a spending account and a view only account with the same public address and cannot post a transaction
```
[ ] Yes
```
```
[ ] Yes
```

ensures that postTransaction uses a spending account

---

ironfish-cli/Dockerfile
ironfish-cli/scripts/build-docker.sh

Send to the Docker build daemon the necessary files from the `.git` directory so that the build scripts can extract the hash of the HEAD commit.
Also fixed a style warning while at it.
1. Run `ironfish-cli/scripts/build-docker.sh` *before* this change
1. Observe that `docker run --rm ironfish:latest status` reports `git src`
1. Run `ironfish-cli/scripts/build-docker.sh` *after* this change
1. Observe that `docker run --rm ironfish:latest status` reports something like `git 2c1b2737`
N/A
N/A

Include the git commit hash in Docker images

---

ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

When importing an account twice, it would not print out the name of the account with the duplicate spending key. This will now include that in the message.
It also improves tests to check the error type instead of error message. We should avoid testing error messages in tests if there is a proper typed error to check.
Created in response to this, https://github.com/iron-fish/ironfish/issues/5084
1. Create a spending key account
- `ironfish wallet:create foobar`
2. Export account
- `ironfish wallet:export foobar --mnemonic`
3. Import account
- `ironfish wallet:import --name bazmonkey <mnemonic>`
4. Check error includes the name `foobar` which already contains the mneomonic
- `Account (foobar) already exists with provided spending key`
5. Delete account `ironfish wallet:delete foobar`
Does …

Import duplicate spending key says account name

---

ironfish-cli/src/utils/ledger.ts

Specifically calling out to the user to unlock the ledger device if it is locked. This is a different error for an unlocked device but a closed Ironfish ledger app.
```
[ ] Yes
```
```
[ ] Yes
```

Add check for locked ledger device

---

ironfish-cli/package.json
ironfish-cli/src/commands/chain/genesisadd.ts
ironfish-cli/src/commands/chain/genesisblock.ts
ironfish-cli/src/commands/mempool/transactions.ts
ironfish-cli/src/commands/peers/banned.ts
ironfish-cli/src/commands/peers/index.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/multisig/participants/index.ts
ironfish-cli/src/commands/wallet/notes/combine.ts
ironfish-cli/src/commands/wallet/notes/index.ts
ironfish-cli/src/commands/wallet/status.ts
ironfish-cli/src/commands/wallet/transaction/index.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/ui/confirm.ts
ironfish-cli/src/ui/index.ts
ironfish-cli/src/ui/progressBar.ts
ironfish-cli/src/ui/table.ts
ironfish-cli/src/utils/table.ts
yarn.lock

Since oclif 4.x removes their table feature, lets implement our own. The logic
is straight-forward enough that doing this was a reasonable task. The
alternative CLI table libraries didn't have the specific features we use, and
were generally over-engineered for our use.
This does remove some functionality that we were not using, as well as
potentially removing some extra usability that users may miss. We can re-add
these things as needed.
Manually tested the commands side-by-side
N/A
N/A

Implement custom CLI table logic

---

ironfish-cli/src/commands/wallet/send.ts

Add `--ledger` to `wallet:send` command. 
Send transactions with a ledger device using the `--ledger` flag with the `--watch` and `--confirm` flags. Send a transaction with another account that isn't the ledger account. 
```
[ ] Yes
```
```
[ ] Yes
```

add ledger flag to send command

---

ironfish-cli/src/commands/faucet.ts
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/create.ts
ironfish-cli/src/commands/wallet/delete.ts
ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/multisig/dealer/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/participant/create.ts
ironfish-cli/src/commands/wallet/notes/combine.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/ui/index.ts
ironfish-cli/src/ui/prompt.ts
ironfish-cli/src/utils/currency.ts
ironfish-cli/src/utils/expiration.ts

ux.prompt is being removed in oclif 4.x, so in preparation for that, we will use inquirer for input prompts. We are already using inquirer for selection and confirm prompts, so there isn't really anything new in this change.
N/A
N/A

Replace ux.prompt for oclif 4.x upgrade prep

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/note_encrypted.rs
ironfish-rust-nodejs/tests/demo.test.slow.ts
ironfish-rust/src/keys/view_keys.rs
ironfish/src/primitives/noteEncrypted.ts
ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/wallet/scanner/noteDecryptor.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts
ironfish/src/workerPool/tasks/workerMessage.ts
ironfish/src/workerPool/tasks/workerMessages.test.perf.ts
ironfish/src/workerPool/worker.ts

This changes the way the worker pool and the workers communicate in the following way:
- Buffers sent to/from workers are now "transferred". This is a feature of `MessagePort.postMessage()` that allows to transfer ownership of certain objects to the receiving side, avoiding cloning, thus improving the performance of every worker.
- It's now possible to send to the workers an optional `SharedArrayBuffer` as an input (in addition to the `Buffer` that is already supported).
The `BackgroundNoteDecryptor` used by the wallet scanner has been updated to make use of `SharedArrayBuffer` to store the account keys.
This is a draft because it requires https://github.com/iron-fish/jubjub/pull/4 to be merged first.
* Run `wallet:rescan` for a set amount of time with a tool to measure memory usage and …

Worker pool: use the transfer feature and shared buffers for message posting

---

ironfish-cli/src/commands/evm/persist-state.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/evm/stateManager.ts

defines a custom IronfishStateManager extension of the DefaultStateManager
adds an 'open' method that initializes the Trie on the database using 'Trie.create'
the 'Trie' constructor always initializes the Trie with an empty root, which renders existing data unreachable
adds a 'persist-state' command to test and demonstrate data persistence
```
[ ] Yes
```
```
[ ] Yes
```

fixes stateManager persistence

---

ironfish/src/rpc/routes/wallet/utils.ts
ironfish/src/wallet/scanner/noteDecryptor.ts
ironfish/src/wallet/wallet.ts
ironfish/src/workerPool/pool.ts
ironfish/src/workerPool/tasks/decryptNotes.test.ts
ironfish/src/workerPool/tasks/decryptNotes.ts

Most of the note decryption will fail. Currently, if a `DecryptNotesResponse` contains 100 undecrypted notes, it will create a dense array containing 100 `null` values, causing unnecessary large memory allocations and large memory writes. It was in fact observed that the arrays from `DecryptNotesResponse` were one of the top contributors to memory usage during wallet scans.
This commit changes the implementation so that now `DecryptNotesResponse` would create a sparse array containing no values at all. This means that, when no notes are decrypted (i.e. the most common case), all `DecryptNotesResponse` objects consume the same amount of memory, regardless of how many accounts are in the wallet, or how many encrypted notes were requested.
This was shown to reduce the peak memory usage of …

Use a sparse array in `DecryptNotesResponse`

---

ironfish/src/utils/bloomFilter.test.ts
ironfish/src/utils/bloomFilter.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

This commit adds an in-memory bloom filter to remember which nullifiers are stored in the database. The bloom filter is used by `WalletDB.loadNoteHash()` to avoid querying the database if the given nullifier is known to be not present.
While at it, `WalletDB.getTransactionHashFromNullifier()` was optimized in the same way.
* unit tests
* `wallet:rescan`
N/A
N/A

Optimize `WalletDB.loadNoteHash()` to avoid hitting the database if the note nullifier is known to be absent

---

ironfish-cli/src/commands/wallet/sign.ts

Renders transaction summary at the end of the sign command.
```
[ ] Yes
```
```
[ ] Yes
```

Renders transaction summary at the end of the sign command.

---

ironfish-cli/src/commands/test-evm.ts
ironfish/src/evm/__fixtures__/evm.test.ts.fixture
ironfish/src/evm/database.ts
ironfish/src/evm/evm.test.ts
ironfish/src/evm/evm.ts

adds 'withCopy', inspired by withTransaction, to use a shallow copy of the underlying vm for execution
using challowCopy creates a vm instance with empty caches over the committed database state. use of shallowCopy follows the example of gas estimation https://github.com/ethereumjs/ethereumjs-monorepo/blob/cc2848a1f3fc0ebb8c04cf6e9f76b0992e506c2c/packages/client/src/rpc/modules/eth.ts#L535
wraps handler execution with checkpoint/revert logic over the evm journal to ensure that cached state is not committed to the database
updates EvmStateDB to return itself in shallowCopy so that it does not create a duplicate datastore
related …

adds IronfishEvm methods to simulate tx execution

---

ironfish-cli/src/commands/evm/deploy-contract.ts
ironfish-cli/src/commands/test-evm.ts
ironfish/package.json
ironfish/src/evm/evm.ts
yarn.lock

sets block header in runTx to use a baseFeePerGas of 0, which makes gas free to use
modifies test-evm command to send transaction without gas price
```
[ ] Yes
```
```
[ ] Yes
```

turns off gas fees for evm transactions

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/blockchain/schema.ts

Updates mapping of Asset ID (ironfish) to EVM (contract token) to be bidirectional. Uses a prefix on the storage to prevent collisions.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

updating bidirectional mapping for asset to contract/token

---

ironfish/src/blockHasher.test.ts
ironfish/src/blockHasher.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/headers.ts
ironfish/src/consensus/verifier.test.ts
ironfish/src/consensus/verifier.ts
ironfish/src/evm/evm.ts
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts
ironfish/src/network/utils/serializers.ts
ironfish/src/primitives/blockheader.ts
ironfish/src/rpc/routes/miner/submitBlock.ts
ironfish/src/serde/BlockTemplateSerde.ts

adds an optional stateCommitment field to the block header
updates serialization and deserialization of block headers to include the stateCommitment, if present
adds logic to verifyConnectedBlock to verify that the stateCommitment from the header is equal to the stateRoot from the state manager after all transactions have been executed
set activation sequence for EVM on devnet and started mining blocks that include stateCommitment after activation sequence
```
[ ] Yes
``` …

add stateCommitment to block header

---

ironfish-cli/src/commands/chain/assets/info.ts

Closes IFL-2775
Removes the CLI command `ironfish chain:asset`. The command is now `ironfish chain:assets:info`.

Move `chain:asset` to `chain:assets:info`

---

ironfish-cli/src/commands/chain/blocks/info.ts

Closes IFL-2773
N/A
Removes the CLI command `ironfish blocks:show`. The command is now `ironfish chain:blocks:info`.

Move `blocks:show` to `chain:blocks:info`

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/chain/getNetworkHashPower.test.ts
ironfish/src/rpc/routes/chain/getNetworkHashPower.ts

This makes the usability nicer because there are no mandatory arguments.
```
[ ] Yes
```
```
[ ] Yes
```

Make rpc get network power request optional

---

ironfish/src/networks/network.ts
ironfish/src/networks/networkDefinition.ts

So we can reuse this in the CLI and make this consistent everywhere.
```
[ ] Yes
```
```
[ ] Yes
```

Abstract out rendering network name

---

ironfish-cli/src/ui/card.ts
ironfish-cli/src/ui/index.ts

So we can render these horizontal cards more easily.
Example
```
Network:      Mainnet (1)
Blocks:       656880
Synced:       false
Difficulty:   0
Size:         15.41 GB
Work:         15411118322
Power:        0 H
Hash:         000000000000fd9c207f0c91f45ed1aac0413af20c87b4a9bc70cc7cfb5e8ecc
Time:         1721257179702
```
```
[ ] Yes
```
```
[ ] Yes
```

Add UI card element to CLI

---

ironfish-cli/src/commands/chain/status.ts

```
> ironfish chain:status
Network:      Mainnet
Blocks:       656880
Hash:         000000000000fd9c207f0c91f45ed1aac0413af20c87b4a9bc70cc7cfb5e8ecc
Time:         7/17/2024, 3:59:39 PM
Synced:       false
Difficulty:   178062303183912
Size:         15.41 GB
Work:         15411118322
Power:        2.69 TH
```
```
[x] Yes
```
```
[ ] Yes
```

Add command chain:status

---

ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
ironfish/src/mining/manager.test.slow.ts
ironfish/src/mining/manager.ts

as the mining manager takes transactions from the mempool during block template construction it performs some basic verification and skips any invalid transactions. this prevents the mining manager from getting stuck producing templates that include invalid transactions
each evm transaction in the mempool is verified individually, but may be invalid when sequenced after another evm transaction. for instance, if a later transaction uses the same nonce as an earlier transaction, or if it causes an insufficient funds error after an earlier transaction is executed.
adds logic to getNewBlockTransactions to call verifyEvm on each evm transaction taken from the mempool to avoid invalid evm transactions
uses withCopy to prevent database commits from evm transaction execution. transactions are …

manager verifies evm transactions during template construction

---

ironfish-cli/src/commands/evm/deploy-contract.ts
ironfish-cli/src/commands/test-evm.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/verifier.ts
ironfish/src/evm/evm.ts

Previously, we needed to check whether the EVM on the blockchain object was instantiated. There shouldn't be a case where EVM is not instantiated. We should always have an EVM instance.
That change was made because instantiating EVM requires async code because of the VM instantiation.
This change changes that pattern to a synchronous instantiation. The VM instantiation now happens in the open function that is no longer static. We check whether the object has been instantiated in the sub functions of the EVM class.
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on …

Changes how EVM is instantiated.

---

ironfish-cli/src/command.ts

We can use the `this.ctor` property instead of relying on escaping from Typescript's system now.
https://github.com/oclif/core/blob/main/src/command.ts#L187-L189
Manual - run some commands, utilize the common/built-in flags like datadir
N/A
N/A

CLI command: replace unneeded type hacking with built-in ctor property

---

ironfish-cli/src/commands/wallet/chainport/send.ts

This flag doesn't quite work as intended, but having missing flags can sometimes throw compilation errors in certain scenarios. It should throw errors in all scenarios, but that will be tackled soon.
N/A
N/A

Add missing offline flag

---

ironfish/src/rpc/routes/chain/__fixtures__/serializers.test.ts.fixture
ironfish/src/rpc/routes/chain/serializers.test.ts
ironfish/src/rpc/routes/chain/serializers.ts
ironfish/src/rpc/routes/chain/types.ts

This makes it so if you tell the RpcTransaction serializer not to include the serialized format, the notes will also not be included.
```
[X] Yes
```
```
[ ] Yes
```

Dont serialize rpc notes if not passed in

---

ironfish/src/wallet/__fixtures__/wallet.test.slow.ts.fixture
ironfish/src/wallet/scanner/walletScanner.ts

the WalletScanner uses a hash, 'scanFrom', for each account in its scanningAccounts list to check whether it should decrypt notes for the account. if scanFrom is null or equal to the previous block hash then notes are decrypted when connecting a block.
scanFrom is set to the account head when calling refreshScanningAccounts and set to null when connecting a block if scanFrom is equal to the previous hash.
however, when blocks are disconnected scanFrom is not currently changed. in the event of a reorg, decryption is skipped when connecting blocks from the fork if 'scanFrom' is still set to the hash of a disconnected block.
regenerates fixtures for test of this behavior and updates disconnectBlock to set scanFrom to null for all accounts where it is equal to the disconnected block hash. …

refreshes WalletScanner scanningAccounts on disconnect

---

ironfish/src/chainProcessor.test.ts
ironfish/src/chainProcessor.ts

This is experimenting with a fix for a problem i've seen. If the wallet gets ahead of the chain, the node will no longer start with this error.
```
Error: Chain processor head not found in chain: 0000000000012f4aca795fe01d3823b6d2b01a581fb7b4d41e78c09e68f477ba
at Function.isNotNull (/ironfish/src/assert.ts:26:13)
at ChainProcessor.update (/ironfish/src/chainProcessor.ts:76:12)
at <anonymous> (/ironfish/src/wallet/scanner/walletScanner.ts:132:26)
```
You can reproduce this by running
- `ironfish chain:rewind  665566 // use a sequence 1 behind the head`
- `ironfish start`
The problem is that the ChainProcessor crashes if it cannot find the head in the chain. After looking at all the usages of ChainProcessor, I think instead it should just return having not processed any blocks.
Does this …

ChainProcessor returns when head is not found

---

ironfish-cli/src/commands/chain/rewind.ts
ironfish/src/wallet/scanner/scanState.ts
ironfish/src/wallet/scanner/walletScanner.ts

Rewinding the wallet head was not showing progress correctly, and this also now adds a --no-wallet flag for testing.
```
[ ] Yes
```
```
[ ] Yes
```

Fixes chain:rewind to properly rewind the wallet head

---

ironfish-cli/src/commands/wallet/transaction/import.ts

This should make them not discoverable, but users can use them still.
```
[ ] Yes
```
```
[ ] Yes
```

Convert alises to hiddenAlias

---

ironfish-cli/src/command.ts
ironfish-cli/src/commands/browse.ts
ironfish-cli/src/commands/chain/benchmark.ts
ironfish-cli/src/commands/chain/blocks/info.ts
ironfish-cli/src/commands/chain/download.ts
ironfish-cli/src/commands/chain/genesisadd.ts
ironfish-cli/src/commands/chain/genesisblock.ts
ironfish-cli/src/commands/chain/power.ts
ironfish-cli/src/commands/chain/prune.ts
ironfish-cli/src/commands/chain/repair.ts
ironfish-cli/src/commands/chain/rewind.ts
ironfish-cli/src/commands/chain/status.ts
ironfish-cli/src/commands/config/edit.ts
ironfish-cli/src/commands/debug.ts
ironfish-cli/src/commands/migrations/index.ts
ironfish-cli/src/commands/migrations/revert.ts
ironfish-cli/src/commands/migrations/start.ts
ironfish-cli/src/commands/repl.ts
ironfish-cli/src/commands/reset.ts
ironfish-cli/src/commands/rpc/token.ts
ironfish-cli/src/commands/start.ts
ironfish-cli/src/commands/wallet/prune.ts
ironfish-cli/src/flags.ts

This removes LocalFlags entirely, as well as removing these 3 flags from RemoteFlags.
Only 2 or 3 non-hidden commands didn't utilize all 3 of these, and it was mostly the verbose flag, so there are scenarios where verbose will be listed as an argument but doesn't do anything, which I think is an okay trade-off. It's not ideal, but ensuring these flags are present seems very beneficial. 
This has the added benefit of throwing compile errors if a command tries to use a flag it hasn't defined. For some reason, if baseFlags is undefined/empty object, it seems to break the strict typing of flags. Closes IFL-2826
N/A
N/A

Add Config, DataDir and Verbose flags as base flags to all commands

---

ironfish-cli/src/commands/chain/blocks/info.ts

This shows the mining reward, which is derived from the first transaction's fee.
```
> ironfish chain:blocks:info 525600
Hash:                  00000000000035a4680ff1f59390a08ae686575a00a46243543dfbedaeee7d5a
Confirmed:             true
Fork:                  false
Sequence:              525600
Previous Block Hash:   00000000000108fbf92d8d8870b044cf1b39d0b8155596b58a8e3ac83286bbd7
Difficulty:            258980819860357
Timestamp:             4/17/2024 7:02:04 PM PDT
Graffiti:              pool.kryptex.com [1dce]
Mining Reward:         $IRON 19.00000000
Transaction Count:     1
``` …

Add mining reward to chain:blocks:info

---

ironfish-cli/src/commands/chain/blocks/info.ts
ironfish-cli/src/commands/config/get.ts
ironfish-cli/src/commands/config/index.ts
ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/ui/json.ts

We had a few commands that manually added JSON output. This change moves them to use the ui.json function instead. 
I modified ui.json to only attempt stringification of the input if it isn't already a string. The reason this was added is because the wallet:export/import flow would require a lot more substantial changes to work with pretty-printed JSON, and the wallet export RPC already exports the stringified JSON. I would prefer if this wasn't the case, but don't think the effort is worth tackling at this point.
I also slightly modified the output of some of the commands to be more valid JSON or clearer output.
`config:get` - added the config name so its a little easier to read
`config:get --json`
`config` - use the ui.card for normal display
Closes IFL-2820
N/A
N/A

CLI commands: use built-in JSON functionality instead of re-implementing it as needed

---

ironfish-cli/src/commands/chain/power.ts

This makes chain:power standard and return JSON when you pass in --json flag and adds the --color flag support as well.
```
> ironfish chain:power --json
{
"hashesPerSecond": 2662751897683.1084,
"blocks": 120,
"sequence": 665609
}
```
```
[ ] Yes
```
```
[ ] Yes
```

Have chain:power support --json flag

---

ironfish-cli/src/commands/chain/assets/info.ts
ironfish-cli/src/commands/chain/blocks/info.ts

```
[ ] Yes
```
```
[ ] Yes
```

Add json support for chain:assets:info

---

ironfish-cli/src/commands/chain/status.ts

```
> ironfish chain:status
{
"blockchain": {
"synced": false,
"head": {
"hash": "0000000000011bb1a02f5109657dd7b8ffba5129795f1565b05918a6a12b0c38",
"sequence": 665610
},
"headTimestamp": 1721778372512,
"newBlockSpeed": 0,
"dbSizeBytes": 15589950684
},
"difficulty": {
"sequence": 665610,
"hash": "0000000000011bb1a02f5109657dd7b8ffba5129795f1565b05918a6a12b0c38",
"difficulty": "181728058513479"
},
"power": {
"hashesPerSecond": 2662751897683.1084,
"blocks": 120,
"sequence": 665609
},
"node": {
"network": "Mainnet",
"networkId": 1
}
}
```
```
[ ] Yes
``` …

Add --json support for chain:status

---

ironfish-cli/src/commands/chain/transactions/info.ts

this outputs the transaction here. We need to add --serialization support to the RPC.
```
[ ] Yes
```
```
[ ] Yes
```

Add --json support to chain:transactions:info cmd

---

ironfish/src/rpc/routes/chain/getTransaction.ts

It already returned RpcTransaction with extra fields, so we can just use the serializer and attach these extra fields.
```
[ ] Yes
```
```
[ ] Yes
```

Make chain:getTransaction use rpcSerializer

---

ironfish-cli/src/commands/chain/status.ts
ironfish-cli/src/flags.ts

This allows us to over-ride the built in OCLIF JSON flag group which exists at https://github.com/oclif/core/blob/213e9203fd7f0f5aaffdcc9eb28d2828f7679373/src/util/aggregate-flags.ts#L4C1-L7C3
`ironfish chain:status --help`
```
[ ] Yes
```
```
[ ] Yes
```

Move JSON flags into flags module

---

ironfish-cli/src/flags.ts

This should make all the RPC flags show up in their own section in --help now.
```
[ ] Yes
```
```
[ ] Yes
```

Add custom help category for RPC flags

---

ironfish-cli/src/commands/chain/blocks/info.ts
ironfish-cli/src/commands/chain/power.ts
ironfish-cli/src/commands/chain/status.ts

These commands were all missing RemoteFlags.
```
[ ] Yes
```
```
[ ] Yes
```

Added missing RemoteFlags on commands

---

ironfish-cli/src/commands/chain/assets/info.ts
ironfish-cli/src/commands/chain/blocks/info.ts
ironfish-cli/src/commands/chain/power.ts
ironfish-cli/src/commands/chain/transactions/info.ts
ironfish-cli/src/commands/config/get.ts
ironfish-cli/src/commands/config/index.ts
ironfish-cli/src/commands/wallet/export.ts

This will automatically pull in color and the right json flag with the correct help groups.
```
[ ] Yes
```
```
[ ] Yes
```

Upgrade commands to use JsonFlags

---

ironfish-cli/src/commands/start.ts

Because it defaulted to true instead of undefined.
```
ironfish config:set enableWallet false
ironfish start
// See that the wallet is still started before the change and not after
ironfish status
```
```
[ ] Yes
```
```
[ ] Yes
```

Fix start command wallet flag over-riding config

---

ironfish-cli/src/commands/chain/assets/info.ts

It will show an example to see the native currency information
```
> ironfish chain:assets:info --help
show asset information
USAGE
$ ironfish chain:assets:info ID [--json] [-v] [--config <value>] [-d <value>] [--rpc.tcp] [--rpc.ipc] [--rpc.tcp.host <value>] [--rpc.tcp.port <value>] [--rpc.http.host <value>] [--rpc.http.port <value>] [--rpc.http] [--rpc.tcp.tls] [--rpc.auth <value>] [--color]
ARGUMENTS
ID  The identifier of the asset
GLOBAL FLAGS
-d, --datadir=<value>  [default: ~/.ironfish] The path to the data dir
-v, --verbose          Set logging level to verbose
--config=<value>   [default: config.json] The name of the config file to use
OUTPUT FLAGS
--[no-]color  Should colorize the output
--json        format output as json
DESCRIPTION
show asset information
EXAMPLES
get the native …
```

Add an asset info example

---

ironfish-cli/src/commands/chain/broadcast.ts
ironfish-cli/src/commands/chain/export.ts
ironfish-cli/src/commands/chain/power.ts
ironfish-cli/src/commands/chain/transactions/info.ts

This creates a standard in laying our command code.
```
[ ] Yes
```
```
[ ] Yes
```

Reorder chain commands so args are before flags

---

ironfish/src/evm/evm.test.ts
ironfish/src/evm/evm.ts
ironfish/src/evm/stateManager.ts

reading the confirmed balance (for any confirmation range) for an account will require reading from the state trie at a past state root
adds a function, withStateRoot, to make a copy of the stateManager, set the state root, and return the copy to the caller.
defines getAccount and getBalance on the IronfishEvm using withStateRoot
some RPC methods, like eth_getAccount and eth_getBalance, will require this functionality
```
[ ] Yes
```
```
[ ] Yes …
```

adds StateManager method for reading at past state roots

---

ironfish-cli/src/commands/status.ts

```
> ironfish status --json
{
"peerNetwork": {
"peers": 8,
"isReady": true,
"inboundTraffic": 3.827089272106467,
"outboundTraffic": 77.51846118445366,
"publicIdentity": "2BRyL2XoCgk0SjCMg8DkOK/JefkUR+5s8YsClp0OM08="
},
"blockchain": {
"synced": true,
"head": {
"hash": "00000186c16ce24d57584e54453ea2f2f3fded2f70500014e2a9beecf661f357",
"sequence": 625446
},
"headTimestamp": 1723051770752,
"newBlockSpeed": 0,
"dbSizeBytes": 967838004
},
"node": {
"status": "started",
"version": "2.5.0",
"git": "src",
"nodeName": "",
"networkId": 0
},
"cpu": {
"cores": 10,
"percentRollingAvg": 9.2734960340776,
"percentCurrent": 0.9176352705410822
},
"memory": {
"heapMax": 4292074584,
"heapTotal": 54018048,
"heapUsed": 50897496,
"rss": 609730560,
"memFree": 196640768,
"memTotal": 34359738368
}, …
```

status command returns json

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/xchacha20poly1305.rs
ironfish-rust/src/xchacha20poly1305.rs

* Updates `salt` on `EncryptOutput` to be `Vec<u8>`
* Adds serialization for `EncryptOutput`
* Adds napi wrapper function for `encrypt`
Unit test for serialization
```
[ ] Yes
```
```
[ ] Yes
```

feat(rust,rust-nodejs): Add napi `encrypt` function for xchacha20poly1305

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/index.js
ironfish-rust-nodejs/src/xchacha20poly1305.rs
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/account/__fixtures__/encryptedAccount.test.ts.fixture
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/account/encryptedAccount.test.ts
ironfish/src/wallet/account/encryptedAccount.ts
ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/wallet/walletdb/accountValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

* Update Napi `encrypt` / `decrypt` to accept and return JS buffers
* Remove hex conversion from Napi functions and pass raw bytes
* Refactor `AccountValue` to `DecryptedAccountValue`
* Adds `encrypted` property to be used as a type guard in subsequent PRs
* Introduce `EncryptedAccountValue` to represent encrypted accounts in the database
Unit test
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish,rust-nodejs): Add EncryptedAccount class

---

ironfish-cli/src/commands/evm/sendTransaction.ts
ironfish-cli/src/commands/evm/shield-custom-asset.ts
ironfish-cli/src/commands/evm/shield-iron.ts
ironfish-cli/src/commands/test-evm.ts
ironfish/src/blockchain/blockchain.ts
ironfish/src/consensus/verifier.evm.test.slow.ts
ironfish/src/consensus/verifier.ts
ironfish/src/evm/__fixtures__/evm.test.ts.fixture
ironfish/src/evm/evm.test.ts
ironfish/src/evm/evm.ts
ironfish/src/mining/manager.ts

moves evm tx execution out of verifyEvm
consolidates IronfishEvm methods runTx and verifyTx into a single method that returns a result and events decoded from logs or an error if exeuction fails
removes redundant simulateTx method
refactors verifyEvm to take an EvmResult instead of executing the transaction itself. allows us to use evm transaction execution results outside of verification, e.g., for summing miner fees from gas
adds runDesc method for convenience to wrap conversion from EvmDescription to evm transaction
manual testing to see miners fee includes gas:
- apply attached diff: [miner_fee_gas_test.diff.txt](https://github.com/user-attachments/files/16532152/miner_fee_gas_test.diff.txt)
- start node with `--networkId=2` and `--forceMining`
- start miner
- use …

pays gas fees to miners in minersFee transactions

---

ironfish-cli/src/commands/config/edit.ts
ironfish-cli/src/commands/config/get.ts
ironfish-cli/src/commands/config/set.ts
ironfish-cli/src/commands/config/unset.ts

```
[ ] Yes
```
```
[ ] Yes
```

update config descriptions to match our new standard

---

ironfish-cli/src/commands/evm/sendTransaction.ts
ironfish/src/mining/__fixtures__/manager.test.slow.ts.fixture
ironfish/src/mining/manager.test.slow.ts
ironfish/src/network/messages/getBlockHeaders.ts
ironfish/src/network/messages/newCompactBlock.test.ts
ironfish/src/network/utils/serializers.ts

supports gossip for blocks that include stateCommitment in header
updates `evm:sendTransaction` to use the `chain/broadcastTransaction` RPC for testing broadcasting transactions
manually tested by running two nodes, having one mining, and sending evm transactions from the non-mining node
```
[ ] Yes
```
```
[ ] Yes
```

updates peer network header serialization for evm state

---

ironfish/src/consensus/verifier.ts
ironfish/src/evm/__fixtures__/evm.test.ts.fixture
ironfish/src/evm/evm.test.ts
ironfish/src/evm/evm.ts
ironfish/src/mining/manager.ts

the wrapper pattern of withCopy was proving cumbersome to use when verifying evm transactions in blocks because we needed to wrap verification of all transactions in the block
making a copy of the IronfishEvm instance is more straightforward and still has the benefit of not committing changes to the db if we set a checkpoint on the stateManager
removes the optional vm argument to runTx and runDesc since we can now use these on the copy of the IronfishEvm instead of using a copy of only the vm
```
[ ] Yes
``` …

replaces withCopy with copy of IronfishEvm

---

Cargo.lock
ironfish-rust-nodejs/Cargo.toml
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/Cargo.toml
ironfish-rust/src/note.rs
ironfish-rust/src/transaction/evm.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish/src/consensus/verifier.evm.test.slow.ts
ironfish/src/primitives/evmDescription.ts
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/primitives/transaction.test.ts
ironfish/src/primitives/transaction.ts
rust-toolchain.toml
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

signs evm transaction descriptions at signing time for other transaction descriptions
defines UnsignedEvmDescription to exclude signature fields (v, r, s) from EvmDescription
replaces EvmDescription with UnsignedEvmDescription on ProposedTransaction and UnsignedTransaction
uses reth_primitives crate to sign transactions in rust
upgrades napi and other dependencies as required to add reth_primitives dependency
- adds new tests in ironfish-rust to test signing
- modifies verifier.evm.test.slow.ts to accommodate new signing logic
```
[ ] Yes
``` …

moves evm transaction signing into rust

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish-rust/src/transaction/evm.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/tests.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish/src/consensus/__fixtures__/verifier.evm.test.slow.ts.fixture
ironfish/src/consensus/verifier.evm.test.slow.ts
ironfish/src/primitives/evmDescription.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/primitives/transaction.ts

supports use cases like the eth_sendRawTransaction RPC where we might have an evm transaction that the user has already signed that we then wrap with an Iron Fish transaction without access to the user's keys
this could also support a shielding RPC where uses submit signed evm transactions that shield assets that are then wrapped in Iron Fish transactions
```
[ ] Yes
```
```
[ ] Yes
```

allows pre-signed evm descriptions in Iron Fish transactions

---

ironfish/src/wallet/account/encryptedAccount.ts
ironfish/src/wallet/walletdb/accountValue.test.ts
ironfish/src/wallet/walletdb/accountValue.ts
ironfish/src/wallet/walletdb/walletdb.ts

* Expands AccountValueEncoding to support both encrypted and decrypted accounts
* Only return decrypted accounts from the walletdb generator (will be fixed when the wallet can store encrypted accounts)
Unit test for serialization round trip
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add serialization for encrypted accounts

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/eth/__fixtures__/sendRawTransaction.test.ts.fixture
ironfish/src/rpc/routes/eth/index.ts
ironfish/src/rpc/routes/eth/sendRawTransaction.test.ts
ironfish/src/rpc/routes/eth/sendRawTransaction.ts

Send Raw Transaction that will take standard eth transactions and submit them to the network.
```
[ ] Yes
```
```
[ ] Yes
```

eth_sendRawTransaction RPC

---

ironfish/src/wallet/account/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account/account.test.ts
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/account/encryptedAccount.test.ts
ironfish/src/wallet/exporter/encoders/bech32.ts
ironfish/src/wallet/walletdb/accountValue.ts

* Add `encrypt` method for `Account`
* Remove `KEY_LENGTH` duplicate constant (mutual imports were messing this up)
* Refactor interface to type to fix test 
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add `encrypt` method for account

---

ironfish-cli/src/commands/mempool/status.ts
ironfish-cli/src/commands/mempool/transactions.ts

`mempool --help`
`mempool:status --json`
```
{
"size": 0,
"sizeBytes": 0,
"maxSizeBytes": 60000000,
"headSequence": 0,
"evictions": 0,
"recentlyEvictedCache": {
"size": 0,
"maxSize": 60000,
"saturation": 0
}
}
```
```
[ ] Yes
```
```
[ ] Yes
```

update mempool descriptions and add json support to status

---

ironfish-cli/src/commands/miners/pools/start.ts
ironfish-cli/src/commands/miners/pools/status.ts
ironfish-cli/src/commands/miners/start.ts
ironfish/src/mining/stratum/clients/client.ts
ironfish/src/mining/stratum/clients/tcpClient.ts

Required some changes to the stratum client to properly end. Before this PR, the 'close' immediately kicked off the reconnect logic, so there was no actual way to close a client. This adds the ability to manually close a stratum client connection.
N/A
N/A

update miners command descriptions, add json to pool status

---

ironfish-cli/src/commands/wallet/index.ts

This adds optional new table output to the wallet command
```
[ ] Yes
```
```
[ ] Yes
```

Add table output to wallet command

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

* Adds an `encrypt` method to the `Wallet` which grabs the global transaction lock, encrypts accounts with a user-provided passphrase, and then saves the encrypted blobs to disk.
* Updates `Wallet.load` to clear out the cached accounts and encrypted accounts so they can be freshly reloaded from the database
Unit test
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add encrypt method to wallet

---

ironfish-cli/src/commands/wallet/use.ts
ironfish/src/rpc/routes/wallet/useAccount.ts

You can now use `wallet:use --unset` to unset the default account
```
[ ] Yes
```
```
[ ] Yes
```

Add the ability to unset default account in CLI

---

.github/workflows/deploy-node-docker-image.yml

this will allow us to deploy a docker image to AWS named for the 'evm' branch or any branch that includes this change
```
[ ] Yes
```
```
[ ] Yes
```

allows deploying branch-named docker images to AWS

---

ironfish/src/rpc/routes/wallet/getAccounts.ts

Previously, the RPC wasn't receiving this parameter properly due to it being left out of the yup schema. Add it to the schema so that the flag is properly passed through.
```
[ ] Yes
```
```
[ ] Yes
```

fix `wallet:which --displayName` output

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

* Adds `accountsEncrypted` to the walletdb which returns whether all accounts are encrypted or not. It includes an invariant check to ensure the store does not get in a corrupted state where some accounts may be encrypted and some may not.
* Adds `lock` to the `Wallet`. If the wallet accounts are decrypted, no action is necessary since everything is in plaintext already. If the wallet accounts are encrypted, clear any decrypted keys from memory and set the wallet locked state.
* Set the wallet locked state every time a database load is called (i.e. from startup, post encryption, post decryption). The wallet will automatically lock if the accounts are encrypted.
Unit tests …

feat(ironfish): Add lock to wallet

---

.github/workflows/deploy-node-docker-image.yml

removes erroneous 'event' qualifier for ref_type
```
[ ] Yes
```
```
[ ] Yes
```

fixes deployment of branch docker images to AWS

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/accountValue.ts

* Adds an unlock method to the wallet which:
* Does nothing if the wallet is decrypted
* Decrypts all encrypted accounts in memory
* Sets `locked` to false and starts a timeout to automatically lock the wallet
* If the provided `timeout` is `-1`, leave the wallet unlocked indefinitely
* Use a default timeout of 5 minutes if no argument is passed
* Clears any lock timeout when `lock` is called
* Clears the lock timeout when stopping the wallet 
Unit tests
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it with `breaking-change-rpc` …

feat(ironfish): Add unlock to wallet

---

ironfish-cli/src/commands/evm/shield.ts
ironfish/src/wallet/wallet.ts

Requires user to input ethereum spending key during shielding, alternative is that we store as account, pass account name, retrieve account in RPC and then sign in RPC and submit transaction.
```
[ ] Yes
```
```
[ ] Yes
```

Shield cli

---

ironfish-cli/src/commands/evm/unshield.ts

Implements a new CLI command to unshield private assets to public tokens on the EVM chain. Features include:
- Support for both IRON and custom ERC20 tokens
- Uses the Gold Token as an example interface for ERC20 contracts
- User prompts for missing required information
- Validation of Ethereum addresses and node sync status
- Automatic use of default account if not specified
```
[ ] Yes
```
```
[ ] Yes
```

Add EVM unshield command

---

.github/workflows/deploy-node-docker-image.yml

adds a workflow input for `AWS:{BRANCH}` and adds a deploy step for deploying the branch-named image to our AWS ECR repository
```
[ ] Yes
```
```
[ ] Yes
```

supports deploying branch-named Docker images to AWS

---

ironfish-cli/src/commands/evm/balance.ts
ironfish-cli/src/commands/evm/sendTransaction.ts

uses the 'eth/getAccount' RPC to fetch account state at the current chain head and the latest confirmed block
displays unconfirmed and confirmed balances
only supports the native asset for now
```
[ ] Yes
```
```
[ ] Yes
```

adds cli command for unshielded evm balances

---

ironfish-cli/src/commands/evm/unshield.ts

the function input in the global contract is an ethereum address, not a byte array
sent unshield transaction on evmnet after making changes
```
[ ] Yes
```
```
[ ] Yes
```

encodes to address as string in unshield

---

ironfish/src/evm/evm.ts

Call (ie get balance) rather than just runTx
```
[ ] Yes
```
```
[ ] Yes
```

adds call function for calling evm instead of running tx

---

ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

Making the WalletDB interface a bit stricter to read all account values from the database and call the appropriate function instead of using cached values in the wallet. Also accepting an array of accounts seems like a foot-gun in case anyone accidentally doesn't pass in all of the accounts.
These cached accounts are reloaded after encrypt/decrypt so no updates are necessary there.
Refactored unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Remove cached accounts when encrypting/decrypting

---

ironfish/src/rpc/routes/node/getStatus.test.ts
ironfish/src/rpc/routes/node/getStatus.ts

Return if the wallet is locked in `node/getStatus`
Unit test
```
[x] Yes
```
https://github.com/iron-fish/website/pull/719
```
[ ] Yes
```

feat(ironfish): Return if the wallet is locked in getStatus

---

ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts

Also remove things that are not visible in `wallet:status`
```
> ironfish wallet:balance --all
Account:       foobar
Balance:       $IRON✓ 0.00000000
Confirmed:     $IRON✓ 0.00000000
Unconfirmed:   $IRON✓ 0.00000000
Pending:       $IRON✓ 0.00000000
```
```
> ironfish wallet:balances --all
Account: foobar
Asset  Balance    Confirmed  Unconfirmed Pending    Notes Asset Id
────── ────────── ────────── ─────────── ────────── ───── ────────────────────────────────────────────────────────────────
$IRON✓ 0.00000000 0.00000000 0.00000000  0.00000000 0     51f33a2f14f92735e562dc658a5639279ddca3d5079a6d1242b2a588a9cbf44c
```
related …

Make balance output consistent

---

ironfish-cli/src/ui/prompt.ts

The generics were not correct on this use of inquirer, and it was coercing it to something that didnt have value.
```
[ ] Yes
```
```
[ ] Yes
```

Fix account prompt returning undefined

---

ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/balance.ts
ironfish-cli/src/commands/wallet/balances.ts
ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/export.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/notes/index.ts
ironfish-cli/src/commands/wallet/reset.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/commands/wallet/transactions/info.ts
ironfish-cli/src/ui/prompts.ts
ironfish-cli/src/utils/account.ts
ironfish-cli/src/utils/index.ts

- This deprecates arg flags in account context commands
- Prompts users for an account top use if no account was provided and there is no default account
```
[ ] Yes
```
```
[ ] Yes
```

Add new useAccount helper an upgrade commands

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/multisig/account/participants.ts
ironfish-cli/src/commands/wallet/multisig/commitment/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/aggregate.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/commands/wallet/send.ts

And rename or delete command specific competing flags. These command flags had chars that were not consistent across commands like "confirmations". It's best not to have command specific single letter char shortcuts. User's should be explicit when sending transactions.
```
[ ] Yes
```
```
[ ] Yes
```

Standardize account flags to char 'a'

---

ironfish-cli/src/commands/wallet/delete.ts
ironfish-cli/src/ui/prompt.ts

This makes the user type in the account name they are trying to delete
```
[ ] Yes
```
```
[ ] Yes
```

Change wallet:delete to use new confirmInput

---

ironfish/src/evm/evm.ts
ironfish/src/evm/stateManager.ts

Likely to instantiate other state managers (like receipt manager) here.
```
[ ] Yes
```
```
[ ] Yes
```

Move EVM state manager instantiation out of EVM class

---

ironfish-rust/src/transaction/tests.rs

Single test that encapsulates DKG and signing with those shards in a single test.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

dkg signing test rust

---

ironfish-cli/src/commands/wallet/decrypt.ts

Add CLI command to encrypt the wallet
```fish
❯ f wallet:decrypt -d ~/.ironfish-1
yarn run v1.22.18
$ yarn build && yarn start:js wallet:decrypt -d /home/rohan/.ironfish-1
$ tsc -b
? Enter a passphrase to decrypt the wallet: invalid
Wallet decryption failed
❯ f wallet:decrypt -d ~/.ironfish-1
yarn run v1.22.18
$ yarn build && yarn start:js wallet:decrypt -d /home/rohan/.ironfish-1
$ tsc -b
? Enter a passphrase to decrypt the wallet: foobar
Decrypted the wallet
Done in 2.58s.
```
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it …

feat(cli): Add `wallet:decrypt`

---

ironfish-cli/src/commands/wallet/unlock.ts

Add command to unlock the wallet
```sh
❯ f wallet:unlock -d ~/.ironfish-1 
yarn run v1.22.18
$ yarn build && yarn start:js wallet:unlock -d /home/rohan/.ironfish-1
$ tsc -b
? Enter a passphrase to unlock the wallet: passwer
Wallet unlock failed
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
❯ f wallet:unlock -d ~/.ironfish-1
yarn run v1.22.18
$ yarn build && yarn start:js wallet:unlock -d /home/rohan/.ironfish-1
$ tsc -b
? Enter a passphrase to unlock the wallet: password
Unlocked the wallet for 300000ms
Done in 4.77s.
❯ f wallet:unlock -d ~/.ironfish-1 --timeout -1
yarn run v1.22.18
$ yarn build && yarn start:js wallet:unlock -d /home/rohan/.ironfish-1 --timeout -1
$ tsc -b
? Enter a passphrase to unlock the …
```

feat(cli): Add `wallet:unlock`

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/eth/__fixtures__/ethRouter.test.ts.fixture
ironfish/src/rpc/routes/eth/ethRouter.test.ts
ironfish/src/rpc/routes/eth/ethRouter.ts
ironfish/src/rpc/routes/eth/getAccount.ts
ironfish/src/rpc/routes/eth/index.ts
ironfish/src/rpc/routes/eth/sendRawTransaction.ts
ironfish/src/rpc/routes/eth/sendTransaction.ts

For registering RPCs for integration with external systems, but maintain our own api specification, I created this wrapper. It will make the endpoints registered available via the standardized JSON rpc system of eth nodes, but also with our typesafe client.
For example, an endpoint can hit:
`rpc/ethRouter` with request body:
```
{
jsonrpc: '2.0'
id: 1
method: 'eth_sendRawTransaction`
params: [{transaction: '0x....']
}
```
Which is the same as using our client at
`client.eth.sendRawTransaction({transaction: '0x....'})`
or
`rpc/eth/sendTransaction`
Test Passes.
```
[ ] Yes
```
Is this …

eth rpc wrapper

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/blockchain/schema.ts

Will test with RPC addition of `eth_getTransactionByHash`
```
[ ] Yes
```
```
[ ] Yes
```

add eth transaction hash to hash store, for eth_getTransactionByHash

---

ironfish-cli/src/utils/account.ts
ironfish/src/rpc/routes/wallet/utils.ts

Check the wallet is unlocked before returning account(s)
```sh
❯ f wallet:balances -d ~/.ironfish-testnet
yarn run v1.22.21
Error: Wallet is locked. Unlock the wallet to fetch accounts
at useAccount (/Users/rohan/git/ironfish/ironfish-cli/src/utils/account.ts:19:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at BalancesCommand.start (/Users/rohan/git/ironfish/ironfish-cli/src/commands/wallet/balances.ts:36:21)
at BalancesCommand.run (/Users/rohan/git/ironfish/ironfish-cli/src/command.ts:92:14)
at async BalancesCommand._run (/Users/rohan/git/ironfish/node_modules/@oclif/core/lib/command.js:301:22)
at async Config.runCommand (/Users/rohan/git/ironfish/node_modules/@oclif/core/lib/config/config.js:424:25)
at async run …
```

feat(cli,ironfish): Check if the wallet is locked before fetching accounts

---

ironfish/src/wallet/wallet.ts

Small UX improvement to notify the user when the wallet automatically locks so they know to unlock it.
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Notify via logger when the wallet locks

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/eth/__fixtures__/getBalance.test.ts.fixture
ironfish/src/rpc/routes/eth/getBalance.test.ts
ironfish/src/rpc/routes/eth/getBalance.ts
ironfish/src/rpc/routes/eth/index.ts

`eth` RPC can accept other statuses, but not sure they are well defined in our chain:
https://www.quicknode.com/docs/ethereum/eth_getBalance
`The block number in hexadecimal format or the string latest, earliest, pending, safe or finalized (safe and finalized tags are only supported on Ethereum, Gnosis, Arbitrum, Arbitrum Nova and Avalanche C-chain), see the default block parameter description in the official Ethereum documentation`
tests pass
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it with `breaking-change-rpc` or …

eth_getBalance RPC

---

ironfish/src/blockchain/blockchain.ts
ironfish/src/blockchain/database/__fixtures__/evmReceiptValue.test.ts.fixture
ironfish/src/blockchain/database/blockchaindb.ts
ironfish/src/blockchain/database/evmReceiptValue.test.ts
ironfish/src/blockchain/database/evmReceiptValue.ts
ironfish/src/blockchain/schema.ts

stores most of the same fields as geth, but excludes fields that we can obtain from the transaction or block and excludes blob-related fields because we haven't addressed blobs
defines a separate interface for the values stored in the db store since the RunTxResult has many nested fields
updates the store in tandem with the ethTransactionHashToTransactionHash store
TODO: we don't accurately track cumulativeGasUsed right yet
```
[ ] Yes
```
```
[ …
```

adds db store for evm receipts

---

ironfish-cli/src/commands/wallet/decrypt.ts
ironfish-cli/src/commands/wallet/encrypt.ts
ironfish-cli/src/commands/wallet/unlock.ts
ironfish-cli/src/ui/prompt.ts

Hide passphrases when using encryption CLI commands
https://github.com/user-attachments/assets/24e758ab-aaa9-46be-96cc-25ccac45b341
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Hide passphrases in encryption commands

---

ironfish-cli/src/commands/wallet/index.ts
ironfish-cli/src/commands/wallet/which.ts

Notify the user they have a locked wallet instead of no accounts
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Return locked warning in wallet:accounts and wallet:which

---

ironfish/src/rpc/clients/client.ts
ironfish/src/rpc/routes/eth/__fixtures__/accounts.test.ts.fixture
ironfish/src/rpc/routes/eth/accounts.test.ts
ironfish/src/rpc/routes/eth/accounts.ts
ironfish/src/rpc/routes/eth/blockNumber.ts
ironfish/src/rpc/routes/eth/estimateGas.ts
ironfish/src/rpc/routes/eth/index.ts

https://www.quicknode.com/docs/ethereum/eth_getTransactionReceipt
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

eth_accounts

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/__fixtures__/walletdb.test.ts.fixture
ironfish/src/wallet/walletdb/walletdb.test.ts
ironfish/src/wallet/walletdb/walletdb.ts

When doing writes to the database, we need to ensure new values are encrypted if the existing accounts are encrypted. When importing an account, require a passphrase to encrypt the new account value.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Add passphrase to import account for encrypted dbs

---

ironfish/src/rpc/adapters/httpAdapter.ts
ironfish/src/rpc/request.ts

json rpc responses include only a single object rather than the nested objects in our typical responses
checks or the 'jsonrpc' tag in http rpc requests and returns the response data as a flat object for json rpc requests
```
hughy@Hughs-MacBook-Pro ~ % curl http://localhost:8021/eth/ethRouter \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","id":1,"result":{"number":"0x52"}}%                                                                                                            hughy@Hughs-MacBook-Pro ~ % curl https://docs-demo.quiknode.pro/ \    
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"eth_blockNumber","params":[],"id":1,"jsonrpc":"2.0"}' …
```

returns unwrapped data from http adapter for json rpc requests

---

ironfish-cli/src/commands/start.ts

Notify the user when the wallet is locked an unlock is needed
Ran the command
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Log message in start when the wallet is locked

---

ironfish-cli/src/commands/chain/broadcast.ts
ironfish/src/rpc/clients/client.ts

We call `.waitForEnd()` on `broadcastTransaction` and `isValidPublicAddress`, but we don't use the proper RpcResponseEnded type, so users of the client function have to check for null anyway. Also improved the handling of error responses from the `broadcastTransaction` RPC.
```
[ ] Yes
```
```
[ ] Yes
```

Improve RPC client types for broadcastTransaction and isValidPublicAddress

---

ironfish/src/rpc/routes/wallet/resetAccount.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts
ironfish/src/wallet/walletdb/walletdb.ts

When resetting an account, we need a passphrase if the wallet is encrypted to write the encrypted account to disk
Unit tests
```
[x] Yes
```
```
[ ] Yes
```

feat(ironfish): Add passphrase to reset account methods

---

ironfish/src/rpc/routes/wallet/create.ts
ironfish/src/rpc/routes/wallet/createAccount.ts
ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

We need a passphrase when creating a new account and saving it to disk when the wallet is encrypted
Unit tests
```
[x] Yes
```
```
[ ] Yes
```

feat(ironfish): Require passphrase when creating encrypted account

---

ironfish/src/rpc/routes/wallet/rename.ts
ironfish/src/rpc/routes/wallet/renameAccount.ts
ironfish/src/wallet/account/__fixtures__/account.test.ts.fixture
ironfish/src/wallet/account/account.test.ts
ironfish/src/wallet/account/account.ts

Check a passphrase is provided if renaming an account when the wallet is encrypted.
Unit tests
```
[x] Yes
```
```
[ ] Yes
```

feat(ironfish): Require passphrase when renaming encrypted accounts

---

Cargo.lock
ironfish-rust/Cargo.toml
ironfish-rust/src/errors.rs
ironfish-rust/src/xchacha20poly1305.rs
supply-chain/config.toml

Create a struct for the key that can encapsulate the encryption/decryption. This also includes methods to derive a new key or re-derive a key from a master key.
Leaving the original encrypt/decrypt functions for now to keep the PR small.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(rust): Add struct for XChaCha20Poly1305 key

---

ironfish/src/wallet/interfaces/multisigKeys.ts
ironfish/src/wallet/walletdb/multiSigKeys.test.ts
ironfish/src/wallet/walletdb/multisigKeys.ts

a multisig account generated using a Ledger device will have a access to the participant identity, but not the secret or keyPackage
uses a separate interface for MultisigHardwareSigner to cover this case and expands the MultisigKeys type to cover this interface
the distinct interface allows us to store multisig keys for the Ledger case without a database migration for existing multisig keys
```
[ ] Yes
```
```
[ ] Yes
```

defines MultisigHardwareSigner for Ledger multisig keys

---

ironfish-rust/src/frost_utils/account_keys.rs

This diagram is written in a codeblock so it's displayed in monospace, which was erroneously also parsing it as a doctest when running `cargo test`. Add the `ignore` keyword to avoid it being parsed as a doctest.
`cargo test`
```
[ ] Yes
```
```
[ ] Yes
```

dont parse this diagram as a doctest

---

ironfish/src/wallet/masterKey.test.ts
ironfish/src/wallet/masterKey.ts
ironfish/src/wallet/walletdb/masterKeyValue.test.ts
ironfish/src/wallet/walletdb/masterKeyValue.ts

Encapsulate an XChaCha20Poly1305 master key to be used within the wallet. This will be saved in the database and eventually used to derive the parameters to encrypt/decrypt accounts with unique salts and nonces.
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Create master key

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish/src/multisig.test.slow.ts

adds typescript version of test_dkg_signing example
adds multisig.test.slow.ts that replicates the logic of test_dkg_signing from ironfish-rust
- adds method to retrieve frost signing package from deserialized signing package
- adds signingPackageFromRaw method - allows construction of signing package from identities and raw commitments (from frost, not ironfish)
- adds method to NativeSigningCommitment to get raw_commitments
- defines NativeSignatureShare to support deserializing ironfish SignatureShares and accessing the underlying identity and frost signature share
- adds from_frost factor method to reconstruct SignatureShare from parts
Reference](https://ironfish.network/docs/onboarding/rpc/chain))? If yes, …

adds napi methods to support Ledger multisig

---

Cargo.lock
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish-rust-nodejs/src/structs/transaction.rs
ironfish/src/multisig.test.slow.ts

updates ironfish-frost dependency to latest commit
adds napi binding for SigningCommitment::from_raw to support constructing a signing commitment from its raw parts (the signer identity, the raw commitments, and the transaction hash and list of signers for computing a checksum)
removes signing_package_from_raw in favor of constructing SingingCommitments and using existing signing_package method
```
[ ] Yes
```
```
[ ] Yes
```

allows constructing NativeSigningCommitment from raw

---

ironfish-cli/src/commands/wallet/multisig/participants/index.ts
ironfish/src/rpc/routes/wallet/multisig/getIdentities.ts

This is going to be a useful feature when we start to integrate ledger because all identities from ledger will not export their secret.
Updates both the CLI and related RPC
```
[ ] Yes
```
```
[ ] Yes
```

Displays whether a participant has a secret or not

---

ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish/src/multisig.test.slow.ts

allows us to construct a PublicKeyPackage from the raw parts: the frost public key package, the list of signer identities, and the minimum number of signers
following the round3_min changes to ironfish-frost the Ledger app will produce a raw frost public key package at the end of DKG round3, so we will need to construct the ironfish-frost PublicKeyPackage from its parts
```
[ ] Yes
```
```
[ ] Yes
```

defines from_frost factory method on NativePublicKeyPackage

---

ironfish/src/rpc/routes/wallet/multisig/getIdentity.ts

uses walletDb.getMultisigIdentityByName instead of looking up secret by name
since some identities may not have secrets (i.e., identities created using Ledger) these identities won't be found when looking identities up using walletDb.getMultisigSecretByName
```
[ ] Yes
```
```
[ ] Yes
```

fixes wallet/multisig/getIdentity for undefined secrets

---

ironfish/src/rpc/routes/wallet/multisig/importParticipant.test.ts
ironfish/src/rpc/routes/wallet/multisig/importParticipant.ts

throws RPC errors with recognizable error codes
allows CLI to handle RPC errors more easily
```
[ ] Yes
```
```
[ ] Yes
```

fixes errors in wallet/multisig/importParticipant

---

ironfish/src/rpc/clients/memoryClient.ts
ironfish/src/rpc/routes/node/stopNode.ts
ironfish/src/wallet/masterKey.ts
ironfish/src/wallet/wallet.ts

When unlocking a wallet without a running node (i.e. using the rpc memory client), the process will hang until the timeout to re-lock the wallet is called (by default, this is 24h). There are several ways to address this issue:
* Don't enqueue a timeout if unlocking via the UI utility in the CLI. This is not ideal, because if you have a running node, you may just leave it unlocked indefinitely. We can add further logic to prevent this probably.
* Remove the utility to unlock the wallet, but that ruins UX a bit.
This PR does several things:
* Implement the `close` method for the memory client. This did nothing before, but now shuts down the node connection
* Destroy the master key and clear any timeouts before checking if the wallet is started. 
Run CLI commands
Does this change require …

fix(ironfish): Fix unlock hanging in memory client CLI

---

ironfish/src/wallet/wallet.ts

If the wallet is locked, we can skip all the scanning logic. The wallet scanner already functions without this, but the conditional improves the logging and makes it clear when the scanner is actually scanning.
Running CLI commands and toggled locked status
```
[ ] Yes
```
```
[ ] Yes
```

fix(ironfish): Guard event loop when the wallet is locked

---

ironfish/src/rpc/routes/wallet/setScanning.ts
ironfish/src/wallet/account/account.ts
ironfish/src/wallet/wallet.ts

Check if the wallet is encrypted before toggling scanning
Run CLI commands for scanning
```
[ ] Yes
```
```
[ ] Yes
```

feat(ironfish): Write encrypted accounts when toggling scanning

---

ironfish-cli/src/commands/wallet/create.ts
ironfish/src/rpc/routes/wallet/decrypt.test.ts
ironfish/src/rpc/routes/wallet/unlock.test.ts
ironfish/src/wallet/errors.ts

Prompt for the passphrase before the name when creating an account
Run the command
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Check the wallet is unlocked before prompting for name

---

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/utils/ledger.ts
ironfish/src/wallet/index.ts

implements dkgRound3 method on Ledger util class
implements dkgRetrieveKeys on Ledger util class to retrieve all shared multisig keys
implements dkgGetPublicPackage on Ledger util class to retrieve public key package
updates round3 command to run dkg round3, retrieve keys, get public key package, and import account with ledger flag
- manual testing with `wallet:multisig:dkg:round3 --ledger`
```
[ ] Yes
```
```
[ ] Yes
```

implements ledger dkg round3

---

ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/utils/ledger.ts
ironfish/src/wallet/index.ts

adds dkgRound2 method to Ledger util
implements performRound2WithLedger in round2 CLI command
- manual testing with `wallet:multisig:dkg:round2 --ledger`
```
[ ] Yes
```
```
[ ] Yes
```

implements ledger dkg round2

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/utils/ledger.ts
ironfish/src/wallet/index.ts

adds dkgRound1 method to Ledger util
fills in logic of performRound1WithLedger
reads identity from node and adds it to list of signer identities if it's missing
- manual testing with `wallet:multisig:dkg:round1 --ledger`
```
[ ] Yes
```
```
[ ] Yes
```

implements ledger dkg round1

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/participant/create.ts
ironfish-cli/src/utils/ledger.ts
ironfish/src/wallet/index.ts

adds dkgGetIDentity method to ledger util module
adds '--ledger' flag to 'wallet:multisig:participant:create' command
uses 'wallet/multisig/importParticipant' RPC to add the participant identity to the walletDb
- manual testing with `wallet:multisig:participant:create --ledger`
```
[ ] Yes
```
```
[ ] Yes
```

adds ledger flag to participant creation

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/participant/create.ts
ironfish-cli/src/utils/ledger.ts
ironfish/src/wallet/index.ts

removes response handling for error codes, which are no longer included in responses
implements tryInstruction to handle errors from any app instructions
adds methods to help discriminate between KeyResponse types and checks type of KeyResponse for each type of key
adds method to recognize Ledger response errors
defines classes for common recoverable Ledger errors: locked device and app not open. the error code for the app not being open is identified in the docs as a 'technical error', but this is the error code we get when the app isn't open
- manual testing with `wallet:import --ledger`
related documentation pull request for the …

updates ledger.ts for upgrade to @zondax/ledger-js

---

ironfish-cli/src/utils/ledger.ts

ask to approve round3 on Ledger, but don't ask for approval/confirmation when retrieving keys or public package
```
[ ] Yes
```
```
[ ] Yes
```

fixes Ledger approval output in round3

---

ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/utils/ledger.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish/src/primitives/unsignedTransaction.ts

implements dkgSign on Ledger util class to obtain a signature share from the device
adds '--ledger' flag to 'wallet:multisig:signature:create' command
adds selector to command to choose multisig account if one is not provided
adds 'publicKeyRandomness' method to UnsignedTransaction primitive to extract the randomness from the transaction (needed for signing)
adds 'serialize' napi method to NativeSignatureShare to support constructing the signature share from its raw parts and then printing it
- continued signing process from #5398 
- created signature share using `wallet:multisig:signature:create --ledger`
- aggregated signature shares using `wallet:multisig:signature:aggregate`
- mined transaction on devnet
Does this change require any updates to the Iron Fish Docs (ex. …

adds ledger flag for creating signature shares

---

ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/utils/ledger.ts
ironfish-rust-nodejs/index.d.ts
ironfish-rust-nodejs/src/multisig.rs
ironfish/src/primitives/unsignedTransaction.ts

implements dkgGetCommitments on Ledger util class
adds '--ledger' flag to 'wallet:multisig:commitment:create'
adds multisig account selector to 'commitment:create', fetches the identity for the selected account
adds 'hash' method to UnsignedTransaction primitive
- created ledger multisig account using dkg
- ran miner to fund default account, sent transaction to ledger multisig
- created unsigned transaction from ledger multisig
- created signing commitment using ledger multisig
```
[ ] Yes
``` …

adds ledger option for creating signing commitment

---

ironfish/src/rpc/routes/wallet/multisig/importParticipant.ts

includes name of conflicting identity in error message if the request tries to import an identity that already exists in the database
manual testing: tried to import the same identity from Ledger twice
```
[ ] Yes
```
```
[ ] Yes
```

improves error message from importParticipant RPC

---

ironfish-cli/src/commands/wallet/multisig/ledger/restore.ts
ironfish-cli/src/utils/ledger.ts

if the ironfish dkg ledger app is uninstalled, or if it is used to create a second set of keys, then the multisig keys on the device may be lost
the 'wallet:multisig:ledger:backup' command creates an encrypted key backup that can be restored to the device
the 'wallet:multisig:ledger:restore' command restores the backed up keys to the ledger
- created backup using 'wallet:multisig:ledger:backup' (#5400 )
- uninstalled and reinstalled ironfish dkg app
- ran 'wallet:multisig:ledger:restore' to restore keys and printed our keys to verify that they are the same as before …

adds cli command to restore ledger multisig backup

---

ironfish-cli/src/commands/wallet/multisig/ledger/backup.ts
ironfish-cli/src/commands/wallet/multisig/ledger/restore.ts
ironfish-cli/src/utils/ledger.ts

adds a CLI command, 'wallet:multisig:ledger:backup', to create an encrypted backup of multisig keys from the ironfish dkg ledger app
users can restore the keys to their ledger app if they reinstall the app on their device or overwrite the multisig keys in the app
manual testing: used the command to create key backup
```
[ ] Yes
```
```
[ ] Yes
```

implements ledger multisig backup command

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish/src/rpc/adapters/errors.ts
ironfish/src/rpc/routes/wallet/multisig/getIdentity.ts

- Implemented the multisig:dkg:create cli command to facilitate the creation of multisignature accounts using Distributed Key Generation (DKG).
- Added methods for participant management, and DKG rounds (1, 2, and 3) with user prompts for input.
- Integrated error handling and retry logic for every step.
- Enhanced user experience with informative logging and prompts throughout the process.
```
[ ] Yes
```
```
[ ] Yes
```

feat: DKG Create Command

---

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts

creates an encrypted backup and prints it to the terminal at the end of round3 of dkg
```
[ ] Yes
```
```
[ ] Yes
```

adds ledger backup to the end of round3

---

ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/utils/account.ts

extracts the import/name prompt loop logic from the 'wallet:import' command into an 'importAccount' util
uses the 'importAccount' util to import the account at the end of round3 so that import is retried in the case of name collisions
manual testing with `wallet:import`:
- create account 'test1'
- export account 'test1'
- delete account 'test1'
- create new account 'test1'
- try to import exported 'test1' acccount
manual testing with `wallet:multisig:dkg:* --ledger`:
- create ledger identity 'test'
- run through all steps of dkg to create account
- run through all steps of dkg with the same identity (but different partner) again to try to import another 'test' acount …

prompts for new name and retries import in round3

---

ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/ledger/import.ts
ironfish-cli/src/utils/ledger.ts

reads identity, shared multisig keys, and public key package from Ledger device
imports multisig account to wallet and prompts for new name if the provided name is taken
removes hardcoded account version number from other ledger imports (these imports aren't from serialized accounts, so the schema version should always be the current version)
- created multisig account using ledger/dkg
- imported account to new data directory using `wallet:multisig:ledger:import`
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it …

adds cli command to import multisig account from ledger

---

ironfish-cli/package.json
ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/utils/ledger.ts
yarn.lock

uses 'reviewTransaction' method from '@zondax/ledger-ironfish' to force user to review decrypted transaction outputs on the ledger device
updates our '@zondax/ledger-ironfish' dependency to use the latest release, which now includes dkg methods
note: for interactive signing we may only need to review once before creating the signing commitments
manual testing with signing flow
```
[ ] Yes
```
```
[ ] Yes
```

adds clear signing to ledger signing flows

---

ironfish-cli/src/utils/transaction.ts

when approving a transaction using a ledger device users are shown the asset id of each output note on the ledger device
the transaction details they see in the cli will not include the asset id if the asset is verified (the symbol will be displayed instead). this makes it more difficult to verify that the transaction you're seeing on the ledger is correct based on what the cli is showing you
if the asset has a verified symbol, also displays the asset id for the note on the line below the amount
before:
after:
```
[ ] Yes
``` …

always display asset id with notes in transaction details

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/utils/ledger.ts

Also added the ability to reuse an existing identity for the DKG process. The user can specify the account name separately from the participant name.
```
[ ] Yes
```
```
[ ] Yes
```

Adding ledger support for dkg:create

---

ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/ledger.ts

Adds the `--ledger` flag, so ledger accounts can be used to mint assets.
Closes IFL-2970
```
[ ] Yes
```
```
[ ] Yes
```

Add the ability to use a ledger device with the mint command

---

ironfish-cli/src/commands/wallet/mint.ts

This allows you to both mint new coins, and transfer them in the same transaction using the CLI. This is something that was already possible using the SDK or the RPC.
This is done by adding outputs with the same amount as the mint amount.
Example to mint 1 new asset called `foo-coin` and transfer the 1 new coin to `eccfd79c841e02cda4e2c53f3a149070f1bc8c7f76a41886d268b6ec8ed2ae3b`
```
fishy wallet:mint \
--transferTo eccfd79c841e02cda4e2c53f3a149070f1bc8c7f76a41886d268b6ec8ed2ae3b \
--transferMemo "this is a memo" \
--name foo-coin  \
--metadata meta  \
--amount 1  \
--fee 0.00000001
```
related documentation pull request for the …

Enable transfering in a mint in the CLI

---

ironfish/src/index.ts

This reverts commit dcaabd851816e9f994a6f81739d6d090f6e6fad9.
```
[ ] Yes
```
```
[ ] Yes
```

Revert "exports makeFakeWitness test util from ironfish sdk (#5415)"

---

ironfish-cli/src/commands/wallet/mint.ts

Right now, if you run `ironfish wallet:mint --metadata ''`, it will still interactively prompt you for a metadata. With this change, it will accept that you want an empty metadata. The behavior when not including the metadata flag is unchanged.
```
[ ] Yes
```
```
[ ] Yes
```

Allows `--metadata ''` when minting an asset

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

At the moment, ledger dkg only supports up to 4 participants. This commit adds an error message when the user tries to create a dkg with more than 4 participants.
```
[ ] Yes
```
```
[ ] Yes
```

Error for too many participants

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

This way the user has an opportunity to unlock device/ open app/ etc. instead of hitting max retries and failing
```
[ ] Yes
```
```
[ ] Yes
```

Ask for confirmation while retrying ledger connect

---

ironfish-cli/package.json
ironfish-cli/src/utils/ledger.ts
yarn.lock

we have two versions of @zondax/ledger-ironfish in our dependencies that require different versions of @zondax/ledger-js
we need to make sure that each version's dependencies resolve correctly in order for both the DKG and single signer apps to work
```
[ ] Yes
```
```
[ ] Yes
```

fix resolution of @zondax/ledger-js package

---

ironfish-cli/src/commands/wallet/multisig/sign.ts

Previously, this command was written in a way where the user performing this command didn't have to be a participant. This changes that to make sure that the user performing this command is a participant in the multisig wallet.
This is because this command is catering to the most common use case.
```
[ ] Yes
```
```
[ ] Yes
```

Expect to participant in signing

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/ledger/import.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.test.ts
ironfish/src/rpc/routes/wallet/multisig/dkg/round3.ts

adds '--createdAt' flag to 'wallet:multisig:dkg:create', 'wallet:multisig:dkg:round3', and 'wallet:multisig:ledger:import'
updates round3 RPC to accept optional 'accountCreatedAt' parameter
allows user to set the 'createdAt' sequence when creating a multisig account or importing one from a ledger device. this allows users to start using their accounts more quickly without waiting for the account to scan the entire chain
manual testing with `wallet:multisig:ledger:import` and `wallet:multisig:dkg:create`
```
[ ] Yes
``` …

optionally sets createdAt when importing multisig accounts

---

ironfish-cli/src/utils/transaction.ts

when testing multisig signing we found that rendering unsigned transaction details failed with the error 'No asset found with identifier' when the transaction contained a custom asset, but the wallet had not scanned a transaction that included that asset
users will likely use multisig signing offline, so they may not have access to synced asset data
updates '_renderTransactionDetails' to use 'getAssetVerificationByIds', which handles errors from missing assets
- ran `wallet:multisig:sign` on an unsynced node with a transaction containing a custom asset
```
[ ] Yes
``` …

fixes rendering of tx assets if node not synced

---

ironfish-cli/src/utils/chainport/requests.ts

Use the Chainport fallback API temporarily until we're ready to use the new one.
```
[ ] Yes
```
```
[ ] Yes
```

Use Chainport fallback token list API

---

ironfish-cli/src/utils/chainport/requests.ts

This will be fixed with a more robust solution soon
```
[ ] Yes
```
```
[ ] Yes
```

Temporarily assign different URL for mainnet

---

ironfish-cli/src/utils/ledger.ts

Calling app.getVersion errors when the app is locked and when the app is not open. This is sufficient enough for us to detect whether the app is open or not.
If it isn't open, we just end the process for the dkg commands.
```
[ ] Yes
```
```
[ ] Yes
```

Detects whether ironfish dkg app is open

---

ironfish-cli/src/commands/wallet/multisig/sign.ts

users must enter the identities of all signers (excluding their own) before creating a signing commitment
displays the user's own identity and asks the user to share it with other signers before prompting for the identities of other signers
```
[ ] Yes
```
```
[ ] Yes
```

displays own identity at start of signing process

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

the minimum number of signers cannot be greater than the number of total participants
throw an error when the user enters an invalid number instead of failing during round1
```
[ ] Yes
```
```
[ ] Yes
```

ensures that min signers entered is <= total participants

---

ironfish-cli/src/utils/ledger.ts

we've seen several errors occur commonly when the Ledger app is unavailable either because the device is locked or the app isn't open
catches errors with these codes and displays an error message telling the user that the error may be due to a locked device or closed app
before:
after:
Note that `returnCode` in examples above is from debug outout
```
[ ] Yes
```
```
[ ] Yes
```

uses actionable error message for common Ledger errors

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/ui/prompt.ts

Adds prompt util specific to numbers 
The problem with parse int is that even if you pass it something like "1234123asdf" it will return a success and return 1234123.
This is not what we want. We want to make sure that the user has entered a valid number.
We also want to retry the prompt if the user enters an invalid number or a decimal when an integer is expected.
```
[ ] Yes
```
```
[ ] Yes
```

inputNumberPrompt and usage

---

ironfish-cli/src/commands/wallet/chainport/send.ts

Previously, we showed this fee as the token being sent to the target network. This was an incorrect assumption on our part.
The fee is actually taken in IRON. The chainport fee is the one that is always either in the target token or portx token.
```
[ ] Yes
```
```
[ ] Yes
```

Target network fees is in IRON

---

ironfish-cli/src/commands/wallet/transactions/info.ts

We weren't passing the `account` flag to client.wallet.getAsset, so if your default account didn't happen to have a custom asset, the command would error.
Manually tested before/after on an account with a custom asset.
```
[ ] Yes
```
```
[ ] Yes
```

Fixes fetching assets for display in wallet:transactions:info

---

ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/utils/fees.ts

`wallet:chainport:send`'s fee selector wasn't respecting the `-a` flag.
Fixes IFL-3003
```
[ ] Yes
```
```
[ ] Yes
```

Fix wallet:chainport:send fee selection when -a is used

---

ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/transactions/info.ts
ironfish-cli/src/utils/chainport/config.ts
ironfish-cli/src/utils/chainport/requests.ts
ironfish-cli/src/utils/chainport/types.ts
ironfish-cli/src/utils/chainport/utils.ts

Switches from using the Chainport API directly to using a proxy through [our API](https://github.com/iron-fish/ironfish-api/pull/1767) to avoid breaking old CLI versions when Chainport deploys their new API.
Fixes IFL-2977
```
[ ] Yes
```
```
[ ] Yes
```

Use Iron Fish API for bridge info

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/server.ts
ironfish-cli/src/utils/multisig/network/clients/client.ts
ironfish-cli/src/utils/multisig/network/messages.ts
ironfish-cli/src/utils/multisig/network/server.ts
ironfish-cli/src/utils/multisig/network/serverClient.ts

supports using a single server for multiple runs of dkg and/or signing
updates 'wallet:multisig:dkg:create' to join an existing session with the 'sessionId' flag or create a new session if none is specified
uses UUID strings for session IDs
```
[ ] Yes
```
```
[ ] Yes
```

adds sessions to multisig server

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

This fixes a bug where you only re-ask for a name if it's duplicated once.
```
[ ] Yes
```
```
[ ] Yes
```

Continously ask for name if duplicate

---

ironfish-cli/package.json
ironfish-cli/src/utils/ledger.ts
yarn.lock

zondax/ledger-js is a subdependency of @zondax/ledger-ironfish. We rely on the ResponseError type from ledger-js which should ideally be exported from zondax/ledger-ironfish. This way we don't have to explicitly include this subdependency in our package.json.
A todo has been added to remove this dependency when the ResponseError type is exported from ledger-ironfish.
```
[ ] Yes
```
```
[ ] Yes
```

Adding zondax/ledger-js dependency

---

ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/utils/multisig/network/clients/client.ts
ironfish-cli/src/utils/multisig/network/messages.ts
ironfish-cli/src/utils/multisig/network/server.ts

defines common interface for storing dkg sessions and signing sessions in server memory
adds network messages for signing flow: starting a signing session, signing commitments, signature shares, and retrieving the status of a signing session
updates server and client implementations for new message types
updates 'sign' command:
- adds '--server' flag
- adds '--sessionId' flag
- prompts user to enter a session id or start a new session if server is set, but not session id
- connects to server, starts or joins a session, and uses messages to/from server to complete signing
```
[ ] Yes …
```

multisig server signing

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/server.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/index.ts
ironfish-cli/src/multisigBroker/utils.ts

uses TlsUtils from ironfish sdk to create TLS key and cert files on server start
adds '--tls' flag to server, dkg:create, multisig:sign commands
enables TLS by default
extracts repeated client creation logic into MultisigServerUtils.createClient util function
Closes IFL-3011
Closes IFL-3012
- started server with tls
- ran through dkg with two clients using tls
```
[ ] Yes
```
```
[ ] Yes
```

adds TLS support to multisig server

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/clients/tcpClient.ts
ironfish-cli/src/multisigBroker/utils.ts

uses xchacha20poly1305 to encrypt all string fields in messages sent to multisig server
client decrypts string fields in messages received from multisig server
derives the client key from a passphrase and the session ID (uses the bytes of the session ID, which is a UUID, for the salt and nonce). ensures that any client in the session can derive the key if they have the passphrase.
adds passphrase flags and prompts to dkg:create and multisig:sign
NOTE: numeric fields, like minSigners, are not currently encrypted
NOTE also: this encrypts the fields rather than the entire message so that the server can still distinguish between identities, publlc packages, etc. in its session state
Closes IFL-3013
- ran 'dkg:create' with two participants using a passphrase
Does this change …

encrypts multisig server messages

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts

updates 'dkg:create' and 'multisig:sign' not to set the '--tls' flag by default. since this flag depends on the '--server' flag this means that the '--server' flag must also be provided by default
```
[ ] Yes
```
```
[ ] Yes
```

fixes default tls flag in multisig commands

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts

- changes log messages to debug for packages that don't need to be sent to other participants: signing package, encrypted secret packages
- does not log identities, packages, commitments, shares when using multisig broker
- logs session ID on separate line when starting session
Closes IFL-3014
Closes IFL-3015
Closes IFL-3019
DKG logs after changes with broker:
```
[ ] Yes
```
```
[ ] Yes
```

reduces log output when using multisig broker

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/messages.ts
ironfish-cli/src/multisigBroker/server.ts

- Added logic on the server to check if a session has 0 connected clients when a client disconnects. If it does, it will delete the session
- Added a connected response from the server to the client when a client connects. Previously, it was sending the join session message immediately after connecting, which would lead to the message getting lost in the void
Closes IFL-3022
```
[ ] Yes
```
```
[ ] Yes
```

Cleanup sessions on Multisig Broker Server

---

ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/messages.ts
ironfish-cli/src/multisigBroker/server.ts

adds a server 'ack' message that the server sends to the client upon receiving and successfully parsing the client message. each 'ack' contains the client's message id
client sets an interval to retry sending each message. when it receives the 'ack' for its message it clears the interval for that message id
1. modified server to randomly drop messages
2. ran dkg successfully
```
[ ] Yes
```
```
[ ] Yes
```

automatically retries messages to multisig broker

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/server.ts

uses maxSigners for dkg and numSigners for signing to broadcast the session status once the required number of  participants have submitted data of a particular type
removes broadcasts of individual identities, packages, etc.
removes client handlers for messages containing individual identities, packages, etc.
simplifies client logic for waiting on data from server: only uses status messages instead of listening for individual identities etc AND polling status
distinguishes message methods for dkg identities and signing identities. the message bodies are the same, but it allows the server to distinguish how to handle the session
Closes IFL-3024
- created multisig account with `wallet:multisig:dkg:create` via server
- signed transaction using `wallet:multisig:sign` via …

multisig broker server broadcasts on step completions

---

ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/messages.ts
ironfish-cli/src/multisigBroker/server.ts

if a client submits data to the broker server encrypted with the wrong passphrase and key then all other clients will now skip that data
adds a 'challenge' to the session which is a string encrypted with the session passphrase and key
if a client fails to decrypt the challenge then the client throws an error
decrypts message data only when necessary
Closes IFL-3028
- ran dkg with two participants while a third client submitted bad data to the server
- tried to connect with incorrect passphrase and failed decryption challenge
```
[ ] Yes
```
Is this a breaking change? …

prevents incorrect session encryption from halting process

---

ironfish-cli/src/multisigBroker/server.ts

Sessions now track client IDs
Server has encapsulated logic to add/remove clients to/from sessions
Removes the need to iterate over all clients to determine if a session is active or not, and for broadcasting
Closes IFL-3029
```
[ ] Yes
```
```
[ ] Yes
```

Add ability for sessions to track specific clients

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts

displays the number of identities, packages, commitments, etc. that the client has received from the server and how many are expected
Closes IFL-3016
```
[ ] Yes
```
```
[ ] Yes
```

updates ux status messages waiting for multisig broker

---

ironfish-cli/src/commands/wallet/multisig/server.ts
ironfish-cli/src/multisigBroker/server.ts

uses a timeout to clean up data from idle sessions instead of cleaning up immediately after last client disconnects
allows for clients to reconnect to sessions
adds cli flag to server command
Closes IFL-3040
```
[ ] Yes
```
```
[ ] Yes
```

adds idle session timeout to multisig broker server

---

ironfish-cli/src/commands/wallet/multisig/sign.ts

This uses the new ledger UI action so that it will wait for the user to connect and unlock their ledger.
```
[ ] Yes
```
```
[ ] Yes
```

Upgrade wallet:multisig:sign to use ui.ledger

---

ironfish-cli/src/commands/wallet/import.ts

This uses the new ledger UI action so that it will wait for the user to connect and unlock their ledger.
```
[ ] Yes
```
```
[ ] Yes
```

Upgrade wallet:import to use ui.ledger

---

ironfish-cli/src/ledger/ledger.ts

This is currently broken while waiting for a fix from the zondax devs. This will at least make it work for now. We just cannot use the app info on any rust based app like DKG.
```
[ ] Yes
```
```
[ ] Yes
```

Handle appInfo() crash on rust app

---

ironfish-cli/src/ledger/ledger.ts

Since we can disconnect on the appInfo() call we need to cache this and make sure we use the correct app.
```
[ ] Yes
```
```
[ ] Yes
```

Use the connected app in case of disconnect

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

when starting a new dkg session with a ledger the user currently sees output about getting the identity from the ledger in between choosing to start a new session and entering the max/min signers for that session
before:
after:
```
[ ] Yes
```
```
[ ] Yes
```

get identity after dkg parameters in dkg:create

---

ironfish-cli/src/ui/ledger.ts

removes the error status (e.g., 'Open Ledger App Ironfish') after the user has resolved the cause of the error
manual testing with `wallet:import --ledger`
```
[ ] Yes
```
```
[ ] Yes
```

resets ledger ui status between errors

---

ironfish-cli/src/ledger/ledger.ts

This makes one unified type with all the known error codes.
```
[ ] Yes
```
```
[ ] Yes
```

Unify ledger errors and zondax errors

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

Makes it a little easier to get through the setup phase for power users
- Test with server and with flags: Should not prompt for total participants and min signers
`wallet:multisig:dkg:create --server <...> --totalParticipants 2 --minSigners 2`
- Test with server and without flags: Should prompt for total participants and min signers
`wallet:multisig:dkg:create --server <...>`
- Test without server and with flags: Should not prompt for total participants and min signers
`wallet:multisig:dkg:create --totalParticipants 2 --minSigners 2`
- Test without server and without flags: Should prompt for total participants and min signers
`wallet:multisig:dkg:create`
- Test with sessionId and with flags: Should throw an error due to these flags being exclusive
`wallet:multisig:dkg:create --sessionId …

Add flags for minSigners and totalParticipants for dkg:create

---

ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ui/ledger.ts

If you don't approve the command you will now get a nice error.
```
[ ] Yes
```
```
[ ] Yes
```

Handle app command rejections from device

---

ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/ledger/backup.ts
ironfish-cli/src/commands/wallet/multisig/ledger/import.ts
ironfish-cli/src/commands/wallet/multisig/ledger/restore.ts
ironfish-cli/src/commands/wallet/multisig/participant/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/commands/wallet/transactions/sign.ts
ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ledger/ledgerMultiSigner.ts
ironfish-cli/src/ledger/ledgerSingleSigner.ts
ironfish-cli/src/ui/ledger.ts

the Ledger class and subclasses do not log messages. clients that want log output must log themselves
```
[ ] Yes
```
```
[ ] Yes
```

removes logger from Ledger class

---

ironfish-cli/src/ui/ledger.ts
ironfish-cli/src/ui/prompt.ts
ironfish-cli/src/ui/retry.ts

And convert ui.ledger to use it.
```
[ ] Yes
```
```
[ ] Yes
```

Convert ui.retry to new confirmListPrompt

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

This allows round3 and backup to fail independently and we can retry them separately.
```
[ ] Yes
```
```
[ ] Yes
```

Backup ledger keys in a separate step

---

ironfish-cli/src/ledger/ledger.ts

This handles the error as either a ResponseError or a TransportStatusError. The C SDK throws ResponseError and the Rust SDK throws TransportStatusError.
```
[ ] Yes
```
```
[ ] Yes
```

Fix rejection type on C vs Rust SDK

---

ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ui/ledger.ts

This fix ensures that the timeout threshold to check the user should approve the action is more than the connect timeout.
```
[ ] Yes
```
```
[ ] Yes
```

Set approve timeout greater than connect timeout

---

ironfish-cli/src/commands/wallet/transactions/info.ts
ironfish-cli/src/utils/chainport/utils.ts

* Show tx details even if there's an error fetching network details
* Remove extra source information from logs
* Use states in line with bridge prototype and update checks using Chainport API docs
```
[ ] Yes
```
```
[ ] Yes
```

feat(cli): Update transaction summary for chainport transactions

---

ironfish-cli/src/ledger/README.md
ironfish-cli/src/ledger/ledger.ts

This adds new documentation about what and which errors are thrown. It
also removes appInfo() and getVersion() during tryInstruction because it
duplicates the error cdoes you get from just running any app commands.
This also transforms ledger app errors from TransportStatusError into
ResponseError so we can handle all the error codes in a single way.
The original investigation of this fix was done by @hughy and we furthered the research on figuring out that the entire connect handshake is not needed.
Original PR: https://github.com/iron-fish/ironfish/pull/5511
```
[ ] Yes
```
Is this …

Avoid connect handshake and handle all error cases

---

ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts
ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ledger/ledgerMultiSigner.ts

updates dkgGetCommitments and dkgSign to catch Ledger error caused by unreviewed
transaction (InvalidTxHash), call reviewTransaction, and finally recursively
call themselves
adds error type for LedgerInvalidTxHash
```
[ ] Yes
```
```
[ ] Yes
```

reviews tx on InvalidTxHash error

---

ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ui/ledger.ts

When the ledger app panics at least show a better error and give them a chance to reopen the app to retry.
```
[ ] Yes
```
```
[ ] Yes
```

Handle ledger app panics

---

ironfish/src/rpc/routes/chain/followChainStream.ts
ironfish/src/rpc/routes/chain/getTransactionStream.ts
ironfish/src/rpc/routes/chain/serializers.ts
ironfish/src/rpc/routes/chain/types.ts
ironfish/src/rpc/routes/wallet/mintAsset.test.ts
ironfish/src/rpc/routes/wallet/mintAsset.ts
ironfish/src/rpc/routes/wallet/serializers.ts

assets stored in the blockchain database include both 'creator' and 'owner', but the RpcMint type only includes 'creator'
our api expects to receive mint data that includes 'owner'
updates RpcMint to include owner
NOTE: this field is immediately deprecated alongside 'creator' and other fields that can be read from asset RPCs. fully deprecating these fields for endpoints like 'followChainStream' and 'getTransactionStream' that expect streams of chain data could make the process of fetching asset data with separate requests between streaming responses difficult
```
[ ] Yes
```
Is this …

adds owner to RpcMint

---

ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ui/ledger.ts

Because zondax removed the ability to discern between a locked app and a locked device.
```
[ ] Yes
```
```
[ ] Yes
```

Handle all device locks as manual retry

---

ironfish-cli/src/ledger/ledger.ts

Found these in the hw-transport library from ledgerhq.
```
[ ] Yes
```
```
[ ] Yes
```

Handle all connecting errors as LedgerConnectError

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/clients/tcpClient.ts
ironfish-cli/src/multisigBroker/clients/tlsClient.ts
ironfish-cli/src/multisigBroker/utils.ts

changes '--server' to boolean flag in 'wallet:multisig:sign' and 'wallet:multisig:dkg:create'
adds '--hostname' and '--port' flags in place of previous '--server' flag to supply server hostname and port
defaults 'hostname' to 'multisig.ironfish.network' and 'port' to 9035
adds support for connection strings with '--connection' flag
adds util function to parse all connection options from flags
prints connection string to console after starting session
Closes IFL-3043
```
? Enter a name for the multisig account: test0
? Enter the ID of a multisig session to join, or press enter to start a new session: 
? Enter the passphrase for the multisig session: test
? Enter the total number of participants: 2
? Enter the number of minimum signers: 2
Started new DKG session: …
```

adds default multisig broker server

---

ironfish-cli/src/commands/wallet/multisig/ledger/restore.ts

This also makes the type of `encryptedKeys` `string` and not `string | undefined`.
```
[ ] Yes
```
```
[ ] Yes
```

Fix ledger restore to require encrypted key

---

ironfish-cli/src/commands/wallet/multisig/ledger/restore.ts

This uses the new reliable ledger connection
```
[ ] Yes
```
```
[ ] Yes
```

Upgrade ledger:restore cmd to use ledger ui

---

ironfish-cli/package.json
package.json
yarn.lock

This makes sure that we get the same error types as all of the sub
packages from ledgerhq and zondax. They are using mixed versions of the
same package.
```
[ ] Yes
```
```
[ ] Yes
```

 Add @ledgerhq/errors resolution to package

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/ui/prompt.ts

if a user inputs a duplicate string into a prompt from collectStrings, they will be informed of the duplicate and the prompt will be repeated
adds option to allow duplicates
updates usage of collectStrings in 'wallet:multisig:dkg:create' and 'wallet:multisig:sign' not to error on duplicates
```
[ ] Yes
```
```
[ ] Yes
```

updates collectStrings to prompt for new item on duplicate

---

ironfish-cli/src/multisigBroker/server.ts

if the broker server receives a message that it cannot parse then it should disconnect from the client that sent the message
the server cannot send an 'ack' message to the client if it cannot parse the message and cannot send an error message with the message id of the errant message, so the client may continue retrying the malformed message if the server does not disconnect
for now the server does not implement client banning
Closes IFL-3062
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it with `breaking-change-rpc` or …

multisig broker server disconnects on invalid message

---

ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts

gives the user feedback that the command is waiting on a connection to the multisig broker server
Closes IFL-3054
```
[ ] Yes
```
```
[ ] Yes
```

uses ux action to show client connecting

---

ironfish-cli/src/multisigBroker/server.ts
ironfish-cli/src/multisigBroker/sessionManagers/dkgSessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/signingSessionManager.ts

updates server to send 'joined_session' message to client after starting the session on the server side
updates session manager to wait for 'joined_session' message before returning from startSession
adds ux status output when waiting for confirmation of joined session
Closes IFL-3057
```
[ ] Yes
```
```
[ ] Yes
```

wait for server to confirm session started

---

ironfish-cli/src/commands/wallet/import.ts
ironfish-cli/src/commands/wallet/multisig/ledger/import.ts
ironfish-cli/src/ledger/ledgerMultiSigner.ts

adds a '--multisig' flag to use with the '--ledger' flag to import a multisig account from the Ironfish DKG Ledger app
adds an 'importAccount' method to 'LedgerMultiSigner' to match the function signature in the 'LedgerSingleSigner' class
updates 'wallet:multisig:ledger:import' to use the same lgoic
hides 'wallet:multisig:ledger:import' and adds a deprecation message
```
[ ] Yes
```
```
[ ] Yes
```

updates 'wallet:import' to support ledger multisig

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/clients/tcpClient.ts
ironfish-cli/src/multisigBroker/sessionManagers/dkgSessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/signingSessionManager.ts
ironfish-cli/src/multisigBroker/utils.ts

instead of requiring a passphrase at the time of client construction, sets the client passphrase only when starting or joining a session
moves usage of 'parseConnectionOptions' into session manager for sessions that use the multisig broker server
prompts the user for sessionId and passphrase in 'startSession'. this will allow for re-prompting if starting or joining the session fails
```
[ ] Yes
```
```
[ ] Yes
```

sets passphrase on client when joining session

---

ironfish-cli/src/multisigBroker/sessionManagers/dkgSessionManager.ts

Right now, if you input an invalid number for total participants or min signers, it will end the process by throwing an error. A better experience is to display the error and allow the user to try again with proper input.
Run `wallet:multisig:dkg:create --server --ledger` and:
- for total participants:
- press enter without a number
- enter 0
- enter 99
- enter 4
- for min signers:
- press enter without a number
- enter 0
- enter 99
- enter 3
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it with `breaking-change-rpc` or …

Don't crash when invalid dkg config input is given

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/errors.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts

if a user enters the passphrase for a session by the client is unable to decrypt the session challenge string, the client emits a 'SessionDecryptionError'. the 'wallet:multisig:dkg:create' and 'wallet:multisig:sign' commands will now retry the step and prompt the user to re-enter the passphrase
adds an event emitter, 'onClientError', to the multisig client. emitting client errors as events provides a way for the command logic to define error handlers to throw/catch the error in the control flow of the command instead of in response to server data
```
[ ] Yes
``` …

retries joining session if passphrase incorrect

---

.github/workflows/deploy-brew.yml
ironfish-cli/scripts/deploy-brew.sh

We've been deploying these to R2 for a while, but the script still uploads releases to both. Since we've had some confusion over which to use, we can remove the S3 upload.
```
[ ] Yes
```
```
[ ] Yes
```

Remove S3 uploading from Homebrew deployment

---

ironfish-cli/src/multisigBroker/server.ts
ironfish-cli/src/multisigBroker/serverClient.ts

If you disconnect and re-connect  during the identity phase, and add/remove --ledger flag or otherwise do something that would change the identity, the DKG process will keep the old identity around and move forward to the next stage, making it impossible to complete the process.
We can safely delete the identity from the session when a user disconnects so long as it happens during the identity collection phase. If it has moved past that phase, there are more implications, so I did not handle it in this PR.
This PR also opens the door for other improvements by adding the identity to the server client.
related documentation pull request …

Clear identities when a user disconnects during the identity collection phase

---

ironfish-cli/src/multisigBroker/errors.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts

listens for server error messages with the error code for sessionId not found while waiting for a session. throws an error if the sessionId is not found
Closes IFL-3052
```
[ ] Yes
```
```
[ ] Yes
```

prompts user to re-enter sessionId if session not found

---

ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/utils.ts

supports passphrases that contain spaces and other unicode characters that would result in invalid connection strings
decodes passphrase when parsing connection string
Closes IFL-3073
manual testing
```
[ ] Yes
```
```
[ ] Yes
```

encodes passphrase as URI component in connection string

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/messages.ts
ironfish-cli/src/multisigBroker/server.ts
ironfish-cli/src/multisigBroker/sessionManagers/dkgSessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/signingSessionManager.ts

modifies multisigBroker messages so that each client submits its identity when it starts or joins a session
simplifies the session flow by removing separate messages for submitting identities
Closes IFL-3076
- created multisig account with 'wallet:multiisg:dkg:create'
- signed transaction with 'wallet:multisig:sign'
```
[ ] Yes
```
```
[ ] Yes
```

clients submit identity when starting or joining session

---

ironfish-cli/src/commands/wallet/multisig/sign.ts

when running the 'wallet:multisig:sign' command using a broker server there are no prompts or manual steps after the initial setup. this doesn't give the user a chance to confirm the details of the unsigned transaction before the signing process moves forward
adds a confirmation prompt if the 'sessionManager' is connected to a server
moves the rendering of transaction details and the confirmation prompt out of a 'retryStep' function so that confirmation isn't retried
manual testing
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why this is breaking and label it …

adds confirmation prompt to 'multisig:sign' if using server

---

ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/errors.ts
ironfish-cli/src/multisigBroker/messages.ts
ironfish-cli/src/multisigBroker/server.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/signingSessionManager.ts

server blocks any client from joining the session if its identity is not in the set of allowed identities
sends the (encrypted) list of account identities to the server when starting a signing session. guards against user accidentally joining signing session with the wrong account
throws an error when joining the session with an identity that is not in the allowed set (does not retry)
allowedIdentities is optional for dkg sessions, but there's not a clear way yet of specifying this set
Closes IFL-3074
- tried to join session with the wrong account/identity
- joined session and signed transaction with correct identity
related …

adds allowed identities set to multisig server sessions

---

ironfish-cli/src/utils/transaction.ts
ironfish/src/primitives/unsignedTransaction.ts

when reviewing an unsigned transaction it will be helpful to display the transaction fee and expiration
these fields are shown when reviewing the transaction on a ledger device, so we should also display them on the CLI
```
[ ] Yes
```
```
[ ] Yes
```

renders fee and expiration in unsigned transaction summary

---

ironfish-rust/src/lib.rs

These are used in downstream consumers of `ironfish` package, making them public.
```
[ ] Yes
```
```
[ ] Yes
```

make sapling params public

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/multisigBroker/sessionManagers/dkgSessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/signingSessionManager.ts
ironfish-cli/src/multisigBroker/utils.ts

if a user sets the hostname or port for the multisig broker server using flags then they should not need to _also_ set the '--server' flag in order to connect to the server
defines constants for default multisig broker hostname and port
removes default values for hostname and port flags in 'wallet:multisig:dkg:create' and 'wallet:multisig:sign' and applies defaults only when flags are used. allows flags to be unset to determine whether user has set the flags
adds factory functions for session managers
Closes IFL-3084
- ran 'wallet:multisig:dkg:create --hostname localhost', connected to localhost
- ran 'wallet:multisig:dkg:create --server', connected to AWS server …

uses server if user sets 'hostname' or 'port'

---

ironfish-cli/src/commands/wallet/unlock.ts

Imported TimeUtils to access renderSpan
Updated log to output lock timeout in hrs, mins, secs.
Encrypt, lock, and unlock wallet to see log
N/A
```
N/A
```

Wallet Unlock Log: Added Lock Timeout in Hrs, Min, Sec

---

ironfish-cli/src/multisigBroker/clients/client.ts

if a client disconnects from the multisig broker server unexpectedly then the server will remove the client and its identity from the session
client automatically rejoins the session after automatically reconnecting so that the server adds it and its identity back into the session
nests sessionId and passphrase properties into a single 'session' property along with the identity. sessionId, passphrase, and identity must all be non-null or all null, and grouping them into an object reflects this
apply the diff below (`git diff apply`) to make the server drop a client's connection on ~50% of 'dkg.get_status' messages:
```
diff --git a/ironfish-cli/src/multisigBroker/server.ts b/ironfish-cli/src/multisigBroker/server.ts
index adf297087..88d841165 100644
--- …
```

automatically rejoins session when reconnecting to server

---

ironfish-rust/src/errors.rs
ironfish-rust/src/serializing/mod.rs
ironfish-zkp/src/hex.rs
ironfish-zkp/src/lib.rs

Moves `hex_to_bytes`, `bytes_to_hex`, and `hex_to_vec_bytes` to `ironfish-zkp` so that we can use it for ser/de of structs there too.
As `ironfish-zkp` is dependency of `ironfish-rust`, this will be available in both crates now.
tests pass
```
[ ] Yes
```
```
[ ] Yes
```

hex encode/decode pushed to ironfish-zkp

---

ironfish-cli/src/multisigBroker/clients/client.ts
ironfish-cli/src/multisigBroker/sessionManagers/dkgSessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts
ironfish-cli/src/multisigBroker/sessionManagers/signingSessionManager.ts

adds 'onDisconnected' event emitter to multisig broker client
uses 'onDisconnected' events in sessionManager to wait from confirmation that client has reconnected to server and rejoined session
by using 'waitForConnectedMessage' and 'waitForJoinedSession' we display ux status output to the user _and_ throw an error if the session can't be rejoined
updates session managers to conditionally start ux actions in polling loops. this makes it so that the session manager won't clear the ux status output from waiting to reconnect or rejoin a session while polling for session status
Closes IFL-3090
1. start server using 'wallet:multisig:server'
2. connect to server for dkg session with 'wallet:multisig:dkg:create --hostname localhost', wait until session joined
3. stop and restart server process …

handles reconnect/rejoin status in session managers

---

.github/workflows/ci.yml
.github/workflows/rust_ci.yml
package.json

We were getting intermittent issues using the original codecov upload process,
which has been deprecated for a few years now. The coverage also has been
broken for some unknown amount of time. Using the github action is the
officially recommended way to upload to codecov now.
```
[ ] Yes
```
```
[ ] Yes
```

use github action for uploading codecov

---

ironfish-cli/src/multisigBroker/sessionManagers/sessionManager.ts

the handler that we add to the MultisigClient.onDisconnected event assumes that the client will try to reconnect and rejoin a session after a disconnect. however, if the session is ended, the client will not try to reconnect. this results in the CLI displaying an endless action stating that it is waiting to connect after the session ends
clears the handler before stopping the client so that the sessionManager won't wait for messages confirming server reconnection and session rejoin
manual testing: ran through signing flow with server
```
[ ] Yes
```
Is this a breaking change? If yes, …

clears onDisconnected event handler when ending session

---

ironfish/src/rpc/routes/wallet/create.test.slow.ts
ironfish/src/rpc/routes/wallet/createAccount.ts

Allow account creation to take a createdAt object
Unit tests
```
[ ] Yes
```
```
[ ] Yes
```

Add createdAt to createAccount RPC

---

.github/workflows/ci.yml

Shards the main test suite across 3 shards, and slow tests across 2 shards, resulting in a CI runtime reduction from around 15 minutes to around 6.5-7 minutes: https://github.com/iron-fish/ironfish/actions/runs/11486776859
Re-ran CI workflow multiple times across 2 branches
```
[ ] Yes
```
```
[ ] Yes
```

shard unit tests in CI for faster CI runs

---

Cargo.lock
ironfish-rust-nodejs/Cargo.toml
ironfish-rust/Cargo.toml
supply-chain/audits.toml
supply-chain/config.toml

Now that `ironfish-frost` is published, we can use the published version instead of the "git" version.
Unit tests
N/A
N/A

Change the `ironfish-frost` dependency to use the crate from crates.io

---

.github/workflows/rust_ci.yml

uses nextest as a test runner and llvm-cov as the coverage reporter. neither the default test runner nor cargo tarpaulin support sharding, so opting to use nextest for this purpose.
see: https://github.com/iron-fish/ironfish/actions/runs/11507837608
```
[ ] Yes
```
```
[ ] Yes
```

shard rust unit tests on ci

---

ironfish-cli/package.json
ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/utils/multisig/sessionManagers/sessionManager.ts
yarn.lock

upgrades '@ironfish/multisig-broker'
catches error messages with the 'DKG_SESSION_FULL' error code and throws an appropriate error in 'waitForJoinedSession'
changes 'dkg:create' to ask the user if they want to retry joining the session. gives the user an opportunity to wait before immediately trying to rejoin a full session
defines error types that were removed from '@ironfish/multisig-broker'
Closes IFL-3098
1. start dev server
2. start dkg session using `ironfish wallet:multisig:dkg:create --hostname localhost --ledger`. set total participants to 2. use ledger so that round1 does not start before extra client tries to join.
3. join dkg session with second client
4. try to join dkg session with third client and observe error and prompt to retry
Does this change require any updates to the …

handles errors from full dkg sessions

---

.github/workflows/ci-regenerate-fixtures.yml

See https://github.com/iron-fish/ironfish/actions/runs/10905813952/job/30265585854
It looks like this secret may have been renamed at some point, but the CI job wasn't updated to reflect it
N/A
N/A

update fixture ci job to use the right secret

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/sign.ts

removes dependency of tls flag on server flag in 'wallet:multisig:dkg:create' and 'wallet:multisig:sign'
allows user to use flag combinations like '--hostname localhost --no-tls' without needing to also set the '--server' flag
1. start dev server in `multisig-broker` repo using `yarn start`. the dev server does not use TLS
2. run `wallet:multisig:dkg:create --hostname localhost --no-tls` to connect to the dev server without TLS
```
[ ] Yes
``` …

allows multisig commands to disable tls without server flag

---

.github/workflows/perf_test.yml

The performance test CI job was regularly taking ~45 minutes, with it sometimes taking up to an hour and a half. The reason it takes more than 10 minutes at all is because it is downloading a 7.5gb yarn cache via the `actions/setup-node` job. This is unnecessary since it seems to have all of these files cached locally as it is.
After removing the yarn cache, it has to recompile the rust code on each run. However, since the runner is a fairly powerful machine, it only takes about a minute, which seems better than trying to download the cache from a data center somewhere over a somewhat slow wifi network.
See: https://github.com/iron-fish/ironfish/actions/runs/11523779611/job/32082513578
Ran the perf job directly on the branch by adding it to the job's push branches and allowing the runner …

dont cache yarn

---

ironfish-cli/src/utils/multisig/sessionManagers/dkgSessionManager.ts
ironfish-cli/src/utils/multisig/sessionManagers/sessionManager.ts
ironfish-cli/src/utils/multisig/sessionManagers/signingSessionManager.ts

when prompting for session ID, tries to parse the user input as a connection string. this allows the user to enter a connection string (e.g., 'tcp://session-id:passphrase@hostname:port') in this prompt instead of only the session ID
updates MultisigClientSessionManager to delay instantiating the client until connection time to allow the prompt to change the hostname and/or port
Closes IFL-3096
1. start dkg session using `wallet:multisig:dkg:create --server`
2. join dkg session in second window using `wallet:multisig:dkg:create --server` and entering the connection string from step 1 in the session ID prompt
related documentation pull …

allows multisig users to enter connection string for session ID

---

.github/workflows/deploy-npm-ironfish-rust-nodejs.yml

When deploying the rust binding packages, if the download-artifacts step fails to download any artifacts, it will not raise an error. Neither will the npm publish step. This will lead to problems where the packages depending on the bindings will be broken since the bindings will not get released.
This PR adds a basic sanity check to make sure that some artifacts are downloaded, otherwise it will fail. 
Closes IFL-2719
Temporarily added this step into a different CI job to ensure it works as expected.
- Folder doesn't exist (fail): https://github.com/iron-fish/ironfish/actions/runs/11526254922/job/32090058598
- Folder is empty (fail): https://github.com/iron-fish/ironfish/actions/runs/11526268604/job/32090093439
- Folder exists and has at least one file in it (pass): …

ensure artifacts folder exists when deploying rust bindings

---

ironfish-cli/src/commands/wallet/index.ts
ironfish/src/rpc/routes/wallet/serializers.ts
ironfish/src/rpc/routes/wallet/types.ts

defaults to showing table header so that we can display default account column as well.
```
...
{
"name": "testnet genesis",
"id": "b0557e1c-16e1-4f2b-b491-38e87422df58",
"head": {
"hash": "0000025a50df477c9699d4149558857b6955f84b0e7032b3880fd6612baa7076",
"sequence": 738626,
"inChain": true
},
"scanningEnabled": true,
"viewOnly": false,
"default": true
},
```
```
Account         Default
─────────────── ───────
foo                    
nodeapptest            
testnetnodeapp         
testnet                
testnet genesis ✓      
rahuldaniel            
nodeappdkg             
50a26d7134        
```
related documentation pull request …

feat(IFL-2710): Show default account in account list

---

ironfish/src/wallet/scanner/walletScanner.ts

only logs scan starts and ends in debug output if the start and end sequences differ
reduces noise from debug output when running a synced node where each block produces a new scan with equal start and end sequences
Closes IFL-2707
ran synced node in verbose node before and after applying changes
```
[ ] Yes
```
```
[ ] Yes
```

chore(IFL-2707): conditionally logs scan starts and ends

---

ironfish-cli/src/commands/wallet/burn.ts
ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/commands/wallet/mint.ts
ironfish-cli/src/commands/wallet/send.ts
ironfish-cli/src/utils/currency.ts
ironfish-cli/src/utils/fees.ts

For verified assets, show `asset.name ✓`
for unverified show `asset.name`
Open to suggestions on what to show after unverified name
```
51f33a2f14f92735e562dc658a5639279ddca3d5079a6d1242b2a588a9cbf44c ($IRON✓) (984.90098975) 
f3b28d5a7a1d6674cff47b5518e81c729b8330118ab0a42582fa7c345e3416fd (NORI) (9999999999999999) 
```
```
[ ] Yes
```
```
[ ] Yes
```

chore(IFL-2555): Prompt currency cleanup

---

ironfish-cli/src/commands/evm/erc20/balance.ts

Adds command to get ERC20 balance
```
[ ] Yes
```
```
[ ] Yes
```

get erc20 balance

---

ironfish-rust/src/frost_utils/account_keys.rs

A text block has been incorrectly marked with `ignore`. This means that `cargo test` considers the block as a doc test that shouldn't be compiled/run and is reported in its output.
Run `cargo test -p ironfish` and verify that this line is gone:
```
test ironfish-rust/src/frost_utils/account_keys.rs - frost_utils::account_keys::derive_account_keys (line 29) ... ignored
```
N/A
N/A

Mark a doc comment block as `text` instead of `ignore`

---

ironfish-rust-nodejs/src/stats.rs

This was missed during the transition from `jubjub` to `ironfish_jubjub`
```
cargo test --all-features
```
N/A
N/A

Fix an undeclared crate name error when the `stats` feature is enabled

---

ironfish-cli/src/commands/wallet/chainport/send.ts
ironfish-cli/src/utils/chainport/requests.ts
ironfish-cli/src/utils/chainport/types.ts

Displays the Received amount using the symbol of the token on the target network instead of the symbol on Iron Fish.
Also changed "Ironfish" to "Iron Fish"
Also changed to do conversions of bridged amount and fees using chainport's decimals rather than ours. I don't think it's likely that there would be a conflict anyway, since our API only shows bridgeable assets if they're verified and the decimals are the same as Chainport's API.
Ran through wallet:chainport:send up to the confirmation screen.
```
[ ] Yes
``` …

Use destination token symbol on bridge confirmation

---

ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/ui/table.ts

this was printing the headers for every line because it was not checking the no-headers table option
its a known issue that the json output for streamed responses is still not fixed, but that is a bigger problem to tackle
run `wallet:transactions --csv`
N/A
N/A

fix streamed csv output for wallet:transactions

---

ironfish/src/network/peerNetwork.ts
ironfish/src/network/peers/peer.ts

adds onMessage event handler to log a warning message if a bootstrap node is on a different network than the user's node
outputs the warning without requiring verbose output and specifies that the peer with the network mismatch is a bootstrap node
updates 'Peer.dispose' to use 'clearAfter' on 'onMessage' so that this second handler will still fire to log the warning even after disconnecting from the bootstrap node
Closes IFL-1217
run a testnet node and use the `--bootstrap` or `-b` flag to specify a mainnet bootstrap node, observe warning message
```
[ ] Yes
``` …

logs warning if bootstrap node on different network

---

ironfish-cli/src/commands/wallet/account.ts

'wallet:account' displays the status information available in 'wallet:accounts --extended' for a single account accepted as an arg
defaults to the wallet's default account
Closes IFL-2651
default account:
no account with name:
```
[X] Yes
```
```
[ ] Yes
```

adds command to display status for single account

---

.github/workflows/rust_ci.yml

This is to ensure that our code works with different Rust feature combinations.
This does not exercise *all* feature combinations, but a subset. The reason why we're using a subset are multiple:
* tests are slow and expensive
* exercising all combinations would be done with tools like [cargo-all-features](https://github.com/frewsxcv/cargo-all-features) that however do not support parallelization of tests
* even if the tools supported parallelization, integrating them with the GitHub CI wouldn't be straighforward
To make sure that all feature combinations at least *build* successfully, the clippy checks will be expanded in a future PR.
Example run for this PR: https://github.com/iron-fish/ironfish/actions/runs/11620113212?pr=5608
N/A
N/A

Rust CI: run tests with `--no-default-features` and `--all-features`

---

.github/workflows/rust_ci.yml

This changes the Rust CI to run `cargo check` for every possible feature combination.
What `cargo check` does is compiling the Rust packages without performing the last step of code generation (see the [documentation](https://doc.rust-lang.org/cargo/commands/cargo-check.html)), which basically mean it will catch almost all build errors. Running `cargo check` for every feature combination helps ensuring that every combination can be built.
Example run: https://github.com/iron-fish/ironfish/actions/runs/11620444213/job/32362234716?pr=5609
N/A
N/A

Rust CI: run `cargo check-all-features` instead of `cargo check`

---

ironfish-rust/build.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/sapling.rs

This is to allow our documentation to build on platforms like docs.rs, which need to build the documentation for our crates, but don't have access to the Sapling parameters.
This is currently blocking us from having working documentation on docs.rs, see:
* https://docs.rs/crate/ironfish/0.3.0
* https://docs.rs/crate/ironfish/0.3.0/builds/1473279
This commit hopefully should fix this problem for future releases.
This also slightly improves the experience for developers who use this crate for the first time: if they use the crate without the Sapling parameters, they'll now get a helpful warning instead of a panic.
Remove the Sapling parameters from your checkout, and run `cargo doc`. No errors should be reported.
N/A
N/A

Make the Sapling parameters optional for documentation builds

---

ironfish-cli/src/commands/mempool/transactions.ts
ironfish-cli/src/commands/peers/banned.ts
ironfish-cli/src/commands/wallet/assets.ts
ironfish-cli/src/commands/wallet/notes/index.ts
ironfish-cli/src/commands/wallet/transactions.ts
ironfish-cli/src/ui/table.ts

- adds default limit for table output to 50
- prints message at end of table if limit is reached
- updates commands to handle limit
- Intentionally excluded table command updates for: multisig, genesis, and combine notes
- Did not update print to occur on csv/json
Tested all updated commands with `--limit 1`
```
Timestamp                  Status       Type     Hash                                                             Expiration Submitted Sequence Fee Paid ($IRON) Asset                     Amount          
─── ────────────────────────── ──────────── ──────── ──────────────────────────────────────────────────────────────── ────────── ────────────────── ──────────────── ───────────────────────── ────────────────
10/28/2024 2:45:48 PM PDT  confirmed    send …
```

chore(IFL-2545): adds default limit for table output to 50

---

ironfish/src/rpc/routes/wallet/create.ts
ironfish/src/rpc/routes/wallet/createAccount.test.slow.ts

The wallet/create endpoint is being deprecated but it is not yet. We removed the tests so adding them back in. The endpoint also was not working as expected so fixing passing in the schema on register of the endpoint 
```
[ ] Yes
```
```
[ ] Yes
```

Fix tests + schema for wallet/create endpoint

---

ironfish-cli/src/commands/wallet/transactions/index.ts

All other list commands are index.ts instead of a duplicated name file. Making this consistent.
1. `yarn clean`
1. `yarn build`
1. `yarn start wallet:transactions`
```
[ ] Yes
```
```
[ ] Yes
```

Move transactions list command to index

---

ironfish-rust-nodejs/src/lib.rs
ironfish-rust-nodejs/src/nacl.rs
ironfish-rust/src/keys/public_address.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/note.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/unsigned.rs
ironfish-rust/src/witness.rs
ironfish-zkp/src/circuits/util.rs
ironfish-zkp/src/lib.rs
ironfish-zkp/src/primitives/value_commitment.rs

* Unit tests
* `cargo clippy`
N/A
N/A

Enable the `unused_qualifications` lint for our Rust crates

---

ironfish-rust-nodejs/src/lib.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/mining/thread.rs
ironfish-rust/src/transaction/value_balances.rs
ironfish-zkp/src/circuits/mod.rs
ironfish-zkp/src/circuits/util.rs
ironfish-zkp/src/lib.rs

* Unit tests
* `cargo clippy`
N/A
N/A

Enable the `unreachable_pub` lint for our Rust crates

---

ironfish-rust-nodejs/src/lib.rs
ironfish-rust/src/lib.rs
ironfish-rust/src/mining/thread.rs
ironfish-zkp/src/lib.rs

Also forbid the use of `println!`, `eprintln!`, `dbg!` and similar invocations, which should not be allowed in a library.
* Unit tests
* `cargo clippy`
N/A
N/A

Enable lints for unused code/dependencies in our Rust crates

---

ironfish/src/rpc/routes/wallet/create.test.ts
ironfish/src/rpc/routes/wallet/createAccount.test.ts
ironfish/src/rpc/routes/wallet/createAccount.ts
ironfish/src/testUtilities/fixtures/account.ts
ironfish/src/wallet/wallet.ts

This allows syncing to completely skip over an account until it reaches the passed in head value
Unit tests + testing with node app creating a fresh account
```
[ ] Yes
```
```
[ ] Yes
```

Pass in account head to wallet/createAccount

---

ironfish-rust/src/transaction/burns.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/mod.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/spends.rs

This way writing tests is easier, because a lot of methods commonly used in tests expects the arguments to implement `Debug`.
Note that `Transaction` and all the related descriptions do not hold any private/secret data, hence implementing `Debug` is safe.
N/A
N/A
N/A

Implement the `Debug` trait for `Transaction`

---

ironfish-cli/package.json
ironfish-rust-nodejs/npm/darwin-arm64/package.json
ironfish-rust-nodejs/npm/darwin-x64/package.json
ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json
ironfish-rust-nodejs/npm/linux-arm64-musl/package.json
ironfish-rust-nodejs/npm/linux-x64-gnu/package.json
ironfish-rust-nodejs/npm/linux-x64-musl/package.json
ironfish-rust-nodejs/npm/win32-x64-msvc/package.json
ironfish-rust-nodejs/package.json
ironfish/package.json

Version bump to 2.9.0
```
[ ] Yes
```
```
[ ] Yes
```

Version bump to 2.9.0

---

Cargo.lock
Cargo.toml
ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/errors.rs
ironfish-rust-wasm/src/lib.rs
supply-chain/audits.toml
supply-chain/config.toml
supply-chain/imports.lock

This adds a new `ironfish-rust-wasm` crate whose goal is to expose the `ironfish-rust` functionality to WASM for web browsers, just like `ironfish-rust-nodejs` exposes the functionality to NodeJS.
For now, the new crate only exposes the `IronfishError` struct.
* `cd ironfish-rust-wasm && cargo build --target=wasm32-unknown-unknown`
* `cd ironfish-rust-wasm && cargo test`
Support for proper testing through a web browser will be added in a future PR.
N/A
N/A

Add a barebone WASM crate

---

ironfish/src/wallet/scanner/__fixtures__/walletScanner.test.ts.fixture
ironfish/src/wallet/scanner/walletScanner.test.ts

Hash on account `createdAt` is being deprecated so just check against the sequence
```
[ ] Yes
```
```
[ ] Yes
```

Fix fixtures for wallet scanner

---

ironfish-cli/src/commands/wallet/transactions/index.ts

Was previously only printing out last row, bug was introduced here: https://github.com/iron-fish/ironfish/pull/5611/files
```
❯ fish wallet:transactions -d ~/.ironfish-testnet
$ yarn build && yarn start:js wallet:transactions -d /Users/joe/.ironfish-testnet
$ tsc -b tsconfig.build.json
$ cross-env OCLIF_TS_NODE=0 IRONFISH_DEBUG=1 node --expose-gc --inspect=:0 --inspect-publish-uid=http --enable-source-maps bin/run wallet:transactions -d /Users/joe/.ironfish-testnet
Timestamp                  Status       Type     Hash                                                             Expiration Submitted Sequence Fee Paid ($IRON) Asset                     Amount           
─── ────────────────────────── ──────────── ──────── …
```

fix transaction list output

---

ironfish/src/wallet/walletdb/walletdb.ts

the walletDb has serveral leftover implementations of methods that clear datastores
these methods are unused
not only are these methods unused, but they _should not_ be used: calling 'clear' on a datastore has the potential to block the wallet and node process while deleting from the database. data are deleted from these stores incrementally in the background using 'cleanUpDeletedAccounts' for this reason
N/A, methods unused
```
[ ] Yes
```
``` …
```

removes 'clear*' methods from the walletDb

---

ironfish-cli/src/commands/wallet/transactions/index.ts

This allows you to use --no-account to now see all the transactions data for all accounts.
**View transactions for the default account**
- `ironfish wallet:transactions`
**View transactions for myaccount**
- `ironfish wallet:transactions --account myaccount`
- `ironfish wallet:transactions --a myaccount`
**View transactions for all accounts**
- `ironfish wallet:transactions --no-account`
- `ironfish wallet:transactions --no-a`
Execute the commands listed above in the examples
```
[ ] Yes
``` …

Support viewing transaction data for all accounts

---

ironfish/src/wallet/account/account.ts
ironfish/src/wallet/walletdb/walletdb.ts

cleans up the walletDb by removing unused methods
removes one unused wallet method that was the only usage of a walletDb method
N/A
```
[ ] Yes
```
```
[ ] Yes
```

removes unused methods from walletDb

---

ironfish-cli/src/commands/wallet/transactions/index.ts

This adds 2 new columns which resolve to the account names of the sender / recipient if they are known to the wallet.
```
[ ] Yes
```
```
[ ] Yes
```

Include account names when displaying notes

---

Cargo.lock
ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/primitives.rs

Added bindings for:
- `Scalar`
- `Fr`
- `ExtendedPoint`
- `SubgroupPoint`
- `Nullifier`
- `redjubjub::PrivateKey`
- `redjubjub::PublicKey`
- `redjubjub::Signature`
These are all structs that are required by transactions.
* `cd ironfish-rust-wasm && cargo build --target=wasm32-unknown-unknown`
* `cd ironfish-rust-wasm && cargo test`
N/A
N/A

WASM: add bindings for the primitive types

---

ironfish-cli/src/commands/wallet/transactions/index.ts

This adds a new output transfers which uses the same column as notes but excludes change notes and makes it the default.
- `ironfish wallet:transactions --format notes`
- `ironfish wallet:transactions --format transfers`
- `ironfish wallet:transactions --format transactions`
- `ironfish wallet:transactions`
```
[ ] Yes
```
```
[ ] Yes
```

Add a new output 'transfers' and make it default

---

Cargo.lock
ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/keys/mod.rs
ironfish-rust-wasm/src/keys/public_address.rs
ironfish-rust-wasm/src/lib.rs
ironfish-rust/src/keys/public_address.rs

This commit exposes the `PublicAddress` struct to the WASM layer.
* `cd ironfish-rust-wasm && cargo build`
* `cd ironfish-rust-wasm && cargo test`
N/A
N/A

WASM: add bindings for `PublicAddress`

---

Cargo.lock
ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/keys/public_address.rs
ironfish-rust-wasm/src/lib.rs
supply-chain/audits.toml
supply-chain/imports.lock

The unit tests currently are marked with both `#[test]` and `#[wasm_bindgen_test]`. This allows tests to run with both `cargo test` and `wasm-pack test`.
In theory, we could drop `#[test]`, but given that `cargo test` is faster than `wasm-pack test`, this makes developing easier, so I'm keeping it for now.
One or more of the following:
* `cd ironfish-rust-wasm && wasm-pack test --firefox --headless`
* `cd ironfish-rust-wasm && wasm-pack test --chrome --headless`
* `cd ironfish-rust-wasm && wasm-pack test --safari --headless`
`--headless` is not required (it makes the output appear on the terminal instead of in the browser)
N/A
N/A

WASM: enable in-browser tests through `wasm-bindgen-test`

---

.github/workflows/rust_ci.yml
ironfish-rust-wasm/src/errors.rs
ironfish-rust-wasm/src/primitives.rs

* Expanded the license header check to include the wasm crate (and fixed the files that did not have the header)
* Added a workflow to run the wasm tests in Chrome and Firefox
Example run: https://github.com/iron-fish/ironfish/actions/runs/11809229845/job/32899173267?pr=5647
N/A
N/A

Run tests on the WASM package as part of the GitHub workflow

---

ironfish-cli/src/commands/wallet/transactions/index.ts
ironfish-cli/src/ui/table.ts
ironfish-cli/src/utils/table.ts

This clarifies the names and keeps them consistent with the table naming.
```
[ ] Yes
```
```
[ ] Yes
```

Rename Format -> TableOutput and output -> Format

---

ironfish-cli/src/commands/wallet/transactions/index.ts

This lets you filter dates based on a date input such as 04/20/2023
```
ironfish wallet:transactions --no-account --filter.start 09/1/2024 --filter.end 10/01/2024
```
```
[ ] Yes
```
```
[ ] Yes
```

Add filter start and end support

---

ironfish/src/rpc/routes/wallet/importAccount.test.ts
ironfish/src/rpc/routes/wallet/importAccount.ts
ironfish/src/wallet/exporter/account.ts
ironfish/src/wallet/exporter/encoder.ts

adds a field to the wallet/importAccount RPC that allows clients to specify the format of the account (Base64Json, JSON, Mnemonic, or SpendingKey)
if format is specified in the request then the decoding is only attempted for the specified format
results in more specific error messages instead of an error message containing the errors for each encoder
```
[X] Yes
```
https://github.com/iron-fish/website/pull/755
```
[ ] Yes
```

adds 'format' option to account import

---

ironfish-rust-wasm/src/assets.rs
ironfish-rust-wasm/src/keys/mod.rs
ironfish-rust-wasm/src/lib.rs
ironfish-rust/src/assets/asset.rs

Added bindings for two new types: `Asset` and `AssetIdentifier` 
Unit tests
N/A
N/A

WASM: expose the `Asset` and `AssetIdentifier` types

---

ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/merkle_note.rs
ironfish-rust/src/merkle_note.rs

Added bindings for two new types: `MerkleNote` and `MerkleNoteHash`
Unit tests
N/A
N/A

WASM: expose the `MerkleNote` and `MerkleNoteHash` types

---

ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/transaction/burns.rs
ironfish-rust-wasm/src/transaction/mints.rs
ironfish-rust-wasm/src/transaction/mod.rs
ironfish-rust-wasm/src/transaction/outputs.rs
ironfish-rust-wasm/src/transaction/spends.rs
ironfish-rust/src/transaction/burns.rs
ironfish-rust/src/transaction/outputs.rs

Added bindings for `SpendDescription`, `OutputDescription`, `MintDescription`, and `BurnDescription`
Tests for these types will be added as part of a more general transaction test (once the `Transaction` bindings are added).
N/A
N/A

WASM: expose the transaction description types

---

ironfish-cli/src/commands/wallet/burn.ts

Allows the user to use a ledger device to sign the burn transaction.
```
[ ] Yes
```
```
[ ] Yes
```

adds ledger flag to burn command

---

ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ui/ledger.ts

as of v1.1.0 of the Ironfish Ledger app expert mode must be required to review a transaction that sends custom assets
defines the error code for the new export mode error
stops polling the Ledger app when an expert mode error is thrown so that the user can navigate to the expert mode screen and enable expert mode before continuing
Closes IFL-3148
with expert mode set to `disabled`, run `wallet:mint --ledger --transferTo <other_address>` to send a transaction with a custom asset as an output note
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below on why …

handles expert mode required error in ledger ui

---

ironfish-cli/src/commands/wallet/transactions/sign.ts

the 'ledger' function from the ui module handles a variety of errors from the ledger app. using the ui function to wrap the app interactions improves user experience over calling the ledger sign method directly
Closes IFL-3149
1. create an unsigned transaction from a ledger account using `wallet:send --unsignedTransaction`
2. checkout the staging branch
3. without connecting your ledger, use `wallet:transactions:sign` to attempt to sign the transaction and observer that the command crashes with an error
4. checkout this branch
5. repeat step 3 but observe that the command catches the error and instructs you to connect and unlock your ledger
Reference](https://ironfish.network/docs/onboarding/rpc/chain))? If yes, …

updates sign command to use ui.ledger for ledger signing

---

ironfish/src/wallet/scanner/__fixtures__/walletScanner.test.ts.fixture
ironfish/src/wallet/scanner/walletScanner.test.ts
ironfish/src/wallet/scanner/walletScanner.ts
ironfish/src/wallet/wallet.ts

When an account has the following 
createdAt: 10
head: null
the wallet scanner should not take any action on this account until it reaches block 10. Currently the wallet scanner will still connect blocks 1-10 (without decrypting transactions) but it still takes some time and it doesn't provide any value over just connecting block 10 directly
Unit tests + running local wallet tests
```
[ ] Yes
```
```
[ ] Yes
```

WalletScanner skips accounts with createdAt until createdAt sequence is reached

---

ironfish-rust-wasm/Cargo.toml

Make it so that `ironfish-wasm` and `ironfish` have the same set of toggleable features, and the same defaults.
Unit tests
In the future, I might add a GitHub Actions test that builds all feature combinations, based on https://github.com/frewsxcv/cargo-all-features
N/A
N/A

Expose the ironfish crate features in the wasm crate

---

ironfish-rust-wasm/src/assets.rs
ironfish-rust-wasm/src/keys/public_address.rs
ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/merkle_note.rs
ironfish-rust-wasm/src/primitives.rs
ironfish-rust-wasm/src/transaction/burns.rs
ironfish-rust-wasm/src/transaction/mints.rs
ironfish-rust-wasm/src/transaction/mod.rs
ironfish-rust-wasm/src/transaction/outputs.rs
ironfish-rust-wasm/src/transaction/spends.rs

This reduces the amount of repeated code. Also, it adds some conversions that were previously not implemented.
Unit tests
N/A
N/A

WASM: use a macro to simplify the definition of binding types

---

ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts

the ui.ledger function includes error handling and retry logic that will be helpful when signing multisig transactions using the dkg ledger app
Closes IFL-3153
manual testing signing transaction with ledger dkg app
```
[ ] Yes
```
```
[ ] Yes
```

upgrades multisig signing commands to use ui.ledger

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/participant/create.ts

the ui.ledger function includes error handling and retry logic that could be useful in each of the standalone dkg commands ('participant:create', 'dkg:round1', 'dkg:round2', and 'dkg:round3')
Closes IFL-3152
created ledger multisig account using separate cli command flow
```
[ ] Yes
```
```
[ ] Yes
```

converts dkg commands to use ui.ledger

---

ironfish-cli/src/ledger/ledger.ts
ironfish-cli/src/ui/ledger.ts

if a user attempts to sign a transaction, but their ledger app doesn't have any multisig keys persisted, then the signing operation will fail with an 'invalid dkg status' error. this can happen if the user reinstalls the app or if the user starts creating a new account on the device using bkg, but doesn't finish
the only ways to recover from this error are to restore an encrypted backup to the device, or to create a new multisig account using the device. since the error shows up during signing, we can infer that the user expects to have an account on the device and should be instructed to restore the backup
Closes IFL-3151
1. create multisig ledger account
2. create a transaction to sign using the multisig account(s)
3. reinstall the ironfish dkg app to clear the account …

handles Ledger 'invalid dkg status' errors

---

ironfish/src/wallet/wallet.ts

Practically this doesn't fix any issues since we don't ever use `decryptNotes` to decrypt notes for spender, but currently the `decryptForSpender` flag is ignored, so this change fixes the flag to pass it through to the decryptNotes worker pool task.
```
[ ] Yes
```
```
[ ] Yes
```

Pass through decryptForSpender flag to note decryption

---

ironfish-rust/src/merkle_note.rs
ironfish-rust/src/transaction/proposed.rs
ironfish-rust/src/transaction/spends.rs

Dynamic dispatch has a small runtime overhead, hence removing it.
Unit tests
N/A
This change should be 100% backward-compatible as it makes the inputs to some functions more generic.

Rust: remove unnecessary uses of dynamic dispatch

---

.github/workflows/build-ironfish-rust-nodejs.yml
.github/workflows/check-pr-branch.yml
.github/workflows/ci-regenerate-fixtures.yml
.github/workflows/ci.yml
.github/workflows/deploy-node-docker-image.yml
.github/workflows/deploy-npm-ironfish-cli.yml
.github/workflows/deploy-npm-ironfish-rust-nodejs.yml
.github/workflows/deploy-npm-ironfish.yml
.github/workflows/push-version-to-api.yml
.github/workflows/rust_ci.yml
.github/workflows/rust_ci_cache.yml

ubuntu-latest is switching to default to Ubuntu 24 soon: https://github.blog/changelog/2024-11-05-notice-of-breaking-changes-for-github-actions/ I think it's not likely to cause any problems, but for now we can opt out of the update by fixing the version.
I created an issue for upgrading versions later: https://linear.app/if-labs/issue/IFL-3158/upgrade-github-actions-from-ubuntu-2204-to-ubuntu-2404
```
[ ] Yes
```
```
[ ] Yes
```

Switch from ubuntu-latest to ubuntu-22.04

---

ironfish-cli/src/ui/ledger.ts

if a user rejects an action on their Ledger, the command will now ~exit~ ask the user to retry instead of automatically retrying and prompting the user again to approve the action
before:
after:
```
[ ] Yes
```
```
[ ] Yes
```

optionally retries in cli commands if user rejects Ledger request

---

ironfish-rust/src/mining/thread.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/spends.rs
ironfish-zkp/src/circuits/util.rs

These are qualifications that rust 1.76 (specified in `rust-toolchain.toml` does not detect, but the latest version of Rust detects and warns about.
* Unit tests
* Run `cargo build` with the latest version of the Rust toolchain and verify that no warnings are produced
N/A
N/A

Remove unnecessary qualifications from Rust code

---

ironfish-rust-wasm/src/keys/mod.rs
ironfish-rust-wasm/src/keys/proof_generation_key.rs
ironfish-rust-wasm/src/keys/sapling_key.rs
ironfish-rust-wasm/src/keys/view_keys.rs
ironfish-rust-wasm/src/primitives.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-zkp/src/primitives/proof_generation_key.rs

This exposes all the functionality of the Sapling keys, except for the `toWords` and `fromWords`, which have not been implemented because they require bindings for the "language" enum (this will be added in a future PR).
Unit tests
N/A
N/A

WASM: add bindings for the Sapling keys

---

ironfish-rust-wasm/src/assets.rs
ironfish-rust-wasm/src/keys/mod.rs
ironfish-rust-wasm/src/keys/proof_generation_key.rs
ironfish-rust-wasm/src/keys/sapling_key.rs
ironfish-rust-wasm/src/keys/view_keys.rs
ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/merkle_note.rs
ironfish-rust-wasm/src/note.rs
ironfish-rust-wasm/src/primitives.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/view_keys.rs
ironfish-rust/src/note.rs
ironfish-zkp/src/primitives/proof_generation_key.rs

WASM: add decryption methods to MerkleNote

---

ironfish-rust-wasm/src/transaction/mints.rs
ironfish-rust-wasm/src/transaction/mod.rs
ironfish-rust-wasm/src/transaction/spends.rs
ironfish-rust-wasm/src/transaction/unsigned.rs
ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/spends.rs
ironfish-rust/src/transaction/unsigned.rs

Also add bindings to generate transaction signatures
Unit tests
N/A
N/A

WASM: add bindings for unsigned transactions and descriptions

---

ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/merkle_note.rs
ironfish-rust-wasm/src/note.rs
ironfish-rust/src/note.rs

WASM: add bindings for `Note`

---

ironfish/src/wallet/wallet.test.slow.ts

adds a test case to wallet slow tests to serve as an example for how to build a test transaction and sign it using the JavaScript SDK
useful for integrations that require testing transaction signing (e.g., Ledger integration) without running a network and/or building a chain
```
[ ] Yes
```
```
[ ] Yes
```

adds a single signer transaction signing test

---

ironfish/src/primitives/rawTransaction.test.slow.ts
ironfish/src/primitives/rawTransaction.test.ts
ironfish/src/primitives/rawTransaction.ts
ironfish/src/wallet/wallet.ts

the publicAddress passed to postedSize is not used
```
[ ] Yes
```
```
[ ] Yes
```

removes unused argument from RawTransaction.postedSize

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

compares the estimated postedSize of the raw transaction to the maximum transaction size computed by the verifier
throws a new error type, MaxTransactionSizeError, if the proposed transaction is too big
```
[ ] Yes
```
```
[ ] Yes
```

throws error in createTransaction if tx is too big

---

ironfish-cli/src/commands/wallet/transactions/sign.ts

changes the 'wallet:transactions:sign' command to render the details of the unsigned transaction before signing the transaction
this gives the user a chance to see the transaction details on the CLI before signing the transaction
manual testing
```
[ ] Yes
```
```
[ ] Yes
```

displays tx details before signing in 'wallet:sign'

---

ironfish-rust/src/test_util.rs

- Removed a `buffer` that was not used
- Removed calls to `clone()` that are unnecessary (because read-only references are passed around)
Unit tests
N/A
N/A

Remove unused/unnecessary code from `ironfish::test_utils`

---

ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture
ironfish/src/wallet/errors.ts
ironfish/src/wallet/wallet.test.ts
ironfish/src/wallet/wallet.ts

keeps track of the posted size of a raw transaction in 'fund' and updates the size after each spend is added to the raw transaction
throws an error if and when the posted size of the transaction will exceed the maximum transaction size
inlines the logic of 'addSpendsForAsset' to avoid having to plumb posted size and max transaction size down to that method
defines the constructor and error message for MaxTransactionSizeError
- updates existing unit test
```
[ ] Yes
``` …

checks max transaction size while funding transaction

---

ironfish-cli/src/commands/wallet/ledger/address.ts
ironfish-cli/src/ledger/ledgerSingleSigner.ts

CLI command that displays the wallet address of the connected Ledger device.
```
[ ] Yes
```
```
[ ] Yes
```

wallet:ledger:address CLI command

---

ironfish-cli/src/utils/chainport/requests.ts

Previously the API wasn't passing through Chainport error messages on the response. Now that it does, we update the response parsing to pull out the error messages if they exist.
Tested by manually modifying the command to send known bad parameters:
```
? Enter the public address of the recipient: <omitted>
Fetching bridgeable assets... done
? Select the asset you wish to send 51f33a2f14f92735e562dc658a5639279ddca3d5079a6d1242b2a588a9cbf44c ($IRON✓) (<omitted>)
Fetching available networks... done
? Select the network you would like to bridge IRON to Base
? Enter the amount in $IRON✓ (balance <omitted>): 1
Error: Chainport error: Amount too big
at <anonymous> (/Users/derek/repos/ironfish/ironfish-cli/src/utils/chainport/requests.ts:81:15)
at process.processTicksAndRejections …
```

Pass through Chainport error messages from API

---

ironfish/src/rpc/routes/wallet/__fixtures__/getAccountTransactions.test.ts.fixture
ironfish/src/rpc/routes/wallet/getAccountTransactions.test.ts
ironfish/src/rpc/routes/wallet/getAccountTransactions.ts
ironfish/src/wallet/account/account.ts

adds optional startSequence and endSequence request parameters to the 'wallet/getAccountTransactions' RPC to support fetching transactions by a range of block sequences (inclusive)
if startSequence is set but not endSequence, then all the maximum 32-bit integer value is used for endSequence
if endSequence is set but not startSequence, then the genesis block sequence (1) is used for startSequence
adds unit test
```
[X] Yes
```
```
[ ] Yes
```

adds support for fetching account tx by range

---

ironfish-rust-wasm/src/lib.rs
ironfish-rust-wasm/src/witness.rs
ironfish-rust/src/witness.rs

This is a pre-requisite for SpendBuilder
Unit tests
N/A
N/A

WASM: add bindings for `Witness`

---

ironfish-rust-wasm/src/keys/view_keys.rs
ironfish-rust-wasm/src/primitives.rs

This is needed to ease the creation of transactions, as well as ease testing.
Future PRs will include tests that use these methods.
N/A
N/A

WASM: add methods to create randomized keys

---

ironfish-rust-wasm/src/keys/public_address.rs

Added methods to convert a hex string to a `PublicAddress`, as well as a method to check if a hex string is a valid address.
Removed the `bytes()` method, which is redundant and does the same job as `serialize()`.
* Unit tests
N/A
N/A

WASM: add convenience methods to `PublicAddress` to work with hex

---

Cargo.lock
ironfish-rust-nodejs/src/lib.rs
ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/keys/mnemonics.rs
ironfish-rust-wasm/src/keys/mod.rs
ironfish-rust-wasm/src/keys/sapling_key.rs
ironfish-rust-wasm/src/keys/view_keys.rs
ironfish-rust/src/keys/mod.rs
ironfish-rust/src/keys/test.rs
ironfish-rust/src/keys/view_keys.rs

Added methods to convert keys to/from mnemonic words.
Limited unit tests (more, better tests may be added in a future PR)
N/A
N/A

WASM: add support for mnemonics

---

ironfish-cli/src/commands/wallet/unlock.ts
ironfish/src/utils/time.test.ts
ironfish/src/utils/time.ts

Added years, months, and days to renderSpan
Estimated years to 365 days and months to 30 days.
Lock and unlock a wallet with flags for various time intervals.
Confirmed it returns the highest 2 time units (year & month, month & day, etc.)
N/A
N/A

renderSpan: add more time intervals

---

ironfish-cli/src/ui/table.ts

I don't think the default needs to be this low.
```
[ ] Yes
```
```
[ ] Yes
```

Increase table default limit to 500 rows

---

ironfish-cli/src/ui/table.ts

This output would not print because of the inversed sign introduced in https://github.com/iron-fish/ironfish/pull/5611/files#diff-03f7c44b5cd857fe07731018037071afdb7710680236763c818fda56e8340825R219
1. Create 3 accounts
2. Use `ironfish wallet --limit 1`
3. See that message does not print before, but does after
```
[ ] Yes
```
```
[ ] Yes
```

Fix warning that table is being truncated

---

ironfish-cli/src/ledger/ledgerMultiSigner.ts
ironfish-cli/src/ledger/ledgerSingleSigner.ts

Saw this in another PR. This will help avoid issues if the ledger SDK changes,
No testing necessary, this is just making implicit types explicit.
```
[ ] Yes
```
```
[ ] Yes
```

Add specific types to ledger functions

---

Cargo.lock
ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/primitives.rs

This is the last bit remaining to support Oreowallet
* Unit tests
N/A
N/A

WASM: add bindings for `Proof`

---

ironfish/src/wallet/exporter/encoders/base64json.test.ts
ironfish/src/wallet/exporter/encoders/bech32.test.ts
ironfish/src/wallet/exporter/encoders/bech32json.test.ts
ironfish/src/wallet/exporter/encoders/json.test.ts
ironfish/src/wallet/exporter/encoders/mnemonic.test.ts
ironfish/src/wallet/exporter/encoders/spendingKey.test.ts

This improves the reliability of these tests by ensuring they are receiving the errors they are actually looking for. Without these checks, the code could begin throwing an unrelated error and the unit tests would not catch it.
These changes are specifically to unit tests, so they should still pass.
N/A
N/A

Encoder tests now look for specific errors

---

ironfish/src/wallet/account/account.test.ts

Original test was lexicographically sorting the hashed transactions, which could misorder the transactions based on their string representations. Added in sorting based on the buffer compare method to compare the bytes
Deleted and regenerated account.test.fixture and reran test 10 times.
Staging - failed
account.test - 10/10 passed
No
No

account.test - getTransactionsByTime: added buffer comparison to sort

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts

when running DKG using a Ledger device, the user's identity must match the identity from the Ledger device.
rather than reading an identity from the node based on a name we can read the identity directly from the Ledger.
reads identity from Ledger in 'wallet:multisig:dkg:round1' and 'wallet:multisig:dkg:create' instead of reading the identity from the node
- created multisig account using ledger
```
[ ] Yes
```
```
[ ] Yes
```

reads identity from ledger in dkg round1

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts
ironfish-cli/src/commands/wallet/multisig/participant/create.ts

sets hidden to false for a few commands that still had the ledger flag hidden
```
[ ] Yes
```
```
[ ] Yes
```

unhides remaining ledger flags

---

ironfish-cli/src/commands/wallet/multisig/participant/index.ts

supports reading identity from ledger and displaying on CLI
- run `ironfish wallet:multisig:participant --ledger`
```
[ ] Yes
```
```
[ ] Yes
```

adds ledger flag to 'wallet:multisig:participant'

---

ironfish-cli/src/commands/wallet/multisig/signature/create.ts

when a user passes the '--ledger' flag to the
'wallet:multisig:signature:create' command they intend to use a Ledger device to create a signature share. the identity used _must_ be the identity from the Ledger device, so read the identity from the device instead of from the walletDB
Closes IFL-3172
1. start devnet node
2. mine devnet blocks
3. create multisig account using ledger
4. fund multisig account with transaction from default account
5. create unsigned transaction from multisig account
6. create signing commitment with multisig account and ledger
7. create signature share with multisig account and ledger
related documentation …

reads identity from ledger in 'wallet:multisig:signature:create'

---

ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/LICENSE
ironfish-rust-wasm/README.md

Add package description to Cargo.toml and create README.md to improve documentation and NPM package visibility. The README includes:
- Usage examples with TypeScript
- Links to documentation and support
```
[ ] Yes
```
```
[ ] Yes
```

wasm docs: package description License and README

---

ironfish-cli/src/commands/wallet/multisig/sign.ts
ironfish-cli/src/ui/prompts.ts

uses 'wallet/getAccounts' RPC to fetch the list of all account names
next uses 'wallet/multisig/getAccountIdentity' to filter accounts that are not multisig accounts (if an account is not a multisig account then it will not have an identity)
replaces 'accountPrompt' prompt with 'multisigAccountPrompt' in 'wallet:multisig:sign' command
- run `wallet:multisig:sign` on a node that has a mix of multisig and single-signer accounts and observe that the prompt only includes the multisig accounts
```
[ ] Yes
``` …

creates ui prompt to select multisig account

---

.github/workflows/deploy-npm-ironfish-rust-wasm.yml

Adds GitHub Actions workflow to build, test and publish the ironfish-rust-wasm package to npm. Includes Firefox and Chrome headless testing and supports dry-run mode for validation before actual publishing.
Successful run: https://github.com/iron-fish/ironfish/actions/runs/13186387340/job/36809353086
```
[ ] Yes
```
```
[ ] Yes
```

ci: Publish Rust WASM package to npm

---

.github/workflows/deploy-npm-ironfish-rust-wasm.yml

This has the effect of creating the package.json with a different package name.
Without the flag: "name": "ironfish-wasm",
With the flag:    "name": "@ironfish/ironfish-wasm",
```
[ ] Yes
```
```
[ ] Yes
```

Adds scope flag to wasm github action

---

ironfish-rust-wasm/src/keys/mnemonics.rs

The current implementation makes `Language` a "string enum", however such enums do not get properly translated to Javascript/Typescript, in the sense that on the JS/TS side you cannot write `Language.English`, but you must write `"en"`.
This PR changes `Language` to be a regular enum instead, so that the code on the JS/TS side is more clear, and in particular type-checking can find invalid enum values.
Unit tests

WASM: change `Language` to be a proper TypeScript enum

---

ironfish-rust-wasm/src/keys/public_address.rs

This is for consistency with other structs.
```
[ ] Yes
```
```
[ ] Yes
```

WASM: change the `PublicAddress.hex` getter to `PublicAddress.toHex()`

---

ironfish-rust-wasm/src/keys/sapling_key.rs
ironfish-rust/src/keys/mod.rs

These are needed to create proofs, like Oreowallet does.
```
[ ] Yes
```
```
[ ] Yes
```

WASM: expose authorizing keys from `SaplingKey`

---

ironfish-rust-wasm/src/keys/view_keys.rs

This method returns a struct which also has a `randomized_public_key` method, which results in code like this:
```rs
let r = x.randomized_public_key();
let p = r.randomized_public_key();
```
... which is very ambiguous/confusing. With this PR, the above code becomes:
```rs
let r = x.randomized_public_key_pair();
let p = r.randomized_public_key();
```
```
[ ] Yes
```
```
[ ] Yes
```

WASM: rename `randomized_public_key` to `randomized_public_key_pair`

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts

when running DKG using a Ledger device we must use the identity from the Ledger
reads the identity from the Ledger device during DKG round3 instead of from the walletDB when using the '--ledger' flag in 'wallet:multisig:dkg:create' and 'wallet:multisig:dkg:round3'
Closes IFL-3170
Closes IFL-3171
- create multisig account using `wallet:multisig:dkg:create`
- create multisig account using separate dkg commands:
- `wallet:multisig:participant:create`
- `wallet:multisig:dkg:round1`
- `wallet:multisig:dkg:round2`
- `wallet:multisig:dkg:round3`
```
[ ] Yes
``` …

reads identity from Ledger in DKG round3

---

ironfish-cli/src/commands/wallet/multisig/commitment/create.ts
ironfish-cli/src/commands/wallet/multisig/signature/create.ts

replaces 'multisigSecretPrompt' with 'multisigAccountPrompt' in 'wallet:multisig:commitment:create' and 'wallet:multisig:signature:create'.
renames 'participantName' variable to 'accountName' since this refers to the name of an imported account
Closes IFL-3174
Closes IFL-3175
run both commands using a node that has both multisig and single-signer accounts and observe that the prompt only shows the multisig accounts
```
[ ] Yes
```
```
[ ] Yes …
```

uses multisigAccountPrompt in signing commands

---

ironfish-cli/src/commands/wallet/multisig/sign.ts

instead of fetching the list of all identities for an account and comparing it to the list of all identities stored in the walletDB we can now directly query for the account's identity using the 'wallet/multisig/getAccountIdentity' RPC
minor refactoring to pass identity instead of MultisigParticipant interface since downstream functions only need the identity
Closes IFL-3173
- create multisig account
- fund account with transaction
- create unsigned transaction to sign
- use 'wallet:multisig:sign' to sign transaction
```
[ ] Yes
```
Is this a breaking change? If yes, add notes below …

uses 'getAccountIdentity' to determine identity in multisig sign

---

ironfish-rust/src/transaction/mints.rs
ironfish-rust/src/transaction/outputs.rs
ironfish-rust/src/transaction/proposed.rs
ironfish-rust/src/transaction/spends.rs

Needed by Oreowallet.
```
[ ] Yes
```
```
[ ] Yes
```

Add methods to ProposedTransaction and description builders to build zk circuits

---

ironfish-cli/src/commands/wallet/multisig/dkg/create.ts

we don't need to import the identity from the Ledger device into the walletDB unless and until we finish creating the account.
removes the call to 'wallet/multisig/importParticipant' in 'wallet:multisig:dkg:create' command
Closes IFL-3164
- run `wallet:multisig:dkg:create` with and without the `--ledger` flag
```
[ ] Yes
```
```
[ ] Yes
```

does not import ledger identity in 'wallet:multisig:dkg:create'

---

ironfish-cli/src/commands/wallet/multisig/participant/create.ts

there is no longer a need to "create" the participant identity from the Ledger device by importing it into the walletDB since our CLI commands now read the identity directly from the Ledger when needed
removes the '--ledger' flag from the command and thereby removes the call to importParticipant
Closes IFL-3168
run `ironfish wallet:multisig:participant:create --ledger` and verify that it fails due to the nonexistent flag
```
[ ] Yes
```
```
[ ] …
```

removes ledger flag from 'wallet:multisig:participant:create'

---

ironfish-rust-wasm/src/primitives.rs

```
[ ] Yes
```
```
[ ] Yes
```

WASM: add bindings for `Scalar.zero()` and `Fr.from_bytes()`

---

ironfish/src/rpc/routes/wallet/getAccountTransactions.test.ts

Removed the sort for the accountTransactions since it is already received in order. I regenerated the fixtures and the random hash lexographically sorted ended up swapping the order of the transactions.
I regenerated fixtures without sort and test passed
N/A
N/A

getAccountsTransactions.test: Removed sort from streams back transactions for a given block sequence range

---

ironfish-rust-wasm/src/witness.rs

This provides better type safety.
Also fixed the exported names to follow JS conventions.
```
[ ] Yes
```
```
[ ] Yes
```

WASM: change `Witness` to use `MerkleNoteHash` instead of `Scalar`

---

ironfish-rust-wasm/Cargo.toml
ironfish-rust-wasm/src/transaction/mints.rs
ironfish-rust-wasm/src/transaction/mod.rs
ironfish-rust-wasm/src/transaction/spends.rs

These are feature-gated and disabled by default because they do not work in a web environment. In order to work, users need to patch `yastl` so that it runs tasks serially rather than in parallel (because there's no support for threads in a web environment). Also, even after patching, generating a zero-knowledge proof currently takes an absurd amount of time in a web browser.
```
cargo test --all-features
```
```
[ ] Yes
```
```
[ ] Yes
```

Implement spend and mint description builders

---

ironfish-rust-wasm/src/transaction/mod.rs
ironfish-rust/Cargo.toml

```
[ ] Yes
```
```
[ ] Yes
```

Fix `cargo clippy` errors generated when `transaction-proofs` is off

---

ironfish-cli/src/commands/wallet/multisig/dkg/round1.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round2.ts
ironfish-cli/src/commands/wallet/multisig/dkg/round3.ts

when using a ledger device the user should not need to enter a participant name or select the participant from those in the walletDB since the identity should be read from the ledger device
prompts the user for an account name in round3 if using a ledger
Closes IFL-3176
used dkg rounds 1,2, and 3 to create a multisig account. used two participants on one node, one with a ledger
```
[ ] Yes
```
```
[ ] Yes
```

makes participantName and ledger flags exclusive in dkg

---

ironfish/src/rpc/routes/chain/exportChainStream.test.ts
ironfish/src/rpc/routes/chain/exportChainStream.ts
ironfish/src/rpc/routes/chain/serializers.ts
ironfish/src/rpc/routes/chain/types.ts

Removed deprecated seq and prev properties from exportChainStream.
Updated to sequence and previousBlockHash
Successfully exportedChainStream after change
```
[X] Yes - https://github.com/iron-fish/website/pull/774/files
```
```
[X] Yes, this removes backward compatibility for seq and previous
```

exportChainStream: removed seq and prev from block and tests

---

ironfish/src/rpc/routes/wallet/getBalance.test.ts
ironfish/src/rpc/routes/wallet/getBalance.ts

Removed assetVerification reference from getBalance route and tests
we're using getAsset endpoint instead now.
```
[X] Yes - https://github.com/iron-fish/website/pull/780
```
```
[X] Yes - breaking-change-rpc
```

getBalance: removed assetVerification

---

ironfish/src/rpc/routes/wallet/getBalances.test.ts
ironfish/src/rpc/routes/wallet/getBalances.ts

removed assetVerification, assetName, assetCreator, assetOwner from getBalances, schema, tests since we are now using getAsset endpoint for that info.
```
[X] Yes - https://github.com/iron-fish/website/pull/781
```
```
[X] Yes - breaking-change-rpc
```

getBalances: removed assetVerification, assetName, assetCreator, assetOwner 

---

ironfish-cli/Dockerfile

This pins the rust version to our current toolchain of 1.76.0 because the sh.rustup.rs script automatically installs stable. This means if stable drifts from our toolchain version it will automatically start failing new builds.
Just run `RUN curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain=1.76.0` with different versions, or excluded.
```
[ ] Yes
```
```
[ ] Yes
```

Fix docker builds by pinning rust toolchain
