iron-fish/ironfish

README.md
Adds a header image to the README file.
=> Add header image to README

.github/workflows/deploy-node-aws.yml
The secrets were old repo secrets which became unavaiable once the repo
moved.
=> Fix github actions in new repo

ironfish/src/network/peers/peerConnectionManager.ts
This will try to reduce connections even if we hit our max connection  attempt per loop .
=> Still try to reduce connections 

ironfish-cli/Dockerfile, ironfish-cli/src/commands/backup.ts
This new command will tar your data folder and upload to a specified S3
bucket. It's a hidden command because we're using it to test during test
net, and isn't really intended to be used by end users. It requires
'tar' and 'curl' programs to be installed on your computer.
=> Add backup command

ironfish/src/rpc/routes/chain/getBlock.ts
Added braces around if statements to make this more organized and
consistent in its own usage of if braces.
=> Small code formatting cleanup

ironfish-cli/src/commands/chain/genesisblock.ts, ironfish-cli/src/commands/start.test.ts, ironfish-cli/src/commands/start.ts, ironfish/src/account/accounts.test.slow.ts, ironfish/src/account/accounts.test.ts, ironfish/src/account/accounts.ts, ironfish/src/blockSyncer.test.ts, ironfish/src/blockchain/blockchain.test.perf.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/captain/captain.ts, ironfish/src/captain/testUtilities/helpers/anchorChain.ts, ironfish/src/genesis/genesis.test.slow.ts, ironfish/src/genesis/makeGenesisBlock.ts, ironfish/src/mining/director.test.slow.ts, ironfish/src/node.ts, ironfish/src/rpc/routes/accounts/importAccount.ts, ironfish/src/rpc/routes/accounts/rescanAccount.ts, ironfish/src/rpc/routes/chain/getBlock.test.ts, ironfish/src/rpc/routes/chain/getBlock.ts, ironfish/src/rpc/routes/chain/getBlockInfo.ts, ironfish/src/rpc/routes/chain/getChain.ts, ironfish/src/rpc/routes/chain/getChainInfo.test.ts, ironfish/src/rpc/routes/chain/getChainInfo.ts, ironfish/src/rpc/routes/mining/newBlocksStream.ts, ironfish/src/rpc/routes/node/getStatus.ts, ironfish/src/rpc/routes/transactions/sendTransaction.test.ts, ironfish/src/rpc/routes/transactions/sendTransaction.ts, ironfish/src/testUtilities/nodeTest.ts
In preparation for removing captain completely. Look at each commit since github decided to auto merge my PR's into each other,
=> Remove many instances of captain

README.md
Removed outdated information, and simplified the readme as a whole a bit.
https://github.com/iron-fish/ironfish/blob/5e4cf299768f760c9d276c476d4b8772b276c1ff/README.md
=> Refactor root readme

README.md
Once something merges, the badge should display correct information now.
=> Update badge on readme for codecov

ironfish/src/blockchain/blockchain.ts, ironfish/src/genesis/genesis.test.slow.ts, ironfish/src/mining/director.test.slow.ts, ironfish/src/node.ts, ironfish/src/testUtilities/fake/helpers/blockchain.ts, ironfish/src/testUtilities/helpers/storage.ts
Before the DB was created outside and passed in, but were going to move
all the logic into a new BlockchainDB that's going to be constructed
inside of Blockchain. This helps make it isolated enough to make that
possible.
=> Create blockchain db inside of blockchain

ironfish/src/blockSyncer.ts, ironfish/src/blockchain/blockchain.ts
Cleaning the constructor of Blockchain up a little bit.
There's no code change, and I didn't want to mix these changes into a PR with real changes.
=> Improve blockchain code hygiene

ironfish/package.json, package.json, yarn.lock
Updates the Lerna and Typedoc dependencies to fix a few Dependabot alerts (though these are only used during development).
=> Update lerna and typedoc dependencies

ironfish-cli/package.json, ironfish/package.json, ironfish/src/network/peers/peer.test.ts, ironfish/src/network/peers/peerConnectionManager.test.ts, ironfish/src/network/peers/peerManager.test.ts, yarn.lock
Update some WebRTC-related packages to see if it either cuts down on the number of node-webrtc segfaults or improves the error logging for them.
=> Update WebRTC-related packages

.github/workflows/deploy-node-aws.yml, .github/workflows/deploy-node-github-beta.yml, ironfish-cli/scripts/deploy-docker.sh
Creating ironfish-beta docker package and github action script. This is so we can more easily test the staging branch.
=> Creating ironfish-beta docker package

ironfish/src/syncer.ts
This is a temporary measure because there is a bug in the graphs of the
chain where the graphs become disconnected. We shouldnt add orphans
anyway, since we are gutting that logic. It'll be deleted soon, but this
makes the chain graphs more stable by only adding non islands.
=> Don't add orphans when syncing blocks

ironfish/src/memPool/memPool.ts
Also removes a log of added transactions, since fetching the transaction fee ties up a worker and we're not actively using the log right now.
=> Switch MemPool to use BufferMap

ironfish/src/blockchain/blockchain.old.test.ts
There's no tests in this describe
=> Delete unused test describe

ironfish/src/account/accounts.ts
The `stop` command in `accounts` doesn't wait for the `updateHead` to finish before resolving, so it's possible that the node shutdown can continue to re-saving (and closing) the accounts database while updateHead is still running. I repurposed ScanState for this, maybe it could still be refactored better.
=> Wait for account updates to finish before shutting down

ironfish/src/blockchain/blockchain.test.ts, ironfish/src/blockchain/blockchain.ts
Just beefs up the tests a little bit for the new stuff, including a new helper function
=> Add more testing for new block chain add

ironfish/src/blockchain/blockchain.test.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/blockchain/schema.ts
This table is used to store the heaviest head chain BlockHash -> BlockHash
=> Add new hash to next table

.github/workflows/ci.yml, .github/workflows/rust_ci.yml
This should help pull request actions actually run
=> Set github actions to pull request

ironfish/src/syncer.test.ts, ironfish/src/syncer.ts, ironfish/src/testUtilities/matchers/buffer.ts, ironfish/src/testUtilities/matchers/index.ts
There was no test that tested paginated syncing, this will test that it
requests 4 pages of 1 block each.
=> Add syncer test for paginated syncing

ironfish/src/blockchain/blockchain.ts, ironfish/src/metrics/meter.ts, ironfish/src/node.ts, ironfish/src/primitives/transaction.ts, ironfish/src/rpc/routes/node/getStatus.ts
We werent passing in the metric down into the peer network, and on top
of that the metrics meter was broken pre launch in commit 05ae5c6c74b3409a769589b1ccd822811090c165
=> Fix network traffic metrics

ironfish/src/syncer.ts
This should update the sequence in 2 cases... 
1. If they gossip a block we update their known sequence if it's higher. We don't update their work/ head because we don't know that it's their head since they could have added it to a fork.
2. If we sync from them we know its their head, so we update their peer info to this block if its later than their existing announced one
=> Update peer sequence in gossip / sync

ironfish-cli/scripts/run-network-macos.sh, ironfish/src/platform.ts
Shortened the agent to just if instead of ironfish so it doesn't get cut
off in our status command.
=> Shorten agent to if from ironfish

ironfish/src/blockchain/blockchain.old.test.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/mining/director.ts, ironfish/src/rpc/routes/chain/utils.ts, ironfish/src/syncer.ts, ironfish/src/testUtilities/matchers/buffer.ts
=> Cleanup various logs and other things

ironfish-cli/src/commands/chain/export.ts, ironfish/src/blockchain/utils.ts, ironfish/src/metrics/meter.ts
Various commits needed for repair block command
=> Add prefixes for repair block command

ironfish/src/mining/director.test.slow.ts, ironfish/src/mining/director.ts
Adds two checks, along with tests:
* If adding the block to the chain fails, does not send the block out to the network
* If a block is successfully mined, checks that the new block's previous hash is equal to the chain's heaviest head, else discards the block.
=> Discard mined blocks if chain head changes or can't add block

ironfish/src/network/version.ts
In preparation for the next staging build.
=> Bump protocol version to 4

ironfish-graph-explorer/src/index.js
Blocks with no graffiti should be gray now
=> Color blocks with no graffiti as gray

ironfish/src/syncer.ts
Right now, when were orphan syncing, and any error occurs, it'll hit the
error handler inside of PeerNetwork, which is used to determine if
gossiping should happen. Ideally, as soon as it determines its an orphan
we should no longer gossip.
To do this, instead of awaiting syncOrphan()
we just use startSync() directly. syncOrphan was used to guarantee that
the peer had the orphan block to begin with, but we don't need to do
that anymore because we only gossip blocks that we add.
Note that once startSync is called, it takes over responsibility for handling errors for things like peer disconnection errors, etc.
=> Transfer ownership of orphan syncing to syncer

ironfish/src/syncer.ts
I think this is more straight forward, because I've seen people get confused over what this does.
=> Minor cleanup on abort readability

ironfish/src/network/peers/peerManager.test.ts, ironfish/src/network/peers/peerManager.ts
Disconnect messages can be forwarded through a brokering peer, so that when one peers requests connection to another via WebRTC, they don't have to finish establishing the connection before disconnecting from each other. However, the disconnect handler was always disconnecting from the message sender rather than the sourceIdentity on the message. E.g. If forwarding messages to another peer through the bootstrap node and the peer requests a disconnect, we would disconnect from the bootstrap node rather than the new peer.
=> Disconnect from the sourceIdentity on disconnect messages rather than the message sender

ironfish/src/network/version.ts
=> Bump network version to 5

ironfish/src/blockchain/blockchain.ts, ironfish/src/syncer.ts
Try some small fixes to debug the banning issue
=> Small fixes to blockchain

ironfish-cli/src/commands/chain/forks.ts, ironfish/src/rpc/clients/rpcClient.ts, ironfish/src/rpc/routes/events/index.ts, ironfish/src/rpc/routes/events/onGossip.ts, ironfish/src/rpc/routes/events/types.ts, ironfish/src/rpc/routes/events/utils.ts, ironfish/src/rpc/routes/index.ts, ironfish/src/rpc/routes/router.ts, ironfish/src/sdk.ts, ironfish/src/syncer.ts
This new command will listen to gossip blocks on the network to try to
parse out what forks exist without having to download them.
=> Add chain:forks command

ironfish/src/blockchain/blockchain.old.test.ts, ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture, ironfish/src/consensus/verifier.test.ts, ironfish/src/consensus/verifier.ts, ironfish/src/memPool/memPool.ts
* Add `VerificationResultReason.DOUBLE_SPEND` 
* Move tests over to `verifier.test.ts` and update to use fixtures instead of fake blocks
=> refactor(ironfish): Move `hasValidSpends` unit tests to `verifier.test.ts`

ironfish/src/blockchain/blockchain.ts
This seems to do the same thing as saveConnect with some DB writes pulled out elsewhere. If we're intending to differentiate these later, feel free to close this.
=> Remove saveReconnect from blockchain

ironfish/src/blockchain/blockchain.ts
Experimenting with ordering to see if it feels cleaner
=> Move state getters and setters

ironfish-cli/src/commands/chain/forks.ts
This feeks old forks around so that if someone ends up mining an old
fork, we still can measure the generations on it. We don't show these
old forks in our list though, they still get filtered out.
=> Keep old fork around in chain:forks command

ironfish/src/blockchain/blockchain.ts, ironfish/src/node.ts, ironfish/src/sdk.ts
This was old and isnt being used anymore because all the old fake tests
that used it are gone.
=> Remove loadGenesisBlock

ironfish-cli/src/commands/chain/export.ts
This allows you to pass negative numbers to export the last N blocks
from the end. If you pass -5 from start, on a chain with a head of
sequence 10, it will export blocks 6-10 (the last 5 blocks)
=> Support export starting from end of chain

ironfish-cli/src/commands/accounts/balance.ts
https://linear.app/ironfish/issue/IRO-727/change-description-of-accountsbalance-to-remove-export
=> Remove reference to export in balance

ironfish/src/rpc/routes/transactions/sendTransaction.test.ts, ironfish/src/rpc/routes/transactions/sendTransaction.ts
This code duplicated the new synced check, so I deleted the duplication.
=> Simplify payment synced requirement

ironfish-http-api-v2/.gitignore, ironfish-http-api-v2/docker-compose.sql, ironfish-http-api-v2/docker-compose.yml, ironfish-http-api-v2/package.json, ironfish-http-api-v2/prisma/schema.prisma, yarn.lock
Adding some setup for local development with Prisma and Postgres
=> feat(http-api): Install Prisma and add Docker Compose

.github/workflows/deploy-api-v2.yml
Deploy to staging every time a commit has been pushed to `beta`
=> feat(http-api): Add deploy script for staging API

ironfish-http-api-v2/Procfile, ironfish-http-api-v2/package.json
=> fix(http-api): Call prisma migrate during the release phase

ironfish-http-api-v2/prisma/migrations/20210709171941_create_events/migration.sql, ironfish-http-api-v2/prisma/schema.prisma
Add a migration to create a table to persist events for accounts.
=> feat(http-api): Create events table

.github/workflows/ci.yml, .github/workflows/deploy-api-v2.yml, ironfish-http-api-v2/.env.test, ironfish-http-api-v2/docker-compose.sql, ironfish-http-api-v2/package.json, ironfish-http-api-v2/prisma/schema.prisma, ironfish-http-api-v2/src/accounts/accounts.module.ts, ironfish-http-api-v2/src/accounts/accounts.service.test.ts, ironfish-http-api-v2/src/accounts/accounts.service.ts, ironfish-http-api-v2/src/app.module.ts, ironfish-http-api-v2/src/prisma/prisma.module.ts, ironfish-http-api-v2/src/prisma/prisma.service.ts, ironfish-http-api-v2/src/test/test-app.ts, ironfish-http-api-v2/tsconfig.json, yarn.lock
* Add NestJS modules and services for Prisma and Accounts
* Update names for Prisma run-time types
* Add Postgres container to Github actions for testing
=> feat(http-api): Create accounts service

ironfish-http-api-v2/Procfile
Re-generate the Prisma client types during the release phase
=> feat(api): Generate Prisma schema after running migrations

ironfish-http-api-v2/src/app.module.ts, ironfish-http-api-v2/src/events/events.module.ts, ironfish-http-api-v2/src/events/events.service.test.ts, ironfish-http-api-v2/src/events/events.service.ts, ironfish-http-api-v2/src/test/test-app.ts
Create a service to fetch events from the store
=> feat(api): Create service for events

ironfish-http-api-v2/src/accounts/accounts.controller.test.ts, ironfish-http-api-v2/src/accounts/accounts.controller.ts, ironfish-http-api-v2/src/accounts/accounts.module.ts, ironfish-http-api-v2/src/accounts/accounts.service.test.ts
=> feat(api): Create controller to fetch account

ironfish-cli/src/commands/backup.ts
There is an issue with the DB indexes getting corrupted when a backup
runs while the node is running. This forces it to wait for the database
to become free by default, and allows the passing of a new flag --lock
and --no-lock to change this default.
Examples
```bash
ironfish backup <BACKUP_ID> --lock
ironfish backup <BACKUP_ID> --no-lock
```
=> Wait for database lock before running backup

ironfish-cli/src/commands/backup.ts
Change export command to not backup accounts unless you explicitly pass
--accounts flag to it.
=> Make backup command not export accounts

ironfish-cli/src/commands/status.ts, ironfish/src/rpc/routes/node/getStatus.ts
This adds the current mem pool size to the get status command
https://linear.app/ironfish/issue/IRO-844/add-mem-pool-to-status-command
=> Add mempool status to status command

ironfish/src/primitives/__fixtures__/transaction.test.slow.ts.fixture, ironfish/src/primitives/transaction.test.slow.ts
Add a test to make sure miners fees don't have the same transaction
hash.
=> Add test for transaction hashes

ironfish-cli/src/commands/accounts/export.test.ts, ironfish-cli/src/commands/accounts/export.ts, ironfish/src/rpc/clients/ipcClient.ts, ironfish/src/utils/error.ts
Changelog
---
- Account information is now exported to a default filename if a directory is given as the export path.
=> IRO-1020: Fix Account Export Flow

ironfish-cli/src/commands/workers/status.ts, ironfish/src/rpc/routes/workers/getStatus.test.ts, ironfish/src/rpc/routes/workers/getStatus.ts
Add pool speed status to worker get status command
=> IRO-1111: Add pool speed status to workers info command

ironfish-cli/src/api.ts, ironfish-cli/src/commands/chain/sync.ts, ironfish/src/rpc/routes/chain/followChain.ts
Changelog
---
- Add block size to block type from sync process
- Add block size to API payload
- Add additional logging to clarify sync process
=> IRO-1122: Add Block Size to Block Sync Payload

ironfish/.eslintrc.js, ironfish/src/utils/graffiti.ts
=> IRO-1136: Update toHuman() to remove unicode control chars

ironfish-cli/Dockerfile
=> IRO-1137: Update node versions and remove debian testing repo

ironfish/src/network/version.ts
After our recent changes we want to know if these changes are going to
affect the network positively, so we're going to force people to
upgrade if possible to see what the effect is.
=> Bump network version and min version to 8

ironfish/src/utils/bigint.test.ts, ironfish/src/utils/bigint.ts
This is useful for getting ratios between two BigInt types
=> Add BigInt helper to divide to a number

ironfish/src/telemetry/index.ts
Users are spamming errors against our server
=> Disable telemetry globally

ironfish-cli/src/commands/accounts/import.ts
Just a small documentation fix
=> import.ts: command line documentation fix

ironfish-cli/src/commands/accounts/pay.ts, ironfish/package.json
The description of the _fee_ argument is wrong. The software considers the fees in IRON, not in ORE.
Changed the description.
=> _fee_ argument is wrong

.github/pull_request_template.md
It felt weird that we can't distinguish between no, and someone who forgot to fill out this item.
=> Add "No" option to breaking change

.github/pull_request_template.md
=>  Make breaking change IN PR TEMPLATE into check boxeS

package.json, yarn.lock
Were hoping it fixes this issue https://github.com/codecov/codecov-node/issues/324
No testing plan
```
[ ] Yes
[x] No
```
=> Upgrade codecov to 3.8.3

ironfish/package.json
Forgot to increment the version in the last one prior to merging.
=> Staging -> Master

ironfish/src/consensus/verifier.ts
Minor cleanup and code reduction
=> Verifier cleanup

ironfish/src/consensus/__fixtures__/verifier.test.ts.fixture, ironfish/src/consensus/verifier.test.ts, ironfish/src/consensus/verifier.ts
Rename this to indicate that it is verifying after the block and spends have been added.
=> Rename hasValidSpends to verifyConnectedSpends

ironfish/src/fileStores/config.ts
Change this to 15 which should be 15 minutes.
Just a config change, no testing needed.
```
[ ] Yes
[x] No
```
=> Set default expiration delta to 15 from 450

ironfish-cli/package.json, ironfish-cli/tsconfig.json
Need to make this change so we can include package.json in the
source to get the version in our source code.
Deploy to ironfish brew beta
```
[ ] Yes
[x] No
```
=> Change ironfish-cli build dir to ./ from ./src

ironfish-rust/src/mining.rs
When comparing hashes, comparing two `[u8; 32]` seems more efficient than
making a `BigUInt` to compare against target. On my laptop this improves
single-core hash rate from ~2.1 MH/s to ~4.1 MH/s.
This is my first time working in rust. I would greatly appreciate any critique, big or small, functional or aesthetic.
Added tests. Miner runs. Would like to confirm blocks are still found organically, but that's pretty time consuming.
No.
=> Avoid making BigUInts when comparing hashes

ironfish-rust/src/mining.rs
Fat-fingered or misread this originally, not sure which.
```
[ ] Yes
[ ] No
```
=> Fix -/+ typo

ironfish/src/telemetry/index.ts
Telemetry is online, so we can remove this flag.
Manually tested.
```
[ ] Yes
[ ] No
```
=> feat(ironfish): Remove `TELEMETRY_OFFLINE` flag

ironfish-cli/src/commands/testnet.ts, ironfish/src/webApi.ts
this new command will fetch a users test net user and auto configure
their node with their testnet user with their graffiti and node name.
```
[ ] Yes
[x] No
```
=> Add new testnet command to auto set up your node

ironfish/src/metrics/metricsMonitor.ts
Adds an interval to submit memory from the metrics monitor to telemetry every 15 seconds.
Manually tested.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Submit heap values on interval to telemetry

ironfish/src/node.ts, ironfish/src/telemetry/telemetry.test.ts, ironfish/src/telemetry/telemetry.ts
This helps scalability for adding more things in the future
Run code
```
[ ] Yes
[X] No
```
=> Convert telemetry constructor to object

CONTRIBUTING.md
Very minor change, but looks a bit weird without the capitalization.
```
[ ] Yes
[x ] No
```
=> Github -> GitHub

ironfish/README.md
Updated docs to remove old references
-
```
[ ] Yes
[x] No
```
=> Remove captain from readme docs

ironfish-cli/package.json, ironfish-cli/src/commands/status.test.ts, ironfish-cli/src/commands/status.ts, ironfish/src/metrics/metricsMonitor.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/node.ts, ironfish/src/rpc/routes/node/getStatus.ts, ironfish/src/telemetry/telemetry.ts
* (#1036)
* (#1038)
* (#1033)
* (#1045)
N/A
```
[ ] Yes
[x] No
```
=> `staging` -> `master`

ironfish/src/fileStores/hosts.ts, ironfish/src/network/peers/addressManager.test.ts, ironfish/src/network/testUtilities/mockHostsStore.ts
Removes unused fields from HostsStore.
All tests pass.
```
[ ] Yes
[x] No
```
=> Clean up unused field in hostsStore

ironfish-cli/src/commands/debug.ts
This will remove 1 more question/variable when trying to debug issues, which hopefully will speed up the turn around time on resolving issues for users.
```
[ ] Yes
[x] No
```
=> Check if `ironfish` is present in PATH in `debug` command

ironfish/src/node.ts, ironfish/src/telemetry/telemetry.test.ts, ironfish/src/telemetry/telemetry.ts
Submit the head sequence of the node's chain to telemetry.
Manually tested:
```
[ ] Yes
[x] No
```
=> feat(ironfish): Submit chain head's sequence to telemetry

CONTRIBUTING.md, ironfish/src/fileStores/config.ts
=> update discord links

ironfish/src/consensus/verifier.ts, ironfish/src/typedefs/bufio.d.ts, ironfish/src/workerPool/messages.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/tasks/__fixtures__/verifyTransaction.test.ts.fixture, ironfish/src/workerPool/tasks/handlers.ts, ironfish/src/workerPool/tasks/index.ts, ironfish/src/workerPool/tasks/verifyTransaction.test.ts, ironfish/src/workerPool/tasks/verifyTransaction.ts, ironfish/src/workerPool/tasks/workerMessage.ts, ironfish/src/workerPool/worker.ts
Use new serializable interface for verifying transactions.
Added unit test.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Move transaction verification to buffer serialization

.github/workflows/deploy-node-github-beta.yml, .github/workflows/deploy-node-github.yml
This allows our actions to deploy to docker
Ran the docker deploy from master after this merges
```
[ ] Yes
[x] No
```
=> Set permissions for docker deploys

ironfish/package.json
Hopefully temporary until we can find a better solution for pool's sqlite dependency
```
[ ] Yes
[ ] No
```
=> Move sqlite to main dependency

ironfish-rust-nodejs/tests/demo.test.slow.ts
This fixes a test with something that was removed from the rust native side
```
[ ] Yes
[x] No
```
=> Fix node native slow test

ironfish/src/workerPool/messages.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/tasks/__fixtures__/createMinersFee.test.ts.fixture, ironfish/src/workerPool/tasks/createMinersFee.test.ts, ironfish/src/workerPool/tasks/createMinersFee.ts, ironfish/src/workerPool/tasks/handlers.ts, ironfish/src/workerPool/tasks/index.ts, ironfish/src/workerPool/tasks/workerMessage.ts, ironfish/src/workerPool/worker.ts
Use new serializable interface for creating miners fees.
Added unit tests.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Move create miners fee to buffer serialization

ironfish-cli/Dockerfile
=> Add Python install to Dockerfile for dependency

ironfish/src/rpc/routes/workers/getStatus.ts, ironfish/src/typedefs/bufio.d.ts, ironfish/src/workerPool/messages.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/tasks/handlers.ts, ironfish/src/workerPool/tasks/index.ts, ironfish/src/workerPool/tasks/sleep.test.ts, ironfish/src/workerPool/tasks/sleep.ts, ironfish/src/workerPool/tasks/workerMessage.ts, ironfish/src/workerPool/tasks/workerTask.ts, ironfish/src/workerPool/worker.ts
Converts the Sleep task to the new serialization format.
Added unit tests for the Sleep task.
```
[ ] Yes
[X] No
```
=> Convert Sleep task to serialized form

ironfish-cli/src/commands/miners/start.ts
This makes it easier usability wise, because you can just use host:port,
host, or :port.
Run miner with different flags inputs
Removing one flag
```
[x] Yes
[ ] No
```
=> Combine miner pool host and port flags

ironfish/package.json, package.json, yarn.lock
This will at least bump to a node-gyp version that supports Python 3
```
[ ] Yes
[ ] No
```
=> Use updated version of sqlite3 with more recent version of node-gyp

ironfish/src/network/identity.ts, ironfish/src/network/peers/encryption.ts, ironfish/src/workerPool/messages.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/tasks/handlers.ts, ironfish/src/workerPool/tasks/index.ts, ironfish/src/workerPool/tasks/unboxMessage.test.ts, ironfish/src/workerPool/tasks/unboxMessage.ts, ironfish/src/workerPool/tasks/workerMessage.ts, ironfish/src/workerPool/worker.ts
Convert the UnboxMessage worker pool task to use serialization.
Added unit tests for the message.
```
[ ] Yes
[X] No
```
=> Serialize UnboxMessage worker task

ironfish/src/rpc/routes/workers/getStatus.ts, ironfish/src/workerPool/interfaces/workerMessageStats.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/utils.ts
Use new worker message types in pool stats
```
[ ] Yes
[x] No
```
=> feat(ironfish): Use `WorkerMessageType` in pool stats

ironfish/src/workerPool/interfaces/workerHeader.ts, ironfish/src/workerPool/job.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/worker.ts
This is a temporary solution until the worker pool is refactored further, but add some logs if errors are encountered during parsing.
N/A
```
[ ] Yes
[x] No
```
=> feat(ironfish): Add logs for header and payload parsing in pool

ironfish-rust/src/transaction/mod.rs
We checked a while ago that this was accurate, I don't think it's necessary to have this comment here any longer.
No testing needed, it's a comment change.
```
[ ] Yes
[ ] No
```
=> Remove unnecessary TODO

ironfish/src/network/messages.test.ts, ironfish/src/network/messages.ts
The note and nullifier messages aren't used anywhere, so we can remove them.
Fixes IRO-1688
Fixes IRO-1691
```
[ ] Yes
[X] No
```
=> Remove unused Note and Nullifier messages

ironfish/src/common/serializable.ts, ironfish/src/network/messages/networkMessage.ts
Create new abstract class for network message conversion.
N/A
```
[ ] Yes
[x] No
```
=> feat(ironfish): Create abstract class for serializable network messages

ironfish-cli/package.json, yarn.lock
Also removes the pack command, since we're using yarn pack directly to generate the tarballs.
I ran pack locally to make sure it still works.
```
[ ] Yes
[X] No
```
=> Upgrade oclif dev cli to 2.6.0

ironfish-cli/package.json, ironfish/package.json
=> Bump sdk and cli version for release 0.1.28

ironfish/src/network/messages.ts, ironfish/src/network/messages/networkMessage.ts, ironfish/src/network/messages/signalRequest.test.ts, ironfish/src/network/messages/signalRequest.ts, ironfish/src/network/peers/connections/connection.ts, ironfish/src/network/peers/peer.ts, ironfish/src/network/peers/peerManager.test.ts, ironfish/src/network/peers/peerManager.ts
Update signal request message to be buffer serializable.
Added unit tests.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Make signal request message buffer serializable

ironfish/src/telemetry/interfaces/metric.ts, ironfish/src/telemetry/telemetry.test.ts, ironfish/src/telemetry/telemetry.ts, ironfish/src/typedefs/bufio.d.ts, ironfish/src/workerPool/tasks/submitTelemetry.test.ts, ironfish/src/workerPool/tasks/submitTelemetry.ts
Clean up the fields when serializing the telemetry job.
Updated unit tests.
```
[ ] Yes
[x] No
```
=> refactor(ironfish): Improve telemetry serialization

ironfish/src/network/messages.test.ts, ironfish/src/network/messages.ts, ironfish/src/network/messages/networkMessage.ts, ironfish/src/network/messages/peerList.test.ts, ironfish/src/network/messages/peerList.ts, ironfish/src/network/peers/connections/connection.ts, ironfish/src/network/peers/peer.ts, ironfish/src/network/peers/peerManager.test.ts, ironfish/src/network/peers/peerManager.ts
Migrate peer list message to new serializable interface.
Unit tests
```
[ ] Yes
[x] No
```
=> feat(ironfish): Make PeerList buffer serializable

ironfish/src/network/messages.test.ts, ironfish/src/network/messages.ts, ironfish/src/network/messages/networkMessage.ts, ironfish/src/network/messages/peerListRequest.test.ts, ironfish/src/network/messages/peerListRequest.ts, ironfish/src/network/peers/connections/connection.ts, ironfish/src/network/peers/peerManager.test.ts, ironfish/src/network/peers/peerManager.ts
Convert `PeerListRequest` use the new serializable interface
Unit tests
```
[ ] Yes
[x] No
```
=> feat(ironfish): Make PeerListRequest buffer serializable

ironfish/src/mining/discord.ts, ironfish/src/mining/poolShares.ts
=> Pool: Add total share count to discord message

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Looks like my  format-on-save had opinions about bringing the spacing inline with our other package json files
```
[ ] Yes
[ ] No
```
=> Version bump 0.1.29 CLI

ironfish/src/network/messageRouters/fireAndForget.ts, ironfish/src/network/messageRouters/globalRpc.test.ts, ironfish/src/network/messageRouters/globalRpc.ts, ironfish/src/network/messageRouters/gossip.ts, ironfish/src/network/messageRouters/messageRouter.ts, ironfish/src/network/messageRouters/rpc.test.ts, ironfish/src/network/messageRouters/rpc.ts, ironfish/src/network/messages.test.ts, ironfish/src/network/messages.ts, ironfish/src/network/messages/getBlocks.test.ts, ironfish/src/network/messages/getBlocks.ts, ironfish/src/network/messages/networkMessage.ts, ironfish/src/network/messages/networkTask.ts, ironfish/src/network/messages/rpcNetworkMessage.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/network/peers/connections/connection.ts, ironfish/src/network/peers/peerManager.ts
Convert `GetBlocks` to be binary serializable
Unit tests and manually ran
```
[ ] Yes
[x] No
```
=> feat(ironfish): Make get blocks buffer serializable

ironfish/src/network/messageRouters/rpc.ts, ironfish/src/network/messages.test.ts, ironfish/src/network/messages.ts, ironfish/src/network/messages/getBlockHashes.test.ts, ironfish/src/network/messages/getBlockHashes.ts, ironfish/src/network/messages/networkMessage.ts, ironfish/src/network/messages/peerList.ts, ironfish/src/network/messages/signalRequest.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/network/peers/connections/connection.ts
Make GetBlockHashes request and response binary serializable.
Added unit tests and manually ran node.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Convert get block hashes to buffer serialization

ironfish/src/network/messages.ts, ironfish/src/network/messages/networkMessage.ts, ironfish/src/network/messages/newBlock.test.ts, ironfish/src/network/messages/newBlock.ts, ironfish/src/network/peerNetwork.test.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/network/peers/connections/connection.ts, ironfish/src/network/peers/connections/webRtcConnection.ts, ironfish/src/network/peers/connections/webSocketConnection.ts
Migrate new blocks message
Unit test
```
[ ] Yes
[x] No
```
=> feat(ironfish): Move new blocks to buffer serialization

ironfish/src/node.ts, ironfish/src/telemetry/telemetry.test.ts, ironfish/src/telemetry/telemetry.ts, ironfish/src/testUtilities/mocks.ts, ironfish/src/webApi.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/tasks/submitTelemetry.test.ts, ironfish/src/workerPool/tasks/submitTelemetry.ts
Note that this isn't adding graffiti to the telemetry payload itself, just to the API request. Will need accompanying API PR
```
[ ] Yes
[ ] No
```
=> Add graffiti to telemetry API payload

ironfish/src/network/messageRouters/rpc.test.ts, ironfish/src/network/messageRouters/rpc.ts
Switches the RPC router to store peers on requests rather than connections, allowing responses to be sent over a different connection (for example, when switching from a WebSocket to WebRTC connection).
Also fixes an issue with RPC IDs incrementing in the RPC router.
```
[ ] Yes
[X] No
```
=> Allow for RPC response on different connection

ironfish/src/workerPool/tasks/workerMessage.ts, ironfish/src/workerPool/worker.ts
See title
Covered by existing unit tests.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Remove `size` from worker pool message header

codecov.yml
We have 3 projects event, logger, serde that no longer exist in the
monorepo.
```
[ ] Yes
[x] No
```
=> Remove projects from codecov that don't exist

ironfish-cli/src/commands/testnet.ts, ironfish/src/webApi.ts
=> Testnet command uses graffiti instead of ID for improved usability

ironfish/src/rpc/adapters/tcpAdapter.ts
Change code style to do early returns without else statements
Existing tests
```
[ ] Yes
[X] No
```
=> Change code style to do early returns without else statements

ironfish/src/network/messages/getBlockHashes.test.ts, ironfish/src/network/messages/getBlockHashes.ts, ironfish/src/network/messages/getBlocks.test.ts, ironfish/src/network/messages/getBlocks.ts, ironfish/src/network/messages/newBlock.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/primitives/blockheader.ts, ironfish/src/serde/PartialHeaderSerde.ts, ironfish/src/typedefs/bufio.d.ts, ironfish/src/utils/bigint.test.ts, ironfish/src/utils/bigint.ts
Reduces the size of the block and block hash request messages in the networking serialization branch.
Tests should pass, and will manually test the serialize-networking branch once it's ready.
```
[ ] Yes
[X] No
```
=> Shrink the block and block hash request messages

ironfish/src/memPool/memPool.ts, ironfish/src/node.ts
Remove unused field from mempool.
Run node and existing unit tests.
```
[ ] Yes
[x] No
```
=> refactor(ironfish): Remove unused strategy from mempool

ironfish/src/merkletree/database/leaves.ts
Fixes TODOs that were added in the serialize-database branch by fixing the size of merkle tree elements.
Tests should pass, and we'll do a full manual test on the serialize-database branch when it's finished.
*All of the database encoding changes should be breaking changes.*
```
[X] Yes
[ ] No
```
=> Fix TODO in serialization of merkle tree leaves

ironfish-cli/src/commands/accounts/import.ts, ironfish/src/account/account.ts, ironfish/src/account/accounts.ts, ironfish/src/account/accountsdb.ts, ironfish/src/account/database/accounts.test.ts, ironfish/src/account/database/accounts.ts, ironfish/src/account/index.ts, ironfish/src/account/validator.ts, ironfish/src/rpc/routes/accounts/getPublicKey.test.ts
Migrate `accounts` store in Accounts DB to binary serialization
Unit tests
```
[ ] Yes
[x] No
```
=> feat(ironfish): Refactor serialization for accountsdb accounts store

ironfish/src/rpc/routes/chain/getTransactionStream.ts
Bit of lint cleanup that slipped through the cracks
```
[ ] Yes
[ ] No
```
=> Remove unneeded async keywords

ironfish/src/mining/manager.ts
See title
Run the node
```
[ ] Yes
[x] No
```
=> feat(ironfish): Bump `MAX_TRANSACTIONS_PER_BLOCK` to 300

ironfish/src/rpc/routes/chain/getTransactionStream.ts
We need this field to make deposits record progress properly for
resuming.
Run tests
```
[ ] Yes
[x] No
```
=> Upload previousBlockHash with all deposits

ironfish/src/blockchain/blockchain.ts, ironfish/src/blockchain/database/transactions.ts
See title
Unit tests
```
[ ] Yes
[x] No
```
=> refactor(ironfish): Remove `workerPool` from Blockchain Transactions encoder

ironfish-cli/src/commands/deposit.ts
=> Deposit CLI command will exit early if account does not have required balance

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Bumps package versions for the staging release.
```
[ ] Yes
[ ] No
```
=> Bump to 0.0.8, 0.1.30, 0.1.4

ironfish/src/workerPool/tasks/createTransaction.test.slow.ts, ironfish/src/workerPool/tasks/createTransaction.ts
This was getting clobbered as ascii which would've caused issues with syncing deposits
```
[ ] Yes
[ ] No
```
=> Worker pool createTransaction serializes memo as utf8

ironfish-cli/src/commands/reset.ts, ironfish/src/fileStores/hosts.ts
This reverts commit ffb5674ad31fc1742333ac7f83ad728df4456a90.
accidental merge into master instead of staging
```
[ ] Yes
[ ] No
```
=> Revert "delete the hosts.json file on a database reset (#1285)"

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Bumps the versions for the Phase 2 testnet release.
```
[ ] Yes
[ ] No
```
=> Bump versions to 0.0.10, 0.1.32, 0.1.6

ironfish/src/network/peers/connections/webSocketConnection.ts
Reduce down log level to debug
Run the node
```
[ ] Yes
[x] No
```
=> feat(ironfish): Bump down log level for non-buffer messages

ironfish-cli/src/commands/start.ts
Reverts iron-fish/ironfish#1300
=> Revert "If there is no default account on startup, create one"

ironfish-cli/src/commands/deposit.ts, ironfish/src/webApi.ts
Several users reported that the deposit command would respond with "No graffiti found" when the API was under heavy load. If the node receives a status code above 500, report that the API is having an issue and that the user should try again later.
Currently waiting for pool payout so I can test it with coins.
```
[ ] Yes
[ ] No
```
=> Fix incorrect registered graffiti error

ironfish/src/network/peerNetwork.ts
Drop transactions when syncing sooner
Works locally 
No
=> Drop transactions when syncing sooner

ironfish-cli/package.json, ironfish/package.json
=> Version bump 0.1.33

ironfish-cli/package.json, ironfish/package.json
=> Bump versions to 0.1.34, 0.1.12

ironfish/src/memPool/memPool.ts
Minor thing that has bothered me for a while. Keeps making me think we're doing more transaction work than is needed when just running a regular node which isn't actually the case
```
[ ] Yes
[ ] No
```
=> "Deleted transactions" log should now only display if transactions are actually removed

ironfish/src/primitives/noteEncrypted.ts, ironfish/src/primitives/transaction.ts
Adds comments to the JS-side deserialization to document the fields in the transactions, notes, and spends. Blocks are documented already by the block message writer.
Also sliced the merkle hash out of the buffer directly to avoid the need to instantiate a Rust object.
```
[ ] Yes
[X] No
```
=> Document field sizes and speed up merkleHash

ironfish/src/mining/pool.ts, ironfish/src/mining/stratum/stratumServer.ts
Few minor fixes to make the client count more accurate. I don't expect this to fully fix the issue, but it should help
```
[ ] Yes
[ ] No
```
=> Pool: Only count good clients, and properly dispose of clients that error out

ironfish-cli/package.json, ironfish/package.json
=> Bump versions to 0.1.35, 0.0.13

ironfish/src/mining/pool.ts, ironfish/src/mining/stratum/stratumServer.ts
Adding some logs to the mining pool to figure out why pool is not sending logs for a long time
```
[ ] Yes
[X] No
```
=> Add logs to mining pool

ironfish/src/rpc/routes/chain/exportChain.test.ts
Increase exportChain.ts code coverage to 100%
yarn lint
yarn test
```
[ ] Yes
[X] No
```
=> exportChain code coverage

ironfish/src/mining/stratum/stratumClient.ts
protects against reading partial messages from the TCP socket stream.
stores any partial messages read from the socket in the message buffer and
concatenates the next read onto the message buffer.
background:
tcp sockets are modeled on streams of data, and the data that the server writes
to the socket may be broken apart during transmission. the reader is guaranteed
to receive data in the same order that the writer sends it, but not necessarily
in a contiguous chunk.
- uses last index of message delimiter ('\n') to identify beginning of any
partial messages
- clears message buffer on socket disconnect
the attached patch reproduces the error when running a pool and miner locally. the changes here resolve the error
[stratum_tcp_test.patch.txt](https://github.com/iron-fish/ironfish/files/8828 …
=> feat: adds a message buffer to the stratum client

ironfish-cli/package.json, ironfish/package.json
=> Bump versions to 0.1.36, 0.0.14

ironfish/src/rpc/adapters/tcpAdapter.ts
I'm trying to bring parity to the two of them
Run adapter and user commands
```
[ ] Yes
[x] No
```
=> Add TcpAdapter.started from IpcAdapter

ironfish/package.json, ironfish/src/network/peerNetwork.ts, ironfish/src/typedefs/bfilter.d.ts, yarn.lock
Replaces the `bfilter` dependency with the [`@ironfish/bfilter`](https://www.npmjs.com/package/@ironfish/bfilter) fork.
Run the node.
```
[ ] Yes
[x] No
```
=> feat(ironfish): Replace `bfilter` with `@ironfish/bfilter`

ironfish-cli/src/commands/accounts/publickey.test.ts
Add test to cover command "accounts:publickey"
```
[ ] Yes
[ ] No
```
=> Add test for accounts:publickey

codecov.yml
As a follow-up to #1222, reduce the `codecov/patch` target until larger projects are completed.
N/A
```
[ ] Yes
[x] No
```
=> chore(): Lower `codecov/patch` target to 10%

CONTRIBUTING.md
Put FIP definition above section on why it should be used, and fixed a
link to that section.
=> Improve contributing.MD

.github/pull_request_template.md
It now matches our other repositories.
Testing
```
[ ] Yes
```
=> Remove NO from PR template for breaking change

CONTRIBUTING.md
anchor tag missing in contributing.MD file
=> fix: broken link in docs

CONTRIBUTING.md
=> Make reasons to reject linkable in CONTRIBUTING.md

config/eslint-config-ironfish/index.js, openapitools.json
These are unused since we deleted the HTTP and rosetta subprojects
```
[ ] Yes
[ ] No
```
=> Delete old open api files

ironfish/src/mining/poolDatabase/database.ts
=> fixes sql error from missing space

ironfish-cli/src/commands/miners/pools/status.ts, ironfish/src/mining/pool.ts, ironfish/src/mining/stratum/messages.ts, ironfish/src/mining/webhooks/webhookNotifier.ts
And rename banCount to be consistent with pluralized words that don't
have "Count" suffix.
Run locally
```
[ ] Yes
```
=> Add clients to status

ironfish-cli/src/commands/debug.ts, ironfish/src/account/__fixtures__/accounts.test.ts.fixture, ironfish/src/account/accounts.test.ts, ironfish/src/account/accounts.ts, ironfish/src/account/accountsdb.ts, ironfish/src/account/database/meta.ts
Allows future improvements like syncing accounts individually and maintaining state separately
Closes IRO-2223
```
[ ] Yes
```
=> Store headHash per account to allow for syncing accounts

ironfish/src/consensus/verifier.test.ts, ironfish/src/metrics/metricsMonitor.ts, ironfish/src/mining/manager.ts, ironfish/src/network/peers/peer.ts, ironfish/src/network/peers/peerManager.ts, ironfish/src/node.ts, ironfish/src/telemetry/telemetry.test.ts, ironfish/src/telemetry/telemetry.ts
We want to be able to visualize network topology. For this we will need to add peer lists to telemetry. We will upload peer lists from all peers every ~5 minutes
Local testing
```
[ ] Yes
```
=> Upload peer lists to telemetry

ironfish/src/account/accounts.test.slow.ts, ironfish/src/account/accounts.ts, ironfish/src/account/accountsdb.ts, ironfish/src/account/database/decryptedNotes.test.ts, ironfish/src/account/database/decryptedNotes.ts
These notes are already decrypted.
N/A
```
[ ] Yes
```
=> refactor(ironfish): s/decryptableNotes/decryptedNotes

ironfish-cli/src/commands/start.test.ts, ironfish/src/account/account.ts, ironfish/src/account/accounts.test.slow.ts, ironfish/src/account/accounts.ts, ironfish/src/account/accountsdb.ts
Move decrypted note into account for encapsulation
```
[ ] Yes
```
=> refactor(ironfish): Encapsulate decrypted notes inside account

ironfish/src/account/accounts.ts
Rename variable name to be more accurate
N/A
```
[ ] Yes
```
=> refactor(ironfish): s/nullifier/decryptedNote in `syncTransaction`

ironfish/src/indexers/minedBlocksIndexer.ts
=> Update accountsToRemove map in minedBlocksIndexer

ironfish/src/account/accounts.ts
Currently there is no synchronization around creating transactions for an account. It's possible for two calls for creating transaction to grab the same note.
Manual testing
```
[ ] Yes
```
=> fix(ironfish): Add mutex for sending transactions

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, ironfish-cli/README.md, ironfish-rust/README.md, ironfish/README.md, ironfish/src/serde/README.md
Fixed the spelling and grammar of the Markdown files
None required
No
```
[ ] Yes
```
Graffiti: ironfishup
=> Spelling and Grammar fixes of Markdown files

ironfish/src/network/messageRegistry.ts, ironfish/src/network/messages/newBlockV2.test.ts, ironfish/src/network/messages/newBlockV2.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/network/types.ts, ironfish/src/network/utils/block.ts, ironfish/src/primitives/block.ts, ironfish/src/typedefs/bufio.d.ts
This adds the message iteself, as well as a stub for implementing the handler later (this may end up getting refactored elsewhere).
Node should still start up as before.
```
[ ] Yes
```
=> Add NewBlockV2 message

ironfish/src/memPool/__fixtures__/memPool.test.ts.fixture, ironfish/src/memPool/memPool.test.ts, ironfish/src/memPool/memPool.ts, ironfish/src/mining/manager.test.ts, ironfish/src/mining/manager.ts, ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture, ironfish/src/network/messages/pooledTransactions.test.ts, ironfish/src/network/peerNetwork.test.ts, ironfish/src/network/peerNetwork.ts
Implement the logic to handle peer requests for transactions by hash from the mempool. Logic outlined in [gossip proposal](https://coda.io/d/Gossip_d7HSvA-Pxcz/Transaction-Gossip-Proposal_suP5z#_lueoR)
Unit tests
```
[ ] Yes
```
=> Handle PooledTransactionRequest

ironfish-cli/src/commands/accounts/rescan.test.ts, ironfish-cli/src/commands/accounts/rescan.ts, ironfish/src/account/accounts.ts, ironfish/src/rpc/routes/accounts/rescanAccount.ts
`ironfish accounts:rescan --local --reset`
```
Scanning for transactions
Asking node to start scanning... done
Scanning Blocks: [----------------------------------------] 363/75956 0% 40/sec | 19m 16s
```
Run the CLI command
```
[ ] Yes
```
=> Improve accounts:rescan CLI command UX

ironfish-cli/package.json, ironfish/package.json
Bumping versions for release
```
[ ] Yes
```
=> Bump version to 0.1.38

ironfish/src/account/accountsdb.ts, ironfish/src/storage/database/encoding.ts
Create a store which will hold a mapping of account IDs to unconfirmed balance.
N/A
```
[ ] Yes
```
=> feat(ironfish): Create unconfirmed balance store for accounts

ironfish/src/account/accounts.ts
**Builds on #1768**
Gives us the ability to pass in specific accounts, for selectively choosing which accounts to try decrypting for. This should result in improve performance for rescans as well as normal transaction syncing when not all accounts are up to date
```
[ ] Yes
```
=> Allow decryptNotes to take an optional array of accounts

ironfish/src/network/messageRegistry.ts, ironfish/src/network/messages/newPooledTransactionHashes.test.ts, ironfish/src/network/messages/newPooledTransactionHashes.ts, ironfish/src/network/peerNetwork.ts
Create a message for gossiping transactions by hash
Unit tests
```
[ ] Yes
```
=> Add NewPooledTransactionHashes message

ironfish/src/network/peerNetwork.ts
Doing some refactoring (no logic changes) to more easily integrate new transaction propagation logic
```
[ ] Yes
```
=> Refactor Transaction gossip in PeerNetwork

ironfish-rust/src/transaction/miners_fee.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/tests.rs, ironfish-rust/src/transaction/transfer.rs
Create new implementation for miners fee transactions
Unit tests
```
[ ] Yes
```
=> feat(rust): Create miners fee transaction

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> bump version to 0.0.17 and 0.1.39

ironfish-cli/package.json, ironfish/src/network/peerNetwork.test.ts
=> fix some broken tests

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump version to 0.1.40

ironfish/src/account/accountsdb.ts, ironfish/src/account/database/transactions.test.ts, ironfish/src/account/database/transactions.ts
This looks like it's missing and won't be saved correctly.
```
[ ] Yes
```
=> Serialize TransactionValue.sequence

ironfish/src/account/account.ts
This one is a bit in reverse
-
```
[ ] Yes
```
=> Make if statement consistent with the rest of the code

ironfish-cli/src/commands/status.test.ts, ironfish-cli/src/commands/status.ts, ironfish/src/rpc/routes/node/getStatus.ts
FIP: #1858
Adding nodeName and blockGraffiti information to status command via RPC payload.
```
[ ] Yes
```
=> Add nodeName and blockGraffiti to status command

ironfish-cli/src/commands/accounts/transactions.ts
Support display options extend from CliUx.ux.table.
Local test.
```
[ ] Yes
[✓] No
```
=> Display options extend from CliUx.ux.table

ironfish/src/utils/bench.test.ts, ironfish/src/utils/bench.ts
The new segment will measure time and memory allocation (if the gc is
exposed) for the segment you measure.
Run tests, or play around with it yourself.
```
[ ] Yes
```
=> Add tools to bench mark segments of code

ironfish/src/sdk.ts
Found while tinkering with message boxing changes
```
[ ] Yes
```
=> Remove unused privateIdentity param in IronfishSdk

ironfish/src/network/__fixtures__/peerNetwork.test.ts.fixture, ironfish/src/network/peerNetwork.test.ts, ironfish/src/network/peerNetwork.ts, ironfish/src/syncer.ts
Removes the use of nonce filtering from the onNewBlock handler, allowing for removing the nonce filter entirely.
```
[ ] Yes
```
=> Remove filter for gossip nonces

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json, ironfish/src/network/version.ts
Bump version for release. We are also bumping network version so we can enforce upgrading for gossip changes
```
[ ] Yes
```
=> Bump version 0.1.41

ironfish/src/account/accountsdb.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/indexers/minedBlocksIndexer.ts, ironfish/src/mining/stratum/stratumClient.ts, ironfish/src/mining/stratum/stratumServer.ts, ironfish/src/mining/stratum/version.ts
Reverts iron-fish/ironfish#1896
#1896 targeted to master by mistake
=> Revert "standardizes naming of version constants"

ironfish/src/telemetry/telemetry.ts
Adds RSS to telemetry.
```
[ ] Yes
```
=> Add RSS to periodic telemetry payload

ironfish/src/account/accounts.ts
Add a handful of messages for asserts in accounts, so that we can tell where an error is occurring easier.
```
[ ] Yes
```
=> Add messages to asserts in accounts

ironfish-rust/src/primitives/asset_type.rs, ironfish-rust/src/receiving.rs, ironfish-rust/src/spending.rs, ironfish-rust/src/transaction/miners_fee.rs, ironfish-rust/src/transaction/transfer.rs
=> Add support for transfering custom assets

ironfish-cli/src/commands/chain/download.ts
Axios does not time out idle connections, this means if you're downloading
for a long time and the TCP connection gets lost you'll be stuck
downloading the snapshot and it won't fail or kill the command.
This re-writes downloading to use axios cancelation source to kill the
request after a specified idle timeout. It also fixes some issues
plumbing the errors through the process.
See https://github.com/axios/axios/issues/2143 for more information
1. Run the snapshot download
2. Turn off your wifi for 30 seconds
3. See that it errors properly
```
[ ] Yes
```
=> Timeout idle connections when downloading snapshot

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
bumps package versions to prepare for release
```
[ ] Yes
```
=> bump versions for release version 0.1.42

ironfish-cli/src/commands/chain/prune.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/storage/database/database.ts, ironfish/src/storage/levelup/database.ts
This will delete forks and compact the leveldown instance.
```
[ ] Yes
```
=> Add offline prune command

ironfish-cli/src/commands/accounts/import.ts, ironfish/src/migrations/data/013-wallet-2/new/accounts.ts, ironfish/src/migrations/data/013-wallet-2/new/stores.ts, ironfish/src/testUtilities/fixtures.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/database/accountValue.test.ts, ironfish/src/wallet/database/accountValue.ts, ironfish/src/wallet/database/accountsdb.ts, ironfish/src/wallet/index.ts, ironfish/src/wallet/validator.ts, ironfish/src/wallet/wallet.ts
- Also make the file name match
- Rename the encoding too
- Update the migration to match
```
[ ] Yes
```
=> Rename AccountsValue -> AccountValue

ironfish/src/migrations/data/013-wallet-2/new/decryptedNotes.ts, ironfish/src/migrations/data/013-wallet-2/new/stores.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/database/accountsdb.ts, ironfish/src/wallet/database/decryptedNoteValue.test.ts, ironfish/src/wallet/database/decryptedNoteValue.ts
- Also make the file name match
- Rename the encoding too
- Update the migration to match
```
[ ] Yes
```
=> Rename DecrypytedNotesValue -> DecryptedNoteValue

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> bump version to 0.1.44

ironfish/src/wallet/database/accountsdb.ts, ironfish/src/wallet/database/transactionValue.test.ts, ironfish/src/wallet/database/transactionValue.ts
- Also make the file name match
- Rename the encoding too
- Update the migration to match
```
[ ] Yes
```
=> Rename TransactionsValue -> TransactionValue

ironfish/src/wallet/database/decryptedNoteValue.ts, ironfish/src/wallet/database/transactionValue.ts
I'm documenting these because I have to keep reading through the code to figure out when these are not null.
```
[ ] Yes
```
=> Add documentation for wallet2 stores

ironfish/src/migrations/data/013-wallet-2.ts, ironfish/src/typedefs/buffer-map.d.ts
I didn't know this was exposed in that module when I wrote this.
```
[ ] Yes
```
=> Use BufferSet instead of BufferMap<true>

ironfish-cli/package.json
=> Add a start:debug command for inspecting the node process

ironfish/src/account/accounts.ts
Issue https://github.com/iron-fish/ironfish/issues/1877
Local test.
```
[ ] Yes
```
=> Add confirming status for getTransactions

ironfish/src/mining/poolShares.ts, ironfish/src/rpc/routes/mining/blockTemplateStream.ts
Small PR to improve some logging. Ran into an issue where the pool didn't notify discord of a payout success or error, and don't really have enough logs to figure out if the payout failed for some strange reason, or if the issue was with the discord notification.
```
[ ] Yes
```
=> Add some additional logging for pool payouts and block template

ironfish/src/migrations/data/013-wallet-2.ts, ironfish/src/migrations/data/013-wallet-2/new/transactions.ts, ironfish/src/rpc/routes/accounts/utils.ts, ironfish/src/utils/buffer.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/database/accountsdb.ts, ironfish/src/wallet/database/transactionValue.test.ts, ironfish/src/wallet/database/transactionValue.ts, ironfish/src/wallet/wallet.ts
=> Convert transactionValue.blockHash to Buffer

ironfish/src/account/accounts.ts
Fix issue https://github.com/iron-fish/ironfish/issues/2052
```
[ ] Yes
```
=> MinersFeeTransaction status of forked block

ironfish-rust/src/primitives/asset_type.rs, ironfish-rust/src/proofs/circuit/create_asset.rs, ironfish-rust/src/proofs/circuit/mod.rs, ironfish-rust/src/proofs/circuit/mycircuit.rs, ironfish-rust/src/proofs/circuit/sapling.rs, ironfish-rust/src/transaction/transfer.rs
=> First proof of concept for a create asset circuit

ironfish/src/wallet/wallet.ts
Made this code a little more linear so it's clearer what the if is doing
```
[ ] Yes
```
=> Minor code change to read the code easier

ironfish-rust/src/asset_note.rs, ironfish-rust/src/lib.rs, ironfish-rust/src/note.rs, ironfish-rust/src/primitives/asset_type.rs, ironfish-rust/src/proofs/circuit/create_asset.rs, ironfish-rust/src/receiving.rs
=> Add commitment stuff to create asset circuit

ironfish/src/node.ts
This DB was not being closed like the others.
```
[ ] Yes
```
=> Fix not closing indexer DB

ironfish/src/wallet/account.ts
We always name these with the key first, and the value as the second
part of the name.
```
[ ] Yes
```
=> Rename noteHashesBySequence to inverse name

ironfish/src/indexers/minedBlocksIndexer.ts, ironfish/src/wallet/wallet.ts
This causes errors now because of the new error merged into staging.
```
[ ] Yes
```
=> Fix passing in wallet TX into chain DB

ironfish/src/wallet/account.ts, ironfish/src/wallet/database/accountsdb.ts, ironfish/src/wallet/wallet.ts
=> Fixes a few race conditions we found

ironfish-rust/src/proofs/circuit/mint_asset.rs, ironfish-rust/src/test_util.rs
=> Add merkle path stuff to mint circuit

ironfish/src/network/peers/connections/connection.ts
I was testing this out locally and didn't mean to commit it, but it ended up merging in #2037. I think it's probably a reasonable change, but I'd like to make the change with a more evidence-based approach.
```
[ ] Yes
```
=> Revert connection timeout

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump versions to 0.1.45

ironfish-rust/src/proofs/circuit/mint_asset.rs, ironfish-rust/src/test_util.rs
Add new test that creates brand new asset, mints some coins, and spends these coins
Added the test
```
[ ] Yes
```
=> feat(rust): Update test to spend notes from create / mint

ironfish/src/utils/bench.ts
Make segment memory non nullable because we always collect it now.
```
[ ] Yes
```
=> Make segment memory non nullable

ironfish/src/rpc/adapters/ipcAdapter.test.ts, ironfish/src/rpc/adapters/socketAdapter/socketAdapter.ts, ironfish/src/rpc/adapters/tcpAdapter.test.ts, ironfish/src/rpc/routes/router.ts, ironfish/src/sdk.test.ts, ironfish/src/sdk.ts
Make each TcpAdapter test use an OS assigned port
```
[ ] Yes
```
=> Make each TcpAdapter test use an OS assigned port

ironfish/src/rpc/adapters/socketAdapter/protocol.ts
=> Remove duplicate type

ironfish-rust-nodejs/Cargo.lock, ironfish-rust-nodejs/Cargo.toml, ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/note.rs, ironfish-rust-nodejs/src/structs/note_encrypted.rs, ironfish-rust-nodejs/src/structs/transaction.rs
=> Upgrade napi 2.9 and use JsBuffers to avoid memory issues

ironfish/src/consensus/verifier.ts
We weren't using the result of the pastRoot calculation anyway, and it's fairly expensive to calculate, so we can skip it and just check for double spends only.
```
[ ] Yes
```
=> Remove pastRoot calculation on new transactions

ironfish-cli/package.json, yarn.lock
Fix for https://github.com/iron-fish/ironfish/issues/2165. Issue was fixed by oclif team https://github.com/oclif/core/pull/432, just need to bump to latest stable version.
Test `ironfish accounts:transactions` with account that has lots of transactions
```
[ ] Yes
```
=> upgrade @oclif/core to latest

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
- SDK to 23
- CLI to 46
```
[ ] Yes
```
=> Version bump staging

ironfish/src/rpc/routes/accounts/getNotes.ts, ironfish/src/rpc/routes/accounts/getTransaction.ts, ironfish/src/rpc/routes/accounts/utils.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/accounts.test.slow.ts, ironfish/src/wallet/database/accountsdb.ts, ironfish/src/wallet/wallet.ts
=> Remove in memory notes from wallet 2.0

ironfish/src/migrations/data/013-wallet-2.ts, ironfish/src/migrations/data/013-wallet-2/new/decryptedNotes.ts, ironfish/src/wallet/database/decryptedNoteValue.ts
This field was renamed in #2125 but not updated in the migration because the migration had not merged yet.
```
[ ] Yes
```
=> Fix migration note index field name

ironfish/src/consensus/verifier.ts
This was dead code
```
[ ] Yes
```
=> Remove unused verifier block hash

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Bumping for the release, with rust changes.
```
[ ] Yes
```
=> Bump versions for release

ironfish-rust/src/proofs/circuit/mint_asset.rs
Fix a unit test due to conflicts in constraint namespace
Updated unit test
```
[ ] Yes
```
=> fix(rust): Fix `test_mint_constraints`

ironfish-rust/src/proofs/circuit/sapling.rs
=> Minor test fixes

ironfish-rust/src/create_asset_note.rs, ironfish-rust/src/creating_asset.rs, ironfish-rust/src/lib.rs, ironfish-rust/src/proofs/circuit/create_asset.rs, ironfish-rust/src/transaction/mod.rs
=> Start adding CreateAssetNote type and related types to abstract complexity

ironfish-cli/src/commands/service/snapshot.ts
the AWS SDK can automatically read credentials from IAM roles or from environment variables. the cli options require these keys to either be set on the command line or in environment variables.
automatically reading credentials from IAM roles attached to an EC2 instance is very convenient for automating service:snapshot since it allows us to run the command without setting keys on a remote instance.
users of service:snapshot can still set each of these variables as environment variables when running the command
- removes options for aws_access_key_id, aws_secret_access_key, region
- updates description for upload option to indicate that AWS credentials must be set in order to upload
local testing with snapshot upload …
=> removes snapshot cli options for aws keys

ironfish/src/wallet/database/accountsdb.ts
=> Remove single operation transaction

ironfish/src/wallet/account.ts
=> Fix missing DB TX in Account.getDecryptedNote()

ironfish-rust/src/proofs/circuit/create_asset.rs, ironfish-rust/src/proofs/notes/creating_asset.rs, ironfish-rust/src/proofs/notes/minting_asset.rs, ironfish-rust/src/transaction/mod.rs
=> feat(rust): Serialize create / mint proofs on transactions

ironfish/src/memPool/memPool.ts
If the transaction already exists in the mempool we want to return early from `addTransaction`. Similarly we want to return early from `deleteTransaction` if the transaction doesn't exist.
Unit tests and local testing
```
[ ] Yes
```
=> Return early for addTransaction and deleteTransaction in the mempool

ironfish-rust/src/note.rs, ironfish-rust/src/primitives/sapling.rs, ironfish-rust/src/proofs/circuit/create_asset.rs, ironfish-rust/src/proofs/circuit/mint_asset.rs, ironfish-rust/src/proofs/notes/create_asset_note.rs, ironfish-rust/src/proofs/notes/creating_asset.rs, ironfish-rust/src/proofs/notes/mint_asset_note.rs, ironfish-rust/src/proofs/notes/minting_asset.rs
=> Some cleanup of new circuit/note code

ironfish-cli/src/commands/chain/download.ts
uses 'tar.list' to asynchronously count the number of files in the snapshot archive and the 'onentry' callback of 'tar.extract' to update a progress bar representing the progress on unzipping the snapshot archive.
```
[ ] Yes
```
=> adds progress bar on snapshot unzip

ironfish/src/mining/pool.ts
Fix https://github.com/iron-fish/ironfish/issues/2215
```
[ ] Yes
```
=> Fix: recalculateTraget bug caused by shallow copy

ironfish-cli/src/commands/accounts/transactions.ts, ironfish/src/rpc/routes/accounts/getTransactions.ts
=> Support hash filter in getTransactions() CLI

ironfish/src/rpc/adapters/tcpAdapter.test.ts
Add back the unit test
```
[ ] Yes
```
=> Add back the unit test

ironfish-rust-nodejs/src/structs/note.rs, ironfish-rust/src/keys/public_address.rs, ironfish-rust/src/merkle_note.rs, ironfish-rust/src/note.rs, ironfish-rust/src/primitives/asset_type.rs, ironfish-rust/src/proofs/circuit/create_asset.rs, ironfish-rust/src/proofs/circuit/mint_asset.rs, ironfish-rust/src/proofs/circuit/sapling.rs, ironfish-rust/src/proofs/notes/mint_asset_note.rs, ironfish-rust/src/proofs/notes/minting_asset.rs, ironfish-rust/src/proofs/notes/mod.rs, ironfish-rust/src/proofs/notes/spendable_note.rs, ironfish-rust/src/spending.rs, ironfish-rust/src/test_util.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/transfer.rs
=> Introduce Note traits

ironfish-rust/src/note.rs, ironfish-rust/src/primitives/asset_type.rs, ironfish-rust/src/proofs/circuit/mint_asset.rs, ironfish-rust/src/spending.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/transfer.rs
=> Add multi-asset value logic to existing Transaction

ironfish-cli/src/commands/accounts/create.ts, ironfish-cli/src/commands/accounts/remove.ts, ironfish-cli/src/commands/accounts/use.ts
Follow up to https://github.com/iron-fish/ironfish/pull/2255. 
- Forgot to update `args.account` in remove.ts
- create.ts & use.ts both need same update
```
[ ] Yes
```
=> Fix account flag

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/index.js, ironfish-rust-nodejs/src/structs/assets.rs, ironfish-rust-nodejs/src/structs/mod.rs, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Closes IRO-2657
```
[ ] Yes
```
=> Add CreateAssetTransaction function to wallet in Typescript

ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.ts
This error is caught below in sendTransaction and coereced into an RPC error
Run existing tests, or try to make a transaction without funds
```
[ ] Yes
```
=> Make Wallet.createTransaction throw NotEnoughFundsError

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/index.js, ironfish-rust-nodejs/src/structs/assets.rs, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust/src/proofs/notes/create_asset_note.rs, ironfish/src/wallet/__fixtures__/wallet.test.ts.fixture, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
=> feat(ironfish,rust): Add mint asset transaction method to wallet

ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Return from functions running in the wallet event loop during shutdown using an AbortController.
```
[ ] Yes
```
=> Fix wallet event loop shutdown

ironfish-cli/package.json, ironfish/package.json
Version bump for the release, generated with version-bump script.
```
[ ] Yes
```
=> Version bump to CLI 48, SDK 25

ironfish-rust/src/common/mod.rs, ironfish-rust/src/common/readwrite.rs, ironfish-rust/src/lib.rs, ironfish-rust/src/note.rs, ironfish-rust/src/primitives/asset_type.rs, ironfish-rust/src/proofs/notes/create_asset_note.rs, ironfish/src/wallet/wallet.test.ts
=> Add ReadWrite Trait, implement for CreateAssetNote

ironfish-rust-nodejs/src/structs/assets.rs, ironfish-rust/src/merkle_note.rs, ironfish-rust/src/notes/minting_asset.rs, ironfish-rust/src/receiving.rs, ironfish/src/blockchain/blockchain.ts, ironfish/src/primitives/note.ts, ironfish/src/primitives/transaction.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
=> Start adding mint description notes to the merkle tree

ironfish-cli/src/commands/start.ts, ironfish/src/rpc/routes/router.ts, ironfish/src/sdk.test.ts, ironfish/src/sdk.ts
Remove protected namespace and clean up the codes
https://github.com/iron-fish/ironfish/pull/2308
unit test 
```
[ ] Yes
```
@NullSoldier
=> Remove protected namespace

ironfish/src/rpc/routes/accounts/getNotes.ts
Another way to use unsignedHash https://github.com/iron-fish/ironfish/pull/2344
```
[ ] Yes
```
=> unsignedHash as notes.transactionHash

ironfish-cli/src/commands/status.ts, ironfish/src/rpc/routes/node/getStatus.ts
Fix the RPC being sent back as a pre-rendered. We should not send back dereived pre-rendered info, and only raw data.
```
[ ] Yes
```
=> Fix prerendered head

ironfish/src/memPool/__fixtures__/feeEstimator.test.ts.fixture, ironfish/src/memPool/feeEstimator.test.ts, ironfish/src/memPool/feeEstimator.ts, ironfish/src/memPool/memPool.ts
renames the module and class to match its function; estimating fees
```
[ ] Yes
```
=> renames RecentFeeCache to FeeEstimator

ironfish-rust-nodejs/package.json
This will now delete the old non workspace target left over in the rust directory.
```
[ ] Yes
```
=> Adds clean stage to rust

ironfish-cli/src/commands/accounts/pay.ts, ironfish-cli/src/commands/deposit-all.ts, ironfish-cli/src/commands/deposit.ts, ironfish/src/rpc/routes/fees/getFees.test.ts, ironfish/src/rpc/routes/fees/getFees.ts
As for `fees/getFees` route, use `bigint` type for calculation, use `string` type for network communication.
```
[ ] Yes
```
=> replace number with string for getFee

ironfish-cli/src/commands/deposit-all.ts
Related to 
https://github.com/iron-fish/ironfish/commit/3de92b29c16080099e975935f0211e00555987b2
Would be nice to rework this command to reuse code from the deposit command, but would take a decent amount of rewrite. I propose we just duplicate since this command will not be used after this phase.
Manual test
```
[ ] Yes
```
=> feat: update deposit-all for increased size

ironfish-cli/src/commands/accounts/transaction.ts, ironfish/src/rpc/routes/accounts/getTransaction.ts, ironfish/src/rpc/routes/accounts/types.ts
Add blockInfo for getTransaction.
```
[ ] Yes
```
=> Add blockInfo for getTransaction

ironfish/src/rpc/routes/fees/estimateFee.ts
`priority` in request data is never used. 
```
[ ] Yes
```
=> Remove unused element

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/spend_proof.rs, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust/src/lib.rs, ironfish-rust/src/spending.rs, ironfish-rust/src/transaction/mod.rs
=> refactor(rust): Rename SpendProof to SpendDescription

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
Version bump for the release, generated with version-bump script.
```
[ ] Yes
```
=> Version bump to CLI 50, SDK 27, rust-nodejs 15

ironfish/src/rpc/routes/chain/__fixtures__/getBlockInfo.test.ts.fixture, ironfish/src/rpc/routes/chain/getBlockInfo.test.ts
Increase code coverage of getBlockInfo
yarn test:coverage:html
yarn lint
```
[ ] Yes
```
=> Increase getBlockInfo coverage to 100%

ironfish-rust/src/assets/asset.rs, ironfish-rust/src/lib.rs, ironfish-rust/src/note.rs, ironfish-rust/src/util.rs, ironfish-zkp/src/lib.rs
- Introduce str_to_array helper for converting strings to fixed size arrays
- De-duplicate group_hash function
- Add some tests for Asset
```
[ ] Yes
```
=> refactor(rust): Minor cleanup and tests for Asset

ironfish/src/rpc/clients/socketClient.ts, ironfish/src/rpc/clients/tlsClient.ts, ironfish/src/utils/error.ts
=> Rpc connect error

ironfish-cli/src/commands/accounts/balance.ts, ironfish/src/utils/currency.ts
This special case function can only confuse people. We should use it in every command or none, so I chose none since it was experimental.
Removing code, no test needed.
```
[x] Yes
```
--ore flag being removed from balance
=> Remove CurrencyUtils.render()

ironfish-cli/src/commands/deposit-all.ts
It looks like we were unintentionally attempting deposits with a negative amount. Changing our check to make sure we have enough balance to send a deposit transaction including the fee
```
[ ] Yes
```
=> Deposit all negative transaction amount

ironfish-rust/src/assets/asset.rs, ironfish-zkp/src/circuits/mint_asset.rs, ironfish-zkp/src/circuits/util.rs
=> feat(rust): add token identifier to asset

ironfish-cli/src/commands/fees.ts, ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/fees/estimateFeeRates.ts
- Dont need to cast the keys
- If RPC has all fields as optional the whole payload can be optional
- Dont need to try catch in a command because that happens in the base command
```
[ ] Yes
```
=> Fee command changes

ironfish/src/syncer.ts
We were unintentionally banning the peer when they timed out during syncing or otherwise failed a request. This is not the worst thing since we want to disconnect from them anyway but we probably don't want to ban them for this
Local testing and unit tests
```
[ ] Yes
```
=> Don't ban peer on sync disconnect

ironfish/src/wallet/account.ts
=> Remove unnecessary wrapper functions

ironfish-cli/src/commands/chain/rewind.ts, ironfish/src/blockchain/blockchain.ts
given a sequence, rewind the chain by disconnecting blocks until the head of the chain is at that sequence.
```
[ ] Yes
```
=> adds chain:rewind command

ironfish/src/network/peerNetwork.ts
Syncing a transaction can be slow since it needs to call decryptNotes and update the wallet state, so we should defer it until after rebroadcasting the transaction to avoid delaying transaction propagation. Additionally, we should only need to sync the transaction once when it's initially accepted to the mempool.
```
[ ] Yes
```
=> Defer syncing transaction until after broadcasting

ironfish-rust/src/assets/asset.rs, ironfish-rust/src/transaction/mints.rs, ironfish-rust/src/transaction/mod.rs, ironfish-zkp/src/circuits/mint_asset.rs, ironfish-zkp/src/circuits/util.rs
=> feat(rust,zkp): Move asset description fields to metadata

ironfish-rust/src/assets/asset.rs, ironfish-rust/src/keys/mod.rs, ironfish-rust/src/transaction/mints.rs
=> refactor(rust,zkp): Change Asset owner public address to asset public key

ironfish-rust/src/assets/asset.rs, ironfish-zkp/src/circuits/mint_asset.rs, ironfish-zkp/src/circuits/util.rs, ironfish-zkp/src/constants.rs
=> refactor(rust,zkp): Use pedersen hash for asset identifier

ironfish-cli/src/commands/chain/hardfork.ts, ironfish-cli/src/commands/chain/repair.ts, ironfish-cli/src/commands/chain/rewind.ts, ironfish-cli/src/commands/start.ts
This will repair your nullifier tree if any nullifier is missing from your index.
```
> ironfish chain:repair
Missing nullifier: block 1745, index: 61266: 37c01607a76994466fc2dd7063ccf167025fc39de9da165c4bc7e5c20ba50d41 (repaired 1)
Missing nullifier: block 2981, index: 168233: a24405e518dd85bcf8605fff9f482554acd0207b1f80e2610e8e5dced0e3d022 (repaired 2)
Missing nullifier: block 7880, index: 419198: f1071ccebc4e39efafa0de183769dd104e1c3ba7085e5766a62143b1abdafb48 (repaired 3)
Missing nullifier: block 9567, index: 571074: 81272d0fd834b7ba573d9c8745a30160d0a82d9424db2283eecb391de6f1fe92 (repaired 4)
Missing nullifier: block 10052, index: 616751: 1a6042c69d2f467f05683b01f2e3bbb085f9381cb5025f7cbd473d9a3f121251 (repaired 5)
Missing nullifier: block 10930, index: 686536: …
```
=> Add repair command

ironfish-rust/src/transaction/mints.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/outputs.rs, ironfish-rust/src/transaction/spending.rs
=> feat(rust): Add value commitment to mint description

.github/workflows/rust_ci.yml, Cargo.lock
See https://github.com/iron-fish/ironfish/actions/runs/3472232298/jobs/5802782533
```
[ ] Yes
```
=> feat(ci): add job to check cargo lockfile

ironfish/src/syncer.ts
We were logging both in getBlocks and outside of it, which creates some confusion around whether there are multiple outgoing requests. I consolidated the log into the getBlocks function, and also passed in the sequence just for the purpose of logging.
```
[ ] Yes
```
=> Remove double-logging from syncer

ironfish-rust/src/transaction/mints.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/spending.rs, ironfish-zkp/src/circuits/mint_asset.rs, ironfish-zkp/src/circuits/util.rs
=> refactor(rust,zkp): Add value commitment to mint circuit, sign mint descriptions

ironfish/src/chainProcessor.test.ts, ironfish/src/chainProcessor.ts
ChainProcessor was failing to update correctly if the head was behind the chain head
Unit tests and local testing
```
[ ] Yes
```
=> Add rewind to chain processor

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> bump versions for v0.1.52

ironfish-rust/src/transaction/mints.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/spending.rs, ironfish-zkp/src/circuits/mint_asset.rs
=> chore(rust,zkp): Add some docs for mint circuit and description

ironfish/src/blockchain/blockchain.ts
This should prevent some re-orging. And we should delete this in the network-reset branch.
```
[ ] Yes
```
=> Encode hard fork into invalid blocks

ironfish/src/blockchain/blockchain.ts, ironfish/src/node.ts, ironfish/src/strategy.test.slow.ts, ironfish/src/strategy.test.ts, ironfish/src/strategy.ts
Need this for adjusting the mining reward using consensus parameters
```
[ ] Yes
```
=> Add consensus parameters to strategy

ironfish-zkp/src/circuits/mint_asset.rs
=> chore(zkp): Add some tests for bad inputs on mint circuit

ironfish/src/fileStores/config.test.ts, ironfish/src/fileStores/config.ts, ironfish/src/fileStores/fileStore.test.ts, ironfish/src/fileStores/keyStore.test.ts, ironfish/src/fileStores/keyStore.ts
If you use any transformers in yup, we don't use the return value. So we can't use things like default(), or trim().
```
[ ] Yes
```
=> Use the assigned schema validation results

.github/workflows/rust_ci.yml, ironfish-zkp/src/circuits/output.rs, ironfish-zkp/src/circuits/spend.rs
=> fix(ci): Make clippy check all targets (tests, bin, etc)

ironfish-cli/src/commands/accounts/repair.ts
only considers transactions expired if the transaction does not have a sequence.
adds repairTransactions function to clear out expired transactions stuck in unexpired state. calls expireTransaction on transaction if it is expired.
```
[ ] Yes
```
=> fixes accounts:repair for expired transactions

ironfish-cli/src/commands/service/sync-transactions.ts
- Print the axios error if there is one
- Add a message indicating were rate limited
- Don't for loop to calculate transactions in the buffer
- Print deposit upload time
I'm running this service locally.
```
[ ] Yes
```
=> Changes to synctransactions service command

ironfish-rust/src/transaction/mints.rs
=> fix(rust): Add value to Mint Description

ironfish-rust-nodejs/src/structs/note.rs, ironfish-rust/src/assets/asset.rs, ironfish-rust/src/assets/mod.rs, ironfish-rust/src/merkle_note.rs, ironfish-rust/src/note.rs, ironfish-rust/src/transaction/burns.rs, ironfish-rust/src/transaction/mints.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/outputs.rs, ironfish-rust/src/transaction/spending.rs, ironfish-rust/src/transaction/tests.rs
=> feat(rust): make Transaction fully multi-asset

ironfish/src/memPool/feeEstimator.test.ts, ironfish/src/memPool/feeEstimator.ts
getPendingTransactionSize currently only adds notes for receives. if there is change left over after the fee then another note needs to be added to return change to the sender.
- adds note size when spender has change
- does not call createSpends a second time when estimating size because it will return the same notes from the first call
- assumes that only one more spend will cover the fee to avoid recursively calling createSpends
- updates test to avoid hardcoded fee
```
[ ] Yes
```
=> adds note for spender change to estimated tx size

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/index.js, ironfish-rust-nodejs/src/structs/asset.rs, ironfish-rust-nodejs/src/structs/mod.rs, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust/src/assets/asset.rs, ironfish/src/primitives/mintDescription.ts, ironfish/src/primitives/transaction.ts
Read mint descriptions from a transaction TS-side.
```
[ ] Yes
```
=> feat(ironfish,rust,rust-nodejs): Add Napi bindings for mint descriptions

ironfish/src/mining/poolMiner.ts, ironfish/src/mining/soloMiner.ts, ironfish/src/mining/utils.ts, ironfish/src/rpc/routes/mining/submitBlock.ts
A few fields weren't updated as a result of 
header changes, so mining isn't working on 
staging. This should fix them up.
```
[X] Yes
```
=> Fix mining resulting from header changes

ironfish/src/primitives/note.ts
=> refactor(ironfish): Read and store Note asset identifier for quicker acces

ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust/src/lib.rs, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/tests.rs
Made some changes in https://github.com/iron-fish/ironfish/pull/2676 but somehow the changes were merged in even though formatting was off
```
[ ] Yes
```
=> fix rust formatting

ironfish/src/fileStores/config.ts
NETWORK RESET PR
Moving database paths to consistent subdirectory as delineated in task:
https://airtable.com/appIXmGgVqP9QdbCf/tblAWSTOQbTq6vh6X/viwHAfsDVPWLk63IW/recswRXAfNGoulBEt?blocks=hide
```
[ ] Yes
```
=> chore: database paths to one folder

ironfish/src/blockchain/blockchain.ts, ironfish/src/blockchain/database/assets.test.ts, ironfish/src/blockchain/database/assets.ts, ironfish/src/blockchain/schema.ts
Persist newly created assets in the blockchain DB.
N/A
```
[ ] Yes
```
=> feat(ironfish): Add assets store to blockchain

ironfish/src/fileStores/config.ts
These are now fields on the config
```
[ ] Yes
```
=> Convert properties to fields

ironfish/src/wallet/account.ts
adds a database transaction to reads from nullifierToNoteHash datastore
```
[ ] Yes
```
=> uses database transaction in `getNoteHash`

ironfish/package.json, ironfish/src/typedefs/bufio.d.ts, ironfish/src/utils/bigint.test.ts, ironfish/src/utils/bigint.ts, yarn.lock
We want to serialize BigInt consistently so adding some serializers for BigInt256 and BigInt128
Unit tests
```
[ ] Yes
```
=> Add serialization of BigInts

ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/primitives/transaction.ts
Adds sender to transaction, will likely need to regenerate fixtures once rust change is in place
```
[ ] Yes
```
=> feat: add sender to transaction ts

ironfish/src/consensus/verifier.ts
Doing a little refactoring to make it easier to understand that miners fee is always the first transaction
```
[ ] Yes
```
=> refactor miners fee check

ironfish-cli/src/commands/start.ts, ironfish/src/blockchain/blockchain.ts
Daniel has a PR to remove the chain:hardfork command, and I think this should be the last remaining code dealing the with bad block.
```
[ ] Yes
```
=> Remove more hard fork code

ironfish/src/consensus/verifier.ts
Removes some out of date references to miners fee in the block header.
```
[ ] Yes
```
=> Remove some incorrect details from Verifier comment

ironfish-rust/src/assets/asset.rs
=> feat(rust): Assets should have a valid non-empty name

ironfish/src/primitives/note.ts
=> refactor(ironfish): Note value deserializes as a bigint

ironfish/src/network/peers/connections/connection.ts, ironfish/src/network/peers/connections/webRtcConnection.ts, ironfish/src/network/peers/connections/webSocketConnection.ts
Removing some comments that mention sending messages as JSON, which we no longer do.
```
[ ] Yes
```
=> Remove incorrect comments from connection code

ironfish-cli/src/commands/chain/benchmark.ts, ironfish/src/blockchain/blockchain.test.ts, ironfish/src/blockchain/blockchain.ts, ironfish/src/blockchain/nullifierSet/nullifierSet.test.ts, ironfish/src/blockchain/nullifierSet/nullifierSet.ts, ironfish/src/consensus/verifier.ts, ironfish/src/genesis/makeGenesisBlock.ts, ironfish/src/memPool/memPool.ts, ironfish/src/mining/manager.ts, ironfish/src/primitives/block.ts, ironfish/src/primitives/transaction.ts, ironfish/src/rpc/routes/chain/followChain.ts, ironfish/src/rpc/routes/chain/getBlock.ts, ironfish/src/rpc/routes/chain/getBlockInfo.ts, ironfish/src/rpc/routes/chain/getTransaction.ts, ironfish/src/rpc/routes/chain/getTransactionStream.ts, ironfish/src/rpc/routes/wallet/getTransactions.ts, ironfish/src/rpc/routes/wallet/types.ts, ironfish/src/strategy.test.slow.ts, ironfish/src/telemetry/telemetry.ts, ironfish/src/testUtilities/helpers/transaction.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts, ironfish/src/workerPool/tasks/createTransaction.test.slow.ts
Some new descriptions didnt return iterators, and some had functions that returned length. None of that matters now since its all just arrays fmor the constructor.
```
[ ] Yes
```
=> Normalize transaction value accessors

ironfish/src/blockchain/blockchain.ts, ironfish/src/migrations/migrator.ts
Array.reverse() will reverse in place, which we don't intend in all of these places.
```
[ ] Yes
```
=> Fix instances of reversing in place

ironfish-rust/src/transaction/spends.rs
=> refactor(rust): Derive clone trait instead of manual implementation

ironfish-rust/src/note.rs, ironfish-zkp/src/circuits/output.rs, ironfish-zkp/src/circuits/spend.rs, ironfish-zkp/src/util.rs, ironfish/src/primitives/transaction.ts
```
[ ] Yes
```
@jowparks @mat-if
=> Clean up for sender address

ironfish-cli/src/commands/accounts/notes.ts, ironfish-cli/src/commands/accounts/transaction.ts
Textual CLI output update
```
[ ] Yes
```
=> feat: change sender output text

ironfish/src/workerPool/tasks/postTransaction.ts
This was using the wrong type for the message.
```
[ ] Yes
```
=> Fix WorkerPool.postTransaction()

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
ironfish-cli 0.1.54 -> 0.1.55
ironfish-rust-nodejs 0.1.17 -> 0.1.18
ironfish 0.0.31 -> 0.0.32
```
[ ] Yes
```
=> ironfish-cli 0.1.54 -> 0.1.55

ironfish-cli/src/commands/accounts/pay.ts, ironfish-cli/src/commands/accounts/repair.ts, ironfish-cli/src/commands/accounts/transactions.ts, ironfish/src/consensus/verifier.ts, ironfish/src/fileStores/config.ts, ironfish/src/memPool/memPool.ts, ironfish/src/mining/manager.ts, ironfish/src/primitives/rawTransaction.test.ts, ironfish/src/primitives/rawTransaction.ts, ironfish/src/primitives/transaction.ts, ironfish/src/rpc/routes/chain/getTransaction.ts, ironfish/src/rpc/routes/transactions/sendTransaction.test.ts, ironfish/src/rpc/routes/transactions/sendTransaction.ts, ironfish/src/rpc/routes/wallet/getTransactions.ts, ironfish/src/rpc/routes/wallet/types.ts, ironfish/src/wallet/account.test.ts, ironfish/src/wallet/account.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.ts, ironfish/src/wallet/walletdb/walletdb.ts, ironfish/src/workerPool/pool.ts, ironfish/src/workerPool/tasks/createTransaction.ts, ironfish/src/workerPool/tasks/postTransaction.test.ts
Only for JS, rust coming next.
```
[ ] Yes
```
=> Rename expirationSequence -> expiration in JS 

ironfish-cli/src/commands/accounts/pay.ts, ironfish/src/rpc/routes/transactions/sendTransaction.ts
Add `assetIdentifier` as a flag in `pay` command
Manual test
```
[ ] Yes
```
=> feat(cli): Add `assetIdentifier` to pay command

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust-nodejs/tests/demo.test.slow.ts, ironfish-rust/src/transaction/mod.rs, ironfish-rust/src/transaction/tests.rs, ironfish/src/primitives/rawTransaction.ts, ironfish/src/wallet/walletdb/walletdb.ts, ironfish/src/workerPool/tasks/createTransaction.ts
This makes the rust side match the JS side
```
[ ] Yes
```
=> Rename expirationSequence -> expiration in RS

ironfish-cli/src/commands/assets/mint.ts, ironfish-cli/src/commands/wallet/mint.ts
Add a CLI command to mint an asset
Manual test
```
[ ] Yes
```
=> feat(cli): Introduce `assets:mint` CLI command

ironfish-cli/src/commands/accounts/pay.ts
Show the asset identifier if available
Manual test
```
[ ] Yes
```
=> feat(cli): Show asset identifier for amount being paid instead of $IRON

ironfish-cli/src/commands/accounts/repair.ts
now that an account's stored balance only reflects transactions on chain it is not feasible to recompute the balance only from an account's decrypted notes. we should not include spent notes in the balance, but we don't currently have an efficient way to determine if the note was spent in a transaction that is on the chain or in a transaction that is pending.
we can still make some repairs to the spent attribute stored on the note, so the old implementation of `repairBalance` processes notes without updating balance and is renamed `repairNotes`.
future changes to better support recomputing the balance:
- add sequence and block hash to balance store to allow incremental updates to balance
- add balance delta to transactions to avoid iterating over all notes and spends
- add an index from …
=> removes balance repair from accounts:repair

ironfish-cli/src/commands/accounts/transactions.ts, ironfish/src/rpc/routes/wallet/getTransactions.ts, ironfish/src/rpc/routes/wallet/types.ts
=> Display Mints and Burns for accounts:transactions

ironfish-cli/src/commands/accounts/transactions.ts
The longest status is `unconfirmed` so without this the rows get really unalligneds.
```
[ ] Yes
```
=> Extend status column to 12

ironfish-cli/src/commands/accounts/notes.ts, ironfish/src/rpc/routes/wallet/getNotes.ts
This renamed a field on the note incorrectly
```
[ ] Yes
```
=> Change RPC note.amount to be value

ironfish/src/blockchain/blockchain.test.ts, ironfish/src/testUtilities/fixtures.ts, ironfish/src/testUtilities/helpers/transaction.ts
This new fixture is useful to create a block with a mint in it
```
[ ] Yes
```
=> Add useMintBlockFixture for tests

ironfish/src/rpc/routes/assets/mint.ts, ironfish/src/wallet/wallet.ts
Add expiration arguments for consistency with other wallet methods
N/A
```
[ ] Yes
```
=> feat(ironfish): Update mint arguments to be consistent with pay

ironfish/src/rpc/clients/client.ts, ironfish/src/rpc/routes/router.ts, ironfish/src/rpc/routes/transactions/sendTransaction.ts
This is the only RPC call inside of this namespace
```
[ ] Yes
```
=> Merge transaction namespace into wallet RPC namespace

ironfish-cli/package.json, ironfish-cli/src/commands/accounts/create.ts, ironfish-cli/src/commands/accounts/import.ts, ironfish-cli/src/commands/accounts/pay.ts, ironfish-cli/src/commands/accounts/remove.ts, ironfish-cli/src/commands/faucet.ts, ironfish-cli/src/commands/testnet.ts, yarn.lock
This adds a fix I commited to oclif/core to fix the prompt return type released in 1.20.1 here, https://github.com/oclif/core/releases/tag/1.20.1
```
> ironfish fees
Fee Rates ($ORE/kB)
low:    1
medium: 1
high:   1
```
```
[ ] Yes
```
=> Upgrading oclif/core to 1.23.1

ironfish-cli/src/commands/accounts/address.ts, ironfish-cli/src/commands/accounts/index.ts, ironfish-cli/src/commands/accounts/status.ts, ironfish-cli/src/commands/chain/benchmark.ts, ironfish-cli/src/commands/chain/readd-block.ts, ironfish-cli/src/commands/config/index.ts, ironfish-cli/src/commands/migrations/index.ts, ironfish-cli/src/commands/peers/index.ts, ironfish-cli/src/commands/service/sync-masp-transactions.ts
Grep for aliases in the cli and remove.
`yarn test` successful.
```
[ ] Yes
[x] No
```
=> Kill CLI aliases.

ironfish-cli/src/commands/accounts/send.ts, ironfish/src/rpc/routes/wallet/__fixtures__/sendTransaction.test.ts.fixture, ironfish/src/rpc/routes/wallet/sendTransaction.test.ts, ironfish/src/rpc/routes/wallet/sendTransaction.ts, ironfish/src/testUtilities/fixtures.ts, ironfish/src/wallet/__fixtures__/wallet.test.slow.ts.fixture, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.ts
Skylar says no one uses the phrase "pay" to describe this, it should be described as send().
```
[ ] Yes
```
=> Rename Wallet.pay() -> Wallet.send()

ironfish/src/testUtilities/fixtures/account.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/testUtilities/fixtures/fixture.ts, ironfish/src/testUtilities/fixtures/index.ts, ironfish/src/testUtilities/fixtures/transactions.ts
Started to clean up these fixtures by moving them into distinct folders.
```
[ ] Yes
```
=> Move fixtures into distinct folders

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump versions

ironfish/src/network/version.ts
=> Bump p2p protocol version to 19

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump to version CLI 0.1.57 and SDK 0.1.20

ironfish/src/wallet/wallet.ts
https://github.com/iron-fish/ironfish/pull/2867/files#r1065203567
N/A
```
[ ] Yes
```
=> refactor(ironfish): Remove destructure in `wallet.getBalances`

package.json, yarn.lock
=> chore: pin a couple nodejs transitive dependencies for security fixes

.github/workflows/rust_ci.yml, .github/workflows/rust_ci_cache.yml
=> fix(ci): Add more rust-related file triggers for the Rust CI

ironfish-cli/src/commands/service/sync-multi-asset.ts, ironfish/src/webApi.ts
Cleaning up API naming in `ironfish`
```
[ ] Yes
```
=> chore: cleanup web api

ironfish/src/blockchain/blockchain.ts, ironfish/src/migrations/data/014-blockchain.ts, ironfish/src/migrations/data/015-wallet.ts, ironfish/src/migrations/data/index.ts, ironfish/src/wallet/walletdb/walletdb.ts
This will prevent people from running into errors in Phase 3
```
[ ] Yes
```
=> Bump database migration versions

ironfish-cli/src/commands/backup.ts, ironfish-cli/src/commands/reset.ts, ironfish/src/fileStores/config.ts, ironfish/src/migrations/data/015-wallet.ts, ironfish/src/node.ts
Fixing places that still refer to to the wallet DB as account DB
```
[ ] Yes
```
=> Fix references to account DB

ironfish-cli/src/commands/wallet/send.ts
Updates references to `account` to say `wallet`
```
[ ] Yes
```
=> chore: update send command consistent

ironfish-cli/src/commands/wallet/balances.ts, ironfish/src/rpc/routes/wallet/getBalances.test.ts, ironfish/src/rpc/routes/wallet/getBalances.ts
* Update request `account` to be optional
* Return `account` name
* Add CLI command
```sh
λ ironfish wallet:balances
Account: default
Asset Name Asset Id                                                         Confirmed Balance
────────── ──────────────────────────────────────────────────────────────── ─────────────────
rohan      0d69819630f69b17b0c566bd258868e1796baee360f4839fdf1e90df35881aea 0.00000000
$IRON      d7c86706f5817aa718cd1cfad03233bcd64a7789fd9422d3b17af6823a7e6ac6 60.00000000
✨  Done in 5.32s.
```
```sh
λ ironfish wallet:balances --all
Account: default
Asset Name Asset Id                                                         Confirmed Balance Unconfirmed Balance Head Hash                                                        Head Sequence
────────── …
```
=> feat(cli,ironfish): Add `wallet:balances` command

ironfish/src/rpc/routes/wallet/getBalance.ts, ironfish/src/rpc/routes/wallet/getBalances.ts, ironfish/src/wallet/wallet.ts
Also the underlying code already does this sanitization just in case
```
[ ] Yes
```
=> Add RPC validation to confirmations

ironfish/src/wallet/account.ts
This will help keep the balance model intact and create less variables
```
[ ] Yes
```
=> Reduce destructuring balance model

CONTRIBUTING.md, ironfish/src/fileStores/config.ts
Changing to a link we control so we don't have to worry about it breaking
```
[ ] Yes
```
=> chore: update Discord invite link

ironfish-rust/src/rolling_filter.rs, ironfish-zkp/src/circuits/mint_asset.rs, rust-toolchain.toml
Easy perf wins (between 6-10% on transactions), and a couple lint fixes from new lints
```
STAGING - 100 samples
--- 
transactions/transaction simple
time:   [1.1441 s 1.1498 s 1.1558 s]
transactions/transaction multiasset
time:   [1.6546 s 1.6633 s 1.6728 s]
1.66.1 - 100 samples
---
transactions/transaction simple
time:   [1.0410 s 1.0462 s 1.0515 s]
change: [-9.6515% -9.0084% -8.3321%] (p = 0.00 < 0.05)
Performance has improved.
transactions/transaction multiasset
time:   [1.5435 s 1.5520 s 1.5613 s]
change: [-7.4691% -6.6904% -5.9807%] (p = 0.00 < 0.05)
Performance has improved.
1.66.1 - 30 samples
---
transactions/transaction simple
time:   [1.0303 s 1.0381 s 1.0467 s]
change: [-1.7026% -0.7805% +0.1816%] (p = 0.14 > 0.05)
No change in performance detected.
transactions/transaction …
```
=> chore(rust): Upgrade rust version to 1.66.1

ironfish-cli/package.json, ironfish-rust-nodejs/npm/darwin-arm64/package.json, ironfish-rust-nodejs/npm/darwin-x64/package.json, ironfish-rust-nodejs/npm/linux-arm64-gnu/package.json, ironfish-rust-nodejs/npm/linux-arm64-musl/package.json, ironfish-rust-nodejs/npm/linux-x64-gnu/package.json, ironfish-rust-nodejs/npm/linux-x64-musl/package.json, ironfish-rust-nodejs/npm/win32-x64-msvc/package.json, ironfish-rust-nodejs/package.json, ironfish/package.json
=> Bump CLI 0.1.58, SDK 0.0.35, Rust 0.1.21

ironfish-rust-nodejs/index.d.ts, ironfish-rust-nodejs/src/structs/transaction.rs, ironfish-rust/src/transaction/mod.rs, ironfish/src/strategy.test.slow.ts
This is vestige code from when we were introducing sender
```
[ ] Yes
```
=> chore: removing sender from proposed transaction, no longer needed

ironfish-cli/src/commands/miners/start.ts
This removes the need to use the `-a`/`--address` flag
```
[ ] Yes
```
=> feat(cli): Pool miner will now load the default public address

ironfish-cli/src/commands/wallet/balances.ts
=> fix(cli): Add table flags to `wallet:balances`

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts
Use fee in $IRON for mint and burn
```
[ ] Yes
```
=> fix(cli): Make `fee` denomination in mint/burn consistent with send

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts
Pull default account and make argument optional to be consistent with send
Manually run
```
[ ] Yes
```
=> fix(cli): Make account optional for mint and burn

ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/testUtilities/fixtures/transactions.ts, ironfish/src/testUtilities/helpers/transaction.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
Refactor create transaction, clean up duplicate codes
existing unit tests
```
[ ] Yes
```
@NullSoldier @hughy
=> Wallet create transaction cleanup

ironfish/src/primitives/transaction.test.slow.ts, ironfish/src/rpc/routes/wallet/mintAsset.test.ts, ironfish/src/rpc/routes/wallet/postTransaction.ts, ironfish/src/testUtilities/fixtures/blocks.ts, ironfish/src/testUtilities/fixtures/transactions.ts, ironfish/src/wallet/wallet.test.slow.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
refactor post transaction and clean up duplicate codes
```
[ ] Yes
```
@NullSoldier @hughy
=> Post transaction cleanup

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts
Add more examples with long-form arguments for mint and burn commands
```
[ ] Yes
```
=> chore(cli): Add more examples for mint / burn CLI

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/mint.ts, ironfish/src/rpc/routes/wallet/burnAsset.test.ts, ironfish/src/rpc/routes/wallet/burnAsset.ts
Make amounts consistent with send
Manual test
```
[ ] Yes
```
=> fix(cli): Update amount denominations in mint/burn to be IRON

ironfish/src/rpc/routes/wallet/mintAsset.ts, ironfish/src/wallet/interfaces/mintAssetOptions.ts, ironfish/src/wallet/wallet.test.ts, ironfish/src/wallet/wallet.ts
=> Remove transaction prefix from obviously tx things

ironfish-cli/src/commands/wallet/burn.ts
Add interactive mode to burn command
https://user-images.githubusercontent.com/5459049/212980877-fefa7990-22e8-45fa-9043-3d85a3708142.mp4
```
[ ] Yes
```
=> feat(cli): Add interactive mode to burn

ironfish/src/wallet/wallet.ts
=> fixes comparison for transaction type

ironfish-cli/src/commands/wallet/burn.ts, ironfish-cli/src/commands/wallet/send.ts, ironfish-cli/src/utils/asset.ts, ironfish-cli/src/utils/index.ts
=> feat(cli): add asset selector to burn command

ironfish-cli/src/commands/wallet/mint.ts
~~Builds on #2955~~
```
[ ] Yes
```
=> feat(cli): Add asset selector to the mint command

ironfish-cli/src/commands/wallet/burn.ts
This wouldn't let you enter pass the fee.
```
[ ] Yes
```
=> Allow default fee in burn

ironfish-cli/src/commands/wallet/mint.ts
you couldn't press enter to accept the default fee.
```
[ ] Yes
```
=> Allow default fee in mint

ironfish-cli/README.md, ironfish-cli/src/commands/faucet.ts, ironfish-cli/src/commands/wallet/create.ts, ironfish-cli/src/commands/wallet/import.ts, ironfish-cli/src/commands/wallet/repair.ts, ironfish-cli/src/commands/wallet/which.ts, ironfish/src/rpc/routes/wallet/utils.ts
Changes a number of instances of outdated documentation 
```
[ ] Yes
```
=> accounts -> wallet

ironfish-cli/package.json, ironfish/package.json
Bumping versions for the release.
```
[ ] Yes
```
=> Version bump CLI 0.1.60, SDK 0.0.37

ironfish-cli/package.json, ironfish/package.json
=> Version bump

ironfish-cli/src/commands/service/faucet.ts
=> fix(cli): faucet service now checks public address validity

ironfish-cli/src/commands/wallet/send.ts
=> Fix: minor typo
